(C Code, RLOOP, Hover Engine Thermal Management Ssystem): HE_THERM__ETHERNET
HE_THERM__ETHERNET
RLOOP » HE_THERM
Functions
void vHETHERM_ETH__Transmit (E_NET__PACKET_T ePacketType)
Transmit an eth packet.
void vHETHERM_ETH__Init (void)
Configure the ethernet.
void vHETHERM_ETH__Process (void)
Process any ethernet tasks.
Luint8 u8HETHERM_ETH__Is_LinkUp (void)
Do we have an ethernet Link?
void vHETHERM_ETH__RxUDP (Luint8 *pu8Buffer, Luint16 u16Length, Luint16 u16DestPort)
RX a UDP packet from the eth.
void vHETHERM_ETH__RxSafeUDP (Luint8 *pu8Payload, Luint16 u16PayloadLength, Luint16 ePacketType, Luint16 u16DestPort, Luint16 u16Fault)
Rx a processed safety UDP packet.
void vHETHERM_ETH__10MS_ISR (void)
ToDo.
Variables
TS_HET__MAIN sHET
Detailed Description
Function Documentation
Luint8 u8HETHERM_ETH__Is_LinkUp (void)
Do we have an ethernet Link?
SafeTool Function MD5:
4474B73CA898BC1EBD8846EDF0AFD603
SafeTool Function ID:
LCCM721R0.FILE.008.FUNC.003
Referenced by vHETHERM_ETH__Process().
void vHETHERM_ETH__10MS_ISR (void)
ToDo.
SafeTool Function MD5:
099C8D3267F59EF7222870AFF99AF776
SafeTool Function ID:
LCCM721R0.FILE.008.FUNC.007
References TS_HET__MAIN::sUDPDiag, TS_HET__MAIN::u810MS_Flag, and TS_HET__MAIN::u8250MS_Flag.
Referenced by vHETHERM_TIMERS__10MS_ISR().
void vHETHERM_ETH__Init (void)
Configure the ethernet.
SafeTool Function MD5:
356CC0ED787767665FCA45C57EA6C650
SafeTool Function ID:
LCCM721R0.FILE.008.FUNC.001
References TS_HET__MAIN::eTxStreamingType, TS_HET__MAIN::sEthernet, TS_HET__MAIN::sUDPDiag, TS_HET__MAIN::u810MS_Flag, TS_HET__MAIN::u8250MS_Flag, TS_HET__MAIN::u8IPAddx, and TS_HET__MAIN::u8MACAddx.
Referenced by vHETHERM__Init().
void vHETHERM_ETH__Process (void)
Process any ethernet tasks.
SafeTool Function MD5:
A84E095D906D5A68D00AB43BCE650174
SafeTool Function ID:
LCCM721R0.FILE.008.FUNC.002
References TS_HET__MAIN::eTxStreamingType, TS_HET__MAIN::sUDPDiag, TS_HET__MAIN::u810MS_Flag, TS_HET__MAIN::u8250MS_Flag, u8HETHERM_ETH__Is_LinkUp(), and vHETHERM_ETH__Transmit().
Referenced by vHETHERM__Process().
void vHETHERM_ETH__RxSafeUDP (Luint8 * pu8Payload, Luint16 u16PayloadLength, Luint16 ePacketType, Luint16 u16DestPort, Luint16 u16Fault)
Rx a processed safety UDP packet.
Parameters
[in] u16Fault Faults during packet processing?
[in] u16DestPort Destination port
[in] ePacketType Type of packet
[in] u16PayloadLength Total payload length
[in] *pu8Payload Pointer to the payload
SafeTool Function MD5:
195DB0CCCB84AC31FBE01D64C6E1D265
SafeTool Function ID:
LCCM721R0.FILE.008.FUNC.005
Manual control of the solenoids
References vHETHERM_SOL__Close(), and vHETHERM_SOL__Open().
void vHETHERM_ETH__RxUDP (Luint8 * pu8Buffer, Luint16 u16Length, Luint16 u16DestPort)
RX a UDP packet from the eth.
Parameters
[in] u16DestPort Destination port addx.
[in] u16Length Packet Length
[in] *pu8Buffer Pointer to data
SafeTool Function MD5:
5141B6243B3AFF96ACBA45D78D544C21
SafeTool Function ID:
LCCM721R0.FILE.008.FUNC.004
void vHETHERM_ETH__Transmit (E_NET__PACKET_T ePacketType)
Transmit an eth packet.
Parameters
[in] ePacketType Packet type
SafeTool Function MD5:
97C946B3B25E3E39512A42F8D3619F4E
SafeTool Function ID:
LCCM721R0.FILE.008.FUNC.006
References TS_HET__MAIN::sBrake, TS_HET__MAIN::sBrakeMotor, TS_HET__MAIN::sLeft, TS_HET__MAIN::sLeftHE, TS_HET__MAIN::sMotorTemp, TS_HET__MAIN::sRight, TS_HET__MAIN::sRightHE, and TS_HET__MAIN::sSol.
Referenced by vHETHERM_ETH__Process().
Variable Documentation
TS_HET__MAIN sHET