(C Code, RLOOP, Hover Engine Thermal Management Ssystem): HE_THERM__CORE
HE_THERM__CORE
RLOOP » HE_THERM
Functions
void vHETHERM__Init (void)
Init the HE thermal system.
void vHETHERM__Process (void)
Process any HE thermal tasks.
Variables
TS_HET__MAIN sHET
Detailed Description
Function Documentation
void vHETHERM__Init (void)
Init the HE thermal system.
SafeTool Function MD5:
A8D73F006B09664F71BEA2CC99FC9A71
SafeTool Function ID:
LCCM721R0.FILE.000.FUNC.001
References vHETHERM_ETH__Init(), vHETHERM_SOL__Init(), and vHETHERM_TC__Init().
void vHETHERM__Process (void)
Process any HE thermal tasks.
SafeTool Function MD5:
7195AD6FA2AC38B07BBADC93B11065D8
SafeTool Function ID:
LCCM721R0.FILE.000.FUNC.002
References vHETHERM_ETH__Process(), vHETHERM_SOL__Process(), and vHETHERM_TC__Process().
Variable Documentation
TS_HET__MAIN sHET