(C Code, RLOOP, Hover Engine Thermal Management Ssystem): HE_THERM__SOLENOIDS
HE_THERM__SOLENOIDS
RLOOP » HE_THERM
Functions
void vHETHERM_SOL__Init (void)
Configure the solenoids.
void vHETHERM_SOL__Process (void)
Process any solenoid tasks.
void vHETHERM_SOL__Open (Luint8 u8Index)
Open the sol, allowing gas to flow.
void vHETHERM_SOL__Close (Luint8 u8Index)
Close the solenoid, blocking gas.
Variables
TS_HET__MAIN sHET
Detailed Description
Function Documentation
void vHETHERM_SOL__Close (Luint8 u8Index)
Close the solenoid, blocking gas.
Parameters
[in] u8Index Solenoid index
SafeTool Function MD5:
D7BE4EAF87B58E720135FB17823121B5
SafeTool Function ID:
LCCM721R0.FILE.007.FUNC.004
Referenced by vHETHERM_ETH__RxSafeUDP(), and vHETHERM_SOL__Init().
void vHETHERM_SOL__Init (void)
Configure the solenoids.
SafeTool Function MD5:
59DBB43CE132BA87912FB75CD265A819
SafeTool Function ID:
LCCM721R0.FILE.007.FUNC.001
References TS_HET__MAIN::sBrake, TS_HET__MAIN::sLeft, TS_HET__MAIN::sRight, TS_HET__MAIN::sSol, and vHETHERM_SOL__Close().
Referenced by vHETHERM__Init().
void vHETHERM_SOL__Open (Luint8 u8Index)
Open the sol, allowing gas to flow.
Parameters
[in] u8Index Sol index
SafeTool Function MD5:
8F236426AF33C5B02788F538BB543678
SafeTool Function ID:
LCCM721R0.FILE.007.FUNC.003
Referenced by vHETHERM_ETH__RxSafeUDP().
void vHETHERM_SOL__Process (void)
Process any solenoid tasks.
SafeTool Function MD5:
265F046D0ED65D916A38798F54F7F828
SafeTool Function ID:
LCCM721R0.FILE.007.FUNC.002
References TS_HET__MAIN::sBrake, TS_HET__MAIN::sBrakeMotor, TS_HET__MAIN::sLeft, TS_HET__MAIN::sLeftHE, TS_HET__MAIN::sMotorTemp, TS_HET__MAIN::sRight, TS_HET__MAIN::sRightHE, and TS_HET__MAIN::sSol.
Referenced by vHETHERM__Process().
Variable Documentation
TS_HET__MAIN sHET