(C Code, MULTICORE, DS18B20 Temperature Sensor): DS18B20__ADDRESS
DS18B20__ADDRESS
MULTICORE » DS18B20
Functions
void vDS18B20_ADDX__Init (void)
Init the addressing module.
Lint16 s16DS18B20_ADDX__Search (void)
Search for all devices on the bus on all channels.
void vDS18B20_ADDX__SearchSM_Start (void)
Start the search.
void vDS18B20_ADDX__SearchSM_Process (void)
State machine based search processing.
Lint16 s16DS18B20_ADDX__Upload_Addx (Luint16 u16SensorIndex, Luint8 u8ChannelIndex, Luint8 *pu8Addx)
Manually upload an address into the device table.
Luint16 u16DS18B20_ADDX__Get_NumEnumerated (void)
Returns the number of enumerated devices.
void vDS18B20_ADDX__Set_SearchComplete (void)
Luint8 u8DS18B20_ADDX__SearchSM_IsBusy (void)
Checks to see if the search state machine is busy or not.
Variables
struct _strDS18B20 sDS18B20
Detailed Description
Function Documentation
Lint16 s16DS18B20_ADDX__Search (void)
Search for all devices on the bus on all channels.
Note
This is a single blocking function that will try and search for everything via binary tree searching of the ROM ID's. THIS IS VERY SLOW. Several hundred sensors can take minutes to search. If this is a problem, use the state machine based search.
SafeTool Function MD5:
03D56F57CC4B53C6E8DDFB5E41E53B27
SafeTool Function ID:
LCCM644R0.FILE.006.FUNC.001
References _strDS18B20::f32Temperature, s16DS18B20_SEARCH__SearchFirstDevice(), s16DS18B20_SEARCH__SearchNextDevice(), s16DS18B20_TEMP__Get_Resolution(), _strDS18B20::sDevice, sDS18B20, _strDS18B20::sEnum, _strDS18B20::sSearch, _strDS18B20::sTemp, _strDS18B20::u16NumDevices, _strDS18B20::u8ChannelIndex, _strDS18B20::u8FirstSearched, _strDS18B20::u8Resolution, _strDS18B20::u8SearchCompleted, and _strDS18B20::u8SerialNumber.
Lint16 s16DS18B20_ADDX__Upload_Addx (Luint16 u16SensorIndex, Luint8 u8ChannelIndex, Luint8 * pu8Addx)
Manually upload an address into the device table.
Note
WARNING: Addresses must be loaded incrementally from 0 to n. This function Will set the maximum enumerated index as +1 from the last supplied index
Parameters
[in] *pu8Addx Pointer to the ROM ID
[in] u8ChannelIndex The 1-wire channel (0 ro 1)
[in] u16SensorIndex The index in the device table.
Returns
0 = success
-ve = error
SafeTool Function MD5:
C5F366E226D6FBF235ACD5DE610D696C
SafeTool Function ID:
LCCM644R0.FILE.006.FUNC.006
References _strDS18B20::sDevice, sDS18B20, _strDS18B20::sEnum, _strDS18B20::u16NumDevices, _strDS18B20::u8ChannelIndex, and _strDS18B20::u8SerialNumber.
Luint16 u16DS18B20_ADDX__Get_NumEnumerated (void)
Returns the number of enumerated devices.
Returns
The num enumerated, or manually added devices
SafeTool Function MD5:
78A160EF3A561E598B4CEED556011A47
SafeTool Function ID:
LCCM644R0.FILE.006.FUNC.007
References sDS18B20, _strDS18B20::sEnum, and _strDS18B20::u16NumDevices.
Luint8 u8DS18B20_ADDX__SearchSM_IsBusy (void)
Checks to see if the search state machine is busy or not.
Returns
1 = We are busy
0 = Not busy / Idle
SafeTool Function MD5:
E720061D5D7EB748E726EFDCFBCD7CB4
SafeTool Function ID:
LCCM644R0.FILE.006.FUNC.005
References sDS18B20, SEARCH_STATE__IDLE, _strDS18B20::sSearch, and _strDS18B20::sSearchState.
void vDS18B20_ADDX__Init (void)
Init the addressing module.
SafeTool Function MD5:
035167D86A5C1B6A0F972794E0D0E221
SafeTool Function ID:
LCCM644R0.FILE.006.FUNC.002
References sDS18B20, SEARCH_STATE__IDLE, _strDS18B20::sSearch, _strDS18B20::sSearchState, _strDS18B20::u8FirstSearched, _strDS18B20::u8SearchCompleted, and _strDS18B20::u8WireChannelCounter.
Referenced by vDS18B20__Init().
void vDS18B20_ADDX__SearchSM_Process (void)
State machine based search processing.
SafeTool Function MD5:
43A0A3E0F1548582B19735246BA11219
SafeTool Function ID:
LCCM644R0.FILE.006.FUNC.004
References _strDS18B20::f32Temperature, s16DS18B20_SEARCH__SearchFirstDevice(), s16DS18B20_SEARCH__SearchNextDevice(), _strDS18B20::sDevice, sDS18B20, SEARCH_STATE__CLEANUP, SEARCH_STATE__IDLE, SEARCH_STATE__INC_CHANNEL, SEARCH_STATE__RUN, SEARCH_STATE__START, _strDS18B20::sEnum, _strDS18B20::sSearch, _strDS18B20::sSearchState, _strDS18B20::sTemp, _strDS18B20::u16NumDevices, _strDS18B20::u8ChannelIndex, _strDS18B20::u8FirstSearched, _strDS18B20::u8Resolution, _strDS18B20::u8SearchCompleted, _strDS18B20::u8SerialNumber, and _strDS18B20::u8WireChannelCounter.
Referenced by vDS18B20__Process().
void vDS18B20_ADDX__SearchSM_Start (void)
Start the search.
SafeTool Function MD5:
24F9B9296E21F4BD8177F4D713AB4017
SafeTool Function ID:
LCCM644R0.FILE.006.FUNC.003
References sDS18B20, SEARCH_STATE__IDLE, SEARCH_STATE__START, _strDS18B20::sSearch, and _strDS18B20::sSearchState.
void vDS18B20_ADDX__Set_SearchComplete (void)
References sDS18B20, _strDS18B20::sSearch, and _strDS18B20::u8SearchCompleted.
Variable Documentation
struct _strDS18B20 sDS18B20
Referenced by s16DS18B20_ADDX__Search(), s16DS18B20_ADDX__Upload_Addx(), u16DS18B20_ADDX__Get_NumEnumerated(), u8DS18B20_ADDX__SearchSM_IsBusy(), vDS18B20_ADDX__Init(), vDS18B20_ADDX__SearchSM_Process(), vDS18B20_ADDX__SearchSM_Start(), and vDS18B20_ADDX__Set_SearchComplete().