(C Code, MULTICORE, DS18B20 Temperature Sensor): DS18B20__SCRATCHPAD
DS18B20__SCRATCHPAD
MULTICORE » DS18B20
Functions
Lint16 s16DS18B20_SCRATCH__Write (Luint16 u16SensorIndex, const Luint8 *pu8Scratch)
Write to the scratch pad, and then commit to the device.
Lint16 s16DS18B20_SCRATCH__Read (Luint16 u16SensorIndex, Luint8 *pu8Scratch)
Read the scratch memory, 9 bytes.
Luint8 u8DS18B20_SCRATCH__Compute_CRC (Luint8 *pu8Scratch)
compute the CRC on the scratch pad
Variables
struct _strDS18B20 sDS18B20
Detailed Description
Function Documentation
Lint16 s16DS18B20_SCRATCH__Read (Luint16 u16SensorIndex, Luint8 * pu8Scratch)
Read the scratch memory, 9 bytes.
Note
The DSIndex must be a valid already searched or already known ROM serial number.
Scratchpad Byte Allocation: 0: Temperature LSB 1: Temperature MSB 2: High alarm temp 3: Low alarm temp 4: DS18S20: store for crc DS18B20 & DS1822: configuration register 5: Internal use & crc 6: DS18S20: COUNT_REMAIN DS18B20 & DS1822: store for crc 7: DS18S20: COUNT_PER_C DS18B20 & DS1822: store for crc 8: SCRATCHPAD_CRC
Parameters
[in] *pu8Scratch Pointer to return scratchpad memory.
[in] u16SensorIndex The index of the DS2482 device ROM serial number
Returns
0 = success
-ve = error
SafeTool Function MD5:
F5C21A2413EB188C980C35D9929417EC
SafeTool Function ID:
LCCM644R0.FILE.004.FUNC.001
References C_DS18B20__SCRATCHPAD_SIZE, s16DS18B20_1WIRE__Generate_Reset(), s16DS18B20_1WIRE__ReadByte(), s16DS18B20_1WIRE__SelectDevice(), s16DS18B20_1WIRE__WriteByte(), _strDS18B20::sDevice, sDS18B20, _strDS18B20::u8ChannelIndex, u8DS18B20_SCRATCH__Compute_CRC(), and _strDS18B20::u8SerialNumber.
Referenced by s16DS18B20_TEMP__Get_Resolution(), s16DS18B20_TEMP__Get_UserID(), s16DS18B20_TEMP__Read(), s16DS18B20_TEMP__Request(), and s16DS18B20_TEMP__Set_Resolution().
Lint16 s16DS18B20_SCRATCH__Write (Luint16 u16SensorIndex, const Luint8 * pu8Scratch)
Write to the scratch pad, and then commit to the device.
Parameters
[in] *pu8Scratch Buffer holding scratchpad data
[in] u16SensorIndex Address index
Returns
0 = success
-ve = error
SafeTool Function MD5:
0F8658952A33463C9CEB88D97FF1A6EE
SafeTool Function ID:
LCCM644R0.FILE.004.FUNC.002
References s16DS18B20_1WIRE__Generate_Reset(), s16DS18B20_1WIRE__SelectDevice(), s16DS18B20_1WIRE__WriteByte(), _strDS18B20::sDevice, sDS18B20, _strDS18B20::u8ChannelIndex, _strDS18B20::u8SerialNumber, and vDS18B20_DELAYS__Delay_mS().
Referenced by s16DS18B20_TEMP__Set_Resolution().
Luint8 u8DS18B20_SCRATCH__Compute_CRC (Luint8 * pu8Scratch)
compute the CRC on the scratch pad
Note
http://pdfserv.maximintegrated.com/en/an/AN27.pdf
Parameters
[in] *pu8Scratch Pointer to the scratch ram buffer
Returns
The computed CRC
SafeTool Function MD5:
AEAF986D7CBDBAA8D8CD0B4C903D15DE
SafeTool Function ID:
LCCM644R0.FILE.004.FUNC.003
Referenced by s16DS18B20_SCRATCH__Read(), and s16DS18B20_TEMP__Set_Resolution().
Variable Documentation
struct _strDS18B20 sDS18B20
Referenced by s16DS18B20_SCRATCH__Read(), and s16DS18B20_SCRATCH__Write().