(C Code, MULTICORE, DS18B20 Temperature Sensor): DS18B20__TEMPERATURE
DS18B20__TEMPERATURE
MULTICORE » DS18B20
Functions
static void vDS18B20_TEMP__Scratch_To_Temp (Luint16 u16SensorIndex, const Luint8 *pu8Scratch, Lfloat32 *pf32Temp)
Convert scratchpad to temperature Takes the two temp bytes in the scratchpad and converts to floating point temp;.
Lint16 s16DS18B20_TEMP__Read (Luint16 u16SensorIndex)
Read the temperature from a device ONCE the conversion is complete.
Lint16 s16DS18B20_TEMP__All_Request (Luint16 u16SensorIndex, Luint8 u8Wait)
Issue a global command to start conversion of all devices on the wire This is most useful for starting thousands of sensors to convert.
Lint16 s16DS18B20_TEMP__All_Request_ByChannel (Luint8 u8ChannelIndex, Luint8 u8Wait)
Lint16 s16DS18B20_TEMP__Request (Luint16 u16SensorIndex, Luint8 u8Wait)
Request the temperature.
Lint16 s16DS18B20_TEMP__Get_Resolution (Luint16 u16SensorIndex, Luint8 *pu8Resolution)
Gets the current resolution by reading the scratchpad memory.
Lint16 s16DS18B20_TEMP__Get_UserID (Luint16 u16SensorIndex)
Lint16 s16DS18B20_TEMP__Set_Resolution (Luint16 u16SensorIndex, Luint8 u8Resolution)
Set the temperature resolution.
Variables
struct _strDS18B20 sDS18B20
Detailed Description
Function Documentation
Lint16 s16DS18B20_TEMP__All_Request (Luint16 u16SensorIndex, Luint8 u8Wait)
Issue a global command to start conversion of all devices on the wire This is most useful for starting thousands of sensors to convert.
Parameters
[in] u8Wait Set to 1 to wait the desired conversion time.
[in] u16SensorIndex The sensor index
Returns
0 = success
-ve = error
SafeTool Function MD5:
2A3FA2AC34982FD9EA9455F9CB0482D1
SafeTool Function ID:
LCCM644R0.FILE.003.FUNC.003
References s16DS18B20_1WIRE__Generate_Reset(), s16DS18B20_1WIRE__Skip(), s16DS18B20_1WIRE__WriteByte(), _strDS18B20::sDevice, sDS18B20, _strDS18B20::u8ChannelIndex, _strDS18B20::u8Resolution, and vDS18B20_DELAYS__Delay_mS().
Lint16 s16DS18B20_TEMP__All_Request_ByChannel (Luint8 u8ChannelIndex, Luint8 u8Wait)
References s16DS18B20_1WIRE__Generate_Reset(), s16DS18B20_1WIRE__Skip(), s16DS18B20_1WIRE__WriteByte(), _strDS18B20::sDevice, sDS18B20, _strDS18B20::u8Resolution, and vDS18B20_DELAYS__Delay_mS().
Referenced by vDS18B20__Process().
Lint16 s16DS18B20_TEMP__Get_Resolution (Luint16 u16SensorIndex, Luint8 * pu8Resolution)
Gets the current resolution by reading the scratchpad memory.
Parameters
[out] *pu8Resolution Returned resolution value
[in] u16SensorIndex Already enumerated address ID
Returns
0 = success
-ve = error
SafeTool Function MD5:
79132391B133E345569932CFFF9C4316
SafeTool Function ID:
LCCM644R0.FILE.003.FUNC.002
References s16DS18B20_SCRATCH__Read(), sDS18B20, and _strDS18B20::u8TempScratch.
Referenced by s16DS18B20_ADDX__Search(), and vDS18B20__Process().
Lint16 s16DS18B20_TEMP__Get_UserID (Luint16 u16SensorIndex)
References s16DS18B20_SCRATCH__Read(), _strDS18B20::sDevice, sDS18B20, _strDS18B20::u16UserIndex, and _strDS18B20::u8TempScratch.
Referenced by vDS18B20__Process().
Lint16 s16DS18B20_TEMP__Read (Luint16 u16SensorIndex)
Read the temperature from a device ONCE the conversion is complete.
Parameters
[in] u16SensorIndex The sensor index
Returns
0 = success
-ve = error
SafeTool Function MD5:
A078A4525D85F13160DDAF5DF26FE1E2
SafeTool Function ID:
LCCM644R0.FILE.003.FUNC.006
References _strDS18B20::f32Temperature, s16DS18B20_SCRATCH__Read(), sDS18B20, _strDS18B20::sTemp, _strDS18B20::u8TempScratch, and vDS18B20_TEMP__Scratch_To_Temp().
Referenced by vDS18B20__Process().
Lint16 s16DS18B20_TEMP__Request (Luint16 u16SensorIndex, Luint8 u8Wait)
Request the temperature.
If successful the temperature will be updated in the memory structure
Parameters
[in] u8Wait Set this to 1 to wait the required time for conversion
[in] u16SensorIndex The addressed index of the device.
Returns
0 = success
-ve = error
SafeTool Function MD5:
860D63E72330497D8ACB60F9EBF50D2D
SafeTool Function ID:
LCCM644R0.FILE.003.FUNC.004
References _strDS18B20::f32Temperature, s16DS18B20_1WIRE__Generate_Reset(), s16DS18B20_1WIRE__SelectDevice(), s16DS18B20_1WIRE__WriteByte(), s16DS18B20_SCRATCH__Read(), _strDS18B20::sDevice, sDS18B20, _strDS18B20::sTemp, _strDS18B20::u8ChannelIndex, _strDS18B20::u8Resolution, _strDS18B20::u8SerialNumber, _strDS18B20::u8TempScratch, vDS18B20_DELAYS__Delay_mS(), and vDS18B20_TEMP__Scratch_To_Temp().
Lint16 s16DS18B20_TEMP__Set_Resolution (Luint16 u16SensorIndex, Luint8 u8Resolution)
Set the temperature resolution.
Parameters
[in] u8Resolution New Res: 12,11,10 or 9 bit
[in] u16SensorIndex Device index address
Returns
0 = success
-ve = error
SafeTool Function MD5:
AA30E950FFA1C69214EC088D9D467661
SafeTool Function ID:
LCCM644R0.FILE.003.FUNC.001
References s16DS18B20_SCRATCH__Read(), s16DS18B20_SCRATCH__Write(), sDS18B20, u8DS18B20_SCRATCH__Compute_CRC(), and _strDS18B20::u8TempScratch.
Referenced by vDS18B20__Process().
void vDS18B20_TEMP__Scratch_To_Temp (Luint16 u16SensorIndex, const Luint8 * pu8Scratch, Lfloat32 * pf32Temp) static
Convert scratchpad to temperature Takes the two temp bytes in the scratchpad and converts to floating point temp;.
Note
Resolution must be known at this stage, otherwise reported temperature is 128.0C
Parameters
[out] *pf32Temp Pointer to return temperature value
[in] *pu8Scratch Pointer to scratchpad memory
[in] u16SensorIndex Index of the device so as we know our resoltion
SafeTool Function MD5:
65DE1541B347FC9CA29984F03A7B741D
SafeTool Function ID:
LCCM644R0.FILE.003.FUNC.005
References _strDS18B20::sDevice, sDS18B20, _strDS18B20::u8Resolution, and _strDS18B20::u8SerialNumber.
Referenced by s16DS18B20_TEMP__Read(), and s16DS18B20_TEMP__Request().
Variable Documentation
struct _strDS18B20 sDS18B20
Referenced by f32DS18B20__Get_Temperature_DegC(), s16DS18B20_TEMP__All_Request(), s16DS18B20_TEMP__All_Request_ByChannel(), s16DS18B20_TEMP__Get_Resolution(), s16DS18B20_TEMP__Get_UserID(), s16DS18B20_TEMP__Read(), s16DS18B20_TEMP__Request(), s16DS18B20_TEMP__Set_Resolution(), u162DS18B20__Get_UserIndex(), u16DS18B20__Get_NumEnum_Sensors(), u32DS18B20__Get_DeviceAddx(), u82DS18B20__Get_BusIndex(), u82DS18B20__Get_Resolution(), u8DS18B20__Is_NewDataAvail(), vDS18B20__Clear_NewDataAvail(), vDS18B20__Get_ROMID(), vDS18B20__Init(), vDS18B20__Process(), vDS18B20__Start_ConfigureResolution(), vDS18B20__Start_TempRead(), and vDS18B20_TEMP__Scratch_To_Temp().