(C Code, MULTICORE, ATA6870N Driver): ATA6870__BALANCE
ATA6870__BALANCE
MULTICORE » ATA6870
Functions
static Luint8 u8ATA6870_BALANCE__Handle (Luint8 u8DeviceIndex, Luint8 u8CellCounter, Luint8 u8CellIndex)
Handle the actual discharging.
static void vATA6870_BALANCE__Do (void)
Do the balancing.
void vATA6870_BALANCE__Init (void)
Init any balancer systems.
void vATA6870_BALANCE__Start (void)
Start the balancing process.
void vATA6870_BALANCE__Stop (void)
Stop the blanacing process and terminate any discharging resistors.
Luint8 u8ATA6870_BALANCE__Is_Busy (void)
Check if the balancer is busy.
void vATA6870_BALANCE__Process (void)
Process the balancer state machine.
void vATA6870_BALANCE__Manual (Luint8 u8CellIndex, Luint8 u8Enable)
Variables
struct _str6870 sATA6870
Detailed Description
Function Documentation
Luint8 u8ATA6870_BALANCE__Handle (Luint8 u8DeviceIndex, Luint8 u8CellCounter, Luint8 u8CellIndex) static
Handle the actual discharging.
Parameters
[in] u8CellIndex The cell in the stack to act on.
[in] u8CellCounter Individual cell in the BMS
[in] u8DeviceIndex ATA device index
Returns
return 1 if we are resistors on
SafeTool Function MD5:
A00A9DCBE0AF34E89F897ED43D57E81F
SafeTool Function ID:
LCCM650R0.FILE.012.FUNC.006
References _str6870::f32AverageCellVoltage, _str6870::f32BalanceTolerance, _str6870::f32Voltage, sATA6870, _str6870::sBalance, _str6870::u8ResistorOn, vATA6870_RES__TurnOff(), and vATA6870_RES__TurnOn().
Referenced by vATA6870_BALANCE__Do().
Luint8 u8ATA6870_BALANCE__Is_Busy (void)
Check if the balancer is busy.
Returns
0 = Not busy
1 = Busy
SafeTool Function MD5:
0C6AEF282147D3B4C0985DC3C7515D2E
SafeTool Function ID:
LCCM650R0.FILE.012.FUNC.004
References BALANCE_STATE__IDLE, _str6870::eState, sATA6870, and _str6870::sBalance.
void vATA6870_BALANCE__Do (void) static
Do the balancing.
SafeTool Function MD5:
D2C266693DEBB69953303D9FCEDB80E9
SafeTool Function ID:
LCCM650R0.FILE.012.FUNC.007
References C_ATA6870__MAX_CELLS, _str6870::f32Voltage, sATA6870, _str6870::sBalance, u8ATA6870_BALANCE__Handle(), and _str6870::u8MaxBalanceCells.
Referenced by vATA6870_BALANCE__Process().
void vATA6870_BALANCE__Init (void)
Init any balancer systems.
SafeTool Function MD5:
71AFDB346C1B611F3C203CE6F4BACCA1
SafeTool Function ID:
LCCM650R0.FILE.012.FUNC.001
References BALANCE_STATE__IDLE, C_ATA6870__TOTAL_CELLS, _str6870::eState, _str6870::f32BalanceTolerance, sATA6870, _str6870::sBalance, _str6870::u8MaxBalanceCells, and _str6870::u8ResistorOn.
Referenced by vATA6870__Init().
void vATA6870_BALANCE__Manual (Luint8 u8CellIndex, Luint8 u8Enable)
References C_ATA6870__MAX_CELLS, sATA6870, _str6870::sBalance, _str6870::u8ResistorOn, vATA6870_RES__TurnOff(), and vATA6870_RES__TurnOn().
void vATA6870_BALANCE__Process (void)
Process the balancer state machine.
Call this from main loop fast as possible.
SafeTool Function MD5:
173C6582E979E9DC904E68091ABF0A71
SafeTool Function ID:
LCCM650R0.FILE.012.FUNC.005
References BALANCE_STATE__BALANCED, BALANCE_STATE__CHECK_BALANCED, BALANCE_STATE__IDLE, BALANCE_STATE__START_BALANCING, BALANCE_STATE__WAIT_VOLTAGE_UPDATE, C_ATA6870__TOTAL_CELLS, _str6870::eState, sATA6870, _str6870::sBalance, _str6870::u8AverageUpdated, _str6870::u8ResistorOn, vATA6870_BALANCE__Do(), and vATA6870_BALANCE__Stop().
Referenced by vATA6870__Process().
void vATA6870_BALANCE__Start (void)
Start the balancing process.
SafeTool Function MD5:
461C224CAEE30E4668EF221BA446985D
SafeTool Function ID:
LCCM650R0.FILE.012.FUNC.002
References BALANCE_STATE__WAIT_VOLTAGE_UPDATE, _str6870::eState, sATA6870, _str6870::sBalance, and _str6870::u8AverageUpdated.
void vATA6870_BALANCE__Stop (void)
Stop the blanacing process and terminate any discharging resistors.
SafeTool Function MD5:
0FEC574EA48C801CCD0F4C9D113A53AA
SafeTool Function ID:
LCCM650R0.FILE.012.FUNC.003
References BALANCE_STATE__IDLE, C_ATA6870__TOTAL_CELLS, _str6870::eState, sATA6870, _str6870::sBalance, _str6870::u8ResistorOn, and vATA6870_RES__TurnAllOff().
Referenced by vATA6870_BALANCE__Process().
Variable Documentation
struct _str6870 sATA6870
Referenced by u8ATA6870_BALANCE__Handle(), u8ATA6870_BALANCE__Is_Busy(), vATA6870_BALANCE__Do(), vATA6870_BALANCE__Init(), vATA6870_BALANCE__Manual(), vATA6870_BALANCE__Process(), vATA6870_BALANCE__Start(), and vATA6870_BALANCE__Stop().