(C Code, MULTICORE, ATA6870N Driver): ATA6870__CELL_VOLT
ATA6870__CELL_VOLT
MULTICORE » ATA6870
Functions
Lint16 s16ATA6870_CELL__BulkRead_All (void)
bulk read voltages: 6 voltages, 1 temperature
void vATA6870_CELL__Sum_CellVoltages (void)
Compute the sum of all voltages (= our pack voltage)
Lfloat32 f32ATA6870_CELL__Get_PackVoltage (void)
void vATA6870_CELL__Average_CellVoltages (void)
Take the average cell voltages.
Lint16 s16ATA6870_CELL__Check_CellVoltageError (Lfloat32 *pf32Voltages)
Check if a cell is above or below safe threshold.
Lfloat32 f32ATA6870_CELL__Get_HighestVoltage (void)
Lfloat32 f32ATA6870_CELL__Get_LowestVoltage (void)
void vATA6870_CELL__Get_Voltages (Luint8 u8DeviceIndex, Lfloat32 *pf32Voltages, Lfloat32 *pF32Temperature)
Gets the voltages for each cell from a specific BMS device.
Variables
struct _str6870 sATA6870
Detailed Description
Function Documentation
Lfloat32 f32ATA6870_CELL__Get_HighestVoltage (void)
References C_ATA6870__MAX_CELLS, _str6870::f32Voltage, and sATA6870.
Lfloat32 f32ATA6870_CELL__Get_LowestVoltage (void)
References C_ATA6870__MAX_CELLS, _str6870::f32Voltage, and sATA6870.
Lfloat32 f32ATA6870_CELL__Get_PackVoltage (void)
References _str6870::f32PackVoltage, and sATA6870.
Lint16 s16ATA6870_CELL__BulkRead_All (void)
bulk read voltages: 6 voltages, 1 temperature
SafeTool Function MD5:
9E83BF6A7C1E8046881758D51B0CFCFD
SafeTool Function ID:
LCCM650R0.FILE.011.FUNC.003
References C_ATA6870__MAX_CELLS, _str6870::f32NTCTemperatureReading, _str6870::f32Voltage, s16ATA6870_CELL__Check_CellVoltageError(), sATA6870, and vATA6870_CELL__Get_Voltages().
Referenced by vATA6870__Process().
Lint16 s16ATA6870_CELL__Check_CellVoltageError (Lfloat32 * pf32Voltages)
Check if a cell is above or below safe threshold.
Note
if we use UNDER_VOLT function instead, be sure to implement an upper bound check as well for over voltage
Parameters
[in] *pf32Voltages voltages array of size C_ATA6870__MAX_CELLS
Returns
0 = Cell OK
-ve = error
SafeTool Function MD5:
7F85DF6A37F294D8B5FCB4BBE87CCDF6
SafeTool Function ID:
LCCM650R0.FILE.011.FUNC.006
References C_ATA6870__MAX_CELLS, C_ATA6870__MAX_VOLTS, and C_ATA6870__MIN_VOLTS.
Referenced by s16ATA6870_CELL__BulkRead_All().
void vATA6870_CELL__Average_CellVoltages (void)
Take the average cell voltages.
SafeTool Function MD5:
A17AE34A218A538C08AE40D5AD05A344
SafeTool Function ID:
LCCM650R0.FILE.011.FUNC.005
References C_ATA6870__TOTAL_CELLS, _str6870::f32AverageCellVoltage, _str6870::f32PackVoltage, sATA6870, and _str6870::u8AverageUpdated.
Referenced by vATA6870__Process().
void vATA6870_CELL__Get_Voltages (Luint8 u8DeviceIndex, Lfloat32 * pf32Voltages, Lfloat32 * pF32Temperature)
Gets the voltages for each cell from a specific BMS device.
Note
Need to ensure that a conversion has actually completed before this can be issued
Parameters
[out] *pF32Temperature The returned temperature reading from the NTC
[out] *pf32Voltages An array of 6 Cell voltages
[in] u8DeviceIndex The device index on the bus
SafeTool Function MD5:
EEE52897EC66ACC3E9A55AD2F3176D4F
SafeTool Function ID:
LCCM650R0.FILE.011.FUNC.002
References ATA6870_REG__DATA_RD16_BURST, C_ATA6870__ADC_RES_V, C_ATA6870__BUSRT_LENGTH, C_ATA6870__MAX_CELLS, C_ATA6870__OFFSET_VOLTAGE, and vATA6870_LOWLEVEL__Reg_ReadU8().
Referenced by s16ATA6870_CELL__BulkRead_All().
void vATA6870_CELL__Sum_CellVoltages (void)
Compute the sum of all voltages (= our pack voltage)
SafeTool Function MD5:
C722B0B07CE53C27DEF8357D218011DA
SafeTool Function ID:
LCCM650R0.FILE.011.FUNC.004
References C_ATA6870__TOTAL_CELLS, _str6870::f32PackVoltage, _str6870::f32Voltage, and sATA6870.
Referenced by vATA6870__Process().
Variable Documentation
struct _str6870 sATA6870
Referenced by f32ATA6870_CELL__Get_HighestVoltage(), f32ATA6870_CELL__Get_LowestVoltage(), f32ATA6870_CELL__Get_PackVoltage(), s16ATA6870_CELL__BulkRead_All(), vATA6870_CELL__Average_CellVoltages(), and vATA6870_CELL__Sum_CellVoltages().