(C Code, MULTICORE, ATA6870N Driver): ATA6870__CORE
ATA6870__CORE
MULTICORE » ATA6870
Functions
static void vATA6870__StartConversion (Luint8 u8VoltageMode, Luint8 u8TempBit)
Start ATA6870N Conversion.
void vATA6870__Init (void)
Init any ATA6870 systems.
void vATA6870__Process (void)
Process any ATA6870 tasks.
Luint32 u32ATA6870__Get_VoltsUpdateCount (void)
void vATA6870__10MS_ISR (void)
10ms ISR
Variables
struct _str6870 sATA6870
Detailed Description
Function Documentation
Luint32 u32ATA6870__Get_VoltsUpdateCount (void)
References sATA6870, and _str6870::u32VoltsUpdateCount.
void vATA6870__10MS_ISR (void)
10ms ISR
SafeTool Function MD5:
EFCD04EB2C2B91C6325DB0C8D146E16B
SafeTool Function ID:
LCCM644R0.FILE.000.FUNC.004
References sATA6870, and _str6870::u32ISR_Counter.
void vATA6870__Init (void)
Init any ATA6870 systems.
SafeTool Function MD5:
DD75420783FCC074EFEE1B22E4564570
SafeTool Function ID:
LCCM650R0.FILE.000.FUNC.001
References ATA6870_STATE__INIT_DEVICE, C_ATA6870__TOTAL_CELLS, _str6870::eState, _str6870::f32AverageCellVoltage, _str6870::f32NTCTemperatureReading, _str6870::f32PackVoltage, _str6870::f32Voltage, sATA6870, _str6870::u32VoltsUpdateCount, _str6870::u8AverageUpdated, vATA6870_BALANCE__Init(), vATA6870_INT__Init(), vATA6870_LOWLEVEL__Init(), vATA6870_LOWLEVEL__PowerOn(), and vATA6870_SCAN__Init().
void vATA6870__Process (void)
Process any ATA6870 tasks.
SafeTool Function MD5:
CC6F99350533FEAE2044081BD632EF21
SafeTool Function ID:
LCCM650R0.FILE.000.FUNC.002
References ATA6870_REG__CONTROL, ATA6870_REG__IRQ_MASK, ATA6870_STATE__AVERAGE_CELL_VOLTAGES, ATA6870_STATE__IDLE, ATA6870_STATE__INIT_DEVICE, ATA6870_STATE__READ_CELL_VOLTAGES, ATA6870_STATE__RUN_FILTERING, ATA6870_STATE__START_CONVERSION, ATA6870_STATE__SUM_CELL_VOLTAGES, ATA6870_STATE__WAIT_CONVERSION, C_ATA6870__TOTAL_CELLS, _str6870::eState, _str6870::f32Voltage, s16ATA6870_CELL__BulkRead_All(), sATA6870, _str6870::u16FilteringChannel, _str6870::u32ISR_Counter, _str6870::u32VoltsUpdateCount, vATA6870__StartConversion(), vATA6870_BALANCE__Process(), vATA6870_CELL__Average_CellVoltages(), vATA6870_CELL__Sum_CellVoltages(), vATA6870_LOWLEVEL__Reg_WriteU8(), and vATA6870_SCAN__Start().
void vATA6870__StartConversion (Luint8 u8VoltageMode, Luint8 u8TempBit) static
Start ATA6870N Conversion.
Parameters
[in] u8TempBit Enable temp measurement
[in] u8VoltageMode Enable volt measurement
References ATA6870_REG__OPERATION, u8ATA6870_STATUS__Get_IRQ_Status(), u8ATA6870_STATUS__Get_Op_Status(), and vATA6870_LOWLEVEL__Reg_WriteU8().
Referenced by vATA6870__Process().
Variable Documentation
struct _str6870 sATA6870
Referenced by f32ATA6870_CELL__Get_HighestVoltage(), f32ATA6870_CELL__Get_LowestVoltage(), f32ATA6870_CELL__Get_PackVoltage(), s16ATA6870_CELL__BulkRead_All(), u32ATA6870__Get_VoltsUpdateCount(), u8ATA6870_BALANCE__Handle(), u8ATA6870_BALANCE__Is_Busy(), vATA6870__10MS_ISR(), vATA6870__Init(), vATA6870__Process(), vATA6870_BALANCE__Do(), vATA6870_BALANCE__Init(), vATA6870_BALANCE__Manual(), vATA6870_BALANCE__Process(), vATA6870_BALANCE__Start(), vATA6870_BALANCE__Stop(), vATA6870_CELL__Average_CellVoltages(), vATA6870_CELL__Sum_CellVoltages(), vATA6870_INT__Init(), vATA6870_LOWLEVEL__Reg_ReadU8(), vATA6870_LOWLEVEL__Reg_WriteU8(), vATA6870_SCAN__Init(), and vATA6870_SCAN__Start().