(C Code, MULTICORE, ATA6870N Driver): ATA6870__RESISTORS
ATA6870__RESISTORS
MULTICORE » ATA6870
Functions
void vATA6870_RES__TurnOn (Luint8 u8DeviceIndex, Luint8 u8CellIndex)
Turn on an individual discharge resistor.
void vATA6870_RES__TurnOff (Luint8 u8DeviceIndex, Luint8 u8CellIndex)
Turn off an individual discharge resistor.
void vATA6870_RES__TurnAllOff (Luint8 u8DeviceIndex)
Turn off all resistors.
Variables
struct _str6870 sATA6870
Detailed Description
Function Documentation
void vATA6870_RES__TurnAllOff (Luint8 u8DeviceIndex)
Turn off all resistors.
Parameters
[in] u8DeviceIndex The BMS device index
SafeTool Function MD5:
11DAF5AAFB4EB61EA1B25C872B8C3CB2
SafeTool Function ID:
LCCM650R0.FILE.008.FUNC.003
References ATA6870_REG__CH_DISCHARGE, and vATA6870_LOWLEVEL__Reg_WriteU8().
Referenced by vATA6870_BALANCE__Stop().
void vATA6870_RES__TurnOff (Luint8 u8DeviceIndex, Luint8 u8CellIndex)
Turn off an individual discharge resistor.
Parameters
[in] u8CellIndex The specific cell index from 0 to 6
[in] u8DeviceIndex The BMS device index
SafeTool Function MD5:
CAC32654A9021593CFCB202AE04CA309
SafeTool Function ID:
LCCM650R0.FILE.008.FUNC.002
References ATA6870_REG__CH_DISCHARGE, vATA6870_LOWLEVEL__Reg_ReadU8(), and vATA6870_LOWLEVEL__Reg_WriteU8().
Referenced by u8ATA6870_BALANCE__Handle(), and vATA6870_BALANCE__Manual().
void vATA6870_RES__TurnOn (Luint8 u8DeviceIndex, Luint8 u8CellIndex)
Turn on an individual discharge resistor.
Parameters
[in] u8CellIndex The specific cell index from 0 to 6
[in] u8DeviceIndex The BMS device index
SafeTool Function MD5:
F59776F8654983DB7210D16DA2C75DFE
SafeTool Function ID:
LCCM650R0.FILE.008.FUNC.001
References ATA6870_REG__CH_DISCHARGE, vATA6870_LOWLEVEL__Reg_ReadU8(), and vATA6870_LOWLEVEL__Reg_WriteU8().
Referenced by u8ATA6870_BALANCE__Handle(), and vATA6870_BALANCE__Manual().
Variable Documentation
struct _str6870 sATA6870