/*
 * fcu_core__eeprom_layout.h
 *
 *  Created on: 9 Jan 2017
 *      Author: Lachlan
 */

#ifndef _FCU_CORE__EEPROM_LAYOUT_H_
#define _FCU_CORE__EEPROM_LAYOUT_H_

		//Indexes for Stepper system
		#define C_LOCALDEF__LCCM231__M0_MICROSTEP_RESOLUTION__PARAM_INDEX	(0U)
		#define C_LOCALDEF__LCCM231__M0_MAX_ACCELERATION__PARAM_INDEX		(1U)
		#define C_LOCALDEF__LCCM231__M0_MICRONS_PER_REVOLUTION__PARAM_INDEX	(2U)
		#define C_LOCALDEF__LCCM231__M0_STEPS_PER_REVOLUTION__PARAM_INDEX	(3U)
		#define C_LOCALDEF__LCCM231__M0_MAX_ANGULAR_VELOCITY__PARAM_INDEX	(4U)

		#define C_LOCALDEF__LCCM231__M1_MICROSTEP_RESOLUTION__PARAM_INDEX	(6U)
		#define C_LOCALDEF__LCCM231__M1_MAX_ACCELERATION__PARAM_INDEX		(7U)
		#define C_LOCALDEF__LCCM231__M1_MICRONS_PER_REVOLUTION__PARAM_INDEX	(8U)
		#define C_LOCALDEF__LCCM231__M1_STEPS_PER_REVOLUTION__PARAM_INDEX	(9U)
		#define C_LOCALDEF__LCCM231__M1_MAX_ANGULAR_VELOCITY__PARAM_INDEX	(10U)

		#define C_LOCALDEF__LCCM231__PARAM_INDEX__HEADER					(11U)
		#define C_LOCALDEF__LCCM231__PARAM_INDEX__CRC						(12U)


		//The parameter indexes for MMA8451
		#define C_LOCALDEF__LCCM418__PARAM_INDEX__U32_HEADER				(20U)
		#define C_LOCALDEF__LCCM418__PARAM_INDEX__S16_SENSOR0_X_ZERO		(21U)
		#define C_LOCALDEF__LCCM418__PARAM_INDEX__S16_SENSOR0_Y_ZERO		(22U)
		#define C_LOCALDEF__LCCM418__PARAM_INDEX__S16_SENSOR0_Z_ZERO		(23U)
		#define C_LOCALDEF__LCCM418__PARAM_INDEX__S16_SENSOR1_X_ZERO		(24U)
		#define C_LOCALDEF__LCCM418__PARAM_INDEX__S16_SENSOR1_Y_ZERO		(25U)
		#define C_LOCALDEF__LCCM418__PARAM_INDEX__S16_SENSOR1_Z_ZERO		(26U)
		#define C_LOCALDEF__LCCM418__PARAM_INDEX__S16_SENSOR2_X_ZERO		(27U)
		#define C_LOCALDEF__LCCM418__PARAM_INDEX__S16_SENSOR2_Y_ZERO		(28U)
		#define C_LOCALDEF__LCCM418__PARAM_INDEX__S16_SENSOR2_Z_ZERO		(29U)
		#define C_LOCALDEF__LCCM418__PARAM_INDEX__S16_SENSOR3_X_ZERO		(30U)
		#define C_LOCALDEF__LCCM418__PARAM_INDEX__S16_SENSOR3_Y_ZERO		(31U)
		#define C_LOCALDEF__LCCM418__PARAM_INDEX__S16_SENSOR3_Z_ZERO		(32U)
		#define C_LOCALDEF__LCCM418__PARAM_INDEX__U16_CRC					(33U)

		//Flight Control - brakes
		#define C_LOCALDEF__LCCM655__EEPROM_OFFSET__BRAKES_HEADER			(40U)
		#define C_LOCALDEF__LCCM655__EEPROM_OFFSET__BRAKE0_ZERO				(41U)
		#define C_LOCALDEF__LCCM655__EEPROM_OFFSET__BRAKE0_SPAN				(42U)
		#define C_LOCALDEF__LCCM655__EEPROM_OFFSET__BRAKE1_ZERO				(43U)
		#define C_LOCALDEF__LCCM655__EEPROM_OFFSET__BRAKE1_SPAN				(44U)
		#define C_LOCALDEF__LCCM655__EEPROM_OFFSET__BRAKES_CRC				(45U)

		#define C_LOCALDEF__LCCM655__EEPROM_OFFSET__STEP0_VELOC				(46U)
		#define C_LOCALDEF__LCCM655__EEPROM_OFFSET__STEP0_ACCEL				(47U)
		#define C_LOCALDEF__LCCM655__EEPROM_OFFSET__STEP1_VELOC				(48U)
		#define C_LOCALDEF__LCCM655__EEPROM_OFFSET__STEP1_ACCEL				(49U)
		#define C_LOCALDEF__LCCM655__EEPROM_OFFSET__STEP_CRC				(50U)

		//Laser Opto's - Height
		#define C_LOCALDEF__LCCM655__FCTL_OPTONCDT___FL_ZERO				(51U)
		#define C_LOCALDEF__LCCM655__FCTL_OPTONCDT___FR_ZERO				(52U)
		#define C_LOCALDEF__LCCM655__FCTL_OPTONCDT___RL_ZERO				(53U)
		#define C_LOCALDEF__LCCM655__FCTL_OPTONCDT___RR_ZERO				(54U)
		#define C_LOCALDEF__LCCM655__FCTL_OPTONCDT___CRC					(55U)

		//flight control, current DB
		#define C_LOCALDEF__LCCM655__FCTL_TRACKDB___CURRENT_DB				(60U)

		//Flight Control - Geometry
		#define C_LOCALDEF__LCCM655__FCTL_GEOM___START_INDEX				(61U)
		#define C_LOCALDEF__LCCM655__FCTL_GEOM___END_INDEX					(C_LOCALDEF__LCCM655__FCTL_GEOM___START_INDEX + (8*3)*2)
		#define C_LOCALDEF__LCCM655__FCTL_GEOM___CRC						(C_LOCALDEF__LCCM655__FCTL_GEOM___END_INDEX + 1)



#endif /* _FCU_CORE__EEPROM_LAYOUT_H_ */
