LFW615 (RLOOP - AUX PROP UNIT (APU)): AUXPROP__CORE
AUXPROP__CORE
RLOOP » AUXPROP
Functions
void vAPU__Init (void)
Init the APU.
void vAPU__Process (void)
Process any APU tasks.
Variables
TS_APU__MAIN sAPU
Detailed Description
Function Documentation
void vAPU__Init (void)
Init the APU.
SafeTool Function MD5:
9F3032F0BF6440DE53B0790362A22787
SafeTool Function ID:
LCCM720R0.FILE.000.FUNC.001
References HR_PRESCALE__1, LR_PRESCALE__32, N2HET_CHANNEL__1, vAPU_CLUTCH__Init(), vAPU_DAQ__Init(), vAPU_ETH__Init(), vAPU_THROTTLE__Init(), vRM4_EEPROM__Init(), vRM4_GIO__Init(), vRM4_N2HET__Init(), vRM4_RTI__Init(), vRM4_RTI__Start_Counter(), vRM4_RTI__Start_Interrupts(), vRTI_COMPARE__Enable_CompareInterrupt(), and vSIL3_EEPARAM__Init().
Referenced by main().
void vAPU__Process (void)
Process any APU tasks.
SafeTool Function MD5:
8EF605122727951038A1777EAA22BEB7
SafeTool Function ID:
LCCM720R0.FILE.000.FUNC.002
References vAPU_CLUTCH__Process().
Referenced by main().
Variable Documentation
TS_APU__MAIN sAPU