LFW615 (RLOOP - AUX PROP UNIT (APU)): N2HET__PINS
N2HET__PINS
RM4 » N2HET
Functions
void vRM4_N2HET_PINS__Init (RM4_N2HET__CHANNEL_T eChannel)
Init the HET Pins.
void vRM4_N2HET_PINS__AND_ShareControl (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32PinNumber, Luint8 u8Enable)
Usually the N2HET design allows only one HR structure to generate HR edges on a pin configured as output pin.
Luint8 u8RM4_N2HET_PINS__Get_Pin (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32PinNumber)
returns the pin data
Luint32 u32RM4_N2HET_PINS__Get_DIN_HET1 (void)
Returns the data in register for the HET1 group.
Luint32 u32RM4_N2HET_PINS__Get_DIN_HET2 (void)
Returns the data in register for the HET2 group.
void vRM4_N2HET_PINS__Set_PinDirection_Output (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32PinNumber)
sets a pin as an output
void vRM4_N2HET_PINS__Set_PinDirection_Input (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32PinNumber)
Sets a pin to input.
void vRM4_N2HET_PINS__Set_PortData (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32Value)
Sets the entire port value to a u32.
void vRM4_N2HET_PINS__Set_Pin (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32Bit, Luint32 u32Value)
Sets a pin value.
void vRM4_N2HET_PINS__Set_PinHigh (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32PinIndex)
sets a single bit on
void vRM4_N2HET_PINS__Set_PinLow (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32PinIndex)
sets a single port bit off
void vRM4_N2HET_PINS__Set_PortData_LSR (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32Value, Luint32 u32LSRValue, Luint32 u32DataMask)
Sets the port data, and performs a left shift on the value first.
Detailed Description
Function Documentation
Luint32 u32RM4_N2HET_PINS__Get_DIN_HET1 (void)
Returns the data in register for the HET1 group.
SafeTool Function MD5:
264B327A48E7B37F3B452F1F7BB69C41
SafeTool Function ID:
LCCM240R0.FILE.007.FUNC.010
References hetREG1.
Luint32 u32RM4_N2HET_PINS__Get_DIN_HET2 (void)
Returns the data in register for the HET2 group.
SafeTool Function MD5:
DC2C1BC74D27B0F41D4B85E7F5338949
SafeTool Function ID:
LCCM240R0.FILE.007.FUNC.011
References hetREG2.
Luint8 u8RM4_N2HET_PINS__Get_Pin (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32PinNumber)
returns the pin data
Parameters
[in] u32PinNumber The HET pin number
[in] eChannel The HET channel
Returns
1 or 0 depending on pin state
SafeTool Function MD5:
6964E5684FBF73742C9B04F0C6F11534
SafeTool Function ID:
LCCM240R0.FILE.007.FUNC.002
References hetREG1, hetREG2, and N2HET_CHANNEL__1.
void vRM4_N2HET_PINS__AND_ShareControl (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32PinNumber, Luint8 u8Enable)
Usually the N2HET design allows only one HR structure to generate HR edges on a pin configured as output pin.
The HETXOR register allows a logical XOR of the output signals of two consecutive HR structures N (even) and N+1 (odd). See Figure 20-13. In this way, it is possible to generate pulses smaller than the loop resolution clock since both edges can be generated by two independent HR structures. This is especially required for symmetrical PWM. See Figure 20-14. The hardware provides a XOR gate that is connected to the outputs of the HR structure of two consecutive pins. In this structure, pin N+1 remains available for general purpose input/output.
20.4.12 AND Share Control Register (HETAND)
BIT FIELD VALUE DESCRIPTION
15-0 AND SHARE n+1 / n AND Share Enable Enable the AND sharing of the same pin for two HR structures. For example, if bit AND SHARE 1/0 is set, the pin HET[0] will then be commanded by a logical AND of both HR structures 0 and 1.
Note: If HR AND SHARE bits are used, pins not connected to HR structures (the odd number pin in each pair) can be accessed as general inputs/outputs. 0 HR Output of HET[n+1] and HET[n] are not AND shared 1 HR Output of HET[n+1] and HET[n] are AND shared onto pin HET[n]
Parameters
[in] u8Enable 1 = Enable and sharing
[in] u32PinNumber Pin in the N2HET
[in] eChannel N2HET Channel
SafeTool Function MD5:
45ADA672D07A3058907B11D9C71ECD81
SafeTool Function ID:
LCCM240R0.FILE.007.FUNC.012
References hetREG1, and N2HET_CHANNEL__1.
void vRM4_N2HET_PINS__Init (RM4_N2HET__CHANNEL_T eChannel)
Init the HET Pins.
Parameters
[in] eChannel The HET channel
SafeTool Function MD5:
7BB4F9495F8DEA62FFA2B93D1C83A5EF
SafeTool Function ID:
LCCM240R0.FILE.007.FUNC.001
References N2HET_CHANNEL__1.
void vRM4_N2HET_PINS__Set_Pin (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32Bit, Luint32 u32Value)
Sets a pin value.
Parameters
[in] u32Value The value
[in] u32Bit The bit index in the port
[in] eChannel The HET channel
SafeTool Function MD5:
495A05C524D411AD3F5541B21EEF839A
SafeTool Function ID:
LCCM240R0.FILE.007.FUNC.006
References vRM4_N2HET_PINS__Set_PinHigh(), and vRM4_N2HET_PINS__Set_PinLow().
Referenced by vAPU_CLUTCH__Disengage(), vAPU_CLUTCH__Engage(), vAPU_THROTTLE__Forward(), and vAPU_THROTTLE__Reverse().
void vRM4_N2HET_PINS__Set_PinDirection_Input (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32PinNumber)
Sets a pin to input.
Parameters
[in] u32PinNumber The pin number
[in] eChannel The HET channel
SafeTool Function MD5:
AFCE8B641AFD036DF37CFEE148F4005C
SafeTool Function ID:
LCCM240R0.FILE.007.FUNC.004
References hetREG1, hetREG2, and N2HET_CHANNEL__1.
void vRM4_N2HET_PINS__Set_PinDirection_Output (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32PinNumber)
sets a pin as an output
Parameters
[in] u32PinNumber Pin number ranges from 0 to 31
[in] eChannel The HET channel.
SafeTool Function MD5:
43A15D9D43555969D12A60F8FF964875
SafeTool Function ID:
LCCM240R0.FILE.007.FUNC.003
References hetREG1, hetREG2, and N2HET_CHANNEL__1.
Referenced by vAPU_CLUTCH__Init(), and vAPU_THROTTLE__Init().
void vRM4_N2HET_PINS__Set_PinHigh (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32PinIndex)
sets a single bit on
Parameters
[in] u32PinIndex The pin index
[in] eChannel The HET channel
SafeTool Function MD5:
6D710DA1FADA2AB42FB1DDF12E40830E
SafeTool Function ID:
LCCM240R0.FILE.007.FUNC.007
References hetREG1, hetREG2, and N2HET_CHANNEL__1.
Referenced by vRM4_N2HET_PINS__Set_Pin().
void vRM4_N2HET_PINS__Set_PinLow (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32PinIndex)
sets a single port bit off
Parameters
[in] u32PinIndex The PIN index
[in] eChannel The HET channel
SafeTool Function MD5:
67A737CB7B4B8D544442583AB4AFADE4
SafeTool Function ID:
LCCM240R0.FILE.007.FUNC.008
References hetREG1, hetREG2, and N2HET_CHANNEL__1.
Referenced by vRM4_N2HET_PINS__Set_Pin().
void vRM4_N2HET_PINS__Set_PortData (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32Value)
Sets the entire port value to a u32.
Will affect any pins who's direction is set to 1.
Parameters
[in] u32Value Port value
[in] eChannel The channel
SafeTool Function MD5:
2A2E9DB524D376EC2201A0B967438B52
SafeTool Function ID:
LCCM240R0.FILE.007.FUNC.005
References hetREG1, hetREG2, and N2HET_CHANNEL__1.
void vRM4_N2HET_PINS__Set_PortData_LSR (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32Value, Luint32 u32LSRValue, Luint32 u32DataMask)
Sets the port data, and performs a left shift on the value first.
useful for using the HET pins as address busses with out affecting anything else. The data mask should contain zeros in the bits that we need to modify. For example to mask off NHET1_20:17 DataMask = 0x1E0000 -> NOT = FFE1FFFF
Parameters
[in] u32DataMask ## Desc ##
[in] u32LSRValue ## Desc ##
[in] u32Value ## Desc ##
[in] eChannel The HET channel
SafeTool Function MD5:
9F720D0789E465431B83D6597D3781F2
SafeTool Function ID:
LCCM240R0.FILE.007.FUNC.009
References hetREG1, hetREG2, and N2HET_CHANNEL__1.