LFW615 (RLOOP - AUX PROP UNIT (APU)): EEPARAMS__CORE
EEPARAMS__CORE
MULTICORE » EEPARAMS
Macros
#define C_EEPARAMS__SHIFT_VALUE 2U
Functions
void vSIL3_EEPARAM__Init (void)
Inits the params module.
Luint8 u8SIL3_EEPARAM__Read (Luint16 u16Index)
Read a byte parameter.
void vSIL3_EEPARAM__WriteU8 (Luint16 u16Index, Luint8 u8Value, E_EEPROM_PARAMS__DELAY_T eDelay)
write a u8 parameter
Luint16 u16SIL3_EEPARAM__Read (Luint16 u16Index)
Read a u16 value.
void vSIL3_EEPARAM__WriteU16 (Luint16 u16Index, Luint16 u16Value, E_EEPROM_PARAMS__DELAY_T eDelay)
Write a U16 value.
Lint16 s16SIL3_EEPARAM__Read (Luint16 u16Index)
Read a s16 parameter.
void vSIL3_EEPARAM__WriteS16 (Luint16 u16Index, Lint16 s16Value, E_EEPROM_PARAMS__DELAY_T eDelay)
Write s16 param.
Luint32 u32SIL3_EEPARAM__Read (Luint16 u16Index)
read a u32 parameter
void vSIL3_EEPARAM__WriteU32 (Luint16 u16Index, Luint32 u32Value, E_EEPROM_PARAMS__DELAY_T eDelay)
Write a u32 param.
Lint32 s32SIL3_EEPARAM__Read (Luint16 u16Index)
read a s32 parameter
void vSIL3_EEPARAM__WriteS32 (Luint16 u16Index, Lint32 s32Value, E_EEPROM_PARAMS__DELAY_T eDelay)
Write a s32 param.
Lfloat32 f32SIL3_EEPARAM__Read (Luint16 u16Index)
read a f32 parameter
void vSIL3_EEPARAM__WriteF32 (Luint16 u16Index, Lfloat32 f32Value, E_EEPROM_PARAMS__DELAY_T eDelay)
write a f32 parameter
void vSIL3_EEPARAM_MAC__Write_MAC8 (Luint16 u16Index, const Luint8 *pu8MAC, E_EEPROM_PARAMS__DELAY_T eDelay)
Write an 8 byte MAC.
void vSIL3_EEPARAM_MAC__Read_MAC8 (Luint16 u16Index, Luint8 *pu8MAC)
Reads an 8 byte MAC.
Detailed Description
Macro Definition Documentation
#define C_EEPARAMS__SHIFT_VALUE 2U
Referenced by f32SIL3_EEPARAM__Read(), s16SIL3_EEPARAM__Read(), s32SIL3_EEPARAM__Read(), u16SIL3_EEPARAM__Read(), u32SIL3_EEPARAM__Read(), u8SIL3_EEPARAM__Read(), vSIL3_EEPARAM__WriteF32(), vSIL3_EEPARAM__WriteS16(), vSIL3_EEPARAM__WriteS32(), vSIL3_EEPARAM__WriteU16(), vSIL3_EEPARAM__WriteU32(), vSIL3_EEPARAM__WriteU8(), vSIL3_EEPARAM_MAC__Read_MAC8(), and vSIL3_EEPARAM_MAC__Write_MAC8().
Function Documentation
Lfloat32 f32SIL3_EEPARAM__Read (Luint16 u16Index)
read a f32 parameter
Specifications:
LCCM188R0.SPEC.UTR.008
Test Specifications:
LCCM188R0.TS.007
Parameters
[in] u16Index The parameter offset index
Returns
The parameter f32
SafeTool Function MD5:
FDFB84928C703235AF7ECEAC63CD5B8D
SafeTool Function ID:
LCCM188R0.FILE.001.FUNC.007
References C_EEPARAMS__SHIFT_VALUE.
Referenced by vSIL3_EEPARAM_MAC__Read_MAC8().
Lint16 s16SIL3_EEPARAM__Read (Luint16 u16Index)
Read a s16 parameter.
Specifications:
LCCM188R0.SPEC.UTR.005
Test Specifications:
LCCM188R0.TS.004
Parameters
[in] u16Index The parameter offset index
Returns
The parameter s16
SafeTool Function MD5:
ED3708F7B726E5FD4FEE34E2DC60E9A0
SafeTool Function ID:
LCCM188R0.FILE.001.FUNC.004
References C_EEPARAMS__SHIFT_VALUE.
Lint32 s32SIL3_EEPARAM__Read (Luint16 u16Index)
read a s32 parameter
Specifications:
LCCM188R0.SPEC.UTR.007
Test Specifications:
LCCM188R0.TS.006
Parameters
[in] u16Index The parameter offset index
Returns
The parameter s32
SafeTool Function MD5:
2BF3516D7F9AA271964DB9142AE80E9F
SafeTool Function ID:
LCCM188R0.FILE.001.FUNC.006
References C_EEPARAMS__SHIFT_VALUE.
Referenced by vSIL3_EEPARAM_MAC__Read_MAC8().
Luint16 u16SIL3_EEPARAM__Read (Luint16 u16Index)
Read a u16 value.
Specifications:
LCCM188R0.SPEC.UTR.004
Test Specifications:
LCCM188R0.TS.003
Parameters
[in] u16Index The parameter offset index
Returns
The parameter u16
SafeTool Function MD5:
489A6FEF2980E9507BE22F4F3254EC9A
SafeTool Function ID:
LCCM188R0.FILE.001.FUNC.003
References C_EEPARAMS__SHIFT_VALUE.
Luint32 u32SIL3_EEPARAM__Read (Luint16 u16Index)
read a u32 parameter
Specifications:
LCCM188R0.SPEC.UTR.006
Test Specifications:
LCCM188R0.TS.005
Parameters
[in] u16Index The parameter offset index
Returns
The parameter u32
SafeTool Function MD5:
D6113CBAF9B7255856BB5F1510E29734
SafeTool Function ID:
LCCM188R0.FILE.001.FUNC.005
References C_EEPARAMS__SHIFT_VALUE.
Luint8 u8SIL3_EEPARAM__Read (Luint16 u16Index)
Read a byte parameter.
Specifications:
LCCM188R0.SPEC.UTR.003
Test Specifications:
LCCM188R0.TS.002
Parameters
[in] u16Index The parameter offset index
Returns
The parameter u8
SafeTool Function MD5:
FD6D031E867C92769BEB212E7E546EAC
SafeTool Function ID:
LCCM188R0.FILE.001.FUNC.002
References C_EEPARAMS__SHIFT_VALUE.
void vSIL3_EEPARAM__Init (void)
Inits the params module.
Specifications:
LCCM188R0.SPEC.UTR.002
Test Specifications:
LCCM188R0.TS.001
SafeTool Function MD5:
AC9D01A029376254D4A654CAAEBC5828
SafeTool Function ID:
LCCM188R0.FILE.001.FUNC.001
Referenced by vAPU__Init().
void vSIL3_EEPARAM__WriteF32 (Luint16 u16Index, Lfloat32 f32Value, E_EEPROM_PARAMS__DELAY_T eDelay)
write a f32 parameter
Specifications:
LCCM188R0.SPEC.UTR.014
Test Specifications:
LCCM188R0.TS.012
Parameters
[in] eDelay Delay the write until another stage
Will just update the buffer, not the FLASH
[in] f32Value The value
[in] u16Index The index
SafeTool Function MD5:
89B734FE2F3FD841B3DA261366092B0C
SafeTool Function ID:
LCCM188R0.FILE.001.FUNC.013
References C_EEPARAMS__SHIFT_VALUE.
Referenced by vSIL3_EEPARAM_MAC__Read_MAC8().
void vSIL3_EEPARAM__WriteS16 (Luint16 u16Index, Lint16 s16Value, E_EEPROM_PARAMS__DELAY_T eDelay)
Write s16 param.
Specifications:
LCCM188R0.SPEC.UTR.011
Test Specifications:
LCCM188R0.TS.010
Parameters
[in] eDelay Delay the write until another stage
Will just update the buffer, not the FLASH
[in] s16Value The value
[in] u16Index The index
SafeTool Function MD5:
F37CC1F98DED5DFB5AD0547309F212D3
SafeTool Function ID:
LCCM188R0.FILE.001.FUNC.010
References C_EEPARAMS__SHIFT_VALUE.
void vSIL3_EEPARAM__WriteS32 (Luint16 u16Index, Lint32 s32Value, E_EEPROM_PARAMS__DELAY_T eDelay)
Write a s32 param.
Specifications:
LCCM188R0.SPEC.UTR.013
Test Specifications:
LCCM188R0.TS.012
Parameters
[in] eDelay Delay the write until another stage
Will just update the buffer, not the FLASH
[in] s32Value The value
[in] u16Index The index
SafeTool Function MD5:
EC7B67133FA3E2C90C9913FDDB7ED566
SafeTool Function ID:
LCCM188R0.FILE.001.FUNC.012
References C_EEPARAMS__SHIFT_VALUE.
Referenced by vSIL3_EEPARAM_MAC__Read_MAC8().
void vSIL3_EEPARAM__WriteU16 (Luint16 u16Index, Luint16 u16Value, E_EEPROM_PARAMS__DELAY_T eDelay)
Write a U16 value.
Specifications:
LCCM188R0.SPEC.UTR.010
Test Specifications:
LCCM188R0.TS.009
Parameters
[in] eDelay Delay the write until another stage Will just update the buffer, not the FLASH
[in] u16Value The value
[in] u16Index The index to store the value
SafeTool Function MD5:
6436C07339095C6AC4B3FBA6B4D4D001
SafeTool Function ID:
LCCM188R0.FILE.001.FUNC.009
References C_EEPARAMS__SHIFT_VALUE.
void vSIL3_EEPARAM__WriteU32 (Luint16 u16Index, Luint32 u32Value, E_EEPROM_PARAMS__DELAY_T eDelay)
Write a u32 param.
Specifications:
LCCM188R0.SPEC.UTR.012
Test Specifications:
LCCM188R0.TS.011
Parameters
[in] eDelay Delay the write until another stage
Will just update the buffer, not the FLASH
[in] u32Value The value
[in] u16Index The param index
SafeTool Function MD5:
2FBB6E38DBFBA30C1781A101EF281A5B
SafeTool Function ID:
LCCM188R0.FILE.001.FUNC.011
References C_EEPARAMS__SHIFT_VALUE.
void vSIL3_EEPARAM__WriteU8 (Luint16 u16Index, Luint8 u8Value, E_EEPROM_PARAMS__DELAY_T eDelay)
write a u8 parameter
Specifications:
LCCM188R0.SPEC.UTR.009
Test Specifications:
LCCM188R0.TS.008
Parameters
[in] eDelay Delay the write until another stage
Will just update the buffer, not the FLASH
[in] u8Value The value to write
[in] u16Index The index
SafeTool Function MD5:
CE00807CBA4D6B0FEC6BFD3A2010D8FD
SafeTool Function ID:
LCCM188R0.FILE.001.FUNC.008
References C_EEPARAMS__SHIFT_VALUE.
void vSIL3_EEPARAM_MAC__Read_MAC8 (Luint16 u16Index, Luint8 * pu8MAC)
Reads an 8 byte MAC.
Parameters
[out] pu8MAC Pointer to user buffer
[in] u16Index The param index
SafeTool Function MD5:
116E6DC44C18C99BDFAE93FAF60EACA5
SafeTool Function ID:
LCCM188R0.FILE.001.FUNC.018
References C_EEPARAMS__SHIFT_VALUE, DELAY_T__DELAYED_WRITE, f32SIL3_EEPARAM__Read(), tsNUM_f32Vector_3D::f32X, tsNUM_f32Vector_3D::f32Y, tsNUM_f32Vector_3D::f32Z, s32SIL3_EEPARAM__Read(), tsNUM_s32Vector_3D::s32X, tsNUM_s32Vector_3D::s32Y, tsNUM_s32Vector_3D::s32Z, vSIL3_EEPARAM__WriteF32(), and vSIL3_EEPARAM__WriteS32().
void vSIL3_EEPARAM_MAC__Write_MAC8 (Luint16 u16Index, const Luint8 * pu8MAC, E_EEPROM_PARAMS__DELAY_T eDelay)
Write an 8 byte MAC.
Parameters
[in] eDelay Delay the write until another stage Will just update the buffer, not the FLASH
[in] pu8MAC Pointer to 8 byte MAC
[in] u16Index The param index
SafeTool Function MD5:
F871B880D9D0E2E4F783DB10E713EE91
SafeTool Function ID:
LCCM188R0.FILE.001.FUNC.017
References C_EEPARAMS__SHIFT_VALUE, and DELAY_T__DELAYED_WRITE.