LFW615 (RLOOP - AUX PROP UNIT (APU)): ADC__INTERRUPTS
ADC__INTERRUPTS
RM4 » ADC
Functions
void vRM4_ADC_INT__UserNotification (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup)
User Notification Port.
void vRM4_ADC1_INT__Group0_ISR (void)
ADC1 Event Group Interrupt Handler.
void vRM4_ADC1_INT__Group1_ISR (void)
ADC1 Group 1 Interrupt Handler.
void vRM4_ADC1_INT__Group2_ISR (void)
ADC1 Group 2 Interrupt Handler.
void vRM4_ADC2_INT__Group0_ISR (void)
ADC2 Event Group Interrupt Handler.
void vRM4_ADC2_INT__Group1_ISR (void)
ADC2 Group 1 Interrupt Handler.
void vRM4_ADC2_INT__Group2_ISR (void)
ADC2 Group 2 Interrupt Handler.
void vRM4_ADC_LOWLEVEL__Enable_Notification (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup)
Enable notification.
void vRM4_ADC_LOWLEVEL__Disable_Notification (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup)
Disable notification.
Variables
RM4_ADC_T gADC
Detailed Description
Function Documentation
void vRM4_ADC1_INT__Group0_ISR (void)
ADC1 Event Group Interrupt Handler.
SafeTool Function MD5:
88C726775FBC3FAFBFC64866CD79DD60
SafeTool Function ID:
LCCM414R0.FILE.010.FUNC.002
References ADC_GROUP__EVENT, adcREG1, RM4_ADC__1, and vRM4_ADC_INT__UserNotification().
void vRM4_ADC1_INT__Group1_ISR (void)
ADC1 Group 1 Interrupt Handler.
SafeTool Function MD5:
FD756F2488FD65EC0058ED8ADD5BCF73
SafeTool Function ID:
LCCM414R0.FILE.010.FUNC.003
References ADC_GROUP__GROUP_1, adcREG1, RM4_ADC__1, and vRM4_ADC_INT__UserNotification().
void vRM4_ADC1_INT__Group2_ISR (void)
ADC1 Group 2 Interrupt Handler.
SafeTool Function MD5:
5C8631D53D77A54378A36819B9BAC172
SafeTool Function ID:
LCCM414R0.FILE.010.FUNC.004
References ADC_GROUP__GROUP_2, adcREG1, RM4_ADC__1, and vRM4_ADC_INT__UserNotification().
void vRM4_ADC2_INT__Group0_ISR (void)
ADC2 Event Group Interrupt Handler.
SafeTool Function MD5:
8F73AF3DAA2619E9E6D54C07BB71ED3F
SafeTool Function ID:
LCCM414R0.FILE.010.FUNC.005
References ADC_GROUP__EVENT, adcREG2, RM4_ADC__2, and vRM4_ADC_INT__UserNotification().
void vRM4_ADC2_INT__Group1_ISR (void)
ADC2 Group 1 Interrupt Handler.
SafeTool Function MD5:
E273B4D4446268AC284B984DB36C30CC
SafeTool Function ID:
LCCM414R0.FILE.010.FUNC.006
References ADC_GROUP__GROUP_1, adcREG2, RM4_ADC__2, and vRM4_ADC_INT__UserNotification().
void vRM4_ADC2_INT__Group2_ISR (void)
ADC2 Group 2 Interrupt Handler.
SafeTool Function MD5:
172722ECDB2BC2FEC615DEE4289237B3
SafeTool Function ID:
LCCM414R0.FILE.010.FUNC.007
References ADC_GROUP__GROUP_2, adcREG2, RM4_ADC__2, and vRM4_ADC_INT__UserNotification().
void vRM4_ADC_INT__UserNotification (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup)
User Notification Port.
Parameters
[in] eGroup ADC Group
[in] eADC ADC Type
SafeTool Function MD5:
85F6C24323A32AA07FC6F0369B89EA40
SafeTool Function ID:
LCCM414R0.FILE.010.FUNC.001
References ADC_GROUP__EVENT, ADC_GROUP__GROUP_1, ADC_GROUP__GROUP_2, RM4_ADC__1, and RM4_ADC__2.
Referenced by vRM4_ADC1_INT__Group0_ISR(), vRM4_ADC1_INT__Group1_ISR(), vRM4_ADC1_INT__Group2_ISR(), vRM4_ADC2_INT__Group0_ISR(), vRM4_ADC2_INT__Group1_ISR(), and vRM4_ADC2_INT__Group2_ISR().
void vRM4_ADC_LOWLEVEL__Disable_Notification (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup)
Disable notification.
Note
The function vRM4_ADC_INIT__Init has to be called before this function can be used.
Parameters
[in] eGroup Group Index
[in] eADC ADC Index
SafeTool Function MD5:
6C9AA7F6AA9FC1B710A7749C41333151
SafeTool Function ID:
LCCM414R0.FILE.010.FUNC.009
References adcREG1, adcREG2, RM4_ADC__1, and RM4_ADC__2.
void vRM4_ADC_LOWLEVEL__Enable_Notification (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup)
Enable notification.
Note
The function vRM4_ADC_INIT__Init has to be called before this function can be used. This function should be called before the conversion is started
Parameters
[in] eGroup Group Index
[in] eADC ADC Index
SafeTool Function MD5:
8F1449AEDFC64C8E71746ECCF1CB055D
SafeTool Function ID:
LCCM414R0.FILE.010.FUNC.008
References adcREG1, adcREG2, RM4_ADC__1, and RM4_ADC__2.
Variable Documentation
RM4_ADC_T gADC