LFW615 (RLOOP - AUX PROP UNIT (APU)): EEPROM__CORE
EEPROM__CORE
RM4 » EEPROM
Functions
void vRM4_EEPROM__Init (void)
Init the EEPROM system.
Lint16 s16RM4_EEPROM__Save (void)
Save the data from the EEPROM buffer back to the EEPROM.
Luint32 u32RM4_EEPROM__Read (Luint32 u32AddxOffset)
Read a U32.
Lint32 s32RM4_EEPROM__Read (Luint32 u32AddxOffset)
Read a S32.
Lfloat32 f32RM4_EEPROM__Read (Luint32 u32AddxOffset)
Read a F32.
void vRM4_EEPROM__WriteU32 (Luint32 u32AddxOffset, Luint32 u32Value, Luint8 u8Delay)
Write a U32 to the eeprom buffer.
void vRM4_EEPROM__WriteS32 (Luint32 u32AddxOffset, Lint32 s32Value, Luint8 u8Delay)
Write a S32.
void vRM4_EEPROM__WriteF32 (Luint32 u32AddxOffset, Lfloat32 f32Value, Luint8 u8Delay)
Write a F32.
void vRM4_EEPROM__Write_U8Array (Luint8 u8Sector, Luint16 u16AddxInSector, Luint8 *pu8Array, Luint16 u16Length)
write an array directly to EEPROM
void vRM4_EEPROM__Read_U8Array (Luint8 u8Sector, Luint16 u16AddxInSector, Luint8 *pu8Array, Luint16 u16Length)
Reads an array from memory.
Variables
RM4_EEPROM__T sEEPROM
Detailed Description
Function Documentation
Lfloat32 f32RM4_EEPROM__Read (Luint32 u32AddxOffset)
Read a F32.
Parameters
[in] u32AddxOffset The address offset
Returns
The read F32 value
SafeTool Function MD5:
FED46881ED37EC987C3D565E182D96D1
SafeTool Function ID:
LCCM230R0.FILE.001.FUNC.005
References C_LCCM320__FLASH_START_ADDX, and f32SIL3_NUM_CONVERT__Array().
Lint16 s16RM4_EEPROM__Save (void)
Save the data from the EEPROM buffer back to the EEPROM.
Returns
0 = success
-1 = fault (check the fault flags)
SafeTool Function MD5:
977FF11E1667FFDC3EE81A7353520965
SafeTool Function ID:
LCCM230R0.FILE.001.FUNC.002
References C_LCCM230__CORE__FAULT_INDEX__00, C_LCCM230__CORE__FAULT_INDEX__01, C_LCCM230__CORE__FAULT_INDEX__02, C_LCCM320__FLASH_BANK, C_LCCM320__FLASH_SECTOR_SIZE_BYTES, C_LCCM320__FLASH_START_ADDX, RM4_EEPROM__T::sFaultTree, RM4_EEPROM__T::u8Buffer, RM4_EEPROM__T::u8Dirty, RM4_EEPROM__T::u8Init, and vSIL3_FAULTTREE__Set_Flag().
Referenced by vRM4_EEPROM__WriteF32(), vRM4_EEPROM__WriteS32(), and vRM4_EEPROM__WriteU32().
Lint32 s32RM4_EEPROM__Read (Luint32 u32AddxOffset)
Read a S32.
Parameters
[in] u32AddxOffset The address offset
Returns
The read S32 value
SafeTool Function MD5:
2DB76D368C4DF5C964A6CE5452472787
SafeTool Function ID:
LCCM230R0.FILE.001.FUNC.004
References C_LCCM320__FLASH_START_ADDX, and s32SIL3_NUM_CONVERT__Array().
Luint32 u32RM4_EEPROM__Read (Luint32 u32AddxOffset)
Read a U32.
Parameters
[in] u32AddxOffset The address offset
Returns
The read U32 value
SafeTool Function MD5:
1DAFDCC57575EE4C81F803FAF4E8AC89
SafeTool Function ID:
LCCM230R0.FILE.001.FUNC.003
References C_LCCM320__FLASH_START_ADDX, and u32SIL3_NUM_CONVERT__Array().
void vRM4_EEPROM__Init (void)
Init the EEPROM system.
SafeTool Function MD5:
CD6A0D5CB034AB003282E97DA9B1EA1C
SafeTool Function ID:
LCCM230R0.FILE.001.FUNC.001
References C_LCCM320__FLASH_SIZE_U32S, C_LCCM320__FLASH_START_ADDX, RM4_EEPROM__T::u8Buffer, RM4_EEPROM__T::u8Dirty, and RM4_EEPROM__T::u8Init.
Referenced by vAPU__Init().
void vRM4_EEPROM__Read_U8Array (Luint8 u8Sector, Luint16 u16AddxInSector, Luint8 * pu8Array, Luint16 u16Length)
Reads an array from memory.
Parameters
[in] u16Length The length of data to read
[out] pu8Array Pointer to user array to hold the data
[in] u16AddxInSector The address offset in the sector
[in] u8Sector The memory sector to read from
SafeTool Function MD5:
F4FEDC85D64406C406C0980355FA48A4
SafeTool Function ID:
LCCM230R0.FILE.001.FUNC.010
References C_LCCM320__FLASH_SECTOR_0__START_ADDX, C_LCCM320__FLASH_SECTOR_1__START_ADDX, C_LCCM320__FLASH_SECTOR_2__START_ADDX, and C_LCCM320__FLASH_SECTOR_3__START_ADDX.
void vRM4_EEPROM__Write_U8Array (Luint8 u8Sector, Luint16 u16AddxInSector, Luint8 * pu8Array, Luint16 u16Length)
write an array directly to EEPROM
Parameters
[in] u16Length Length of the data to write.
[in] pu8Array Pointer to the buffer to write
[in] u16AddxInSector The address in the sector
[in] u8Sector The sector in bank 7
SafeTool Function MD5:
F17E9D4AAE44DAC05AD79167850194EE
SafeTool Function ID:
LCCM230R0.FILE.001.FUNC.009
References C_LCCM230__CORE__FAULT_INDEX__00, C_LCCM230__CORE__FAULT_INDEX__01, C_LCCM230__CORE__FAULT_INDEX__02, C_LCCM320__FLASH_BANK, C_LCCM320__FLASH_NUM_SECTORS, C_LCCM320__FLASH_SECTOR_0__START_ADDX, C_LCCM320__FLASH_SECTOR_1__START_ADDX, C_LCCM320__FLASH_SECTOR_2__START_ADDX, C_LCCM320__FLASH_SECTOR_3__START_ADDX, C_LCCM320__FLASH_SECTOR_SIZE_BYTES, C_LCCM320__FLASH_SIZE_U32S, RM4_EEPROM__T::sFaultTree, RM4_EEPROM__T::u8Buffer, RM4_EEPROM__T::u8Dirty, RM4_EEPROM__T::u8Init, and vSIL3_FAULTTREE__Set_Flag().
void vRM4_EEPROM__WriteF32 (Luint32 u32AddxOffset, Lfloat32 f32Value, Luint8 u8Delay)
Write a F32.
Parameters
[in] u8Delay Set to 1 to delay writing. User must manually perform
the save at a later time. This prevents flogging the EEPROM.
[in] f32Value Value
[in] u32AddxOffset Addx Multiple
SafeTool Function MD5:
87E97AC2C5B537FA5CF287F981B47065
SafeTool Function ID:
LCCM230R0.FILE.001.FUNC.008
References s16RM4_EEPROM__Save(), RM4_EEPROM__T::u8Buffer, RM4_EEPROM__T::u8Dirty, and vSIL3_NUM_CONVERT__Array_F32().
void vRM4_EEPROM__WriteS32 (Luint32 u32AddxOffset, Lint32 s32Value, Luint8 u8Delay)
Write a S32.
Parameters
[in] u8Delay Set to 1 to delay writing. User must manually perform the save at a later time. This prevents flogging the EEPROM.
[in] s32Value The write value
[in] u32AddxOffset Addx Multiple
SafeTool Function MD5:
55F18CAEAAE2151BC15FCAACFC20CB6A
SafeTool Function ID:
LCCM230R0.FILE.001.FUNC.007
References s16RM4_EEPROM__Save(), RM4_EEPROM__T::u8Buffer, RM4_EEPROM__T::u8Dirty, and vSIL3_NUM_CONVERT__Array_S32().
void vRM4_EEPROM__WriteU32 (Luint32 u32AddxOffset, Luint32 u32Value, Luint8 u8Delay)
Write a U32 to the eeprom buffer.
Parameters
[in] u8Delay Set to 1 to delay writing. User must manually perform the save at a later time. This prevents flogging the EEPROM.
[in] u32Value The value to write
[in] u32AddxOffset The address offset
SafeTool Function MD5:
48F19D5F9D78A42DEC51C97C8D32B1F2
SafeTool Function ID:
LCCM230R0.FILE.001.FUNC.006
References s16RM4_EEPROM__Save(), RM4_EEPROM__T::u8Buffer, RM4_EEPROM__T::u8Dirty, and vSIL3_NUM_CONVERT__Array_U32().
Variable Documentation
RM4_EEPROM__T sEEPROM