LFW615 (RLOOP - AUX PROP UNIT (APU)): ADC__DMA
ADC__DMA
RM4 » ADC
Functions
void vRM4_ADC_DMA__Setup_Interleave (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup, Luint32 u32ArrayDestAddx, Luint32 u32ArraySize, Luint32 u32NumChannels)
Setup the interleaver using DMA Creates a DMA packet to interleave n channels into an array of arrays (where the array is linear in memory) Uses the FIFO buffer and DMA trigger each group to transfer the entire groups samples into the user array.
void vRM4_ADC_DMA__Enable_SingleConversionDMA (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup)
19.6.1 DMA Request for Each Conversion Result Written to the Results Memory In this mode, the ADC module will generate the first DMA request as soon as a conversion result gets written to the group's results memory.
void vRM4_ADC_DMA__Enable_BlockTransferDMA (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup, Luint32 u32BlockSize)
19.6.2 DMA Request for a Fixed Number of Conversion Results This mode is enabled by setting both the group's DMA EN and the group's BLOCK XFER bits in the group's DMA control registers.
Variables
RM4_DMA__CONTROL_T m_ADCDMAControlPacket [3U]
Detailed Description
Function Documentation
void vRM4_ADC_DMA__Enable_BlockTransferDMA (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup, Luint32 u32BlockSize)
19.6.2 DMA Request for a Fixed Number of Conversion Results This mode is enabled by setting both the group's DMA EN and the group's BLOCK XFER bits in the group's DMA control registers.
In this mode, a DMA request will be generated for a specified number of conversion results being available in the group's results' memory. The number of conversion results desired are configured using the group's BLOCKS field in the control registers. For example, if the BLOCK count is configured for 10, then ADC module will generate a DMA request at the end of 10th conversion. DMA controller should complete reading out 10 data before next set of 10 conversions complete. NOTE: Usage of Block DMA transfers with Threshold Interrupts It is not recommended to enable the block DMA transfers for a group at the same time as the group threshold interrupt. The group's BLOCKS field is essentially the same as the group's THRESHOLD field in the group's interrupt control register described in Section 19.5.2.
Parameters
[in] u32BlockSize The transfer block size
[in] eGroup ADC group
[in] eADC ADC pointer
SafeTool Function MD5:
049445E01ADC1997BC62FE46EC6A2745
SafeTool Function ID:
LCCM414R0.FILE.015.FUNC.003
References ADC_GROUP__EVENT, ADC_GROUP__GROUP_1, and ADC_GROUP__GROUP_2.
void vRM4_ADC_DMA__Enable_SingleConversionDMA (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup)
19.6.1 DMA Request for Each Conversion Result Written to the Results Memory In this mode, the ADC module will generate the first DMA request as soon as a conversion result gets written to the group's results memory.
Subsequent writes to the results memory will cause DMA requests to be generated. This mode allows a smaller amount of ADC results memory to suffice for an application. This DMA request generation is enabled by setting the group's DMA EN bit in the group's DMA control register. The BLOCK XFER bit in this register must be left cleared (default) if a DMA request is desired to be generated for new results getting written to the results memory.
Parameters
[in] eGroup ## Desc ##
[in] eADC ## Desc ##
SafeTool Function MD5:
0796643ED2C5D356D1600E3CA2E0CEE5
SafeTool Function ID:
LCCM414R0.FILE.015.FUNC.002
References ADC_GROUP__EVENT, ADC_GROUP__GROUP_1, ADC_GROUP__GROUP_2, adcREG1, RM4_ADC__1, and RM4_ADC__2.
void vRM4_ADC_DMA__Setup_Interleave (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup, Luint32 u32ArrayDestAddx, Luint32 u32ArraySize, Luint32 u32NumChannels)
Setup the interleaver using DMA Creates a DMA packet to interleave n channels into an array of arrays (where the array is linear in memory) Uses the FIFO buffer and DMA trigger each group to transfer the entire groups samples into the user array.
Example:
 //maximum number of channel to sample
 #define C_CHANNELS 3
 //max DMA frame count is 1FFF = 8192
 #define C_SAMPLES 32
 //Sample array
 Luint16 u16Results[C_CHANNELS][C_SAMPLES];
 //setup interleaving
 vRM4_ADC_DMA__Setup_Interleave(RM4_ADC__1, ADC_GROUP__GROUP_1, (Luint32)&u16Results[0][0], C_SAMPLES, C_CHANNELS);
Parameters
[in] u32NumChannels Total chanels
[in] u32ArraySize Array length
[in] u32ArrayDestAddx Destination Index
[in] eGroup Conversion group
[in] eADC ADC Type
SafeTool Function MD5:
1DFDABDDCEA10CADD75B0C286256149F
SafeTool Function ID:
LCCM414R0.FILE.015.FUNC.001
References ACCESS_16_BIT, ADC_GROUP__EVENT, ADC_GROUP__GROUP_1, ADC_GROUP__GROUP_2, adcREG1, adcREG2, RM4_DMA__CONTROL_T::ADDMODERD, RM4_DMA__CONTROL_T::ADDMODEWR, ADDX_MODE__FIXED, ADDX_MODE__OFFSET, RM4_DMA__CONTROL_T::AUTOINIT, AUTOINIT_OFF, RM4_DMA__CONTROL_T::CHCTRL, RM4_DMA__CONTROL_T::DADD, DMA_CH0, DMA_HW, RM4_DMA__CONTROL_T::ELCNT, RM4_DMA__CONTROL_T::ELDOFFSET, RM4_DMA__CONTROL_T::ELSOFFSET, FRAME_TRANSFER, RM4_DMA__CONTROL_T::FRCNT, RM4_DMA__CONTROL_T::FRDOFFSET, RM4_DMA__CONTROL_T::FRSOFFSET, HW_REQ__ADC1_GROUP_1, INTERRUPT__BLOCK_TX_COMPLETE, RM4_DMA__CONTROL_T::PORTASGN, RM4_DMA__CONTROL_T::RDSIZE, RM4_ADC__1, RM4_ADC__2, RM4_DMA__CONTROL_T::SADD, RM4_DMA__CONTROL_T::TTYPE, vRM4_DMA__Enable(), vRM4_DMA__EnableInterrupt(), vRM4_DMA__RequestAssign(), vRM4_DMA__Set_ChannelEnable(), vRM4_DMA__Set_ControlPacket(), and RM4_DMA__CONTROL_T::WRSIZE.
Variable Documentation
RM4_DMA__CONTROL_T m_ADCDMAControlPacket[3U]