LFW615 (RLOOP - AUX PROP UNIT (APU)): EMAC__INTERRUPTS
EMAC__INTERRUPTS
RM4 » EMAC
Functions
void vRM4_EMAC_INT__TxISR (void)
Interrupt Handler for Core 0 Transmit interrupt.
void vRM4_EMAC_INT__RxISR (void)
Interrupt Handler for Core 0 Receive interrupt.
void vRM4_EMAC_INT__Enable_TxIntPulse (Luint32 u32ControlCore, Luint32 u32Channel)
Enables the TXPULSE Interrupt Generation.
void vRM4_EMAC_INT__Disable_TxIntPulse (Luint32 u32ControlCore, Luint32 u32Channel)
Disables the TXPULSE Interrupt Generation.
void vRM4_EMAC_INT__Enable_RxIntPulse (Luint32 u32ControlCore, Luint32 u32Channel)
Enables the RXPULSE Interrupt Generation.
void vRM4_EMAC_INT__Disable_RxIntPulse (Luint32 u32ControlCore, Luint32 u32Channel)
Disables the RXPULSE Interrupt Generation.
void vRM4_EMAC_INT__CoreIntAck (Luint32 u32EOIFlag)
Acknowledges an interrupt processed to the EMAC Control Core.
Variables
volatile int countEMACCore0TxIsr = 0U
volatile int countEMACCore0RxIsr = 0U
Detailed Description
Function Documentation
void vRM4_EMAC_INT__CoreIntAck (Luint32 u32EOIFlag)
Acknowledges an interrupt processed to the EMAC Control Core.
Acknowledges an interrupt processed to the EMAC Control Core. The application software must acknowledge the EMAC control module after processing packets by writing the appropriate C0TX key to the EMAC End-Of-Interrupt Vector register (MACEOIVECTOR). See Section 28.5.12 for the acknowledge key values.
Parameters
[in] u32EOIFlag u32EOIFlag can take the following values: EMAC_INT_CORE0_TX - Core 0 TX Interrupt EMAC_INT_CORE1_TX - Core 1 TX Interrupt EMAC_INT_CORE2_TX - Core 2 TX Interrupt EMAC_INT_CORE0_RX - Core 0 RX Interrupt EMAC_INT_CORE1_RX - Core 1 RX Interrupt EMAC_INT_CORE2_RX - Core 2 RX Interrupt
SafeTool Function MD5:
C301E3EF23044506E9CABD61E90263EE
SafeTool Function ID:
LCCM254R0.FILE.010.FUNC.007
References EMAC_BASE, EMAC_MACEOIVECTOR, and HWREG.
Referenced by vRM4_EMAC_LINK__Process(), vRM4_EMAC_RX__RxIntHandler(), and vRM4_EMAC_TX__Tx_IntHandler().
void vRM4_EMAC_INT__Disable_RxIntPulse (Luint32 u32ControlCore, Luint32 u32Channel)
Disables the RXPULSE Interrupt Generation.
Parameters
[in] u32Channel The EMAC channel
[in] u32ControlCore The value
SafeTool Function MD5:
02DF2FA663F1FD81E4DF7DCE7BD26D7A
SafeTool Function ID:
LCCM254R0.FILE.010.FUNC.006
References EMAC_BASE, EMAC_CTRL_BASE, EMAC_CTRL_CnRXEN, EMAC_RXINTMASKCLEAR, and HWREG.
void vRM4_EMAC_INT__Disable_TxIntPulse (Luint32 u32ControlCore, Luint32 u32Channel)
Disables the TXPULSE Interrupt Generation.
Parameters
[in] u32Channel The EMAC channel
[in] u32ControlCore The value
SafeTool Function MD5:
3EA539E78A6C44DDFEC660668D4A492C
SafeTool Function ID:
LCCM254R0.FILE.010.FUNC.004
References EMAC_BASE, EMAC_CTRL_BASE, EMAC_CTRL_CnTXEN, EMAC_TXINTMASKCLEAR, and HWREG.
void vRM4_EMAC_INT__Enable_RxIntPulse (Luint32 u32ControlCore, Luint32 u32Channel)
Enables the RXPULSE Interrupt Generation.
Parameters
[in] u32Channel The EMAC channel
[in] u32ControlCore The value
SafeTool Function MD5:
271748BC60ACACBF713F0266D9439CBD
SafeTool Function ID:
LCCM254R0.FILE.010.FUNC.005
References EMAC_BASE, EMAC_CTRL_BASE, EMAC_CTRL_CnRXEN, EMAC_RXINTMASKSET, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC_INT__Enable_TxIntPulse (Luint32 u32ControlCore, Luint32 u32Channel)
Enables the TXPULSE Interrupt Generation.
Parameters
[in] u32Channel The EMAC channel
[in] u32ControlCore The value
SafeTool Function MD5:
4EDEB7CF1982F93551CB5CB78467A101
SafeTool Function ID:
LCCM254R0.FILE.010.FUNC.003
References EMAC_BASE, EMAC_CTRL_BASE, EMAC_CTRL_CnTXEN, EMAC_TXINTMASKSET, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC_INT__RxISR (void)
Interrupt Handler for Core 0 Receive interrupt.
SafeTool Function MD5:
EE7B977116572E58740EDC8D5906FDEF
SafeTool Function ID:
LCCM254R0.FILE.010.FUNC.002
References countEMACCore0RxIsr, and vRM4_EMAC_RX__RxIntHandler().
void vRM4_EMAC_INT__TxISR (void)
Interrupt Handler for Core 0 Transmit interrupt.
SafeTool Function MD5:
BB61598D47AA68E2503813CB8819B0A0
SafeTool Function ID:
LCCM254R0.FILE.010.FUNC.001
References countEMACCore0TxIsr, and vRM4_EMAC_TX__Tx_IntHandler().
Variable Documentation
volatile int countEMACCore0RxIsr = 0U
Referenced by vRM4_EMAC_INT__RxISR().
volatile int countEMACCore0TxIsr = 0U
Referenced by vRM4_EMAC_INT__TxISR().