LFW615 (RLOOP - AUX PROP UNIT (APU)): DMA__CORE
DMA__CORE
RM4 » DMA
Functions
void vRM4_DMA__Init (void)
Init the DMA engine Call this at power on Reset.
void vRM4_DMA__Enable (void)
This function brings DMA out of reset.
void vRM4_DMA__Set_ChannelBusy (RM4_DMA__CHANNEL_E eChannel)
Set the channel busy flag and indicate that the channel is busy.
void vRM4_DMA__Clear_ChannelBusy (RM4_DMA__CHANNEL_E eChannel)
Clear the channel busy flag.
Luint8 u8RM4_DMA__IsChannelBusy (RM4_DMA__CHANNEL_E eChannel)
Gets if a channel is busy.
void vRM4_DMA__Disable (void)
This function disables DMA module.
void vRM4_DMA__RequestAssign (RM4_DMA__CHANNEL_E eChannel, RM4_DMA__HW_REQUEST_TYPE__T eRequestLine)
Assign DMA request lines to channels.
Luint32 u32RM4_DMA__Get_Request (RM4_DMA__CHANNEL_E eChannel)
Gets the request line number mapped to the selected channel.
void vRM4_DMA__Set_ControlPacket (RM4_DMA__CHANNEL_E eChannel, RM4_DMA__CONTROL_T g_dmaCTRLPKT)
Set control packet.
Luint32 u32RM4_DMA__Config_ControlPacket (RM4_DMA__CONTROL_T *g_dmaCTRLPKT, Luint32 u32SourceAddx, Luint32 u32DestAddx, Luint32 u32TransferSize)
Configuring dma control packet stack After configuring the stack the control packet needs to be set by calling vRM4_DMA__Set_ControlPacket()
void vRM4_DMA__Set_ChannelEnable (RM4_DMA__CHANNEL_E eChannel, RM4_DMA__REQUEST_TYPE_T type)
This function enables the DMA channel for hardware or software triggering.
void vRM4_DMA__Set_Priority (RM4_DMA__CHANNEL_E eChannel, RM4_DMA__PRIORITY_T priority)
Assign Priority to the channel.
void vRM4_DMA__EnableInterrupt (RM4_DMA__CHANNEL_E eChannel, RM4_DMA__INTERRUPT_T eIntType)
This function enables the selected interrupt for the selected channel.
void vRM4_DMA__DisableInterrupt (RM4_DMA__CHANNEL_E eChannel, RM4_DMA__INTERRUPT_T eIntType)
This function disables the selected interrupt for the selected channel.
void vRM4_DMA__DefineRegion (RM4_DMA__REGION_T eRegion, Luint32 u32StartAddx, Luint32 u32EndAddx)
Configure start and end address of the region.
void vRM4_DMA__EnableRegion (RM4_DMA__REGION_T eRegion, RM4_DMA__REGION_ACCESS_T eAccess, Luint8 u8InterruptEnable)
This function enables the selected region with selected access permission with or without interrupt enable.
void vRM4_DMA__DisableRegion (RM4_DMA__REGION_T eRegion)
This function disables the selected region(no address checking done).
void vRM4_DMA__EnableParityCheck (void)
Enable Parity Check.
void vRM4_DMA__DisableParityCheck (void)
Disable Parity Check.
Variables
struct _strRM4DMA sRM4DMA
Detailed Description
Function Documentation
Luint32 u32RM4_DMA__Config_ControlPacket (RM4_DMA__CONTROL_T * g_dmaCTRLPKT, Luint32 u32SourceAddx, Luint32 u32DestAddx, Luint32 u32TransferSize)
Configuring dma control packet stack After configuring the stack the control packet needs to be set by calling vRM4_DMA__Set_ControlPacket()
Parameters
[in] u32TransferSize The size of the transfer in RD/WR Size
[in] u32DestAddx The destination address
[in] u32SourceAddx The source address
References ACCESS_16_BIT, RM4_DMA__CONTROL_T::ADDMODERD, RM4_DMA__CONTROL_T::ADDMODEWR, ADDX_MODE__FIXED, ADDX_MODE__POST_INCREMENT, RM4_DMA__CONTROL_T::AUTOINIT, AUTOINIT_OFF, BLOCK_TRANSFER, RM4_DMA__CONTROL_T::CHCTRL, RM4_DMA__CONTROL_T::DADD, RM4_DMA__CONTROL_T::ELCNT, RM4_DMA__CONTROL_T::ELDOFFSET, RM4_DMA__CONTROL_T::ELSOFFSET, RM4_DMA__CONTROL_T::FRCNT, RM4_DMA__CONTROL_T::FRDOFFSET, RM4_DMA__CONTROL_T::FRSOFFSET, RM4_DMA__CONTROL_T::PORTASGN, RM4_DMA__CONTROL_T::RDSIZE, RM4_DMA__CONTROL_T::SADD, RM4_DMA__CONTROL_T::TTYPE, and RM4_DMA__CONTROL_T::WRSIZE.
Luint32 u32RM4_DMA__Get_Request (RM4_DMA__CHANNEL_E eChannel)
Gets the request line number mapped to the selected channel.
Parameters
[in] eChannel The DMA channel
SafeTool Function MD5:
17871C8018D9FBB8260DAA8360306DCE
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.007
References dmaREG.
Luint8 u8RM4_DMA__IsChannelBusy (RM4_DMA__CHANNEL_E eChannel)
Gets if a channel is busy.
Parameters
[in] eChannel The channel index
Returns
1 = busy
0 = not busy
SafeTool Function MD5:
BF00D0D0473091249B2389D98733AB64
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.004
References _strRM4DMA::sChannel, sRM4DMA, and _strRM4DMA::u8Busy.
void vRM4_DMA__Clear_ChannelBusy (RM4_DMA__CHANNEL_E eChannel)
Clear the channel busy flag.
Parameters
[in] eChannel The DMA channel
SafeTool Function MD5:
0971D35EBD7844A6C3909546341503A6
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.024
References _strRM4DMA::sChannel, sRM4DMA, and _strRM4DMA::u8Busy.
void vRM4_DMA__DefineRegion (RM4_DMA__REGION_T eRegion, Luint32 u32StartAddx, Luint32 u32EndAddx)
Configure start and end address of the region.
Parameters
[in] u32EndAddx End address of the region
[in] u32StartAddx Start address of the the region
[in] eRegion Memory Region
DMA_REGION0
DMA_REGION1
DMA_REGION2
DMA_REGION3
SafeTool Function MD5:
CBDD1F34C479AD693C4BA095C83A80D6
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.014
References dmaREG.
void vRM4_DMA__Disable (void)
This function disables DMA module.
SafeTool Function MD5:
5FD747D806C93AFFBC40742A3A7C859D
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.005
References DMA_GCTRL_BUSBUSY, and dmaREG.
void vRM4_DMA__DisableInterrupt (RM4_DMA__CHANNEL_E eChannel, RM4_DMA__INTERRUPT_T eIntType)
This function disables the selected interrupt for the selected channel.
Parameters
[in] eIntType The type of interrupt to set
INTERRUPT__FRAME_TX_COMPLETE: Frame Transfer Complete Interrupt will be disabled for the selected channel
INTERRUPT__LAST_FRAME_START: Last Frame Transfer Started Interrupt will be disabled for the selected channel
INTERRUPT__HALF_BLOCK_COMPLETE: First Half Of Block Complete Interrupt will be disabled for the selected channel
INTERRUPT__BLOCK_TX_COMPLETE: Block transfer complete Interrupt will be disabled for the selected channel
BER: Bus Error Interrupt will be disabled for the selected channel
Parameters
[in] eChannel The DMA channel to use
SafeTool Function MD5:
1886D0DC92E752D7EE149277695A3CE8
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.013
References dmaREG, INTERRUPT__BLOCK_TX_COMPLETE, INTERRUPT__FRAME_TX_COMPLETE, INTERRUPT__HALF_BLOCK_COMPLETE, and INTERRUPT__LAST_FRAME_START.
void vRM4_DMA__DisableParityCheck (void)
Disable Parity Check.
SafeTool Function MD5:
FECF1199F7082A452C68B014B6ED09D8
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.018
References dmaREG.
void vRM4_DMA__DisableRegion (RM4_DMA__REGION_T eRegion)
This function disables the selected region(no address checking done).
Parameters
[in] region Memory Region
DMA_REGION0
DMA_REGION1
DMA_REGION2
DMA_REGION3
SafeTool Function MD5:
13BF52E1D58060FE6BC14EFC872834C4
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.016
References dmaREG.
void vRM4_DMA__Enable (void)
This function brings DMA out of reset.
Note
This may be needed for devices like the EMAC
SafeTool Function MD5:
C23EB70178E4483AD79335AFBD58D4D2
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.002
References dmaREG.
Referenced by vRM4_ADC_DMA__Setup_Interleave().
void vRM4_DMA__EnableInterrupt (RM4_DMA__CHANNEL_E eChannel, RM4_DMA__INTERRUPT_T eIntType)
This function enables the selected interrupt for the selected channel.
Parameters
[in] eIntType Interrupt to be enabled
INTERRUPT__FRAME_TX_COMPLETE: Frame Transfer Complete Interrupt will be disabled for the selected channel
INTERRUPT__LAST_FRAME_START: Last Frame Transfer Started Interrupt will be disabled for the selected channel
INTERRUPT__HALF_BLOCK_COMPLETE: First Half Of Block Complete Interrupt will be disabled for the selected channel
INTERRUPT__BLOCK_TX_COMPLETE: Block transfer complete Interrupt will be disabled for the selected channel
BER: Bus Error Interrupt will be disabled for the selected channel
[in] eChannel channel DMA channel
SafeTool Function MD5:
C1EB50D5A9DBA3EB1BDAA8CBDD0AEAD3
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.012
References dmaREG, INTERRUPT__BLOCK_TX_COMPLETE, INTERRUPT__FRAME_TX_COMPLETE, INTERRUPT__HALF_BLOCK_COMPLETE, and INTERRUPT__LAST_FRAME_START.
Referenced by vRM4_ADC_DMA__Setup_Interleave().
void vRM4_DMA__EnableParityCheck (void)
Enable Parity Check.
SafeTool Function MD5:
0F56DFB37264267FBAEE57B3E20B6ADB
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.017
References dmaREG.
void vRM4_DMA__EnableRegion (RM4_DMA__REGION_T eRegion, RM4_DMA__REGION_ACCESS_T eAccess, Luint8 u8InterruptEnable)
This function enables the selected region with selected access permission with or without interrupt enable.
Parameters
[in] u8InterruptEnable Interrupt to be enabled or not
INTERRUPT_ENABLE : Enable interrupt for the selected region
INTERRUPT_DISABLE: Disable interrupt for the selected region
[in] eAccess Access permission of the selected region
FULLACCESS
READONLY
WRITEONLY
NOACCESS
[in] eRegion Memory Region
DMA_REGION0
DMA_REGION1
DMA_REGION2
DMA_REGION3
SafeTool Function MD5:
6C3B0515DBC0249CCD4F5FC84E5AAE2D
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.015
References dmaREG.
void vRM4_DMA__Init (void)
Init the DMA engine Call this at power on Reset.
SafeTool Function MD5:
1E44C5E67B74EF34C9B99CDA56B4546D
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.001
References DMA_CH0, DMA_CH1, _strRM4DMA::sChannel, sRM4DMA, and _strRM4DMA::u8Busy.
Referenced by vRM4_SYSTEM__After_STC().
void vRM4_DMA__RequestAssign (RM4_DMA__CHANNEL_E eChannel, RM4_DMA__HW_REQUEST_TYPE__T eRequestLine)
Assign DMA request lines to channels.
Parameters
[in] eRequestLine DMA request line
[in] eChannel DMA channel
SafeTool Function MD5:
C05F5F371F14393A302DB7E894224247
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.006
References dmaREG.
Referenced by vRM4_ADC_DMA__Setup_Interleave().
void vRM4_DMA__Set_ChannelBusy (RM4_DMA__CHANNEL_E eChannel)
Set the channel busy flag and indicate that the channel is busy.
Parameters
[in] eChannel The channel
SafeTool Function MD5:
94B8CDD8450E9CFAB040D7D8320423FE
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.003
References _strRM4DMA::sChannel, sRM4DMA, and _strRM4DMA::u8Busy.
void vRM4_DMA__Set_ChannelEnable (RM4_DMA__CHANNEL_E eChannel, RM4_DMA__REQUEST_TYPE_T type)
This function enables the DMA channel for hardware or software triggering.
Parameters
[in] type Type of hardware triggering DMA_HW: Enables the selected DMA channel for hardware triggering DMA_SW: Enables the selected DMA channel for software triggering
[in] eChannel The DMA channel
SafeTool Function MD5:
3388553BA79F1792D6BDD08BC3388492
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.010
References DMA_HW, DMA_SW, dmaREG, _strRM4DMA::sChannel, sRM4DMA, and _strRM4DMA::u8Busy.
Referenced by vRM4_ADC_DMA__Setup_Interleave().
void vRM4_DMA__Set_ControlPacket (RM4_DMA__CHANNEL_E eChannel, RM4_DMA__CONTROL_T g_dmaCTRLPKT)
Set control packet.
Parameters
[in] g_dmaCTRLPKT Externally set control packet
[in] eChannel The DMA channel
SafeTool Function MD5:
716AED0F5AE86843A0426C267CA2EB9E
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.008
References RM4_DMA__CONTROL_T::ADDMODERD, RM4_DMA__CONTROL_T::ADDMODEWR, RM4_DMA__CONTROL_T::AUTOINIT, RM4_DMA__CONTROL_T::CHCTRL, RM4_DMA__CONTROL_T::DADD, dmaRAMREG, dmaREG, RM4_DMA__CONTROL_T::ELCNT, RM4_DMA__CONTROL_T::ELDOFFSET, RM4_DMA__CONTROL_T::ELSOFFSET, RM4_DMA__CONTROL_T::FRCNT, RM4_DMA__CONTROL_T::FRDOFFSET, RM4_DMA__CONTROL_T::FRSOFFSET, RM4_DMA__CONTROL_T::PORTASGN, RM4_DMA__CONTROL_T::RDSIZE, RM4_DMA__CONTROL_T::SADD, RM4_DMA__CONTROL_T::TTYPE, and RM4_DMA__CONTROL_T::WRSIZE.
Referenced by vRM4_ADC_DMA__Setup_Interleave().
void vRM4_DMA__Set_Priority (RM4_DMA__CHANNEL_E eChannel, RM4_DMA__PRIORITY_T priority)
Assign Priority to the channel.
Parameters
[in] priority priority Priority queue to which channel needs to be assigned PRIORITY_LOW : The selected channel will be assigned to low priority queue PRIORITY_HIGH: The selected channel will be assigned to high priority queue
[in] eChannel The DMA channel
SafeTool Function MD5:
1E10051AFBA09A56BC11100EA07F0A13
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.011
References dmaREG, and PRIORITY_LOW.
Variable Documentation
struct _strRM4DMA sRM4DMA
Referenced by u8RM4_DMA__IsChannelBusy(), vRM4_DMA__Clear_ChannelBusy(), vRM4_DMA__Init(), vRM4_DMA__Set_ChannelBusy(), vRM4_DMA__Set_ChannelEnable(), vRM4_DMA_ISR__BTCAInterrupt(), and vRM4_DMA_ISR__FTCAInterrupt().