LFW615 (RLOOP - AUX PROP UNIT (APU)): SYSTEM__STARTUP
SYSTEM__STARTUP
RM4 » SYSTEM
Typedefs
typedef void(* handler_fptr) (const Luint8 *in, Luint8 *out)
Functions
void copy_in (void *binit)
void main (void)
void exit (void)
void _c_int00 ()
Main program entry point after reset.
void vRM4_SYSTEM__After_STC (void)
Variables
struct _strRM4BIST sBIST
Luint32 __TI_Handler_Table_Base
Luint32 __TI_Handler_Table_Limit
Luint32 __TI_CINIT_Base
Luint32 __TI_CINIT_Limit
Luint32 __TI_PINIT_Base
Luint32 __TI_PINIT_Limit
Luint32 * __binit__
Detailed Description
Typedef Documentation
typedef void(* handler_fptr) (const Luint8 *in, Luint8 *out)
Function Documentation
void _c_int00 ()
Main program entry point after reset.
SafeTool Function MD5:
3D7300D39B50B7A9FD2166D4AA524CE9
SafeTool Function ID:
LCCM219R0.FILE.005.FUNC.001
References _errata_CORTEXR4_57_(), _errata_CORTEXR4_66_(), _mpuInit_(), _rm4_system_core__EnableEventBusExport_(), _rm4_system_core__esmCcmErrorsClear_(), _rm4_system_core__InitRegisters_(), _rm4_system_core__InitStackPointer_(), _rm57_system_core__EnableEventBusExport_(), _rm57_system_core__InitRegisters_(), _rm57_system_core__InitStackPointer_(), C_RM4SYSTEM__CPU_RESET, C_RM4SYSTEM__DEVICE_ID_REV, C_RM4SYSTEM__ICEPICK_RESET, C_RM4SYSTEM__OSC_FAILURE_RESET, C_RM4SYSTEM__POWERON_RESET, C_RM4SYSTEM__SW_RESET, C_RM4SYSTEM__SYS_EXCEPTION, C_RM4SYSTEM__WATCHDOG_RESET, C_RM4SYSTEM__WATCHDOG_STATUS, esmREG, PBIST_TripleReadFast, PBIST_TripleReadSlow, STC_INTERVAL, STC_MAX_TIMEOUT, STC_ROM_PBIST_RAM_GROUP, stcREG, u8RM4_BIST__IsTestCompleted(), u8RM4_BIST__IsTestPassed(), vRM4_BIST__errata_PBIST_4(), vRM4_BIST__Run(), vRM4_BIST__SelfCheck(), vRM4_BIST__Stop(), vRM4_SELFTEST__CPU_Test(), vRM4_SELFTEST__Init(), vRM4_SELFTEST__STC_Check(), vRM4_SYSTEM__After_STC(), vRM4_SYSTEM__Init(), and vRM57_BIST__errata_PBIST_4().
void copy_in (void * binit)
Referenced by vRM4_SYSTEM__After_STC().
void exit (void)
Referenced by vRM4_SYSTEM__After_STC().
void main (void)
References vAPU__Init(), and vAPU__Process().
Referenced by vRM4_SYSTEM__After_STC().
void vRM4_SYSTEM__After_STC (void)
References __binit__, __TI_CINIT_Base, __TI_CINIT_Limit, __TI_Handler_Table_Base, __TI_Handler_Table_Limit, __TI_PINIT_Base, __TI_PINIT_Limit, _mpuInit_(), _rm4_system_core__DisableRamEcc_(), _rm4_system_core__EnableIrqVicOffset_(), _rm4_system_core__EnableRamEcc_(), _rm57_system_core__EnableIrqVicOffset_(), C_LCCM227__CORE__FAULT_INDEX__00, C_LCCM227__CORE__FAULT_INDEX__02, copy_in(), exit(), main(), mibspiREG1, mibspiREG3, mibspiREG5, PBIST_March13N_DP, PBIST_March13N_SP, rtiREG1, sBIST, _strRM4BIST::sFaultFlags, u8RM4_BIST__IsTestCompleted(), u8RM4_BIST__IsTestPassed(), vRM4_BIST__Init(), vRM4_BIST__Run(), vRM4_BIST__Stop(), vRM4_DMA__Init(), vRM4_ESM__Init(), vRM4_SELFTEST__ADC1_ParityCheck(), vRM4_SELFTEST__ADC2_ParityCheck(), vRM4_SELFTEST__CAN1_ParityCheck(), vRM4_SELFTEST__CAN2_ParityCheck(), vRM4_SELFTEST__CAN3_ParityCheck(), vRM4_SELFTEST__CCM_Check(), vRM4_SELFTEST__Check_RAMECC(), vRM4_SELFTEST__DisableParity(), vRM4_SELFTEST__DMA_ParityCheck(), vRM4_SELFTEST__EnableParity(), vRM4_SELFTEST__MemoryInit(), vRM4_SELFTEST__MIBSPI1_ParityCheck(), vRM4_SELFTEST__MIBSPI3_ParityCheck(), vRM4_SELFTEST__MIBSPI5_ParityCheck(), vRM4_SELFTEST__N2HET1_ParityCheck(), vRM4_SELFTEST__N2HET2_ParityCheck(), vRM4_SELFTEST__VIM_ParityCheck(), vRM4_VIM__Init(), and vSIL3_FAULTTREE__Set_Flag().
Referenced by _c_int00().
Variable Documentation
Luint32* __binit__
Referenced by vRM4_SYSTEM__After_STC().
Luint32 __TI_CINIT_Base
Referenced by vRM4_SYSTEM__After_STC().
Luint32 __TI_CINIT_Limit
Referenced by vRM4_SYSTEM__After_STC().
Luint32 __TI_Handler_Table_Base
Referenced by vRM4_SYSTEM__After_STC().
Luint32 __TI_Handler_Table_Limit
Referenced by vRM4_SYSTEM__After_STC().
Luint32 __TI_PINIT_Base
Referenced by vRM4_SYSTEM__After_STC().
Luint32 __TI_PINIT_Limit
Referenced by vRM4_SYSTEM__After_STC().
struct _strRM4BIST sBIST
Referenced by u32RM4_BIST__Get_FaultFlags(), vRM4_BIST__Init(), vRM4_BIST__SelfCheck(), and vRM4_SYSTEM__After_STC().