LFW615 (RLOOP - AUX PROP UNIT (APU)): NUMERICAL__CORE
NUMERICAL__CORE
MULTICORE » NUMERICAL
Functions
void vSIL3_NUM__Init (void)
Init any requirements of the numerical module.
Luint16 u16SIL3_NUM_CONVERT__Array (const Luint8 *pu8Array)
converts an array item to a U16
Luint16 u16SIL3_NUM_CONVERT__Array_2 (const Luint8 *pu8Array)
ToDo.
Luint16 u16SIL3_NUM_CONVERT__Array_LITTLEENDIAN (const Luint8 *pu8Array)
Convert an array to a U16, force little endian mode.
void vSIL3_NUM_CONVERT__Array_U16 (Luint8 *pu8Array, Luint16 u16Value)
Convert a U16 into an array.
void vSIL3_NUM_CONVERT__Array_U16_LITTLEENDIAN (Luint8 *pu8Array, Luint16 u16Value)
Convert a U16 into an array and force little endian.
void vSIL3_NUM_CONVERT__Array_U16_BIGENDIAN (Luint8 *pu8Array, Luint16 u16Value)
Convert a U16 into an array and force use big endian.
Lint16 s16SIL3_NUM_CONVERT__Array (const Luint8 *pu8Array)
Convert an array to a s16.
Lint16 s16SIL3_NUM_CONVERT__Array_2 (const Luint8 *pu8Array)
ToDo.
void vSIL3_NUM_CONVERT__Array_S16 (Luint8 *pu8Array, Lint16 s16Value)
Convert a S16 value into an array.
Luint32 u32SIL3_NUM_CONVERT__Array (const Luint8 *pu8Array)
Convert array to U32.
Luint32 u32SIL3_NUM_CONVERT__Array_2 (const Luint8 *pu8Array)
ToDo.
Luint32 u32SIL3_NUM_CONVERT__Array_LITTLEENDIAN (const Luint8 *pu8Array)
Convert an array into a U32.
Luint32 u32SIL3_NUM_CONVERT__Array_BIGENDIAN (const Luint8 *pu8Array)
Convert an array to a U32, force bigendian mode.
void vSIL3_NUM_CONVERT__Array_U32 (Luint8 *pu8Array, Luint32 u32Value)
Put a U32 value into an array.
void vSIL3_NUM_CONVERT__Array_U32_LITTLEENDIAN (Luint8 *pu8Array, Luint32 u32Value)
Put a U32 value into an array and force little endian mode.
void vSIL3_NUM_CONVERT__Array_U32_BIGENDIAN (Luint8 *pu8Array, Luint32 u32Value)
Convert a U32 value into an array and force bigendian mode.
Lint32 s32SIL3_NUM_CONVERT__Array (const Luint8 *pu8Array)
Convert array to s32.
void vSIL3_NUM_CONVERT__Array_S32 (Luint8 *pu8Array, Lint32 s32Value)
Conver a S32 value into an array.
Lfloat32 f32SIL3_NUM_CONVERT__Array (const Luint8 *pu8Array)
Convert an array to a F32.
Lfloat32 f32SIL3_NUM_CONVERT__Array_BIGENDIAN (const Luint8 *pu8Array)
Convert an array to a F32 and force bigendian mode.
void vSIL3_NUM_CONVERT__Array_F32 (Luint8 *pu8Array, Lfloat32 f32Value)
Convert an F32 value and store it in an array.
void vSIL3_NUM_CONVERT__Array_F32_LITTLEENDIAN (Luint8 *pu8Array, Lfloat32 f32Value)
Convter a F32 value and store it in an array, force littleendian mode.
void vSIL3_NUM_CONVERT__Array_F64 (Luint8 *pu8Array, Lfloat64 f64Value)
Convert a F64 value and place it in an array.
Lfloat64 f64SIL3_NUM_CONVERT__Array (const Luint8 *pu8Array)
Convert an array of data into a F64.
void vSIL3_NUM_CONVERT__Array_U64 (Luint8 *pu8Array, Luint64 u64Value)
ToDo.
Detailed Description
Function Documentation
Lfloat32 f32SIL3_NUM_CONVERT__Array (const Luint8 * pu8Array)
Convert an array to a F32.
Parameters
[in] pu8Array Pointer to the array to hold the data
Returns
Returns the F32 converted value
SafeTool Function MD5:
E49C25CBAE84E01F4AADB785E9F4245D
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.006
Referenced by f32RM4_EEPROM__Read().
Lfloat32 f32SIL3_NUM_CONVERT__Array_BIGENDIAN (const Luint8 * pu8Array)
Convert an array to a F32 and force bigendian mode.
Parameters
[in] *pu8Array Pointer to the array of data to conver
Returns
The packed F32
SafeTool Function MD5:
39FE6AD0391233E29D7D723AEE730C67
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.023
Lfloat64 f64SIL3_NUM_CONVERT__Array (const Luint8 * pu8Array)
Convert an array of data into a F64.
Parameters
[in] *pu8Array Pointer to the input data
Returns
The computed F64 value
SafeTool Function MD5:
C3C13159A1DDA22AAED4BAD8C43EBDC6
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.026
Lint16 s16SIL3_NUM_CONVERT__Array (const Luint8 * pu8Array)
Convert an array to a s16.
Parameters
[in] pu8Array Pointer to the array to hold the data
Returns
Returns the converted value
SafeTool Function MD5:
343846380C1C6DCD43609DC99581428B
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.003
Lint16 s16SIL3_NUM_CONVERT__Array_2 (const Luint8 * pu8Array)
ToDo.
Parameters
[in] Luint8 ## Desc ##
SafeTool Function MD5:
BE0AFAC8CAC4073DE330DCB587E1FCA6
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.028
Lint32 s32SIL3_NUM_CONVERT__Array (const Luint8 * pu8Array)
Convert array to s32.
Parameters
[in] pu8Array Constant pointer to the array of data
Returns
A signed 32
SafeTool Function MD5:
4C8F951197CC61C58553D21D7A4BDE0E
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.005
Referenced by s32RM4_EEPROM__Read().
Luint16 u16SIL3_NUM_CONVERT__Array (const Luint8 * pu8Array)
converts an array item to a U16
Parameters
[in] pu8Array Pointer to the array to hold the data
Returns
Returns the converted value
SafeTool Function MD5:
AD41C0793090D84675D6BCA561EE6D0D
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.002
Luint16 u16SIL3_NUM_CONVERT__Array_2 (const Luint8 * pu8Array)
ToDo.
Parameters
[in] Luint8 ## Desc ##
SafeTool Function MD5:
4B8C803B13A431ACE7E7F13B07CAE0D3
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.027
Luint16 u16SIL3_NUM_CONVERT__Array_LITTLEENDIAN (const Luint8 * pu8Array)
Convert an array to a U16, force little endian mode.
Parameters
[in] *pu8Array Pointer to the input array
Returns
The converted U16 value
SafeTool Function MD5:
51FFFB35A168070DEE16BA6EE7882076
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.016
Luint32 u32SIL3_NUM_CONVERT__Array (const Luint8 * pu8Array)
Convert array to U32.
Parameters
[in] pu8Array Constant pointer to array
Returns
Returns the converted value
SafeTool Function MD5:
DAB3C924B36654841AADB5A07CFDF33C
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.004
Referenced by u32RM4_EEPROM__Read(), and vAPU_ETH__RxSafeUDP().
Luint32 u32SIL3_NUM_CONVERT__Array_2 (const Luint8 * pu8Array)
ToDo.
Parameters
[in] Luint8 ## Desc ##
SafeTool Function MD5:
69DAB771D1602FE6F3BC725B723BC9FC
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.029
Luint32 u32SIL3_NUM_CONVERT__Array_BIGENDIAN (const Luint8 * pu8Array)
Convert an array to a U32, force bigendian mode.
Parameters
[in] *pu8Array Pointer to the input array data
Returns
The U32 value made from the array
SafeTool Function MD5:
C41FF41F10904B178DDA6FBF9F158D95
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.020
Luint32 u32SIL3_NUM_CONVERT__Array_LITTLEENDIAN (const Luint8 * pu8Array)
Convert an array into a U32.
Parameters
[in] *pu8Array Pointer to the array of data to conver
Returns
The U32 value made from the array
SafeTool Function MD5:
B4860417CC578E418C345F8C25F15EFF
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.019
void vSIL3_NUM__Init (void)
Init any requirements of the numerical module.
SafeTool Function MD5:
2B0C4CC8DE62A9F09FF549511CCA59CF
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.001
void vSIL3_NUM_CONVERT__Array_F32 (Luint8 * pu8Array, Lfloat32 f32Value)
Convert an F32 value and store it in an array.
Parameters
[in] pu8Array Pointer to the array to hold the data
[in] f32value The value to convert into an array
SafeTool Function MD5:
7E6B3B0EA19D1FAC42A49490228B92F3
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.011
Referenced by vRM4_EEPROM__WriteF32().
void vSIL3_NUM_CONVERT__Array_F32_LITTLEENDIAN (Luint8 * pu8Array, Lfloat32 f32Value)
Convter a F32 value and store it in an array, force littleendian mode.
Parameters
[in] f32Value The value to convert
[in] *pu8Array Pointer to the array to hold the data
SafeTool Function MD5:
760ADF04447FAB413ED433BAFCC293DA
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.024
void vSIL3_NUM_CONVERT__Array_F64 (Luint8 * pu8Array, Lfloat64 f64Value)
Convert a F64 value and place it in an array.
Parameters
[in] f64Value The input value to place in the array
[in] *pu8Array Pointer to the array to hold the converted data
SafeTool Function MD5:
7B35CD2821996EFF13E12F8E39E55C18
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.025
void vSIL3_NUM_CONVERT__Array_S16 (Luint8 * pu8Array, Lint16 s16Value)
Convert a S16 value into an array.
Parameters
[in] pu8Array Pointer to the array to hold the data
[in] u16Value The value to be placed in the array
Returns
Returns the converted value
SafeTool Function MD5:
16B0EFC680989C232FD49B1932F8703B
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.008
void vSIL3_NUM_CONVERT__Array_S32 (Luint8 * pu8Array, Lint32 s32Value)
Conver a S32 value into an array.
Parameters
[in] pu8Array Pointer to the array to hold the data
[in] s32value The value to convert into an array
SafeTool Function MD5:
7C67D9B487DC9DD1F532462C992133D9
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.010
Referenced by vRM4_EEPROM__WriteS32().
void vSIL3_NUM_CONVERT__Array_U16 (Luint8 * pu8Array, Luint16 u16Value)
Convert a U16 into an array.
Parameters
[in] pu8Array Pointer to the array to hold the data
Returns
Returns the converted value
SafeTool Function MD5:
E18D3F6E7C8186E84FC12E11081E43FD
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.007
void vSIL3_NUM_CONVERT__Array_U16_BIGENDIAN (Luint8 * pu8Array, Luint16 u16Value)
Convert a U16 into an array and force use big endian.
Parameters
[in] u16Value The U16 Value
[in] *pu8Array Pointer to the array to hold the data
SafeTool Function MD5:
D59791B3B904C1597868FF91B44BD393
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.018
void vSIL3_NUM_CONVERT__Array_U16_LITTLEENDIAN (Luint8 * pu8Array, Luint16 u16Value)
Convert a U16 into an array and force little endian.
Parameters
[in] u16Value The inptu value
[in] *pu8Array Pointer to array to hold the value
SafeTool Function MD5:
9FB00FDC72C2FFE07DF99224DD530103
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.017
void vSIL3_NUM_CONVERT__Array_U32 (Luint8 * pu8Array, Luint32 u32Value)
Put a U32 value into an array.
Parameters
[in] *pu8Array Pointer to the array to hold the data
[in] u32Value The value to convert into an array
SafeTool Function MD5:
BF2D22EC6376DDC446B72D956A935A2E
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.009
Referenced by vRM4_EEPROM__WriteU32().
void vSIL3_NUM_CONVERT__Array_U32_BIGENDIAN (Luint8 * pu8Array, Luint32 u32Value)
Convert a U32 value into an array and force bigendian mode.
Parameters
[in] u32Value The value to convert to an array
[in] *pu8Array Pointer to the array to hold the data
SafeTool Function MD5:
E7F2CC20721D5A71FE88F37678EAC472
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.022
void vSIL3_NUM_CONVERT__Array_U32_LITTLEENDIAN (Luint8 * pu8Array, Luint32 u32Value)
Put a U32 value into an array and force little endian mode.
Parameters
[in] u32Value The u32 value
[in] *pu8Array Pointer to the array to hold the return data
SafeTool Function MD5:
86F2EE144867A5067268F0694C23A89F
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.021
void vSIL3_NUM_CONVERT__Array_U64 (Luint8 * pu8Array, Luint64 u64Value)
ToDo.
Parameters
[in] Luint64 ## Desc ##
[in] *pu8Array ## Desc ##
SafeTool Function MD5:
A338597438769DBFABCD2EEB2F583403
SafeTool Function ID:
LCCM118R0.FILE.001.FUNC.030