LFW615 (RLOOP - AUX PROP UNIT (APU)): ADC__CORE
ADC__CORE
RM4 » ADC
Functions
void vRM4_ADC__ChannelID_InResult (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup, Luint8 u8Enable)
Enable/disable channel ID in result.
void vRM4_ADC__Enable_GroupPin (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup, Luint32 u32PinsOR)
Enable a pin in a group ADC1 has up to 24 pins, ADC2 has up to 16 At the same this will start the conversion, unless the event type is hardware triggered.
void vRM4_ADC__Clear_GroupPins (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup)
A group's conversion can be stopped by clearing the group's channel select register.
void vRM4_ADC_FIFO__Set_FIFO_Size (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup, Luint32 u32Size)
Set the size of the ADC fifo for a particular group.
void vRM4_ADC__Set_ConversionMode (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup, RM4_ADC__CONVERT_MODE_E eMode)
Set the conversion mode.
void vRM4_ADC_LOWLEVEL__StartConversion (RM4_ADC__BASE_T *adc, RM4_ADC__GROUPS_T eGroup)
Starts a conversion by writing to the GxSEL register.
void vRM4_ADC_LOWLEVEL__StopConversion (RM4_ADC__BASE_T *adc, RM4_ADC__GROUPS_T eGroup)
This function stops a conversion of the ADC hardware group.
void vRM4_ADC_LOWLEVEL__Reset_FIFO (RM4_ADC__BASE_T *adc, RM4_ADC__GROUPS_T eGroup)
This function resets the FiFo read and write pointers.
Luint32 u32RM4_ADC_LOWLEVEL__GetData (RM4_ADC__BASE_T *adc, RM4_ADC__GROUPS_T eGroup, RM4_ADC__DATA_T *data)
This function writes a ADC message into a ADC message box.
Luint32 u32RM4_ADC_LOWLEVEL__Is_FIFOFull (RM4_ADC__BASE_T *adc, RM4_ADC__GROUPS_T eGroup)
Check if the FIFO is full.
Luint8 u8RM4_ADC_LOWLEVEL__Is_ConversionComplete (RM4_ADC__BASE_T *adc, RM4_ADC__GROUPS_T eGroup)
This function checks if conversion is complete by polling the conversion flags.
void vRM4_ADC_LOWLEVEL__Set_EVTPin (RM4_ADC__BASE_T *adc, Luint32 value)
Set ADCEVT pin.
Luint32 vRM4_ADC_LOWLEVEL__Get_EVTPin (RM4_ADC__BASE_T *adc)
Get Pin Value.
Variables
RM4_ADC_T gADC
Detailed Description
Function Documentation
Luint32 u32RM4_ADC_LOWLEVEL__GetData (RM4_ADC__BASE_T * adc, RM4_ADC__GROUPS_T eGroup, RM4_ADC__DATA_T * data)
This function writes a ADC message into a ADC message box.
This function must be called after receiving the conversionComplete signal in order to be sure that there is meaningful data in RAM
Parameters
[out] *data Returned data
[in] u32Group Channel Group
[in] *adc ADC base registers
SafeTool Function MD5:
232DEA5E58ECF9AA137206E26ABC8955
SafeTool Function ID:
LCCM414R0.FILE.003.FUNC.009
References ADC_12_BIT_MODE, adcData::u16Value, and adcData::u32ID.
Referenced by vRM4_ADC_USER__Process().
Luint32 u32RM4_ADC_LOWLEVEL__Is_FIFOFull (RM4_ADC__BASE_T * adc, RM4_ADC__GROUPS_T eGroup)
Check if the FIFO is full.
Parameters
[in] u32Group Channel Group
[in] *adc ADC Base registers
SafeTool Function MD5:
DAD1DBD731D08D556934595D8AC0D92D
SafeTool Function ID:
LCCM414R0.FILE.003.FUNC.010
Luint8 u8RM4_ADC_LOWLEVEL__Is_ConversionComplete (RM4_ADC__BASE_T * adc, RM4_ADC__GROUPS_T eGroup)
This function checks if conversion is complete by polling the conversion flags.
Note
19.3.7 How to Know When the Group Conversion is Completed Each conversion group has a status flag to indicate when its conversion has ended. See ADEVSR, ADG1SR and ADG2SR. This bit is set when a conversion sequence for a group ends. This bit does is always set if a group is configured for continuous conversions.
Parameters
[in] eGroup Channel Group
[in] *adc ADC base registers
SafeTool Function MD5:
49309236DF52FC110C95AC2034693D79
SafeTool Function ID:
LCCM414R0.FILE.003.FUNC.011
Referenced by vRM4_ADC_USER__Process().
void vRM4_ADC__ChannelID_InResult (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup, Luint8 u8Enable)
Enable/disable channel ID in result.
Parameters
[in] u8Enable 1 = Enable
[in] eGroup The ADC group
[in] eADC The ADC Index
SafeTool Function MD5:
EC06BDE0864331A058E6C147A6150BAF
SafeTool Function ID:
LCCM414R0.FILE.003.FUNC.001
References adcREG1, adcREG2, RM4_ADC__1, and RM4_ADC__2.
void vRM4_ADC__Clear_GroupPins (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup)
A group's conversion can be stopped by clearing the group's channel select register.
Parameters
[in] eGroup Channel group
[in] eADC ADC module
SafeTool Function MD5:
B21A419D0410EC3F429CB4E8AE4051D6
SafeTool Function ID:
LCCM414R0.FILE.003.FUNC.003
References adcREG1, adcREG2, RM4_ADC__1, and RM4_ADC__2.
void vRM4_ADC__Enable_GroupPin (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup, Luint32 u32PinsOR)
Enable a pin in a group ADC1 has up to 24 pins, ADC2 has up to 16 At the same this will start the conversion, unless the event type is hardware triggered.
Example:
 //On RM48HDK this will enable 3 ADC channels for group 1.
 //thermister on ADC8
 //light sensor on ADC 9
 vRM4_ADC__Enable_GroupPin(RM4_ADC__1, ADC_GROUP__GROUP_1, (1 << 8) | (1 << 9) | (1 << 0));
Parameters
[in] u32PinsOR ORing Mask for the pins
[in] eGroup Channel Group
[in] eADC ADC
SafeTool Function MD5:
EA2F8CF18910BBDF3A1400C344900F24
SafeTool Function ID:
LCCM414R0.FILE.003.FUNC.002
References adcREG1, adcREG2, RM4_ADC__1, and RM4_ADC__2.
void vRM4_ADC__Set_ConversionMode (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup, RM4_ADC__CONVERT_MODE_E eMode)
Set the conversion mode.
Parameters
[in] eMode Mode Type
[in] eGroup Channel Group
[in] eADC ADC
SafeTool Function MD5:
0D61525781EB81DAA2024A87B69A1BD0
SafeTool Function ID:
LCCM414R0.FILE.003.FUNC.005
References adcREG1, adcREG2, CONVERSION_MODE__SINGLE, RM4_ADC__1, and RM4_ADC__2.
void vRM4_ADC_FIFO__Set_FIFO_Size (RM4_ADC__INDEX_T eADC, RM4_ADC__GROUPS_T eGroup, Luint32 u32Size)
Set the size of the ADC fifo for a particular group.
Parameters
[in] u32Size FIFO size
[in] eGroup Channel Group
[in] eADC ADC
SafeTool Function MD5:
658A7B31A648A2FB86293D66AD0758BF
SafeTool Function ID:
LCCM414R0.FILE.003.FUNC.004
References adcREG1, adcREG2, RM4_ADC__1, and RM4_ADC__2.
Luint32 vRM4_ADC_LOWLEVEL__Get_EVTPin (RM4_ADC__BASE_T * adc)
Get Pin Value.
Parameters
[in] *adc Pointer to ADC module
SafeTool Function MD5:
BA349DE866C661ACA886D2CE63D0DDEE
SafeTool Function ID:
LCCM414R0.FILE.003.FUNC.013
void vRM4_ADC_LOWLEVEL__Reset_FIFO (RM4_ADC__BASE_T * adc, RM4_ADC__GROUPS_T eGroup)
This function resets the FiFo read and write pointers.
Parameters
[in] u32Group The channel group
[in] *adc Pointer to ADC regs
SafeTool Function MD5:
2A2328A53C768C9B67799EBC6AAAF494
SafeTool Function ID:
LCCM414R0.FILE.003.FUNC.008
void vRM4_ADC_LOWLEVEL__Set_EVTPin (RM4_ADC__BASE_T * adc, Luint32 value)
Set ADCEVT pin.
Parameters
[in] value Value to be set: 0 or 1
[in] *adc Pointer to ADC module:
SafeTool Function MD5:
28D78613BBDB8C08942FB21262F47BA3
SafeTool Function ID:
LCCM414R0.FILE.003.FUNC.012
void vRM4_ADC_LOWLEVEL__StartConversion (RM4_ADC__BASE_T * adc, RM4_ADC__GROUPS_T eGroup)
Starts a conversion by writing to the GxSEL register.
Note
19.3.6 How to Start a Conversion The conversion groups Group1 and Group2 are software-triggered by default. A conversion in these groups can be started just by writing the desired channels to the respective Channel-Select Registers. For example, in order to convert channels 0, 1, 2, and 3 in Group1 and channels 8, 9, 10, and 11 in Group2, the application just has to write 0x0000000F to ADG1SEL and 0x00000F00 to ADG2SEL. The ADC module will start by servicing the group that was triggered first, Group1 in this example. The conversions for all groups are performed in ascending order of the channel number. For the Group1 the conversions will be performed in the order: channel 0 first, followed by channel 1, then channel 2, and then channel 3. The Group2 conversions will be performed in the order: channels 8, 9, 10, and 11. The Event Group is only hardware-triggered. There are up to eight hardware event trigger sources defined for the ADC module. Check the device datasheet for a complete listing of these eight hardware trigger options. The trigger source to be used needs to be configured in the ADEVSRC register. Similar registers also exist for the Group1 and Group2 as these can also be configured to be event-triggered. The polarity of the event trigger is also configurable, with a falling edge being the default. An Event Group conversion starts when at least one channel is selected for conversion in this group, and when the defined event trigger occurs. If any conversion group is configured to be in a continuous conversion mode, then it needs to only be triggered once. All the channels selected for conversion in that group will be converted repeatedly.
Parameters
[in] u32Group The conversion group to act on.
[in] *adc Pointer to the ADC registers
SafeTool Function MD5:
578F4F647742283E563032543865AAA2
SafeTool Function ID:
LCCM414R0.FILE.003.FUNC.006
Referenced by vRM4_ADC_USER__Process(), and vRM4_ADC_USER__StartConversion().
void vRM4_ADC_LOWLEVEL__StopConversion (RM4_ADC__BASE_T * adc, RM4_ADC__GROUPS_T eGroup)
This function stops a conversion of the ADC hardware group.
Parameters
[in] u32Group The channel grouop
[in] *adc Ptr to ADC registers
SafeTool Function MD5:
D8ECC1A58CA8A33D6589C3F597FEE0D0
SafeTool Function ID:
LCCM414R0.FILE.003.FUNC.007
Variable Documentation
RM4_ADC_T gADC