LFW615 (RLOOP - AUX PROP UNIT (APU)): SYSTEM__ABORTS
SYSTEM__ABORTS
RM4 » SYSTEM
Functions
void custom_dabort (void)
Custom Data abort routine for the application.
void _data (void)
Detailed Description
Function Documentation
void _data (void)
References _rm4_system_core__GetDataFault_(), _rm4_system_core__GetDataFaultAddress_(), _rm57_system_core__GetDataFault_(), _rm57_system_core__GetDataFaultAddress_(), AlignmentFault, BackgroundFault, t_uDfsr::Bits, t_uDfsr::ExT, t_uDfsr::Fs, PermissionFault, SynchronousExternalAbort, t_uDfsr::WnR, and t_uDfsr::Word.
void custom_dabort (void)
Custom Data abort routine for the application.
SafeTool Function MD5:
F828DBB335FF587E7092FE7F60637206
SafeTool Function ID:
LCCM219R0.FILE.001.FUNC.012
References _rm4_system_core__GetDataFault_(), and _rm57_system_core__GetDataFault_().