LFW615 (RLOOP - AUX PROP UNIT (APU)): DMA__NOTIFICATIONS
DMA__NOTIFICATIONS
RM4 » DMA
Functions
void vRM4_DMA__Notification (RM4_DMA__INTERRUPT_T eInterruptType, Luint8 u8Channel)
User Notification for interrupts and other module events This is a callback that is provided by the application and is called apon an interrupt.
Detailed Description
Function Documentation
void vRM4_DMA__Notification (RM4_DMA__INTERRUPT_T eInterruptType, Luint8 u8Channel)
User Notification for interrupts and other module events This is a callback that is provided by the application and is called apon an interrupt.
The parameter passed to the callback is a copy of the interrupt flag register The user should override this in their own application if needed
Parameters
[in] eInterruptType Interrupt type
INTERRUPT__FRAME_TX_COMPLETE
INTERRUPT__LAST_FRAME_START
INTERRUPT__HALF_BLOCK_COMPLETE
INTERRUPT__BLOCK_TX_COMPLETE
[in] u8Channel The DMA Channel (0 .. 15)
SafeTool Function MD5:
956831FDB04B0732F49633B3BFA12AB8
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.023
Referenced by vRM4_DMA_ISR__BTCAInterrupt(), vRM4_DMA_ISR__FTCAInterrupt(), vRM4_DMA_ISR__HBCAInterrupt(), and vRM4_DMA_ISR__LFSAInterrupt().