LFW615 (RLOOP - AUX PROP UNIT (APU)): N2HET__CORE
N2HET__CORE
RM4 » N2HET
Functions
void vRM4_N2HET__Init (RM4_N2HET__CHANNEL_T eChannel, Luint8 u8DontUpdateRAM, RM4_N2HET__HR_PRESCALE_T eHR_Prescale, RM4_N2HET__LR_PRESCALE_T eLR_Prescale)
Initializes the het Driver.
void vRM4_N2HET__Disable (RM4_N2HET__CHANNEL_T eChannel)
Disable the N2HET.
void vRM4_N2HET__Enable (RM4_N2HET__CHANNEL_T eChannel)
Enable the N2HET.
Variables
struct _strRM4_N2HET sN2HET
Detailed Description
Function Documentation
void vRM4_N2HET__Disable (RM4_N2HET__CHANNEL_T eChannel)
Disable the N2HET.
Parameters
[in] eChannel The N2HET Channel
SafeTool Function MD5:
358602E9993FCFA0576879EDDBA51F01
SafeTool Function ID:
LCCM240R0.FILE.001.FUNC.004
References hetREG1, hetREG2, and N2HET_CHANNEL__1.
Referenced by vRM4_N2HET__Init().
void vRM4_N2HET__Enable (RM4_N2HET__CHANNEL_T eChannel)
Enable the N2HET.
Parameters
[in] eChannel The N2HET Channel
SafeTool Function MD5:
EA61F9982EA2024F4B1E55023363B9C0
SafeTool Function ID:
LCCM240R0.FILE.001.FUNC.005
Setup control register
Enable output buffers
Ignore software breakpoints
Slave Mode since multiple HET's are active
Enable HET
References hetREG1, hetREG2, and N2HET_CHANNEL__1.
void vRM4_N2HET__Init (RM4_N2HET__CHANNEL_T eChannel, Luint8 u8DontUpdateRAM, RM4_N2HET__HR_PRESCALE_T eHR_Prescale, RM4_N2HET__LR_PRESCALE_T eLR_Prescale)
Initializes the het Driver.
Note
Loop Resolution and High Resoluation Prescalers Time Slots: The number of cycles available for instruction execution per loop. Time Slots is the number of VCLK2 cycles in a Loop Resolution Clock. High Resolution Clock: The high resolution clock is the smallest time increment with which a pin can change it’s state or can be measured in the case of input signals. A 6-bit prescaler dividing VCLK2 by a user-defined HR prescale divide rate (hr) stored in the 6-bit HR prescale factor code (HETPFR). See Table 20-5. Loop Resolution Clock: The loop resolution clock defines the timebase for executing all instructions in a N2HET program. Since instructions can be conditionally executed, the longest path through the N2HET program must fit into one loop resolution clock period (LRP).A 3-bit prescaler dividing the HR clock by a user-defined loop-resolution prescale divide rate (lr) stored in the 3-bit loop-resolution prescale factor code (HETPFR). See Table 20-5.
The following abbreviations and relations are used in this document:
hr: high resolution prescale factor (1, 2, 3, 4,..., 63, 64)
lr: loop resolution prescale factor (1, 2, 4, 8, 16, 32, 64,128)
ts: Time slots (cycles) available for instruction execution per loop. ts = hr x lr
HRP = high resolution clock period HRP = hr x TVCLK2 (ns)
LRP = loop resolution clock period LRP = lr x HRP (ns)
Example:
 vRM4_N2HET__Init(N2HET_CHANNEL__1, 1U, HR_PRESCALE__1, LR_PRESCALE__32);
Parameters
[in] eLR_Prescale The Loop Resoluation Clock Prescaler
[in] eHR_Prescale The High Resoluation Clock Prescaler
[in] u8DontUpdateRAM 1=don't modify the instruction RAM
[in] eChannel The HET Channel
SafeTool Function MD5:
B83D7607AB919EA429EDF4B0F638E9D0
SafeTool Function ID:
LCCM240R0.FILE.001.FUNC.001
Set HET pins open drain enable
Set HET pins pullup/down enable
Set HET pins pullup/down select
Set HET pins high resolution share
Set HET pins AND share
Set HET pins XOR share
Setup prescaler values
Loop resolution prescaler
High resolution prescaler
Loop Resolution Prescale Factor
High Resolution Prescale Factor
Fill HET RAM with opcodes and Data
Setup interrupt priority level
Enable interrupts
Parity control register
Enable/Disable Parity check
Setup control register
Enable output buffers
Ignore software breakpoints
Slave Mode since multiple HET's are active
Enable HET
References hetREG1, hetREG2, N2HET_CHANNEL__1, vN2HET_PROG_DYNAMIC__Clear(), and vRM4_N2HET__Disable().
Referenced by vAPU__Init().
Variable Documentation
struct _strRM4_N2HET sN2HET
Referenced by u16N2HET_PROG_DYNAMIC__Add_Capture(), u16N2HET_PROG_DYNAMIC__Add_Edge(), u16N2HET_PROG_DYNAMIC__Add_Edge_Counter(), u16N2HET_PROG_DYNAMIC__Add_PWM(), u16N2HET_PROG_DYNAMIC__Add_PWM_Counter(), vN2HET_PROG__Update_RAM(), and vN2HET_PROG_DYNAMIC__Clear().