LFW615 (RLOOP - AUX PROP UNIT (APU)): BIST__CORE
BIST__CORE
RM4 » BIST
Functions
void errataFailNotification (Luint32 flag)
void vRM4_BIST__Init (void)
Init the BIST module.
Luint32 u32RM4_BIST__Get_FaultFlags (void)
Return any fault flags from the BIST module.
void vRM4_BIST__SelfCheck (void)
PBIST self test Driver This function is called to perform PBIST self test.
void vRM4_BIST__Run (Luint32 u32RAMInfoL, Luint32 u32AlgoMask)
CPU self test Driver This function performs Memory Built-in Self test using PBIST module.
void vRM4_BIST__Stop (void)
This function is called to stop PBIST after test is performed.
Luint8 u8RM4_BIST__IsTestCompleted (void)
Checks to see if the PBIST test is completed.
Luint8 u8RM4_BIST__IsTestPassed (void)
Checks to see if the PBIST test is completed successfully.
Luint8 u8RM4_BIST__PortTestStatus (Luint32 port)
Checks to see if the selected PBIST Port test is completed successfully.
void vRM4_BIST__errata_PBIST_4 (void)
This function is workaround for Errata PBIST#4.
void vRM57_BIST__errata_PBIST_4 (void)
Variables
struct _strRM4BIST sBIST
Detailed Description
Function Documentation
void errataFailNotification (Luint32 flag)
Referenced by vRM57_BIST__errata_PBIST_4().
Luint32 u32RM4_BIST__Get_FaultFlags (void)
Return any fault flags from the BIST module.
SafeTool Function MD5:
4A7C433174F7DBB6362E403D48EAD21E
SafeTool Function ID:
LCCM227R0.FILE.001.FUNC.008
References sBIST, _strRM4BIST::sFaultFlags, and FAULT_TREE__PUBLIC_T::u32Flags.
Luint8 u8RM4_BIST__IsTestCompleted (void)
Checks to see if the PBIST test is completed.
Returns
1 if PBIST test completed, otherwise 0.
SafeTool Function MD5:
46B2DF9FF71902E57962FB2FFFDA0636
SafeTool Function ID:
LCCM227R0.FILE.001.FUNC.004
References systemREG1.
Referenced by _c_int00(), and vRM4_SYSTEM__After_STC().
Luint8 u8RM4_BIST__IsTestPassed (void)
Checks to see if the PBIST test is completed successfully.
Returns
1 if PBIST test passed, otherwise 0.
SafeTool Function MD5:
1AEBF69A4058790E4B428E52C72DE015
SafeTool Function ID:
LCCM227R0.FILE.001.FUNC.005
References pbistREG.
Referenced by _c_int00(), and vRM4_SYSTEM__After_STC().
Luint8 u8RM4_BIST__PortTestStatus (Luint32 port)
Checks to see if the selected PBIST Port test is completed successfully.
Parameters
[in] port Select the port to get the status.
Returns
1 if PBIST Port test completed successfully, otherwise 0.
SafeTool Function MD5:
7A6D483DEEC7B68A24F333D9FFE5FE98
SafeTool Function ID:
LCCM227R0.FILE.001.FUNC.006
References PBIST_PORT0, and pbistREG.
void vRM4_BIST__errata_PBIST_4 (void)
This function is workaround for Errata PBIST#4.
This function is designed to initialize the ROMs using the PBIST controller. The CPU will configure the PBIST controller to test the PBIST ROM and STC ROM. This function should be called at startup after system init before using the ROMs.
SafeTool Function MD5:
475D453BE47EA1D553A20EAB7A5A9693
SafeTool Function ID:
LCCM227R0.FILE.001.FUNC.009
References _pmuDisableCountersGlobal_(), _pmuEnableCountersGlobal_(), _pmuGetCycleCount_(), _pmuResetCounters_(), _pmuStartCounters_(), _pmuStopCounters_(), pbistREG, pmuCYCLE_COUNTER, and systemREG1.
Referenced by _c_int00().
void vRM4_BIST__Init (void)
Init the BIST module.
SafeTool Function MD5:
5ECF61DC580038614F3973AE3D97CE05
SafeTool Function ID:
LCCM227R0.FILE.001.FUNC.007
References sBIST, _strRM4BIST::sFaultFlags, and vSIL3_FAULTTREE__Init().
Referenced by vRM4_SYSTEM__After_STC().
void vRM4_BIST__Run (Luint32 u32RAMInfoL, Luint32 u32AlgoMask)
CPU self test Driver This function performs Memory Built-in Self test using PBIST module.
Parameters
[in] u32AlgoMask Select the list of Algorithm to be run.
[in] u32RAMInfoL Select the list of RAM to be tested.
SafeTool Function MD5:
8FD8D714F0D3CB64751A3752A62A3817
SafeTool Function ID:
LCCM227R0.FILE.001.FUNC.002
References pbistREG, and systemREG1.
Referenced by _c_int00(), and vRM4_SYSTEM__After_STC().
void vRM4_BIST__SelfCheck (void)
PBIST self test Driver This function is called to perform PBIST self test.
SafeTool Function MD5:
036435CA4FD7C9F83999519C305B347B
SafeTool Function ID:
LCCM227R0.FILE.001.FUNC.001
References C_LCCM227__CORE__FAULT_INDEX__00, C_LCCM227__CORE__FAULT_INDEX__01, pbistREG, PBISTSELFCHECK_FAIL1, sBIST, _strRM4BIST::sFaultFlags, systemREG1, vRM4_SELFTEST__Set_FailNotification(), and vSIL3_FAULTTREE__Set_Flag().
Referenced by _c_int00().
void vRM4_BIST__Stop (void)
This function is called to stop PBIST after test is performed.
SafeTool Function MD5:
110F31589FCA4ECC03AAD6AA5E1130AF
SafeTool Function ID:
LCCM227R0.FILE.001.FUNC.003
References pbistREG, and systemREG1.
Referenced by _c_int00(), and vRM4_SYSTEM__After_STC().
void vRM57_BIST__errata_PBIST_4 (void)
References _pmuDisableCountersGlobal_(), _pmuEnableCountersGlobal_(), _pmuGetCycleCount_(), _pmuInit_(), _pmuResetCounters_(), _pmuStartCounters_(), _pmuStopCounters_(), errataFailNotification(), PBISTERRATA_FAIL1, PBISTERRATA_FAIL2, PBISTERRATA_FAIL3, pbistREG, pmuCYCLE_COUNTER, and systemREG1.
Referenced by _c_int00().
Variable Documentation
struct _strRM4BIST sBIST
Referenced by u32RM4_BIST__Get_FaultFlags(), vRM4_BIST__Init(), vRM4_BIST__SelfCheck(), and vRM4_SYSTEM__After_STC().