LFW615 (RLOOP - AUX PROP UNIT (APU)): I2C__TIMEOUT
I2C__TIMEOUT
RM4 » I2C
Functions
void vRM4_I2C_TIMEOUT__Start (void)
Start the timeout mechanism.
Luint8 u8RM4_I2C_TIMEOUT__Check (void)
Check to see if the current timeout has been exceeded.
void vRM4_I2C_TIMEOUT__Stop (void)
Call this to stop / cleanup after the timeout module is not required.
Variables
struct _strRM4I2C sRM4I2C
Detailed Description
Function Documentation
Luint8 u8RM4_I2C_TIMEOUT__Check (void)
Check to see if the current timeout has been exceeded.
Call this in a while loop that requires timeout support
Returns
0 = Timeout has not occurred
1 = Timeout has occurred.
SafeTool Function MD5:
3EA175E3B075A07842294C9A61CDACCD
SafeTool Function ID:
LCCM215R0.FILE.051.FUNC.002
References sRM4I2C, _strRM4I2C::sStats, _strRM4I2C::u32General_Timeout, and _strRM4I2C::u32TimeoutCounter.
Referenced by u8RM4_I2C_WAIT__IsBusBusy(), u8RM4_I2C_WAIT__RxBufferFull(), u8RM4_I2C_WAIT__TxBufferEmpty(), and u8RM4_I2C_WAIT__TxBufferEmpty_Or_NACK().
void vRM4_I2C_TIMEOUT__Start (void)
Start the timeout mechanism.
Call this before requiring to use the timeout
SafeTool Function MD5:
895D14A0366BFD8AD91038D6024FD961
SafeTool Function ID:
LCCM215R0.FILE.051.FUNC.001
References sRM4I2C, and _strRM4I2C::u32TimeoutCounter.
Referenced by u8RM4_I2C_WAIT__IsBusBusy(), u8RM4_I2C_WAIT__RxBufferFull(), u8RM4_I2C_WAIT__TxBufferEmpty(), and u8RM4_I2C_WAIT__TxBufferEmpty_Or_NACK().
void vRM4_I2C_TIMEOUT__Stop (void)
Call this to stop / cleanup after the timeout module is not required.
SafeTool Function MD5:
61C452CD91B8031F826648EA82B99CF9
SafeTool Function ID:
LCCM215R0.FILE.051.FUNC.003
Referenced by u8RM4_I2C_WAIT__IsBusBusy(), u8RM4_I2C_WAIT__RxBufferFull(), u8RM4_I2C_WAIT__TxBufferEmpty(), and u8RM4_I2C_WAIT__TxBufferEmpty_Or_NACK().
Variable Documentation
struct _strRM4I2C sRM4I2C
Referenced by u8RM4_I2C_TIMEOUT__Check(), and vRM4_I2C_TIMEOUT__Start().