LFW615 (RLOOP - AUX PROP UNIT (APU)): NUMERICAL__MATRIX
NUMERICAL__MATRIX
MULTICORE » NUMERICAL
Functions
void vNUMERICAL_MATRIX__Mult (Luint32 aRows, Luint32 aCols_bRows, Luint32 bCols, Lfloat32 matrixC[], const Lfloat32 matrixA[], const Lfloat32 matrixB[])
Matrix Mult.
void vNUMERICAL_MATRIX__Mult_3X3 (const Lfloat32 a[3][3], const Lfloat32 b[3][3], Lfloat32 mat[3][3])
Mult two 3 by 3 matrix'.
void vNUMERICAL_MATRIX__Add (Luint32 rows, Luint32 cols, Lfloat32 matrixC[], const Lfloat32 matrixA[], const Lfloat32 matrixB[])
Matrix Addition.
void vNUMERICAL_MATRIX__Sub (Luint32 rows, Luint32 cols, Lfloat32 matrixC[], const Lfloat32 matrixA[], const Lfloat32 matrixB[])
Matrix Subtraction.
void vNUMERICAL_MATRIX__Scale (Luint32 rows, Luint32 cols, Lfloat32 matrixC[], Lfloat32 scaler, const Lfloat32 matrixA[])
Matrix Scaling.
void vNUMERICAL_MATRIX__Transpose_3X3 (Lfloat32 matrixC[9], const Lfloat32 matrixA[9])
3 x 3 Matrix Transpose
void vNUMERICAL_MATRIX__Inverse_3X3 (Lfloat32 matrixC[9], const Lfloat32 matrixA[9])
3 x 3 Matrix Inverse
Detailed Description
Function Documentation
void vNUMERICAL_MATRIX__Add (Luint32 rows, Luint32 cols, Lfloat32 matrixC[], const Lfloat32 matrixA[], const Lfloat32 matrixB[])
Matrix Addition.
Note
matrix A + matrix B, size is m x n Result in matrix C, size is m x n
Example:
vNUMERICAL_MATRIX__Add(m, n, C, A, B);
Parameters
[in] matrixB Matrix B
[in] matrixA Matrix A
[out] matrixC Result matrix
[in] cols Cols of matrix
[in] rows Rows of matrix
SafeTool Function MD5:
2B83EE376F66AFCBFD55A42CD869B742
SafeTool Function ID:
LCCM118R0.FILE.010.FUNC.003
void vNUMERICAL_MATRIX__Inverse_3X3 (Lfloat32 matrixC[9], const Lfloat32 matrixA[9])
3 x 3 Matrix Inverse
Note
3x3 Inverse of A Result in matrix C, size 3 x 3
Example:
vNUMERICAL_MATRIX__Inverse_3X3(C, A)
Parameters
[in] matrixA Matrix A
References vNUMERICAL_MATRIX__Scale(), and vNUMERICAL_MATRIX__Transpose_3X3().
void vNUMERICAL_MATRIX__Mult (Luint32 aRows, Luint32 aCols_bRows, Luint32 bCols, Lfloat32 matrixC[], const Lfloat32 matrixA[], const Lfloat32 matrixB[])
Matrix Mult.
Note
A * B A size is m x n B size is n x p C = result
Parameters
[in] matrixB Mat B
[in] matrixA Mat A
[out] matrixC Result matrix
[in] bCols Num cols in B
[in] aCols_bRows Num cols in A and Rows in B
[in] aRows Num rows in A
SafeTool Function MD5:
FBCE85C289AB9CAB07EBBBC2DC650B04
SafeTool Function ID:
LCCM118R0.FILE.010.FUNC.001
void vNUMERICAL_MATRIX__Mult_3X3 (const Lfloat32 a[3][3], const Lfloat32 b[3][3], Lfloat32 mat[3][3])
Mult two 3 by 3 matrix'.
Parameters
[out] mat Result
[in] b B 3x3
[in] a A 3x3
SafeTool Function MD5:
7A39EC0F5D43773B641D0A3A6990D10D
SafeTool Function ID:
LCCM118R0.FILE.010.FUNC.002
void vNUMERICAL_MATRIX__Scale (Luint32 rows, Luint32 cols, Lfloat32 matrixC[], Lfloat32 scaler, const Lfloat32 matrixA[])
Matrix Scaling.
Note
A * S, size is m x n Result in matrix C, size is m x n
Example:
vNUMERICAL_MATRIX__Scale(m, n, C, S, B)
Parameters
[in] matrixA Matrix A
[in] scaler Scale Factor
Referenced by vNUMERICAL_MATRIX__Inverse_3X3().
void vNUMERICAL_MATRIX__Sub (Luint32 rows, Luint32 cols, Lfloat32 matrixC[], const Lfloat32 matrixA[], const Lfloat32 matrixB[])
Matrix Subtraction.
Note
matrix A - matrix B, size is m x n Result in matrix C, size is m x n
Example:
vNUMERICAL_MATRIX__Sub(m, n, C, A, B);
Parameters
[in] matrixB Matrix B
[in] matrixA Matrix A
[out] matrixC Result matrix
[in] cols Num Cols
[in] rows Num Rows
SafeTool Function MD5:
6423ADB93CD26D0A9E718835B1DF03C6
SafeTool Function ID:
LCCM118R0.FILE.010.FUNC.004
void vNUMERICAL_MATRIX__Transpose_3X3 (Lfloat32 matrixC[9], const Lfloat32 matrixA[9])
3 x 3 Matrix Transpose
Note
3x3 Transpose of A Result in matrix C, size is 3 x 3
Example:
vNUMERICAL_MATRIX__Transpose_3X3(C, A);
Parameters
[in] matrixA Matrix A
Referenced by vNUMERICAL_MATRIX__Inverse_3X3().