LFW615 (RLOOP - AUX PROP UNIT (APU)): I2C__USER
I2C__USER
RM4 » I2C
Functions
void vRM4_I2C_USER__Init (void)
User call to init the module.
Luint32 u32RM4_I2C_USER__Get_FaultFlags (void)
Returns the I2C modules fault flags.
Lint16 s16RM4_I2C_USER__Tx_U8 (Luint8 u8DeviceAddx, Luint8 u8RegisterAddx, Luint8 u8Byte)
Transmits a byte.
Lint16 s16RM4_I2C_USER__TxReg (Luint8 u8DeviceAddx, Luint8 u8RegisterAddx)
Only transmit the register address This is useful for devices that just need a ping to do something useful and dont need any additional data.
Lint16 s16RM4_I2C_USER__TxByte16 (Luint8 u8DeviceAddx, Luint16 u16RegisterAddx, Luint8 u8Byte)
Transmit a byte using 16bit addressing.
Lint16 s16RM4_I2C_USER__Rx_U8 (Luint8 u8DeviceAddx, Luint8 u8RegisterAddx, Luint8 *pu8Byte)
Receives a byte from a device.
Lint16 s16RM4_I2C_USER__RxReg (Luint8 u8DeviceAddx, Luint8 *pu8Byte)
Non standard set address and then read.
Lint16 s16RM4_I2C_USER__RxByte16 (Luint8 u8DeviceAddx, Luint16 u16RegisterAddx, Luint8 *pu8Byte)
Receive a byte using 16BIT slave addressing.
Lint16 s16RM4_I2C_USER__Tx_U8Array (Luint8 u8DeviceAddx, Luint8 u8RegisterAddx, Luint8 *pu8Array, Luint8 u8ArrayLength)
Transmits a byte array.
Lint16 s16RM4_I2C_USER__Tx_U8Array_Constant (Luint8 u8DeviceAddx, Luint8 u8RegisterAddx, Luint8 u8Value, Luint16 u16ArrayLength)
Transmit a byte array of a constant value.
Lint16 s16RM4_I2C_USER__Rx_U8Array (Luint8 u8DeviceAddx, Luint8 u8RegisterAddx, Luint8 *pu8Array, Luint8 u8ArrayLength)
Handles the reception of a byte array from an addx NOTE: Make sure pArray is big enough.
Lint16 s16RM4_I2C_USER__RxByteArray16 (Luint8 u8DeviceAddx, Luint16 u16RegisterAddx, Luint8 *pu8Array, Luint8 u8ArrayLength)
Read an array ising 16bit slave addressing.
Lint16 s16RM4_I2C_USER__RxBit_U8 (Luint8 u8DeviceAddx, Luint8 u8RegisterAddx, Luint8 u8BitNumber, Luint8 *pu8Byte)
Read a single bit from an 8-bit device register.
Lint16 s16RM4_I2C_USER__RxBits_U8 (Luint8 u8DeviceAddx, Luint8 u8RegisterAddx, Luint8 u8BitStart, Luint8 u8Length, Luint8 *pu8Byte)
Read multiple bits from an 8-bit device register.
Variables
struct _strRM4I2C sRM4I2C
Detailed Description
Function Documentation
Lint16 s16RM4_I2C_USER__Rx_U8 (Luint8 u8DeviceAddx, Luint8 u8RegisterAddx, Luint8 * pu8Byte)
Receives a byte from a device.
Note
When passing in the device address, this is the I2C address that the device communicates over It is the NON SHIFTED version. So if you have a device address from the datasheet of 0xEF for read = 0b1110111R then the address you need to supply is actually 0x77 = 0b01110111.
Parameters
[out] *pu8Byte Pointer to Returned byte
[in] u8RegisterAddx Register address on device
[in] u8DeviceAddx Device hardware address on bus
Returns
0 = success
-ve = error
SafeTool Function MD5:
4F45F2FEF8EF0FB4D72FC4384B3F4AF9
SafeTool Function ID:
LCCM215R0.FILE.005.FUNC.007
References C_LCCM215__CORE__FAULT_INDEX__02, C_RM4I2C__ERROR__NO_ERROR, C_RM4I2C__ERROR__TIMEOUT, i2cREG1, _strRM4I2C::sFaultFlags, sRM4I2C, u8RM4_I2C__ReceiveByte(), u8RM4_I2C_WAIT__IsBusBusy(), u8RM4_I2C_WAIT__RxBufferFull(), u8RM4_I2C_WAIT__TxBufferEmpty(), vRM4_I2C__SendByte(), vRM4_I2C__Set_Start(), vRM4_I2C__SetUpTransaction(), and vSIL3_FAULTTREE__Set_Flag().
Referenced by s16RM4_I2C_USER__RxBit_U8(), and s16RM4_I2C_USER__RxBits_U8().
Lint16 s16RM4_I2C_USER__Rx_U8Array (Luint8 u8DeviceAddx, Luint8 u8RegisterAddx, Luint8 * pu8Array, Luint8 u8ArrayLength)
Handles the reception of a byte array from an addx NOTE: Make sure pArray is big enough.
Parameters
[in] u8ArrayLength Length of data to read
[out] pu8Array Pointer to buffer to hold data
[in] u8RegisterAddx The register addx to start reading from
[in] u8DeviceAddx The device address on the bus
Returns
0 = success
-ve error
SafeTool Function MD5:
1E1EF8E7FD5F1AFEBDA8B01511BAAE68
SafeTool Function ID:
LCCM215R0.FILE.005.FUNC.003
References C_LCCM215__CORE__FAULT_INDEX__02, _strRM4I2C::sFaultFlags, sRM4I2C, u8RM4_I2C__ReceiveByte(), u8RM4_I2C_WAIT__IsBusBusy(), u8RM4_I2C_WAIT__RxBufferFull(), u8RM4_I2C_WAIT__TxBufferEmpty(), vRM4_I2C__SendByte(), vRM4_I2C__Set_Start(), vRM4_I2C__SetUpTransaction(), and vSIL3_FAULTTREE__Set_Flag().
Lint16 s16RM4_I2C_USER__RxBit_U8 (Luint8 u8DeviceAddx, Luint8 u8RegisterAddx, Luint8 u8BitNumber, Luint8 * pu8Byte)
Read a single bit from an 8-bit device register.
Parameters
[out] pu8Byte Pointer to the byte (bit) to read
[in] u8BitNumber The bit number in the register
[in] u8RegisterAddx The reg index to read
[in] u8DeviceAddx The I2C device addx on the bus
SafeTool Function MD5:
4D2800FA8FF8F0822CDFB9B3D451D191
SafeTool Function ID:
LCCM215R0.FILE.005.FUNC.005
References s16RM4_I2C_USER__Rx_U8().
Lint16 s16RM4_I2C_USER__RxBits_U8 (Luint8 u8DeviceAddx, Luint8 u8RegisterAddx, Luint8 u8BitStart, Luint8 u8Length, Luint8 * pu8Byte)
Read multiple bits from an 8-bit device register.
Parameters
[out] pu8Byte Container for right-aligned value (i.e. '101' read from any bitStart position will equal 0x05)
[in] u8Length Number of bits to read (not more than 8)
[in] u8BitStart First bit position to read (0-7)
[in] u8RegisterAddx Register regAddr to read from
[in] u8DeviceAddx I2C slave device address
Returns
0 = success
-ve = error
SafeTool Function MD5:
8D01F62FCCA9ADC9A319A28C69592B14
SafeTool Function ID:
LCCM215R0.FILE.005.FUNC.006
References s16RM4_I2C_USER__Rx_U8().
Lint16 s16RM4_I2C_USER__RxByte16 (Luint8 u8DeviceAddx, Luint16 u16RegisterAddx, Luint8 * pu8Byte)
Receive a byte using 16BIT slave addressing.
Parameters
[out] pu8Byte Pointer to the returned byte
[in] u16RegisterAddx The 16BIT slave address
[in] u8DeviceAddx The device address on the bus
SafeTool Function MD5:
EFCC85266B42499A3F124FA0146C98FC
SafeTool Function ID:
LCCM215R0.FILE.005.FUNC.013
References C_LCCM215__CORE__FAULT_INDEX__02, I2C_BUSBUSY, I2C_NACK, I2C_SCD, I2C_TX, i2cREG1, _strRM4I2C::sFaultFlags, sRM4I2C, u8RM4_I2C__IsBusBusy(), u8RM4_I2C__ReceiveByte(), u8RM4_I2C_WAIT__RxBufferFull(), u8RM4_I2C_WAIT__TxBufferEmpty(), u8RM4_I2C_WAIT__TxBufferEmpty_Or_NACK(), vRM4_I2C__SendByte(), vRM4_I2C__Set_Start(), vRM4_I2C__Set_Stop(), vRM4_I2C__SetUpTransaction(), and vSIL3_FAULTTREE__Set_Flag().
Lint16 s16RM4_I2C_USER__RxByteArray16 (Luint8 u8DeviceAddx, Luint16 u16RegisterAddx, Luint8 * pu8Array, Luint8 u8ArrayLength)
Read an array ising 16bit slave addressing.
Parameters
[in] u8ArrayLength The total length of bytes to read
[out] pu8Array Pointer to the returned array
[in] u16RegisterAddx The 16BIT register address
[in] u8DeviceAddx The slave device address
SafeTool Function MD5:
A61476EF411EA5E84E7F082643ED8E4A
SafeTool Function ID:
LCCM215R0.FILE.005.FUNC.014
References C_LCCM215__CORE__FAULT_INDEX__02, i2cREG1, _strRM4I2C::sFaultFlags, sRM4I2C, u8RM4_I2C__IsBusBusy(), u8RM4_I2C__ReceiveByte(), u8RM4_I2C_WAIT__RxBufferFull(), u8RM4_I2C_WAIT__TxBufferEmpty(), vRM4_I2C__SendByte(), vRM4_I2C__Set_Start(), vRM4_I2C__SetUpTransaction(), and vSIL3_FAULTTREE__Set_Flag().
Lint16 s16RM4_I2C_USER__RxReg (Luint8 u8DeviceAddx, Luint8 * pu8Byte)
Non standard set address and then read.
Parameters
[out] *pu8Byte Pointer to Rx byte
[in] u8DeviceAddx I2C device Addx
SafeTool Function MD5:
92F27BF017D1F67179E0E009803B310D
SafeTool Function ID:
LCCM215R0.FILE.005.FUNC.018
References C_LCCM215__CORE__FAULT_INDEX__02, C_RM4I2C__ERROR__NO_ERROR, C_RM4I2C__ERROR__TIMEOUT, i2cREG1, _strRM4I2C::sFaultFlags, sRM4I2C, u8RM4_I2C__ReceiveByte(), u8RM4_I2C_WAIT__IsBusBusy(), u8RM4_I2C_WAIT__RxBufferFull(), vRM4_I2C__Set_Start(), vRM4_I2C__SetUpTransaction(), and vSIL3_FAULTTREE__Set_Flag().
Lint16 s16RM4_I2C_USER__Tx_U8 (Luint8 u8DeviceAddx, Luint8 u8RegisterAddx, Luint8 u8Byte)
Transmits a byte.
Parameters
[in] u8Byte The byte of data to send
[in] u8RegisterAddx The target register address
[in] u8DeviceAddx The device addx on the bus.
Returns
0 = success
-ve = error
SafeTool Function MD5:
914B4F5E1D1E00ED30D8CE407A6A8482
SafeTool Function ID:
LCCM215R0.FILE.005.FUNC.001
References C_LCCM215__CORE__FAULT_INDEX__01, C_RM4I2C__ERROR__NACK, C_RM4I2C__ERROR__NO_ERROR, C_RM4I2C__ERROR__TIMEOUT, i2cREG1, _strRM4I2C::sFaultFlags, sRM4I2C, u8RM4_I2C__Get_NACK(), u8RM4_I2C_WAIT__IsBusBusy(), u8RM4_I2C_WAIT__TxBufferEmpty(), vRM4_I2C__SendByte(), vRM4_I2C__Set_Start(), vRM4_I2C__SetUpTransaction(), and vSIL3_FAULTTREE__Set_Flag().
Lint16 s16RM4_I2C_USER__Tx_U8Array (Luint8 u8DeviceAddx, Luint8 u8RegisterAddx, Luint8 * pu8Array, Luint8 u8ArrayLength)
Transmits a byte array.
Parameters
[in] u8ArrayLength Write length
[in] pu8Array Pointer to data to write
[in] u8RegisterAddx First register addx to write to
[in] u8DeviceAddx Device address on bus
Returns
0 = success
-ve error
SafeTool Function MD5:
BB2229B079CF3655E1011E67483D19CE
SafeTool Function ID:
LCCM215R0.FILE.005.FUNC.004
References C_LCCM215__CORE__FAULT_INDEX__01, i2cREG1, _strRM4I2C::sFaultFlags, sRM4I2C, u8RM4_I2C_WAIT__IsBusBusy(), u8RM4_I2C_WAIT__TxBufferEmpty(), vRM4_I2C__SendByte(), vRM4_I2C__Set_Start(), vRM4_I2C__SetUpTransaction(), and vSIL3_FAULTTREE__Set_Flag().
Lint16 s16RM4_I2C_USER__Tx_U8Array_Constant (Luint8 u8DeviceAddx, Luint8 u8RegisterAddx, Luint8 u8Value, Luint16 u16ArrayLength)
Transmit a byte array of a constant value.
This function is useful for sending data to a LCD.
Parameters
[in] u16ArrayLength ## Desc ##
[in] u8Value ## Desc ##
[in] u8RegisterAddx ## Desc ##
[in] u8DeviceAddx ## Desc ##
SafeTool Function MD5:
DA2A96999D24E78FCDBD355780332D69
SafeTool Function ID:
LCCM215R0.FILE.005.FUNC.016
References C_LCCM215__CORE__FAULT_INDEX__01, i2cREG1, _strRM4I2C::sFaultFlags, sRM4I2C, u8RM4_I2C__IsBusBusy(), u8RM4_I2C_WAIT__TxBufferEmpty(), vRM4_I2C__SendByte(), vRM4_I2C__Set_Start(), vRM4_I2C__SetUpTransaction(), and vSIL3_FAULTTREE__Set_Flag().
Lint16 s16RM4_I2C_USER__TxByte16 (Luint8 u8DeviceAddx, Luint16 u16RegisterAddx, Luint8 u8Byte)
Transmit a byte using 16bit addressing.
Parameters
[in] u8Byte The byte to transmit
[in] u16RegisterAddx The 16BIT register address
[in] u8DeviceAddx The device address on the bus
SafeTool Function MD5:
3DC7D0F761C88C3A60170687A56386E9
SafeTool Function ID:
LCCM215R0.FILE.005.FUNC.012
References C_LCCM215__CORE__FAULT_INDEX__01, C_RM4I2C__ERROR__NACK, C_RM4I2C__ERROR__NO_ERROR, C_RM4I2C__ERROR__TIMEOUT, i2cREG1, _strRM4I2C::sFaultFlags, sRM4I2C, u8RM4_I2C__Get_NACK(), u8RM4_I2C_WAIT__IsBusBusy(), u8RM4_I2C_WAIT__TxBufferEmpty(), vRM4_I2C__SendByte(), vRM4_I2C__Set_Start(), vRM4_I2C__SetUpTransaction(), and vSIL3_FAULTTREE__Set_Flag().
Lint16 s16RM4_I2C_USER__TxReg (Luint8 u8DeviceAddx, Luint8 u8RegisterAddx)
Only transmit the register address This is useful for devices that just need a ping to do something useful and dont need any additional data.
Parameters
[in] u8RegisterAddx The register address
[in] u8DeviceAddx The I2C device address
Returns
+ve = success
-ve = error
SafeTool Function MD5:
DD444F4FB0CDD131B9151410BFAA5051
SafeTool Function ID:
LCCM215R0.FILE.005.FUNC.017
References C_LCCM215__CORE__FAULT_INDEX__01, C_RM4I2C__ERROR__NO_ERROR, C_RM4I2C__ERROR__TIMEOUT, i2cREG1, _strRM4I2C::sFaultFlags, sRM4I2C, u8RM4_I2C_WAIT__IsBusBusy(), u8RM4_I2C_WAIT__TxBufferEmpty(), vRM4_I2C__SendByte(), vRM4_I2C__Set_Start(), vRM4_I2C__SetUpTransaction(), and vSIL3_FAULTTREE__Set_Flag().
Luint32 u32RM4_I2C_USER__Get_FaultFlags (void)
Returns the I2C modules fault flags.
Returns
Any fault flag values
SafeTool Function MD5:
FBEC632B374F529C627CFF3361FDC816
SafeTool Function ID:
LCCM215R0.FILE.005.FUNC.011
References _strRM4I2C::sFaultFlags, sRM4I2C, and FAULT_TREE__PUBLIC_T::u32Flags.
void vRM4_I2C_USER__Init (void)
User call to init the module.
SafeTool Function MD5:
B89957B16091B5F6ECA77D15CFED4016
SafeTool Function ID:
LCCM215R0.FILE.005.FUNC.010
References _strRM4I2C::sFaultFlags, sRM4I2C, vRM4_I2C__Init(), and vSIL3_FAULTTREE__Init().
Variable Documentation
struct _strRM4I2C sRM4I2C
Referenced by s16RM4_I2C_USER__Rx_U8(), s16RM4_I2C_USER__Rx_U8Array(), s16RM4_I2C_USER__RxByte16(), s16RM4_I2C_USER__RxByteArray16(), s16RM4_I2C_USER__RxReg(), s16RM4_I2C_USER__Tx_U8(), s16RM4_I2C_USER__Tx_U8Array(), s16RM4_I2C_USER__Tx_U8Array_Constant(), s16RM4_I2C_USER__TxByte16(), s16RM4_I2C_USER__TxReg(), u32RM4_I2C_USER__Get_FaultFlags(), and vRM4_I2C_USER__Init().