LFW615 (RLOOP - AUX PROP UNIT (APU)): COMMON_CODE/RM4/LCCM126__RM4__CAN/ERRORS/rm4_can__errors.c File Reference
rm4_can__errors.c File Reference
#include "../rm4_can.h"
Functions
Luint8 u8RM4_CAN_ERROR__Get_TxErrorCount (RM4_CAN__CHANNEL_E eChannel)
Return the tranmsit error count.
Luint8 u8RM4_CAN_ERROR__Get_RxErrorCount (RM4_CAN__CHANNEL_E eChannel)
Get the Rx error count.
Luint32 u32RM4_CAN_ERROR__Get_LastError (RM4_CAN__CHANNEL_E eChannel)
Gets last RX/TX-Error of CAN message traffic.
Luint32 u32RM4_CAN_ERROR__Get_ErrorLevel (RM4_CAN__CHANNEL_E eChannel)
Gets error level of a CAN node.
void vRM4_CAN_ERROR__Enable_ErrorNotification (RM4_CAN__CHANNEL_E eChannel)
Enable error notification This function will enable the notification for the reaching the error levels warning, passive and bus off.
void vRM4_CAN_ERROR__Disable_ErrorNotification (RM4_CAN__CHANNEL_E eChannel)
Disable error notifications This function will disable the notification for the reaching the error levels warning, passive and bus off.
Variables
struct _strRM4CAN sRM4CAN
Function Documentation
Luint32 u32RM4_CAN_ERROR__Get_ErrorLevel (RM4_CAN__CHANNEL_E eChannel)
Gets error level of a CAN node.
This function returns the current error level of a CAN node. : : canLEVEL_ACTIVE [0x00U): When RX- and TX error counters are below 96 : canLEVEL_WARNING [0x40): When RX- or TX error counter are between 96 and 127 : canLEVEL_PASSIVE [0x20): When RX- or TX error counter are between 128 and 255 : canLEVEL_BUS_OFF [0x80): When RX- or TX error counter are above 255
Parameters
[in] eChannel The CAN controller channel
SafeTool Function MD5:
48965993FFC0E5153AEBC5733B884E74
SafeTool Function ID:
LCCM126R0.FILE.003.FUNC.002
References C_LCCM126__FAULT_INDEX__00, canREG1, canREG2, canREG3, _strRM4CAN::sFaultFlags, sRM4CAN, and vSIL3_FAULTTREE__Set_Flag().
Luint32 u32RM4_CAN_ERROR__Get_LastError (RM4_CAN__CHANNEL_E eChannel)
Gets last RX/TX-Error of CAN message traffic.
The function will return: : 0 is flag not set otherwise will return the validation flag itself. : canERROR_OK [0): When no CAN error occured : canERROR_STUFF [1): When a stuff error occured on RX message : canERROR_FORMAT [2): When a form/format error occured on RX message : canERROR_ACKNOWLEDGE [3): When a TX message wasn't acknowledged : canERROR_BIT1 [4): When a TX message monitored dominant level where recessive is expected : canERROR_BIT0 [5): When a TX message monitored recessive level where dominant is expected : canERROR_CRC [6): When a RX message has wrong CRC value : canERROR_NO [7): When no error occured since last call of this function : The function canInit has to be called before this function can be used
Parameters
[in] eChannel The CAN controller channel
SafeTool Function MD5:
A50E989372E0C4BF67FE0B01BE78FE00
SafeTool Function ID:
LCCM126R0.FILE.003.FUNC.001
References C_LCCM126__FAULT_INDEX__00, canREG1, canREG2, canREG3, _strRM4CAN::sFaultFlags, sRM4CAN, and vSIL3_FAULTTREE__Set_Flag().
Luint8 u8RM4_CAN_ERROR__Get_RxErrorCount (RM4_CAN__CHANNEL_E eChannel)
Get the Rx error count.
Parameters
[in] eChannel The channel
Returns
The Rx Error Count
SafeTool Function MD5:
1C00F42F7938A13BB21B71651627A89A
SafeTool Function ID:
LCCM126R0.FILE.003.FUNC.006
References C_LCCM126__FAULT_INDEX__00, canREG1, canREG2, canREG3, _strRM4CAN::sFaultFlags, sRM4CAN, and vSIL3_FAULTTREE__Set_Flag().
Referenced by vRM4_CAN__Process().
Luint8 u8RM4_CAN_ERROR__Get_TxErrorCount (RM4_CAN__CHANNEL_E eChannel)
Return the tranmsit error count.
Parameters
[in] eChannel The channel
Returns
The error count
SafeTool Function MD5:
504B1ED6F906E65A7F20732A93E12C65
SafeTool Function ID:
LCCM126R0.FILE.003.FUNC.005
References C_LCCM126__FAULT_INDEX__00, canREG1, canREG2, canREG3, _strRM4CAN::sFaultFlags, sRM4CAN, and vSIL3_FAULTTREE__Set_Flag().
Referenced by vRM4_CAN__Process().
void vRM4_CAN_ERROR__Disable_ErrorNotification (RM4_CAN__CHANNEL_E eChannel)
Disable error notifications This function will disable the notification for the reaching the error levels warning, passive and bus off.
Parameters
[in] eChannel The CAN controller channel
SafeTool Function MD5:
C192271C45F04AA134764C4A862C9331
SafeTool Function ID:
LCCM126R0.FILE.003.FUNC.004
References C_LCCM126__FAULT_INDEX__00, canREG1, canREG2, canREG3, _strRM4CAN::sFaultFlags, sRM4CAN, and vSIL3_FAULTTREE__Set_Flag().
void vRM4_CAN_ERROR__Enable_ErrorNotification (RM4_CAN__CHANNEL_E eChannel)
Enable error notification This function will enable the notification for the reaching the error levels warning, passive and bus off.
Parameters
[in] eChannel The CAN controller channel
SafeTool Function MD5:
97440BD231B80065807E2EF18E396A4C
SafeTool Function ID:
LCCM126R0.FILE.003.FUNC.003
References C_LCCM126__FAULT_INDEX__00, canREG1, canREG2, canREG3, _strRM4CAN::sFaultFlags, sRM4CAN, and vSIL3_FAULTTREE__Set_Flag().
Variable Documentation
struct _strRM4CAN sRM4CAN
Referenced by u32RM4_CAN_ERROR__Get_ErrorLevel(), u32RM4_CAN_ERROR__Get_LastError(), u8RM4_CAN_ERROR__Get_RxErrorCount(), u8RM4_CAN_ERROR__Get_TxErrorCount(), vRM4_CAN_ERROR__Disable_ErrorNotification(), and vRM4_CAN_ERROR__Enable_ErrorNotification().