LFW615 (RLOOP - AUX PROP UNIT (APU)): COMMON_CODE/RM4/LCCM220__RM4__ERROR_SIGNAL_MODULE/rm4_esm.h File Reference
rm4_esm.h File Reference
Header for error signalling module.
#include <localdef.h>
#include <RM4/LCCM220__RM4__ERROR_SIGNAL_MODULE/rm4_esm__private.h>
#include <RM4/LCCM220__RM4__ERROR_SIGNAL_MODULE/rm4_esm__fault_flags.h>
#include <RM4/LCCM220__RM4__ERROR_SIGNAL_MODULE/rm4_esm__fault_flags_g2.h>
#include <MULTICORE/LCCM284__MULTICORE__FAULT_TREE/fault_tree__public.h>
Data Structures
struct _strRM4ESM
struct esm_config_reg
Typedefs
typedef enum esmSelfTestFlag esmSelfTestFlag_t
ESM Self-Test Status Type Definition.
typedef struct esm_config_reg esm_config_reg_t
Enumerations
enum esmSelfTestFlag {
esmSelfTest_Passed = 0U,
esmSelfTest_Active = 1U,
esmSelfTest_NotStarted = 2U,
esmSelfTest_Failed = 3U
}
Functions
void vRM4_ESM__Init (void)
Initializes Esm Driver.
Luint32 u32RM4_ESM__Get_FaultFlags_G1 (void)
ToDo.
Luint32 u32RM4_ESM__Get_FaultFlags_G2 (void)
ToDo.
void vRM4_ESM__Group1_Notification (Luint32 channel)
ToDo.
void vRM4_ESM__Group2_Notification (Luint32 channel)
ToDo.
Luint32 u32RM4_ESM__Get_Error (void)
Return Error status.
void vRM4_ESM__Enable_Error (Luint64 channels)
Enable Group 1 Channels Error Signals propagation Enable Group 1 Channels Error Signals propagation to the error pin.
void vRM4_ESM__HighInterrupt (void)
High Level Interrupt for ESM.
esmSelfTestFlag_t tRM4_ESM__SelfTestStatus (void)
Return ESM Self test status.
esmSelfTestFlag_t pRM4_ESM__EnterSelfTest (void)
Return ESM Self test status.
Luint64 vRM4_ESM__Get_StatusBuffer (Luint64 u64Channels)
Return Group 2 channel x Error status buffer Returns the group 2 buffered status of selected channels.
Luint64 vRM4_ESM__Get_Status (Luint32 u32Group, Luint64 u64Channels)
Return Error status Returns the channels status of selected group.
void vRM4_ESM__Set_CounterPreloadValue (Luint32 u32Value)
Set counter preload value.
void vRM4_ESM__ClearStatusBuffer (Luint64 u64Channels)
Clear Group 2 error status buffer.
void vRM4_ESM__ClearStatus (Luint32 u32Group, Luint64 u64Channels)
Clear Group error status.
void vRM4_ESM__Set_InterruptLevel (Luint64 u64Channels, Luint64 u64Flags)
Set Group 1 Channels Interrupt Levels.
void vRM4_ESM__DisableInterrupt (Luint64 u64Channels)
Disable Group 1 Channels Interrupts.
void vRM4_ESM__EnableInterrupt (Luint64 u64Channels)
Enable Group 1 Channels Interrupts.
void vRM4_ESM__ActivateNormalOperation (void)
Activate normal operation.
void vRM4_ESM__TriggerErrorPinReset (void)
Trigger error pin reset and switch back to normal operation.
void vRM4_ESM__DisableError (Luint64 u64Channels)
Disable Group 1 Channels Error Signals propagation Disable Group 1 Channels Error Signals propagation to the error pin.
Detailed Description
Header for error signalling module.
Author
Lachlan Grogan
Copyright
This file contains proprietary and confidential information of SIL3 Pty. Ltd. (ACN 123 529 064). This code may be distributed under a license from SIL3 Pty. Ltd., and may be used, copied and/or disclosed only pursuant to the terms of that license agreement. This copyright notice must be retained as part of this file at all times.
This file is copyright SIL3 Pty. Ltd. 2003-2016, All Rights Reserved.
SafeTool FileID:
LCCM220R0.FILE.002
Typedef Documentation
typedef struct esm_config_reg esm_config_reg_t
esmSelfTestFlag_t
ESM Self-Test Status Type Definition.
This type is used to represent ESM Self-Test Status.
Enumeration Type Documentation
enum esmSelfTestFlag
Enumerator
esmSelfTest_Passed
esmSelfTest_Active
esmSelfTest_NotStarted
esmSelfTest_Failed
Function Documentation
void vRM4_ESM__Group1_Notification (Luint32 u32Channel)
ToDo.
Parameters
[in] u32Channel The error channel
SafeTool Function MD5:
FF60B380179EA3404C1CD0720481C8F7
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.018
Referenced by vRM4_ESM__HighInterrupt(), and vRM4_VIM_ISR__ParityErrorHandler().
void vRM4_ESM__Group2_Notification (Luint32 u32Channel)
ToDo.
Parameters
[in] u32Channel The error channel
SafeTool Function MD5:
41F706FECBF7690EFDA878D46702C7D7
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.019
Referenced by vRM4_ESM__HighInterrupt(), and vRM4_VIM_ISR__ParityErrorHandler().