LFW615 (RLOOP - AUX PROP UNIT (APU)): COMMON_CODE/RM4/LCCM126__RM4__CAN/rm4_can__functions.c File Reference
rm4_can__functions.c File Reference
RM4 CAN Main Functions.
#include "rm4_can.h"
Functions
tsCANInterface * tsRM4_CAN_FUNCTIONS__Get_AvailableWriteInterface (RM4_CAN__CHANNEL_E eChannel)
Finds an available write interface for the.
void vRM4_CAN_FUNCTIONS__Configure_MessageObject (RM4_CAN__CHANNEL_E eChannel, Luint32 u32MessageObjectNumber, RM4_CAN__MSGOBJ_DIRECTION_E eDirection, Luint32 u32SingleFrame, Luint32 u32IDEMask, Luint32 u32SID)
Function to configure the required message objects.
Lint16 s16RM4_CAN_FUNCTIONS__Configure_FIFO (RM4_CAN__CHANNEL_E eChannel, Luint8 u8FirstObject, Luint8 u8Size)
#brief Configures a CAN's FIFO for Rx
Variables
struct _strRM4CAN sRM4CAN
Detailed Description
RM4 CAN Main Functions.
Author
Lachlan Grogan
Copyright
This file contains proprietary and confidential information of the Lockie Group of companies, including Lockie Innovation Pty. Ltd (ACN 123 529 064) and Lockie Safety Systems Pty. Ltd (ACN 132 340 571). This code may be distributed under a license from the Lockie Group of companies, and may be used, copied and/or disclosed only pursuant to the terms of that license agreement. This copyright notice must be retained as part of this file at all times.
This file is copyright Lockie Innovation Pty Ltd 2003-2012, All Rights Reserved.
This file is copyright Lockie Safety Systems Pty Ltd 2008-2012, All Rights Reserved.
SafeTool FileID:
LCCM126R0.FILE.004
Function Documentation
Lint16 s16RM4_CAN_FUNCTIONS__Configure_FIFO (RM4_CAN__CHANNEL_E eChannel, Luint8 u8FirstObject, Luint8 u8Size)
#brief Configures a CAN's FIFO for Rx
Parameters
[in] u8Size FIFO Size
[in] u8FirstObject ## Desc ##
[in] eChannel The CAN device channel
Returns
0 = success, FIFO created successfull
-1 = FIFO Size too big to fit in hardware
-2 = First fifo obj out of range
-3 = FIFO out of range
SafeTool Function MD5:
80862E620E2644609686F5835E5F75C8
SafeTool Function ID:
LCCM126R0.FILE.004.FUNC.002
References MSGOBJ_DIR__RECEIVE, RM48_DCANIFMCTL_MULTI_FRAME, RM48_DCANIFMCTL_SINGLE_FRAME, RM48L950_CAN_NUMBER_OF_MSG_OBJ_IN_HARDWARE, and vRM4_CAN_FUNCTIONS__Configure_MessageObject().
Referenced by vRM4_CAN__Init().
tsCANInterface* tsRM4_CAN_FUNCTIONS__Get_AvailableWriteInterface (RM4_CAN__CHANNEL_E eChannel)
Finds an available write interface for the.
Parameters
[in] eChannel The CAN channel to use
SafeTool Function MD5:
24605716C83612BDBF28C5C60455B016
SafeTool Function ID:
LCCM126R0.FILE.004.FUNC.001
References C_LCCM126__FAULT_INDEX__00, C_RM4_CAN__IF1_OFFSET, C_RM4_CAN__IF2_OFFSET, canREG1, canREG2, canREG3, _strRM4CAN::sFaultFlags, sRM4CAN, and vSIL3_FAULTTREE__Set_Flag().
Referenced by s16RM4_CAN_RX__RxMessage_Worker(), s16RM4_CAN_TX__TxMessage_Worker(), and vRM4_CAN_FUNCTIONS__Configure_MessageObject().
void vRM4_CAN_FUNCTIONS__Configure_MessageObject (RM4_CAN__CHANNEL_E eChannel, Luint32 u32MessageObjectNumber, RM4_CAN__MSGOBJ_DIRECTION_E eDirection, Luint32 u32SingleFrame, Luint32 u32IDEMask, Luint32 u32SID)
Function to configure the required message objects.
The DCAN Message RAM contains message objects and parity bits for the message objects.
Parameters
[in] u32SID The standard ID for this message object.
[in] u32IDEMask The identifier mask. Any bits which are cleared in this are not used for the id. Therefore a value of 0 indicates a don't care
[in] u32SingleFrame ## Desc ##
[in] eDirection ## Desc ##
[in] u32MessageObjectNumber ## Desc ##
[in] eChannel The CAN Channel
SafeTool Function MD5:
D347AA5E9E3A353C3B8A26B89E750A59
SafeTool Function ID:
LCCM126R0.FILE.004.FUNC.003
References RM48_DCANIFCMD_CHANGE_ARB, RM48_DCANIFCMD_CHANGE_CTRL, RM48_DCANIFCMD_CHANGE_INT_PEN, RM48_DCANIFCMD_CHANGE_MASK, RM48_DCANIFCMD_KEEP_DATA_A, RM48_DCANIFCMD_KEEP_DATA_B, RM48_DCANIFCMD_KEEP_TX_RQST_RD, RM48_DCANIFCMD_WRITE, and tsRM4_CAN_FUNCTIONS__Get_AvailableWriteInterface().
Referenced by s16RM4_CAN_FUNCTIONS__Configure_FIFO(), and vRM4_CAN__Init().
Variable Documentation
struct _strRM4CAN sRM4CAN
Referenced by tsRM4_CAN_FUNCTIONS__Get_AvailableWriteInterface().