LFW615 (RLOOP - AUX PROP UNIT (APU)): COMMON_CODE/RM4/LCCM126__RM4__CAN/rm4_can__msgfifo.c File Reference
rm4_can__msgfifo.c File Reference
FIFO Functions for CAN.
#include "rm4_can.h"
Functions
void vRM4_CAN_SWFIFO__Init (RM4_CAN__SWFIFO_T *pCANFIFO)
Inits the FIFO.
Lint16 s16RM4_CAN_SWFIFO__Push (RM4_CAN__SWFIFO_T *pCANFIFO, CANRxMessageBuffer tuMessage)
Push data onto the FIFO Push new CAN data on to the software FIFO.
Lint16 s16RM4_CAN_SWFIFO__Pop (RM4_CAN__SWFIFO_T *pCANFIFO, CANRxMessageBuffer *pMsg)
POP a message from the fifo and return the message.
void vRM4_CAN_SWFIFO__Get (RM4_CAN__SWFIFO_T *pCANFIFO, CANRxMessageBuffer *pMsg)
Gets the current message from the FIFO, but does not pop the FIFO.
Luint8 u8RM4_CAN_SWFIFO__Is_Empty (RM4_CAN__SWFIFO_T *pCANFIFO)
Checks to see if the FIFO is empty.
Detailed Description
FIFO Functions for CAN.
Author
Lachlan Grogan
Copyright
This file contains proprietary and confidential information of the Lockie Group of companies, including Lockie Innovation Pty. Ltd (ACN 123 529 064) and Lockie Safety Systems Pty. Ltd (ACN 132 340 571). This code may be distributed under a license from the Lockie Group of companies, and may be used, copied and/or disclosed only pursuant to the terms of that license agreement. This copyright notice must be retained as part of this file at all times.
This file is copyright Lockie Innovation Pty Ltd 2003-2012, All Rights Reserved.
This file is copyright Lockie Safety Systems Pty Ltd 2008-2012, All Rights Reserved.
SafeTool FileID:
LCCM126R0.FILE.007
Function Documentation
Lint16 s16RM4_CAN_SWFIFO__Pop (RM4_CAN__SWFIFO_T * pCANFIFO, CANRxMessageBuffer * pMsg)
POP a message from the fifo and return the message.
Parameters
[in] * ## Desc ##
SafeTool Function MD5:
3B54C1A9247A218D4F16A8A4FCB86FC7
SafeTool Function ID:
LCCM126R0.FILE.007.FUNC.003
References RM4_CAN__SWFIFO_T::tuCANMessageBuffer, RM4_CAN__SWFIFO_T::u8FIFO_Empty, RM4_CAN__SWFIFO_T::u8FIFO_FillLevel, RM4_CAN__SWFIFO_T::u8FIFO_Full, RM4_CAN__SWFIFO_T::u8FIFO_ReadPosition, and RM4_CAN__SWFIFO_T::u8FIFO_WritePosition.
Referenced by vRM4_CAN_RX__RxMessage().
Lint16 s16RM4_CAN_SWFIFO__Push (RM4_CAN__SWFIFO_T * pCANFIFO, CANRxMessageBuffer tuMessage)
Push data onto the FIFO Push new CAN data on to the software FIFO.
Parameters
[in] tuMessage ## Desc ##
[in] pCANFIFO Pointer to FIFO
SafeTool Function MD5:
A8106A2ABADB553D4F704D9775A19CF6
SafeTool Function ID:
LCCM126R0.FILE.007.FUNC.002
References RM4_CAN__SWFIFO_T::tuCANMessageBuffer, RM4_CAN__SWFIFO_T::u8FIFO_Empty, RM4_CAN__SWFIFO_T::u8FIFO_FillLevel, RM4_CAN__SWFIFO_T::u8FIFO_Full, and RM4_CAN__SWFIFO_T::u8FIFO_WritePosition.
Referenced by u8RM4_CAN_RX__ExtractAllMessagesFromHardwareFIFO().
Luint8 u8RM4_CAN_SWFIFO__Is_Empty (RM4_CAN__SWFIFO_T * pCANFIFO)
Checks to see if the FIFO is empty.
Parameters
[in] pCANFIFO Pointer to the can fifo structure
Returns
1 = Empty
0 = Not Empty
SafeTool Function MD5:
B2EBACF9FE6B46DD463434A8146CDA5E
SafeTool Function ID:
LCCM126R0.FILE.007.FUNC.005
References RM4_CAN__SWFIFO_T::u8FIFO_Empty.
Referenced by u8RM4_CAN_RX__Is_MessageAvailable().
void vRM4_CAN_SWFIFO__Get (RM4_CAN__SWFIFO_T * pCANFIFO, CANRxMessageBuffer * pMsg)
Gets the current message from the FIFO, but does not pop the FIFO.
Parameters
[in] * ## Desc ##
SafeTool Function MD5:
01BB1EE1F57B901C469F2E4973BA2BCB
SafeTool Function ID:
LCCM126R0.FILE.007.FUNC.004
References RM4_CAN__SWFIFO_T::tuCANMessageBuffer, and RM4_CAN__SWFIFO_T::u8FIFO_ReadPosition.
void vRM4_CAN_SWFIFO__Init (RM4_CAN__SWFIFO_T * pCANFIFO)
Inits the FIFO.
Parameters
[in] pCANFIFO pointer to the FIFO structure
SafeTool Function MD5:
259D26269665B9A95A3454986144976B
SafeTool Function ID:
LCCM126R0.FILE.007.FUNC.001
References RM4_CAN__SWFIFO_T::u8FIFO_Empty, RM4_CAN__SWFIFO_T::u8FIFO_FillLevel, RM4_CAN__SWFIFO_T::u8FIFO_Full, RM4_CAN__SWFIFO_T::u8FIFO_ReadPosition, and RM4_CAN__SWFIFO_T::u8FIFO_WritePosition.
Referenced by vRM4_CAN__Init().