LFW615 (RLOOP - AUX PROP UNIT (APU)): COMMON_CODE/RM4/LCCM220__RM4__ERROR_SIGNAL_MODULE/rm4_esm__user_template.c File Reference
rm4_esm__user_template.c File Reference
#include "rm4_esm.h"
Functions
void vRM4_ESM__Group1_Notification (Luint32 u32Channel)
ToDo.
void vRM4_ESM__Group2_Notification (Luint32 u32Channel)
ToDo.
Function Documentation
void vRM4_ESM__Group1_Notification (Luint32 u32Channel)
ToDo.
Parameters
[in] u32Channel The error channel
SafeTool Function MD5:
FF60B380179EA3404C1CD0720481C8F7
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.018
Referenced by vRM4_ESM__HighInterrupt(), and vRM4_VIM_ISR__ParityErrorHandler().
void vRM4_ESM__Group2_Notification (Luint32 u32Channel)
ToDo.
Parameters
[in] u32Channel The error channel
SafeTool Function MD5:
41F706FECBF7690EFDA878D46702C7D7
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.019
Referenced by vRM4_ESM__HighInterrupt(), and vRM4_VIM_ISR__ParityErrorHandler().