(C Code, RLOOP, Flight Control Core): FLIGHT_CONTROLLER/BLENDER/fcu__flight__blender.c File Reference
fcu__flight__blender.c File Reference
#include "../../fcu_core.h"
Functions
void vFCU_FCTL_BLENDER__Init (void)
ToDo.
void vFCU_FCTL_BLENDER__Process (void)
ToDo.
Lint32 s32FCU_FCTL_BLENDER__Get_Accel_mmss (void)
ToDo.
Lint32 s32FCU_FCTL_BLENDER__Get_Veloc_mms (void)
ToDo.
Lint32 s32FCU_FCTL_BLENDER__Get_Displacement_mm (void)
ToDo.
void vFCU_FCTL_BLENDER__Veloc_UpdateFrom_Accel (Luint8 u8Channel, Luint32 u32Veloc_mms)
ToDo.
void vFCU_FCTL_BLENDER__Veloc_UpdateFrom_LRF (Luint8 u8Channel, Luint32 u32Veloc_mms)
ToDo.
void vFCU_FCTL_BLENDER__Veloc_UpdateFrom_Contrast (Luint8 u8Channel, Luint32 u32Veloc_mms)
ToDo.
void vFCU_FCTL_BLENDER__Accel_UpdateFrom_Accel (Luint8 u8Channel, Luint32 u32Accel_mmss)
ToDo.
void vFCU_FCTL_BLENDER__Accel_UpdateFrom_LRF (Luint8 u8Channel, Luint32 u32Accel_mmss)
ToDo.
void vFCU_FCTL_BLENDER__Accel_UpdateFrom_Contrast (Luint8 u8Channel, Luint32 u32Accel_mmss)
ToDo.
void vFCU_FCTL_BLENDER__Displacement_UpdateFrom_Accel (Luint8 u8Channel, Luint32 u32Disp_mm)
ToDo.
void vFCU_FCTL_BLENDER__Displacement_UpdateFrom_LRF (Luint8 u8Channel, Luint32 u32Disp_mm)
ToDo.
void vFCU_FCTL_BLENDER__Displacement_UpdateFrom_Contrast (Luint8 u8Channel, Luint32 u32Disp_mm)
ToDo.
Variables
struct _strFCU sFCU
Function Documentation
Lint32 s32FCU_FCTL_BLENDER__Get_Accel_mmss (void)
ToDo.
SafeTool Function MD5:
04CC27AC99940E871624E78E33672C83
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.003
References _strFCU::sBlender, sFCU, and _strFCU::sFlightControl.
Referenced by vFCU_NET_SPACEX_TX__Process().
Lint32 s32FCU_FCTL_BLENDER__Get_Displacement_mm (void)
ToDo.
SafeTool Function MD5:
EAA5F1CFCA6CE2E031FD233665A309D1
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.005
References _strFCU::sBlender, sFCU, and _strFCU::sFlightControl.
Referenced by vFCU_NET_SPACEX_TX__Process().
Lint32 s32FCU_FCTL_BLENDER__Get_Veloc_mms (void)
ToDo.
SafeTool Function MD5:
7323B04512CB94BB9AE1D2F14756DE75
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.004
References _strFCU::sBlender, sFCU, and _strFCU::sFlightControl.
Referenced by vFCU_NET_SPACEX_TX__Process().
void vFCU_FCTL_BLENDER__Accel_UpdateFrom_Accel (Luint8 u8Channel, Luint32 u32Accel_mmss)
ToDo.
Parameters
[in] u32Accel_mmss ## Desc ##
[in] u8Channel ## Desc ##
SafeTool Function MD5:
D0DDA1FC5BC49388A1AFD578BAEBF3F1
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.009
Referenced by vFCU_ACCEL__Process().
void vFCU_FCTL_BLENDER__Accel_UpdateFrom_Contrast (Luint8 u8Channel, Luint32 u32Accel_mmss)
ToDo.
Parameters
[in] u32Accel_mmss ## Desc ##
[in] u8Channel ## Desc ##
SafeTool Function MD5:
B584AA4C4391361450C62BFDE003C99A
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.011
void vFCU_FCTL_BLENDER__Accel_UpdateFrom_LRF (Luint8 u8Channel, Luint32 u32Accel_mmss)
ToDo.
Parameters
[in] u32Accel_mmss ## Desc ##
[in] u8Channel ## Desc ##
SafeTool Function MD5:
655026A0D75A99EE8E7EBE3FDBFEFEE3
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.010
void vFCU_FCTL_BLENDER__Displacement_UpdateFrom_Accel (Luint8 u8Channel, Luint32 u32Disp_mm)
ToDo.
Parameters
[in] u32Disp_mm ## Desc ##
[in] u8Channel ## Desc ##
SafeTool Function MD5:
129388323E9D8D7D2541218E26D05374
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.012
Referenced by vFCU_ACCEL__Process().
void vFCU_FCTL_BLENDER__Displacement_UpdateFrom_Contrast (Luint8 u8Channel, Luint32 u32Disp_mm)
ToDo.
Parameters
[in] u32Disp_mm ## Desc ##
[in] u8Channel ## Desc ##
SafeTool Function MD5:
EF8AE94096E136C3DE982D043F64045C
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.014
void vFCU_FCTL_BLENDER__Displacement_UpdateFrom_LRF (Luint8 u8Channel, Luint32 u32Disp_mm)
ToDo.
Parameters
[in] u32Disp_mm ## Desc ##
[in] u8Channel ## Desc ##
SafeTool Function MD5:
C1359FA82075785458C825BDCA155672
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.013
void vFCU_FCTL_BLENDER__Init (void)
ToDo.
SafeTool Function MD5:
6B43487B4AB4C611614B83DC0EEEBF49
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.001
References _strFCU::sBlender, sFCU, and _strFCU::sFlightControl.
void vFCU_FCTL_BLENDER__Process (void)
ToDo.
SafeTool Function MD5:
31AE84EF1368AB58CB3EB6C6317023B7
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.002
void vFCU_FCTL_BLENDER__Veloc_UpdateFrom_Accel (Luint8 u8Channel, Luint32 u32Veloc_mms)
ToDo.
Parameters
[in] u32Veloc_mms ## Desc ##
[in] u8Channel ## Desc ##
SafeTool Function MD5:
59777C3CBA664752E7B836BBF31863CA
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.006
Referenced by vFCU_ACCEL__Process().
void vFCU_FCTL_BLENDER__Veloc_UpdateFrom_Contrast (Luint8 u8Channel, Luint32 u32Veloc_mms)
ToDo.
Parameters
[in] u32Veloc_mms ## Desc ##
[in] u8Channel ## Desc ##
SafeTool Function MD5:
DA62E13F32AAB193E5867676F9F40554
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.008
void vFCU_FCTL_BLENDER__Veloc_UpdateFrom_LRF (Luint8 u8Channel, Luint32 u32Veloc_mms)
ToDo.
Parameters
[in] u32Veloc_mms ## Desc ##
[in] u8Channel ## Desc ##
SafeTool Function MD5:
1A965AB11BC3801E8CBD37BA6AF48288
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.007