(C Code, RLOOP, Flight Control Core): fcu_core.h File Reference
fcu_core.h File Reference
Main header for the FCU.
#include <localdef.h>
#include <LCCM655__RLOOP__FCU_CORE/fcu_core__types.h>
#include <LCCM655__RLOOP__FCU_CORE/fcu_core__defines.h>
#include <LCCM655__RLOOP__FCU_CORE/fcu_core__enums.h>
#include <LCCM655__RLOOP__FCU_CORE/FAULTS/fcu__faults__fault_flags.h>
#include <LCCM655__RLOOP__FCU_CORE/fcu_core__fault_flags.h>
#include <LCCM655__RLOOP__FCU_CORE/BRAKES/fcu__brakes__fault_flags.h>
#include <LCCM655__RLOOP__FCU_CORE/ACCELEROMETERS/fcu__accel__fault_flags.h>
#include <LCCM655__RLOOP__FCU_CORE/LASER_OPTO/fcu__laser_opto__fault_flags.h>
#include <LCCM655__RLOOP__FCU_CORE/THROTTLES/fcu__throttles__fault_flags.h>
#include <LCCM655__RLOOP__FCU_CORE/LASER_DISTANCE/fcu__laser_distance__fault_flags.h>
#include <LCCM655__RLOOP__FCU_CORE/ASI_RS485/fcu__asi_defines.h>
#include <LCCM655__RLOOP__FCU_CORE/ASI_RS485/fcu__asi_types.h>
#include <LCCM655__RLOOP__FCU_CORE/NETWORKING/fcu_core__net__packet_types.h>
#include <MULTICORE/LCCM284__MULTICORE__FAULT_TREE/fault_tree__public.h>
#include <MULTICORE/LCCM418__MULTICORE__MMA8451/mma8451__types.h>
Data Structures
struct _strFCU
main flight control structure
struct _strFCU::strThrottleInterfaceData
Input data for throttle layer.
Macros
#define C_MLP__MAX_AVERAGE_SIZE (8U)
Functions
DLL_DECLARATION void vFCU__Init (void)
Init the FCU.
DLL_DECLARATION void vFCU__Process (void)
Process any FCU tasks.
DLL_DECLARATION void vFCU__RTI_100MS_ISR (void)
100ms timer
DLL_DECLARATION void vFCU__RTI_10MS_ISR (void)
10ms timer
void vFCU_FCTL__Init (void)
Init any variables as is needed by the main state machine.
void vFCU_FCTL__Process (void)
Process the flight controller.
void vFCU_FCTL_MAINSM__Init (void)
void vFCU_FCTL_MAINSM__Process (void)
void vFCU_FCTL_MAINSM__10MS_ISR (void)
void vFCU_FCTL_MAINSM__100MS_ISR (void)
void vFCU_FCTL_MAINSM__MISERABLE_STOP_100MS_ISR (void)
Luint32 u32FCU_NET_RX__GetGsCommTimer (void)
void vFCU_FCTL_BLENDER__Init (void)
ToDo.
void vFCU_FCTL_BLENDER__Process (void)
ToDo.
Lint32 s32FCU_FCTL_BLENDER__Get_Accel_mmss (void)
ToDo.
Lint32 s32FCU_FCTL_BLENDER__Get_Veloc_mms (void)
ToDo.
Lint32 s32FCU_FCTL_BLENDER__Get_Displacement_mm (void)
ToDo.
void vFCU_FCTL_BLENDER__Veloc_UpdateFrom_Accel (Luint8 u8Channel, Luint32 u32Veloc_mms)
ToDo.
void vFCU_FCTL_BLENDER__Veloc_UpdateFrom_LRF (Luint8 u8Channel, Luint32 u32Veloc_mms)
ToDo.
void vFCU_FCTL_BLENDER__Veloc_UpdateFrom_Contrast (Luint8 u8Channel, Luint32 u32Veloc_mms)
ToDo.
void vFCU_FCTL_BLENDER__Accel_UpdateFrom_Accel (Luint8 u8Channel, Luint32 u32Accel_mmss)
ToDo.
void vFCU_FCTL_BLENDER__Accel_UpdateFrom_LRF (Luint8 u8Channel, Luint32 u32Accel_mmss)
ToDo.
void vFCU_FCTL_BLENDER__Accel_UpdateFrom_Contrast (Luint8 u8Channel, Luint32 u32Accel_mmss)
ToDo.
void vFCU_FCTL_BLENDER__Displacement_UpdateFrom_Accel (Luint8 u8Channel, Luint32 u32Disp_mm)
ToDo.
void vFCU_FCTL_BLENDER__Displacement_UpdateFrom_LRF (Luint8 u8Channel, Luint32 u32Disp_mm)
ToDo.
void vFCU_FCTL_BLENDER__Displacement_UpdateFrom_Contrast (Luint8 u8Channel, Luint32 u32Disp_mm)
ToDo.
void vFCU_FCTL_TRACKDB__Init (void)
ToDo.
void vFCU_FCTL_TRACKDB__Process (void)
ToDo.
void vFCU_FCTL_TRACKDB__Set_CurrentDB (Luint32 u32Key, Luint32 u32TrackID)
ToDo.
DLL_DECLARATION Luint32 u32FCU_FCTL_TRACKDB__Get_CurrentDB (void)
ToDo.
DLL_DECLARATION Luint32 u32FCU_FCTL_TRACKDB__Get_TrackID (void)
ToDo.
DLL_DECLARATION Luint32 u32FCU_FCTL_TRACKDB__Get_TrackStartPosX_mm (void)
ToDo.
DLL_DECLARATION Luint32 u32FCU_FCTL_TRACKDB__Get_Current_TrackEndPosX_mm (void)
ToDo.
DLL_DECLARATION Luint32 u32FCU_FCTL_TRACKDB__Get_LRF_StartPosX_mm (void)
ToDo.
DLL_DECLARATION Luint32 u32FCU_FCTL_TRACKDB__Get_NumStripes (void)
ToDo.
DLL_DECLARATION Luint32 u32FCU_FCTL_TRACKDB__Get_StripeStartPosX_mm (Luint32 u32StripeIndex)
ToDo.
DLL_DECLARATION Luint32 u32FCU_FCTL_TRACKDB__Get_EnableLRF (void)
ToDo.
DLL_DECLARATION Luint32 u32FCU_FCTL_TRACKDB__Get_EnableAccels (void)
ToDo.
DLL_DECLARATION Luint32 u32FCU_FCTL_TRACKDB__Get_EnableContrast (void)
ToDo.
DLL_DECLARATION Luint32 u32FCU_FCTL_TRACKDB__Get_GetFooter (void)
ToDo.
void vFCU_FCTL_TRACKDB_MEM__Init (void)
ToDo.
void vFCU_FCTL_TRACKDB_MEM__Process (void)
ToDo.
void vFCU_FCTL_TRACKDB_MEM__UploadChunk (Luint32 u32TrackID, Luint32 u32ChunkIndex, Luint32 u32Length, Luint8 *pu8Buffer)
ToDo.
void vFCU_FCTL_TRACKDB_WIN32__Init (void)
void vFCU_FCTL_TRACKDB_WIN32__Process (void)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Clear_Array (void)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Get_Array (Luint8 *pu8ByteArray)
DLL_DECLARATION Luint16 u16FCU_FCTL_TRACKDB_WIN32__Get_StructureSize (void)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_Array (Luint8 *pu8ByteArray)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_Header (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_DataLength (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_TrackID (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_TrackStartXPos (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_TrackEndXPos (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_LRF_StartXPos (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_NumStripes (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_StripeStartX (Luint32 u32Index, Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_EnableAccels (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_EnableLRF (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_EnableContrast (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_HeaderSpare (Luint32 u32Index, Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_Footer (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_Profile_PusherFrontStartPos (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_Profile_PusherFrontEndPos (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_Profile_PodFrontTargetXPos (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_Profile_NumSetpoints (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_Profile_BrakeSetpointPosX (Luint32 u32Index, Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_Profile_BrakeSetpointVelocityX (Luint32 u32Index, Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_Profile_Spare (Luint32 u32Index, Luint32 u32Value)
DLL_DECLARATION Luint16 u16FCTL_TRAKDB_WIN32__ComputeCRC (void)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_CRC (Luint16 u16Value)
void vFCU_MAINSM_AUTO__Init (void)
Init the auto sequence system.
void vFCU_MAINSM_AUTO__Process (void)
Process the main state machine.
Luint8 u8FCU_MAINSM_AUTO__Is_Busy (void)
Are we busy in the auto sequence.
Luint8 u8FCU_MAINSM_AUTO__Is_Abort (void)
Do we need to do an immediate abort?
void vFCU_FCTL_ETH__Init (void)
Init Eth.
void vFCU_FCTL_ETH__Transmit (E_NET__PACKET_T ePacketType)
Process FCU Eth.
void vFCU_PODHEALTH__Init (void)
ToDo.
void vFCU_PODHEALTH__Process (void)
ToDo.
void vFCU_FLIGHTCTL_LASERORIENT__Init (void)
void vFCU_FLIGHTCTL_LASERORIENT__Process (void)
Lint16 s16FCU_FLIGHTCTL_LASERORIENT__Get_Roll (void)
Lint16 s16FCU_FLIGHTCTL_LASERORIENT__Get_Pitch (void)
Lint16 s16FCU_FLIGHTCTL_LASERORIENT__Get_Yaw (void)
Lfloat32 f32FCU_FLIGHTCTL_LASERORIENT__Get_Lateral (void)
Lint16 s16FCU_FLIGHTCTL_LASERORIENT__Get_TwistRoll (void)
Lint16 s16FCU_FLIGHTCTL_LASERORIENT__Get_TwistPitch (void)
void vFCU_FLIGHTCTL_CONTRASTNAV__Init (void)
Init contrast sensor navigation.
void vFCU_FLIGHTCTL_CONTRASTNAV__Process (void)
Process any navigation tasks.
Luint32 u32FCU_FLIGHTCTL_CONTRASTNAV__Get_Position_mm (void)
ToDo.
Luint8 u8FCU_FLIGHTCTL_CONTRASTNAV__Get_IsFault (void)
ToDo.
Luint32 u32FCU_FLIGHTCTL_CONTRASTNAV__Get_FaultFlags (void)
ToDo.
Lint16 s16FCU_FLIGHTCTL_BRAKES__Brake_Lookup (Luint32 u32Veloc_mms, Luint32 u32DragForce_n, Luint32 *pu32IBDistance_um)
void vFCU_NET__Init (void)
Inits the ethernet networking Sets our IP and MAC addresses for this hardware and starts up ethernet.
void vFCU_NET__Process (void)
Process the EMAC link.
void vFCU_NET_RX__Init (void)
ToDo.
Luint8 u8FCU_NET__Is_LinkUp (void)
Is the EMAC link up.
void vFCU_NET_RX__RxUDP (Luint8 *pu8Buffer, Luint16 u16Length, Luint16 u16DestPort)
Rx a normal UDP packet.
void vFCU_NET_RX__RxSafeUDP (Luint8 *pu8Payload, Luint16 u16PayloadLength, Luint16 ePacketType, Luint16 u16DestPort, Luint16 u16Fault)
Rx a SafetyUDP.
void vFCU_NET_TX__Init (void)
Init any network transmission stuff.
void vFCU_NET_TX__Process (void)
Process network transmission and do any transmission as required.
void vFCU_NET_TX__10MS_ISR (void)
To be called from the 10ms timer routine Sets a flag to allow this module to determine that 10ms has elapsed.
void vFCU_NET_TX__100MS_ISR (void)
100ms ISR
void vFCU_NET_SPACEX_TX__Init (void)
Init the spaceX timed network transmission process.
void vFCU_NET_SPACEX_TX__Process (void)
Do the transmission.
void vFCU_NET_SPACEX_TX__100MS_ISR (void)
To be called from the 100ms timer routine Sets a flag to allow this module to determine that 100ms has elapsed.
void vFCU_FAULTS__Init (void)
Init the fault processing system.
void vFCU_FAULTS__Process (void)
Process any faults.
Luint8 u8FCU_FAULTS__Get_IsFault (void)
return 1 if we have some sort of a fault, dig into the flags to see what happened
Luint32 u32FCU_FAULTS__Get_FaultFlags (void)
Return the top level fault flags.
void vFCU_FAULTS_ETH__Init (void)
void vFCU_FAULTS_ETH__Transmit (E_NET__PACKET_T ePacketType)
void vFCU_LASERCONT__Init (void)
Init the contrast laser system.
void vFCU_LASERCONT__Process (void)
Process the laser contrast system.
void vFCU_LASERCONT__Reset (Luint32 u32Key)
Reset the laser contrast system.
void vFCU_LASERCONT__ISR (E_FCU__LASER_CONT_INDEX_T eLaser, Luint32 u32Register)
Interrupt from the RM4 notification system.
void vFCU_LASERCONT_TL__Init (void)
Init the timing list.
void vFCU_LASERCONT_TL__Process (void)
Process the laser contrast list system.
DLL_DECLARATION void vFCU_LASERCONT_TL__ISR (E_FCU__LASER_CONT_INDEX_T eLaser, Luint32 u32Register)
Rising and falling edge Interrupts from the RM4 notification system.
Luint8 u8FCU_LASERCONT_TL__Get_NewRisingAvail (E_FCU__LASER_CONT_INDEX_T eLaser)
Return if a new rising edge has been detected.
void vFCU_LASERCONT_TL__Clear_NewRisingAvail (E_FCU__LASER_CONT_INDEX_T eLaser)
Clear out the new rising edge flag once its been taken.
Luint64 u64FCU_LASERCONT_TL__Get_TimeDelta (E_FCU__LASER_CONT_INDEX_T eLaser, Luint16 u16CurrentIndex)
Gets the difference btween the current edge and previous edge.
void vFCU_LASERCONT_VELOC__Init (void)
ToDo.
void vFCU_LASERCONT_VELOC__Process (void)
ToDo.
Luint32 u32FCU_LASERCONT_VELOC__Get_CurrentVeloc_mms (void)
ToDo.
Luint32 u32FCU_LASERCONT_VELOC__Compute (Luint32 u32Distance, Luint64 u64TimeDelta)
ToDo.
void vFCU_LASERCONT_TRKDB__Init (void)
Create the database.
void vFCU_LASERCONT_TRKDB__Process (void)
Process track database systems.
void vFCU_LASERCONT_TRKDB__Inc_Marker (E_FCU__LASER_CONT_INDEX_T eLaser)
Increment the next marker position based on a rising edge from the system.
void vFCU_LASERCONT_TRKDB__Compute (E_FCU__LASER_CONT_INDEX_T eLaser)
Compute the previous track distance Should really only do this on a new marker, but for constatnt CPU loading can do repeateldy.
Luint32 u32FCU_LASERCONT_TRKDB__Get_DistanceElapsed_mm (E_FCU__LASER_CONT_INDEX_T eLaser)
Return the distance that has current elpased.
Luint32 u32FCU_LASERCONT_TRKDB__Get_DistancePrevSeg_mm (E_FCU__LASER_CONT_INDEX_T eLaser)
Gets the distance in the previous 100ft, 30.48m segment.
void vFCU_LASERCONT_ETH__Transmit (E_NET__PACKET_T ePacketType)
Transmit a laser contrast eth packet.
void vFCU_LASERDIST__Init (void)
Init any of the laser distance items.
void vFCU_LASERDIST__Process (void)
Process the laser distance system.
Lint32 s32FCU_LASERDIST__Get_Distance_mm (void)
Return the current computed distance.
Lint32 s32FCU_LASERDIST__Get_Velocity_mms (void)
void vFCU_LASERDIST__100MS_ISR (void)
100ms Timer interrupt.
DLL_DECLARATION void vFCU_LASERDIST_WIN32__Set_DistanceRaw (Lint32 s32Value)
void vFCU_LASERDIST_ETH__Init (void)
Init Laser distance eth portion.
void vFCU_LASERDIST_ETH__Transmit (E_NET__PACKET_T ePacketType)
Transmith a laser distance eth packet.
void vFCU_LASERDIST_ETH__Enable_EmulationMode (Luint32 u32Key, Luint32 u32Enable)
Enable emulation mode.
void vFCU_LASERDIST_ETH__Emulation_Injection (Lint32 s32Value)
Via eth, inject some emulation value in.
void vFCU_LASERDIST_FILT__Init (void)
Init any filtering for laser distance.
void vFCU_LASERDIST_FILT__Process (void)
Process the laser distance filtering.
void vFCU_LASEROPTO__Init (void)
Init any variables.
void vFCU_LASEROPTO__Process (void)
Process any laser opto tasks.
void vFCU_LASEROPTO__Set_CalValue (Luint32 u32Key, Lfloat32 f32Offset)
ToDo.
Lfloat32 f32FCU_LASEROPTO__Get_Distance (E_FCU__LASER_OPTO__INDEX_T eLaser)
Get a lasers distance (The filtered value)
Luint8 u8FCU_LASEROPTO__Get_Error (E_FCU__LASER_OPTO__INDEX_T eLaser)
Get laser error state.
void vFCU_LASEROPTO__100MS_ISR (void)
100MS ISR point
DLL_DECLARATION void vFCU_LASEROPTO_WIN32__Set_DistanceRaw (Luint32 u32Index, Lfloat32 f32Value)
void vFCU_LASEROPTO_ETH__Transmit (E_NET__PACKET_T ePacketType)
Transmit the laser opto packet.
void vFCU_LASEROPTO_FILT__FilterPacket (E_FCU__LASER_OPTO__INDEX_T eLaser)
Apply the laser opto filter.
void vFCU_BRAKES__Init (void)
Init any brakes variables, etc.
void vFCU_BRAKES__Process (void)
Process any brakes tasks.
void vFCU_BRAKES__Begin_Init (Luint32 u32Key)
must start calibration from the ground station to put the brakes into a mode where they can be used.
void vFCU_BRAKES__Move_IBeam_Distance_mm (Lfloat32 f32Distance)
Move the brakes to a distance in microns from the I Beam.
void vFCU_BRAKES__100MS_ISR (void)
100ms timer input
void vFCU_BRAKES__10MS_ISR (void)
ToDo.
Lfloat32 f32FCU_BRAKES__Get_ScrewPos (E_FCU__BRAKE_INDEX_T eBrake)
Gets the computed screw position.
E_FCU__SWITCH_STATE_T eFCU_BRAKES__Get_SwtichState (E_FCU__BRAKE_INDEX_T eBrake, E_FCU__BRAKE_LIMSW_INDEX_T eSwitch)
Returns the brake switch state.
Luint16 u16FCU_BRAKES__Get_ADC_Raw (E_FCU__BRAKE_INDEX_T eBrake)
Get the RAW ADC values.
Lfloat32 f32FCU_BRAKES__Get_IBeam_mm (E_FCU__BRAKE_INDEX_T eBrake)
Get the distance between the brake and the I-Beam.
Lfloat32 f32FCU_BRAKES__Get_MLP_mm (E_FCU__BRAKE_INDEX_T eBrake)
Get the computed MLP measurement.
void vFCU_BRAKES_STEP__Init (void)
Init the stepper interface.
void vFCU_BRAKES_STEP__Process (void)
Process any brake commands.
void vFCU_BRAKES_STEP__Move (Lint32 s32Brake0Pos, Lint32 s32Brake1Pos)
Move the brakes as a pair to a position based on the lead screw distance.
Lint32 s32FCU_BRAKES__Get_CurrentPos (E_FCU__BRAKE_INDEX_T eBrake)
Returns the current position of the lead screw for the brakes.
void vFCU_BRAKES_STEP__UpdateValues (Luint32 u32Brake, Luint32 u32Type, Lint32 s32Value)
ToDo.
void vFCU_BRAKES_SW__Init (void)
Init the brake switches modules.
void vFCU_BRAKES_SW__Process (void)
Process the brake swtich tasks.
DLL_DECLARATION void vFCU_BRAKES_SW__Left_SwitchExtend_ISR (void)
Brake 0 (Left) Extended switch interrupt handler.
DLL_DECLARATION void vFCU_BRAKES_SW__Left_SwitchRetract_ISR (void)
Brake 0 (Left) Retract switch interrupt handler.
DLL_DECLARATION void vFCU_BRAKES_SW__Right_SwitchExtend_ISR (void)
Brake 1 (Right) Extended switch interrupt handler.
DLL_DECLARATION void vFCU_BRAKES_SW__Right_SwitchRetract_ISR (void)
Brake 1 (Right) Retract switch interrupt handler.
E_FCU__SWITCH_STATE_T eFCU_BRAKES_SW__Get_Switch (E_FCU__BRAKE_INDEX_T eBrake, E_FCU__BRAKE_LIMSW_INDEX_T eSwitch)
Gets the state of a brake limit swtich.
Luint8 u8FCU_BRAKES_SW__Get_FaultFlag (E_FCU__BRAKE_INDEX_T eBrake)
Gets the fault flag of a brake limit switches.
void vFCU_BRAKES_MLP__Init (void)
init the systems specifically to the MLP
void vFCU_BRAKES_MLP__Process (void)
resample the MLP sensors
void vFCU_BRAKES_MLP__ComputeCalibration_Zero (Luint32 u32Key, E_FCU__BRAKE_INDEX_T eBrake)
compute live calibration zero
void vFCU_BRAKES_MLP__ComputeCalibration_Span (Luint32 u32Key, E_FCU__BRAKE_INDEX_T eBrake)
Compute the calibration span value from the current brake pos.
void vFCU_BRAKES_ETH__Init (void)
Init the eth portion of the brakes system.
void vFCU_BRAKES_ETH__Transmit (E_NET__PACKET_T ePacketType)
Process any new eth packets (transmit)
void vFCU_BRAKES_ETH__MoveMotor_RAW (Luint32 u32Index, Lint32 s32Position)
Raw motor position movement.
void vFCU_BRAKES_ETH__MoveMotor_IBeam (Lfloat32 f32Value)
In development mode, move the brakes to an I-Beam distance.
void vFCU_BRAKES_ETH__Enable_DevMode (Luint32 u32Key0, Luint32 u32Key1)
Permit brake development/testing mode.
void vFCU_BRAKES_ETH__MLP_ZeroSpan (Luint32 u32Key0, Luint32 u32Brake, Luint32 u32Function)
Perform a MLP zero or span.
void vFCU_BRAKES_CAL__Init (void)
Init the calibration module.
void vFCU_BRAKES_CAL__Process (void)
ToDo.
void vFCU_BRAKES_CAL__BeginCal (Luint32 u32Key)
begin the calibration routine
Luint8 u8FCU_BRAKES_CAL__Is_Busy (void)
returns 1 if we are busy
void vFCU_BRAKES_WDT__Init (void)
Init the watchdog pin.
void vFCU_BRAKES_WDT__Pet_Start (void)
Start of the petting process.
void vFCU_BRAKES_WDT__Pet_End (void)
End the petting process.
void vFCU_ACCEL__Init (void)
Init the accel subsystem layer.
void vFCU_ACCEL__Process (void)
Process the accel's Call as fast as possible from the main loop.
Lint16 s16FCU_ACCEL__Get_LastSample (Luint8 u8Index, Luint8 u8Axis)
Get the last recorded sample from the Accels.
Lfloat32 f32FCU_ACCEL__Get_LastG (Luint8 u8Index, Luint8 u8Axis)
Get the last G-Force calculated value.
DLL_DECLARATION Lint32 s32FCU_ACCELL__Get_CurrentAccel_mmss (Luint8 u8Channel)
Return the current velocity as most recently computed in mm/sec.
DLL_DECLARATION Lint32 s32FCU_ACCELL__Get_CurrentVeloc_mms (Luint8 u8Channel)
Return the current velocity as most recently computed in mm/sec.
DLL_DECLARATION Lint32 s32FCU_ACCELL__Get_CurrentDisplacement_mm (Luint8 u8Channel)
Return the current displacement.
void vFCU_ACCEL_ETH__Init (void)
Init the eth portion.
void vFCU_ACCEL_ETH__Transmit (E_NET__PACKET_T ePacketType)
Transmit acceleration data over ethernet.
void vFCU_PUSHER__Init (void)
Init any variables for the pusher system.
void vFCU_PUSHER__Process (void)
Process any pusher interface tasks.
void vFCU_PUSHER__InterlockA_ISR (void)
Called from the N2HET notifications that an edge has occurred on Interlock A.
void vFCU_PUSHER__InterlockB_ISR (void)
Called from the N2HET notifications that an edge has occurred on Interlock B.
Luint8 u8FCU_PUSHER__Get_InterlockA (void)
Gets the current pin status of interlock A.
Luint8 u8FCU_PUSHER__Get_InterlockB (void)
Gets the current pin status of interlock B.
void vFCU_PUSHER__10MS_ISR (void)
10ms interrupt function, coming from FCU Core indicating that a new 10mS event has occurred.
Luint8 u8FCU_PUSHER__Get_Switch (Luint8 u8Switch)
Get a pusher switch state.
E_FCU_PUSHPIN_STATE_T eFCU_PUSHER__Get_PusherState (void)
Get the total pusher state.
void vFCU_PUSHER_ETH__Init (void)
Init any pusher ethernet issues.
void vFCU_PUSHER_ETH__Transmit (E_NET__PACKET_T ePacketType)
Transmit a pusher ethernet packet.
void vFCU_ASI__Init (void)
Init any variables.
void vFCU_ASI__10MS_ISR (void)
10MS ISR point
void vFCU_ASI__Process (void)
Process any ASI tasks.
void vFCU_ASI__MemSet (Luint8 *pu8Buffer, Luint8 u8Value, Luint32 u32Count)
void vFCU_ASI__Set_Throttle (Luint8 u8Index, Luint16 u16RPM)
void vFCU_ASI_CRC__AddCRC (Luint8 *pu8Data)
Add CRC to modbus command frame.
DLL_DECLARATION Luint16 u16FCU_ASI_CRC__ComputeCRC (Luint8 *pu8Data, Luint16 u16DataLen)
Compute the CRC.
Lint16 s16FCU_ASI_CRC__CheckCRC (Luint8 *pu8Data, Luint8 u8DataLen)
Check CRC from ASI device response.
void vFCU_ASI_MUX__Init (void)
Init the multiplexer.
void vFCU_ASI_MUX__Process (void)
Process any mux tasks.
void vFCU_ASI_MUX__SelectChannel (Luint8 u8ChannelIndex)
Selet the correct channel for the mux.
DLL_DECLARATION Luint8 u8FCU_ASI_MUX_WIN32__Get (void)
void vFCU_ASI_ETH__Init (void)
Init ASI ethernet interface.
void vFCU_ASI_ETH__Transmit (E_NET__PACKET_T ePacketType)
Do the ASI eth transmission.
void vFCU_THROTTLE__Init (void)
Init any variables.
void vFCU_THROTTLE__Process (void)
Process any Throttle tasks.
void vFCU_THROTTLE__100MS_ISR (void)
Timer function, returns after 100 milliseconds.
void vFCU_THROTTLE__Enable_Run (void)
Enable the throttle system into RUN mode.
void vFCU_THROTTLE__Set_Throttle (Luint8 u8EngineIndex, Luint16 u16RPM, E_THROTTLE_CTRL_T eRampType)
Application layer to enable throttles to be set.
void vFCU_THROTTLE_ETH__Init (void)
Init the throttle eth layer.
void vFCU_THROTTLE_ETH__Transmit (E_NET__PACKET_T ePacketType)
Send a throttle eth packet.
void vFCU_THROTTLE_ETH__Enable_DevMode (Luint32 u32Key0, Luint32 u32Key1)
safely switch on dev mode
void vFCU_THROTTLE_ETH__Set_Throttle (Luint8 u8EngineIndex, Luint16 u16RPM, E_THROTTLE_CTRL_T eRampType)
Manually set the throttle via the Ethernet.
void vFCU_GEOM__Init (void)
void vFCU_GEOM__Process (void)
void vFCU_GEOM_ETH__Init (void)
void vFCU_GEOM_ETH__Transmit (E_NET__PACKET_T ePacketType)
E_FCU__HOVERENGINES_STATES_T eFCU_FCTL_HOVERENGINES__Get_State (void)
void vFCU_FCTL_HOVERENGINES__ManualCommandsHandle (void)
void vFCU_FCTL_HOVERENGINES__Process (void)
void vFCU_FCTL_HOVERENGINES__Start (void)
void vFCU_FCTL_HOVERENGINES__Stop (void)
Luint16 u16FCU_ASI__ReadMotorRpm (Luint8 u8EngineIndex)
Lfloat32 f32FCU_ASI__ReadMotorCurrent (Luint8 u8EngineIndex)
Lfloat32 f32FCU_ASI__ReadControllerTemperature (Luint8 u8EngineIndex)
void vFCU_FCTL_DRIVEPOD__10MS_ISR (void)
void vFCU_FCTL_DRIVEPOD__SetPodStopCmd (void)
void vFCU_FCTL_AUX_PROP__Stop (void)
void vFCU_FCTL_AUX_PROP__Disable (void)
void vFCU_FCTL_COOLING__ManualCommandsHandle ()
void vFCU_FCTL_COOLING__Disable (void)
void vFCU_FCTL_COOLING__Enable (void)
void vFCU_COOLING__Set_Valve (Luint8 ValveNumber, Lfloat32 TimeOn, Lfloat32 TimeOff)
void vFCU_FCTL_LIFTMECH_Dir (E_FCU__LIFTMECH_ACTUATOR actuator, E_FCU__LIFTMECH_DIRECTION dir)
void vFCU_FCTL_LIFTMECH__SetDirAll (E_FCU__LIFTMECH_DIRECTION dir)
void vFCU_FCTL_LIFTMECH__SetSpeedAll (Luint32 u32speed)
void vFCU_FCTL_LIFTMECH__Extend (void)
void vFCU_FCTL_EDDYBRAKES_Speed (E_FCU__FCTL_EDDYBRAKES_ACTUATOR actuator, Luint32 u32speed)
void vFCU_FCTL_EDDYBRAKES__SetSpeedAll (Luint32 u32speed)
void vFCU_FCTL_EDDYBRAKES__SetDirAll (E_FCU__FCTL_EDDYBRAKES_DIRECTION dir)
void vFCU_FCTL_EDDY_BRAKES__ControlledEmergencyBrake ()
void vFCU_FCTL_EDDY_BRAKES__ApplyFullBrakes (void)
void vFCU_FCTL_EDDY_BRAKES__Release (void)
void vFCU_FCTL_EDDY_BRAKES__GainScheduleController (Luint32 u32speed)
void vFCU_FCTL_EDDY_BRAKES__GimbalSpeedController (void)
Luint8 u8FCU_FCTL_MAINSM__CheckIfUnlifted (void)
Luint8 u8FCU_FCTL_MAINSM__CheckIfLifted (void)
Luint8 u8FCU_FCTL_MAINSM__CheckIfHoveringStatically (void)
Luint8 u8FCU_FCTL_MAINSM__CheckIfReadyForPush (void)
Luint8 u8FCU_FCTL_MAINSM__CheckIfPushing (void)
Luint8 u8FCU_FCTL_MAINSM__CheckIfCoasting (void)
Luint8 u8FCU_FCTL_MAINSM__CheckIfBraking (void)
Luint8 u8FCU_FCTL_MAINSM__CheckIfControlledBraking (void)
void vFCU_FCTL_MAINSM__EnterPreRun_Phase ()
Luint32 u32FCU_FCTL_NAV__PodSpeed (void)
Luint8 u8FCU_FCTL_NAV__GetPodSpeedTooHigh (void)
Luint32 u32FCU_FCTL_NAV__GetFrontPos (void)
Luint32 u32FCU_FCTL_NAV__GetRearPos (void)
Luint32 u32FCU_FCTL_NAV__Get_Accel_mmss (void)
Luint32 u32FCU_FCTL_LASERORIENT__Get_Z_Pos ()
void vFCU_FLIGHTCTL_BRAKEPID__Init (void)
Detailed Description
Main header for the FCU.
Author
Lachlan Grogan
Copyright
rLoop Inc.
SafeTool FileID:
LCCM655R0.FILE.001
Macro Definition Documentation
#define C_MLP__MAX_AVERAGE_SIZE (8U)
Referenced by s16FCU_BRAKES_MLP__Filter_ADC_Value().
Function Documentation
E_FCU__HOVERENGINES_STATES_T eFCU_FCTL_HOVERENGINES__Get_State (void)
Lfloat32 f32FCU_FLIGHTCTL_LASERORIENT__Get_Lateral (void)
Lint16 s16FCU_FLIGHTCTL_BRAKES__Brake_Lookup (Luint32 u32Veloc_mms, Luint32 u32DragForce_n, Luint32 * pu32IBDistance_um)
Lint16 s16FCU_FLIGHTCTL_LASERORIENT__Get_Pitch (void)
Lint16 s16FCU_FLIGHTCTL_LASERORIENT__Get_Roll (void)
Lint16 s16FCU_FLIGHTCTL_LASERORIENT__Get_TwistPitch (void)
Lint16 s16FCU_FLIGHTCTL_LASERORIENT__Get_TwistRoll (void)
Lint16 s16FCU_FLIGHTCTL_LASERORIENT__Get_Yaw (void)
Lint32 s32FCU_FCTL_BLENDER__Get_Accel_mmss (void)
ToDo.
SafeTool Function MD5:
04CC27AC99940E871624E78E33672C83
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.003
References _strFCU::sBlender, sFCU, and _strFCU::sFlightControl.
Referenced by vFCU_NET_SPACEX_TX__Process().
Lint32 s32FCU_FCTL_BLENDER__Get_Displacement_mm (void)
ToDo.
SafeTool Function MD5:
EAA5F1CFCA6CE2E031FD233665A309D1
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.005
References _strFCU::sBlender, sFCU, and _strFCU::sFlightControl.
Referenced by vFCU_NET_SPACEX_TX__Process().
Lint32 s32FCU_FCTL_BLENDER__Get_Veloc_mms (void)
ToDo.
SafeTool Function MD5:
7323B04512CB94BB9AE1D2F14756DE75
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.004
References _strFCU::sBlender, sFCU, and _strFCU::sFlightControl.
Referenced by vFCU_NET_SPACEX_TX__Process().
Lint32 s32FCU_LASERDIST__Get_Velocity_mms (void)
DLL_DECLARATION Luint16 u16FCTL_TRAKDB_WIN32__ComputeCRC (void)
DLL_DECLARATION Luint16 u16FCU_FCTL_TRACKDB_WIN32__Get_StructureSize (void)
Luint32 u32FCU_FCTL_LASERORIENT__Get_Z_Pos ()
Luint32 u32FCU_FCTL_NAV__Get_Accel_mmss (void)
Luint32 u32FCU_FCTL_NAV__GetFrontPos (void)
Luint32 u32FCU_FCTL_NAV__GetRearPos (void)
Luint32 u32FCU_FCTL_NAV__PodSpeed (void)
Luint32 u32FCU_NET_RX__GetGsCommTimer (void)
DLL_DECLARATION Luint8 u8FCU_ASI_MUX_WIN32__Get (void)
Referenced by vFCU_ASI_MUX__SelectChannel().
Luint8 u8FCU_FCTL_MAINSM__CheckIfBraking (void)
Luint8 u8FCU_FCTL_MAINSM__CheckIfCoasting (void)
Luint8 u8FCU_FCTL_MAINSM__CheckIfControlledBraking (void)
Luint8 u8FCU_FCTL_MAINSM__CheckIfHoveringStatically (void)
Luint8 u8FCU_FCTL_MAINSM__CheckIfLifted (void)
Luint8 u8FCU_FCTL_MAINSM__CheckIfPushing (void)
Luint8 u8FCU_FCTL_MAINSM__CheckIfReadyForPush (void)
Luint8 u8FCU_FCTL_MAINSM__CheckIfUnlifted (void)
Luint8 u8FCU_FCTL_NAV__GetPodSpeedTooHigh (void)
void vFCU_COOLING__Set_Valve (Luint8 ValveNumber, Lfloat32 TimeOn, Lfloat32 TimeOff)
void vFCU_FAULTS_ETH__Init (void)
Referenced by vFCU_FAULTS__Init().
void vFCU_FAULTS_ETH__Transmit (E_NET__PACKET_T ePacketType)
Referenced by vFCU_NET_TX__Process().
void vFCU_FCTL_AUX_PROP__Disable (void)
void vFCU_FCTL_AUX_PROP__Stop (void)
void vFCU_FCTL_BLENDER__Accel_UpdateFrom_Accel (Luint8 u8Channel, Luint32 u32Accel_mmss)
ToDo.
Parameters
[in] u32Accel_mmss ## Desc ##
[in] u8Channel ## Desc ##
SafeTool Function MD5:
D0DDA1FC5BC49388A1AFD578BAEBF3F1
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.009
Referenced by vFCU_ACCEL__Process().
void vFCU_FCTL_BLENDER__Accel_UpdateFrom_Contrast (Luint8 u8Channel, Luint32 u32Accel_mmss)
ToDo.
Parameters
[in] u32Accel_mmss ## Desc ##
[in] u8Channel ## Desc ##
SafeTool Function MD5:
B584AA4C4391361450C62BFDE003C99A
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.011
void vFCU_FCTL_BLENDER__Accel_UpdateFrom_LRF (Luint8 u8Channel, Luint32 u32Accel_mmss)
ToDo.
Parameters
[in] u32Accel_mmss ## Desc ##
[in] u8Channel ## Desc ##
SafeTool Function MD5:
655026A0D75A99EE8E7EBE3FDBFEFEE3
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.010
void vFCU_FCTL_BLENDER__Displacement_UpdateFrom_Accel (Luint8 u8Channel, Luint32 u32Disp_mm)
ToDo.
Parameters
[in] u32Disp_mm ## Desc ##
[in] u8Channel ## Desc ##
SafeTool Function MD5:
129388323E9D8D7D2541218E26D05374
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.012
Referenced by vFCU_ACCEL__Process().
void vFCU_FCTL_BLENDER__Displacement_UpdateFrom_Contrast (Luint8 u8Channel, Luint32 u32Disp_mm)
ToDo.
Parameters
[in] u32Disp_mm ## Desc ##
[in] u8Channel ## Desc ##
SafeTool Function MD5:
EF8AE94096E136C3DE982D043F64045C
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.014
void vFCU_FCTL_BLENDER__Displacement_UpdateFrom_LRF (Luint8 u8Channel, Luint32 u32Disp_mm)
ToDo.
Parameters
[in] u32Disp_mm ## Desc ##
[in] u8Channel ## Desc ##
SafeTool Function MD5:
C1359FA82075785458C825BDCA155672
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.013
void vFCU_FCTL_BLENDER__Init (void)
ToDo.
SafeTool Function MD5:
6B43487B4AB4C611614B83DC0EEEBF49
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.001
References _strFCU::sBlender, sFCU, and _strFCU::sFlightControl.
void vFCU_FCTL_BLENDER__Process (void)
ToDo.
SafeTool Function MD5:
31AE84EF1368AB58CB3EB6C6317023B7
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.002
void vFCU_FCTL_BLENDER__Veloc_UpdateFrom_Accel (Luint8 u8Channel, Luint32 u32Veloc_mms)
ToDo.
Parameters
[in] u32Veloc_mms ## Desc ##
[in] u8Channel ## Desc ##
SafeTool Function MD5:
59777C3CBA664752E7B836BBF31863CA
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.006
Referenced by vFCU_ACCEL__Process().
void vFCU_FCTL_BLENDER__Veloc_UpdateFrom_Contrast (Luint8 u8Channel, Luint32 u32Veloc_mms)
ToDo.
Parameters
[in] u32Veloc_mms ## Desc ##
[in] u8Channel ## Desc ##
SafeTool Function MD5:
DA62E13F32AAB193E5867676F9F40554
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.008
void vFCU_FCTL_BLENDER__Veloc_UpdateFrom_LRF (Luint8 u8Channel, Luint32 u32Veloc_mms)
ToDo.
Parameters
[in] u32Veloc_mms ## Desc ##
[in] u8Channel ## Desc ##
SafeTool Function MD5:
1A965AB11BC3801E8CBD37BA6AF48288
SafeTool Function ID:
LCCM655R0.FILE.092.FUNC.007
void vFCU_FCTL_COOLING__Disable (void)
void vFCU_FCTL_COOLING__Enable (void)
void vFCU_FCTL_COOLING__ManualCommandsHandle ()
void vFCU_FCTL_DRIVEPOD__10MS_ISR (void)
Referenced by vFCU__RTI_10MS_ISR(), and vFCU_NET_RX__RxSafeUDP().
void vFCU_FCTL_DRIVEPOD__SetPodStopCmd (void)
Referenced by vFCU_NET_RX__RxSafeUDP().
void vFCU_FCTL_EDDY_BRAKES__ApplyFullBrakes (void)
void vFCU_FCTL_EDDY_BRAKES__ControlledEmergencyBrake ()
void vFCU_FCTL_EDDY_BRAKES__GainScheduleController (Luint32 u32speed)
void vFCU_FCTL_EDDY_BRAKES__GimbalSpeedController (void)
void vFCU_FCTL_EDDY_BRAKES__Release (void)
void vFCU_FCTL_EDDYBRAKES__SetDirAll (E_FCU__FCTL_EDDYBRAKES_DIRECTION dir)
void vFCU_FCTL_EDDYBRAKES__SetSpeedAll (Luint32 u32speed)
void vFCU_FCTL_EDDYBRAKES_Speed (E_FCU__FCTL_EDDYBRAKES_ACTUATOR actuator, Luint32 u32speed)
void vFCU_FCTL_HOVERENGINES__ManualCommandsHandle (void)
void vFCU_FCTL_HOVERENGINES__Process (void)
void vFCU_FCTL_HOVERENGINES__Start (void)
void vFCU_FCTL_HOVERENGINES__Stop (void)
void vFCU_FCTL_LIFTMECH__Extend (void)
Referenced by vFCU_NET_RX__RxSafeUDP().
void vFCU_FCTL_LIFTMECH__SetDirAll (E_FCU__LIFTMECH_DIRECTION dir)
void vFCU_FCTL_LIFTMECH__SetSpeedAll (Luint32 u32speed)
Referenced by vFCU_NET_RX__RxSafeUDP().
void vFCU_FCTL_LIFTMECH_Dir (E_FCU__LIFTMECH_ACTUATOR actuator, E_FCU__LIFTMECH_DIRECTION dir)
void vFCU_FCTL_MAINSM__100MS_ISR (void)
Referenced by vFCU__RTI_100MS_ISR().
void vFCU_FCTL_MAINSM__10MS_ISR (void)
Referenced by vFCU__RTI_10MS_ISR().
void vFCU_FCTL_MAINSM__EnterPreRun_Phase ()
Referenced by vFCU_NET_RX__RxSafeUDP().
void vFCU_FCTL_MAINSM__Init (void)
Referenced by vFCU__Process().
void vFCU_FCTL_MAINSM__MISERABLE_STOP_100MS_ISR (void)
void vFCU_FCTL_MAINSM__Process (void)
Referenced by vFCU__Process().
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Clear_Array (void)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Get_Array (Luint8 * pu8ByteArray)
void vFCU_FCTL_TRACKDB_WIN32__Init (void)
Referenced by vFCU_FCTL_TRACKDB__Init().
void vFCU_FCTL_TRACKDB_WIN32__Process (void)
Referenced by vFCU_FCTL_TRACKDB__Process().
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_Array (Luint8 * pu8ByteArray)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_CRC (Luint16 u16Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_DataLength (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_EnableAccels (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_EnableContrast (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_EnableLRF (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_Footer (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_Header (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_HeaderSpare (Luint32 u32Index, Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_LRF_StartXPos (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_NumStripes (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_Profile_BrakeSetpointPosX (Luint32 u32Index, Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_Profile_BrakeSetpointVelocityX (Luint32 u32Index, Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_Profile_NumSetpoints (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_Profile_PodFrontTargetXPos (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_Profile_PusherFrontEndPos (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_Profile_PusherFrontStartPos (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_Profile_Spare (Luint32 u32Index, Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_StripeStartX (Luint32 u32Index, Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_TrackEndXPos (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_TrackID (Luint32 u32Value)
DLL_DECLARATION void vFCU_FCTL_TRACKDB_WIN32__Set_TrackStartXPos (Luint32 u32Value)
void vFCU_FLIGHTCTL_BRAKEPID__Init (void)
void vFCU_FLIGHTCTL_LASERORIENT__Init (void)
void vFCU_FLIGHTCTL_LASERORIENT__Process (void)
void vFCU_GEOM__Init (void)
void vFCU_GEOM__Process (void)
void vFCU_GEOM_ETH__Init (void)
void vFCU_GEOM_ETH__Transmit (E_NET__PACKET_T ePacketType)
DLL_DECLARATION void vFCU_LASERDIST_WIN32__Set_DistanceRaw (Lint32 s32Value)
Referenced by vFCU_LASERDIST__100MS_ISR().
DLL_DECLARATION void vFCU_LASEROPTO_WIN32__Set_DistanceRaw (Luint32 u32Index, Lfloat32 f32Value)
Referenced by vFCU_LASEROPTO__100MS_ISR().
void vFCU_PODHEALTH__Init (void)
ToDo.
SafeTool Function MD5:
3DC546ADC8B0B45C310F55BF2317E1B5
SafeTool Function ID:
LCCM655R0.FILE.081.FUNC.001
References sFCU, _strFCU::sHealthFlags, and _strFCU::sPodHealth.
void vFCU_PODHEALTH__Process (void)
ToDo.
SafeTool Function MD5:
A7BAB7E3F5A7399BC1EC97869D225163
SafeTool Function ID:
LCCM655R0.FILE.081.FUNC.002
References C_FCU__NUM_HOVER_ENGINES, C_FCU__POD_HEALTH_INDEX__BATTERY_CELL_TEMP_RANGE, C_FCU__POD_HEALTH_INDEX__BATTERY_CELL_VOLTAGE_RANGE, C_FCU__POD_HEALTH_INDEX__BATTERY_PACK_TEMP_RANGE, C_FCU__POD_HEALTH_INDEX__BATTERY_VOLTAGE_RANGE, C_FCU__POD_HEALTH_INDEX__HE_CURRENT_RANGE, C_FCU__POD_HEALTH_INDEX__HE_RPM_RANGE, C_FCU__POD_HEALTH_INDEX__PV_PRESS_RANGE, C_FCU__POD_HEALTH_INDEX__PV_TEMP_RANGE, _strFCU::f32AverageTemp, _strFCU::f32HighestCellVoltage, _strFCU::f32HighestTemp, _strFCU::f32LowestCellVoltage, _strFCU::f32PackVoltage, _strFCU::f32PV_Press, _strFCU::f32PV_Temp, _strFCU::sASI, _strFCU::sBMS, sFCU, _strFCU::sHolding, and vFCU_PODHEALTH__Set_FlagInRage__F32().