(C Code, RLOOP, Flight Control Core): POD_HEALTH/fcu__pod_health.c File Reference
fcu__pod_health.c File Reference
#include "../fcu_core.h"
Macros
#define C_FCU__POD_HEALTH_INDEX__BATTERY_PACK_TEMP_RANGE 0x00000000
Quick and nasty here.
#define C_FCU__POD_HEALTH_INDEX__BATTERY_CELL_TEMP_RANGE 0x00000001
#define C_FCU__POD_HEALTH_INDEX__BATTERY_VOLTAGE_RANGE 0x00000002
#define C_FCU__POD_HEALTH_INDEX__BATTERY_CELL_VOLTAGE_RANGE 0x00000003
#define C_FCU__POD_HEALTH_INDEX__BATTERY_CURRENT_RANGE 0x00000004
#define C_FCU__POD_HEALTH_INDEX__HE_TEMP_RANGE 0x00000005
#define C_FCU__POD_HEALTH_INDEX__HE_CURRENT_RANGE 0x00000006
#define C_FCU__POD_HEALTH_INDEX__HE_VOLT_RANGE 0x00000007
#define C_FCU__POD_HEALTH_INDEX__HE_RPM_RANGE 0x00000008
#define C_FCU__POD_HEALTH_INDEX__PV_PRESS_RANGE 0x00000009
#define C_FCU__POD_HEALTH_INDEX__PV_TEMP_RANGE 0x0000000A
Functions
Luint32 u32FCU_PODHEALTH__Check_InRange_F32 (Lfloat32 f32Value, Lfloat32 f32Min, Lfloat32 f32Max)
void vFCU_PODHEALTH__Set_FlagInRage__F32 (Lfloat32 f32Value, Lfloat32 f32Min, Lfloat32 f32Max, Luint32 u32FlagIndex)
void vFCU_PODHEALTH__Init (void)
void vFCU_PODHEALTH__Process (void)
Variables
struct _strFCU sFCU
Macro Definition Documentation
#define C_FCU__POD_HEALTH_INDEX__BATTERY_CELL_TEMP_RANGE 0x00000001
Referenced by vFCU_PODHEALTH__Process().
#define C_FCU__POD_HEALTH_INDEX__BATTERY_CELL_VOLTAGE_RANGE 0x00000003
Referenced by vFCU_PODHEALTH__Process().
#define C_FCU__POD_HEALTH_INDEX__BATTERY_CURRENT_RANGE 0x00000004
#define C_FCU__POD_HEALTH_INDEX__BATTERY_PACK_TEMP_RANGE 0x00000000
Quick and nasty here.
Referenced by vFCU_PODHEALTH__Process().
#define C_FCU__POD_HEALTH_INDEX__BATTERY_VOLTAGE_RANGE 0x00000002
Referenced by vFCU_PODHEALTH__Process().
#define C_FCU__POD_HEALTH_INDEX__HE_CURRENT_RANGE 0x00000006
Referenced by vFCU_PODHEALTH__Process().
#define C_FCU__POD_HEALTH_INDEX__HE_RPM_RANGE 0x00000008
Referenced by vFCU_PODHEALTH__Process().
#define C_FCU__POD_HEALTH_INDEX__HE_TEMP_RANGE 0x00000005
#define C_FCU__POD_HEALTH_INDEX__HE_VOLT_RANGE 0x00000007
#define C_FCU__POD_HEALTH_INDEX__PV_PRESS_RANGE 0x00000009
Referenced by vFCU_PODHEALTH__Process().
#define C_FCU__POD_HEALTH_INDEX__PV_TEMP_RANGE 0x0000000A
Referenced by vFCU_PODHEALTH__Process().
Function Documentation
Luint32 u32FCU_PODHEALTH__Check_InRange_F32 (Lfloat32 f32Value, Lfloat32 f32Min, Lfloat32 f32Max)
Referenced by vFCU_PODHEALTH__Set_FlagInRage__F32().
void vFCU_PODHEALTH__Init (void)
References sFCU, _strFCU::sHealthFlags, and _strFCU::sPodHealth.
void vFCU_PODHEALTH__Process (void)
References C_FCU__NUM_HOVER_ENGINES, C_FCU__POD_HEALTH_INDEX__BATTERY_CELL_TEMP_RANGE, C_FCU__POD_HEALTH_INDEX__BATTERY_CELL_VOLTAGE_RANGE, C_FCU__POD_HEALTH_INDEX__BATTERY_PACK_TEMP_RANGE, C_FCU__POD_HEALTH_INDEX__BATTERY_VOLTAGE_RANGE, C_FCU__POD_HEALTH_INDEX__HE_CURRENT_RANGE, C_FCU__POD_HEALTH_INDEX__HE_RPM_RANGE, C_FCU__POD_HEALTH_INDEX__PV_PRESS_RANGE, C_FCU__POD_HEALTH_INDEX__PV_TEMP_RANGE, _strFCU::f32AverageTemp, _strFCU::f32HighestCellVoltage, _strFCU::f32HighestTemp, _strFCU::f32LowestCellVoltage, _strFCU::f32PackVoltage, _strFCU::f32PV_Press, _strFCU::f32PV_Temp, _strFCU::sASI, _strFCU::sBMS, sFCU, _strFCU::sHolding, and vFCU_PODHEALTH__Set_FlagInRage__F32().
void vFCU_PODHEALTH__Set_FlagInRage__F32 (Lfloat32 f32Value, Lfloat32 f32Min, Lfloat32 f32Max, Luint32 u32FlagIndex)
References sFCU, _strFCU::sHealthFlags, _strFCU::sPodHealth, and u32FCU_PODHEALTH__Check_InRange_F32().
Referenced by vFCU_PODHEALTH__Process().