(C Code, RLOOP, Flight Control Core): FCU__CORE
FCU__CORE
RLOOP » FCU
Functions
void vFCU__Init (void)
Init the FCU.
void vFCU__Process (void)
Process any FCU tasks.
void vFCU__RTI_100MS_ISR (void)
100ms timer
void vFCU__RTI_10MS_ISR (void)
10ms timer
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
void vFCU__Init (void)
Init the FCU.
Call this first thing.
SafeTool Function MD5:
2B87B49581828868F2B8726833317ADB
SafeTool Function ID:
LCCM655R0.FILE.000.FUNC.001
References _strFCU::eInitStates, INIT_STATE__RESET, sFCU, _strFCU::u32Guard1, _strFCU::u32Guard2, vFCU_BRAKES__Init(), and vFCU_FAULTS__Init().
void vFCU__Process (void)
Process any FCU tasks.
SafeTool Function MD5:
BC230E2F20B042C85F76C1DBCF00A966
SafeTool Function ID:
LCCM655R0.FILE.000.FUNC.002
References BRAKE_SW__EXTEND, BRAKE_SW__RETRACT, C_LCCM655__CORE__FAULT_INDEX__00, C_LCCM655__CORE__FAULT_INDEX__01, _strFCU::eInitStates, FCU_BRAKE__LEFT, FCU_BRAKE__RIGHT, INIT_STATE__INIT_COMMS, INIT_STATE__INIT_IO, INIT_STATE__INIT_SPI_UARTS, INIT_STATE__LOWER_SYSTEMS, INIT_STATE__RESET, INIT_STATE__RUN, INIT_STATE__START_TIMERS, LASER_CONT__AFT, LASER_CONT__FWD, LASER_CONT__MID, _strFCU::sBrakes, _strFCU::sFaults, sFCU, _strFCU::sLimits, _strFCU::sPusher, _strFCU::sSwitches, _strFCU::sTopLevel, _strFCU::u32Guard1, _strFCU::u32Guard2, vFCU_MAINSM__Init(), vFCU_MAINSM__Process(), vFCU_NET__Init(), and vFCU_NET__Process().
void vFCU__RTI_100MS_ISR (void)
100ms timer
SafeTool Function MD5:
29FA796863975C61E514D3ED94ED79CA
SafeTool Function ID:
LCCM655R0.FILE.000.FUNC.003
References vFCU_LASERDIST__100MS_ISR(), vFCU_LASEROPTO__100MS_ISR(), and vFCU_PICOMMS__100MS_ISR().
void vFCU__RTI_10MS_ISR (void)
10ms timer
SafeTool Function MD5:
132920CE083F2C05C9100CBC35DA7876
SafeTool Function ID:
LCCM655R0.FILE.000.FUNC.004
References vFCU_NET_TX__10MS_ISR(), and vFCU_PUSHER__10MS_ISR().
Variable Documentation
struct _strFCU sFCU
Referenced by u32FCU_FAULTS__Get_FaultFlags(), u8FCU_FAULTS__Get_IsFault(), u8FCU_MAINSM_AUTO__Is_Busy(), vFCU__Init(), vFCU__Process(), vFCU_BRAKES_SW__Left_SwitchExtend_ISR(), vFCU_BRAKES_SW__Left_SwitchRetract_ISR(), vFCU_BRAKES_SW__Right_SwitchExtend_ISR(), vFCU_BRAKES_SW__Right_SwitchRetract_ISR(), vFCU_FAULTS__Init(), vFCU_MAINSM__Init(), vFCU_MAINSM__Process(), vFCU_MAINSM_AUTO__Init(), vFCU_MAINSM_AUTO__Process(), vFCU_PUSHER__10MS_ISR(), vFCU_PUSHER__InterlockA_ISR(), vFCU_PUSHER__InterlockB_ISR(), and vRM4_N2HET_DYNAMIC__Notification().