(C Code, RLOOP, Flight Control Core): FCU__BRAKES__MLP
FCU__BRAKES__MLP
RLOOP » FCU
Functions
static void vFCU_BRAKES_MLP__Sample_ADC (void)
Call this function to sample the ADC channel associated with the brake.
static Lint16 s16FCU_BRAKES_MLP__Check_ADC_Limits (E_FCU__BRAKE_INDEX_T eBrake)
Check the limits of the ADC data.
static void vFCU_BRAKES_MLP__Apply_Zero (E_FCU__BRAKE_INDEX_T eBrake)
Apply the zero value to the ADC sample.
static void vFCU_BRAKES_MLP__Apply_Span (E_FCU__BRAKE_INDEX_T eBrake)
Apply the system span value.
static Lint16 s16FCU_BRAKES_MLP__Filter_ADC_Value (E_FCU__BRAKE_INDEX_T eBrake)
Filtering the MLP sensor value.
void vFCU_BRAKES_MLP__Init (void)
init the systems specifically to the MLP
void vFCU_BRAKES_MLP__Process (void)
resample the MLP sensors
void vFCU_BRAKES_MLP__ComputeCalibration_Zero (Luint32 u32Key, E_FCU__BRAKE_INDEX_T eBrake)
compute live calibration zero
void vFCU_BRAKES_MLP__ComputeCalibration_Span (Luint32 u32Key, E_FCU__BRAKE_INDEX_T eBrake)
Compute the calibration span value from the current brake pos.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
Lint16 s16FCU_BRAKES_MLP__Check_ADC_Limits (E_FCU__BRAKE_INDEX_T eBrake) static
Check the limits of the ADC data.
Parameters
[in] eBrake The brake index
Returns
-1 = Error, limits out of range
0 = success
SafeTool Function MD5:
BE00FC48D260311DF0578D1DA2E875DB
SafeTool Function ID:
LCCM655R0.FILE.024.FUNC.004
References _strFCU::sBrakes, sFCU, and _strFCU::sMLP.
Referenced by vFCU_BRAKES_MLP__Process().
Lint16 s16FCU_BRAKES_MLP__Filter_ADC_Value (E_FCU__BRAKE_INDEX_T eBrake) static
Filtering the MLP sensor value.
Parameters
[in] eBrake The brake index
Returns
Filtered Value
SafeTool Function MD5:
25BE0217D808FC312C8067B6D646C03B
SafeTool Function ID:
LCCM655R0.FILE.024.FUNC.005
References C_MLP__MAX_AVERAGE_SIZE, _strFCU::sBrakes, sFCU, and _strFCU::sMLP.
Referenced by vFCU_BRAKES_MLP__Process().
void vFCU_BRAKES_MLP__Apply_Span (E_FCU__BRAKE_INDEX_T eBrake) static
Apply the system span value.
Example:
Brake_Pos = (ADCValue - Zero) * Span
Parameters
[in] eBrake The brake index
SafeTool Function MD5:
30F2A16DDC839D704891DC145917EA38
SafeTool Function ID:
LCCM655R0.FILE.024.FUNC.006
References C_FCU__NUM_BRAKES, _strFCU::sBrakes, sFCU, and _strFCU::sMLP.
Referenced by vFCU_BRAKES_MLP__Process().
void vFCU_BRAKES_MLP__Apply_Zero (E_FCU__BRAKE_INDEX_T eBrake) static
Apply the zero value to the ADC sample.
Parameters
[in] eBrake The brake index
SafeTool Function MD5:
91B14636179F6DEA07A2A6B2DD7B2C37
SafeTool Function ID:
LCCM655R0.FILE.024.FUNC.007
References C_FCU__NUM_BRAKES, _strFCU::sBrakes, sFCU, and _strFCU::sMLP.
Referenced by vFCU_BRAKES_MLP__Process().
void vFCU_BRAKES_MLP__ComputeCalibration_Span (Luint32 u32Key, E_FCU__BRAKE_INDEX_T eBrake)
Compute the calibration span value from the current brake pos.
Parameters
[in] eBrake The brake channel
[in] u32Key 0x33334444U
SafeTool Function MD5:
4A737F5C67F4BFA7B927F989EF02DB3D
SafeTool Function ID:
LCCM655R0.FILE.024.FUNC.009
References C_LOCALDEF__LCCM655__EEPROM_OFFSET__BRAKE0_SPAN, C_LOCALDEF__LCCM655__EEPROM_OFFSET__BRAKE1_SPAN, C_LOCALDEF__LCCM655__EEPROM_OFFSET__BRAKES_CRC, C_LOCALDEF__LCCM655__EEPROM_OFFSET__BRAKES_HEADER, FCU_BRAKE__LEFT, FCU_BRAKE__RIGHT, _strFCU::sBrakes, sFCU, and _strFCU::sMLP.
Referenced by vFCU_BRAKES_ETH__MLP_ZeroSpan().
void vFCU_BRAKES_MLP__ComputeCalibration_Zero (Luint32 u32Key, E_FCU__BRAKE_INDEX_T eBrake)
compute live calibration zero
Parameters
[in] eBrake The brake channel.
[in] u32Key 0x11112222U
SafeTool Function MD5:
D0AA7E9E1B254C1D2169CA3C6513C15D
SafeTool Function ID:
LCCM655R0.FILE.024.FUNC.008
References C_LOCALDEF__LCCM655__EEPROM_OFFSET__BRAKE0_ZERO, C_LOCALDEF__LCCM655__EEPROM_OFFSET__BRAKE1_SPAN, C_LOCALDEF__LCCM655__EEPROM_OFFSET__BRAKE1_ZERO, C_LOCALDEF__LCCM655__EEPROM_OFFSET__BRAKES_CRC, C_LOCALDEF__LCCM655__EEPROM_OFFSET__BRAKES_HEADER, FCU_BRAKE__LEFT, FCU_BRAKE__RIGHT, _strFCU::sBrakes, sFCU, and _strFCU::sMLP.
Referenced by vFCU_BRAKES_ETH__MLP_ZeroSpan().
void vFCU_BRAKES_MLP__Init (void)
init the systems specifically to the MLP
SafeTool Function MD5:
EF7193F48D28AB9115D5EE38BFB0C3F7
SafeTool Function ID:
LCCM655R0.FILE.024.FUNC.001
References C_FCU__NUM_BRAKES, C_LCCM655__BRAKES__FAULT_INDEX__00, C_LCCM655__BRAKES__FAULT_INDEX__03, C_LOCALDEF__LCCM655__EEPROM_OFFSET__BRAKE0_SPAN, C_LOCALDEF__LCCM655__EEPROM_OFFSET__BRAKE0_ZERO, C_LOCALDEF__LCCM655__EEPROM_OFFSET__BRAKE1_SPAN, C_LOCALDEF__LCCM655__EEPROM_OFFSET__BRAKE1_ZERO, C_LOCALDEF__LCCM655__EEPROM_OFFSET__BRAKES_CRC, C_LOCALDEF__LCCM655__EEPROM_OFFSET__BRAKES_HEADER, _strFCU::sBrakes, _strFCU::sBrakesGlobal, _strFCU::sFaultFlags, sFCU, and _strFCU::sMLP.
Referenced by vFCU_BRAKES__Init().
void vFCU_BRAKES_MLP__Process (void)
resample the MLP sensors
SafeTool Function MD5:
BD5E7979D0E472FD0EA53691718E9C7F
SafeTool Function ID:
LCCM655R0.FILE.024.FUNC.002
References C_FCU__NUM_BRAKES, s16FCU_BRAKES_MLP__Check_ADC_Limits(), s16FCU_BRAKES_MLP__Filter_ADC_Value(), _strFCU::sBrakes, sFCU, _strFCU::sMLP, vFCU_BRAKES_MLP__Apply_Span(), vFCU_BRAKES_MLP__Apply_Zero(), and vFCU_BRAKES_MLP__Sample_ADC().
Referenced by vFCU_BRAKES__Process().
void vFCU_BRAKES_MLP__Sample_ADC (void) static
Call this function to sample the ADC channel associated with the brake.
Parameters
[in] eBrake The brake index
SafeTool Function MD5:
22651109FEC8DB182929455B0B0FE06D
SafeTool Function ID:
LCCM655R0.FILE.024.FUNC.003
References C_FCU__NUM_BRAKES, FCU_BRAKE__LEFT, FCU_BRAKE__RIGHT, _strFCU::sBrakes, sFCU, and _strFCU::sMLP.
Referenced by vFCU_BRAKES_MLP__Process().
Variable Documentation
struct _strFCU sFCU
Referenced by s16FCU_BRAKES_MLP__Check_ADC_Limits(), s16FCU_BRAKES_MLP__Filter_ADC_Value(), vFCU_BRAKES_MLP__Apply_Span(), vFCU_BRAKES_MLP__Apply_Zero(), vFCU_BRAKES_MLP__ComputeCalibration_Span(), vFCU_BRAKES_MLP__ComputeCalibration_Zero(), vFCU_BRAKES_MLP__Init(), vFCU_BRAKES_MLP__Process(), and vFCU_BRAKES_MLP__Sample_ADC().