(C Code, RLOOP, Flight Control Core): FCU__FLIGHT_CTL__TRACK_DATABASE
FCU__FLIGHT_CTL__TRACK_DATABASE
RLOOP » FCU
Functions
Luint32 u32FCU_FCTL_TRACKDB__Get_Current_TrackEndPosX_mm (void)
void vFCU_FCTL_TRACKDB__Init (void)
void vFCU_FCTL_TRACKDB__Process (void)
void vFCU_FCTL_TRACKDB__Set_CurrentDB (Luint32 u32Key, Luint32 u32TrackID)
Luint32 u32FCU_FCTL_TRACKDB__Get_CurrentDB (void)
Luint32 u32FCU_FCTL_TRACKDB__Get_TrackID (void)
Luint32 u32FCU_FCTL_TRACKDB__Get_TrackStartPosX_mm (void)
Luint32 u32FCU_FCTL_TRACKDB__Get_LRF_StartPosX_mm (void)
Luint32 u32FCU_FCTL_TRACKDB__Get_NumStripes (void)
Luint32 u32FCU_FCTL_TRACKDB__Get_StripeStartPosX_mm (Luint32 u32StripeIndex)
Luint32 u32FCU_FCTL_TRACKDB__Get_EnableLRF (void)
Luint32 u32FCU_FCTL_TRACKDB__Get_EnableAccels (void)
Luint32 u32FCU_FCTL_TRACKDB__Get_EnableContrast (void)
Luint32 u32FCU_FCTL_TRACKDB__Get_GetFooter (void)
Variables
struct _strFCU sFCU
struct _strTrackDatabase sTrackDB
Detailed Description
Function Documentation
Luint32 u32FCU_FCTL_TRACKDB__Get_Current_TrackEndPosX_mm (void)
References _strTrackDatabase::sDB, sTrackDB, and _strTrackDatabase::u8TrackEndXPosition_mm.
Referenced by vFCU_FCTL_TRACKDB__Process().
Luint32 u32FCU_FCTL_TRACKDB__Get_CurrentDB (void)
References sFCU, _strFCU::sFlightControl, and _strFCU::sTrackDB.
Luint32 u32FCU_FCTL_TRACKDB__Get_EnableAccels (void)
References _strTrackDatabase::sDB, sTrackDB, and _strTrackDatabase::u8EnableAccels.
Luint32 u32FCU_FCTL_TRACKDB__Get_EnableContrast (void)
References _strTrackDatabase::sDB, sTrackDB, and _strTrackDatabase::u8EnableContrast.
Luint32 u32FCU_FCTL_TRACKDB__Get_EnableLRF (void)
References _strTrackDatabase::sDB, sTrackDB, and _strTrackDatabase::u8EnableLRF.
Luint32 u32FCU_FCTL_TRACKDB__Get_GetFooter (void)
References _strTrackDatabase::sDB, sTrackDB, and _strTrackDatabase::u8Footer.
Luint32 u32FCU_FCTL_TRACKDB__Get_LRF_StartPosX_mm (void)
References _strTrackDatabase::sDB, sTrackDB, and _strTrackDatabase::u8LRFAreaBeginningXPosition_mm.
Luint32 u32FCU_FCTL_TRACKDB__Get_NumStripes (void)
References _strTrackDatabase::sDB, sTrackDB, and _strTrackDatabase::u8NumberOfStripes.
Luint32 u32FCU_FCTL_TRACKDB__Get_StripeStartPosX_mm (Luint32 u32StripeIndex)
References _strTrackDatabase::sDB, sTrackDB, and _strTrackDatabase::u8StripeBeginningXPosition_mm.
Luint32 u32FCU_FCTL_TRACKDB__Get_TrackID (void)
References _strTrackDatabase::sDB, sTrackDB, and _strTrackDatabase::u8TrackID.
Luint32 u32FCU_FCTL_TRACKDB__Get_TrackStartPosX_mm (void)
References _strTrackDatabase::sDB, sTrackDB, and _strTrackDatabase::u8TrackBeginningXPosition_mm.
void vFCU_FCTL_TRACKDB__Init (void)
References C_FCTL_TRACKDB__MAX_MEM_DATABASES, C_LOCALDEF__LCCM655__FCTL_TRACKDB___CURRENT_DB, sFCU, _strFCU::sFlightControl, _strFCU::sTrackDB, vFCU_FCTL_TRACKDB_MEM__Init(), and vFCU_FCTL_TRACKDB_WIN32__Init().
Referenced by vFCU_FCTL__Init().
void vFCU_FCTL_TRACKDB__Process (void)
References u32FCU_FCTL_TRACKDB__Get_Current_TrackEndPosX_mm(), vFCU_FCTL_TRACKDB_MEM__Process(), and vFCU_FCTL_TRACKDB_WIN32__Process().
Referenced by vFCU_FCTL__Process().
void vFCU_FCTL_TRACKDB__Set_CurrentDB (Luint32 u32Key, Luint32 u32TrackID)
References C_FCTL_TRACKDB__MAX_MEM_DATABASES, C_LOCALDEF__LCCM655__FCTL_TRACKDB___CURRENT_DB, sFCU, _strFCU::sFlightControl, _strFCU::sTrackDB, and vFCU_FCTL_TRACKDB_MEM__Init().
Referenced by vFCU_NET_RX__RxSafeUDP().
Variable Documentation
struct _strFCU sFCU
Referenced by u32FCU_FCTL_TRACKDB__Get_CurrentDB(), vFCU_FCTL_TRACKDB__Init(), and vFCU_FCTL_TRACKDB__Set_CurrentDB().
struct _strTrackDatabase sTrackDB
Referenced by u32FCU_FCTL_TRACKDB__Get_Current_TrackEndPosX_mm(), u32FCU_FCTL_TRACKDB__Get_EnableAccels(), u32FCU_FCTL_TRACKDB__Get_EnableContrast(), u32FCU_FCTL_TRACKDB__Get_EnableLRF(), u32FCU_FCTL_TRACKDB__Get_GetFooter(), u32FCU_FCTL_TRACKDB__Get_LRF_StartPosX_mm(), u32FCU_FCTL_TRACKDB__Get_NumStripes(), u32FCU_FCTL_TRACKDB__Get_StripeStartPosX_mm(), u32FCU_FCTL_TRACKDB__Get_TrackID(), u32FCU_FCTL_TRACKDB__Get_TrackStartPosX_mm(), vFCU_FCLT_TRACKDB_MEM__Save_TrackDB(), and vFCU_FCTL_TRACKDB_MEM__UploadChunk().