(C Code, RLOOP, Flight Control Core): FCU__CORE_NET
FCU__CORE_NET
RLOOP » FCU
Functions
void vFCU_NET__Init (void)
Inits the ethernet networking Sets our IP and MAC addresses for this hardware and starts up ethernet.
void vFCU_NET__Process (void)
Process the EMAC link.
Luint8 u8FCU_NET__Is_LinkUp (void)
Is the EMAC link up.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
Luint8 u8FCU_NET__Is_LinkUp (void)
Is the EMAC link up.
Returns
0 = link down
1 = link up.
SafeTool Function MD5:
7992142A1C21AA07872803587554E851
SafeTool Function ID:
LCCM655R0.FILE.016.FUNC.003
Referenced by vFCU_NET__Process().
void vFCU_NET__Init (void)
Inits the ethernet networking Sets our IP and MAC addresses for this hardware and starts up ethernet.
SafeTool Function MD5:
13A035336C96D72DBAFD7A5F41412935
SafeTool Function ID:
LCCM655R0.FILE.016.FUNC.001
References _strFCU::sEthernet, sFCU, _strFCU::u8IPAddx, _strFCU::u8MACAddx, and vFCU_NET_TX__Init().
Referenced by vFCU__Process().
void vFCU_NET__Process (void)
Process the EMAC link.
Note
This should be called from main program loop after power is stable This also calls the EMAC link state machine which processes the EMAC link and handles bringing the EMAC on line.
SafeTool Function MD5:
7B2AF3925C7CFC0E6ABD265C1AAC7F6B
SafeTool Function ID:
LCCM655R0.FILE.016.FUNC.002
References u8FCU_NET__Is_LinkUp(), and vFCU_NET_TX__Process().
Referenced by vFCU__Process().
Variable Documentation
struct _strFCU sFCU
Referenced by vFCU_NET__Init().