(C Code, RLOOP, Flight Control Core): FCU_CORE__FAULTS
FCU_CORE__FAULTS
RLOOP » FCU
Functions
void vFCU_FAULTS__Init (void)
Init the fault processing system.
void vFCU_FAULTS__Process (void)
Process any faults.
Luint8 u8FCU_FAULTS__Get_IsFault (void)
return 1 if we have some sort of a fault, dig into the flags to see what happened
Luint32 u32FCU_FAULTS__Get_FaultFlags (void)
Return the top level fault flags.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
Luint32 u32FCU_FAULTS__Get_FaultFlags (void)
Return the top level fault flags.
SafeTool Function MD5:
C6B448B0CA30A17A3C405BB7FEE3C440
SafeTool Function ID:
LCCM655R0.FILE.022.FUNC.004
References _strFCU::sFaults, sFCU, and _strFCU::sTopLevel.
Referenced by vFCU_FAULTS_ETH__Transmit(), and vFCU_FCTL_ETH__Transmit().
Luint8 u8FCU_FAULTS__Get_IsFault (void)
return 1 if we have some sort of a fault, dig into the flags to see what happened
SafeTool Function MD5:
646024F18B39EE4EB1A7E44000184D1B
SafeTool Function ID:
LCCM655R0.FILE.022.FUNC.003
References _strFCU::sFaults, sFCU, and _strFCU::sTopLevel.
void vFCU_FAULTS__Init (void)
Init the fault processing system.
SafeTool Function MD5:
5CF11A5E121D877F3D2EE0529551224C
SafeTool Function ID:
LCCM655R0.FILE.022.FUNC.001
References _strFCU::sFaults, sFCU, _strFCU::sTopLevel, and vFCU_FAULTS_ETH__Init().
Referenced by vFCU__Init().
void vFCU_FAULTS__Process (void)
Process any faults.
SafeTool Function MD5:
BF2420870949587CB67641D07D3954DC
SafeTool Function ID:
LCCM655R0.FILE.022.FUNC.002
References C_LCCM655__FAULTS__FAULT_INDEX__00, C_LCCM655__FAULTS__FAULT_INDEX__01, C_LCCM655__FAULTS__FAULT_INDEX__02, C_LCCM655__FAULTS__FAULT_INDEX__03, C_LCCM655__FAULTS__FAULT_INDEX__04, _strFCU::sAccel, _strFCU::sASI, _strFCU::sBrakesGlobal, _strFCU::sFaultFlags, _strFCU::sFaults, sFCU, and _strFCU::sTopLevel.
Referenced by vFCU__Process().
Variable Documentation
struct _strFCU sFCU
Referenced by u32FCU_FAULTS__Get_FaultFlags(), u8FCU_FAULTS__Get_IsFault(), vFCU_FAULTS__Init(), and vFCU_FAULTS__Process().