(C Code, RLOOP, Flight Control Core): FCU__ASI_RS485
FCU__ASI_RS485
RLOOP » FCU
Functions
void vFCU_ASI__BuildCmdFrame (struct _strASICmd *pCmd)
Build Modbus read/write register command frame to issue to ASI controller.
Lint16 s16FCU_ASI__ProcessError (struct _strASICmd *pCmd)
Process error from ASI device.
void vFCU_ASI__SetErr (struct _strASICmd *pCmd)
Set variable with appropriate error from ASI device.
void vFCU_ASI__MemCopy (Luint8 *pu8Dest, const Luint8 *cpu8Source, Luint32 u32Length)
Lint16 s16FCU_ASI__SendCommand (void)
Send Read/Write register command to ASI controller.
Lint16 s16FCU_ASI__ProcessReply (void)
Process reply from ASI device.
void vFCU_ASI__Init (void)
Init any variables.
void vFCU_ASI__Process (void)
Process any ASI tasks.
void vFCU_ASI__Set_Throttle (Luint8 u8Index, Luint16 u16RPM)
void vFCU_ASI__10MS_ISR (void)
10MS ISR point
void vFCU_ASI__MemSet (Luint8 *pu8Buffer, Luint8 u8Value, Luint32 u32Count)
Luint16 u16FCU_ASI__ReadMotorRpm (Luint8 u8EngineIndex)
Luint16 u16FCU_ASI__ReadMotorVoltage (Luint8 u8EngineIndex)
Lfloat32 f32FCU_ASI__ReadMotorCurrent (Luint8 u8EngineIndex)
Lfloat32 f32FCU_ASI__ReadControllerTemperature (Luint8 u8EngineIndex)
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
Lfloat32 f32FCU_ASI__ReadControllerTemperature (Luint8 u8EngineIndex)
References _strFCU::sASI, sFCU, and _strFCU::sHolding.
Lfloat32 f32FCU_ASI__ReadMotorCurrent (Luint8 u8EngineIndex)
References _strFCU::sASI, sFCU, and _strFCU::sHolding.
Lint16 s16FCU_ASI__ProcessError (struct _strASICmd * pCmd)
Process error from ASI device.
Parameters
[in] pCmd Command being processed
References E_ERROR_RESPONSE, _strASICmd::eErrorType, _strFCU::sASI, _strFCU::sCurrentCommand, sFCU, and vFCU_ASI__SetErr().
Referenced by vFCU_ASI__Process().
Lint16 s16FCU_ASI__ProcessReply (void)
Process reply from ASI device.
Parameters
[in] pCmd Command being processed in command queue
Returns
-1 = crc error 0 = success
References C_FCU_ASI__CONT_TEMP, C_FCU_ASI__FAULTS, C_FCU_ASI__MOTOR_CURRENT, C_FCU_ASI__MOTOR_RPM, C_FCU_ASI__TEMPERATURE, E_CRC_CHECK_FAILED, E_ERROR_RESPONSE, E_INT16, E_INT8, E_SLAVE_MISMATCH, E_UINT16, E_UINT8, _strASICmd::eDestVarType, _strASICmd::eErrorType, _strASICmd::eObjectType, _strASICmd::framedCmd, _strASICmd::s16, s16FCU_ASI_CRC__CheckCRC(), _strASICmd::s8, _strFCU::sASI, _strFCU::sCurrentCommand, sFCU, _strFCU::sHolding, _strASICmd::u16, _strASICmd::u8, _strASICmd::u8Response, _strFCU::u8ScanIndex, and _strASICmd::unDestVar.
Referenced by vFCU_ASI__Process().
Lint16 s16FCU_ASI__SendCommand (void)
Send Read/Write register command to ASI controller.
Parameters
[in] pCmd Command structure
Returns
-1 = error 0 = success
References _strFCU::sASI, _strFCU::sCurrentCommand, sFCU, _strFCU::u8NewCommandToSend, and vFCU_ASI__BuildCmdFrame().
Referenced by s16FCU_ASI_CTRL__GetFaults(), s16FCU_ASI_CTRL__Init(), s16FCU_ASI_CTRL__ReadControllerTemperature(), s16FCU_ASI_CTRL__ReadMotorCurrent(), s16FCU_ASI_CTRL__ReadMotorRpm(), s16FCU_ASI_CTRL__SaveSettings(), and vFCU_ASI__Process().
Luint16 u16FCU_ASI__ReadMotorRpm (Luint8 u8EngineIndex)
References _strFCU::sASI, sFCU, and _strFCU::sHolding.
Luint16 u16FCU_ASI__ReadMotorVoltage (Luint8 u8EngineIndex)
void vFCU_ASI__10MS_ISR (void)
10MS ISR point
References _strFCU::sASI, sFCU, _strFCU::u32ASI_replywait_Counter, _strFCU::u32ASI_turnaround_Counter, and _strFCU::u810MS_Timer.
Referenced by vFCU__RTI_10MS_ISR().
void vFCU_ASI__BuildCmdFrame (struct _strASICmd * pCmd)
Build Modbus read/write register command frame to issue to ASI controller.
Parameters
[in] pCmd Command structure
References _strASICmd::eFunctionCode, _strASICmd::eObjectType, _strASICmd::framedCmd, _strASICmd::u16ParamValue, _strASICmd::u8SlaveAddress, and vFCU_ASI_CRC__AddCRC().
Referenced by s16FCU_ASI__SendCommand().
void vFCU_ASI__Init (void)
Init any variables.
References ASI_STATE__IDLE, C_FCU__NUM_HOVER_ENGINES, C_FCU_ASI__CONT_TEMP, C_FCU_ASI__FAULTS, C_FCU_ASI__MOTOR_CURRENT, C_FCU_ASI__MOTOR_RPM, _strFCU::eCommandList, _strFCU::eMainState, _strFCU::sASI, _strFCU::sFaultFlags, sFCU, _strFCU::sHolding, _strFCU::u32ASI_replywait_Counter, _strFCU::u32ASI_turnaround_Counter, _strFCU::u32Guard1, _strFCU::u32Guard2, _strFCU::u810MS_Timer, _strFCU::u8CommandListIndex, _strFCU::u8NewCommandToSend, _strFCU::u8RxCount, _strFCU::u8ScanIndex, _strFCU::u8SerialNetworkCommand, _strFCU::u8ThrottleCommand, vFCU_ASI_ETH__Init(), and vFCU_ASI_MUX__Init().
void vFCU_ASI__MemCopy (Luint8 * pu8Dest, const Luint8 * cpu8Source, Luint32 u32Length)
void vFCU_ASI__MemSet (Luint8 * pu8Buffer, Luint8 u8Value, Luint32 u32Count)
Referenced by s16FCU_ASI_CTRL__GetFaults(), s16FCU_ASI_CTRL__Init(), s16FCU_ASI_CTRL__ReadControllerTemperature(), s16FCU_ASI_CTRL__ReadMotorCurrent(), s16FCU_ASI_CTRL__ReadMotorRpm(), and s16FCU_ASI_CTRL__SaveSettings().
void vFCU_ASI__Process (void)
Process any ASI tasks.
References ASI_COMM_STATE__IDLE, ASI_COMM_STATE__PROCESS_ERROR, ASI_COMM_STATE__PROCESS_REPLY, ASI_COMM_STATE__WAIT_REPLY, ASI_COMM_STATE__WAIT_TURNAROUND_DELAY, ASI_STATE__CONFIG_MUX, ASI_STATE__IDLE, ASI_STATE__INC_SCAN_INDEX, ASI_STATE__ISSUE_COMMAND, ASI_STATE__ISSUE_SERIAL_TRHOTTLE, ASI_STATE__WAIT_COMMAND_COMPLETE, C_ASI__DEFAULT_SLAVE_ADDX, C_ASI__MAX_REPLYWAIT_DELAY, C_ASI__MAX_TURNAROUND_DELAY, C_ASI__RW_FRAME_SIZE, C_FCU__ASI_COMMAND_LIST_MAX, C_FCU__NUM_HOVER_ENGINES, C_FCU__SC16_ASI_INDEX, C_FCU_ASI__REMOTE_THROTTLE_VOLTAGE, C_FCU_ASI__THROT_SENSOR_SOURCE, E_REPLY_TIMEOUT_EXPIRED, E_UINT16, _strFCU::eCommandList, _strASICmd::eDestVarType, _strASICmd::eErrorType, _strASICmd::eFunctionCode, _strFCU::eMainState, _strFCU::eModBusState, _strASICmd::eObjectType, _strASICmd::framedCmd, FUNCTION_CODE__READ_HOLDING_REGS, FUNCTION_CODE__WRITE_SINGLE_REG, s16FCU_ASI__ProcessError(), s16FCU_ASI__ProcessReply(), s16FCU_ASI__SendCommand(), _strFCU::sASI, _strFCU::sCurrentCommand, sFCU, _strASICmd::u16ParamValue, _strFCU::u16Throttle, _strFCU::u32ASI_replywait_Counter, _strFCU::u32ASI_turnaround_Counter, _strFCU::u32Guard1, _strFCU::u32Guard2, _strFCU::u810MS_Timer, _strFCU::u8CommandListIndex, _strFCU::u8NewCommandToSend, _strASICmd::u8Response, _strFCU::u8RxCount, _strFCU::u8ScanIndex, _strFCU::u8SerialNetworkCommand, _strASICmd::u8SlaveAddress, _strFCU::u8ThrottleCommand, vFCU_ASI_MUX__Process(), and vFCU_ASI_MUX__SelectChannel().
void vFCU_ASI__Set_Throttle (Luint8 u8Index, Luint16 u16RPM)
References C_FCU__NUM_HOVER_ENGINES, _strFCU::sASI, sFCU, _strFCU::u16RPM, _strFCU::u16Throttle, and _strFCU::u8ThrottleCommand.
Referenced by vFCU_NET_RX__RxSafeUDP().
void vFCU_ASI__SetErr (struct _strASICmd * pCmd)
Set variable with appropriate error from ASI device.
Parameters
[in] pCmd Command being processed
References E_INT16, E_INT8, E_UINT16, E_UINT8, and _strASICmd::eDestVarType.
Referenced by s16FCU_ASI__ProcessError().
Variable Documentation
struct _strFCU sFCU
Referenced by f32FCU_ASI__ReadControllerTemperature(), f32FCU_ASI__ReadMotorCurrent(), s16FCU_ASI__ProcessError(), s16FCU_ASI__ProcessReply(), s16FCU_ASI__SendCommand(), u16FCU_ASI__ReadMotorRpm(), vFCU_ASI__10MS_ISR(), vFCU_ASI__Init(), vFCU_ASI__Process(), and vFCU_ASI__Set_Throttle().