(C Code, RLOOP, Flight Control Core): FCU__MAIN_SM
FCU__MAIN_SM
RLOOP » FCU
Functions
void vFCU_MAINSM__Init (void)
Init any variables as is needed by the main state machine.
void vFCU_MAINSM__Process (void)
Process the main state machine.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
void vFCU_MAINSM__Init (void)
Init any variables as is needed by the main state machine.
SafeTool Function MD5:
5224534176289DBD9FF1B39936308C7E
SafeTool Function ID:
LCCM655R0.FILE.020.FUNC.001
References _strFCU::eRunState, RUN_STATE__RESET, sFCU, and vFCU_MAINSM_AUTO__Init().
Referenced by vFCU__Process().
void vFCU_MAINSM__Process (void)
Process the main state machine.
SafeTool Function MD5:
2C23D1564E9845C3BED5E00B06C0BBB3
SafeTool Function ID:
LCCM655R0.FILE.020.FUNC.002
References _strFCU::eRunState, RUN_STATE__AUTO_SEQUENCE_MODE, RUN_STATE__FLIGHT_ABORT, RUN_STATE__FLIGHT_MODE, RUN_STATE__INIT_SYSTEMS, RUN_STATE__RESET, RUN_STATE__STARTUP_MODE, sFCU, u8FCU_MAINSM_AUTO__Is_Abort(), u8FCU_MAINSM_AUTO__Is_Busy(), vAMC7812__Init(), vAMC7812__Process(), vFCU_ACCEL__Init(), vFCU_ACCEL__Process(), vFCU_ASI__Init(), vFCU_BRAKES__Init(), vFCU_BRAKES__Process(), vFCU_FLIGHTCTL__Init(), vFCU_FLIGHTCTL__Process(), vFCU_LASERCONT__Init(), vFCU_LASERCONT__Process(), vFCU_LASERDIST__Process(), vFCU_LASEROPTO__Init(), vFCU_LASEROPTO__Process(), vFCU_MAINSM_AUTO__Process(), vFCU_PICOMMS__Init(), vFCU_PICOMMS__Process(), vFCU_PUSHER__Init(), vFCU_THROTTLE__Init(), and vFCU_THROTTLE__Process().
Referenced by vFCU__Process().
Variable Documentation
struct _strFCU sFCU
Referenced by vFCU_MAINSM__Init(), and vFCU_MAINSM__Process().