(C Code, RLOOP, Flight Control Core): FCU__THROTTLES
FCU__THROTTLES
RLOOP » FCU
Macros
#define u16THROTTLE_TOL 0U
#define ALL_HES 0U
#define RAMP_DONE 99U
#define THROTTLE_RAMP_TIMER_INTERVAL 100.0F
#define HOVER_ENGINE_MINIMUM_SPEED 0U
#define HOVER_ENGINE_MAXIMUM_SPEED 50000U
#define HOVER_ENGINE_STATIC_HOVER_SPEED 20000U
#define HOVER_ENGINE_STANDBY_SPEED 20000U
#define FCU_MODE STOPPED_LIFTED
#define GS_COMMAND_MODE SET_HEX_SPEED
#define GS_COMMAND_UNITS 0U
#define GS_THROTTLE_COMMAND 15000U
#define GS_ENGINE_NUMBER 6U
#define GS_THROTTLE_RAMP_DURATION 3000U
Functions
Lfloat32 f32FCU_THROTTLE__RPM_To_Volts (Luint16 u16RPM)
Compute volts to DAC based on RPM for a single engine only.
Luint16 u16FCU_THROTTLE__Compute_RPM_StepUp (Luint16 u16RPM)
Compute the step to the next RPM increment.
Luint16 u16FCU_THROTTLE__Compute_RPM_StepDown (Luint16 u16RPM)
Compute the step to the next RPM Decrement.
void vFCU_THROTTLE__Init (void)
Init any variables.
void vFCU_THROTTLE__Process (void)
Process any Throttle tasks.
void vFCU_THROTTLE__Enable_Run (void)
Enable the throttle system into RUN mode.
void vFCU_THROTTLE__Set_Throttle (Luint8 u8EngineIndex, Luint16 u16RPM, E_THROTTLE_CTRL_T eRampType)
Application layer to enable throttles to be set.
void vFCU_THROTTLE__100MS_ISR (void)
Timer function, returns after 100 milliseconds.
Variables
struct _strFCU sFCU
static Luint16 u16LastThrottleSetPoint
static Luint16 u16LastThrottleCommandValue
static Luint16 u16InitThrottleCommand
Detailed Description
Macro Definition Documentation
#define ALL_HES 0U
#define FCU_MODE STOPPED_LIFTED
#define GS_COMMAND_MODE SET_HEX_SPEED
#define GS_COMMAND_UNITS 0U
#define GS_ENGINE_NUMBER 6U
#define GS_THROTTLE_COMMAND 15000U
#define GS_THROTTLE_RAMP_DURATION 3000U
#define HOVER_ENGINE_MAXIMUM_SPEED 50000U
#define HOVER_ENGINE_MINIMUM_SPEED 0U
#define HOVER_ENGINE_STANDBY_SPEED 20000U
#define HOVER_ENGINE_STATIC_HOVER_SPEED 20000U
#define RAMP_DONE 99U
#define THROTTLE_RAMP_TIMER_INTERVAL 100.0F
#define u16THROTTLE_TOL 0U
Function Documentation
Lfloat32 f32FCU_THROTTLE__RPM_To_Volts (Luint16 u16RPM)
Compute volts to DAC based on RPM for a single engine only.
Parameters
[in] u16RPM Desired RPM
Returns
DAC Volts
SafeTool Function MD5:
104E1A0088369417D74427715DC40585
SafeTool Function ID:
LCCM655R0.FILE.006.FUNC.007
Referenced by vFCU_THROTTLE__Process().
Luint16 u16FCU_THROTTLE__Compute_RPM_StepDown (Luint16 u16RPM)
Compute the step to the next RPM Decrement.
Parameters
[in] u16RPM Current RPM
SafeTool Function MD5:
BABD3902310B5EA38BC850114E39C924
SafeTool Function ID:
LCCM655R0.FILE.006.FUNC.004
References _strFCU::u16RPM.
Referenced by vFCU_THROTTLE__Process().
Luint16 u16FCU_THROTTLE__Compute_RPM_StepUp (Luint16 u16RPM)
Compute the step to the next RPM increment.
Parameters
[in] u16RPM RPM
SafeTool Function MD5:
55FA32EE2926B39A2247666B10DA85EC
SafeTool Function ID:
LCCM655R0.FILE.006.FUNC.003
References _strFCU::u16RPM.
Referenced by vFCU_THROTTLE__Process().
void vFCU_THROTTLE__100MS_ISR (void)
Timer function, returns after 100 milliseconds.
SafeTool Function MD5:
BD90C8C26FABACCFB1ECCA3E4C0460FD
SafeTool Function ID:
LCCM655R0.FILE.006.FUNC.008
References C_FCU__NUM_HOVER_ENGINES, sFCU, _strFCU::sThrottle, and _strFCU::strThrottleInterfaceData::u8100ms_Timer.
Referenced by vFCU__RTI_100MS_ISR().
void vFCU_THROTTLE__Enable_Run (void)
Enable the throttle system into RUN mode.
This is needed To be done via flight control to prevent unintended HE startup
SafeTool Function MD5:
49C9345E807752C9DD7876859EDD2F73
SafeTool Function ID:
LCCM655R0.FILE.006.FUNC.005
References _strFCU::strThrottleInterfaceData::eState, sFCU, _strFCU::sThrottle, THROTTLE_STATE__IDLE, and THROTTLE_STATE__RUN.
Referenced by vFCU_THROTTLE_ETH__Enable_DevMode().
void vFCU_THROTTLE__Init (void)
Init any variables.
SafeTool Function MD5:
3D83D3CBE94E074C73347E324EE431FB
SafeTool Function ID:
LCCM655R0.FILE.006.FUNC.001
References C_FCU__NUM_HOVER_ENGINES, C_LCCM655__THROTTLES__FAULT_INDEX__03, _strFCU::strThrottleInterfaceData::eRequestedMode, _strFCU::strThrottleInterfaceData::eState, _strFCU::strThrottleInterfaceData::sDevMode, _strFCU::strThrottleInterfaceData::sFaultFlags, sFCU, _strFCU::sThrottle, THROTTLE_STATE__IDLE, THROTTLE_TYPE__STEP, _strFCU::strThrottleInterfaceData::u16CurrentRPM, _strFCU::strThrottleInterfaceData::u16RequestedRPM, _strFCU::strThrottleInterfaceData::u32SecurityKey, _strFCU::strThrottleInterfaceData::u8100ms_Timer, _strFCU::strThrottleInterfaceData::u8Enabled, and _strFCU::strThrottleInterfaceData::u8RunIndex.
void vFCU_THROTTLE__Process (void)
Process any Throttle tasks.
SafeTool Function MD5:
519F9282320179D5EA89621405D7BACA
SafeTool Function ID:
LCCM655R0.FILE.006.FUNC.002
References C_FCU__NUM_HOVER_ENGINES, C_LCCM655__THROTTLES__FAULT_INDEX__00, C_LCCM655__THROTTLES__FAULT_INDEX__01, C_LCCM655__THROTTLES__FAULT_INDEX__03, _strFCU::strThrottleInterfaceData::eRequestedMode, _strFCU::strThrottleInterfaceData::eState, f32FCU_THROTTLE__RPM_To_Volts(), _strFCU::strThrottleInterfaceData::sFaultFlags, sFCU, _strFCU::sThrottle, THROTTLE_STATE__ERROR, THROTTLE_STATE__IDLE, THROTTLE_STATE__INC_INDEX, THROTTLE_STATE__RAMP_DOWN, THROTTLE_STATE__RAMP_UP, THROTTLE_STATE__RUN, THROTTLE_STATE__STEP, THROTTLE_TYPE__RAMP, _strFCU::strThrottleInterfaceData::u16CurrentRPM, u16FCU_THROTTLE__Compute_RPM_StepDown(), u16FCU_THROTTLE__Compute_RPM_StepUp(), _strFCU::strThrottleInterfaceData::u16RequestedRPM, _strFCU::strThrottleInterfaceData::u8100ms_Timer, and _strFCU::strThrottleInterfaceData::u8RunIndex.
void vFCU_THROTTLE__Set_Throttle (Luint8 u8EngineIndex, Luint16 u16RPM, E_THROTTLE_CTRL_T eRampType)
Application layer to enable throttles to be set.
Parameters
[in] eRampType The type of throttle ramp
[in] u16RPM Required RPM
[in] u8EngineIndex HE Index, 8 = all HE's
SafeTool Function MD5:
67F20EE1B480E01FC261370E4AD8190C
SafeTool Function ID:
LCCM655R0.FILE.006.FUNC.006
References C_FCU__NUM_HOVER_ENGINES, C_LCCM655__THROTTLES__FAULT_INDEX__00, C_LCCM655__THROTTLES__FAULT_INDEX__02, _strFCU::strThrottleInterfaceData::eRequestedMode, _strFCU::strThrottleInterfaceData::sFaultFlags, sFCU, _strFCU::sThrottle, _strFCU::strThrottleInterfaceData::u16RequestedRPM, and _strFCU::u16RPM.
Variable Documentation
struct _strFCU sFCU
Referenced by vFCU_THROTTLE__100MS_ISR(), vFCU_THROTTLE__Enable_Run(), vFCU_THROTTLE__Init(), vFCU_THROTTLE__Process(), and vFCU_THROTTLE__Set_Throttle().
Luint16 u16InitThrottleCommand static
Luint16 u16LastThrottleCommandValue static
Luint16 u16LastThrottleSetPoint static