(C Code, RLOOP, Flight Control Core): FCU__LASER_CONTRAST__VELOC
FCU__LASER_CONTRAST__VELOC
RLOOP » FCU
Functions
void vFCU_LASERCONT_VELOC__Init (void)
ToDo.
void vFCU_LASERCONT_VELOC__Process (void)
ToDo.
Luint32 u32FCU_LASERCONT_VELOC__Get_CurrentVeloc_mms (void)
ToDo.
Luint32 u32FCU_LASERCONT_VELOC__Compute (Luint32 u32Distance, Luint64 u64TimeDelta)
ToDo.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
Luint32 u32FCU_LASERCONT_VELOC__Compute (Luint32 u32Distance, Luint64 u64TimeDelta)
ToDo.
Parameters
[in] u64TimeDelta ## Desc ##
[in] u32Distance ## Desc ##
SafeTool Function MD5:
ECF00834753BE38E259AC1C2C5F9310A
SafeTool Function ID:
LCCM655R0.FILE.040.FUNC.004
Referenced by vFCU_LASERCONT__Process().
Luint32 u32FCU_LASERCONT_VELOC__Get_CurrentVeloc_mms (void)
ToDo.
SafeTool Function MD5:
50C036B4AF050E1193B9F57E0B5390FD
SafeTool Function ID:
LCCM655R0.FILE.040.FUNC.003
void vFCU_LASERCONT_VELOC__Init (void)
ToDo.
SafeTool Function MD5:
2248CD3745D2D329825B4B41A5F777E9
SafeTool Function ID:
LCCM655R0.FILE.040.FUNC.001
Referenced by vFCU_LASERCONT__Init().
void vFCU_LASERCONT_VELOC__Process (void)
ToDo.
SafeTool Function MD5:
A630BB7D8CB5F66027917286E6DE41BC
SafeTool Function ID:
LCCM655R0.FILE.040.FUNC.002
Referenced by vFCU_LASERCONT__Process().
Variable Documentation
struct _strFCU sFCU