(C Code, RLOOP, Flight Control Core): FCU__CORE_NET_SPACEX
FCU__CORE_NET_SPACEX
RLOOP » FCU
Functions
void vFCU_NET_SPACEX_TX__Init (void)
Init the spaceX timed network transmission process.
void vFCU_NET_SPACEX_TX__Process (void)
Do the transmission.
void vFCU_NET_SPACEX_TX__100MS_ISR (void)
To be called from the 100ms timer routine Sets a flag to allow this module to determine that 100ms has elapsed.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
void vFCU_NET_SPACEX_TX__100MS_ISR (void)
To be called from the 100ms timer routine Sets a flag to allow this module to determine that 100ms has elapsed.
SafeTool Function MD5:
D01FDA076F08496417237931291DDA01
SafeTool Function ID:
LCCM655R0.FILE.039.FUNC.003
References sFCU, _strFCU::sSpaceX, and _strFCU::u8100MS_Flag.
Referenced by vFCU_NET_TX__100MS_ISR().
void vFCU_NET_SPACEX_TX__Init (void)
Init the spaceX timed network transmission process.
SafeTool Function MD5:
E26089EA43BEAD5D8FCFEC4B17029C33
SafeTool Function ID:
LCCM655R0.FILE.039.FUNC.001
References sFCU, _strFCU::sSpaceX, _strFCU::u32TestCounter, and _strFCU::u8100MS_Flag.
Referenced by vFCU_NET_TX__Init().
void vFCU_NET_SPACEX_TX__Process (void)
Do the transmission.
Note
Teams shall send a binary telemetry frame for SpaceX monitoring of the status of their pod. The frame shall be sent via UDP to IP 192.168.0.1, port 3000 at no greater than 10Hz, and must obey the following format, where the type UINTx is an unsigned integer of x bits in length, and INTx is a twos-complement signed integer of x bits in length. The first 5 fields are required; the latter five fields are optional. If a field is unused, its value must be left as 0.
Name Type Description team_id UINT8 Identifier for the team, assigned by SpaceX. Required. status UINT8 Pod status, indicating current pod health and pushing state, as defined below. Required. acceleration INT32 Acceleration in centimeters per second squared. Required. position INT32 Velocity in centimeters per second. Required. velocity INT32 Position in centimeters. Required. battery_voltage INT32 Battery voltage in millivolts. battery_current INT32 Battery current in milliamps. battery_temperature INT32 Battery temperature in tenths of a degree Celsius. pod_temperature INT32 Pod temperature in tenths of a degree Celsius. stripe_count UINT32 Count of optical navigation stripes detected in the tube.
SafeTool Function MD5:
1E6784E2B771F1C758670E96D9F5F364
SafeTool Function ID:
LCCM655R0.FILE.039.FUNC.002
References sFCU, _strFCU::sSpaceX, _strFCU::u32TestCounter, and _strFCU::u8100MS_Flag.
Referenced by vFCU_NET_TX__Process().
Variable Documentation
struct _strFCU sFCU
Referenced by vFCU_NET_SPACEX_TX__100MS_ISR(), vFCU_NET_SPACEX_TX__Init(), and vFCU_NET_SPACEX_TX__Process().