(C Code, RLOOP, Flight Control Core): FCU__PUSHER
FCU__PUSHER
RLOOP » FCU
Functions
void vFCU_PUSHER__Init (void)
Init any variables for the pusher system.
void vFCU_PUSHER__Process (void)
Process any pusher interface tasks.
void vFCU_PUSHER__InterlockA_ISR (void)
Called from the N2HET notifications that an edge has occurred on Interlock A.
void vFCU_PUSHER__InterlockB_ISR (void)
Called from the N2HET notifications that an edge has occurred on Interlock B.
Luint8 u8FCU_PUSHER__Get_Switch (Luint8 u8Switch)
Get a pusher switch state.
E_FCU_PUSHPIN_STATE_T eFCU_PUSHER__Get_PusherState (void)
Get the total pusher state.
Luint8 u8FCU_PUSHER__Get_InterlockA (void)
Gets the current pin status of interlock A.
Luint8 u8FCU_PUSHER__Get_InterlockB (void)
Gets the current pin status of interlock B.
void vFCU_PUSHER__10MS_ISR (void)
10ms interrupt function, coming from FCU Core indicating that a new 10mS event has occurred.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
E_FCU_PUSHPIN_STATE_T eFCU_PUSHER__Get_PusherState (void)
Get the total pusher state.
SafeTool Function MD5:
F51AB362F5D574A9114B7915B833FF9F
SafeTool Function ID:
LCCM655R0.FILE.012.FUNC.006
References _strFCU::ePusher_Status, sFCU, and _strFCU::sPusher.
Luint8 u8FCU_PUSHER__Get_InterlockA (void)
Gets the current pin status of interlock A.
Returns
0 = switch open
1 = switch closed.
SafeTool Function MD5:
7F1CA2D799181F98607158FCA01EC0C1
SafeTool Function ID:
LCCM655R0.FILE.012.FUNC.007
Referenced by vFCU_PUSHER__Process().
Luint8 u8FCU_PUSHER__Get_InterlockB (void)
Gets the current pin status of interlock B.
Returns
0 = switch open
1 = switch closed.
SafeTool Function MD5:
C22C0173C59CD8B44B0F76CB010AF54D
SafeTool Function ID:
LCCM655R0.FILE.012.FUNC.008
Referenced by vFCU_PUSHER__Process().
Luint8 u8FCU_PUSHER__Get_Switch (Luint8 u8Switch)
Get a pusher switch state.
Parameters
[in] u8Switch Switch index
SafeTool Function MD5:
06E52713C8F3CF4DECF9DB0F2411A42E
SafeTool Function ID:
LCCM655R0.FILE.012.FUNC.005
References sFCU, _strFCU::sPusher, and _strFCU::sSwitches.
void vFCU_PUSHER__10MS_ISR (void)
10ms interrupt function, coming from FCU Core indicating that a new 10mS event has occurred.
SafeTool Function MD5:
D970044779CEE3EA4596DB4D7FFBA79F
SafeTool Function ID:
LCCM655R0.FILE.012.FUNC.009
References sFCU, _strFCU::sPusher, and _strFCU::u32SwtichTimer.
Referenced by vFCU__RTI_10MS_ISR().
void vFCU_PUSHER__Init (void)
Init any variables for the pusher system.
SafeTool Function MD5:
7C79C686EA715C75414C8A1DC69E9CCD
SafeTool Function ID:
LCCM655R0.FILE.012.FUNC.001
References _strFCU::ePusher_Status, _strFCU::eState, PIN_FINAL_STATE__UNKNOWN, PUSH_STATE__IDLE, _strFCU::sFaultFlags, sFCU, _strFCU::sPusher, _strFCU::sSwitches, _strFCU::u32Guard1, _strFCU::u32Guard2, _strFCU::u32SwtichTimer, and vFCU_PUSHER_ETH__Init().
void vFCU_PUSHER__InterlockA_ISR (void)
Called from the N2HET notifications that an edge has occurred on Interlock A.
SafeTool Function MD5:
F532E783C3D9B9BC924CFEFB16029DC8
SafeTool Function ID:
LCCM655R0.FILE.012.FUNC.003
References sFCU, _strFCU::sPusher, and _strFCU::sSwitches.
Referenced by vRM4_N2HET_DYNAMIC__Notification().
void vFCU_PUSHER__InterlockB_ISR (void)
Called from the N2HET notifications that an edge has occurred on Interlock B.
SafeTool Function MD5:
F66C164179E4FC4101AE1B9F280DA709
SafeTool Function ID:
LCCM655R0.FILE.012.FUNC.004
References sFCU, _strFCU::sPusher, and _strFCU::sSwitches.
Referenced by vRM4_N2HET_DYNAMIC__Notification().
void vFCU_PUSHER__Process (void)
Process any pusher interface tasks.
SafeTool Function MD5:
8E34704E4F1C7C92744F7538476CE733
SafeTool Function ID:
LCCM655R0.FILE.012.FUNC.002
References _strFCU::ePusher_Status, _strFCU::eState, PIN_FINAL_STATE__CONNECTED, PIN_FINAL_STATE__DISCONNECTED, PUSH_STATE__CHECK_DISAGREE, PUSH_STATE__DETERMINE_PUSHER_STATE, PUSH_STATE__IDLE, PUSH_STATE__SAMPLE_SWITCHES, PUSH_STATE__WAIT_SW_STABLE, sFCU, _strFCU::sPusher, _strFCU::sSwitches, _strFCU::u32Guard1, _strFCU::u32Guard2, _strFCU::u32SwtichTimer, u8FCU_PUSHER__Get_InterlockA(), and u8FCU_PUSHER__Get_InterlockB().
Variable Documentation
struct _strFCU sFCU
Referenced by eFCU_PUSHER__Get_PusherState(), u8FCU_PUSHER__Get_Switch(), vFCU_PUSHER__10MS_ISR(), vFCU_PUSHER__Init(), vFCU_PUSHER__InterlockA_ISR(), vFCU_PUSHER__InterlockB_ISR(), and vFCU_PUSHER__Process().