(C Code, RLOOP, Flight Control Core): FCU__CORE_NET_TX
FCU__CORE_NET_TX
RLOOP » FCU
Functions
void vFCU_NET_TX__Init (void)
Init any network transmission stuff.
void vFCU_NET_TX__Process (void)
Process network transmission and do any transmission as required.
void vFCU_NET_TX__10MS_ISR (void)
To be called from the 10ms timer routine Sets a flag to allow this module to determine that 10ms has elapsed.
void vFCU_NET_TX__100MS_ISR (void)
ToDo.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
void vFCU_NET_TX__100MS_ISR (void)
ToDo.
SafeTool Function MD5:
EAD22CC59DC6AF2FAD5C3B84720BB133
SafeTool Function ID:
LCCM655R0.FILE.019.FUNC.004
References vFCU_NET_SPACEX_TX__100MS_ISR().
Referenced by vFCU__RTI_100MS_ISR().
void vFCU_NET_TX__10MS_ISR (void)
To be called from the 10ms timer routine Sets a flag to allow this module to determine that 10ms has elapsed.
SafeTool Function MD5:
3A00D72EA0E8E8896C26BBDFA0E4F006
SafeTool Function ID:
LCCM655R0.FILE.019.FUNC.003
References sFCU, _strFCU::sUDPDiag, and _strFCU::u810MS_Flag.
Referenced by vFCU__RTI_10MS_ISR().
void vFCU_NET_TX__Init (void)
Init any network transmission stuff.
SafeTool Function MD5:
ABD3145988312367E93F1F22D96F7A42
SafeTool Function ID:
LCCM655R0.FILE.019.FUNC.001
References _strFCU::eTxPacketType, _strFCU::eTxStreamingType, NET_PKT__NONE, sFCU, _strFCU::sUDPDiag, _strFCU::u810MS_Flag, and vFCU_NET_SPACEX_TX__Init().
Referenced by vFCU_NET__Init().
void vFCU_NET_TX__Process (void)
Process network transmission and do any transmission as required.
SafeTool Function MD5:
CC51B5F1A0B55EC4C0976DE4FB083F76
SafeTool Function ID:
LCCM655R0.FILE.019.FUNC.002
References _strFCU::eTxPacketType, _strFCU::eTxStreamingType, NET_PKT__FCU_ACCEL__TX_CAL_DATA, NET_PKT__FCU_ACCEL__TX_FULL_DATA, NET_PKT__FCU_BRAKES__TX_DATA, NET_PKT__FCU_BRAKES__TX_MOTOR_PARAM, NET_PKT__FCU_NAV__TX_NAV_PROGRESS, NET_PKT__LASER_CONT__TX_LASER_DATA_0, NET_PKT__LASER_DIST__TX_LASER_DATA, NET_PKT__LASER_OPTO__TX_LASER_DATA, NET_PKT__NONE, sFCU, _strFCU::sUDPDiag, _strFCU::u810MS_Flag, vFCU_ACCEL_ETH__Transmit(), vFCU_BRAKES_ETH__Transmit(), vFCU_LASERCONT_ETH__Transmit(), vFCU_LASERDIST_ETH__Transmit(), vFCU_LASEROPTO_ETH__Transmit(), and vFCU_NET_SPACEX_TX__Process().
Referenced by vFCU_NET__Process().
Variable Documentation
struct _strFCU sFCU
Referenced by vFCU_NET_TX__10MS_ISR(), vFCU_NET_TX__Init(), and vFCU_NET_TX__Process().