(C Code, RLOOP, Flight Control Core): FCU__FLIGHT_CTL
FCU__FLIGHT_CTL
RLOOP » FCU
Functions
void vFCU_FLIGHTCTL__Init (void)
Init any variables as is needed by the main state machine.
void vFCU_FLIGHTCTL__Process (void)
Process the flight controller.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
void vFCU_FLIGHTCTL__Init (void)
Init any variables as is needed by the main state machine.
SafeTool Function MD5:
FED0062F6B73B20B0F3C694DC29503FB
SafeTool Function ID:
LCCM655R0.FILE.035.FUNC.001
References vFCU_FLIGHTCTL_CONTRASTNAV__Init().
Referenced by vFCU_MAINSM__Process().
void vFCU_FLIGHTCTL__Process (void)
Process the flight controller.
SafeTool Function MD5:
2111AE504D0BAC2BA86A479BB729D51D
SafeTool Function ID:
LCCM655R0.FILE.035.FUNC.002
References vFCU_FLIGHTCTL_CONTRASTNAV__Process().
Referenced by vFCU_MAINSM__Process().
Variable Documentation
struct _strFCU sFCU