(C Code, RLOOP, Flight Control Core): FCU__ASI__CONTROLLER
FCU__ASI__CONTROLLER
RLOOP » FCU
Functions
Lint16 s16FCU_ASI_CTRL__Init (void)
Initialize ASI controller parameters Broadcast to all devices.
Lint16 s16FCU_ASI_CTRL__ReadMotorRpm (Luint8 u8ASIDevNum, Luint16 *u16Rpm)
Read motor rpm.
Lint16 s16FCU_ASI_CTRL__ReadMotorCurrent (Luint8 u8ASIDevNum, Luint16 *u16Current)
Read motor rpm.
Lint16 s16FCU_ASI_CTRL__ReadControllerTemperature (Luint8 u8ASIDevNum, Luint16 *u16Temp)
Read controller's base plate temperature.
Lint16 s16FCU_ASI_CTRL__SaveSettings (Luint8 u8ASIDevNum)
Save ASI controller settings.
Lint16 s16FCU_ASI_CTRL__GetFaults (Luint8 u8ASIDevNum, Luint16 *u16Faults)
Get faults from ASI controller.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
Lint16 s16FCU_ASI_CTRL__GetFaults (Luint8 u8ASIDevNum, Luint16 * u16Faults)
Get faults from ASI controller.
Parameters
[in] u8ASIDevNum ASI controler device to communicate (1-8)
[out] u16Faults Parameter to store faults bit array
Returns
-1 = error 0 = success
References C_FCU_ASI__FAULTS, E_UINT16, _strASICmd::eDestVarType, _strASICmd::eFunctionCode, _strASICmd::eObjectType, FUNCTION_CODE__READ_INPUT_REGS, s16FCU_ASI__SendCommand(), _strASICmd::u16ParamValue, _strASICmd::u8SlaveAddress, and vFCU_ASI__MemSet().
Lint16 s16FCU_ASI_CTRL__Init (void)
Initialize ASI controller parameters Broadcast to all devices.
Returns
-1 = error 0 = success
References C_FCU_ASI__COMMAND_SOURCE, C_FCU_ASI__FOLDBACK_END_TEMP, C_FCU_ASI__FOLDBACK_STARING_TEMP, C_FCU_ASI__OVER_TEMP_THRESHOLD, _strASICmd::eFunctionCode, _strASICmd::eObjectType, s16FCU_ASI__SendCommand(), _strASICmd::u16ParamValue, _strASICmd::u8SlaveAddress, and vFCU_ASI__MemSet().
Lint16 s16FCU_ASI_CTRL__ReadControllerTemperature (Luint8 u8ASIDevNum, Luint16 * u16Temp)
Read controller's base plate temperature.
Parameters
[in] u8ASIDevNum ASI controler device to communicate (1-8)
[out] u16Temp Parameter to store temperature in Celsius
Returns
-1 = error 0 = success
References C_FCU_ASI__CONT_TEMP, E_UINT16, _strASICmd::eDestVarType, _strASICmd::eFunctionCode, _strASICmd::eObjectType, FUNCTION_CODE__READ_INPUT_REGS, s16FCU_ASI__SendCommand(), _strASICmd::u16ParamValue, _strASICmd::u8SlaveAddress, and vFCU_ASI__MemSet().
Lint16 s16FCU_ASI_CTRL__ReadMotorCurrent (Luint8 u8ASIDevNum, Luint16 * u16Current)
Read motor rpm.
Parameters
[in] u8ASIDevNum ASI controler device to communicate (1-8)
[out] u16Current Parameter to store rpm
Returns
-1 = error 0 = success
References C_FCU_ASI__MOTOR_CURRENT, E_UINT16, _strASICmd::eDestVarType, _strASICmd::eFunctionCode, _strASICmd::eObjectType, FUNCTION_CODE__READ_INPUT_REGS, s16FCU_ASI__SendCommand(), _strASICmd::u16ParamValue, _strASICmd::u8SlaveAddress, and vFCU_ASI__MemSet().
Lint16 s16FCU_ASI_CTRL__ReadMotorRpm (Luint8 u8ASIDevNum, Luint16 * u16Rpm)
Read motor rpm.
Parameters
[in] u8ASIDevNum ASI controler device to communicate (1-8)
[out] u16Rpm Parameter to store rpm
Returns
-1 = error 0 = success
References C_FCU_ASI__MOTOR_RPM, E_UINT16, _strASICmd::eDestVarType, _strASICmd::eFunctionCode, _strASICmd::eObjectType, FUNCTION_CODE__READ_INPUT_REGS, s16FCU_ASI__SendCommand(), _strASICmd::u16ParamValue, _strASICmd::u8SlaveAddress, and vFCU_ASI__MemSet().
Lint16 s16FCU_ASI_CTRL__SaveSettings (Luint8 u8ASIDevNum)
Save ASI controller settings.
Parameters
[in] u8ASIDevNum ASI controler device to communicate (1-8)
Returns
-1 = error 0 = success
References C_FCU_ASI__SAVE_SETTINGS, _strASICmd::eFunctionCode, _strASICmd::eObjectType, FUNCTION_CODE__READ_INPUT_REGS, s16FCU_ASI__SendCommand(), _strASICmd::u16ParamValue, _strASICmd::u8SlaveAddress, and vFCU_ASI__MemSet().
Variable Documentation
struct _strFCU sFCU