(C Code, RLOOP, Flight Control Core): FCU__LASER_DISTANCE__ETHERNET
FCU__LASER_DISTANCE__ETHERNET
RLOOP » FCU
Functions
void vFCU_LASERDIST_ETH__Init (void)
Init Laser distance eth portion.
void vFCU_LASERDIST_ETH__Transmit (E_NET__PACKET_T ePacketType)
Transmith a laser distance eth packet.
void vFCU_LASERDIST_ETH__Emulation_Injection (Lint32 s32Value)
Via eth, inject some emulation value in.
void vFCU_LASERDIST_ETH__Enable_EmulationMode (Luint32 u32Key, Luint32 u32Enable)
Enable emulation mode.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
void vFCU_LASERDIST_ETH__Emulation_Injection (Lint32 s32Value)
Via eth, inject some emulation value in.
Parameters
[in] f32Value The value in laser distance units
SafeTool Function MD5:
3FBE47EDCE814C80FCF4FA76AC2BAB6B
SafeTool Function ID:
LCCM655R0.FILE.058.FUNC.003
References _strFCU::sEmu, sFCU, and _strFCU::sLaserDist.
Referenced by vFCU_NET_RX__RxSafeUDP().
void vFCU_LASERDIST_ETH__Enable_EmulationMode (Luint32 u32Key, Luint32 u32Enable)
Enable emulation mode.
Parameters
[in] u32Enable 1 = Enable
[in] u32Key 0x01010202
SafeTool Function MD5:
14B66A518C87DDDB5C890BF2B042B2C4
SafeTool Function ID:
LCCM655R0.FILE.058.FUNC.004
References _strFCU::sEmu, sFCU, and _strFCU::sLaserDist.
Referenced by vFCU_NET_RX__RxSafeUDP().
void vFCU_LASERDIST_ETH__Init (void)
Init Laser distance eth portion.
SafeTool Function MD5:
A53F7D42D7CCD995A438A1C6C5F45CC4
SafeTool Function ID:
LCCM655R0.FILE.058.FUNC.001
References _strFCU::sEmu, sFCU, and _strFCU::sLaserDist.
Referenced by vFCU_LASERDIST__Init().
void vFCU_LASERDIST_ETH__Transmit (E_NET__PACKET_T ePacketType)
Transmith a laser distance eth packet.
Parameters
[in] ePacketType The packet type
SafeTool Function MD5:
6F7EDE1C5CBC08569FA17C9563330D2D
SafeTool Function ID:
LCCM655R0.FILE.058.FUNC.002
References C_RLOOP_NET__FCU__PORT, NET_PKT__LASER_DIST__TX_LASER_DATA, _strFCU::s32Accel_mmss, _strFCU::s32Distance_mm, _strFCU::s32PrevAccel_mmss, _strFCU::s32PrevDistance_mm, _strFCU::s32PrevVelocity_mms, _strFCU::s32Velocity_mms, _strFCU::sBinary, _strFCU::sFaultFlags, sFCU, and _strFCU::sLaserDist.
Referenced by vFCU_NET_TX__Process().
Variable Documentation
struct _strFCU sFCU
Referenced by vFCU_LASERDIST_ETH__Emulation_Injection(), vFCU_LASERDIST_ETH__Enable_EmulationMode(), vFCU_LASERDIST_ETH__Init(), and vFCU_LASERDIST_ETH__Transmit().