(C Code, RLOOP, Flight Control Core): FCU__CORE_NET_RX
FCU__CORE_NET_RX
RLOOP » FCU
Functions
void vFCU_NET_RX__Init (void)
ToDo.
void vFCU_NET_RX__RxUDP (Luint8 *pu8Buffer, Luint16 u16Length, Luint16 u16DestPort)
Rx a normal UDP packet.
void vFCU_NET_RX__RxSafeUDP (Luint8 *pu8Payload, Luint16 u16PayloadLength, Luint16 ePacketType, Luint16 u16DestPort, Luint16 u16Fault)
Rx a SafetyUDP.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
void vFCU_NET_RX__Init (void)
ToDo.
SafeTool Function MD5:
5B1DE8A3F401FB4A50E331F747199F27
SafeTool Function ID:
LCCM655R0.FILE.018.FUNC.003
References _strFCU::f32AverageTemp, _strFCU::f32HighestCellVoltage, _strFCU::f32HighestTemp, _strFCU::f32LowestCellVoltage, _strFCU::f32PackVoltage, _strFCU::f32PV_Press, _strFCU::f32PV_Temp, _strFCU::sBMS, and sFCU.
void vFCU_NET_RX__RxSafeUDP (Luint8 * pu8Payload, Luint16 u16PayloadLength, Luint16 ePacketType, Luint16 u16DestPort, Luint16 u16Fault)
Rx a SafetyUDP.
Parameters
[in] u16Fault Any fault flags with the Tx.
[in] u16DestPort UDP Destination Port
[in] ePacketType SafeUDP packet Type
[in] u16PayloadLength Length of only the SafeUDP payload
[in] *pu8Payload Pointer to the payload bytes
SafeTool Function MD5:
5AD676C1CB39DA8E23F769F70DAA8534
SafeTool Function ID:
LCCM655R0.FILE.018.FUNC.002
References _strFCU::eTxPacketType, _strFCU::eTxStreamingType, _strFCU::f32AverageTemp, _strFCU::f32HighestCellVoltage, _strFCU::f32HighestTemp, _strFCU::f32LowestCellVoltage, _strFCU::f32PackVoltage, _strFCU::f32PV_Press, _strFCU::f32PV_Temp, NET_PKT__FCU_ACCEL__AUTO_CALIBRATE, NET_PKT__FCU_ACCEL__FINE_ZERO_ADJUSTMENT, NET_PKT__FCU_ACCEL__REQUEST_CAL_DATA, NET_PKT__FCU_ACCEL__REQUEST_FULL_DATA, NET_PKT__FCU_ACCEL__TX_CAL_DATA, NET_PKT__FCU_ACCEL__TX_FULL_DATA, NET_PKT__FCU_ASI__SET_THROTTLE, NET_PKT__FCU_BRAKES__ENABLE_DEV_MODE, NET_PKT__FCU_BRAKES__INIT, NET_PKT__FCU_BRAKES__MLP_ZEROSPAN, NET_PKT__FCU_BRAKES__MOVE_IBEAM, NET_PKT__FCU_BRAKES__MOVE_MOTOR_RAW, NET_PKT__FCU_BRAKES__REQ_MOTOR_PARAM, NET_PKT__FCU_BRAKES__SET_MOTOR_PARAM, NET_PKT__FCU_BRAKES__START_CAL_MODE, NET_PKT__FCU_BRAKES__TX_MOTOR_PARAM, NET_PKT__FCU_BRAKES__VELOC_ACCEL_SET, NET_PKT__FCU_FLT__SELECT_TRACK_DB, NET_PKT__FCU_FLT__TX_TRACK_DB_CHUNK, NET_PKT__FCU_GEN__DAQ_ENABLE, NET_PKT__FCU_GEN__DAQ_FLUSH, NET_PKT__FCU_GEN__ENTER_PRE_RUN_PHASE_COMMAND, NET_PKT__FCU_GEN__GS_HEARTBEAT, NET_PKT__FCU_GEN__POD_EMULATION_CONTROL, NET_PKT__FCU_GEN__POD_STOP_COMMAND, NET_PKT__FCU_GEN__STREAMING_CONTROL, NET_PKT__FCU_HOVERENGINES_CONTROL__M_SET_SPEED_HE1, NET_PKT__FCU_HOVERENGINES_CONTROL__M_SET_SPEED_HE2, NET_PKT__FCU_HOVERENGINES_CONTROL__M_SET_SPEED_HE3, NET_PKT__FCU_HOVERENGINES_CONTROL__M_SET_SPEED_HE4, NET_PKT__FCU_HOVERENGINES_CONTROL__M_SET_SPEED_HE5, NET_PKT__FCU_HOVERENGINES_CONTROL__M_SET_SPEED_HE6, NET_PKT__FCU_HOVERENGINES_CONTROL__M_SET_SPEED_HE7, NET_PKT__FCU_HOVERENGINES_CONTROL__M_SET_SPEED_HE8, NET_PKT__FCU_HOVERENGINES_CONTROL__RELEASE_STATIC_HOVERING, NET_PKT__FCU_HOVERENGINES_CONTROL__STATIC_HOVERING, NET_PKT__FCU_LIFTMECH__RELEASE, NET_PKT__FCU_LIFTMECH__SET_GROUP_SPEED, NET_PKT__FCU_PUSH__REQUEST_PUSHER_DATA, NET_PKT__FCU_PUSH__TX_PUSHER_DATA, NET_PKT__FCU_THROTTLE__ENABLE_DEV_MODE, NET_PKT__FCU_THROTTLE__REQUEST_DATA, NET_PKT__FCU_THROTTLE__SET_RAW_THROTTLE, NET_PKT__FCU_THROTTLE__TX_DATA, NET_PKT__LASER_CONT__REQUEST_LASER_DATA, NET_PKT__LASER_CONT__TX_LASER_DATA_0, NET_PKT__LASER_CONT__TX_LASER_DATA_1, NET_PKT__LASER_CONT__TX_LASER_DATA_2, NET_PKT__LASER_DIST__ENABLE_EMULATION_MODE, NET_PKT__LASER_DIST__RAW_EMULATION_VALUE, NET_PKT__LASER_DIST__REQUEST_LASER_DATA, NET_PKT__LASER_DIST__TX_LASER_DATA, NET_PKT__LASER_OPTO__CAL_LASER_HEIGHT, NET_PKT__LASER_OPTO__REQUEST_LASER_DATA, NET_PKT__LASER_OPTO__TX_LASER_DATA, NET_PKT__NONE, NET_PKT__PWR_BMS__TX_BMS_STATUS, _strFCU::sBMS, sFCU, _strFCU::sUDPDiag, vFCU_ASI__Set_Throttle(), vFCU_BRAKES__Begin_Init(), vFCU_BRAKES_CAL__BeginCal(), vFCU_BRAKES_ETH__Enable_DevMode(), vFCU_BRAKES_ETH__MLP_ZeroSpan(), vFCU_BRAKES_ETH__MoveMotor_IBeam(), vFCU_BRAKES_ETH__MoveMotor_RAW(), vFCU_BRAKES_STEP__UpdateValues(), vFCU_FCTL_DRIVEPOD__10MS_ISR(), vFCU_FCTL_DRIVEPOD__SetPodStopCmd(), vFCU_FCTL_LIFTMECH__Extend(), vFCU_FCTL_LIFTMECH__SetSpeedAll(), vFCU_FCTL_MAINSM__EnterPreRun_Phase(), vFCU_FCTL_TRACKDB__Set_CurrentDB(), vFCU_FCTL_TRACKDB_MEM__UploadChunk(), vFCU_LASERDIST_ETH__Emulation_Injection(), vFCU_LASERDIST_ETH__Enable_EmulationMode(), vFCU_LASEROPTO__Set_CalValue(), vFCU_THROTTLE_ETH__Enable_DevMode(), and vFCU_THROTTLE_ETH__Set_Throttle().
void vFCU_NET_RX__RxUDP (Luint8 * pu8Buffer, Luint16 u16Length, Luint16 u16DestPort)
Rx a normal UDP packet.
Parameters
[in] u16DestPort The dest port on the UDP frame
[in] u16Length Length of UDP payload
[in] *pu8Buffer Pointer to UDP payload
SafeTool Function MD5:
DC1B8CA75C73EC734B09AF640F3012B7
SafeTool Function ID:
LCCM655R0.FILE.018.FUNC.001
Variable Documentation
struct _strFCU sFCU
Referenced by vFCU_NET_RX__Init(), and vFCU_NET_RX__RxSafeUDP().