(C Code, RLOOP, Flight Control Core): FCU__LASER_CONTRAST__TIMING_LIST
FCU__LASER_CONTRAST__TIMING_LIST
RLOOP » FCU
Functions
void vFCU_LASERCONT_TL__Init (void)
Init the timing list.
void vFCU_LASERCONT_TL__Process (void)
Process the laser contrast list system.
void vFCU_LASERCONT_TL__ISR (E_FCU__LASER_CONT_INDEX_T eLaser, Luint32 u32Register)
Rising and falling edge Interrupts from the RM4 notification system.
Luint64 u64FCU_LASERCONT_TL__Get_TimeDelta (E_FCU__LASER_CONT_INDEX_T eLaser, Luint16 u16CurrentIndex)
Gets the difference btween the current edge and previous edge.
Luint8 u8FCU_LASERCONT_TL__Get_NewRisingAvail (E_FCU__LASER_CONT_INDEX_T eLaser)
Return if a new rising edge has been detected.
void vFCU_LASERCONT_TL__Clear_NewRisingAvail (E_FCU__LASER_CONT_INDEX_T eLaser)
Clear out the new rising edge flag once its been taken.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
Luint64 u64FCU_LASERCONT_TL__Get_TimeDelta (E_FCU__LASER_CONT_INDEX_T eLaser, Luint16 u16CurrentIndex)
Gets the difference btween the current edge and previous edge.
can only use used if new rising edge avail = 1 and there is suitable rising data
Parameters
[in] eLaser The laser index
[in] u16CurrentIndex The current index to compare against
SafeTool Function MD5:
A7C670C712B3C8EA0B5451ECAABE9577
SafeTool Function ID:
LCCM655R0.FILE.042.FUNC.006
References _strFCU::sContrast, sFCU, _strFCU::sTimingList, and _strFCU::u64RisingList.
Referenced by vFCU_LASERCONT__Process().
Luint8 u8FCU_LASERCONT_TL__Get_NewRisingAvail (E_FCU__LASER_CONT_INDEX_T eLaser)
Return if a new rising edge has been detected.
Parameters
[in] eLaser The laser index
SafeTool Function MD5:
92F834345EEDB528E2092A78E1806443
SafeTool Function ID:
LCCM655R0.FILE.042.FUNC.004
References _strFCU::sContrast, sFCU, _strFCU::sTimingList, and _strFCU::u8NewRisingAvail.
Referenced by vFCU_LASERCONT__Process().
void vFCU_LASERCONT_TL__Clear_NewRisingAvail (E_FCU__LASER_CONT_INDEX_T eLaser)
Clear out the new rising edge flag once its been taken.
Parameters
[in] eLaser The laser index
SafeTool Function MD5:
E776E69E5EDEE8E30C9B3BC6D316D0A2
SafeTool Function ID:
LCCM655R0.FILE.042.FUNC.005
References _strFCU::sContrast, sFCU, _strFCU::sTimingList, and _strFCU::u8NewRisingAvail.
Referenced by vFCU_LASERCONT__Process().
void vFCU_LASERCONT_TL__Init (void)
Init the timing list.
SafeTool Function MD5:
9BA52F4C0FCD64FBCF621D2764E85A47
SafeTool Function ID:
LCCM655R0.FILE.042.FUNC.001
References C_FCU__LASER_CONTRAST__MAX_STRIPES, LASER_CONT__MAX, _strFCU::sContrast, sFCU, and _strFCU::sTimingList.
Referenced by vFCU_LASERCONT__Init().
void vFCU_LASERCONT_TL__ISR (E_FCU__LASER_CONT_INDEX_T eLaser, Luint32 u32Register)
Rising and falling edge Interrupts from the RM4 notification system.
Note
This is an interrupt task!. Take Care
Parameters
[in] eLaser The laser
[in] u32Register Snapshot of pin
SafeTool Function MD5:
C9E0D08D7A05712DAD2D8ACF97A7DF77
SafeTool Function ID:
LCCM655R0.FILE.042.FUNC.003
References C_FCU__LASER_CONTRAST__MAX_STRIPES, LASER_CONT__AFT, LASER_CONT__FWD, LASER_CONT__MAX, LASER_CONT__MID, _strFCU::sContrast, sFCU, _strFCU::sTimingList, _strFCU::u16FallingCount, _strFCU::u16RisingCount, _strFCU::u64FallingList, _strFCU::u64RisingList, and _strFCU::u8NewRisingAvail.
Referenced by vFCU_LASERCONT__ISR().
void vFCU_LASERCONT_TL__Process (void)
Process the laser contrast list system.
SafeTool Function MD5:
B49F777F22EE331A3A234297EEC04270
SafeTool Function ID:
LCCM655R0.FILE.042.FUNC.002
References C_FCU__LASER_CONTRAST__MAX_STRIPES, LASER_CONT__MAX, _strFCU::sContrast, sFCU, and _strFCU::sTimingList.
Referenced by vFCU_LASERCONT__Process().
Variable Documentation
struct _strFCU sFCU
Referenced by u64FCU_LASERCONT_TL__Get_TimeDelta(), u8FCU_LASERCONT_TL__Get_NewRisingAvail(), vFCU_LASERCONT_TL__Clear_NewRisingAvail(), vFCU_LASERCONT_TL__Init(), vFCU_LASERCONT_TL__ISR(), and vFCU_LASERCONT_TL__Process().