(C Code, RLOOP, Flight Control Core): FCU__LASER_DISTANCE
FCU__LASER_DISTANCE
RLOOP » FCU
Functions
void vFCU_LASERDIST__Append_Byte (Luint8 u8Value)
Append a new byte from the UART into the internal array, handle any error checking.
void vFCU_LASERDIST__Process_Packet (void)
void vFCU_LASERDIST__Init (void)
Init any of the laser distance items.
void vFCU_LASERDIST__Process (void)
Process the laser distance system.
Lint32 s32FCU_LASERDIST__Get_Distance_mm (void)
Return the current computed distance.
void vFCU_LASERDIST__Process_Packet_ASCII (void)
Process the laser packet Take the laser packet byte array that has been captured and process it into a length including fault detection.
void vFCU_LASERDIST__100MS_ISR (void)
100ms Timer interrupt.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
Lint32 s32FCU_LASERDIST__Get_Distance_mm (void)
Return the current computed distance.
SafeTool Function MD5:
130FEC5285C1E938EA3350D14F3B468C
SafeTool Function ID:
LCCM655R0.FILE.033.FUNC.003
References _strFCU::s32Distance_mm, sFCU, and _strFCU::sLaserDist.
void vFCU_LASERDIST__100MS_ISR (void)
100ms Timer interrupt.
SafeTool Function MD5:
D7AC2E42B341C67C3BC9659D2E8CEC02
SafeTool Function ID:
LCCM655R0.FILE.033.FUNC.006
References _strFCU::s32Distance_mm, sFCU, _strFCU::sLaserDist, _strFCU::u32BytesSeen_Counter, _strFCU::u32LaserPOR_Counter, _strFCU::u32PacketsSeen_Counter, and vFCU_LASERDIST_WIN32__Set_DistanceRaw().
Referenced by vFCU__RTI_100MS_ISR().
void vFCU_LASERDIST__Append_Byte (Luint8 u8Value)
Append a new byte from the UART into the internal array, handle any error checking.
Parameters
[in] u8Value The new byte
SafeTool Function MD5:
4CFB149BFF4B44D13D8DC54626482976
SafeTool Function ID:
LCCM655R0.FILE.033.FUNC.005
References _strFCU::eRxState, LASERDIST_RX__BYTE_0, LASERDIST_RX__BYTE_1, LASERDIST_RX__BYTE_2, LASERDIST_RX__BYTE_3, LASERDIST_RX__BYTE_4, LASERDIST_RX__BYTE_D, _strFCU::sBinary, sFCU, _strFCU::sLaserDist, _strFCU::u32PacketsSeen_Counter, _strFCU::u8NewByteArray, and _strFCU::u8NewPacket.
Referenced by vFCU_LASERDIST__Process().
void vFCU_LASERDIST__Init (void)
Init any of the laser distance items.
SafeTool Function MD5:
CB16DEE2A7F5C05AABD3BA9584754C90
SafeTool Function ID:
LCCM655R0.FILE.033.FUNC.001
References _strFCU::eLaserState, _strFCU::eRxState, LASERDIST_RX__BYTE_D, LASERDIST_STATE__RESET, _strFCU::s32Accel_mmss, _strFCU::s32Distance_mm, _strFCU::s32PrevAccel_mmss, _strFCU::s32PrevDistance_mm, _strFCU::s32PrevVelocity_mms, _strFCU::s32Velocity_mms, _strFCU::sBinary, _strFCU::sFaultFlags, sFCU, _strFCU::sLaserDist, _strFCU::u32BytesSeen_Counter, _strFCU::u32LaserPOR_Counter, _strFCU::u32PacketsSeen_Counter, _strFCU::u8NewDistanceAvail, _strFCU::u8NewPacket, vFCU_LASERDIST_ETH__Init(), and vFCU_LASERDIST_FILT__Init().
Referenced by vFCU__Process().
void vFCU_LASERDIST__Process (void)
Process the laser distance system.
SafeTool Function MD5:
36297D2EDE06DBA5285970E47A1EC16B
SafeTool Function ID:
LCCM655R0.FILE.033.FUNC.002
References C_FCU__SC16_FWD_LASER_INDEX, C_LCCM655__LASER_DISTANCE__FAULT_INDEX__00, C_LCCM655__LASER_DISTANCE__FAULT_INDEX__01, C_LCCM655__LASER_DISTANCE__FAULT_INDEX__02, _strFCU::eLaserState, LASERDIST_STATE__CHECK_NEW_DATA, LASERDIST_STATE__CHECK_NEW_PACKET, LASERDIST_STATE__INIT_LASER_TURNON, LASERDIST_STATE__RESET, LASERDIST_STATE__WAIT_INIT_DONE, LASERDIST_STATE__WAIT_LASER_RESET, _strFCU::s32Distance_mm, _strFCU::sEmu, _strFCU::sFaultFlags, sFCU, _strFCU::sLaserDist, _strFCU::u32BytesSeen_Counter, _strFCU::u32LaserPOR_Counter, _strFCU::u32PacketsSeen_Counter, _strFCU::u8NewPacket, vFCU_LASERDIST__Append_Byte(), vFCU_LASERDIST__Process_Packet(), and vFCU_LASERDIST_FILT__Process().
Referenced by vFCU__Process().
void vFCU_LASERDIST__Process_Packet (void)
References _strFCU::s32Distance_mm, _strFCU::s32PrevDistance_mm, _strFCU::s32PrevVelocity_mms, _strFCU::s32Velocity_mms, _strFCU::sBinary, sFCU, and _strFCU::sLaserDist.
Referenced by vFCU_LASERDIST__Process().
void vFCU_LASERDIST__Process_Packet_ASCII (void)
Process the laser packet Take the laser packet byte array that has been captured and process it into a length including fault detection.
SafeTool Function MD5:
50D2F735AC8706F6B0746CCB9860BD5A
SafeTool Function ID:
LCCM655R0.FILE.033.FUNC.004
References _strFCU::s32Distance_mm, _strFCU::s32PrevDistance_mm, _strFCU::s32PrevVelocity_mms, _strFCU::s32Velocity_mms, sFCU, _strFCU::sLaserDist, and _strFCU::u8NewByteArray.
Variable Documentation
struct _strFCU sFCU
Referenced by s32FCU_LASERDIST__Get_Distance_mm(), vFCU_LASERDIST__100MS_ISR(), vFCU_LASERDIST__Append_Byte(), vFCU_LASERDIST__Init(), vFCU_LASERDIST__Process(), vFCU_LASERDIST__Process_Packet(), and vFCU_LASERDIST__Process_Packet_ASCII().