(C Code, RLOOP, Flight Control Core): FCU__BRAKES__SWITCHES
FCU__BRAKES__SWITCHES
RLOOP » FCU
Functions
void vFCU_BRAKES_SW__Init (void)
Init the brake switches modules.
void vFCU_BRAKES_SW__Process (void)
Process the brake swtich tasks.
Luint8 u8FCU_BRAKES_SW__Get_FaultFlag (E_FCU__BRAKE_INDEX_T eBrake)
Gets the fault flag of a brake limit switches.
E_FCU__SWITCH_STATE_T eFCU_BRAKES_SW__Get_Switch (E_FCU__BRAKE_INDEX_T eBrake, E_FCU__BRAKE_LIMSW_INDEX_T eSwitch)
Gets the state of a brake limit swtich.
void vFCU_BRAKES_SW__Left_SwitchRetract_ISR (void)
Brake 0 (Left) Retract switch interrupt handler.
void vFCU_BRAKES_SW__Left_SwitchExtend_ISR (void)
Brake 0 (Left) Extended switch interrupt handler.
void vFCU_BRAKES_SW__Right_SwitchRetract_ISR (void)
Brake 1 (Right) Retract switch interrupt handler.
void vFCU_BRAKES_SW__Right_SwitchExtend_ISR (void)
Brake 1 (Right) Extended switch interrupt handler.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
E_FCU__SWITCH_STATE_T eFCU_BRAKES_SW__Get_Switch (E_FCU__BRAKE_INDEX_T eBrake, E_FCU__BRAKE_LIMSW_INDEX_T eSwitch)
Gets the state of a brake limit swtich.
Parameters
[in] eBrake The brake, left or right
[in] eSwitch The extend or retract switch
Returns
Open, Closed or Unknown
SafeTool Function MD5:
3C8ABC20E7D6C00B0AC1BFE2AF5CAC9F
SafeTool Function ID:
LCCM655R0.FILE.008.FUNC.004
References BRAKE_SW__EXTEND, BRAKE_SW__RETRACT, FCU_BRAKE__LEFT, FCU_BRAKE__RIGHT, _strFCU::sBrakes, sFCU, _strFCU::sLimits, SW_STATE__CLOSED, SW_STATE__OPEN, and SW_STATE__UNKNOWN.
Referenced by vFCU_BRAKES_SW__Init(), vFCU_BRAKES_SW__Left_SwitchExtend_ISR(), vFCU_BRAKES_SW__Left_SwitchRetract_ISR(), vFCU_BRAKES_SW__Process(), vFCU_BRAKES_SW__Right_SwitchExtend_ISR(), and vFCU_BRAKES_SW__Right_SwitchRetract_ISR().
Luint8 u8FCU_BRAKES_SW__Get_FaultFlag (E_FCU__BRAKE_INDEX_T eBrake)
Gets the fault flag of a brake limit switches.
Parameters
[in] eBrake The brake index
Returns
0 = normal, 1 = fault
SafeTool Function MD5:
4D64D7EE0EA87E2F031F6F1E830B0400
SafeTool Function ID:
LCCM655R0.FILE.008.FUNC.003
References _strFCU::sBrakes, sFCU, and _strFCU::u8BrakeSWErr.
void vFCU_BRAKES_SW__Init (void)
Init the brake switches modules.
SafeTool Function MD5:
F6743C5D24C6F1A8B21D48171565088E
SafeTool Function ID:
LCCM655R0.FILE.008.FUNC.001
References BRAKE_SW__EXTEND, BRAKE_SW__MAX_SWITCHES, BRAKE_SW__RETRACT, eFCU_BRAKES_SW__Get_Switch(), FCU_BRAKE__LEFT, FCU_BRAKE__MAX_BRAKES, FCU_BRAKE__RIGHT, _strFCU::sBrakes, sFCU, _strFCU::sLimits, SW_STATE__UNKNOWN, and _strFCU::u8BrakeSWErr.
Referenced by vFCU_BRAKES__Init().
void vFCU_BRAKES_SW__Left_SwitchExtend_ISR (void)
Brake 0 (Left) Extended switch interrupt handler.
SafeTool Function MD5:
A1288865E582EA89F5D959E06FF0D94F
SafeTool Function ID:
LCCM655R0.FILE.008.FUNC.006
References BRAKE_SW__EXTEND, eFCU_BRAKES_SW__Get_Switch(), _strFCU::eState, FCU_BRAKE__LEFT, _strFCU::sBrakes, sFCU, _strFCU::sLimits, and SW_STATE__CLOSED.
void vFCU_BRAKES_SW__Left_SwitchRetract_ISR (void)
Brake 0 (Left) Retract switch interrupt handler.
SafeTool Function MD5:
2DF72977BF0AED91B2339B5D3B368119
SafeTool Function ID:
LCCM655R0.FILE.008.FUNC.005
References BRAKE_SW__RETRACT, eFCU_BRAKES_SW__Get_Switch(), _strFCU::eState, FCU_BRAKE__LEFT, _strFCU::sBrakes, sFCU, _strFCU::sLimits, and SW_STATE__CLOSED.
void vFCU_BRAKES_SW__Process (void)
Process the brake swtich tasks.
SafeTool Function MD5:
80D83DD333C80661C9CFB02740D2B094
SafeTool Function ID:
LCCM655R0.FILE.008.FUNC.002
References BRAKE_SW__EXTEND, BRAKE_SW__MAX_SWITCHES, BRAKE_SW__RETRACT, eFCU_BRAKES_SW__Get_Switch(), _strFCU::eSwitchState, FCU_BRAKE__MAX_BRAKES, _strFCU::sBrakes, sFCU, _strFCU::sLimits, SW_STATE__CLOSED, _strFCU::u8BrakeSWErr, and _strFCU::u8EdgeSeen.
Referenced by vFCU_BRAKES__Process().
void vFCU_BRAKES_SW__Right_SwitchExtend_ISR (void)
Brake 1 (Right) Extended switch interrupt handler.
SafeTool Function MD5:
31C93BD90EBEB10F2A6B0E9FAD251F9E
SafeTool Function ID:
LCCM655R0.FILE.008.FUNC.008
References BRAKE_SW__EXTEND, eFCU_BRAKES_SW__Get_Switch(), _strFCU::eState, FCU_BRAKE__RIGHT, _strFCU::sBrakes, sFCU, _strFCU::sLimits, and SW_STATE__CLOSED.
void vFCU_BRAKES_SW__Right_SwitchRetract_ISR (void)
Brake 1 (Right) Retract switch interrupt handler.
SafeTool Function MD5:
0101B1C33C17D48AF5AA3FFF500C3CE4
SafeTool Function ID:
LCCM655R0.FILE.008.FUNC.007
References BRAKE_SW__RETRACT, eFCU_BRAKES_SW__Get_Switch(), _strFCU::eState, FCU_BRAKE__RIGHT, _strFCU::sBrakes, sFCU, _strFCU::sLimits, and SW_STATE__CLOSED.
Variable Documentation
struct _strFCU sFCU
Referenced by eFCU_BRAKES_SW__Get_Switch(), u8FCU_BRAKES_SW__Get_FaultFlag(), vFCU_BRAKES_SW__Init(), vFCU_BRAKES_SW__Left_SwitchExtend_ISR(), vFCU_BRAKES_SW__Left_SwitchRetract_ISR(), vFCU_BRAKES_SW__Process(), vFCU_BRAKES_SW__Right_SwitchExtend_ISR(), and vFCU_BRAKES_SW__Right_SwitchRetract_ISR().