(C Code, RLOOP, Flight Control Core): FCU__LASER_OPTO
FCU__LASER_OPTO
RLOOP » FCU
Macros
#define C_LASEROPTO__ERROR_CODE_VALUE (65468U)
OptoNCDT's error value (out of range)
Functions
static void vFCU_LASEROPTO__Process_Packet (E_FCU__LASER_OPTO__INDEX_T eLaser)
Process the laser packet.
static void vFCU_LASEROPTO__Append_Byte (E_FCU__LASER_OPTO__INDEX_T eLaser, Luint8 u8Value)
Append a newly received byte of data onto the laser subsystem.
void vFCU_LASEROPTO__Init (void)
Init any variables.
void vFCU_LASEROPTO__Set_CalValue (Luint32 u32Key, Lfloat32 f32Offset)
ToDo.
void vFCU_LASEROPTO__Process (void)
Process any laser opto tasks.
Lfloat32 f32FCU_LASEROPTO__Get_Distance (E_FCU__LASER_OPTO__INDEX_T eLaser)
Get a lasers distance (The filtered value)
Luint8 u8FCU_LASEROPTO__Get_Error (E_FCU__LASER_OPTO__INDEX_T eLaser)
Get laser error state.
void vFCU_LASEROPTO__100MS_ISR (void)
100MS ISR point
Variables
struct _strFCU sFCU
Detailed Description
Macro Definition Documentation
#define C_LASEROPTO__ERROR_CODE_VALUE (65468U)
OptoNCDT's error value (out of range)
Referenced by vFCU_LASEROPTO__Process_Packet().
Function Documentation
Lfloat32 f32FCU_LASEROPTO__Get_Distance (E_FCU__LASER_OPTO__INDEX_T eLaser)
Get a lasers distance (The filtered value)
Parameters
[in] u8LaserIndex The laser index
SafeTool Function MD5:
730AD78103D781F1DA11563860869910
SafeTool Function ID:
LCCM655R0.FILE.021.FUNC.003
References sFCU, _strFCU::sFiltered, _strFCU::sLaserOpto, and _strFCU::sOptoLaser.
Luint8 u8FCU_LASEROPTO__Get_Error (E_FCU__LASER_OPTO__INDEX_T eLaser)
Get laser error state.
Parameters
[in] u8LaserIndex The laser index
SafeTool Function MD5:
826C100C0C830F2FFD57066B7877AF99
SafeTool Function ID:
LCCM655R0.FILE.021.FUNC.007
References sFCU, _strFCU::sLaserOpto, _strFCU::sOptoLaser, and _strFCU::u8Error.
void vFCU_LASEROPTO__100MS_ISR (void)
100MS ISR point
SafeTool Function MD5:
E23807C52369107D55D0953516ED2BFB
SafeTool Function ID:
LCCM655R0.FILE.021.FUNC.006
References sFCU, _strFCU::sLaserOpto, _strFCU::sOptoLaser, _strFCU::u32LaserPOR_Counter, and vFCU_LASEROPTO_WIN32__Set_DistanceRaw().
Referenced by vFCU__RTI_100MS_ISR().
void vFCU_LASEROPTO__Append_Byte (E_FCU__LASER_OPTO__INDEX_T eLaser, Luint8 u8Value) static
Append a newly received byte of data onto the laser subsystem.
Note
8.2 Measurement Data Format 18 bits are transmitted per output value, see Chap. 7.5.2. An output value is divided into three bytes that differ in the two most significant bits. The transmission of additional output values is optional. Output value 1 / additional:
L-Byte 0 0 D5 D4 D3 D2 D1 D0 M-Byte 0 1 D11 D10 D9 D8 D7 D6 H-Byte 1 0(2)0(3) 0(3) D15 D14 D13 D12 Output sequence: L-Byte, M-Byte, H-Byte. 1, 3) Error values are coded with 18 Bit. 2) To decide between the 1st output value and additional output values, bit 7 in the H-Byte is set to 1. Bit 7 in the H-Byte is set to 0 for the 1st output value. This simultaneously represents the identifier of a new block. De- pending on the measuring rate, baud rate and output data rate output all data can be output in one block. If data output is not possible, a run-time error will be output. Use the command GETOUTINFO_RS422 to query for data selection and output sequence.
Parameters
[in] u8Value New byte value
[in] u8LaserIndex The laser index.
SafeTool Function MD5:
DA0F12390988943896FBFA359E063324
SafeTool Function ID:
LCCM655R0.FILE.021.FUNC.005
References C_FCU__NUM_LASERS_OPTONCDT, _strFCU::eRxState, OPTONCDT_RX__BYTE_1, OPTONCDT_RX__BYTE_2, OPTONCDT_RX__BYTE_3, _strFCU::sCounters, sFCU, _strFCU::sLaserOpto, _strFCU::sOptoLaser, _strFCU::u8NewByteArray, and _strFCU::u8NewPacket.
Referenced by vFCU_LASEROPTO__Process().
void vFCU_LASEROPTO__Init (void)
Init any variables.
SafeTool Function MD5:
2BA57935D2552A930E3C1C4FF621AE4A
SafeTool Function ID:
LCCM655R0.FILE.021.FUNC.001
References C_FCU__NUM_LASERS_OPTONCDT, C_FCU__SC16_OPTO_FL_INDEX, C_FCU__SC16_OPTO_FR_INDEX, C_FCU__SC16_OPTO_RL_INDEX, C_FCU__SC16_OPTO_RR_INDEX, C_LOCALDEF__LCCM655__FCTL_OPTONCDT___CRC, C_LOCALDEF__LCCM655__FCTL_OPTONCDT___FL_ZERO, C_LOCALDEF__LCCM655__FCTL_OPTONCDT___FR_ZERO, C_LOCALDEF__LCCM655__FCTL_OPTONCDT___RL_ZERO, C_LOCALDEF__LCCM655__FCTL_OPTONCDT___RR_ZERO, _strFCU::eOptoNCDTState, OPTOLASER_STATE__RESET, OPTONCDT_RX__BYTE_1, _strFCU::sCalibration, _strFCU::sFaultFlags, sFCU, _strFCU::sLaserOpto, and _strFCU::sOptoLaser.
void vFCU_LASEROPTO__Process (void)
Process any laser opto tasks.
SafeTool Function MD5:
1BD1F37A6175A03AB900257F01E11343
SafeTool Function ID:
LCCM655R0.FILE.021.FUNC.002
References C_FCU__SC16_OPTO_FL_INDEX, C_FCU__SC16_OPTO_YAWR_INDEX, _strFCU::eOptoNCDTState, OPTOLASER_STATE__CHECK_NEW_DATA, OPTOLASER_STATE__CHECK_NEW_PACKET, OPTOLASER_STATE__FILTER_PACKET, OPTOLASER_STATE__INIT_LASER, OPTOLASER_STATE__RESET, OPTOLASER_STATE__WAIT_INIT_DONE, OPTOLASER_STATE__WAIT_LASER_RESET, sFCU, _strFCU::sLaserOpto, _strFCU::sOptoLaser, _strFCU::u32LaserPOR_Counter, vFCU_LASEROPTO__Append_Byte(), vFCU_LASEROPTO__Process_Packet(), and vFCU_LASEROPTO_FILT__FilterPacket().
void vFCU_LASEROPTO__Process_Packet (E_FCU__LASER_OPTO__INDEX_T eLaser) static
Process the laser packet.
Parameters
[in] u8LaserIndex The laser index
SafeTool Function MD5:
8E92CA04DFF76369C507CD9BBBE3EA66
SafeTool Function ID:
LCCM655R0.FILE.021.FUNC.004
References C_FCU__NUM_LASERS_OPTONCDT, C_LASEROPTO__ERROR_CODE_VALUE, _strFCU::f32DistanceRAW, _strFCU::sCounters, _strFCU::sFaultFlags, sFCU, _strFCU::sLaserOpto, _strFCU::sOptoLaser, _strFCU::u8Error, _strFCU::u8NewByteArray, and _strFCU::u8NewDistanceAvail.
Referenced by vFCU_LASEROPTO__Process().
void vFCU_LASEROPTO__Set_CalValue (Luint32 u32Key, Lfloat32 f32Offset)
ToDo.
Parameters
[in] f32Offset ## Desc ##
[in] u32Key ## Desc ##
SafeTool Function MD5:
BF3670622F86308F09694DAA20E95429
SafeTool Function ID:
LCCM655R0.FILE.021.FUNC.009
References C_FCU__SC16_OPTO_FL_INDEX, C_FCU__SC16_OPTO_FR_INDEX, C_FCU__SC16_OPTO_RL_INDEX, C_FCU__SC16_OPTO_RR_INDEX, C_LOCALDEF__LCCM655__FCTL_OPTONCDT___CRC, C_LOCALDEF__LCCM655__FCTL_OPTONCDT___FL_ZERO, C_LOCALDEF__LCCM655__FCTL_OPTONCDT___FR_ZERO, C_LOCALDEF__LCCM655__FCTL_OPTONCDT___RL_ZERO, C_LOCALDEF__LCCM655__FCTL_OPTONCDT___RR_ZERO, _strFCU::f32Offset, _strFCU::sCalibration, sFCU, _strFCU::sLaserOpto, and _strFCU::sOptoLaser.
Referenced by vFCU_NET_RX__RxSafeUDP().
Variable Documentation
struct _strFCU sFCU
Referenced by f32FCU_LASEROPTO__Get_Distance(), u8FCU_LASEROPTO__Get_Error(), vFCU_LASEROPTO__100MS_ISR(), vFCU_LASEROPTO__Append_Byte(), vFCU_LASEROPTO__Init(), vFCU_LASEROPTO__Process(), vFCU_LASEROPTO__Process_Packet(), and vFCU_LASEROPTO__Set_CalValue().