(C Code, RLOOP, Flight Control Core): FCU__BRAKES__CAL
FCU__BRAKES__CAL
RLOOP » FCU
Macros
#define C_FCU_BRAKES__CAL_TYPE (2U)
Functions
void vFCU_BRAKES_CAL__Init (void)
Init the calibration module.
void vFCU_BRAKES_CAL__Process (void)
Luint8 u8FCU_BRAKES_CAL__Is_Busy (void)
returns 1 if we are busy
void vFCU_BRAKES_CAL__BeginCal (Luint32 u32Key)
begin the calibration routine
Variables
struct _strFCU sFCU
Detailed Description
Macro Definition Documentation
#define C_FCU_BRAKES__CAL_TYPE (2U)
Function Documentation
Luint8 u8FCU_BRAKES_CAL__Is_Busy (void)
returns 1 if we are busy
SafeTool Function MD5:
50D0AE035BAB4BC40A403C24490A26C8
SafeTool Function ID:
LCCM655R0.FILE.068.FUNC.004
References BRAKE_CAL_STATE__COMPLETE, BRAKE_CAL_STATE__IDLE, _strFCU::sBrakesGlobal, _strFCU::sCalibration, and sFCU.
Referenced by vFCU_BRAKES__Process().
void vFCU_BRAKES_CAL__BeginCal (Luint32 u32Key)
begin the calibration routine
Parameters
[in] u32Key 0x00112233U
SafeTool Function MD5:
456C98C08EB01C52485F065B61C9B009
SafeTool Function ID:
LCCM655R0.FILE.068.FUNC.005
References BRAKE_CAL__TYPE2__RETRACT_RIGHT, BRAKE_CAL_STATE__EXTEND_MOTORS, BRAKE_CAL_STATE__IDLE, _strFCU::sBrakesGlobal, _strFCU::sCalibration, and sFCU.
Referenced by vFCU_BRAKES__Process(), vFCU_BRAKES_ETH__Start_Calibration(), and vFCU_NET_RX__RxSafeUDP().
void vFCU_BRAKES_CAL__Init (void)
Init the calibration module.
SafeTool Function MD5:
0D4C59962EF7DD7F98DCFA022EB3D530
SafeTool Function ID:
LCCM655R0.FILE.068.FUNC.002
References BRAKE_CAL_STATE__IDLE, _strFCU::sBrakesGlobal, _strFCU::sCalibration, and sFCU.
Referenced by vFCU_BRAKES__Init().
void vFCU_BRAKES_CAL__Process (void)
References BRAKE_CAL__TYPE2__RELEASE_RIGHT, BRAKE_CAL__TYPE2__RETRACT_RIGHT, BRAKE_CAL__TYPE2__WAIT_RETRACT_RIGHT, BRAKE_CAL_STATE__APPLY_NEW_ZERO, BRAKE_CAL_STATE__COMPLETE, BRAKE_CAL_STATE__EXTEND_MOTORS, BRAKE_CAL_STATE__IDLE, BRAKE_CAL_STATE__RELEASE_ZERO, BRAKE_CAL_STATE__WAIT_EXTEND_MOTORS, BRAKE_CAL_STATE__WAIT_NEW_ZERO, BRAKE_SW__EXTEND, BRAKE_SW__RETRACT, FCU_BRAKE__LEFT, FCU_BRAKE__RIGHT, s32FCU_BRAKES__Get_CurrentPos(), _strFCU::sBrakes, _strFCU::sBrakesGlobal, _strFCU::sCalibration, sFCU, _strFCU::sLimits, _strFCU::sMove, SW_STATE__CLOSED, _strFCU::u32MoveTaskID, and vFCU_BRAKES_CAL__Process().
Referenced by vFCU_BRAKES__Process(), and vFCU_BRAKES_CAL__Process().
Variable Documentation
struct _strFCU sFCU
Referenced by u8FCU_BRAKES_CAL__Is_Busy(), vFCU_BRAKES_CAL__BeginCal(), vFCU_BRAKES_CAL__Init(), and vFCU_BRAKES_CAL__Process().