(C Code, RLOOP, Flight Control Core): FCU__LASER_CONTRAST__TRACK_DATABASE
FCU__LASER_CONTRAST__TRACK_DATABASE
RLOOP » FCU
Functions
void vFCU_LASERCONT_TRKDB__Init (void)
Create the database.
void vFCU_LASERCONT_TRKDB__Process (void)
Process track database systems.
void vFCU_LASERCONT_TRKDB__Inc_Marker (E_FCU__LASER_CONT_INDEX_T eLaser)
Increment the next marker position based on a rising edge from the system.
void vFCU_LASERCONT_TRKDB__Compute (E_FCU__LASER_CONT_INDEX_T eLaser)
Compute the previous track distance Should really only do this on a new marker, but for constatnt CPU loading can do repeateldy.
Luint32 u32FCU_LASERCONT_TRKDB__Get_DistanceElapsed_mm (E_FCU__LASER_CONT_INDEX_T eLaser)
Return the distance that has current elpased.
Luint32 u32FCU_LASERCONT_TRKDB__Get_DistancePrevSeg_mm (E_FCU__LASER_CONT_INDEX_T eLaser)
Gets the distance in the previous 100ft, 30.48m segment.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
Luint32 u32FCU_LASERCONT_TRKDB__Get_DistanceElapsed_mm (E_FCU__LASER_CONT_INDEX_T eLaser)
Return the distance that has current elpased.
Parameters
[in] eLaser Laser Index
SafeTool Function MD5:
0F5DAA0273EF50CD102CD47026CF8B6C
SafeTool Function ID:
LCCM655R0.FILE.041.FUNC.005
References _strFCU::sContrast, sFCU, _strFCU::sTrackDatabase, and _strFCU::u32DistElapsed.
Referenced by vFCU_LASERCONT__Process().
Luint32 u32FCU_LASERCONT_TRKDB__Get_DistancePrevSeg_mm (E_FCU__LASER_CONT_INDEX_T eLaser)
Gets the distance in the previous 100ft, 30.48m segment.
This does not include the distance Over the ripple strips, only full 100ft strips.
Parameters
[in] eLaser The laser index
SafeTool Function MD5:
DC0197FE8B3ADC5DD71049F3419E3E40
SafeTool Function ID:
LCCM655R0.FILE.041.FUNC.006
References _strFCU::sContrast, sFCU, _strFCU::sTrackDatabase, and _strFCU::u32LastIncrement.
Referenced by vFCU_LASERCONT__Process().
void vFCU_LASERCONT_TRKDB__Compute (E_FCU__LASER_CONT_INDEX_T eLaser)
Compute the previous track distance Should really only do this on a new marker, but for constatnt CPU loading can do repeateldy.
Parameters
[in] eLaser Laser Index
SafeTool Function MD5:
FF8FA81B389EEB2F431E86CD917648DA
SafeTool Function ID:
LCCM655R0.FILE.041.FUNC.004
References LASER_CONT__MAX, _strFCU::sContrast, sFCU, _strFCU::sTrackDatabase, _strFCU::u32DistanceElapsed_mm, _strFCU::u32DistElapsed, _strFCU::u32LastIncrement, and _strFCU::u8ElapsedCount.
Referenced by vFCU_LASERCONT__Process().
void vFCU_LASERCONT_TRKDB__Inc_Marker (E_FCU__LASER_CONT_INDEX_T eLaser)
Increment the next marker position based on a rising edge from the system.
Parameters
[in] eLaser The laser index
SafeTool Function MD5:
82CCBDEE1895BD30BA9EC79492F2C184
SafeTool Function ID:
LCCM655R0.FILE.041.FUNC.003
References LASER_CONT__MAX, _strFCU::sContrast, sFCU, _strFCU::sTrackDatabase, and _strFCU::u8ElapsedCount.
Referenced by vFCU_LASERCONT__Process().
void vFCU_LASERCONT_TRKDB__Init (void)
Create the database.
SafeTool Function MD5:
5BCA6D7C693A37A2E92E348B16F52B90
SafeTool Function ID:
LCCM655R0.FILE.041.FUNC.001
References LASER_CONT__MAX, _strFCU::sContrast, sFCU, and _strFCU::sTrackDatabase.
Referenced by vFCU_LASERCONT__Init().
void vFCU_LASERCONT_TRKDB__Process (void)
Process track database systems.
SafeTool Function MD5:
59870A039EA6479C2E49ADD9A7F4EE73
SafeTool Function ID:
LCCM655R0.FILE.041.FUNC.002
Referenced by vFCU_LASERCONT__Process().
Variable Documentation
struct _strFCU sFCU
Referenced by u32FCU_LASERCONT_TRKDB__Get_DistanceElapsed_mm(), u32FCU_LASERCONT_TRKDB__Get_DistancePrevSeg_mm(), vFCU_LASERCONT_TRKDB__Compute(), vFCU_LASERCONT_TRKDB__Inc_Marker(), and vFCU_LASERCONT_TRKDB__Init().