(C Code, RLOOP, Flight Control Core): FCU__ASI__CRC
FCU__ASI__CRC
RLOOP » FCU
Functions
Luint16 u16FCU_ASI_CRC__ComputeCRC (Luint8 *pu8Data, Luint16 u16DataLen)
Compute the CRC.
void vFCU_ASI_CRC__AddCRC (Luint8 *pu8Data)
Add CRC to modbus command frame.
Lint16 s16FCU_ASI_CRC__CheckCRC (Luint8 *pu8Data, Luint8 u8DataLen)
Check CRC from ASI device response.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
Lint16 s16FCU_ASI_CRC__CheckCRC (Luint8 * pu8Data, Luint8 u8DataLen)
Check CRC from ASI device response.
Parameters
[in] u8DataLen Length of data
[in] *pu8Data Pointer to payload
Returns
-1 = error
0 = success
SafeTool Function MD5:
3B9AF9CEEF213072301C15272C0EBDFC
SafeTool Function ID:
LCCM655R0.FILE.071.FUNC.003
References u16FCU_ASI_CRC__ComputeCRC().
Referenced by s16FCU_ASI__ProcessReply().
Luint16 u16FCU_ASI_CRC__ComputeCRC (Luint8 * pu8Data, Luint16 u16DataLen)
Compute the CRC.
Parameters
[in] u16DataLen Length of data
[in] *pu8Data framedParameter
Returns
The returned CRC
SafeTool Function MD5:
1A886073C42670B6EB758BA78DF610D9
SafeTool Function ID:
LCCM655R0.FILE.071.FUNC.001
Referenced by s16FCU_ASI_CRC__CheckCRC(), and vFCU_ASI_CRC__AddCRC().
void vFCU_ASI_CRC__AddCRC (Luint8 * pu8Data)
Add CRC to modbus command frame.
Parameters
[in] *pu8Data framedParameter
SafeTool Function MD5:
4D34D4511E1A72D73DC7388166186BAF
SafeTool Function ID:
LCCM655R0.FILE.071.FUNC.002
References C_ASI__RW_FRAME_SIZE, and u16FCU_ASI_CRC__ComputeCRC().
Referenced by vFCU_ASI__BuildCmdFrame().
Variable Documentation
struct _strFCU sFCU