(C Code, RLOOP, Flight Control Core): FCU__ACCELEROMETER
FCU__ACCELEROMETER
RLOOP » FCU
Functions
void vFCU_ACCEL__Init (void)
Init the accel subsystem layer.
void vFCU_ACCEL__Process (void)
Process the accel's Call as fast as possible from the main loop.
Lint32 s32FCU_ACCELL__Get_CurrentAccel_mmss (Luint8 u8Channel)
Return the current velocity as most recently computed in mm/sec.
Lint32 s32FCU_ACCELL__Get_CurrentVeloc_mms (Luint8 u8Channel)
Return the current velocity as most recently computed in mm/sec.
Lint32 s32FCU_ACCELL__Get_CurrentDisplacement_mm (Luint8 u8Channel)
Return the current displacement.
Lint16 s16FCU_ACCEL__Get_LastSample (Luint8 u8Index, Luint8 u8Axis)
Get the last recorded sample from the Accels.
Lfloat32 f32FCU_ACCEL__Get_LastG (Luint8 u8Index, Luint8 u8Axis)
Get the last G-Force calculated value.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
Lfloat32 f32FCU_ACCEL__Get_LastG (Luint8 u8Index, Luint8 u8Axis)
Get the last G-Force calculated value.
Parameters
[in] u8Axis The axis index
[in] u8Index The accel device index
Returns
The F32 last computed G-Force from each sensor
SafeTool Function MD5:
D4DC470315C624685712D0F05788CC8C
SafeTool Function ID:
LCCM655R0.FILE.010.FUNC.004
References _strFCU::sAccel, _strFCU::sChannels, and sFCU.
Lint16 s16FCU_ACCEL__Get_LastSample (Luint8 u8Index, Luint8 u8Axis)
Get the last recorded sample from the Accels.
Note
If the accels fault out, this value wont update.
Parameters
[in] u8Axis The axis index
[in] u8Index The accel device index
Returns
The S16 last accel value
SafeTool Function MD5:
8BA7DA408E22C09AEF1CAEFD11E12ACF
SafeTool Function ID:
LCCM655R0.FILE.010.FUNC.003
References _strFCU::sAccel, _strFCU::sChannels, and sFCU.
Lint32 s32FCU_ACCELL__Get_CurrentAccel_mmss (Luint8 u8Channel)
Return the current velocity as most recently computed in mm/sec.
Parameters
[in] u8Channel Accel Channel
SafeTool Function MD5:
191B8EC70FB8DA0FCE32BB03F443D0D3
SafeTool Function ID:
LCCM655R0.FILE.010.FUNC.005
References _strFCU::sAccel, _strFCU::sChannels, and sFCU.
Lint32 s32FCU_ACCELL__Get_CurrentDisplacement_mm (Luint8 u8Channel)
Return the current displacement.
Parameters
[in] u8Channel Accel channel
SafeTool Function MD5:
5B659BF07323FD3334B5C7C0E93D8AAD
SafeTool Function ID:
LCCM655R0.FILE.010.FUNC.007
References _strFCU::sAccel, _strFCU::sChannels, and sFCU.
Lint32 s32FCU_ACCELL__Get_CurrentVeloc_mms (Luint8 u8Channel)
Return the current velocity as most recently computed in mm/sec.
Parameters
[in] u8Channel Accel Channel
SafeTool Function MD5:
1157DBB2F10EFDDEA1EEE276145B8F66
SafeTool Function ID:
LCCM655R0.FILE.010.FUNC.006
References _strFCU::sAccel, _strFCU::sChannels, and sFCU.
void vFCU_ACCEL__Init (void)
Init the accel subsystem layer.
SafeTool Function MD5:
46C37AE8833944FB73FC33A8719C9594
SafeTool Function ID:
LCCM655R0.FILE.010.FUNC.001
References C_FCU__ACCEL_FILTER_WINDOW, C_LCCM655__ACCEL__FAULT_INDEX__00, C_LCCM655__ACCEL__FAULT_INDEX__01, _strFCU::sAccel, _strFCU::sChannels, _strFCU::sFaultFlags, sFCU, and vFCU_ACCEL_ETH__Init().
void vFCU_ACCEL__Process (void)
Process the accel's Call as fast as possible from the main loop.
SafeTool Function MD5:
3FC0C3BAE5A3CBF2B906965C1DBDF816
SafeTool Function ID:
LCCM655R0.FILE.010.FUNC.002
References C_FCU__ACCEL_FILTER_WINDOW, C_LCCM655__ACCEL__FAULT_INDEX__00, C_LCCM655__ACCEL__FAULT_INDEX__01, _strFCU::sAccel, _strFCU::sChannels, _strFCU::sFaultFlags, sFCU, vFCU_FCTL_BLENDER__Accel_UpdateFrom_Accel(), vFCU_FCTL_BLENDER__Displacement_UpdateFrom_Accel(), and vFCU_FCTL_BLENDER__Veloc_UpdateFrom_Accel().
Variable Documentation
struct _strFCU sFCU
Referenced by f32FCU_ACCEL__Get_LastG(), s16FCU_ACCEL__Get_LastSample(), s32FCU_ACCELL__Get_CurrentAccel_mmss(), s32FCU_ACCELL__Get_CurrentDisplacement_mm(), s32FCU_ACCELL__Get_CurrentVeloc_mms(), vFCU_ACCEL__Init(), and vFCU_ACCEL__Process().