(C Code, RLOOP, Flight Control Core): FCU__LASER_CONTRAST
FCU__LASER_CONTRAST
RLOOP » FCU
Functions
void vFCU_LASERCONT__Init (void)
Init the contrast laser system.
void vFCU_LASERCONT__Process (void)
Process the laser contrast system.
void vFCU_LASERCONT__Reset (Luint32 u32Key)
Reset the laser contrast system.
void vFCU_LASERCONT__ISR (E_FCU__LASER_CONT_INDEX_T eLaser, Luint32 u32Register)
Interrupt from the RM4 notification system.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
void vFCU_LASERCONT__Init (void)
Init the contrast laser system.
SafeTool Function MD5:
17BB21481013532CE4A1C8E5152D1DB3
SafeTool Function ID:
LCCM655R0.FILE.034.FUNC.001
References LASER_CONT__MAX, _strFCU::sContrast, _strFCU::sFaultFlags, sFCU, _strFCU::sSensors, _strFCU::u32Guard1, _strFCU::u32Guard2, _strFCU::u32Guard3, _strFCU::u32Guard4, vFCU_LASERCONT_TL__Init(), vFCU_LASERCONT_TRKDB__Init(), and vFCU_LASERCONT_VELOC__Init().
void vFCU_LASERCONT__ISR (E_FCU__LASER_CONT_INDEX_T eLaser, Luint32 u32Register)
Interrupt from the RM4 notification system.
Parameters
[in] eLaser The laser index
SafeTool Function MD5:
85A22E789F8036525ED16796EED95EC4
SafeTool Function ID:
LCCM655R0.FILE.034.FUNC.003
References vFCU_LASERCONT_TL__ISR().
void vFCU_LASERCONT__Process (void)
Process the laser contrast system.
SafeTool Function MD5:
5243039BF23965BD12D80A2CE0C8D864
SafeTool Function ID:
LCCM655R0.FILE.034.FUNC.002
References LASER_CONT__MAX, _strFCU::sContrast, sFCU, _strFCU::sSensors, _strFCU::sTimingList, u32FCU_LASERCONT_TRKDB__Get_DistanceElapsed_mm(), u32FCU_LASERCONT_TRKDB__Get_DistancePrevSeg_mm(), u32FCU_LASERCONT_VELOC__Compute(), _strFCU::u32Guard1, _strFCU::u32Guard2, _strFCU::u32Guard3, _strFCU::u32Guard4, u64FCU_LASERCONT_TL__Get_TimeDelta(), u8FCU_LASERCONT_TL__Get_NewRisingAvail(), vFCU_LASERCONT_TL__Clear_NewRisingAvail(), vFCU_LASERCONT_TL__Process(), vFCU_LASERCONT_TRKDB__Compute(), vFCU_LASERCONT_TRKDB__Inc_Marker(), vFCU_LASERCONT_TRKDB__Process(), and vFCU_LASERCONT_VELOC__Process().
void vFCU_LASERCONT__Reset (Luint32 u32Key)
Reset the laser contrast system.
This will need to be done by the flight controller PRIOR to any run.
Parameters
[in] u32Key 0xABCDABCDU
SafeTool Function MD5:
F6F060589AB5BB11032BD32EEAFCCEA0
SafeTool Function ID:
LCCM655R0.FILE.034.FUNC.004
Variable Documentation
struct _strFCU sFCU
Referenced by vFCU_LASERCONT__Init(), and vFCU_LASERCONT__Process().