(C Code, RLOOP, Flight Control Core): FCU_CORE__NOTIFICATIONS
FCU_CORE__NOTIFICATIONS
RLOOP » FCU
Functions
void vRM4_N2HET_DYNAMIC__Notification (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32ProgramIndex, Luint32 u32Register)
Interrupt from N2HET programs.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
void vRM4_N2HET_DYNAMIC__Notification (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32ProgramIndex, Luint32 u32Register)
Interrupt from N2HET programs.
Parameters
[in] u32Register Reg values passed in
[in] u32ProgramIndex N2HET program index
[in] eChannel N2HET Channel
SafeTool Function MD5:
BA3672C0F276685B06058BF6ECA514B1
SafeTool Function ID:
LCCM655R0.FILE.015.FUNC.002
References BRAKE_SW__EXTEND, BRAKE_SW__RETRACT, FCU_BRAKE__RIGHT, LASER_CONT__AFT, LASER_CONT__FWD, LASER_CONT__MID, _strFCU::sBrakes, _strFCU::sContrast, sFCU, _strFCU::sLimits, _strFCU::sPusher, _strFCU::sSensors, _strFCU::sSwitches, vFCU_BRAKES_SW__Right_SwitchExtend_ISR(), vFCU_BRAKES_SW__Right_SwitchRetract_ISR(), vFCU_LASERCONT__ISR(), vFCU_PUSHER__InterlockA_ISR(), and vFCU_PUSHER__InterlockB_ISR().
Variable Documentation
struct _strFCU sFCU
Referenced by vRM4_N2HET_DYNAMIC__Notification().