(C Code, RLOOP, Flight Control Core): FCU__BRAKES__STEPPER
FCU__BRAKES__STEPPER
RLOOP » FCU
Functions
void vFCU_BRAKES_STEP__LimitMove (Lint32 s32Brake0PosIn, Lint32 s32Brake1PosIn, Lint32 *ps32Brake0PosOut, Lint32 *ps32Brake1PosOut)
ToDo.
void vFCU_BRAKES_STEP__Init (void)
Init the stepper interface.
void vFCU_BRAKES_STEP__Process (void)
Process any brake commands.
Lint32 s32FCU_BRAKES__Get_CurrentPos (E_FCU__BRAKE_INDEX_T eBrake)
Returns the current position of the lead screw for the brakes.
void vFCU_BRAKES_STEP__Move (Lint32 s32Brake0Pos, Lint32 s32Brake1Pos)
Move the brakes as a pair to a position based on the lead screw distance.
void vFCU_BRAKES_STEP__UpdateValues (Luint32 u32Brake, Luint32 u32Type, Lint32 s32Value)
ToDo.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
Lint32 s32FCU_BRAKES__Get_CurrentPos (E_FCU__BRAKE_INDEX_T eBrake)
Returns the current position of the lead screw for the brakes.
Parameters
[in] eBrake The brake index
SafeTool Function MD5:
ECB078C68B997C76922FDE710ED8D5BB
SafeTool Function ID:
LCCM655R0.FILE.025.FUNC.003
Referenced by vFCU_BRAKES__Process(), vFCU_BRAKES_CAL__Process(), and vFCU_BRAKES_ETH__MoveMotor_RAW().
void vFCU_BRAKES_STEP__Init (void)
Init the stepper interface.
SafeTool Function MD5:
82EF310377CC37926C5B5B85EBC7540F
SafeTool Function ID:
LCCM655R0.FILE.025.FUNC.001
References C_LCCM655__BRAKES__FAULT_INDEX__00, C_LCCM655__BRAKES__FAULT_INDEX__03, C_LOCALDEF__LCCM655__EEPROM_OFFSET__STEP0_ACCEL, C_LOCALDEF__LCCM655__EEPROM_OFFSET__STEP0_VELOC, C_LOCALDEF__LCCM655__EEPROM_OFFSET__STEP1_ACCEL, C_LOCALDEF__LCCM655__EEPROM_OFFSET__STEP1_VELOC, C_LOCALDEF__LCCM655__EEPROM_OFFSET__STEP_CRC, _strFCU::sBrakes, _strFCU::sBrakesGlobal, _strFCU::sFaultFlags, sFCU, and _strFCU::sMove.
Referenced by vFCU_BRAKES__Init().
void vFCU_BRAKES_STEP__LimitMove (Lint32 s32Brake0PosIn, Lint32 s32Brake1PosIn, Lint32 * ps32Brake0PosOut, Lint32 * ps32Brake1PosOut)
ToDo.
Parameters
[in] ps32Brake1PosOut ## Desc ##
[in] ps32Brake0PosOut ## Desc ##
[in] s32Brake1PosIn ## Desc ##
[in] s32Brake0PosIn ## Desc ##
SafeTool Function MD5:
4F0CAC2E5EDC8F9A8F3EDF9CD8E43534
SafeTool Function ID:
LCCM655R0.FILE.025.FUNC.005
References BRAKE_SW__EXTEND, BRAKE_SW__RETRACT, FCU_BRAKE__LEFT, FCU_BRAKE__RIGHT, _strFCU::sBrakes, sFCU, _strFCU::sLimits, and SW_STATE__CLOSED.
Referenced by vFCU_BRAKES_STEP__Move().
void vFCU_BRAKES_STEP__Move (Lint32 s32Brake0Pos, Lint32 s32Brake1Pos)
Move the brakes as a pair to a position based on the lead screw distance.
Parameters
[in] s32Brake1Pos Microns of brake pos R
[in] s32Brake0Pos Microns on brake pos L
SafeTool Function MD5:
3EA45F9C6480C598FE26185764B0A1F6
SafeTool Function ID:
LCCM655R0.FILE.025.FUNC.004
Unique ID for each task
References _strFCU::sBrakes, _strFCU::sBrakesGlobal, sFCU, _strFCU::sMove, _strFCU::u32MoveTaskID, and vFCU_BRAKES_STEP__LimitMove().
Referenced by vFCU_BRAKES__Process(), and vFCU_BRAKES_ETH__MoveMotor_RAW().
void vFCU_BRAKES_STEP__Process (void)
Process any brake commands.
SafeTool Function MD5:
792382B2C7B93024D59EDDDE0DBD345D
SafeTool Function ID:
LCCM655R0.FILE.025.FUNC.002
void vFCU_BRAKES_STEP__UpdateValues (Luint32 u32Brake, Luint32 u32Type, Lint32 s32Value)
ToDo.
Parameters
[in] s32Value ## Desc ##
[in] u32Type ## Desc ##
[in] u32Brake ## Desc ##
SafeTool Function MD5:
B120DC37AB061A4707E95BB97DE2067E
SafeTool Function ID:
LCCM655R0.FILE.025.FUNC.006
References C_LOCALDEF__LCCM655__EEPROM_OFFSET__STEP0_ACCEL, C_LOCALDEF__LCCM655__EEPROM_OFFSET__STEP0_VELOC, C_LOCALDEF__LCCM655__EEPROM_OFFSET__STEP1_ACCEL, C_LOCALDEF__LCCM655__EEPROM_OFFSET__STEP1_VELOC, C_LOCALDEF__LCCM655__EEPROM_OFFSET__STEP_CRC, _strFCU::sBrakes, sFCU, and _strFCU::sMove.
Referenced by vFCU_NET_RX__RxSafeUDP().
Variable Documentation
struct _strFCU sFCU
Referenced by vFCU_BRAKES_STEP__Init(), vFCU_BRAKES_STEP__LimitMove(), vFCU_BRAKES_STEP__Move(), and vFCU_BRAKES_STEP__UpdateValues().