(C Code, RLOOP, Flight Control Core): FCU__ASI__MUX
FCU__ASI__MUX
RLOOP » FCU
Functions
void vFCU_ASI_MUX__Init (void)
Init the multiplexer.
void vFCU_ASI_MUX__Process (void)
Process any mux tasks.
void vFCU_ASI_MUX__SelectChannel (Luint8 u8ChannelIndex)
Selet the correct channel for the mux.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
void vFCU_ASI_MUX__Init (void)
Init the multiplexer.
SafeTool Function MD5:
E700FA5BEB4A6F0ADA945455A48569E7
SafeTool Function ID:
LCCM655R0.FILE.070.FUNC.001
References _strFCU::sASI, and sFCU.
Referenced by vFCU_ASI__Init().
void vFCU_ASI_MUX__Process (void)
Process any mux tasks.
SafeTool Function MD5:
E69B0009BD94BC2496CA44C7DFDE0154
SafeTool Function ID:
LCCM655R0.FILE.070.FUNC.002
Referenced by vFCU_ASI__Process().
void vFCU_ASI_MUX__SelectChannel (Luint8 u8ChannelIndex)
Selet the correct channel for the mux.
Parameters
[in] u8ChannelIndex The channel index
SafeTool Function MD5:
EB7B3402EC920445295809F30788558B
SafeTool Function ID:
LCCM655R0.FILE.070.FUNC.003
References _strFCU::sASI, sFCU, and u8FCU_ASI_MUX_WIN32__Get().
Referenced by vFCU_ASI__Process().
Variable Documentation
struct _strFCU sFCU
Referenced by vFCU_ASI_MUX__Init(), and vFCU_ASI_MUX__SelectChannel().