(C Code, RLOOP, Flight Control Core): FCU__BRAKES__ETHERNET
FCU__BRAKES__ETHERNET
RLOOP » FCU
Functions
void vFCU_BRAKES_ETH__Init (void)
Init the eth portion of the brakes system.
void vFCU_BRAKES_ETH__Transmit (E_NET__PACKET_T ePacketType)
Process any new eth packets (transmit)
void vFCU_BRAKES_ETH__MoveMotor_RAW (Luint32 u32Index, Lint32 s32Position)
Raw motor position movement.
void vFCU_BRAKES_ETH__MoveMotor_IBeam (Lfloat32 f32Value)
In development mode, move the brakes to an I-Beam distance.
void vFCU_BRAKES_ETH__Start_Calibration (Luint32 u32Key)
Start the calibration mode of the brakes manually.
void vFCU_BRAKES_ETH__MLP_ZeroSpan (Luint32 u32Key0, Luint32 u32Brake, Luint32 u32Function)
Perform a MLP zero or span.
void vFCU_BRAKES_ETH__Enable_DevMode (Luint32 u32Key0, Luint32 u32Key1)
Permit brake development/testing mode.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
void vFCU_BRAKES_ETH__Enable_DevMode (Luint32 u32Key0, Luint32 u32Key1)
Permit brake development/testing mode.
Parameters
[in] u32Key1 Key1 should be 0xABCD0987U
[in] u32Key0 Key0 shoul dbe 0x1293847
SafeTool Function MD5:
F21BB83DD999BFB06DE4C3D53889D9E6
SafeTool Function ID:
LCCM655R0.FILE.007.FUNC.010
References BRAKE_CAL_STATE__COMPLETE, BRAKE_STATE__IDLE, _strFCU::eBrakeStates, _strFCU::sBrakesDev, _strFCU::sBrakesGlobal, _strFCU::sCalibration, _strFCU::sFaultFlags, and sFCU.
Referenced by vFCU_NET_RX__RxSafeUDP().
void vFCU_BRAKES_ETH__Init (void)
Init the eth portion of the brakes system.
SafeTool Function MD5:
3F55F58A66BBC89F7D26261947D1B02E
SafeTool Function ID:
LCCM655R0.FILE.066.FUNC.001
References _strFCU::sBrakesDev, _strFCU::sBrakesGlobal, and sFCU.
Referenced by vFCU_BRAKES__Init().
void vFCU_BRAKES_ETH__MLP_ZeroSpan (Luint32 u32Key0, Luint32 u32Brake, Luint32 u32Function)
Perform a MLP zero or span.
Parameters
[in] u32Function 0 = 0, 1 = span
[in] u32Brake Brake Channel
[in] u32Key0 0x55660123U
SafeTool Function MD5:
F7CBF5117B8E442BBD599BE76CAAC534
SafeTool Function ID:
LCCM655R0.FILE.066.FUNC.012
References vFCU_BRAKES_MLP__ComputeCalibration_Span(), and vFCU_BRAKES_MLP__ComputeCalibration_Zero().
Referenced by vFCU_NET_RX__RxSafeUDP().
void vFCU_BRAKES_ETH__MoveMotor_IBeam (Lfloat32 f32Value)
In development mode, move the brakes to an I-Beam distance.
Parameters
[in] f32Value The distance in mm
SafeTool Function MD5:
AC4FDC65FD7852EEDDD124550F52B0FA
SafeTool Function ID:
LCCM655R0.FILE.066.FUNC.004
References BRAKE_STATE__BEGIN_MOVE, C_FCU__BRAKES__MAX_IBEAM_DIST_MM, C_FCU__BRAKES__MIN_IBEAM_DIST_MM, _strFCU::eBrakeStates, _strFCU::sBrakes, _strFCU::sBrakesDev, _strFCU::sBrakesGlobal, _strFCU::sFaultFlags, sFCU, and _strFCU::sTarget.
Referenced by vFCU_NET_RX__RxSafeUDP().
void vFCU_BRAKES_ETH__MoveMotor_RAW (Luint32 u32Index, Lint32 s32Position)
Raw motor position movement.
Note
Huge caution, this can kill the magnets
Parameters
[in] u32Position The new position in microns
[in] u32Index The motor index
SafeTool Function MD5:
E7ACE5E6A14B23D4226EA1541323229E
SafeTool Function ID:
LCCM655R0.FILE.066.FUNC.003
References FCU_BRAKE__LEFT, FCU_BRAKE__RIGHT, s32FCU_BRAKES__Get_CurrentPos(), _strFCU::sBrakesDev, _strFCU::sBrakesGlobal, _strFCU::sFaultFlags, sFCU, and vFCU_BRAKES_STEP__Move().
Referenced by vFCU_NET_RX__RxSafeUDP().
void vFCU_BRAKES_ETH__Start_Calibration (Luint32 u32Key)
Start the calibration mode of the brakes manually.
Parameters
[in] u32Key Input Key
SafeTool Function MD5:
4DA1A1D8D5E8FA762D3C7B6F399093AC
SafeTool Function ID:
LCCM655R0.FILE.066.FUNC.011
References _strFCU::sBrakesDev, _strFCU::sBrakesGlobal, sFCU, and vFCU_BRAKES_CAL__BeginCal().
void vFCU_BRAKES_ETH__Transmit (E_NET__PACKET_T ePacketType)
Process any new eth packets (transmit)
Parameters
[in] ePacketType The packet type
SafeTool Function MD5:
D5DA6935BF00141E3F4D6C28FE5B72D2
SafeTool Function ID:
LCCM655R0.FILE.066.FUNC.002
References BRAKE_SW__EXTEND, BRAKE_SW__RETRACT, C_LOCALDEF__LCCM231__M0_MAX_ACCELERATION__PARAM_INDEX, C_LOCALDEF__LCCM231__M0_MAX_ANGULAR_VELOCITY__PARAM_INDEX, C_LOCALDEF__LCCM231__M0_MICRONS_PER_REVOLUTION__PARAM_INDEX, C_LOCALDEF__LCCM231__M0_MICROSTEP_RESOLUTION__PARAM_INDEX, C_LOCALDEF__LCCM231__M0_STEPS_PER_REVOLUTION__PARAM_INDEX, C_LOCALDEF__LCCM231__M1_MAX_ACCELERATION__PARAM_INDEX, C_LOCALDEF__LCCM231__M1_MAX_ANGULAR_VELOCITY__PARAM_INDEX, C_LOCALDEF__LCCM231__M1_MICRONS_PER_REVOLUTION__PARAM_INDEX, C_LOCALDEF__LCCM231__M1_MICROSTEP_RESOLUTION__PARAM_INDEX, C_LOCALDEF__LCCM231__M1_STEPS_PER_REVOLUTION__PARAM_INDEX, C_RLOOP_NET__FCU__PORT, _strFCU::eBrakeStates, FCU_BRAKE__MAX_BRAKES, NET_PKT__FCU_BRAKES__TX_DATA, NET_PKT__FCU_BRAKES__TX_MOTOR_PARAM, _strFCU::sBrakes, _strFCU::sBrakesGlobal, _strFCU::sCalibration, _strFCU::sCurrent, _strFCU::sFaultFlags, sFCU, _strFCU::sLimits, _strFCU::sMLP, _strFCU::sMove, _strFCU::sTarget, and _strFCU::u8BrakeSWErr.
Referenced by vFCU_NET_TX__Process().
Variable Documentation
struct _strFCU sFCU
Referenced by vFCU_BRAKES_ETH__Enable_DevMode(), vFCU_BRAKES_ETH__Init(), vFCU_BRAKES_ETH__MoveMotor_IBeam(), vFCU_BRAKES_ETH__MoveMotor_RAW(), vFCU_BRAKES_ETH__Start_Calibration(), and vFCU_BRAKES_ETH__Transmit().