(C Code, RLOOP, Flight Control Core): FCU__THROTTLE__ETHERNET
FCU__THROTTLE__ETHERNET
RLOOP » FCU
Functions
void vFCU_THROTTLE_ETH__Init (void)
Init the throttle eth layer.
void vFCU_THROTTLE_ETH__Transmit (E_NET__PACKET_T ePacketType)
Send a throttle eth packet.
void vFCU_THROTTLE_ETH__Enable_DevMode (Luint32 u32Key0, Luint32 u32Key1)
safely switch on dev mode
void vFCU_THROTTLE_ETH__Set_Throttle (Luint8 u8EngineIndex, Luint16 u16RPM, E_THROTTLE_CTRL_T eRampType)
Manually set the throttle via the Ethernet.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
void vFCU_THROTTLE_ETH__Enable_DevMode (Luint32 u32Key0, Luint32 u32Key1)
safely switch on dev mode
Parameters
[in] u32Key1 0x77558833U
[in] u32Key0 0x11223344U
SafeTool Function MD5:
56200DBE406D716414B25D3E50E01130
SafeTool Function ID:
LCCM655R0.FILE.073.FUNC.003
References _strFCU::strThrottleInterfaceData::sDevMode, sFCU, _strFCU::sThrottle, _strFCU::strThrottleInterfaceData::u32SecurityKey, _strFCU::strThrottleInterfaceData::u8Enabled, and vFCU_THROTTLE__Enable_Run().
Referenced by vFCU_NET_RX__RxSafeUDP().
void vFCU_THROTTLE_ETH__Init (void)
Init the throttle eth layer.
SafeTool Function MD5:
9668C2BF99BB9AE8A102370F75A04DE1
SafeTool Function ID:
LCCM655R0.FILE.073.FUNC.001
void vFCU_THROTTLE_ETH__Set_Throttle (Luint8 u8EngineIndex, Luint16 u16RPM, E_THROTTLE_CTRL_T eRampType)
Manually set the throttle via the Ethernet.
Parameters
[in] eRampType The type of throttle ramp
[in] u16RPM Required RPM
[in] u8EngineIndex 0-7 or 8 for all HE's
SafeTool Function MD5:
BB2011B91C798224E1C974D5299AE804
SafeTool Function ID:
LCCM655R0.FILE.073.FUNC.004
References C_FCU__NUM_HOVER_ENGINES, _strFCU::strThrottleInterfaceData::eRequestedMode, _strFCU::strThrottleInterfaceData::sDevMode, sFCU, _strFCU::sThrottle, _strFCU::strThrottleInterfaceData::u16RequestedRPM, _strFCU::u16RPM, _strFCU::strThrottleInterfaceData::u32SecurityKey, and _strFCU::strThrottleInterfaceData::u8Enabled.
Referenced by vFCU_NET_RX__RxSafeUDP().
void vFCU_THROTTLE_ETH__Transmit (E_NET__PACKET_T ePacketType)
Send a throttle eth packet.
Parameters
[in] ePacketType Packet Type
SafeTool Function MD5:
2E572263EF697DB1F6C4A1DAF679B5C0
SafeTool Function ID:
LCCM655R0.FILE.073.FUNC.002
References C_FCU__NUM_HOVER_ENGINES, C_RLOOP_NET__FCU__PORT, _strFCU::strThrottleInterfaceData::eState, NET_PKT__FCU_THROTTLE__TX_DATA, _strFCU::strThrottleInterfaceData::sFaultFlags, sFCU, _strFCU::sThrottle, _strFCU::strThrottleInterfaceData::u16CurrentRPM, _strFCU::strThrottleInterfaceData::u16RequestedRPM, and _strFCU::strThrottleInterfaceData::u8RunIndex.
Referenced by vFCU_NET_TX__Process().
Variable Documentation
struct _strFCU sFCU
Referenced by vFCU__Init(), vFCU__Process(), vFCU_THROTTLE_ETH__Enable_DevMode(), vFCU_THROTTLE_ETH__Set_Throttle(), and vFCU_THROTTLE_ETH__Transmit().