(C Code, RLOOP, Flight Control Core): FCU__BRAKES__WDT
FCU__BRAKES__WDT
RLOOP » FCU
Functions
void vFCU_BRAKES_WDT__Init (void)
Init the watchdog pin.
void vFCU_BRAKES_WDT__Pet_Start (void)
Start of the petting process.
void vFCU_BRAKES_WDT__Pet_End (void)
End the petting process.
Detailed Description
Function Documentation
void vFCU_BRAKES_WDT__Init (void)
Init the watchdog pin.
SafeTool Function MD5:
2A6A849F0C0A65507AE323B59ED254B5
SafeTool Function ID:
LCCM655R0.FILE.069.FUNC.001
Referenced by vFCU_BRAKES__Init().
void vFCU_BRAKES_WDT__Pet_End (void)
End the petting process.
SafeTool Function MD5:
22F611F2F8924BE1EB7A40847B2A08AF
SafeTool Function ID:
LCCM655R0.FILE.069.FUNC.003
Referenced by vFCU_BRAKES__Process().
void vFCU_BRAKES_WDT__Pet_Start (void)
Start of the petting process.
SafeTool Function MD5:
52C02FF2376AF87C4369251C7EE571F1
SafeTool Function ID:
LCCM655R0.FILE.069.FUNC.002
Referenced by vFCU_BRAKES__Process().