(C Code, RLOOP, Flight Control Core): FCU__BRAKES
FCU__BRAKES
RLOOP » FCU
Functions
void vFCU_BRAKES__Init (void)
Init any brakes variables, etc.
void vFCU_BRAKES__Process (void)
Process any brakes tasks.
void vFCU_BRAKES__Begin_Init (Luint32 u32Key)
must start calibration from the ground station to put the brakes into a mode where they can be used.
Lfloat32 f32FCU_BRAKES__Get_ScrewPos (E_FCU__BRAKE_INDEX_T eBrake)
Gets the computed screw position.
E_FCU__SWITCH_STATE_T eFCU_BRAKES__Get_SwtichState (E_FCU__BRAKE_INDEX_T eBrake, E_FCU__BRAKE_LIMSW_INDEX_T eSwitch)
Returns the brake switch state.
Luint16 u16FCU_BRAKES__Get_ADC_Raw (E_FCU__BRAKE_INDEX_T eBrake)
Get the RAW ADC values.
Lfloat32 f32FCU_BRAKES__Get_IBeam_mm (E_FCU__BRAKE_INDEX_T eBrake)
Get the distance between the brake and the I-Beam.
Lfloat32 f32FCU_BRAKES__Get_MLP_mm (E_FCU__BRAKE_INDEX_T eBrake)
Get the computed MLP measurement.
void vFCU_BRAKES__Move_IBeam_Distance_mm (Lfloat32 f32Distance)
Move the brakes to a distance in microns from the I Beam.
Variables
struct _strFCU sFCU
Detailed Description
Function Documentation
E_FCU__SWITCH_STATE_T eFCU_BRAKES__Get_SwtichState (E_FCU__BRAKE_INDEX_T eBrake, E_FCU__BRAKE_LIMSW_INDEX_T eSwitch)
Returns the brake switch state.
Test Specifications:
LCCM655R0.TS.000
Parameters
[in] eSwitch The switch type
[in] eBrake The brake index
SafeTool Function MD5:
458791C58F924A8B4F72976BC03CD51D
SafeTool Function ID:
LCCM655R0.FILE.007.FUNC.004
References _strFCU::sBrakes, sFCU, and _strFCU::sLimits.
Lfloat32 f32FCU_BRAKES__Get_IBeam_mm (E_FCU__BRAKE_INDEX_T eBrake)
Get the distance between the brake and the I-Beam.
Parameters
[in] eBrake The brake index
SafeTool Function MD5:
26D65B8A8047383128E9ED614EEF4349
SafeTool Function ID:
LCCM655R0.FILE.007.FUNC.006
References _strFCU::sBrakes, _strFCU::sCurrent, and sFCU.
Lfloat32 f32FCU_BRAKES__Get_MLP_mm (E_FCU__BRAKE_INDEX_T eBrake)
Get the computed MLP measurement.
Parameters
[in] eBrake The brake index
SafeTool Function MD5:
822B17DF4905F7682819FF79F9101BBB
SafeTool Function ID:
LCCM655R0.FILE.007.FUNC.007
References _strFCU::sBrakes, _strFCU::sCurrent, and sFCU.
Lfloat32 f32FCU_BRAKES__Get_ScrewPos (E_FCU__BRAKE_INDEX_T eBrake)
Gets the computed screw position.
Parameters
[in] eBrake The brake index
SafeTool Function MD5:
9CBBBE5E8D057A34CAE54C50F502D802
SafeTool Function ID:
LCCM655R0.FILE.007.FUNC.003
References _strFCU::sBrakes, _strFCU::sCurrent, and sFCU.
Luint16 u16FCU_BRAKES__Get_ADC_Raw (E_FCU__BRAKE_INDEX_T eBrake)
Get the RAW ADC values.
Parameters
[in] eBrake The brake index
SafeTool Function MD5:
8BA9CA2F3074B6DB93DAD5CAA61B4C01
SafeTool Function ID:
LCCM655R0.FILE.007.FUNC.005
References _strFCU::sBrakes, sFCU, and _strFCU::sMLP.
void vFCU_BRAKES__Begin_Init (Luint32 u32Key)
must start calibration from the ground station to put the brakes into a mode where they can be used.
Parameters
[in] u32Key 0x98765432U
SafeTool Function MD5:
EE29EBB23A41C03E43DD253219CFD50C
SafeTool Function ID:
LCCM655R0.FILE.007.FUNC.009
References BRAKE_STATE__BEGIN_CAL, BRAKE_STATE__RESET, _strFCU::eBrakeStates, _strFCU::sBrakesGlobal, _strFCU::sFaultFlags, and sFCU.
Referenced by vFCU_NET_RX__RxSafeUDP().
void vFCU_BRAKES__Init (void)
Init any brakes variables, etc.
SafeTool Function MD5:
3D9494F427A4EB2AE2B6114DF7D00A20
SafeTool Function ID:
LCCM655R0.FILE.007.FUNC.001
References BRAKE_STATE__RESET, C_FCU__NUM_BRAKES, _strFCU::eBrakeStates, _strFCU::sBrakes, _strFCU::sBrakesGlobal, _strFCU::sCurrent, _strFCU::sFaultFlags, sFCU, _strFCU::sTarget, _strFCU::u32MoveTaskID, vFCU_BRAKES_CAL__Init(), vFCU_BRAKES_ETH__Init(), vFCU_BRAKES_MLP__Init(), vFCU_BRAKES_STEP__Init(), and vFCU_BRAKES_SW__Init().
Referenced by vFCU_MAINSM__Process().
void vFCU_BRAKES__Move_IBeam_Distance_mm (Lfloat32 f32Distance)
Move the brakes to a distance in microns from the I Beam.
Note
Approx distances are 25,000 um (fully open) to 0um (fully closed)
Parameters
[in] u32Distance The distance in microns
SafeTool Function MD5:
609D069BE1337B6F02723640B571D4A9
SafeTool Function ID:
LCCM655R0.FILE.007.FUNC.008
References BRAKE_STATE__BEGIN_MOVE, BRAKE_STATE__IDLE, C_FCU__BRAKES__MAX_IBEAM_DIST_MM, C_FCU__BRAKES__MIN_IBEAM_DIST_MM, _strFCU::eBrakeStates, _strFCU::f32Distance, _strFCU::sBrakes, _strFCU::sBrakesDev, _strFCU::sBrakesGlobal, sFCU, and _strFCU::sTarget.
void vFCU_BRAKES__Process (void)
Process any brakes tasks.
SafeTool Function MD5:
EDC5BB6DF3DEAFBBC82B5F0EC21A7137
SafeTool Function ID:
LCCM655R0.FILE.007.FUNC.002
References BRAKE_STATE__BEGIN_CAL, BRAKE_STATE__BEGIN_MOVE, BRAKE_STATE__COMPUTE, BRAKE_STATE__FAULT, BRAKE_STATE__IDLE, BRAKE_STATE__MOVE_STOPPED, BRAKE_STATE__MOVING, BRAKE_STATE__RESET, BRAKE_STATE__WAIT_CAL_DONE, _strFCU::eBrakeStates, FCU_BRAKE__LEFT, FCU_BRAKE__MAX_BRAKES, FCU_BRAKE__RIGHT, s32FCU_BRAKES__Get_CurrentPos(), _strFCU::sBrakes, _strFCU::sBrakesGlobal, _strFCU::sFaultFlags, sFCU, _strFCU::sMove, _strFCU::sTarget, u8FCU_BRAKES_CAL__Is_Busy(), vFCU_BRAKES_CAL__BeginCal(), vFCU_BRAKES_CAL__Process(), vFCU_BRAKES_MLP__Process(), vFCU_BRAKES_STEP__Move(), and vFCU_BRAKES_SW__Process().
Referenced by vFCU_MAINSM__Process().
Variable Documentation
struct _strFCU sFCU
Referenced by eFCU_BRAKES__Get_SwtichState(), f32FCU_BRAKES__Get_IBeam_mm(), f32FCU_BRAKES__Get_MLP_mm(), f32FCU_BRAKES__Get_ScrewPos(), u16FCU_BRAKES__Get_ADC_Raw(), vFCU_BRAKES__Begin_Init(), vFCU_BRAKES__Init(), vFCU_BRAKES__Move_IBeam_Distance_mm(), and vFCU_BRAKES__Process().