/**
 * @file		rm4_mibspi135__localdef.h
 * @brief		Local defintions for SPI135
 * @author		Lachlan Grogan
 * @copyright	This file contains proprietary and confidential information of
 *				SIL3 Pty. Ltd. (ACN 123 529 064). This code may be distributed
 *				under a license from SIL3 Pty. Ltd., and may be used, copied
 *				and/or disclosed only pursuant to the terms of that license agreement.
 *				This copyright notice must be retained as part of this file at all times.
 * @copyright	This file is copyright SIL3 Pty. Ltd. 2003-2016, All Rights Reserved.
 * @st_fileID	LCCM280R0.FILE.003
 */
#if 0

/*******************************************************************************
RM4 MiB SPI 1,3 and 5 Common Driver
*******************************************************************************/
	#define C_LOCALDEF__LCCM280__ENABLE_THIS_MODULE							(1U)
	#if C_LOCALDEF__LCCM280__ENABLE_THIS_MODULE == 1U

		//enable specific channels
		#define C_LOCALDEF__LCCM280__ENABLE_MIBSPI_1						(1U)
		#define C_LOCALDEF__LCCM280__ENABLE_MIBSPI_3						(1U)
		#define C_LOCALDEF__LCCM280__ENABLE_MIBSPI_5						(1U)

		//set to 1 to use interrupts
		#define C_LOCALDEF__LCCM280__ENABLE_INTERRUPTS						(1U)

		//setup the data formats
		#if C_LOCALDEF__LCCM280__ENABLE_MIBSPI_1 == 1U

			#define C_LOCALDEF__LCCM280__ENABLE_MULTIBUFFERED_MODE_1		(0U)

			//the transfer length of up to 16 bits
			#define C_LOCALDEF__LCCM280__MIBSPI_1__DATAFMT_0__TXLEN_BITS	MIBSPI135_DATAFORMAT__8BITS
			#define C_LOCALDEF__LCCM280__MIBSPI_1__DATAFMT_1__TXLEN_BITS	MIBSPI135_DATAFORMAT__8BITS
			#define C_LOCALDEF__LCCM280__MIBSPI_1__DATAFMT_2__TXLEN_BITS	MIBSPI135_DATAFORMAT__8BITS
			#define C_LOCALDEF__LCCM280__MIBSPI_1__DATAFMT_3__TXLEN_BITS	MIBSPI135_DATAFORMAT__8BITS

			//set the speed of each format
			#define C_LOCALDEF__LCCM280__MIBSPI_1__DATAFMT_0__SPEED			MIBSPI135_SPEED__5MHZ
			#define C_LOCALDEF__LCCM280__MIBSPI_1__DATAFMT_1__SPEED			MIBSPI135_SPEED__5MHZ
			#define C_LOCALDEF__LCCM280__MIBSPI_1__DATAFMT_2__SPEED			MIBSPI135_SPEED__5MHZ
			#define C_LOCALDEF__LCCM280__MIBSPI_1__DATAFMT_3__SPEED			MIBSPI135_SPEED__5MHZ

			//clock phase
			#define C_LOCALDEF__LCCM280__MIBSPI_1__DATAFMT_0__CPHA			MIBSPI135_CPHA__1
			#define C_LOCALDEF__LCCM280__MIBSPI_1__DATAFMT_1__CPHA			MIBSPI135_CPHA__1
			#define C_LOCALDEF__LCCM280__MIBSPI_1__DATAFMT_2__CPHA			MIBSPI135_CPHA__1
			#define C_LOCALDEF__LCCM280__MIBSPI_1__DATAFMT_3__CPHA			MIBSPI135_CPHA__1

			//clock polarity
			#define C_LOCALDEF__LCCM280__MIBSPI_1__DATAFMT_0__CPOL			MIBSPI135_CPOL__0
			#define C_LOCALDEF__LCCM280__MIBSPI_1__DATAFMT_1__CPOL			MIBSPI135_CPOL__0
			#define C_LOCALDEF__LCCM280__MIBSPI_1__DATAFMT_2__CPOL			MIBSPI135_CPOL__0
			#define C_LOCALDEF__LCCM280__MIBSPI_1__DATAFMT_3__CPOL			MIBSPI135_CPOL__0


		#endif //C_LOCALDEF__LCCM280__ENABLE_MIBSPI_1

		#if C_LOCALDEF__LCCM280__ENABLE_MIBSPI_3 == 1U

			#define C_LOCALDEF__LCCM280__ENABLE_MULTIBUFFERED_MODE_3		(0U)

			//pinmux options
			//Enable in place of GIO B2
			#define C_LOCALDEF__LCCM280__ENABLE_PIN__MIBSPI3_NCS0			(0U)

			//the transfer length of up to 16 bits
			#define C_LOCALDEF__LCCM280__MIBSPI_3__DATAFMT_0__TXLEN_BITS	MIBSPI135_DATAFORMAT__8BITS
			#define C_LOCALDEF__LCCM280__MIBSPI_3__DATAFMT_1__TXLEN_BITS	MIBSPI135_DATAFORMAT__8BITS
			#define C_LOCALDEF__LCCM280__MIBSPI_3__DATAFMT_2__TXLEN_BITS	MIBSPI135_DATAFORMAT__8BITS
			#define C_LOCALDEF__LCCM280__MIBSPI_3__DATAFMT_3__TXLEN_BITS	MIBSPI135_DATAFORMAT__8BITS

			//set the speed of each format
			#define C_LOCALDEF__LCCM280__MIBSPI_3__DATAFMT_0__SPEED			MIBSPI135_SPEED__5MHZ
			#define C_LOCALDEF__LCCM280__MIBSPI_3__DATAFMT_1__SPEED			MIBSPI135_SPEED__5MHZ
			#define C_LOCALDEF__LCCM280__MIBSPI_3__DATAFMT_2__SPEED			MIBSPI135_SPEED__5MHZ
			#define C_LOCALDEF__LCCM280__MIBSPI_3__DATAFMT_3__SPEED			MIBSPI135_SPEED__5MHZ

			//clock phase
			#define C_LOCALDEF__LCCM280__MIBSPI_3__DATAFMT_0__CPHA			MIBSPI135_CPHA__1
			#define C_LOCALDEF__LCCM280__MIBSPI_3__DATAFMT_1__CPHA			MIBSPI135_CPHA__1
			#define C_LOCALDEF__LCCM280__MIBSPI_3__DATAFMT_2__CPHA			MIBSPI135_CPHA__1
			#define C_LOCALDEF__LCCM280__MIBSPI_3__DATAFMT_3__CPHA			MIBSPI135_CPHA__1

		#endif //C_LOCALDEF__LCCM280__ENABLE_MIBSPI_3

		#if C_LOCALDEF__LCCM280__ENABLE_MIBSPI_5 == 1U

			#define C_LOCALDEF__LCCM280__ENABLE_MULTIBUFFERED_MODE_5		(0U)

			//the transfer length of up to 16 bits
			#define C_LOCALDEF__LCCM280__MIBSPI_5__DATAFMT_0__TXLEN_BITS	MIBSPI135_DATAFORMAT__8BITS
			#define C_LOCALDEF__LCCM280__MIBSPI_5__DATAFMT_1__TXLEN_BITS	MIBSPI135_DATAFORMAT__8BITS
			#define C_LOCALDEF__LCCM280__MIBSPI_5__DATAFMT_2__TXLEN_BITS	MIBSPI135_DATAFORMAT__8BITS
			#define C_LOCALDEF__LCCM280__MIBSPI_5__DATAFMT_3__TXLEN_BITS	MIBSPI135_DATAFORMAT__8BITS

			//set the speed of each format
			#define C_LOCALDEF__LCCM280__MIBSPI_5__DATAFMT_0__SPEED			MIBSPI135_SPEED__5MHZ
			#define C_LOCALDEF__LCCM280__MIBSPI_5__DATAFMT_1__SPEED			MIBSPI135_SPEED__5MHZ
			#define C_LOCALDEF__LCCM280__MIBSPI_5__DATAFMT_2__SPEED			MIBSPI135_SPEED__5MHZ
			#define C_LOCALDEF__LCCM280__MIBSPI_5__DATAFMT_3__SPEED			MIBSPI135_SPEED__5MHZ

			//clock phase
			#define C_LOCALDEF__LCCM280__MIBSPI_5__DATAFMT_0__CPHA			MIBSPI135_CPHA__1
			#define C_LOCALDEF__LCCM280__MIBSPI_5__DATAFMT_1__CPHA			MIBSPI135_CPHA__1
			#define C_LOCALDEF__LCCM280__MIBSPI_5__DATAFMT_2__CPHA			MIBSPI135_CPHA__1
			#define C_LOCALDEF__LCCM280__MIBSPI_5__DATAFMT_3__CPHA			MIBSPI135_CPHA__1

		#endif //C_LOCALDEF__LCCM280__ENABLE_MIBSPI_5

		/** Tesing Options */
		#define C_LOCALDEF__LCCM280__ENABLE_TEST_SPEC						(0U)

		//main include file
		#include <RM4/LCCM280__RM4__MIBSPI_135/rm4_mibspi135.h>

	#endif //C_LOCALDEF__LCCM280__ENABLE_THIS_MODULE


#endif //0

