(C Code, RLOOP, Aux Prop Unit): AUXPROP__ETHERNET
AUXPROP__ETHERNET
RLOOP » AUXPROP
Functions
void vAPU_ETH__Transmit (E_NET__PACKET_T ePacketType)
Transmit an eth packet.
void vAPU_ETH__Init (void)
Init the enthernet.
void vAPU_ETH__Process (void)
Process any ethernet tasks.
Luint8 u8APU_ETH__Is_LinkUp (void)
Is the eth link avail?
void vAPU_ETH__RxUDP (Luint8 *pu8Buffer, Luint16 u16Length, Luint16 u16DestPort)
RX a UDP packet off the ethernet stack.
void vAPU_ETH__RxSafeUDP (Luint8 *pu8Payload, Luint16 u16PayloadLength, Luint16 ePacketType, Luint16 u16DestPort, Luint16 u16Fault)
Rx a safety udp packet.
void vAPU_ETH__10MS_ISR (void)
10ms timer for the ethernet
Variables
TS_APU__MAIN sAPU
Detailed Description
Function Documentation
Luint8 u8APU_ETH__Is_LinkUp (void)
Is the eth link avail?
SafeTool Function MD5:
2D30B22DD544C659949B2EBCA8601D11
SafeTool Function ID:
LCCM720R0.FILE.011.FUNC.003
Referenced by vAPU_ETH__Process().
void vAPU_ETH__10MS_ISR (void)
10ms timer for the ethernet
SafeTool Function MD5:
E5AFAA1E421A61627136E6014A02626F
SafeTool Function ID:
LCCM720R0.FILE.011.FUNC.007
References TS_APU__MAIN::sUDPDiag, TS_APU__MAIN::u810MS_Flag, and TS_APU__MAIN::u8250MS_Flag.
Referenced by vAPU_TIMERS__10MS_ISR().
void vAPU_ETH__Init (void)
Init the enthernet.
SafeTool Function MD5:
245D6374D9C6798FA045BF18B64D19D1
SafeTool Function ID:
LCCM720R0.FILE.011.FUNC.001
References TS_APU__MAIN::eTxStreamingType, TS_APU__MAIN::sEthernet, TS_APU__MAIN::sUDPDiag, TS_APU__MAIN::u810MS_Flag, TS_APU__MAIN::u8250MS_Flag, TS_APU__MAIN::u8IPAddx, and TS_APU__MAIN::u8MACAddx.
Referenced by vAPU__Init().
void vAPU_ETH__Process (void)
Process any ethernet tasks.
SafeTool Function MD5:
B1C72E9D3E451E3D44C39A83C5681A7A
SafeTool Function ID:
LCCM720R0.FILE.011.FUNC.002
References TS_APU__MAIN::eTxStreamingType, TS_APU__MAIN::sUDPDiag, TS_APU__MAIN::u810MS_Flag, TS_APU__MAIN::u8250MS_Flag, u8APU_ETH__Is_LinkUp(), and vAPU_ETH__Transmit().
Referenced by vAPU__Process().
void vAPU_ETH__RxSafeUDP (Luint8 * pu8Payload, Luint16 u16PayloadLength, Luint16 ePacketType, Luint16 u16DestPort, Luint16 u16Fault)
Rx a safety udp packet.
Parameters
[in] u16Fault Fault types
[in] u16DestPort Target port
[in] ePacketType Packet type
[in] u16PayloadLength Length of payload
[in] *pu8Payload Pointer to payload
SafeTool Function MD5:
E05CE7EB54B2F6532875CC93B6DAB7BD
SafeTool Function ID:
LCCM720R0.FILE.011.FUNC.005
References vAPU_CLUTCH__Disengage(), vAPU_CLUTCH__Engage(), vAPU_THROTTLE__Disable(), vAPU_THROTTLE__Enable(), vAPU_THROTTLE__Forward(), vAPU_THROTTLE__Reverse(), and vAPU_THROTTLE__Set_Velocity_mms().
void vAPU_ETH__RxUDP (Luint8 * pu8Buffer, Luint16 u16Length, Luint16 u16DestPort)
RX a UDP packet off the ethernet stack.
Parameters
[in] u16DestPort Target port
[in] u16Length Payload length
[in] *pu8Buffer Pointer to the payload
SafeTool Function MD5:
B846CEA87A9BE58828F4027FF8D670A6
SafeTool Function ID:
LCCM720R0.FILE.011.FUNC.004
void vAPU_ETH__Transmit (E_NET__PACKET_T ePacketType)
Transmit an eth packet.
Parameters
[in] ePacketType Eth packet type
SafeTool Function MD5:
B198479C8F088A04FF82D4215B4935DB
SafeTool Function ID:
LCCM720R0.FILE.011.FUNC.006
Referenced by vAPU_ETH__Process().
Variable Documentation
TS_APU__MAIN sAPU