(C Code, RLOOP, Aux Prop Unit): AUXPROP__THROTTLE
AUXPROP__THROTTLE
RLOOP » AUXPROP
Functions
void vAPU_THROTTLE__Init (void)
Init the throttles.
void vAPU_THROTTLE__Process (void)
Process any throttle tasks.
void vAPU_THROTTLE__Set_Velocity_mms (Luint32 u32Veloc_mms)
Sets the velocity.
void vAPU_THROTTLE__Forward (void)
Set direction forward.
void vAPU_THROTTLE__Reverse (void)
Set direction in reverse.
void vAPU_THROTTLE__Enable (void)
Enable the motor.
void vAPU_THROTTLE__Disable (void)
Disable the motor.
Variables
TS_APU__MAIN sAPU
Detailed Description
Function Documentation
void vAPU_THROTTLE__Disable (void)
Disable the motor.
SafeTool Function MD5:
DA3A68EBFEBAAF31186C99D255BC42B4
SafeTool Function ID:
LCCM720R0.FILE.006.FUNC.006
References TS_APU__MAIN::eEnable, TS_APU__MAIN::sThrottle, and THROTTLE_ENA__DISABLED.
Referenced by vAPU_ETH__RxSafeUDP(), and vAPU_THROTTLE__Init().
void vAPU_THROTTLE__Enable (void)
Enable the motor.
SafeTool Function MD5:
9F19C707642E67D5DF1D7736BDF1DFDE
SafeTool Function ID:
LCCM720R0.FILE.006.FUNC.005
References TS_APU__MAIN::eEnable, TS_APU__MAIN::sThrottle, and THROTTLE_ENA__ENABLED.
Referenced by vAPU_ETH__RxSafeUDP().
void vAPU_THROTTLE__Forward (void)
Set direction forward.
SafeTool Function MD5:
A94C4E22E13B755B2FBD72B17913DB8F
SafeTool Function ID:
LCCM720R0.FILE.006.FUNC.003
References TS_APU__MAIN::eDirection, TS_APU__MAIN::sThrottle, and THROTTLE_DIR__FORWARD.
Referenced by vAPU_ETH__RxSafeUDP(), and vAPU_THROTTLE__Init().
void vAPU_THROTTLE__Init (void)
Init the throttles.
SafeTool Function MD5:
95B216A7663D18DBE6E204A91AFC15E8
SafeTool Function ID:
LCCM720R0.FILE.006.FUNC.001
References TS_APU__MAIN::eDirection, TS_APU__MAIN::sThrottle, THROTTLE_DIR__FORWARD, TS_APU__MAIN::u16N2HET_Index, TS_APU__MAIN::u32Frequency, vAPU_THROTTLE__Disable(), vAPU_THROTTLE__Forward(), and vAPU_THROTTLE__Set_Velocity_mms().
Referenced by vAPU__Init().
void vAPU_THROTTLE__Process (void)
Process any throttle tasks.
SafeTool Function MD5:
CC3ECF35746BBD3ECC3130220E396FAB
SafeTool Function ID:
LCCM720R0.FILE.006.FUNC.002
void vAPU_THROTTLE__Reverse (void)
Set direction in reverse.
SafeTool Function MD5:
C3CCD4DB59AE6CF746A901B85FA4DC63
SafeTool Function ID:
LCCM720R0.FILE.006.FUNC.004
References TS_APU__MAIN::eDirection, TS_APU__MAIN::sThrottle, and THROTTLE_DIR__REVERSE.
Referenced by vAPU_ETH__RxSafeUDP().
void vAPU_THROTTLE__Set_Velocity_mms (Luint32 u32Veloc_mms)
Sets the velocity.
Parameters
[in] u32Veloc_mms Veloc in mm/sec
SafeTool Function MD5:
DBF39EC993F3F976F8FE7DA3FCD67825
SafeTool Function ID:
LCCM720R0.FILE.006.FUNC.007
References TS_APU__MAIN::sThrottle, TS_APU__MAIN::u16N2HET_Index, and TS_APU__MAIN::u32Frequency.
Referenced by vAPU_ETH__RxSafeUDP(), and vAPU_THROTTLE__Init().
Variable Documentation
TS_APU__MAIN sAPU