(C Code, RLOOP, Aux Prop Unit): AUXPROP__CLUTCH
AUXPROP__CLUTCH
RLOOP » AUXPROP
Functions
void vAPU_CLUTCH__Init (void)
Init the clutch.
void vAPU_CLUTCH__Process (void)
Process any clutch functions.
void vAPU_CLUTCH__Engage (TE_RLOOP_AUXPROP__SIDE eSide)
Engage the clutch.
void vAPU_CLUTCH__Disengage (TE_RLOOP_AUXPROP__SIDE eSide)
Disengage the clutch.
Variables
TS_APU__MAIN sAPU
Detailed Description
Function Documentation
void vAPU_CLUTCH__Disengage (TE_RLOOP_AUXPROP__SIDE eSide)
Disengage the clutch.
Parameters
[in] eSide Side of the pod, left or right
SafeTool Function MD5:
4CA54DF38A5A2150A068EF1B6DC0B6F9
SafeTool Function ID:
LCCM720R0.FILE.010.FUNC.004
References AUXPROP_SIDE__LEFT, AUXPROP_SIDE__RIGHT, CLUTCH_STATE__DISENGAGED, TS_APU__MAIN::sClutch, and TS_APU__MAIN::u8State.
Referenced by vAPU_CLUTCH__Init(), and vAPU_ETH__RxSafeUDP().
void vAPU_CLUTCH__Engage (TE_RLOOP_AUXPROP__SIDE eSide)
Engage the clutch.
Parameters
[in] eSide Side of the pod, left or right
SafeTool Function MD5:
C27E1A9932AB7414147242E44D0CBEB5
SafeTool Function ID:
LCCM720R0.FILE.010.FUNC.003
References AUXPROP_SIDE__LEFT, AUXPROP_SIDE__RIGHT, CLUTCH_STATE__ENGAGED, TS_APU__MAIN::sClutch, and TS_APU__MAIN::u8State.
Referenced by vAPU_ETH__RxSafeUDP().
void vAPU_CLUTCH__Init (void)
Init the clutch.
SafeTool Function MD5:
A9C4EFDFE2796F7B98FCE5E1CAAA5E0D
SafeTool Function ID:
LCCM720R0.FILE.010.FUNC.001
References AUXPROP_SIDE__LEFT, AUXPROP_SIDE__RIGHT, CLUTCH_STATE__DISENGAGED, TS_APU__MAIN::sClutch, TS_APU__MAIN::u8State, and vAPU_CLUTCH__Disengage().
Referenced by vAPU__Init().
void vAPU_CLUTCH__Process (void)
Process any clutch functions.
SafeTool Function MD5:
1A23B184AA88915B649646C5D3D89A84
SafeTool Function ID:
LCCM720R0.FILE.010.FUNC.002
Referenced by vAPU__Process().
Variable Documentation
TS_APU__MAIN sAPU