(C Code, MULTICORE, BQ76PL536A BMS Driver): BQ76__CELLS
BQ76__CELLS
MULTICORE » BQ76
Functions
void vBQ76_CELLS__Read_All (void)
Read all the cell voltages off the device.
void vBQ76_CELLS__Compute_AllVoltages (void)
Compute the floating point cell voltages from the data arrays.
void vBQ76_CELLS__Init (void)
Init the cells subsystem.
void vBQ76_CELLS__Process (void)
Process the cell level state machine.
Lfloat32 f32BQ76_CELLS__Get_HighestVoltage (void)
Return the highest cell voltage.
Lfloat32 f32BQ76_CELLS__Get_LowestVoltage (void)
Return the lowest cell voltage in the system.
Lfloat32 f32BQ76_CELLS__Compute_CellVoltage (Luint8 u8HighByte, Luint8 u8LowByte)
Compute a cells voltage based on the datasheet equations.
void vBQ76_CELLS__10MS_ISR (void)
10MS interrupt
Variables
TS_BQ76__MAIN sBQ76
Detailed Description
Function Documentation
Lfloat32 f32BQ76_CELLS__Compute_CellVoltage (Luint8 u8HighByte, Luint8 u8LowByte)
Compute a cells voltage based on the datasheet equations.
Parameters
[in] u8LowByte Low byte from read
[in] u8HighByte High byte from read
SafeTool Function MD5:
F6051FF8EEF476D7CAFA5DBACD2A6ABF
SafeTool Function ID:
LCCM715R0.FILE.010.FUNC.005
Referenced by vBQ76_CELLS__Compute_AllVoltages().
Lfloat32 f32BQ76_CELLS__Get_HighestVoltage (void)
Return the highest cell voltage.
SafeTool Function MD5:
8F2B032B9D5EA69046F232D3AC3845CD
SafeTool Function ID:
LCCM715R0.FILE.010.FUNC.003
References TS_BQ76__MAIN::f32Highest, and TS_BQ76__MAIN::sCells.
Lfloat32 f32BQ76_CELLS__Get_LowestVoltage (void)
Return the lowest cell voltage in the system.
Returns
The lowest computed voltage
SafeTool Function MD5:
C4773F27824190CA34294ECB61E26A90
SafeTool Function ID:
LCCM715R0.FILE.010.FUNC.004
References TS_BQ76__MAIN::f32Lowest, and TS_BQ76__MAIN::sCells.
void vBQ76_CELLS__10MS_ISR (void)
10MS interrupt
SafeTool Function MD5:
1CEDE1D02EFC86149E3C00E8A5AB3EA1
SafeTool Function ID:
LCCM715R0.FILE.010.FUNC.007
References TS_BQ76__MAIN::sCells, and TS_BQ76__MAIN::u3210MS_Counter.
Referenced by vBQ76__10MS_ISR().
void vBQ76_CELLS__Compute_AllVoltages (void)
Compute the floating point cell voltages from the data arrays.
SafeTool Function MD5:
0DB7F59511A12A5002E1DC0474DE066F
SafeTool Function ID:
LCCM715R0.FILE.010.FUNC.008
References C_BQ76__MAX_CELLS_PER_DEVICE, f32BQ76_CELLS__Compute_CellVoltage(), TS_BQ76__MAIN::f32CellVoltage, TS_BQ76__MAIN::sCell, TS_BQ76__MAIN::sDevice, and TS_BQ76__MAIN::u8RawVoltArray.
Referenced by vBQ76_CELLS__Process().
void vBQ76_CELLS__Init (void)
Init the cells subsystem.
SafeTool Function MD5:
B734200087845452AE87CF6ACC59141D
SafeTool Function ID:
LCCM715R0.FILE.010.FUNC.001
References C_BQ76__TOTAL_CELLS, CELLS_STATE__IDLE, TS_BQ76__MAIN::f32CellVoltage, TS_BQ76__MAIN::sCell, TS_BQ76__MAIN::sCells, TS_BQ76__MAIN::sState, TS_BQ76__MAIN::u3210MS_Counter, and TS_BQ76__MAIN::u32UpdateCount.
Referenced by vBQ76__Init().
void vBQ76_CELLS__Process (void)
Process the cell level state machine.
SafeTool Function MD5:
DB9A8F4A04A3B0439C6548DAFDEDA803
SafeTool Function ID:
LCCM715R0.FILE.010.FUNC.002
Idle state
Start the conversion
Wait for the conversion to complete
Read the cell voltages
Convert raw to voltages
Do any filtering as needed
Compute the min/max volts
Compute the battery
References BQ76_REG__ADC_CONVERT, C_BQ76__TOTAL_CELLS, CELLS_STATE__COMPUTE_BATTERY, CELLS_STATE__COMPUTE_MIN_MAX, CELLS_STATE__CONVERT_VOLTS, CELLS_STATE__IDLE, CELLS_STATE__READ_VOLTS, CELLS_STATE__RUN_AVERAGER, CELLS_STATE__START_CONVERT, CELLS_STATE__WAIT_CONVERT, TS_BQ76__MAIN::f32CellVoltage, TS_BQ76__MAIN::f32Highest, TS_BQ76__MAIN::f32Lowest, TS_BQ76__MAIN::sCell, TS_BQ76__MAIN::sCells, TS_BQ76__MAIN::sState, TS_BQ76__MAIN::u3210MS_Counter, vBQ76_BATTERY__Compute_PackVoltage(), vBQ76_CELLS__Compute_AllVoltages(), vBQ76_CELLS__Read_All(), and vBQ76_SPI__Write_U8().
Referenced by vBQ76__Process().
void vBQ76_CELLS__Read_All (void)
Read all the cell voltages off the device.
SafeTool Function MD5:
78564D765DDF8EFC0F439B5F489E4572
SafeTool Function ID:
LCCM715R0.FILE.010.FUNC.006
References BQ76_REG__VCELL1, TS_BQ76__MAIN::sCells, TS_BQ76__MAIN::sDevice, TS_BQ76__MAIN::u32UpdateCount, TS_BQ76__MAIN::u8RawVoltArray, and vBQ76_SPI__Read_U8_Array().
Referenced by vBQ76_CELLS__Process().
Variable Documentation
TS_BQ76__MAIN sBQ76