(C Code, MULTICORE, BQ76PL536A BMS Driver): BQ76__RESISTOR
BQ76__RESISTOR
MULTICORE » BQ76
Functions
void vBQ76_RES__Init (void)
Init any resistor items.
void vBQ76_RES__Process (void)
Process any resistor control items.
void vBQ76_RES__All_Off (void)
Turn off all resistors.
void vBQ76_RES__Resistor_On (Luint8 u8CellIndex)
Turn an individual resistor on.
void vBQ76_RES__Resistor_Off (Luint8 u8CellIndex)
Turn an individual resistor off.
Variables
TS_BQ76__MAIN sBQ76
Detailed Description
Function Documentation
void vBQ76_RES__All_Off (void)
Turn off all resistors.
SafeTool Function MD5:
97971BB9CA087C63B21E64D56CA11F78
SafeTool Function ID:
LCCM715R0.FILE.007.FUNC.003
References BQ76_REG__CB_CTRL, C_BQ76__TOTAL_CELLS, TS_BQ76__MAIN::sBalance, TS_BQ76__MAIN::u8Resistor, and vBQ76_SPI__Write_U8().
void vBQ76_RES__Init (void)
Init any resistor items.
SafeTool Function MD5:
02E263E709AE6776A1D965F823088B04
SafeTool Function ID:
LCCM715R0.FILE.007.FUNC.001
Referenced by vBQ76__Init().
void vBQ76_RES__Process (void)
Process any resistor control items.
SafeTool Function MD5:
868D0314B99E1423B048A825A1D9135A
SafeTool Function ID:
LCCM715R0.FILE.007.FUNC.002
Referenced by vBQ76__Process().
void vBQ76_RES__Resistor_Off (Luint8 u8CellIndex)
Turn an individual resistor off.
Parameters
[in] u8CellIndex The resistor index.
SafeTool Function MD5:
443202F442F97669254DFC6511ADC43A
SafeTool Function ID:
LCCM715R0.FILE.007.FUNC.005
References BQ76_REG__CB_CTRL, C_BQ76__MAX_CELLS_PER_DEVICE, TS_BQ76__MAIN::sBalance, u8BQ76_SPI__Read_U8(), TS_BQ76__MAIN::u8Resistor, and vBQ76_SPI__Write_U8().
Referenced by vBQ76_BALANCE__Manual().
void vBQ76_RES__Resistor_On (Luint8 u8CellIndex)
Turn an individual resistor on.
Parameters
[in] u8CellIndex Associated cell resistor
SafeTool Function MD5:
1A954DF979AB61EFBF44011583AAF477
SafeTool Function ID:
LCCM715R0.FILE.007.FUNC.004
References BQ76_REG__CB_CTRL, BQ76_REG__CB_TIME, C_BQ76__MAX_CELLS_PER_DEVICE, TS_BQ76__MAIN::sBalance, u8BQ76_SPI__Read_U8(), TS_BQ76__MAIN::u8Resistor, and vBQ76_SPI__Write_U8().
Referenced by vBQ76_BALANCE__Manual().
Variable Documentation
TS_BQ76__MAIN sBQ76