(C Code, MULTICORE, BQ76PL536A BMS Driver): BQ76__BATTERY
BQ76__BATTERY
MULTICORE » BQ76
Functions
void vBQ76_BATTERY__Init (void)
Init the battery.
void vBQ76_BATTERY__Process (void)
Process any battery tasks.
void vBQ76_BATTERY__Compute_PackVoltage (void)
Compute the pack voltage.
Lfloat32 f32BQ76_BATTERY__Get_PackVoltage (void)
return the pack voltage
Variables
TS_BQ76__MAIN sBQ76
Detailed Description
Function Documentation
Lfloat32 f32BQ76_BATTERY__Get_PackVoltage (void)
return the pack voltage
SafeTool Function MD5:
9B133686076E3583A90F0C223A77EFDB
SafeTool Function ID:
LCCM715R0.FILE.011.FUNC.004
References TS_BQ76__MAIN::f32PackVoltage, and TS_BQ76__MAIN::sBattery.
void vBQ76_BATTERY__Compute_PackVoltage (void)
Compute the pack voltage.
SafeTool Function MD5:
6C6BDAAC96F01266E2AC867276327B77
SafeTool Function ID:
LCCM715R0.FILE.011.FUNC.003
References C_BQ76__TOTAL_CELLS, TS_BQ76__MAIN::f32CellVoltage, TS_BQ76__MAIN::f32PackVoltage, TS_BQ76__MAIN::sBattery, and TS_BQ76__MAIN::sCell.
Referenced by vBQ76_CELLS__Process().
void vBQ76_BATTERY__Init (void)
Init the battery.
SafeTool Function MD5:
8972212B91CA3DA6760475F2EB84EC01
SafeTool Function ID:
LCCM715R0.FILE.011.FUNC.001
References TS_BQ76__MAIN::f32PackVoltage, and TS_BQ76__MAIN::sBattery.
Referenced by vBQ76__Init().
void vBQ76_BATTERY__Process (void)
Process any battery tasks.
SafeTool Function MD5:
7EAEC9E911EA69F8D9997E533A179039
SafeTool Function ID:
LCCM715R0.FILE.011.FUNC.002
Referenced by vBQ76__Process().
Variable Documentation
TS_BQ76__MAIN sBQ76