(C Code, MULTICORE, BQ76PL536A BMS Driver): BQ76__BALANCE
BQ76__BALANCE
MULTICORE » BQ76
Functions
void vBQ76_BALANCE__Init (void)
Init the balancer.
void vBQ76_BALANCE__Process (void)
Process any balancing tasks.
void vBQ76_BALANCE__Start (void)
Start the balancing process.
Luint8 u8BQ76_BALANCE__Is_Busy (void)
Check if the balancer is busy.
void vBQ76_BALANCE__Stop (void)
Stop the balancing.
void vBQ76_BALANCE__Manual (Luint8 u8CellIndex, Luint8 u8Enable)
Manual balancing.
Variables
TS_BQ76__MAIN sBQ76
Detailed Description
Function Documentation
Luint8 u8BQ76_BALANCE__Is_Busy (void)
Check if the balancer is busy.
Returns
1 = busy
SafeTool Function MD5:
EAC635F7A4A802DB33BC96DDB37EF9F6
SafeTool Function ID:
LCCM715R0.FILE.012.FUNC.004
void vBQ76_BALANCE__Init (void)
Init the balancer.
SafeTool Function MD5:
DCBDDD902B64D985F0B09D4BB187B122
SafeTool Function ID:
LCCM715R0.FILE.012.FUNC.001
References C_BQ76__TOTAL_CELLS, TS_BQ76__MAIN::sBalance, and TS_BQ76__MAIN::u8Resistor.
Referenced by vBQ76__Init().
void vBQ76_BALANCE__Manual (Luint8 u8CellIndex, Luint8 u8Enable)
Manual balancing.
Parameters
[in] u8Enable 1 = resistor on
[in] u8CellIndex Cell index in system
SafeTool Function MD5:
0827BCA902FBB2EC4E1DB5C8F0184EFA
SafeTool Function ID:
LCCM715R0.FILE.012.FUNC.006
References C_BQ76__MAX_CELLS_PER_DEVICE, TS_BQ76__MAIN::sBalance, TS_BQ76__MAIN::u8Resistor, vBQ76_RES__Resistor_Off(), and vBQ76_RES__Resistor_On().
void vBQ76_BALANCE__Process (void)
Process any balancing tasks.
SafeTool Function MD5:
600233110464B6BAD3B047B64966DA0D
SafeTool Function ID:
LCCM715R0.FILE.012.FUNC.002
Referenced by vBQ76__Process().
void vBQ76_BALANCE__Start (void)
Start the balancing process.
SafeTool Function MD5:
C75001693893BA9946A832499E1350EF
SafeTool Function ID:
LCCM715R0.FILE.012.FUNC.003
void vBQ76_BALANCE__Stop (void)
Stop the balancing.
SafeTool Function MD5:
FB05686967B46A17D238B4B6740C4B4F
SafeTool Function ID:
LCCM715R0.FILE.012.FUNC.005
Variable Documentation
TS_BQ76__MAIN sBQ76