(C Code, MULTICORE, BQ76PL536A BMS Driver): BQ76__SPI
BQ76__SPI
MULTICORE » BQ76
Functions
void vBQ76_SPI__Set_Addresses (void)
Set all the addresses of devices on the bus.
void vBQ76_SPI__Init (void)
Init the SPI system.
void vBQ76_SPI__Process (void)
Process any SPI subsystems.
void vBQ76_SPI__Reset_All (void)
Reset all devices on the broadcast address.
void vBQ76_SPI__Write_U8 (Luint8 u8DeviceAddx, TE_BQ76__REG_DEFS eReg, Luint8 u8Value)
Write a byte to a register.
Luint8 u8BQ76_SPI__Read_U8 (Luint8 u8DeviceAddx, TE_BQ76__REG_DEFS eReg)
Read a byte from a register.
void vBQ76_SPI__Read_U8_Array (Luint8 u8DeviceAddx, TE_BQ76__REG_DEFS eReg, Luint8 *pu8Data, Luint8 u8Length)
Read a byte array.
Variables
TS_BQ76__MAIN sBQ76
Detailed Description
Function Documentation
Luint8 u8BQ76_SPI__Read_U8 (Luint8 u8DeviceAddx, TE_BQ76__REG_DEFS eReg)
Read a byte from a register.
Parameters
[in] eReg The register address
[in] u8DeviceAddx The device addx (never 0)
Returns
The register value
SafeTool Function MD5:
902FC075958D200AFDF2CB0E663AD9A4
SafeTool Function ID:
LCCM715R0.FILE.006.FUNC.004
References u8BQ76_CRC__Compute().
Referenced by vBQ76_RES__Resistor_Off(), vBQ76_RES__Resistor_On(), and vBQ76_SPI__Set_Addresses().
void vBQ76_SPI__Init (void)
Init the SPI system.
SafeTool Function MD5:
FE8D7268E138C5C629636317DE96F3DA
SafeTool Function ID:
LCCM715R0.FILE.006.FUNC.001
References BQ76_REG__ADC_CONTROL, vBQ76_SPI__Reset_All(), vBQ76_SPI__Set_Addresses(), and vBQ76_SPI__Write_U8().
Referenced by vBQ76__Init().
void vBQ76_SPI__Process (void)
Process any SPI subsystems.
SafeTool Function MD5:
6E2E95BD60B1DA9E00CCE23F1296632F
SafeTool Function ID:
LCCM715R0.FILE.006.FUNC.002
Referenced by vBQ76__Process().
void vBQ76_SPI__Read_U8_Array (Luint8 u8DeviceAddx, TE_BQ76__REG_DEFS eReg, Luint8 * pu8Data, Luint8 u8Length)
Read a byte array.
Parameters
[in] u8Length Total length of data read
[in] pu8Data Pointer to the recive buffer
[in] eReg The starting register adds
[in] u8DeviceAddx Device addx
SafeTool Function MD5:
09F9689D7FB58B23324E170182349B0B
SafeTool Function ID:
LCCM715R0.FILE.006.FUNC.005
Referenced by vBQ76_CELLS__Read_All().
void vBQ76_SPI__Reset_All (void)
Reset all devices on the broadcast address.
SafeTool Function MD5:
61FF74D3EC4F1A5C329FF06B755CC96C
SafeTool Function ID:
LCCM715R0.FILE.006.FUNC.006
References BQ76_REG__RESET, and vBQ76_SPI__Write_U8().
Referenced by vBQ76_SPI__Init().
void vBQ76_SPI__Set_Addresses (void)
Set all the addresses of devices on the bus.
SafeTool Function MD5:
9AD3C95638E48719DC5F2FE8A956CCD5
SafeTool Function ID:
LCCM715R0.FILE.006.FUNC.007
References BQ76_REG__ADDX_CONTROL, BQ76_REG__ALERT_STATUS, C_LCCM715__DEVICE__FAULT_INDEX__00, C_LCCM715__DEVICE__FAULT_INDEX__01, TS_BQ76__MAIN::sDevice, TS_BQ76__MAIN::sFaultFlags, u8BQ76_SPI__Read_U8(), and vBQ76_SPI__Write_U8().
Referenced by vBQ76_SPI__Init().
void vBQ76_SPI__Write_U8 (Luint8 u8DeviceAddx, TE_BQ76__REG_DEFS eReg, Luint8 u8Value)
Write a byte to a register.
Parameters
[in] u8Value The value to write
[in] eReg The register addx
[in] u8DeviceAddx The BQ76 device address (Must not be zero)
SafeTool Function MD5:
E28EEC9D306AB58712AA3FC2286EA0B0
SafeTool Function ID:
LCCM715R0.FILE.006.FUNC.003
References u8BQ76_CRC__Compute().
Referenced by vBQ76_CELLS__Process(), vBQ76_RES__All_Off(), vBQ76_RES__Resistor_Off(), vBQ76_RES__Resistor_On(), vBQ76_SPI__Init(), vBQ76_SPI__Reset_All(), and vBQ76_SPI__Set_Addresses().
Variable Documentation
TS_BQ76__MAIN sBQ76