(C Code, MULTICORE, BQ76PL536A BMS Driver): BQ76__CORE
BQ76__CORE
MULTICORE » BQ76
Functions
void vBQ76__Init (void)
Init the BQ76 device.
void vBQ76__Process (void)
Process any BQ76 tasks.
Lfloat32 f32BQ76__Get_CellVoltage (Luint8 u8CellIndex)
Get a cell voltage.
Luint32 u32BQ76__Get_VoltsUpdateCount (void)
Return the number of times the cells were read.
void vBQ76__10MS_ISR (void)
10ms interrupt
Luint32 u32BQ76__Get_FaultFlags (Luint8 u8DeviceIndex)
Get any BQ76 fault flags.
Variables
TS_BQ76__MAIN sBQ76
Detailed Description
Function Documentation
Lfloat32 f32BQ76__Get_CellVoltage (Luint8 u8CellIndex)
Get a cell voltage.
Note
Returns the filtered voltage if filtering is enabled
Parameters
[in] u8CellIndex The cell index in the pack
Returns
Cell voltage
SafeTool Function MD5:
F9449053D59F927DE2C805568AAE0908
SafeTool Function ID:
LCCM715R0.FILE.000.FUNC.005
References TS_BQ76__MAIN::f32CellVoltage, and TS_BQ76__MAIN::sCell.
Luint32 u32BQ76__Get_FaultFlags (Luint8 u8DeviceIndex)
Get any BQ76 fault flags.
Parameters
[in] u8DeviceIndex BQ76 index
Returns
32bit fault flags.
SafeTool Function MD5:
5964CEBB233BCB7C4E9DAB5E3D38AFEE
SafeTool Function ID:
LCCM715R0.FILE.000.FUNC.006
References TS_BQ76__MAIN::sDevice, and TS_BQ76__MAIN::sFaultFlags.
Luint32 u32BQ76__Get_VoltsUpdateCount (void)
Return the number of times the cells were read.
SafeTool Function MD5:
E866054152E6FBED501DED5B601B916D
SafeTool Function ID:
LCCM715R0.FILE.000.FUNC.003
References TS_BQ76__MAIN::sCells, and TS_BQ76__MAIN::u32UpdateCount.
void vBQ76__10MS_ISR (void)
10ms interrupt
SafeTool Function MD5:
E1AB47E5E68DD020598F75EEF0D0774B
SafeTool Function ID:
LCCM715R0.FILE.000.FUNC.004
References vBQ76_CELLS__10MS_ISR().
void vBQ76__Init (void)
Init the BQ76 device.
SafeTool Function MD5:
F10254CAECA5B757C2E5CBB41CB26500
SafeTool Function ID:
LCCM715R0.FILE.000.FUNC.001
References TS_BQ76__MAIN::sDevice, TS_BQ76__MAIN::sFaultFlags, vBQ76_BALANCE__Init(), vBQ76_BATTERY__Init(), vBQ76_CELLS__Init(), vBQ76_RES__Init(), and vBQ76_SPI__Init().
void vBQ76__Process (void)
Process any BQ76 tasks.
SafeTool Function MD5:
D23D95EBB63C64E05A886A25E83702E6
SafeTool Function ID:
LCCM715R0.FILE.000.FUNC.002
References vBQ76_BALANCE__Process(), vBQ76_BATTERY__Process(), vBQ76_CELLS__Process(), vBQ76_RES__Process(), and vBQ76_SPI__Process().
Variable Documentation
TS_BQ76__MAIN sBQ76