(C Code, MULTICORE, AMC7812 Driver): AMC7812__I2C
AMC7812__I2C
MULTICORE » AMC7812
Functions
void vAMC7812_I2C__Init (void)
Init any I2C requirements.
Lint16 s16AMC7812_I2C__TxCommand (Luint8 u8DeviceAddx, Luint8 u8RegisterAddx)
Transmit only the command byte.
Lint16 s16AMC7812_I2C__WriteU16 (Luint8 u8DeviceAddx, Luint8 u8RegisterAddx, Luint16 u16Value)
Write a U16 to the ACM7812 DAC.
Lint16 s16AMC7812_I2C__ReadU16 (Luint8 u8DeviceAddx, Luint8 u8RegAddx, Luint16 *pu16Value)
Read a U16 from the device.
Variables
struct _strAMC7812 sAMC
Detailed Description
Function Documentation
Lint16 s16AMC7812_I2C__ReadU16 (Luint8 u8DeviceAddx, Luint8 u8RegAddx, Luint16 * pu16Value)
Read a U16 from the device.
Parameters
[out] *pu16Value Return pointer to the read value
[in] u8RegAddx The register to write to
[in] u8DeviceAddx The I2C device address
SafeTool Function MD5:
920EC5F4487D524CBA82E9759E84475F
SafeTool Function ID:
LCCM658R0.FILE.005.FUNC.003
Referenced by vAMC7812__Process(), and vAMC7812_DAC__Process().
Lint16 s16AMC7812_I2C__TxCommand (Luint8 u8DeviceAddx, Luint8 u8RegisterAddx)
Transmit only the command byte.
Parameters
[in] eRegister The register / Command
[in] u8DeviceAddx I2C Bus Address
Returns
I2C Error Code
SafeTool Function MD5:
9A98D912BAD5639D22BB440479EE1774
SafeTool Function ID:
LCCM647R0.FILE.003.FUNC.001
Referenced by vAMC7812__Process().
Lint16 s16AMC7812_I2C__WriteU16 (Luint8 u8DeviceAddx, Luint8 u8RegisterAddx, Luint16 u16Value)
Write a U16 to the ACM7812 DAC.
Parameters
[in] u16Value The value to write
[in] u8RegAddx The register to write to
[in] u8DeviceAddx I2C Bus addx
Returns
I2C Status
SafeTool Function MD5:
404AE153C899FAAAD485205AB8616729
SafeTool Function ID:
LCCM658R0.FILE.005.FUNC.002
Referenced by vAMC7182_DAC__DAC_UpdateVoltage(), vAMC7812__Process(), vAMC7812_DAC__Process(), and vAMC7812_GPIO__Process().
void vAMC7812_I2C__Init (void)
Init any I2C requirements.
SafeTool Function MD5:
69922844C23BC4ED90109040C0E6E4CF
SafeTool Function ID:
LCCM658R0.FILE.005.FUNC.001
Referenced by vAMC7812__Init().
Variable Documentation
struct _strAMC7812 sAMC