(C Code, MULTICORE, AMC7812 Driver): AMC7812__CORE
AMC7812__CORE
MULTICORE » AMC7812
Functions
void vAMC7812__Init (void)
Init the core module.
void vAMC7812__Process (void)
Process any core tasks.
E_AMC7812__MNAIN_STATES_T eAMC7812__Get_State (void)
Luint32 u32AMC7812__Get_FaultFlags (void)
void vAMC7182__DAC_SetVoltage (Luint8 u8Channel, Lfloat32 f32Voltage)
Variables
struct _strAMC7812 sAMC
Detailed Description
Function Documentation
E_AMC7812__MNAIN_STATES_T eAMC7812__Get_State (void)
References _strAMC7812::eState, and sAMC.
Luint32 u32AMC7812__Get_FaultFlags (void)
References sAMC, and _strAMC7812::sFaultTree.
void vAMC7182__DAC_SetVoltage (Luint8 u8Channel, Lfloat32 f32Voltage)
References C_LCCM658__CORE__FAULT_INDEX__00, C_LCCM658__CORE__FAULT_INDEX__01, NUM_DAC_CHANNELS, sAMC, _strAMC7812::sFaultTree, and vAMC7182_DAC__DAC_UpdateVoltage().
void vAMC7812__Init (void)
Init the core module.
SafeTool Function MD5:
ED56D8E9A5830A1D90727FF6BB2FB08D
SafeTool Function ID:
LCCM658R0.FILE.000.FUNC.001
References AMC7812_STATE__RESET, _strAMC7812::eState, sAMC, _strAMC7812::sFaultTree, vAMC7812_ADC__Init(), vAMC7812_DAC__Init(), vAMC7812_GPIO__Init(), vAMC7812_I2C__Init(), and vAMC7812_LOWLEVEL__Init().
void vAMC7812__Process (void)
Process any core tasks.
SafeTool Function MD5:
96394E4CC69E197E228D42A9743AF8BC
SafeTool Function ID:
LCCM658R0.FILE.000.FUNC.002
References AMC7812_DAC_REG__CONFIG, AMC7812_DAC_REG__GAINS, AMC7812_DAC_REG__SW_RESET, AMC7812_REG_ADR__DAC_0_DATA, AMC7812_REG_ADR__DEV_ID, AMC7812_REG_ADR__PWR_DWN, AMC7812_STATE__CONFIGURE_DAC, AMC7812_STATE__FAULT, AMC7812_STATE__IDLE, AMC7812_STATE__RESET, AMC7812_STATE__UPDATE_DAC, C_LCCM658__CORE__FAULT_INDEX__00, C_LCCM658__CORE__FAULT_INDEX__02, _strAMC7812::eState, NUM_DAC_CHANNELS, s16AMC7812_I2C__ReadU16(), s16AMC7812_I2C__TxCommand(), s16AMC7812_I2C__WriteU16(), sAMC, _strAMC7812::sDAC, _strAMC7812::sFaultTree, _strAMC7812::u16DAC_OutputValue, _strAMC7812::u8NewValueLatched, _strAMC7812::u8UpdatePos, vAMC7812_ADC__Process(), vAMC7812_DAC__Process(), and vAMC7812_GPIO__Process().
Variable Documentation
struct _strAMC7812 sAMC
Referenced by eAMC7812__Get_State(), u32AMC7812__Get_FaultFlags(), vAMC7182__DAC_SetVoltage(), vAMC7182_DAC__DAC_UpdateVoltage(), vAMC7812__Init(), vAMC7812__Process(), and vAMC7812_DAC__Init().