(C Code, MULTICORE, AMC7812 Driver): AMC7812__GPIO
AMC7812__GPIO
MULTICORE » AMC7812
Macros
#define LOOP_COUNTER_LIMIT (10000000U)
Functions
void vAMC7812_GPIO__Init (void)
Init the GPIO portion of the device.
void vAMC7812_GPIO__Process (void)
Variables
struct _strAMC7812 sAMC
Detailed Description
Macro Definition Documentation
#define LOOP_COUNTER_LIMIT (10000000U)
Referenced by vAMC7812_GPIO__Process().
Function Documentation
void vAMC7812_GPIO__Init (void)
Init the GPIO portion of the device.
SafeTool Function MD5:
61B0504883195D29B464EA09607BECEF
SafeTool Function ID:
LCCM658R0.FILE.006.FUNC.001
Referenced by vAMC7812__Init().
void vAMC7812_GPIO__Process (void)
References AMC7812_REG_ADR__GPIO, LOOP_COUNTER_LIMIT, and s16AMC7812_I2C__WriteU16().
Referenced by vAMC7812__Process().
Variable Documentation
struct _strAMC7812 sAMC