(C Code, MULTICORE, AMC7812 Driver): AMC7812__DAC
AMC7812__DAC
MULTICORE » AMC7812
Functions
void vAMC7812_DAC__Init (void)
Init the DAC portion.
void vAMC7812_DAC__Process (void)
void vAMC7182_DAC__DAC_UpdateVoltage (Luint8 u8Channel, Lfloat32 f32Voltage)
Variables
struct _strAMC7812 sAMC
Detailed Description
Function Documentation
void vAMC7182_DAC__DAC_UpdateVoltage (Luint8 u8Channel, Lfloat32 f32Voltage)
References AMC7812_STATE__IDLE, C_AMC8172__DAC_SCALING_VALUE, C_LCCM658__CORE__FAULT_INDEX__00, C_LCCM658__CORE__FAULT_INDEX__01, NUM_DAC_CHANNELS, s16AMC7812_I2C__WriteU16(), sAMC, _strAMC7812::sDAC, _strAMC7812::sFaultTree, _strAMC7812::u16DAC_OutputValue, and _strAMC7812::u8NewValueLatched.
Referenced by vAMC7182__DAC_SetVoltage().
void vAMC7812_DAC__Init (void)
Init the DAC portion.
SafeTool Function MD5:
C180710CF0A27FA75265B2D3FA81C0E7
SafeTool Function ID:
LCCM658R0.FILE.007.FUNC.001
References AMC7812_REG_ADR__DAC_0_DATA, AMC7812_REG_ADR__DAC_10_DATA, AMC7812_REG_ADR__DAC_11_DATA, AMC7812_REG_ADR__DAC_1_DATA, AMC7812_REG_ADR__DAC_2_DATA, AMC7812_REG_ADR__DAC_3_DATA, AMC7812_REG_ADR__DAC_4_DATA, AMC7812_REG_ADR__DAC_5_DATA, AMC7812_REG_ADR__DAC_6_DATA, AMC7812_REG_ADR__DAC_7_DATA, AMC7812_REG_ADR__DAC_8_DATA, AMC7812_REG_ADR__DAC_9_DATA, DAC_OUT_MAX_MVOLTS, DAC_OUT_MIN_MVOLTS, NUM_DAC_CHANNELS, sAMC, _strAMC7812::sDAC, _strAMC7812::u16DAC_OutputValue, _strAMC7812::u8NewValueLatched, and _strAMC7812::u8UpdatePos.
Referenced by vAMC7812__Init().
void vAMC7812_DAC__Process (void)
References AMC7812_DAC_CONFIG_MODE_FLAG, AMC7812_DAC_GAIN_FLAG, AMC7812_DAC_REG__CONFIG, AMC7812_DAC_REG__GAINS, AMC7812_DAC_VREF, AMC7812_REG_ADR__DEV_ID, AMC7812_REG_ADR__PWR_DWN, AMC7812_STATE__IDLE, RM48_N2HET1_PIN__AMC7812_HW_RESET, s16AMC7812_I2C__ReadU16(), and s16AMC7812_I2C__WriteU16().
Referenced by vAMC7812__Process().
Variable Documentation
struct _strAMC7812 sAMC
Referenced by vAMC7182_DAC__DAC_UpdateVoltage(), and vAMC7812_DAC__Init().