(C Code, MULTICORE, DAQ Module): DAQ__APPEND
DAQ__APPEND
MULTICORE » DAQ
Functions
Lint16 s16SIL3_DAQ_APPEND__Index_to_Buffer_U8 (Luint16 u16Index)
Convert a DAQ channel to a buffer index for U8.
Lint16 s16DAQ_APPEND__Index_to_Buffer_S16 (Luint16 u16Index)
Get the S16 buffer index.
Lint16 s16DAQ_APPEND__Index_to_Buffer_U16 (Luint16 u16Index)
Get the U16 buffer index.
Lint16 s16DAQ_APPEND__Index_to_Buffer_S32 (Luint16 u16Index)
Get the S32 buffer index.
Lint16 s16DAQ_APPEND__Index_to_Buffer_U32 (Luint16 u16Index)
Get the U32 buffer index.
Lint16 s16DAQ_APPEND__Index_to_Buffer_F32 (Luint16 u16Index)
Get the F32 buffer index.
void vSIL3_DAQ_APPEND__Init (void)
Init the append module.
Lint16 s16SIL3_DAQ_APPEND__Index_to_BufferPointer (Luint16 u16Index, Luint8 **pu8Buffer)
Give a pointer to the buffer for any index.
Variables
struct _strDAQ sDAQ
Detailed Description
Function Documentation
Lint16 s16DAQ_APPEND__Index_to_Buffer_F32 (Luint16 u16Index)
Get the F32 buffer index.
Parameters
[in] u16Index ## Desc ##
SafeTool Function MD5:
42B757FB3C180CE2BA99E2EF84247EEF
SafeTool Function ID:
LCCM662R0.FILE.004.FUNC.014
References M_DAQ__F32_OFFSET, and M_DAQ__NUM_CHANNELS.
Referenced by vSIL3_DAQ_APPEND__Init().
Lint16 s16DAQ_APPEND__Index_to_Buffer_S16 (Luint16 u16Index)
Get the S16 buffer index.
Parameters
[in] u16Index ## Desc ##
SafeTool Function MD5:
02BB1CA9D83EC9A566D9753486CE7DEF
SafeTool Function ID:
LCCM662R0.FILE.004.FUNC.010
References M_DAQ__NUM_CHANNELS, and M_DAQ__S16_OFFSET.
Referenced by vSIL3_DAQ_APPEND__Init().
Lint16 s16DAQ_APPEND__Index_to_Buffer_S32 (Luint16 u16Index)
Get the S32 buffer index.
Parameters
[in] u16Index ## Desc ##
SafeTool Function MD5:
D8DBCA1C6A79406C5668797C7703B3B8
SafeTool Function ID:
LCCM662R0.FILE.004.FUNC.012
References M_DAQ__NUM_CHANNELS, and M_DAQ__S32_OFFSET.
Referenced by vSIL3_DAQ_APPEND__Init().
Lint16 s16DAQ_APPEND__Index_to_Buffer_U16 (Luint16 u16Index)
Get the U16 buffer index.
Parameters
[in] u16Index ## Desc ##
SafeTool Function MD5:
AE5BFEBA5151BFDEFD9857D75756A91C
SafeTool Function ID:
LCCM662R0.FILE.004.FUNC.011
References M_DAQ__NUM_CHANNELS, and M_DAQ__U16_OFFSET.
Referenced by vSIL3_DAQ_APPEND__Init().
Lint16 s16DAQ_APPEND__Index_to_Buffer_U32 (Luint16 u16Index)
Get the U32 buffer index.
Parameters
[in] u16Index ## Desc ##
SafeTool Function MD5:
4DD4FF34FB03CD1FC2B0011953AEF7E6
SafeTool Function ID:
LCCM662R0.FILE.004.FUNC.013
References M_DAQ__NUM_CHANNELS, and M_DAQ__U32_OFFSET.
Referenced by vSIL3_DAQ_APPEND__Init().
Lint16 s16SIL3_DAQ_APPEND__Index_to_Buffer_U8 (Luint16 u16Index)
Convert a DAQ channel to a buffer index for U8.
Parameters
[in] u16Index The system wide channel index
Returns
The UB buffer index or
-ve if we are out of range.
SafeTool Function MD5:
070B9274E22A819B484701CFE87B7429
SafeTool Function ID:
LCCM662R0.FILE.004.FUNC.003
References M_DAQ__U8_OFFSET.
Referenced by vSIL3_DAQ_APPEND__Init().
Lint16 s16SIL3_DAQ_APPEND__Index_to_BufferPointer (Luint16 u16Index, Luint8 ** pu8Buffer)
Give a pointer to the buffer for any index.
Parameters
[out] *pu8Buffer The return pointer to the start of the buffer
[in] u16Index The system wide index.
SafeTool Function MD5:
B39206E970692459348F768B7F10D049
SafeTool Function ID:
LCCM662R0.FILE.004.FUNC.004
References M_DAQ__F32_OFFSET, M_DAQ__NUM_CHANNELS, M_DAQ__S16_OFFSET, M_DAQ__S32_OFFSET, M_DAQ__U16_OFFSET, M_DAQ__U32_OFFSET, M_DAQ__U8_OFFSET, _strDAQ::sBuffers, and sDAQ.
Referenced by vSIL3_DAQ__Process().
void vSIL3_DAQ_APPEND__Init (void)
Init the append module.
SafeTool Function MD5:
2B5FF6E522591A5E4000B0726733F592
SafeTool Function ID:
LCCM662R0.FILE.004.FUNC.001
References M_DAQ__NUM_CHANNELS, s16DAQ_APPEND__Index_to_Buffer_F32(), s16DAQ_APPEND__Index_to_Buffer_S16(), s16DAQ_APPEND__Index_to_Buffer_S32(), s16DAQ_APPEND__Index_to_Buffer_U16(), s16DAQ_APPEND__Index_to_Buffer_U32(), s16SIL3_DAQ_APPEND__Index_to_Buffer_U8(), _strDAQ::sBuffers, sDAQ, _strDAQ::sFIFO, _strDAQ::sInterlock, _strDAQ::sStats, _strDAQ::u32FIFO_F32FullCount, _strDAQ::u32FIFO_S16FullCount, _strDAQ::u32FIFO_S32FullCount, _strDAQ::u32FIFO_U16FullCount, _strDAQ::u32FIFO_U32FullCount, _strDAQ::u32FIFO_U8FullCount, u32SIL3_DAQ__Get_SystemTimer(), _strDAQ::u8F32, _strDAQ::u8S16, _strDAQ::u8S32, _strDAQ::u8StreamingOn, _strDAQ::u8U16, _strDAQ::u8U32, _strDAQ::u8U8, vSIL3_DAQ_APPEND__F32(), vSIL3_DAQ_APPEND__S16(), vSIL3_DAQ_APPEND__S32(), vSIL3_DAQ_APPEND__U16(), vSIL3_DAQ_APPEND__U32(), and vSIL3_DAQ_APPEND__U8().
Referenced by vSIL3_DAQ__Init().
Variable Documentation
struct _strDAQ sDAQ
Referenced by s16SIL3_DAQ_APPEND__Index_to_BufferPointer(), and vSIL3_DAQ_APPEND__Init().