cd D:\SIL3\DESIGN\LDL\COMMON_CODE\MULTICORE\LCCM644__MULTICORE__DS18B20\PCLINT\
D:\SIL3\DESIGN\COMPILERS\PCLINT_8\LINT-NT.EXE -b "D:\SIL3\DESIGN\COMPILERS\PCLINT_8\CONFIG_FILES\sil3_options.lnt" project.lnt D:\SIL3\DESIGN\COMPILERS\PCLINT_8\CONFIG_FILES\sil3_defines.lnt files.lnt > result.txt
