cd D:\SIL3\DESIGN\LDL\COMMON_CODE\XILINX\FIRMWARE\LCCM666__XILINX__SIM_HYPERLOOP\PCLINT\
D:\SIL3\DESIGN\COMPILERS\PCLINT_8\LINT-NT.EXE -b "D:\SIL3\DESIGN\COMPILERS\PCLINT_8\CONFIG_FILES\sil3_options.lnt" project.lnt D:\SIL3\DESIGN\COMPILERS\PCLINT_8\CONFIG_FILES\sil3_defines.lnt files.lnt > result.txt
