(C Code, RLOOP, Landing Gear Control): LGU__ETHERNET
LGU__ETHERNET
RLOOP » LGU
Functions
void vLGU_ETH__Transmit (E_NET__PACKET_T ePacketType)
Transmit an ethernet packet.
void vLGU_ETH__Init (void)
Init the Eth subsystem.
void vLGU_ETH__Process (void)
Process any ethernet tasks.
Luint8 u8LGU_ETH__Is_LinkUp (void)
Is the eth link avail?
void vLGU_ETH__RxUDP (Luint8 *pu8Buffer, Luint16 u16Length, Luint16 u16DestPort)
RX a UDP packet off the ethernet stack.
void vLGU_ETH__RxSafeUDP (Luint8 *pu8Payload, Luint16 u16PayloadLength, Luint16 ePacketType, Luint16 u16DestPort, Luint16 u16Fault)
Rx a safety udp packet.
void vLGU_ETH__10MS_ISR (void)
10ms Interrupt
Variables
TS_LGU__MAIN sLGU
Detailed Description
Function Documentation
Luint8 u8LGU_ETH__Is_LinkUp (void)
Is the eth link avail?
SafeTool Function MD5:
540F753DE45DBA722D86226C6D08E788
SafeTool Function ID:
LCCM667R0.FILE.009.FUNC.003
Referenced by vLGU_ETH__Process().
void vLGU_ETH__10MS_ISR (void)
10ms Interrupt
SafeTool Function MD5:
4FA4E1AC352E516A4F7E399CF5EFE075
SafeTool Function ID:
LCCM667R0.FILE.009.FUNC.007
References TS_LGU__MAIN::sUDPDiag, TS_LGU__MAIN::u810MS_Flag, and TS_LGU__MAIN::u8250MS_Flag.
Referenced by vLGU_TIMERS__10MS_ISR().
void vLGU_ETH__Init (void)
Init the Eth subsystem.
SafeTool Function MD5:
C3B4CC3A5109238CBBFF035E96BE38B9
SafeTool Function ID:
LCCM667R0.FILE.009.FUNC.001
References TS_LGU__MAIN::eTxPacketType, TS_LGU__MAIN::eTxStreamingType, TS_LGU__MAIN::sEthernet, TS_LGU__MAIN::sUDPDiag, TS_LGU__MAIN::u810MS_Flag, TS_LGU__MAIN::u8250MS_Flag, TS_LGU__MAIN::u8IPAddx, and TS_LGU__MAIN::u8MACAddx.
Referenced by vLGU__Init().
void vLGU_ETH__Process (void)
Process any ethernet tasks.
SafeTool Function MD5:
9E5A0DA7B9FA07D662950116C2EDEE30
SafeTool Function ID:
LCCM667R0.FILE.009.FUNC.002
References TS_LGU__MAIN::eTxStreamingType, TS_LGU__MAIN::sUDPDiag, TS_LGU__MAIN::u810MS_Flag, TS_LGU__MAIN::u8250MS_Flag, u8LGU_ETH__Is_LinkUp(), and vLGU_ETH__Transmit().
Referenced by vLGU__Process().
void vLGU_ETH__RxSafeUDP (Luint8 * pu8Payload, Luint16 u16PayloadLength, Luint16 ePacketType, Luint16 u16DestPort, Luint16 u16Fault)
Rx a safety udp packet.
Parameters
[in] u16Fault Fault types
[in] u16DestPort Target port
[in] ePacketType Packet type
[in] u16PayloadLength Length of payload
[in] *pu8Payload Pointer to payload
SafeTool Function MD5:
364C34B3EF4080FBC3AAD1C371F7F1C3
SafeTool Function ID:
LCCM667R0.FILE.009.FUNC.005
Permit network based streaming control
References TS_LGU__MAIN::eTxStreamingType, TS_LGU__MAIN::sUDPDiag, vLGU_LIFT__Set_Direction(), and vLGU_LIFT__Set_Speed().
void vLGU_ETH__RxUDP (Luint8 * pu8Buffer, Luint16 u16Length, Luint16 u16DestPort)
RX a UDP packet off the ethernet stack.
Parameters
[in] u16DestPort Target port
[in] u16Length Payload length
[in] *pu8Buffer Pointer to the payload
SafeTool Function MD5:
FBE43A0B12873DFDADE49E96A32D80E6
SafeTool Function ID:
LCCM667R0.FILE.009.FUNC.004
void vLGU_ETH__Transmit (E_NET__PACKET_T ePacketType)
Transmit an ethernet packet.
Parameters
[in] ePacketType The packet type
SafeTool Function MD5:
CC9DE3848062E90EC70C3EBD67FDEF34
SafeTool Function ID:
LCCM667R0.FILE.009.FUNC.006
Transmit the LGU status packet over the network
References C_LGU__NUM_ACTUATORS.
Referenced by vLGU_ETH__Process().
Variable Documentation
TS_LGU__MAIN sLGU