(C Code, RLOOP, Landing Gear Control): LGU__CORE
LGU__CORE
RLOOP » LGU
Functions
void vLGU__Init (void)
Init the landing gear unit.
void vLGU__Process (void)
Main Landing Gear Process Function.
Variables
TS_LGU__MAIN sLGU
Detailed Description
Function Documentation
void vLGU__Init (void)
Init the landing gear unit.
SafeTool Function MD5:
B98A41297BC9D7630674FF7C2521E1E5
SafeTool Function ID:
LCCM667R0.FILE.000.FUNC.001
References vLGU_ETH__Init(), and vLGU_LIFT__Init().
void vLGU__Process (void)
Main Landing Gear Process Function.
SafeTool Function MD5:
964DF03CCFB853A03BF6BDF521C5F70F
SafeTool Function ID:
LCCM667R0.FILE.000.FUNC.002
References vLGU_ETH__Process(), and vLGU_LIFT__Process().
Variable Documentation
TS_LGU__MAIN sLGU