(C Code, RLOOP, Landing Gear Control): LGU__LIFT
LGU__LIFT
RLOOP » LGU
Functions
void vLGU_LIFT__Init (void)
Init the lift mechanism.
void vLGU_LIFT__Process (void)
Process any lift tasks.
void vLGU_LIFT__Set_Speed (Luint8 u8Actuator, Lfloat32 f32Percent)
Set the speed of the actuator in a percentage.
void vLGU_LIFT__Set_Direction (Luint8 u8Actuator, TE_LGU__LIFT_DIRECTIONS eDir)
Sets the direction of an actuator.
Variables
TS_LGU__MAIN sLGU
Detailed Description
Function Documentation
void vLGU_LIFT__Init (void)
Init the lift mechanism.
SafeTool Function MD5:
93A1624EF95FC806B4F411DF7A837894
SafeTool Function ID:
LCCM667R0.FILE.007.FUNC.001
References LIFT_DIR__EXTEND, LIFT_DIR__RETRACT, TS_LGU__MAIN::sPWM, TS_LGU__MAIN::u16ProgIndex, vLGU_LIFT__Set_Direction(), and vLGU_LIFT__Set_Speed().
Referenced by vLGU__Init().
void vLGU_LIFT__Process (void)
Process any lift tasks.
SafeTool Function MD5:
665AE66506CEEDAD3A611BF87B367675
SafeTool Function ID:
LCCM667R0.FILE.007.FUNC.002
Referenced by vLGU__Process().
void vLGU_LIFT__Set_Direction (Luint8 u8Actuator, TE_LGU__LIFT_DIRECTIONS eDir)
Sets the direction of an actuator.
Parameters
[in] eDir Direction
[in] u8Actuator Actuator index
SafeTool Function MD5:
E9005419DECCC750F041F760E0F79980
SafeTool Function ID:
LCCM667R0.FILE.007.FUNC.004
Actuator Off
Raise the actuator
Lower the actuator
References C_LGU__NUM_ACTUATORS, LIFT_DIR__EXTEND, LIFT_DIR__NONE, and LIFT_DIR__RETRACT.
Referenced by vLGU_ETH__RxSafeUDP(), and vLGU_LIFT__Init().
void vLGU_LIFT__Set_Speed (Luint8 u8Actuator, Lfloat32 f32Percent)
Set the speed of the actuator in a percentage.
Parameters
[in] f32Percent 0.0 to 1.0
[in] u8Actuator Actuator index
SafeTool Function MD5:
BC18C7D4BEA359737A5FB854C8314E26
SafeTool Function ID:
LCCM667R0.FILE.007.FUNC.003
References C_LGU__NUM_ACTUATORS, TS_LGU__MAIN::sPWM, and TS_LGU__MAIN::u16ProgIndex.
Referenced by vLGU_ETH__RxSafeUDP(), and vLGU_LIFT__Init().
Variable Documentation
TS_LGU__MAIN sLGU