cd D:\LOCKIE\DESIGN\RLOOP\FIRMWARE\PROJECT_CODE\LCCM656__RLOOP__PI_COMMS\PCLINT\
D:\LOCKIE\DESIGN\COMPILERS\PCLINT_8\LINT-NT.EXE -b "D:\LOCKIE\DESIGN\COMPILERS\PCLINT_8\CONFIG_FILES\lockie_options.lnt" project.lnt D:\LOCKIE\DESIGN\COMPILERS\PCLINT_8\CONFIG_FILES\lockie_defines.lnt files.lnt > result.txt
