cd D:\SIL3\DESIGN\RLOOP\FIRMWARE\PROJECT_CODE\LCCM656__RLOOP__PI_COMMS\PCLINT\
D:\SIL3\DESIGN\COMPILERS\PCLINT_8\LINT-NT.EXE -b "D:\SIL3\DESIGN\COMPILERS\PCLINT_8\CONFIG_FILES\sil3_options.lnt" project.lnt D:\SIL3\DESIGN\COMPILERS\PCLINT_8\CONFIG_FILES\sil3_defines.lnt files.lnt > result.txt
