(C Code, MULTICORE, TSYS01 Driver): TSYS01__I2C
TSYS01__I2C
MULTICORE » TSYS01
Functions
Lint16 s16TSYS01_I2C__TxCommand (Luint8 u8DeviceAddx, E_TSYS01_REGS_T eRegister)
Transmit only the command byte.
Lint16 s16TSYS01_I2C__TxU8 (Luint8 u8DeviceAddx, E_TSYS01_REGS_T eRegister, Luint8 u8Byte)
Transmit a byte.
Lint16 s16TSYS01_I2C__RxU16 (Luint8 u8DeviceAddx, E_TSYS01_REGS_T eRegister, Luint16 *pu16)
Read a U16.
Lint16 s16TSYS01_I2C__RxU24 (Luint8 u8DeviceAddx, E_TSYS01_REGS_T eRegister, Luint32 *pu32)
Rx a 24 bit value.
Variables
TS_TSYS01__MAIN sTSYS
Detailed Description
Function Documentation
Lint16 s16TSYS01_I2C__RxU16 (Luint8 u8DeviceAddx, E_TSYS01_REGS_T eRegister, Luint16 * pu16)
Read a U16.
SafeTool Images:
The image below shows reading a constant
Parameters
[in] *pu16 Pointer to returned data
[in] eRegister The read register
[in] u8DeviceAddx I2C Bus Address
Returns
I2C Error Code
SafeTool Function MD5:
50EE7EC961C68823AE4651BC0D2F615C
SafeTool Function ID:
LCCM647R0.FILE.003.FUNC.003
Referenced by s16TSYS01__Read_K_Values().
Lint16 s16TSYS01_I2C__RxU24 (Luint8 u8DeviceAddx, E_TSYS01_REGS_T eRegister, Luint32 * pu32)
Rx a 24 bit value.
SafeTool Images:
The image below shows the read command
Parameters
[in] *pu32 Pointer to return data
[in] eRegister Read register
[in] u8DeviceAddx I2C Bus Address
Returns
I2C Error Code
SafeTool Function MD5:
4F32BD32B20CF7AC5C02958166BB20DC
SafeTool Function ID:
LCCM647R0.FILE.003.FUNC.004
Referenced by vTSYS01__Process().
Lint16 s16TSYS01_I2C__TxCommand (Luint8 u8DeviceAddx, E_TSYS01_REGS_T eRegister)
Transmit only the command byte.
SafeTool Images:
The image below shows adc sample start command
Parameters
[in] eRegister The register / Command
[in] u8DeviceAddx I2C Bus Address
Returns
I2C Error Code
SafeTool Function MD5:
7A76FB914FA3B00E23639630F5B6BA4C
SafeTool Function ID:
LCCM647R0.FILE.003.FUNC.001
Referenced by vTSYS01__Process().
Lint16 s16TSYS01_I2C__TxU8 (Luint8 u8DeviceAddx, E_TSYS01_REGS_T eRegister, Luint8 u8Byte)
Transmit a byte.
Parameters
[in] u8Byte The byte to transmit
[in] eRegister Target Register
[in] u8DeviceAddx I2C Bus Address
Returns
I2C Error Code
SafeTool Function MD5:
493DE96A1CD7E223833E8C265719899C
SafeTool Function ID:
LCCM647R0.FILE.003.FUNC.002
Variable Documentation
TS_TSYS01__MAIN sTSYS