(C Code, MULTICORE, TSYS01 Driver): TSYS01__CORE
TSYS01__CORE
MULTICORE » TSYS01
Functions
static Lint16 s16TSYS01__Read_K_Values (Luint16 *pu16Values)
Read each of the 5 K calibration constants over i2c.
static void vTSYS01__Delay_mS (Luint32 u32Value)
Standard delay routine.
void vTSYS01__Init (void)
Init any variables as needed.
void vTSYS01__Process (void)
Main processing state machine.
Lfloat32 f32TSYS01__Get_TempDegC (void)
Most recent measurement, made global for external use.
Luint32 u32TSYS01__Get_FaultFlags (void)
Get any module level fault flags.
Variables
TS_TSYS01__MAIN sTSYS
Detailed Description
Function Documentation
Lfloat32 f32TSYS01__Get_TempDegC (void)
Most recent measurement, made global for external use.
Returns
Temperature in DegC
SafeTool Function MD5:
8659D658713AB1BA9D1CC17CFF9FDCB4
SafeTool Function ID:
LCCM647R0.FILE.000.FUNC.004
References TS_TSYS01__MAIN::f32TempDegC.
Lint16 s16TSYS01__Read_K_Values (Luint16 * pu16Values) static
Read each of the 5 K calibration constants over i2c.
Parameters
[in] *pu16Values Pointer to returned values
Returns
0 = success
-ve = fault
SafeTool Function MD5:
3FAB8ED94A8C7555A93E8EE1B56426F9
SafeTool Function ID:
LCCM647R0.FILE.000.FUNC.003
References s16TSYS01_I2C__RxU16(), TSYS01_REG__k0_ADR, TSYS01_REG__k1_ADR, TSYS01_REG__k2_ADR, TSYS01_REG__k3_ADR, TSYS01_REG__k4_ADR, and vTSYS01__Delay_mS().
Referenced by vTSYS01__Process().
Luint32 u32TSYS01__Get_FaultFlags (void)
Get any module level fault flags.
Returns
The fault flags
SafeTool Function MD5:
EE994C7B49C8B626208C270E5ED75C07
SafeTool Function ID:
LCCM647R0.FILE.000.FUNC.006
References TS_TSYS01__MAIN::sFaultFlags.
void vTSYS01__Delay_mS (Luint32 u32Value) static
Standard delay routine.
Parameters
[in] u32Value ms Delay Value
SafeTool Function MD5:
E7819127BB146243E4215732DBF139AF
SafeTool Function ID:
LCCM647R0.FILE.000.FUNC.005
Referenced by s16TSYS01__Read_K_Values(), and vTSYS01__Process().
void vTSYS01__Init (void)
Init any variables as needed.
SafeTool Function MD5:
AD7E1745A84BCDE183BB048EB939545D
SafeTool Function ID:
LCCM647R0.FILE.000.FUNC.001
References C_TSYS01__MAX_FILTER_SAMPLES, TS_TSYS01__MAIN::eState, TS_TSYS01__MAIN::f32TempDegC, TS_TSYS01__MAIN::sFaultFlags, TSYS01_STATE__INIT_DEVICE, TS_TSYS01__MAIN::u16AverageCounter, TS_TSYS01__MAIN::u32AverageArray, TS_TSYS01__MAIN::u32AverageResult, TS_TSYS01__MAIN::u32AverageResult_Div256, TS_TSYS01__MAIN::u32Guard0, TS_TSYS01__MAIN::u32Guard1, and TS_TSYS01__MAIN::u32LoopCounter.
void vTSYS01__Process (void)
Main processing state machine.
SafeTool Function MD5:
2596479478B2632DCEF8B53771667CED
SafeTool Function ID:
LCCM647R0.FILE.000.FUNC.002
References C_LCCM647__CORE__FAULT_INDEX__00, C_LCCM647__CORE__FAULT_INDEX__01, C_LCCM647__CORE__FAULT_INDEX__02, C_LCCM647__CORE__FAULT_INDEX__03, C_TSYS01__MAX_FILTER_SAMPLES, TS_TSYS01__MAIN::eState, TS_TSYS01__MAIN::f32Coeffs, TS_TSYS01__MAIN::f32TempDegC, s16TSYS01__Read_K_Values(), s16TSYS01_I2C__RxU24(), s16TSYS01_I2C__TxCommand(), TS_TSYS01__MAIN::sFaultFlags, TSYS01_REG__READ_ADC_TEMPERATURE_RESULT, TSYS01_REG__RESET, TSYS01_REG__START_ADC_TEMPERATURE_CONVERSION, TSYS01_STATE__BEGIN_SAMPLE, TSYS01_STATE__COMPUTE, TSYS01_STATE__ERROR, TSYS01_STATE__IDLE, TSYS01_STATE__INIT_DEVICE, TSYS01_STATE__READ_ADC, TSYS01_STATE__READ_CONSTANTS, TSYS01_STATE__WAIT_LOOPS, TS_TSYS01__MAIN::u16AverageCounter, TS_TSYS01__MAIN::u32AverageArray, TS_TSYS01__MAIN::u32AverageResult, TS_TSYS01__MAIN::u32AverageResult_Div256, TS_TSYS01__MAIN::u32Guard0, TS_TSYS01__MAIN::u32Guard1, TS_TSYS01__MAIN::u32LastResult, TS_TSYS01__MAIN::u32LoopCounter, and vTSYS01__Delay_mS().
Variable Documentation
TS_TSYS01__MAIN sTSYS