cd D:\LOCKIE\DESIGN\LDL\COMMON_CODE\MULTICORE\LCCM650__MULTICORE__ATA6870\PCLINT\
D:\LOCKIE\DESIGN\COMPILERS\PCLINT_8\LINT-NT.EXE -b "D:\LOCKIE\DESIGN\COMPILERS\PCLINT_8\CONFIG_FILES\lockie_options.lnt" project.lnt D:\LOCKIE\DESIGN\COMPILERS\PCLINT_8\CONFIG_FILES\lockie_defines.lnt files.lnt > result.txt
