/*
 * fcu__laser_opto__fault_flags.h
 *
 *  Created on: 27 Dec 2016
 *      Author: Lachlan
 */

#ifndef RLOOP_LCCM655__RLOOP__FCU_CORE_LASER_OPTO_FCU__LASER_OPTO__FAULT_FLAGS_H_
#define RLOOP_LCCM655__RLOOP__FCU_CORE_LASER_OPTO_FCU__LASER_OPTO__FAULT_FLAGS_H_





#endif /* RLOOP_LCCM655__RLOOP__FCU_CORE_LASER_OPTO_FCU__LASER_OPTO__FAULT_FLAGS_H_ */
