(C Code, MULTICORE, MS5607): I2C/ms5607_i2c.c File Reference
ms5607_i2c.c File Reference
#include "../ms5607.h"
Functions
Lint16 s16MS5607_I2C__TxCommand (Luint8 u8DeviceAddx, E_MS5607_CMD_T eRegister)
Lint16 s16MS5607_I2C__TxU8 (Luint8 u8DeviceAddx, E_MS5607_CMD_T eRegister, Luint8 u8Byte)
Lint16 s16MS5607_I2C__RxU16 (Luint8 u8DeviceAddx, E_MS5607_CMD_T eRegister, Luint16 *pu16)
Lint16 s16MS5607_I2C__RxU24 (Luint8 u8DeviceAddx, E_MS5607_CMD_T eRegister, Luint32 *pu32)
Function Documentation
Lint16 s16MS5607_I2C__RxU16 (Luint8 u8DeviceAddx, E_MS5607_CMD_T eRegister, Luint16 * pu16)
Referenced by s16MS5607__GetCalibrationContants().
Lint16 s16MS5607_I2C__RxU24 (Luint8 u8DeviceAddx, E_MS5607_CMD_T eRegister, Luint32 * pu32)
Referenced by vMS5607__Process().
Lint16 s16MS5607_I2C__TxCommand (Luint8 u8DeviceAddx, E_MS5607_CMD_T eRegister)
Referenced by s16MS5607__StartPressureConversion(), s16MS5607__StartTemperatureConversion(), and vMS5607__Process().
Lint16 s16MS5607_I2C__TxU8 (Luint8 u8DeviceAddx, E_MS5607_CMD_T eRegister, Luint8 u8Byte)