(C Code, MULTICORE, MS5607): ms5607.c File Reference
ms5607.c File Reference
Barometric Pressure Sensor, with stainless steel cap.
#include "ms5607.h"
Functions
Lint16 s16MS5607__GetCalibrationContants (Luint16 *pu16Values)
Read each of coefficients over i2c.
void vMS5607__Init (void)
Init.
void vMS5607__Process (void)
Luint8 u8MS5607__Get_IsFault (void)
Lint32 sMS5607__GetTemperature (void)
Read Digital Temperature Value D2.
Lint32 sMS5607__GetPressure (void)
Return the compensated pressure as a floating point value, in mbar.
Lint16 s16MS5607__StartTemperatureConversion (void)
Start a temperature conversion with the defined OSR.
Lint16 s16MS5607__StartPressureConversion (void)
Start a pressure conversion with the defined OSR.
void vMS5607__CalculateTemperature (void)
Calculate Compensated Temperature.
void vMS5607__CalculateTempCompensatedPressure (void)
Calculate Temperature Compensated Pressure.
void vMS5607__compensateSecondOrder (void)
Second Order Temperature Compensation.
Luint8 u8MS5607__CRC4 (Luint16 *pu16Coefficients)
calculate the CRC code for details look into CRC CODE NOTES
Luint8 uMS5607__getLSB4Bits (Luint32 u32LastCoefficient)
Variables
struct _strMS5607 sMS5607
Detailed Description
Barometric Pressure Sensor, with stainless steel cap.
Author
Edward Chan (40Chans) [Sftw, HR], Mila Antonova (scrappymacgyver) [Ctrl]
Copyright
rLoop Inc.
Function Documentation
Lint16 s16MS5607__GetCalibrationContants (Luint16 * pu16Values)
Read each of coefficients over i2c.
References MS5607_CMD__PROM_READ, and s16MS5607_I2C__RxU16().
Referenced by vMS5607__Process().
Lint16 s16MS5607__StartPressureConversion (void)
Start a pressure conversion with the defined OSR.
References MS5607_PRESSURE_OSR, and s16MS5607_I2C__TxCommand().
Referenced by vMS5607__Process().
Lint16 s16MS5607__StartTemperatureConversion (void)
Start a temperature conversion with the defined OSR.
References MS5607_TEMPERATURE_OSR, and s16MS5607_I2C__TxCommand().
Referenced by vMS5607__Process().
Lint32 sMS5607__GetPressure (void)
Return the compensated pressure as a floating point value, in mbar.
References _strPressure::s32P, sMS5607, and _strMS5607::sPRESSURE.
Lint32 sMS5607__GetTemperature (void)
Read Digital Temperature Value D2.
Read Digital Pressure Value D1 Return the compensated temperature as a floating point value in C
References _strTemperature::s32TEMP, sMS5607, and _strMS5607::sTEMP.
Luint8 u8MS5607__CRC4 (Luint16 * pu16Coefficients)
calculate the CRC code for details look into CRC CODE NOTES
Returns
crc code
Referenced by vMS5607__Process().
Luint8 u8MS5607__Get_IsFault (void)
References _strMS5607::eState, MS5607_STATE__ERROR, and sMS5607.
Luint8 uMS5607__getLSB4Bits (Luint32 u32LastCoefficient)
Referenced by vMS5607__Process().
void vMS5607__CalculateTempCompensatedPressure (void)
Calculate Temperature Compensated Pressure.
References _strTemperature::s32dT, _strSecondOrderCompensation::s32OFF2, _strPressure::s32P, _strPressure::s64OFF, _strPressure::s64SENS, _strSecondOrderCompensation::s64SENS2, sMS5607, _strMS5607::sPRESSURE, _strMS5607::sSECONDORDER, _strMS5607::sTEMP, _strMS5607::u16Coefficients, and _strMS5607::u32AverageResultPressure.
Referenced by vMS5607__Process().
void vMS5607__CalculateTemperature (void)
Calculate Compensated Temperature.
References _strTemperature::s32dT, _strTemperature::s32TEMP, sMS5607, _strMS5607::sTEMP, _strMS5607::u16Coefficients, and _strMS5607::u32AverageResultTemperature.
Referenced by vMS5607__Process().
void vMS5607__compensateSecondOrder (void)
Second Order Temperature Compensation.
References _strTemperature::s32dT, _strSecondOrderCompensation::s32OFF2, _strTemperature::s32TEMP, _strSecondOrderCompensation::s64SENS2, sMS5607, _strMS5607::sSECONDORDER, and _strMS5607::sTEMP.
Referenced by vMS5607__Process().
void vMS5607__Init (void)
Init.
References C_MS5607__MAX_FILTER_SAMPLES, _strMS5607::eState, MS5607_STATE__INIT_DEVICE, _strPressure::s32P, _strTemperature::s32TEMP, sMS5607, _strMS5607::sPRESSURE, _strMS5607::sTEMP, _strMS5607::u16AverageCounterPressure, _strMS5607::u16AverageCounterTemperature, _strMS5607::u32AverageArrayPressure, _strMS5607::u32AverageArrayTemperature, _strMS5607::u32AverageResultPressure, _strMS5607::u32AverageResultTemperature, and _strMS5607::u32LoopCounter.
void vMS5607__Process (void)
References C_MS5607__MAX_FILTER_SAMPLES, _strMS5607::eState, MS5607_CMD__ADC_READ, MS5607_CMD__RESET, MS5607_STATE__BEGIN_SAMPLE_PRESSURE, MS5607_STATE__BEGIN_SAMPLE_TEMPERATURE, MS5607_STATE__COMPUTE, MS5607_STATE__ERROR, MS5607_STATE__IDLE, MS5607_STATE__INIT_DEVICE, MS5607_STATE__INTERRUPT, MS5607_STATE__READ_ADC_PRESSURE, MS5607_STATE__READ_ADC_TEMPERATURE, MS5607_STATE__READ_CALIBRATION, MS5607_STATE__WAIT_LOOPS_PRESSURE, MS5607_STATE__WAIT_LOOPS_TEMPERATURE, MS5607_STATE__WAITING, s16MS5607__GetCalibrationContants(), s16MS5607__StartPressureConversion(), s16MS5607__StartTemperatureConversion(), s16MS5607_I2C__RxU24(), s16MS5607_I2C__TxCommand(), _strTemperature::s32TEMP, sMS5607, _strMS5607::sTEMP, _strMS5607::u16AverageCounterPressure, _strMS5607::u16AverageCounterTemperature, _strMS5607::u16Coefficients, _strMS5607::u32AverageArrayPressure, _strMS5607::u32AverageArrayTemperature, _strMS5607::u32AverageResultPressure, _strMS5607::u32AverageResultTemperature, _strMS5607::u32LastResultPressure, _strMS5607::u32LastResultTemperature, _strMS5607::u32LoopCounter, u8MS5607__CRC4(), uMS5607__getLSB4Bits(), vMS5607__CalculateTempCompensatedPressure(), vMS5607__CalculateTemperature(), and vMS5607__compensateSecondOrder().
Variable Documentation
struct _strMS5607 sMS5607
Referenced by sMS5607__GetPressure(), sMS5607__GetTemperature(), u8MS5607__Get_IsFault(), vMS5607__CalculateTempCompensatedPressure(), vMS5607__CalculateTemperature(), vMS5607__compensateSecondOrder(), vMS5607__Init(), and vMS5607__Process().