/*
 * power_core__eeprom_index.h
 *
 *  Created on: 28 Dec 2016
 *      Author: Lachlan
 */

#ifndef POWER_CORE__EEPROM_INDEX_H_
#define POWER_CORE__EEPROM_INDEX_H_

	//indexes for the eeprom params
	#define C_POWERCORE__EEPARAM_INDEX__BATTTEMP__NUM_SENSORS			(0U)
	#define C_POWERCORE__EEPARAM_INDEX__BATTTEMP__PACK_CRC				(1U)
	#define C_POWERCORE__EEPARAM_INDEX__BATTTEMP__CRC					(2U)

	#define C_POWERCORE__EEPARAM_INDEX__CHARGER__MAX_CELL_VOLT			(3U)
	#define C_POWERCORE__EEPARAM_INDEX__CHARGER__MIN_PACK_VOLT			(4U)
	#define C_POWERCORE__EEPARAM_INDEX__CHARGER__MAX_PACK_VOLT			(5U)
	#define C_POWERCORE__EEPARAM_INDEX__CHARGER__MAX_CELL_TEMP			(6U)
	#define C_POWERCORE__EEPARAM_INDEX__CHARGER__CRC					(7U)

	//For the power node
	#define C_POWERCORE__EEPARAM_INDEX__NODE_TYPE__TYPE_A				(8U)
	#define C_POWERCORE__EEPARAM_INDEX__NODE_TYPE__TYPE_B				(9U)
	#define C_POWERCORE__EEPARAM_INDEX__NODE_TYPE__TYPE_CRC				(10U)

#endif /* POWER_CORE__EEPROM_INDEX_H_ */
