LFW513 (RLOOP - POWER NODE): COMMON_CODE/MULTICORE/LCCM284__MULTICORE__FAULT_TREE/fault_tree.h File Reference
fault_tree.h File Reference
Main header file.
#include <localdef.h>
#include <MULTICORE/LCCM284__MULTICORE__FAULT_TREE/fault_tree__public.h>
Functions
void vFAULTTREE__Init (FAULT_TREE__PUBLIC_T *pFaultTree)
Init the fault Tree.
void vFAULTTREE__Set_Flag (FAULT_TREE__PUBLIC_T *pFaultTree, Luint32 u32FlagIndex)
set a fault tree flag.
void vFAULTTREE__Clear_Flag (FAULT_TREE__PUBLIC_T *pFaultTree, Luint32 u32FlagIndex)
Clear a fault flag.
Luint8 u8FAULTTREE__Get_Fault (const FAULT_TREE__PUBLIC_T *pFaultTree, Luint32 u32FlagIndex)
Gets a fault based on a flag index.
Detailed Description
Main header file.
Author
Lachlan Grogan
Copyright
This file contains proprietary and confidential information of the Lockie Group of companies, including SIL3 Pty. Ltd (ACN 123 529 064) and Lockie Safety Systems Pty. Ltd (ACN 132 340 571). This code may be distributed under a license from the Lockie Group of companies, and may be used, copied and/or disclosed only pursuant to the terms of that license agreement. This copyright notice must be retained as part of this file at all times.
This file is copyright SIL3 Pty Ltd 2003-2012, All Rights Reserved.
This file is copyright Lockie Safety Systems Pty Ltd 2008-2012, All Rights Reserved.
SafeTool FileID:
LCCM284R0.FILE.009
Function Documentation
Luint8 u8FAULTTREE__Get_Fault (const FAULT_TREE__PUBLIC_T * pFaultTree, Luint32 u32FlagIndex)
Gets a fault based on a flag index.
Parameters
[in] u32FlagIndex The flag index
[in] pFaultTree Pointer to fault tree
Returns
1 = is fault
0 = flag is not at fault
SafeTool Function MD5:
F5C7F7DCDFF0A75E2D73866E3A37912A
SafeTool Function ID:
LCCM284R0.FILE.008.FUNC.003
SafeTool://LCCM284R0.SPEC.FR.004
Specifications:
: LCCM284R0.SPEC.FR.004
Category: SOFTWARE/FUNCTIONAL/GET The user will be able to check if a particular fault flag is set.
References FAULT_TREE__PUBLIC_T::u32Flags.
void vFAULTTREE__Clear_Flag (FAULT_TREE__PUBLIC_T * pFaultTree, Luint32 u32FlagIndex)
Clear a fault flag.
Used to clear an already set flag if the user does not want to implement sticky flags.
Parameters
[in] u32FlagIndex The flag index.
[in] pFaultTree Pointer to users structure
SafeTool Function MD5:
2FA4298E46C8D72BFC61D14B4DC71C02
SafeTool Function ID:
LCCM284R0.FILE.008.FUNC.004
SafeTool://LCCM284R0.SPEC.FR.003
Specifications:
: LCCM284R0.SPEC.FR.003
Category: SOFTWARE/FUNCTIONAL/CLEAR The user can clear a particular flag.
References FAULT_TREE__PUBLIC_T::u32Flags, and FAULT_TREE__PUBLIC_T::u8FaultFlag.
void vFAULTTREE__Init (FAULT_TREE__PUBLIC_T * pFaultTree)
Init the fault Tree.
Inits the internal structure values for the fault tree
Parameters
[in] pFaultTree Pointer to the users fault tree
SafeTool Function MD5:
B7FBF6468679CE0E37367DC907AB0C41
SafeTool Function ID:
LCCM284R0.FILE.008.FUNC.001
SafeTool://LCCM284R0.SPEC.FR.001
Specifications:
: LCCM284R0.SPEC.FR.001
Category: SOFTWARE/FUNCTIONAL/INIT The fault tree module will be initted by a single function call accepting the user falt tree type.
References FAULT_TREE__PUBLIC_T::u32Flags, and FAULT_TREE__PUBLIC_T::u8FaultFlag.
Referenced by vDS2482S__Init(), vRM4_BIST__Init(), vRM4_ESM__Init(), vRM4_I2C_USER__Init(), and vRM4_SELFTEST__Init().
void vFAULTTREE__Set_Flag (FAULT_TREE__PUBLIC_T * pFaultTree, Luint32 u32FlagIndex)
set a fault tree flag.
Pass in the fault tree for the current module and the defined flag index number ranging between 0 and 63
Parameters
[in] u32FlagIndex Defined flag index
[in] pFaultTree Pointer to users fault tree
SafeTool Function MD5:
FDAFFD24ED72FE1782B179658EA209F4
SafeTool Function ID:
LCCM284R0.FILE.008.FUNC.002
SafeTool://LCCM284R0.SPEC.FR.002
Specifications:
: LCCM284R0.SPEC.FR.002
Category: SOFTWARE/FUNCTIONAL/SET The user can set a particular flag in the fault tree based on a flag index.
References FAULT_TREE__PUBLIC_T::u32Flags, and FAULT_TREE__PUBLIC_T::u8FaultFlag.
Referenced by s16RM4_CAN_RX__RxMessage_Worker(), s16RM4_EEPROM__Save(), s16RM4_I2C_USER__RxByte(), s16RM4_I2C_USER__RxByte16(), s16RM4_I2C_USER__RxByteArray(), s16RM4_I2C_USER__RxByteArray16(), s16RM4_I2C_USER__RxReg(), s16RM4_I2C_USER__TxByte(), s16RM4_I2C_USER__TxByte16(), s16RM4_I2C_USER__TxByteArray(), s16RM4_I2C_USER__TxByteArray_Constant(), s16RM4_I2C_USER__TxReg(), tsRM4_CAN_FUNCTIONS__Get_AvailableWriteInterface(), u32RM4_CAN_ERROR__Get_ErrorLevel(), u32RM4_CAN_ERROR__Get_LastError(), u32RM4_CAN_RX__IsRxMessageArrived(), u8RM4_CAN_ERROR__Get_RxErrorCount(), u8RM4_CAN_ERROR__Get_TxErrorCount(), u8RM4_CAN_RX__Is_HardwareFIFOempty(), u8RM4_CAN_RX__Is_MessageAvailable(), u8RM4_CAN_RX__ProcessFIFOs(), vRM4_BIST__SelfCheck(), vRM4_CAN__Init(), vRM4_CAN_ERROR__Disable_ErrorNotification(), vRM4_CAN_ERROR__Enable_ErrorNotification(), vRM4_CAN_RX__RxMessage(), vRM4_EEPROM__Write_U8Array(), vRM4_ESM__HighInterrupt(), vRM4_SELFTEST__CAN1_ParityCheck(), vRM4_SELFTEST__CAN2_ParityCheck(), vRM4_SELFTEST__CAN3_ParityCheck(), vRM4_SELFTEST__CCM_Check(), vRM4_SELFTEST__Check_RAMECC(), vRM4_SELFTEST__DMA_ParityCheck(), vRM4_SELFTEST__EFuse_Check(), vRM4_SELFTEST__MIBSPI1_ParityCheck(), vRM4_SELFTEST__MIBSPI3_ParityCheck(), vRM4_SELFTEST__MIBSPI5_ParityCheck(), vRM4_SELFTEST__N2HET1_ParityCheck(), vRM4_SELFTEST__VIM_ParityCheck(), and vRM4_SYSTEM__After_STC().