LFW513 (RLOOP - POWER NODE): VIM
VIM
RM4
Vectored Interrupt Manager.
Modules
VIM__CORE
Functions
void vRM4_VIM__Init (void)
This function initializes VIM RAM and registers.
void vRM4_VIM__ChannelMap (Luint32 u32Request, Luint32 u32Channel, t_isrFuncPTR handler)
Map selected interrupt request to the selected channel.
void vRM4_VIM__EnableInterrupt (Luint32 u32Channel, RM4_VIM__SYSTEM_INTERRUPT_T eType)
Enable interrupt for the the selected channel.
void vRM4_VIM__DisableInterrupt (Luint32 u32Channel)
Disable interrupt for the the selected channel.
void vRM4_VIM__MasterEnable (void)
VIM Master Interrupt enable.
void vRM4_VIM__MasterDisable (void)
VIM Master Disable.
Luint32 u32RM4_VIM__Get_MasterStatus (void)
Get teh status of the VIM.
void vRM4_VIM_ISR__ParityErrorHandler (void)
Parity Error Interrupt Handler.
void vRM4_VIM__Enable_USB (void)
ToDo.
Variables
Luint32 vimBase::IRQINDEX
Luint32 vimBase::FIQINDEX
Luint32 vimBase::rsvd1
Luint32 vimBase::rsvd2
Luint32 vimBase::FIRQPR0
Luint32 vimBase::FIRQPR1
Luint32 vimBase::FIRQPR2
Luint32 vimBase::FIRQPR3
Luint32 vimBase::INTREQ0
Luint32 vimBase::INTREQ1
Luint32 vimBase::INTREQ2
Luint32 vimBase::INTREQ3
Luint32 vimBase::REQMASKSET0
Luint32 vimBase::REQMASKSET1
Luint32 vimBase::REQMASKSET2
Luint32 vimBase::REQMASKSET3
Luint32 vimBase::REQMASKCLR0
Luint32 vimBase::REQMASKCLR1
Luint32 vimBase::REQMASKCLR2
Luint32 vimBase::REQMASKCLR3
Luint32 vimBase::WAKEMASKSET0
Luint32 vimBase::WAKEMASKSET1
Luint32 vimBase::WAKEMASKSET2
Luint32 vimBase::WAKEMASKSET3
Luint32 vimBase::WAKEMASKCLR0
Luint32 vimBase::WAKEMASKCLR1
Luint32 vimBase::WAKEMASKCLR2
Luint32 vimBase::WAKEMASKCLR3
Luint32 vimBase::IRQVECREG
Luint32 vimBase::FIQVECREG
Luint32 vimBase::CAPEVT
Luint32 vimBase::rsvd3
Luint32 vimBase::CHANCTRL [24U]
Luint32 vim_config_reg::CONFIG_FIRQPR0
Luint32 vim_config_reg::CONFIG_FIRQPR1
Luint32 vim_config_reg::CONFIG_FIRQPR2
Luint32 vim_config_reg::CONFIG_FIRQPR3
Luint32 vim_config_reg::CONFIG_REQMASKSET0
Luint32 vim_config_reg::CONFIG_REQMASKSET1
Luint32 vim_config_reg::CONFIG_REQMASKSET2
Luint32 vim_config_reg::CONFIG_REQMASKSET3
Luint32 vim_config_reg::CONFIG_WAKEMASKSET0
Luint32 vim_config_reg::CONFIG_WAKEMASKSET1
Luint32 vim_config_reg::CONFIG_WAKEMASKSET2
Luint32 vim_config_reg::CONFIG_WAKEMASKSET3
Luint32 vim_config_reg::CONFIG_CAPEVT
Luint32 vim_config_reg::CONFIG_CHANCTRL [24U]
Detailed Description
Vectored Interrupt Manager.
The vectored interrupt manager (VIM) provides hardware assistance for prioritizing and controlling the many interrupt sources present on a device. Interrupts are caused by events outside of the normal flow of program execution.
Related files:
reg_vim.h
sys_vim.h
sys_vim.c
Function Documentation
Luint32 u32RM4_VIM__Get_MasterStatus (void)
Get teh status of the VIM.
Returns
The VIM Status
SafeTool Function MD5:
86F5973F73CD4F2811BFDA203BDFA2D7
SafeTool Function ID:
LCCM225R0.FILE.001.FUNC.009
void vRM4_VIM__ChannelMap (Luint32 u32Request, Luint32 u32Channel, t_isrFuncPTR handler)
Map selected interrupt request to the selected channel.
Parameters
[in] handler Address of the interrupt handler
[in] u32Channel VIM Channel number 2..95
[in] u32Request Interrupt request number 2..95
SafeTool Function MD5:
AFE9CAAAC497646021907EB321540B2B
SafeTool Function ID:
LCCM225R0.FILE.001.FUNC.002
References vimRAM, and vimREG.
void vRM4_VIM__DisableInterrupt (Luint32 u32Channel)
Disable interrupt for the the selected channel.
Parameters
[in] u32Channel VIM Channel number 2..95
SafeTool Function MD5:
F88A9C3655850DC90D8FC68636A8E74B
SafeTool Function ID:
LCCM225R0.FILE.001.FUNC.004
References vimREG.
void vRM4_VIM__Enable_USB (void)
ToDo.
SafeTool Function MD5:
102FADA3D808CE09D35D2317E638C1EB
SafeTool Function ID:
LCCM225R0.FILE.001.FUNC.010
References SYS_IRQ, and vRM4_VIM__EnableInterrupt().
void vRM4_VIM__EnableInterrupt (Luint32 u32Channel, RM4_VIM__SYSTEM_INTERRUPT_T eType)
Enable interrupt for the the selected channel.
Parameters
[in] eType Interrupt type SYS_IRQ: Selected channel will be enabled as IRQ SYS_FIQ: Selected channel will be enabled as FIQ
[in] u32Channel VIM Channel number 2..95
SafeTool Function MD5:
0ADCA3BE3C64264F622A683E57959215
SafeTool Function ID:
LCCM225R0.FILE.001.FUNC.003
References SYS_IRQ, and vimREG.
Referenced by vRM4_EMAC_LINK__Process(), and vRM4_VIM__Enable_USB().
void vRM4_VIM__Init (void)
This function initializes VIM RAM and registers.
SafeTool Function MD5:
CFB538ECD68E7F4E79E623E537DD9A82
SafeTool Function ID:
LCCM225R0.FILE.001.FUNC.001
References s_vim_init, SYS_FIQ, SYS_IRQ, VIM_CHANNELS, VIM_FBPARERR, vimRAM, vimREG, and vRM4_VIM_ISR__ParityErrorHandler().
Referenced by vRM4_SYSTEM__After_STC().
void vRM4_VIM__MasterDisable (void)
VIM Master Disable.
SafeTool Function MD5:
FCA74ED231A225E59B3B42EEDCD91BF3
SafeTool Function ID:
LCCM225R0.FILE.001.FUNC.008
void vRM4_VIM__MasterEnable (void)
VIM Master Interrupt enable.
SafeTool Function MD5:
7F49E2FA504FEF580487B4E5FC3ACE88
SafeTool Function ID:
LCCM225R0.FILE.001.FUNC.007
void vRM4_VIM_ISR__ParityErrorHandler (void)
Parity Error Interrupt Handler.
SafeTool Function MD5:
B22153B22D670864C7639DBF0C246F74
SafeTool Function ID:
LCCM225R0.FILE.001.FUNC.006
References esmREG, s_vim_init, VIM_ADDERR, VIM_PARFLG, vimRAM, vimREG, vRM4_ESM__Group1_Notification(), and vRM4_ESM__Group2_Notification().
Referenced by vRM4_VIM__Init().
Variable Documentation
Luint32 vimBase::CAPEVT
Luint32 vimBase::CHANCTRL[24U]
Luint32 vim_config_reg::CONFIG_CAPEVT
Luint32 vim_config_reg::CONFIG_CHANCTRL[24U]
Luint32 vim_config_reg::CONFIG_FIRQPR0
Luint32 vim_config_reg::CONFIG_FIRQPR1
Luint32 vim_config_reg::CONFIG_FIRQPR2
Luint32 vim_config_reg::CONFIG_FIRQPR3
Luint32 vim_config_reg::CONFIG_REQMASKSET0
Luint32 vim_config_reg::CONFIG_REQMASKSET1
Luint32 vim_config_reg::CONFIG_REQMASKSET2
Luint32 vim_config_reg::CONFIG_REQMASKSET3
Luint32 vim_config_reg::CONFIG_WAKEMASKSET0
Luint32 vim_config_reg::CONFIG_WAKEMASKSET1
Luint32 vim_config_reg::CONFIG_WAKEMASKSET2
Luint32 vim_config_reg::CONFIG_WAKEMASKSET3
Luint32 vimBase::FIQINDEX
Luint32 vimBase::FIQVECREG
Luint32 vimBase::FIRQPR0
Luint32 vimBase::FIRQPR1
Luint32 vimBase::FIRQPR2
Luint32 vimBase::FIRQPR3
Luint32 vimBase::INTREQ0
Luint32 vimBase::INTREQ1
Luint32 vimBase::INTREQ2
Luint32 vimBase::INTREQ3
Luint32 vimBase::IRQINDEX
Luint32 vimBase::IRQVECREG
Luint32 vimBase::REQMASKCLR0
Luint32 vimBase::REQMASKCLR1
Luint32 vimBase::REQMASKCLR2
Luint32 vimBase::REQMASKCLR3
Luint32 vimBase::REQMASKSET0
Luint32 vimBase::REQMASKSET1
Luint32 vimBase::REQMASKSET2
Luint32 vimBase::REQMASKSET3
Luint32 vimBase::rsvd1
Luint32 vimBase::rsvd2
Luint32 vimBase::rsvd3
Luint32 vimBase::WAKEMASKCLR0
Luint32 vimBase::WAKEMASKCLR1
Luint32 vimBase::WAKEMASKCLR2
Luint32 vimBase::WAKEMASKCLR3
Luint32 vimBase::WAKEMASKSET0
Luint32 vimBase::WAKEMASKSET1
Luint32 vimBase::WAKEMASKSET2
Luint32 vimBase::WAKEMASKSET3