LFW513 (RLOOP - POWER NODE): DMA__INTERRUPTS
DMA__INTERRUPTS
RM4 » DMA
Functions
void vRM4_DMA_ISR__FTCAInterrupt (void)
Frame transfer complete interrupt Frame transfer complete Interrupt handler for DMA channel routed to Group A.
void vRM4_DMA_ISR__LFSAInterrupt (void)
Last Frame Transfer Started Last Frame transfer started Interrupt handler for DMA channel routed to Group A.
void vRM4_DMA_ISR__HBCAInterrupt (void)
First half of the block completed interrupt.
void vRM4_DMA_ISR__BTCAInterrupt (void)
Block transfer complete interrupt.
Variables
struct _strRM4DMA sRM4DMA
Detailed Description
Function Documentation
void vRM4_DMA_ISR__BTCAInterrupt (void)
Block transfer complete interrupt.
SafeTool Function MD5:
4092C4071B1632CAD2AAC5DF2D239A82
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.023
References C_RM4_DMA__MAX_CHANNELS, dmaREG, INTERRUPT__BLOCK_TX_COMPLETE, _strRM4DMA::sChannel, sRM4DMA, _strRM4DMA::u8Busy, and vRM4_DMA__Notification().
void vRM4_DMA_ISR__FTCAInterrupt (void)
Frame transfer complete interrupt Frame transfer complete Interrupt handler for DMA channel routed to Group A.
SafeTool Function MD5:
374872A0B2D6807C4C10FFE54B7C6003
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.020
References dmaREG, INTERRUPT__FRAME_TX_COMPLETE, and vRM4_DMA__Notification().
void vRM4_DMA_ISR__HBCAInterrupt (void)
First half of the block completed interrupt.
SafeTool Function MD5:
160A52619B4DB468B97BD769F2319FE2
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.022
References dmaREG, INTERRUPT__HALF_BLOCK_COMPLETE, and vRM4_DMA__Notification().
void vRM4_DMA_ISR__LFSAInterrupt (void)
Last Frame Transfer Started Last Frame transfer started Interrupt handler for DMA channel routed to Group A.
SafeTool Function MD5:
1C6D53A0DA4DCE61EDAE587F368BB65B
SafeTool Function ID:
LCCM229R0.FILE.001.FUNC.021
References dmaREG, INTERRUPT__LAST_FRAME_START, and vRM4_DMA__Notification().
Variable Documentation
struct _strRM4DMA sRM4DMA
Referenced by vRM4_DMA_ISR__BTCAInterrupt().