LFW513 (RLOOP - POWER NODE): EMAC__RX
EMAC__RX
RM4 » EMAC
Functions
void vRM4_EMAC_RX__RxIntHandler (void)
Rx Interrupt Handler.
Variables
struct RM4_EMAC_IF m_pEMAC_IF
Detailed Description
Function Documentation
void vRM4_EMAC_RX__RxIntHandler (void)
Rx Interrupt Handler.
28.2.17.1.2 Receive Packet Completion Interrupts The receive DMA engine has eight channels, which each channel having a corresponding interrupt [RXPENDn). The receive interrupts are level interrupts that remain asserted until cleared by the CPU. Each of the eight receive channel interrupts may be individually enabled by setting the appropriate bit in the receive interrupt mask set register [RXINTMASKSET) to 1. Each of the eight receive channel interrupts may be individually disabled by clearing the appropriate bit by writing a 1 in the receive interrupt mask clear register [RXINTMASKCLEAR). The raw and masked receive interrupt status may be read by reading the receive interrupt status [unmasked) register [RXINTSTATRAW) and the receive interrupt status [masked) register [RXINTSTATMASKED), respectively.
When the EMAC completes a packet reception, the EMAC issues an interrupt to the CPU by writing the packet's last buffer descriptor address to the appropriate channel queue's receive completion pointer located in the state RAM block. The interrupt is generated by the write when enabled by the interrupt mask, regardless of the value written. Upon interrupt reception, the CPU processes one or more packets from the buffer chain and then acknowledges one or more interrupt[s) by writing the address of the last buffer descriptor processed to the queue's associated receive completion pointer in the receive DMA state RAM. The data written by the host [buffer descriptor address of the last processed buffer) is compared to the data in the register written by the EMAC [address of last buffer descriptor used by the EMAC). If the two values are not equal [which means that the EMAC has received more packets than the CPU has processed interrupts for), the receive packet completion interrupt signal remains asserted. If the two values are equal [which means that the host has processed all packets that the EMAC has received), the pending interrupt is de-asserted. The value that the EMAC is expecting is found by reading the receive channel n completion pointer register [RXnCP). The EMAC write to the completion pointer actually stores the value in the state RAM. The CPU written value does not actually change the register value. The host written value is compared to the register content [which was written by the EMAC) and if the two values are equal then the interrupt is removed; otherwise, the interrupt remains asserted. The host may process multiple packets prior to acknowledging an interrupt, or the host may acknowledge interrupts for every packet. The application software must acknowledge the EMAC control module after processing packets by writing the appropriate C0TX key to the EMAC End-Of-Interrupt Vector register [MACEOIVECTOR). See Section 28.5.12 for the acknowledge key values.
SafeTool Function MD5:
4832A593C55223462546628F2E0510D1
SafeTool Function ID:
LCCM254R0.FILE.008.FUNC.001
References EMAC_DSC_FLAG_OWNER, EMAC_DSC_FLAG_SOP, EMAC_INT_CORE0_RX, EMAC_INT_CORE0_TX, m_pEMAC_IF, RM4_EMAC_IF::pEMAC_Rx_Channel, RM4_EMAC__RX_CHANNEL_T::pHeadDescriptor, RM4_EMAC__RX_BD_T::pu32Buffer, RM4_EMAC__RX_BD_T::u16BufferOffset__u16BufferLength, RM4_EMAC__RX_BD_T::u16Flags__u16PacketLength, vRM4_EMAC__RxHdrDescPtrWrite(), vRM4_EMAC__Write_RxChannelCompletionPointer(), and vRM4_EMAC_INT__CoreIntAck().
Referenced by vRM4_EMAC_INT__RxISR().
Variable Documentation
struct RM4_EMAC_IF m_pEMAC_IF
Referenced by vRM4_EMAC_RX__RxIntHandler().