LFW513 (RLOOP - POWER NODE): RM4__N2HET__QEP
RM4__N2HET__QEP
RM4 » RM4__N2HET
Functions
Luint16 u16N2HET_PROG_DYNAMIC__Add_QEP (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32PinCW_Index, Luint32 u32PinCCW_Index)
add a QEP program, relies on external Flip Flops for CW and CCW counts
void vRM4_N2HET_QEP__Zero_Index (RM4_N2HET__CHANNEL_T eChannel, Luint16 u16ProgramIndex)
called from interrupt, etc for a zero index marker to reset the channels may also be user called to reset all dat to zero
Lint32 s32RM4_N2HET_QEP__Get_Counter (RM4_N2HET__CHANNEL_T eChannel, Luint16 u16ProgramIndex)
returns the count
Variables
struct _strRM4_N2HET sN2HET
Detailed Description
Function Documentation
Lint32 s32RM4_N2HET_QEP__Get_Counter (RM4_N2HET__CHANNEL_T eChannel, Luint16 u16ProgramIndex)
returns the count
Parameters
[in] u16ProgramIndex ## Desc ##
[in] eChannel ## Desc ##
SafeTool Function MD5:
678328A042A3E12B158E3B7FD9687578
SafeTool Function ID:
LCCM240R0.FILE.029.FUNC.002
References u32RM4_N2HET_EDGE__Get_Counter().
Luint16 u16N2HET_PROG_DYNAMIC__Add_QEP (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32PinCW_Index, Luint32 u32PinCCW_Index)
add a QEP program, relies on external Flip Flops for CW and CCW counts
Parameters
[in] u32PinCCW_Index The pin for CCW measurement
[in] u32PinCW_Index The pin for CW measurements
[in] eChannel The N2HET channels
SafeTool Function MD5:
24442EFE397C28D0A14AB9B96F08A7EE
SafeTool Function ID:
LCCM240R0.FILE.030.FUNC.001
References EDGE_TYPE__RISING, and u16N2HET_PROG_DYNAMIC__Add_Edge().
void vRM4_N2HET_QEP__Zero_Index (RM4_N2HET__CHANNEL_T eChannel, Luint16 u16ProgramIndex)
called from interrupt, etc for a zero index marker to reset the channels may also be user called to reset all dat to zero
Parameters
[in] u16ProgramIndex ## Desc ##
[in] eChannel ## Desc ##
SafeTool Function MD5:
5DF3DA625270160665F505F61539AF6C
SafeTool Function ID:
LCCM240R0.FILE.029.FUNC.001
References vRM4_N2HET_EDGE__ResetCounter().
Variable Documentation
struct _strRM4_N2HET sN2HET