LFW513 (RLOOP - POWER NODE): SPI135__PINS
SPI135__PINS
RM4 » SPI135
Functions
void vRM4_MIBSPI135_PINS__Set_OutputDirection (RM4_MIBSPI135__CHANNELS_T eChannel, RM4_MIBSPI135__PIN_SELECT_T ePin)
sets the CSn pin as an output direction pin Ports are configured as inputs at reset so you need to change the pin to be able to use it.
void vRM4_MIBSPI135_PINS__Set (RM4_MIBSPI135__CHANNELS_T eChannel, RM4_MIBSPI135__PIN_SELECT_T ePin, Luint32 u32Value)
Set a pin on a channel to a known value.
void vRM4_MIBSPI135_PINS__Set_Low (RM4_MIBSPI135__CHANNELS_T eChannel, RM4_MIBSPI135__PIN_SELECT_T ePin)
Sets a modules chip select pin low.
void vRM4_MIBSPI135_PINS__Set_High (RM4_MIBSPI135__CHANNELS_T eChannel, RM4_MIBSPI135__PIN_SELECT_T ePin)
Set a pin high.
void vRM4_MIBSPI135_PINS__Set_Defaults (RM4_MIBSPI135__CHANNELS_T eChannel)
sets all our pins to their default values
Detailed Description
Function Documentation
void vRM4_MIBSPI135_PINS__Set (RM4_MIBSPI135__CHANNELS_T eChannel, RM4_MIBSPI135__PIN_SELECT_T ePin, Luint32 u32Value)
Set a pin on a channel to a known value.
Parameters
[in] u32Value The value 1 or 0
[in] ePin The pin
[in] eChannel The SPI channel.
SafeTool Function MD5:
AE04666FF4A65630944D850E1654A89F
SafeTool Function ID:
LCCM280R0.FILE.007.FUNC.002
References vRM4_MIBSPI135_PINS__Set_High(), and vRM4_MIBSPI135_PINS__Set_Low().
void vRM4_MIBSPI135_PINS__Set_Defaults (RM4_MIBSPI135__CHANNELS_T eChannel)
sets all our pins to their default values
Parameters
[in] eChannel The channel
SafeTool Function MD5:
85E7616D2C2ACD7E2CB32942289CC821
SafeTool Function ID:
LCCM280R0.FILE.007.FUNC.005
References RM4_MIBSPI135__BASE_T::IOLPKTSTCR, MIBSPI135_CHANNEL__1, MIBSPI135_CHANNEL__3, MIBSPI135_CHANNEL__5, mibspiREG1, mibspiREG3, mibspiREG5, RM4_MIBSPI135__BASE_T::PC0, RM4_MIBSPI135__BASE_T::PC1, RM4_MIBSPI135__BASE_T::PC3, RM4_MIBSPI135__BASE_T::PC6, RM4_MIBSPI135__BASE_T::PC7, and RM4_MIBSPI135__BASE_T::PC8.
Referenced by vRM4_MIBSPI135__Init().
void vRM4_MIBSPI135_PINS__Set_High (RM4_MIBSPI135__CHANNELS_T eChannel, RM4_MIBSPI135__PIN_SELECT_T ePin)
Set a pin high.
Parameters
[in] ePin The pin type
[in] eChannel The channel
SafeTool Function MD5:
E01035A923D36D08657899FD329E3D3D
SafeTool Function ID:
LCCM280R0.FILE.007.FUNC.004
References MIBSPI135_CHANNEL__1, MIBSPI135_CHANNEL__3, MIBSPI135_CHANNEL__5, mibspiREG1, mibspiREG3, and mibspiREG5.
Referenced by vRM4_MIBSPI135_PINS__Set().
void vRM4_MIBSPI135_PINS__Set_Low (RM4_MIBSPI135__CHANNELS_T eChannel, RM4_MIBSPI135__PIN_SELECT_T ePin)
Sets a modules chip select pin low.
Parameters
[in] ePin The pin
[in] eChannel The channel
SafeTool Function MD5:
1921BA536132F83EB4E8D62A79D83041
SafeTool Function ID:
LCCM280R0.FILE.007.FUNC.003
References MIBSPI135_CHANNEL__1, MIBSPI135_CHANNEL__3, MIBSPI135_CHANNEL__5, mibspiREG1, mibspiREG3, and mibspiREG5.
Referenced by vRM4_MIBSPI135_PINS__Set().
void vRM4_MIBSPI135_PINS__Set_OutputDirection (RM4_MIBSPI135__CHANNELS_T eChannel, RM4_MIBSPI135__PIN_SELECT_T ePin)
sets the CSn pin as an output direction pin Ports are configured as inputs at reset so you need to change the pin to be able to use it.
Parameters
[in] ePin The pin type
[in] eChannel SPI channel
SafeTool Function MD5:
C7AF6B175806364FCD7DC7673D8639E9
SafeTool Function ID:
LCCM280R0.FILE.007.FUNC.001
References MIBSPI135_CHANNEL__1, MIBSPI135_CHANNEL__3, MIBSPI135_CHANNEL__5, mibspiREG1, mibspiREG3, and mibspiREG5.