LFW513 (RLOOP - POWER NODE): ESM__CORE
ESM__CORE
RM4 » ESM
Functions
void vRM4_ESM__Init (void)
Initializes Esm Driver.
Luint32 u32RM4_ESM__Get_Error (void)
Return Error status.
void vRM4_ESM__Enable_Error (Luint64 u64Channels)
Enable Group 1 Channels Error Signals propagation Enable Group 1 Channels Error Signals propagation to the error pin.
void vRM4_ESM__DisableError (Luint64 u64Channels)
Disable Group 1 Channels Error Signals propagation Disable Group 1 Channels Error Signals propagation to the error pin.
void vRM4_ESM__TriggerErrorPinReset (void)
Trigger error pin reset and switch back to normal operation.
void vRM4_ESM__ActivateNormalOperation (void)
Activate normal operation.
void vRM4_ESM__EnableInterrupt (Luint64 u64Channels)
Enable Group 1 Channels Interrupts.
void vRM4_ESM__DisableInterrupt (Luint64 u64Channels)
Disable Group 1 Channels Interrupts.
void vRM4_ESM__Set_InterruptLevel (Luint64 u64Channels, Luint64 u64Flags)
Set Group 1 Channels Interrupt Levels.
void vRM4_ESM__ClearStatus (Luint32 u32Group, Luint64 u64Channels)
Clear Group error status.
void vRM4_ESM__ClearStatusBuffer (Luint64 u64Channels)
Clear Group 2 error status buffer.
void vRM4_ESM__Set_CounterPreloadValue (Luint32 u32Value)
Set counter preload value.
Luint64 vRM4_ESM__Get_Status (Luint32 u32Group, Luint64 u64Channels)
Return Error status Returns the channels status of selected group.
Luint64 vRM4_ESM__Get_StatusBuffer (Luint64 u64Channels)
Return Group 2 channel x Error status buffer Returns the group 2 buffered status of selected channels.
esmSelfTestFlag_t pRM4_ESM__EnterSelfTest (void)
Return ESM Self test status.
esmSelfTestFlag_t tRM4_ESM__SelfTestStatus (void)
Return ESM Self test status.
Luint32 u32RM4_ESM__Get_FaultFlags_G1 (void)
ToDo.
Luint32 u32RM4_ESM__Get_FaultFlags_G2 (void)
ToDo.
void vRM4_ESM__HighInterrupt (void)
High Level Interrupt for ESM.
Variables
struct _strRM4ESM sESM
Detailed Description
Function Documentation
esmSelfTestFlag_t pRM4_ESM__EnterSelfTest (void)
Return ESM Self test status.
SafeTool Function MD5:
8322921D0FA123CAA4D69E854C8910AC
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.015
References esmREG, esmSelfTest_Active, esmSelfTest_Failed, and esmSelfTest_NotStarted.
esmSelfTestFlag_t tRM4_ESM__SelfTestStatus (void)
Return ESM Self test status.
SafeTool Function MD5:
A9C4E03F1F29E95E3E80D393A3205B3E
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.016
References esmREG, esmSelfTest_Active, esmSelfTest_Failed, and esmSelfTest_Passed.
Luint32 u32RM4_ESM__Get_Error (void)
Return Error status.
Returns
The error status
SafeTool Function MD5:
9965EC40B138EEFBCD1A2D94844F7998
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.002
References esmREG.
Luint32 u32RM4_ESM__Get_FaultFlags_G1 (void)
ToDo.
SafeTool Function MD5:
53574D7FA2459A6B78A2563D18CE21F7
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.020
References sESM, _strRM4ESM::sFaultTree__Group1, and FAULT_TREE__PUBLIC_T::u32Flags.
Luint32 u32RM4_ESM__Get_FaultFlags_G2 (void)
ToDo.
SafeTool Function MD5:
90A346099AA63550D40607CE7D8FBA21
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.021
References sESM, _strRM4ESM::sFaultTree__Group2, and FAULT_TREE__PUBLIC_T::u32Flags.
void vRM4_ESM__ActivateNormalOperation (void)
Activate normal operation.
SafeTool Function MD5:
13518C4614D29359A8F306040CFD75D7
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.006
References esmREG.
void vRM4_ESM__ClearStatus (Luint32 u32Group, Luint64 u64Channels)
Clear Group error status.
Parameters
[in] u64Channels Channel mask
[in] u32Group Error group
SafeTool Function MD5:
08F052F59A0EF918A6E8B7B0E3CAF777
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.010
References esmREG.
void vRM4_ESM__ClearStatusBuffer (Luint64 u64Channels)
Clear Group 2 error status buffer.
Parameters
[in] u64Channels Channel mask
SafeTool Function MD5:
2E3D2ACF8C684494B5F7349F702A03B5
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.011
References esmREG.
void vRM4_ESM__DisableError (Luint64 u64Channels)
Disable Group 1 Channels Error Signals propagation Disable Group 1 Channels Error Signals propagation to the error pin.
Parameters
[in] channels Channel mask
SafeTool Function MD5:
11F94AD0FB2BFA17644465ED93D8C007
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.004
References esmREG.
void vRM4_ESM__DisableInterrupt (Luint64 u64Channels)
Disable Group 1 Channels Interrupts.
Parameters
[in] u64Channels Channel mask
SafeTool Function MD5:
A8E2EF65E8803219793FC8649E4E5CA3
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.008
References esmREG.
void vRM4_ESM__Enable_Error (Luint64 u64Channels)
Enable Group 1 Channels Error Signals propagation Enable Group 1 Channels Error Signals propagation to the error pin.
Parameters
[in] u64Channels Channel mask
SafeTool Function MD5:
41BEAE44C47BAD0FC7591F399D4CACF2
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.003
References esmREG.
void vRM4_ESM__EnableInterrupt (Luint64 u64Channels)
Enable Group 1 Channels Interrupts.
Parameters
[in] u64Channels Channel mask
SafeTool Function MD5:
95659DA3FC826741227D14B2FB641874
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.007
References esmREG.
Luint64 vRM4_ESM__Get_Status (Luint32 u32Group, Luint64 u64Channels)
Return Error status Returns the channels status of selected group.
Parameters
[in] u64Channels Error Channels
[in] u32Group Error group
Returns
The channels status of selected group
SafeTool Function MD5:
801500C3217A57D416DED6A2F8CDD420
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.013
References esmREG.
Luint64 vRM4_ESM__Get_StatusBuffer (Luint64 u64Channels)
Return Group 2 channel x Error status buffer Returns the group 2 buffered status of selected channels.
Parameters
[in] u64Channels Error Channels
Returns
The channels status
SafeTool Function MD5:
186EE066215AB50E655395231CB0FA88
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.014
References esmREG.
void vRM4_ESM__HighInterrupt (void)
High Level Interrupt for ESM.
SafeTool Function MD5:
C297995926878F83440F02347F360E35
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.017
References C_LCCM220__CORE__FAULT_INDEX__00, C_LCCM220__CORE__FAULT_INDEX__01, C_LCCM220__CORE__FAULT_INDEX__02, C_LCCM220__CORE__FAULT_INDEX__03, C_LCCM220__CORE__FAULT_INDEX__04, C_LCCM220__CORE__FAULT_INDEX__05, C_LCCM220__CORE__FAULT_INDEX__06, C_LCCM220__CORE__FAULT_INDEX__07, C_LCCM220__CORE__FAULT_INDEX__08, C_LCCM220__CORE__FAULT_INDEX__09, C_LCCM220__CORE__FAULT_INDEX__10, C_LCCM220__CORE__FAULT_INDEX__11, C_LCCM220__CORE__FAULT_INDEX__12, C_LCCM220__CORE__FAULT_INDEX__13, C_LCCM220__CORE__FAULT_INDEX__14, C_LCCM220__CORE__FAULT_INDEX__15, C_LCCM220__CORE__FAULT_INDEX__16, C_LCCM220__CORE__FAULT_INDEX__17, C_LCCM220__CORE__FAULT_INDEX__18, C_LCCM220__CORE__FAULT_INDEX__19, C_LCCM220__CORE__FAULT_INDEX__20, C_LCCM220__CORE__FAULT_INDEX__21, C_LCCM220__CORE__FAULT_INDEX__22, C_LCCM220__CORE__FAULT_INDEX__23, C_LCCM220__CORE__FAULT_INDEX__24, C_LCCM220__CORE__FAULT_INDEX__25, C_LCCM220__CORE__FAULT_INDEX__26, C_LCCM220__CORE__FAULT_INDEX__27, C_LCCM220__CORE__FAULT_INDEX__28, C_LCCM220__CORE__FAULT_INDEX__29, C_LCCM220__CORE__FAULT_INDEX__30, C_LCCM220__CORE__FAULT_INDEX__31, C_LCCM220__GROUP2_NON_MASKABLE__FAULT_INDEX__00, C_LCCM220__GROUP2_NON_MASKABLE__FAULT_INDEX__01, C_LCCM220__GROUP2_NON_MASKABLE__FAULT_INDEX__02, C_LCCM220__GROUP2_NON_MASKABLE__FAULT_INDEX__03, C_LCCM220__GROUP2_NON_MASKABLE__FAULT_INDEX__04, C_LCCM220__GROUP2_NON_MASKABLE__FAULT_INDEX__05, C_LCCM220__GROUP2_NON_MASKABLE__FAULT_INDEX__06, C_LCCM220__GROUP2_NON_MASKABLE__FAULT_INDEX__07, C_LCCM220__GROUP2_NON_MASKABLE__FAULT_INDEX__08, esmREG, sESM, _strRM4ESM::sFaultTree__Group1, _strRM4ESM::sFaultTree__Group2, vFAULTTREE__Set_Flag(), vRM4_ESM__Group1_Notification(), and vRM4_ESM__Group2_Notification().
void vRM4_ESM__Init (void)
Initializes Esm Driver.
SafeTool Function MD5:
774F8683B05CAFAB5D2F30D4BF1E701B
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.001
References esmREG, sESM, _strRM4ESM::sFaultTree__Group1, _strRM4ESM::sFaultTree__Group2, and vFAULTTREE__Init().
Referenced by vRM4_SYSTEM__After_STC().
void vRM4_ESM__Set_CounterPreloadValue (Luint32 u32Value)
Set counter preload value.
Parameters
[in] u32Value Counter preload value
SafeTool Function MD5:
5918472DE7D3E7F79B50B8738E3D7FA5
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.012
References esmREG.
void vRM4_ESM__Set_InterruptLevel (Luint64 u64Channels, Luint64 u64Flags)
Set Group 1 Channels Interrupt Levels.
Parameters
[in] u64Flags Level mask: 0: Low priority interrupt 1: High priority interrupt
[in] u64Channels Channel mask
SafeTool Function MD5:
F383492D62079FB1F2D9140BBE149D56
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.009
References esmREG.
void vRM4_ESM__TriggerErrorPinReset (void)
Trigger error pin reset and switch back to normal operation.
SafeTool Function MD5:
56CDB39FB9CF810062C692DC96ECAE07
SafeTool Function ID:
LCCM220R0.FILE.001.FUNC.005
References esmREG.
Variable Documentation
struct _strRM4ESM sESM
Referenced by u32RM4_ESM__Get_FaultFlags_G1(), u32RM4_ESM__Get_FaultFlags_G2(), vRM4_ESM__HighInterrupt(), and vRM4_ESM__Init().