LFW513 (RLOOP - POWER NODE): DS2482S__SEARCH
DS2482S__SEARCH
MULTICORE » DS2482S
Functions
static Lint16 s16DS2482S_SEARCH__Search (Luint8 u8DeviceIndex)
Search the 1-wire bus and return the first address.
Lint16 s16DS2482S_SEARCH__SearchFirstDevice (Luint8 u8DeviceIndex, Luint8 *pu8Addx)
Search for the first device on the bus.
Lint16 s16DS2482S_SEARCH__SearchNextDevice (Luint8 u8DeviceIndex, Luint8 *pu8Addx)
Search for subsequent devices.
Lint16 s16DS2482S_SEARCH__Verify (Luint8 u8DeviceIndex, const Luint8 *pu8Addx)
Verify that a search device exists.
Variables
struct _strDS2482S sDS2482S
Detailed Description
Function Documentation
Lint16 s16DS2482S_SEARCH__Search (Luint8 u8DeviceIndex) static
Search the 1-wire bus and return the first address.
Parameters
[in] u8DeviceIndex Device index on the bus
Returns
1 = Device Found
0 = No device found and no bus error
-ve = error
SafeTool Function MD5:
B439FB4C86E8B041082AC6AB968AB9DC
SafeTool Function ID:
LCCM641R0.FILE.008.FUNC.003
The ROM bit number 1 to 64 currently being searched
The index into the ROM serial number array that we are currently addressing
This is the first bit read in a bit search sequence. his bit is the AND of all of the id_bit_number bits of the devices that are still participating in the search
The complement of the ID Bit. This bit is the AND complement of all of the id_bit_number bits of the devices that are still participating in the search
Used to mask off the current working bit in the ROM byte
Bit value indicating the direction of the search. All devices with this bit stay in the seearch and the rest go ito a wait state for a 1-wire reset
References C_LOCALDEF__LCCM641__NUM_DEVICS, s16DS2482S_1WIRE__ReadBit(), s16DS2482S_1WIRE__WriteBit(), s16DS2482S_1WIRE__WriteByte(), sDS2482S, _strDS2482S::sSearch, _strDS2482S::u8CRC8, u8DS2482S_CRC__CRC8(), u8DS2482S_DEVICE__Wait_Busy(), u8DS2482S_USER__1Wire_Reset(), _strDS2482S::u8LastDeviceFlag, _strDS2482S::u8LastDiscrepancy, _strDS2482S::u8LastFamilyDiscrepancy, and _strDS2482S::u8ROM_SerialNumber.
Referenced by s16DS2482S_SEARCH__SearchFirstDevice(), and s16DS2482S_SEARCH__SearchNextDevice().
Lint16 s16DS2482S_SEARCH__SearchFirstDevice (Luint8 u8DeviceIndex, Luint8 * pu8Addx)
Search for the first device on the bus.
Note
The 'FIRST' operation is to search on the 1-Wire for the first device. This is performed by setting LastDiscrepancy, LastFamilyDiscrepancy, and LastDeviceFlag to zero and then doing the search. The resulting ROM number can then be read from the ROM_NO register. If no devices are present on the 1-Wire the reset sequence does not detect a presence and the search is aborted.
Maxim's 1-Wire devices each have a 64-bit unique registration number in read-only memory ROM that is used to address them individually by a 1-Wire master in a 1-Wire network. If the ROM numbers of the slave devices on the 1-Wire network are not known, then they can be discovered by using a search algorithm. This document explains the search algorithm in detail and provides an example implementation for rapid integration. This algorithm is valid for all current and future devices that feature a 1-Wire interface.
Parameters
[in] *pu8Addx Pointer to hold returned addx
[in] u8DeviceIndex I2C Device index
Returns
1 = Device Found
0 = No device found and no bus error
-ve = error
SafeTool Function MD5:
8F7C8910A44EAB7D120A56C093DBE111
SafeTool Function ID:
LCCM641R0.FILE.008.FUNC.001
References C_LOCALDEF__LCCM641__NUM_DEVICS, s16DS2482S_SEARCH__Search(), sDS2482S, _strDS2482S::sSearch, _strDS2482S::u8LastDeviceFlag, _strDS2482S::u8LastDiscrepancy, _strDS2482S::u8LastFamilyDiscrepancy, and _strDS2482S::u8ROM_SerialNumber.
Referenced by s16DS18B20_SEARCH__SearchFirstDevice(), and vDS18B20__Init().
Lint16 s16DS2482S_SEARCH__SearchNextDevice (Luint8 u8DeviceIndex, Luint8 * pu8Addx)
Search for subsequent devices.
Note
The 'NEXT' operation is to search on the 1-Wire for the next device. This search is usually performed after a 'FIRST' operation or another 'NEXT' operation. It is performed by leaving the state unchanged from the previous search and performing another search. The resulting ROM number can then be read from the ROM_NO register. If the previous search was the last device on the 1-Wire then the result is FALSE and the condition is set to execute a 'FIRST' with the next call of the search algorithm.
Parameters
[in] *pu8Addx Pointer to hold returned addx
[in] u8DeviceIndex I2C Device index
Returns
1 = Device Found
0 = No device found and no bus error
-ve = error
SafeTool Function MD5:
EB7C0E617DEA9CB709D476449BB1054D
SafeTool Function ID:
LCCM641R0.FILE.008.FUNC.002
References C_LOCALDEF__LCCM641__NUM_DEVICS, s16DS2482S_SEARCH__Search(), sDS2482S, _strDS2482S::sSearch, and _strDS2482S::u8ROM_SerialNumber.
Referenced by s16DS18B20_SEARCH__SearchNextDevice().
Lint16 s16DS2482S_SEARCH__Verify (Luint8 u8DeviceIndex, const Luint8 * pu8Addx)
Verify that a search device exists.
Parameters
[in] *pu8Addx Pointer to address to verify
[in] u8DeviceIndex I2C device index
SafeTool Function MD5:
7C80DF04ACBBB568FD976DC6C6BC4E4E
SafeTool Function ID:
LCCM641R0.FILE.008.FUNC.004
Variable Documentation
struct _strDS2482S sDS2482S
Referenced by s16DS2482S_SEARCH__Search(), s16DS2482S_SEARCH__SearchFirstDevice(), s16DS2482S_SEARCH__SearchNextDevice(), and vDS2482S__Init().