LFW513 (RLOOP - POWER NODE): SYSTEM__CORE
SYSTEM__CORE
RM4 » SYSTEM
Functions
void vRM4_SYSTEM__Init (void)
Init the system.
void vRM4_SYSTEM__SetupPLL (void)
Configure PLL control registers and enable PLLs.
void vRM4_SYSTEM__InitPerip (void)
Init the peripherals.
void vRM4_SYSTEM__MapClocks (void)
Map the clock domains.
void vRM4_SYSTEM__SetupFlash (void)
Setup the FLASH memories.
void vRM2_SYSTEM__PowerDown (Luint32 mode)
Power down the system.
void vRM4_SYSTEM__TrimLPO (void)
Set the low power oscillator trim.
void phantomInterrupt (void)
System phantom interrupt.
Detailed Description
Function Documentation
void phantomInterrupt (void)
System phantom interrupt.
SafeTool Function MD5:
B5C6092006DAC1B94D97F0A1EFFD4372
SafeTool Function ID:
LCCM219R0.FILE.001.FUNC.013
void vRM2_SYSTEM__PowerDown (Luint32 mode)
Power down the system.
Parameters
[in] u32Mode ## Desc ##
SafeTool Function MD5:
6D835FC10F659B7B1284C15C30C25D5F
SafeTool Function ID:
LCCM219R0.FILE.001.FUNC.010
References systemREG1.
void vRM4_SYSTEM__Init (void)
Init the system.
SafeTool Function MD5:
FB7A8DDD6E245527825D4BF5CDFECE9E
SafeTool Function ID:
LCCM219R0.FILE.001.FUNC.001
Set up flash address and data wait states based on the target CPU clock frequency The number of address and data wait states for the target CPU clock frequency are specified in the specific part's datasheet.
Configure the LPO such that HF LPO is as close to 10MHz as possible
set ECLK pins functional u32Mode
set ECLK pins default output value
set ECLK pins output direction
set ECLK pins open drain enable
set ECLK pins pullup/pulldown enable
set ECLK pins pullup/pulldown select
Setup ECLK
References _enable_interrupt_(), systemREG1, u8RM4_SELFTEST__EFuse_CheckSelfTest(), vRM4_PINMUX__Init(), vRM4_SELFTEST__EFuse_Check(), vRM4_SYSTEM__InitPerip(), vRM4_SYSTEM__MapClocks(), vRM4_SYSTEM__SetupFlash(), vRM4_SYSTEM__SetupPLL(), and vRM4_SYSTEM__TrimLPO().
Referenced by _c_int00().
void vRM4_SYSTEM__InitPerip (void)
Init the peripherals.
SafeTool Function MD5:
E4E4B42295BBADD48085B6A2BB9B9C1D
SafeTool Function ID:
LCCM219R0.FILE.001.FUNC.003
Disable Peripherals before peripheral powerup
References pcrREG, and systemREG1.
Referenced by vRM4_SYSTEM__Init().
void vRM4_SYSTEM__MapClocks (void)
Map the clock domains.
Datasheet 2.4.2 Clock Domains The clocking on this device is divided into multiple clock domains for flexibility in control as well as clock source selection. There are 10 clock domains on this device. Each of these are described in Table 2-10 below.
Table 2-10. Clock Domains Clock Domain Default Source Special Considerations
Domain Number Source Sel Reg
GCLK 0 OSCIN GHVSRC * Clock domain used by one of the two Cortex-R4F CPUs operating in lock-step
Always the same frequency as HCLK
In phase with HCLK
Is disabled separately from HCLK via the CDDISx registers bit 0
Can be divided by 1up to 8 when running CPU selftest [LBIST] using the CLKDIV field of the STCCLKDIV register at address 0xFFFFE108
GCLK2 0 OSCIN GHVSRC * Clock domain used by the second Cortex-R4F CPU operating in lock-step
Always the same frequency as GCLK
2 cycles delayed from GCLK
Is disabled along with GCLK
Gets divided by the same divider setting as that for GCLK when running CPU selftest [LBIST]
HCLK 1 OSCIN GHVSRC * Clock domain used by the high-speed system modules: Flash memory interfaces, TCRAM interface, Error Signaling Module (ESM), DMA
Is disabled via the CDDISx registers bit 1
Clock domain used by some system modules (VIM), peripheral modules accessed via the Peripheral Central Resource (PCR) controller, and all other register interfaces also accessed via the VCLK 2 OSCIN GHVSRC PCR
Divided down from HCLK
Can be HCLK/1, HCLK/2,... or HCLK/16
Is disabled separately from HCLK via the CDDISx registers bit 2
VCLK2       3           OSCIN       GHVSRC          * Clock domain used by the timer modules: N2HET1, N2HET2 and the dedicated transfer units: HTU1, HTU2
                                                    * Divided down from HCLK
                                                    * Can be HCLK/1, HCLK/2,... or HCLK/16
                                                    * Frequency must be an integer multiple of VCLK frequency
                                                    * Is disabled separately from HCLK via the CDDISx registers bit 3
VCLK3 8 OSCIN GHVSRC * Clock domain used for EMAC, USB and EMIF slave interfaces
Divided down from HCLK
Can be HCLK/1, HCLK/2,... or HCLK/16
Is disabled separately from HCLK via the CDDISx registers bit 8
VCLKA1 4 VCLK VCLKASRC * Clock domain dedicated for the CAN controllers: DCAN1, DCAN2, CAN3, used for baud-rate generation
Defaults to VCLK as the source
Frequency can be as fast as HCLK frequency
Is disabled via the CDDISx registers bit 4
SafeTool Function MD5:
DE13D4B5C3761C49404AED8ECD70C6C8
SafeTool Function ID:
LCCM219R0.FILE.001.FUNC.007
Wait for until clocks are locked
Map device clock domains to desired sources and configure top-level dividers
All clock domains are working off the default clock sources until now
The below assignments can be easily modified using the HALCoGen GUI
Setup GCLK, HCLK and VCLK clock source for normal operation, power down mode and after wakeup
HCLK DIV x
Setup asynchronous peripheral clock sources for AVCLK1 and AVCLK2
Setup asynchronous peripheral clock sources for AVCLK3 and AVCLK4
References SYS_PLL1, SYS_PLL2, SYS_PRE1, SYS_VCLK, systemREG1, and systemREG2.
Referenced by vRM4_SYSTEM__Init().
void vRM4_SYSTEM__SetupFlash (void)
Setup the FLASH memories.
SafeTool Function MD5:
ACECCE5FD95FAD5FE147DF86383B3E64
SafeTool Function ID:
LCCM219R0.FILE.001.FUNC.009
Setup flash read u32Mode, address wait states and data wait states
Setup flash access wait states for bank 7
Disable write access to flash state machine registers
Setup flash bank power modes
References EEPROM_CONFIG_HL, flashWREG, FSM_WR_ENA_HL, and SYS_ACTIVE.
Referenced by vRM4_SYSTEM__Init().
void vRM4_SYSTEM__SetupPLL (void)
Configure PLL control registers and enable PLLs.
The PLL takes (127 + 1024 * NR) oscillator cycles to acquire lock. This initialization sequence performs all the tasks that are not required to be done at full application speed while the PLL locks.
SafeTool Function MD5:
A6C6EAE69A6A94EACD8E954347935434
SafeTool Function ID:
LCCM219R0.FILE.001.FUNC.002
Configure PLL control registers
Initialize Pll1:
Setup pll control register 1:
Setup reset on oscillator slip
Setup bypass on pll slip
setup Pll output clock divider to max before Lock
Setup reset on oscillator fail
Setup reference clock divider
Setup Pll multiplier
Setup pll control register 2
Enable/Disable frequency modulation
Setup spreading rate
Setup bandwidth adjustment
Setup internal Pll output divider
Setup spreading amount
Initialize Pll2:
Setup pll2 control register :
setup Pll output clock divider to max before Lock
Setup reference clock divider
Setup internal Pll output divider
Setup Pll multiplier
Enable PLL(s) to start up or Lock
References systemREG1, and systemREG2.
Referenced by vRM4_SYSTEM__Init().
void vRM4_SYSTEM__TrimLPO (void)
Set the low power oscillator trim.
SafeTool Function MD5:
3E4693A91F29EFDC30E37EA102C78AA5
SafeTool Function ID:
LCCM219R0.FILE.001.FUNC.011
Initialize Lpo:
Load TRIM values from OTP if present else load user defined values
References C_RM4SYSTEM__LPO_TRIM_VALUE, and systemREG1.
Referenced by vRM4_SYSTEM__Init().