LFW513 (RLOOP - POWER NODE): ADC__USER_VOLTAGE
ADC__USER_VOLTAGE
RM4 » ADC
Functions
void vRM4_ADC_USER__Init (void)
The user portion of the ADC init system Put it into voltage measure mode.
void vRM4_ADC_USER__StartConversion (void)
Manually start the conversion.
void vRM4_ADC_USER__Process (void)
Process the ADC voltage user systems.
Luint16 u16RM4_ADC_USER__Get_RawData (Luint8 u8DeviceIndex)
Gets data from our local struct.
Luint16 u16RM4_ADC_USER__Get_AveragedData (Luint8 u8DeviceIndex)
Returns the averaged data from a particular device.
Lfloat32 f32RM4_ADC_USER__Get_Voltage (Luint8 u8DeviceIndex)
Get the user voltage.
Luint8 u8RM4_ADC_USER__Is_ConversionInProgress (void)
Check if a conversion is in progress.
Luint8 u8RM4_ADC_USER__Is_NewDataAvailable (void)
Is any new data avail.
Variables
RM4_ADC_T gADC
Detailed Description
Function Documentation
Lfloat32 f32RM4_ADC_USER__Get_Voltage (Luint8 u8DeviceIndex)
Get the user voltage.
Parameters
[in] u8DeviceIndex Device INdex
SafeTool Function MD5:
3A16E03B586FBCCA08FDBC15F2D6C781
SafeTool Function ID:
LCCM414R0.FILE.009.FUNC.006
References RM4_ADC_T::sChannel, and RM4_ADC_T::sDevice.
Luint16 u16RM4_ADC_USER__Get_AveragedData (Luint8 u8DeviceIndex)
Returns the averaged data from a particular device.
Parameters
[in] u8DeviceIndex Device Index
SafeTool Function MD5:
7CBB6CED7154B046D67A661106A8E15F
SafeTool Function ID:
LCCM414R0.FILE.009.FUNC.005
References RM4_ADC_T::sChannel, and RM4_ADC_T::sDevice.
Luint16 u16RM4_ADC_USER__Get_RawData (Luint8 u8DeviceIndex)
Gets data from our local struct.
All devices at the same time Device 0 is our dump, and our data is enabled from device 1 to n.
Parameters
[in] u8DeviceIndex Device Index
SafeTool Function MD5:
352C1C4AA37261059E9E953AB9539CFC
SafeTool Function ID:
LCCM414R0.FILE.009.FUNC.004
References RM4_ADC_T::sChannel, RM4_ADC_T::sDevice, and RM4_ADC_T::u8NewDataAcquired.
Luint8 u8RM4_ADC_USER__Is_ConversionInProgress (void)
Check if a conversion is in progress.
Returns
1 = in progress
SafeTool Function MD5:
5F97070715DF1B4B2122679E35A0979C
SafeTool Function ID:
LCCM414R0.FILE.009.FUNC.007
References RM4_ADC_T::sChannel, and RM4_ADC_T::u8ConversionInProgress.
Luint8 u8RM4_ADC_USER__Is_NewDataAvailable (void)
Is any new data avail.
Returns
1 = new data avail
SafeTool Function MD5:
326E702877232B6AF3C7886970CCC879
SafeTool Function ID:
LCCM414R0.FILE.009.FUNC.008
References RM4_ADC_T::sChannel, and RM4_ADC_T::u8NewDataAcquired.
void vRM4_ADC_USER__Init (void)
The user portion of the ADC init system Put it into voltage measure mode.
SafeTool Function MD5:
CA0B4D508E47D1E9538443C3357B108B
SafeTool Function ID:
LCCM414R0.FILE.009.FUNC.001
References ADC_PRECISION__12BIT, RM4_ADC__1, RM4_ADC_T::sADC_Data, RM4_ADC_T::sChannel, RM4_ADC_T::sDevice, adcData::u16Value, adcData::u32ID, RM4_ADC_T::u8ConversionInProgress, RM4_ADC_T::u8NewDataAcquired, and vRM4_ADC_INIT__Init().
void vRM4_ADC_USER__Process (void)
Process the ADC voltage user systems.
Call from main program loop.
SafeTool Function MD5:
F1F27176BF7D840EF2796E86A9B3F0E7
SafeTool Function ID:
LCCM414R0.FILE.009.FUNC.003
References ADC_GROUP__GROUP_1, adcREG1, C_RM4ADC__VREF_CONSTANT, RM4_ADC_T::sADC_Data, RM4_ADC_T::sChannel, RM4_ADC_T::sDevice, u16NUMERICAL_FILTERING__Add_U16(), adcData::u16Value, adcData::u32ID, u32RM4_ADC_LOWLEVEL__GetData(), RM4_ADC_T::u8ConversionInProgress, RM4_ADC_T::u8NewDataAcquired, u8RM4_ADC_LOWLEVEL__Is_ConversionComplete(), and vRM4_ADC_LOWLEVEL__StartConversion().
void vRM4_ADC_USER__StartConversion (void)
Manually start the conversion.
SafeTool Function MD5:
47711FF8FA479ED82DF6E0E7EA5953D1
SafeTool Function ID:
LCCM414R0.FILE.009.FUNC.002
References ADC_GROUP__GROUP_1, adcREG1, RM4_ADC_T::sChannel, RM4_ADC_T::u8ConversionInProgress, and vRM4_ADC_LOWLEVEL__StartConversion().
Variable Documentation
RM4_ADC_T gADC