LFW513 (RLOOP - POWER NODE): DS2482S__LOWLEVEL
DS2482S__LOWLEVEL
MULTICORE » DS2482S
Functions
void vDS2482S_LOWLEVEL__Init (Luint8 u8DeviceIndex)
Init any low level specifics for this device index.
Lint16 s16DS2482S_LOWLEVEL__TxReg (Luint8 u8DeviceIndex, E_DS2482_REGS eRegister)
Transmit a byte The DS2482 does not use traditional I2C addx - reg - data modes and requires sometimes that only the reg portion ise sent.
Lint16 s16DS2482S_LOWLEVEL__RxReg (Luint8 u8DeviceIndex, Luint8 *pu8Data)
Rx a simple register value.
Lint16 s16DS2482S_LOWLEVEL__WriteReg (Luint8 u8DeviceIndex, E_DS2482_REGS eRegister, Luint8 u8Value)
Write a register on the device.
Lint16 s16DS2482S_LOWLEVEL__ReadReg (Luint8 u8DeviceIndex, E_DS2482_REGS eRegister, Luint8 *pu8Value)
Read a single register.
Detailed Description
Function Documentation
Lint16 s16DS2482S_LOWLEVEL__ReadReg (Luint8 u8DeviceIndex, E_DS2482_REGS eRegister, Luint8 * pu8Value)
Read a single register.
Parameters
[in] *pu8Value Return register value
[in] eRegister The register type
[in] u8DeviceIndex Device index on the bus
Returns
0 = success
-ve = error
SafeTool Function MD5:
29D34C25CE0177FAEC9D72506979CD1D
SafeTool Function ID:
LCCM641R0.FILE.005.FUNC.005
References M_LOCALDEF__LCCM641__I2C_RX_BYTE, and vRM4_DELAYS__Delay_uS().
Lint16 s16DS2482S_LOWLEVEL__RxReg (Luint8 u8DeviceIndex, Luint8 * pu8Data)
Rx a simple register value.
Due to the way this device works we often just need to read back a register without addressing it.
Parameters
[in] *pu8Data Return register value
[in] u8DeviceIndex The I2C device index
Returns
0 = success
-ve = error
SafeTool Function MD5:
2ACA3147B62B9EA48295A501A229D1D9
SafeTool Function ID:
LCCM641R0.FILE.005.FUNC.003
References M_LOCALDEF__LCCM641__I2C_RX_REG, and vRM4_DELAYS__Delay_uS().
Referenced by s16DS2482S_DEVICE__Get_Status(), s16DS2482S_DEVICE__Read_Byte(), s16DS2482S_DEVICE__Read_ConfigRegister(), s16DS2482S_DEVICE__Reset(), and s16DS2482S_DEVICE__Set_ConfigRegister().
Lint16 s16DS2482S_LOWLEVEL__TxReg (Luint8 u8DeviceIndex, E_DS2482_REGS eRegister)
Transmit a byte The DS2482 does not use traditional I2C addx - reg - data modes and requires sometimes that only the reg portion ise sent.
Parameters
[in] eRegister The register
[in] u8DeviceIndex Device index on the bus
Returns
0 = success
-ve = error
SafeTool Function MD5:
D536F98D5ACAB3C3191814F7A8D28D10
SafeTool Function ID:
LCCM641R0.FILE.005.FUNC.002
References M_LOCALDEF__LCCM641__I2C_TX_REG, and vRM4_DELAYS__Delay_uS().
Referenced by s16DS2482S_1WIRE__Generate_Reset(), s16DS2482S_1WIRE__ReadByte(), s16DS2482S_1WIRE__Set_StrongPullup(), and s16DS2482S_DEVICE__Reset().
Lint16 s16DS2482S_LOWLEVEL__WriteReg (Luint8 u8DeviceIndex, E_DS2482_REGS eRegister, Luint8 u8Value)
Write a register on the device.
Parameters
[in] u8Value The value to write to the register
[in] eRegister The register index
[in] u8DeviceIndex Device index on the bus.
Returns
0 = success
-ve = error
SafeTool Function MD5:
4F5B9DF104F6BFCDBCA82B26C2704C74
SafeTool Function ID:
LCCM641R0.FILE.005.FUNC.004
References M_LOCALDEF__LCCM641__I2C_TX_BYTE, and vRM4_DELAYS__Delay_uS().
Referenced by s16DS2482S_1WIRE__WriteBit(), s16DS2482S_1WIRE__WriteByte(), s16DS2482S_DEVICE__Set_ConfigRegister(), and s16DS2482S_DEVICE__Set_ReadPointer().
void vDS2482S_LOWLEVEL__Init (Luint8 u8DeviceIndex)
Init any low level specifics for this device index.
Parameters
[in] u8DeviceIndex The device index on the bus
SafeTool Function MD5:
60A5416C1E8406DB4BB10F52CEF31C44
SafeTool Function ID:
LCCM641R0.FILE.005.FUNC.001
Referenced by vDS2482S__Init().