LFW513 (RLOOP - POWER NODE): EMAC/MDIO
EMAC/MDIO
Ethernet Media Access Controller/Management Data Input/Output.
Functions
void vRM4_EMAC_LINK__Init (Luint8 *pu8MAC, Luint8 *pu8IP)
Init the link state machine Call this at power up to get the EMAC working.
void vRM4_EMAC_LINK__Set_State (RM4_EMAC__LINK_STATE_T eState)
Set the Link state to a new value.
void vRM4_EMAC_LINK__Process (void)
process the state machine Called each program loop to progressively bring up the link.
Luint8 u8RM4_EMAC_LINK__Is_LinkUp (void)
Is the link up Returns true if the EMAC link is established.
void vRM4_EMAC_RX__RxIntHandler (void)
Rx Interrupt Handler.
void vRM4_EMAC_TX__Tx_IntHandler (void)
Transmit interrupt handler.
Lint16 s16RM4_EMAC_LINK__Link_Setup (void)
Setup the link Attempts to set up the link via auto-negotiation.
Lint16 s16RM4_EMAC_LINK__Link_Setup_AsyncStart (void)
ToDo.
Lint16 s16RM4_EMAC_LINK__Link_Setup_AsyncCheck (void)
ToDo.
void vRM4_EMAC__Init (void)
This API Initializes the EMAC and EMAC Control modules.
void vRM4_EMAC__TxHdrDescPtrWrite (Luint32 u32DescriptorHeader, Luint32 u32Channel)
Write the TX HDP register.
void vRM4_EMAC__RxHdrDescPtrWrite (Luint32 u32DescriptorHeader, Luint32 u32Channel)
Write the RX HDP register.
void vRM4_EMAC__Write_TxChannelCompletionPointer (Luint32 u32Channel, Luint32 u32CompletionPointer)
Writes the the TX Completion Pointer for a specific channel.
void vRM4_EMAC__Write_RxChannelCompletionPointer (Luint32 u32Channel, Luint32 u32CompletionPointer)
Writes the the RX Completion Pointer for a specific channel.
void vRM4_EMAC__Set_MACSrcAddx (Luint8 *pu8MACAddx)
Sets the MAC Address in MACSRCADDR registers.
void vRM4_EMAC__Set_MACAddx (Luint32 u32Channel, Luint8 *pu8MACAddx, Luint32 u32MatchFilter)
Sets the MAC Address in MACADDR registers.
void vRM4_EMAC__Enable_RxUnicast_OnChannel (Luint32 u32Channel)
Enables unicast for a specific channel.
void vRM4_EMAC__Enable_RxBroadcast_OnChannel (Luint32 u32Channel)
Enables a specific channel to receive broadcast frames.
void vRM4_EMAC__Enable_RxPromiscous_OnChannel (Luint32 u32Channel)
ToDo.
void vRM4_EMAC__Set_NumFreeRxBuffers (Luint32 u32Channel, Luint32 u32NumBuffers)
Set the free buffers for a specific channel.
Luint32 u32RM4_EMAC__Get_IntVector (void)
Gets the interrupt vectors of EMAC, which are pending.
void vRM4_EMAC__Set_Duplex (Luint32 u32DuplexMode)
sets the duplex mode of operation(full/half) for MAC.
void vRM4_EMAC__Enable_Tx (void)
API to enable the transmit in the TX Control Register.
void vRM4_EMAC__Enable_Rx (void)
Enable the receive in the RX Control Register.
void vRM4_EMAC__Enable_MII (void)
enables the MII control block
void vRM4_EMAC__Set_RMII_Speed10Mb (void)
This API sets the RMII speed to 10Mb.
void vRM4_EMAC__Set_RMII_Speed100Mb (void)
This API sets the RMII speed to 100Mb.
void vRM4_EMAC_RESET__Soft_Reset (void)
Perform a soft reset.
Lint16 s16RM4_EMAC_MDIO__Init (Luint32 mdioInputFreq, Luint32 mdioOutputFreq)
Initializes the MDIO peripheral.
Luint32 u32RM4_EMAC_MDIO__Get_ModuleRevisionID (void)
reads the module revision ID
Luint32 u32RM4_EMAC_MDIO__Get_AliveStatus (void)
Reads the alive status of all PHY connected to this MDIO.
Luint32 u32RM4_EMAC_MDIO__Get_LinkStatus (void)
Reads the link status of all PHY connected to this MDIO.
Lint16 s16RM4_EMAC_MDIO__Read_Register (Luint32 u32RegisterNum, Luint16 *pu16Data)
Reads a PHY register using MDIO.
void vRM4_EMAC_MDIO__Write_Register (Luint32 u32RegisterNum, Luint16 RegVal)
Writes a PHY register using MDIO.
void vRM4_EMAC_BD__Init (void)
Initialize the Descriptor Memory For TX and RX Only Channel 0 is supported for both TX and RX.
Luint32 u32RM4_EMAC_BD__Get_TxBufferPointer (Luint8 u8BufferIndex)
Return a pointer to a tx buffer.
void vRM4_EMAC_BD__Set_Length (Luint8 u8BufferIndex, Luint16 u16Length)
set the length of the buffer
void vRM4_EMAC_INT__TxISR (void)
Interrupt Handler for Core 0 Transmit interrupt.
void vRM4_EMAC_INT__RxISR (void)
Interrupt Handler for Core 0 Receive interrupt.
void vRM4_EMAC_INT__Enable_TxIntPulse (Luint32 u32ControlCore, Luint32 u32Channel)
Enables the TXPULSE Interrupt Generation.
void vRM4_EMAC_INT__Disable_TxIntPulse (Luint32 u32ControlCore, Luint32 u32Channel)
Disables the TXPULSE Interrupt Generation.
void vRM4_EMAC_INT__Enable_RxIntPulse (Luint32 u32ControlCore, Luint32 u32Channel)
Enables the RXPULSE Interrupt Generation.
void vRM4_EMAC_INT__Disable_RxIntPulse (Luint32 u32ControlCore, Luint32 u32Channel)
Disables the RXPULSE Interrupt Generation.
void vRM4_EMAC_INT__CoreIntAck (Luint32 u32EOIFlag)
Acknowledges an interrupt processed to the EMAC Control Core.
Variables
RM4_EMAC__LINK_STATE_T RM4_EMAC_IF::eLinkState
Luint8 RM4_EMAC_IF::u8MACAddx [6]
Luint8 RM4_EMAC_IF::u8IPAddx [4]
struct RM4_EMAC__TX_CHANNEL_T RM4_EMAC_IF::pEMAC_Tx_Channel
struct RM4_EMAC__RX_CHANNEL_T RM4_EMAC_IF::pEMAC_Rx_Channel
Luint8 RM4_EMAC_IF::u8StackPos
struct {
Luint8 RM4_EMAC_IF::u8StackPos
} RM4_EMAC_IF::sTxStack
Luint8 RM4_EMAC_IF::u8CableLength
Luint8 RM4_EMAC_IF::u8PairsSwapped
Luint8 RM4_EMAC_IF::u8PolarityInvert
struct {
Luint8 RM4_EMAC_IF::u8CableLength
Luint8 RM4_EMAC_IF::u8PairsSwapped
Luint8 RM4_EMAC_IF::u8PolarityInvert
} RM4_EMAC_IF::sStats
Stats about the link.
Detailed Description
Ethernet Media Access Controller/Management Data Input/Output.
The EMAC controls the flow of packet data from the system to the PHY. The MDIO module controls PHY configuration and status monitoring.
Both the EMAC and the MDIO modules interface to the system core through a custom interface that allows efficient data transmission and reception. This custom interface is referred to as the EMAC control module and is considered integral to the EMAC/MDIO peripheral
Related Files
emac.h
emac.c
hw_emac.h
hw_emac_ctrl.h
hw_mdio.h
hw_reg_access.h
mdio.h
mdio.c
Function Documentation
Lint16 s16RM4_EMAC_LINK__Link_Setup (void)
Setup the link Attempts to set up the link via auto-negotiation.
Returns
0 = success
-ve = error
SafeTool Function MD5:
F7E0204FCDFA817F9162A12FAA7A613E
SafeTool Function ID:
LCCM254R0.FILE.014.FUNC.004
References C_DP83640__PHY_INDEX, EMAC_DUPLEX_FULL, EMAC_DUPLEX_HALF, and vRM4_EMAC__Set_Duplex().
Lint16 s16RM4_EMAC_LINK__Link_Setup_AsyncCheck (void)
ToDo.
SafeTool Function MD5:
158221585BF60E05760521AE0804B013
SafeTool Function ID:
LCCM254R0.FILE.014.FUNC.007
References C_DP83640__PHY_INDEX, EMAC_DUPLEX_FULL, EMAC_DUPLEX_HALF, and vRM4_EMAC__Set_Duplex().
Referenced by vRM4_EMAC_LINK__Process().
Lint16 s16RM4_EMAC_LINK__Link_Setup_AsyncStart (void)
ToDo.
SafeTool Function MD5:
8C509E5A2CFE1B95E3A9A93980FFEC24
SafeTool Function ID:
LCCM254R0.FILE.014.FUNC.006
References C_DP83640__PHY_INDEX.
Referenced by vRM4_EMAC_LINK__Process().
Lint16 s16RM4_EMAC_MDIO__Init (Luint32 mdioInputFreq, Luint32 mdioOutputFreq)
Initializes the MDIO peripheral.
Initializes the MDIO peripheral This enables the MDIO state machine, uses standard pre-amble and set the clock divider value. 28.2.8.2.1 Initializing the MDIO Module The following steps are performed by the application software or device driver to initialize the MDIO device:
Configure the PREAMBLE and CLKDIV bits in the MDIO control register [CONTROL).
Enable the MDIO module by setting the ENABLE bit in CONTROL.
The MDIO PHY alive status register [ALIVE) can be read in polling fashion until a PHY connected to the system responded, and the MDIO PHY link status register [LINK) can determine whether this PHY already has a link.
Setup the appropriate PHY addresses in the MDIO user PHY select register [USERPHYSELn), and set the LINKINTENB bit to enable a link change event interrupt if desirable.
If an interrupt on general MDIO register access is desired, set the corresponding bit in the MDIO user command complete interrupt mask set register [USERINTMASKSET) to use the MDIO user access register [USERACCESSn). Since only one PHY is used in this device, the application software can use one USERACCESSn to trigger a completion interrupt; the other USERACCESSn is not setup.
28.2.16.3 MDIO Module Initialization The MDIO module is used to initially configure and monitor one or more external PHY devices. Other than initializing the software state machine [details on this state machine can be found in the IEEE 802.3 standard), all that needs to be done for the MDIO module is to enable the MDIO engine and to configure the clock divider. To set the clock divider, supply an MDIO clock of 1 MHz. For example, if the peripheral clock is 50 MHz, the divider can be set to 50. Both the state machine enable and the MDIO clock divider are controlled through the MDIO control register [CONTROL). If none of the potentially connected PHYs require the access preamble, the PREAMBLE bit in CONTROL can also be set to speed up PHY register access. If the MDIO module is to operate on an interrupt basis, the interrupts can be enabled at this time using the MDIO user command complete interrupt mask set register [USERINTMASKSET) for register access and the MDIO user PHY select register [USERPHYSELn) if a target PHY is already known. Once the MDIO state machine has been initialized and enabled, it starts polling all 32 PHY addresses on the MDIO bus, looking for an active PHY. Since it can take up to 50 μs to read one register, it can be some time before the MDIO module provides an accurate representation of whether a PHY is available. Also, a PHY can take up to 3 seconds to negotiate a link. Thus, it is advisable to run the MDIO software off a time-based event rather than polling.
Parameters
[in] mdioOutputFreq The clock output required on the MDIO bus
[in] mdioInputFreq The clock input to the MDIO module
Returns
0 = success -ve = error
SafeTool Function MD5:
F54A11A8B8BD8C4DBE13C9A20BAFBC6E
SafeTool Function ID:
LCCM254R0.FILE.009.FUNC.001
References C_DP83640__PHY_INDEX, HWREG, MDIO_BASE, MDIO_CONTROL, MDIO_CONTROL_CLKDIV, MDIO_CONTROL_ENABLE, MDIO_CONTROL_FAULTENB, MDIO_CONTROL_PREAMBLE, u32RM4_EMAC_MDIO__Get_AliveStatus(), and u32RM4_EMAC_MDIO__Get_ModuleRevisionID().
Referenced by vRM4_EMAC_LINK__Process().
Lint16 s16RM4_EMAC_MDIO__Read_Register (Luint32 u32RegisterNum, Luint16 * pu16Data)
Reads a PHY register using MDIO.
Reads a PHY register using MDIO. 28.2.8.2.3 Reading Data From a PHY Register The MDIO module includes a user access register [USERACCESSn) to directly access a specified PHY device. To read a PHY register, perform the following:
Check to ensure that the GO bit in the MDIO user access register [USERACCESSn) is cleared.
Write to the GO, REGADR, and PHYADR bits in USERACCESSn corresponding to the PHY and PHY register you want to read.
The read data value is available in the DATA bits in USERACCESSn after the module completes the read operation on the serial bus. Completion of the read operation can be determined by polling the GO and ACK bits in USERACCESSn. Once the GO bit has cleared, the ACK bit is set on a successful read.
Completion of the operation sets the corresponding USERINTRAW bit [0 or 1) in the MDIO user command complete interrupt register [USERINTRAW) corresponding to USERACCESSn used. If interrupts have been enabled on this bit using the MDIO user command complete interrupt mask set register [USERINTMASKSET), then the bit is also set in the MDIO user command complete interrupt register [USERINTMASKED) and an interrupt is triggered on the CPU.
Parameters
[out] pu16Data Pointer where the read value shall be written.
[in] u32RegisterNum Register Number to be read.
Returns
0 - read is not acknowledged properly 1 - read is successful
SafeTool Function MD5:
65801E14373DA1D59CDD2A58DA95CEEA
SafeTool Function ID:
LCCM254R0.FILE.009.FUNC.003
References C_DP83640__PHY_INDEX, HWREG, MDIO__PHY_ADDR_MASK, MDIO__PHY_ADDR_SHIFT, MDIO__PHY_DATA_MASK, MDIO__PHY_REG_MASK, MDIO__PHY_REG_SHIFT, MDIO_BASE, MDIO_USERACCESS0, MDIO_USERACCESS0_ACK, MDIO_USERACCESS0_GO, and MDIO_USERACCESS0_READ.
Luint32 u32RM4_EMAC__Get_IntVector (void)
Gets the interrupt vectors of EMAC, which are pending.
SafeTool Function MD5:
57F6B8FA945D8C7D6450DDDB014BF128
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.023
References EMAC_BASE, EMAC_MACINVECTOR, and HWREG.
Luint32 u32RM4_EMAC_BD__Get_TxBufferPointer (Luint8 u8BufferIndex)
Return a pointer to a tx buffer.
Parameters
[in] u8BufferIndex The transmit buffer index
SafeTool Function MD5:
3D64A272B59D65A50656235E952A82F3
SafeTool Function ID:
LCCM254R0.FILE.012.FUNC.001
References m_u8EMAC_TxBuffer.
Luint32 u32RM4_EMAC_MDIO__Get_AliveStatus (void)
Reads the alive status of all PHY connected to this MDIO.
Reads the alive status of all PHY connected to this MDIO The bit corresponding to the PHY address will be set if the PHY is alive. MDIO Alive bits. Each of the 32 bits of this register is set if the most recent access to the PHY with address corresponding to the register bit number was acknowledged by the PHY; the bit is reset if the PHY fails to acknowledge the access. Both the user and polling accesses to a PHY will cause the corresponding alive bit to be updated. The alive bits are only meant to be used to give an indication of the presence or not of a PHY with the corresponding address. Writing a 1 to any bit will clear it, writing a 0 has no effect.
Returns
0 The PHY fails to acknowledge the access. 1 The most recent access to the PHY with an address corresponding to the register bit number was acknowledged by the PHY.
SafeTool Function MD5:
800FFE2AAB99170B0380281EF3826575
SafeTool Function ID:
LCCM254R0.FILE.009.FUNC.005
References HWREG, MDIO_ALIVE, and MDIO_BASE.
Referenced by s16RM4_EMAC_MDIO__Init(), and vRM4_EMAC_LINK__Process().
Luint32 u32RM4_EMAC_MDIO__Get_LinkStatus (void)
Reads the link status of all PHY connected to this MDIO.
Reads the link status of all PHY connected to this MDIO. The bit corresponding to the PHY address will be set if the PHY link is active. MDIO Link state bits. This register is updated after a read of the generic status register of a PHY. The bit is set if the PHY with the corresponding address has link and the PHY acknowledges the read transaction. The bit is reset if the PHY indicates it does not have link or fails to acknowledge the read transaction. Writes to the register have no effect.
Returns
0 The PHY indicates it does not have a link or fails to acknowledge the read transaction 1 The PHY with the corresponding address has a link and the PHY acknowledges the read transaction.
SafeTool Function MD5:
E839F26A5A9885ED6BB2FA0927F36757
SafeTool Function ID:
LCCM254R0.FILE.009.FUNC.006
References HWREG, MDIO_BASE, and MDIO_LINK.
Luint32 u32RM4_EMAC_MDIO__Get_ModuleRevisionID (void)
reads the module revision ID
Returns
The Rev ID
SafeTool Function MD5:
9E95F6366A3389687C08B0099AB9D33B
SafeTool Function ID:
LCCM254R0.FILE.009.FUNC.002
References HWREG, MDIO_BASE, and MDIO_REVID.
Referenced by s16RM4_EMAC_MDIO__Init().
Luint8 u8RM4_EMAC_LINK__Is_LinkUp (void)
Is the link up Returns true if the EMAC link is established.
Returns
0 = link down
1 = link up
SafeTool Function MD5:
A5EF9C0FC3175F17D6016D1B08F7D92D
SafeTool Function ID:
LCCM254R0.FILE.014.FUNC.003
References RM4_EMAC_IF::eLinkState, LINK_STATE__RUN, and m_pEMAC_IF.
void vRM4_EMAC__Enable_MII (void)
enables the MII control block
SafeTool Function MD5:
7EA6C1991F4D7CB31D3FE008A5E93F78
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.008
References EMAC_BASE, EMAC_MACCONTROL, EMAC_MACCONTROL_GMIIEN, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__Enable_Rx (void)
Enable the receive in the RX Control Register.
After the transmit is enabled, and write to RXHDP of a channel, the data can be received in the destination specified by the corresponding RX buffer descriptor.
SafeTool Function MD5:
BF28161241FC629DD8468A4AC60D3525
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.011
References EMAC_BASE, EMAC_RXCONTROL, EMAC_RXCONTROL_RXEN, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__Enable_RxBroadcast_OnChannel (Luint32 u32Channel)
Enables a specific channel to receive broadcast frames.
To receive frames with a matching unicast or multicast destination address. The RXBROADEN bit in the receive multicast/broadcast/promiscuous channel enable register (RXMBPENABLE) determines if broadcast frames are enabled or filtered. If broadcast frames are enabled (when set to 1), then they are copied to only a single channel selected by the RXBROADCH bit in RXMBPENABLE.
Parameters
[in] u32Channel Channel Number.
SafeTool Function MD5:
EEFCD96DBDB1BFA07B495721D5A108BA
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.020
References EMAC_BASE, EMAC_RXMBPENABLE, EMAC_RXMBPENABLE_RXBROADCH, EMAC_RXMBPENABLE_RXBROADCH_SHIFT, EMAC_RXMBPENABLE_RXBROADEN, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__Enable_RxPromiscous_OnChannel (Luint32 u32Channel)
ToDo.
Parameters
References EMAC_BASE, EMAC_RXMBPENABLE, EMAC_RXMBPENABLE_RXPROMCH_SHIFT, and HWREG.
void vRM4_EMAC__Enable_RxUnicast_OnChannel (Luint32 u32Channel)
Enables unicast for a specific channel.
28.2.11.2 Receive Channel Enabling Each of the eight receive channels has an enable bit (RXCHnEN) in the receive unicast set register (RXUNICASTSET) that is controlled using RXUNICASTSET and the receive unicast clear register (RXUNICASTCLEAR). The RXCHnEN bits determine whether the given channel is enabled (when set to 1) to receive frames with a matching unicast or multicast destination address. The RXBROADEN bit in the receive multicast/broadcast/promiscuous channel enable register (RXMBPENABLE) determines if broadcast frames are enabled or filtered. If broadcast frames are enabled (when set to 1), then they are copied to only a single channel selected by the RXBROADCH bit in RXMBPENABLE. The RXMULTEN bit in RXMBPENABLE determines if hash matching multicast frames are enabled or filtered. Incoming multicast addresses (group addresses) are hashed into an index in the hash table. If the indexed bit is set then the frame hash matches and will be transferred to the channel selected by the RXMULTCH bit in RXMBPENABLE when multicast frames are enabled. The multicast hash bits are set in the MAC address hash n registers (MACHASH1 and MACHASH2). The RXPROMCH bit in RXMBPENABLE selects the promiscuous channel to receive frames selected by the RXCMFEN, RXCSFEN, RXCEFEN, and RXCAFEN bits. These four bits allow reception of MAC control frames, short frames, error frames, and all frames (promiscuous), respectively.
Parameters
[in] u32Channel Channel Number
SafeTool Function MD5:
E0D46C26158CAEFA74D71EC17C36630E
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.021
References EMAC_BASE, EMAC_RXUNICASTSET, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__Enable_Tx (void)
API to enable the transmit in the TX Control Register.
After the transmit is enabled, any write to TXHDP of a channel will start transmission
SafeTool Function MD5:
338CA8AE75A77B93F328FEC83F35E482
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.010
References EMAC_BASE, EMAC_TXCONTROL, EMAC_TXCONTROL_TXEN, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__Init (void)
This API Initializes the EMAC and EMAC Control modules.
The EMAC Control module is reset, the CPPI RAM is cleared. also, all the interrupts are disabled. This API does not enable any interrupt or operation of the EMAC.
28.2.16.4 EMAC Module Initialization The EMAC module is used to send and receive data packets over the network. This is done by maintaining up to eight transmit and receive descriptor queues. The EMAC module configuration must also be kept up-to-date based on PHY negotiation results returned from the MDIO module. Most of the work in developing an application or device driver for Ethernet is programming this module. The following is the initialization procedure a device driver would follow to get the EMAC to the state where it is ready to receive and send Ethernet packets. Some of these steps are not necessary when performed immediately after device reset.
If enabled, clear the device interrupt enable bits in the EMAC control module interrupt control registers C0RXTHRESHEN, C0RXEN, C0TXEN, and C0MISCEN.
Clear the MAC control register [MACCONTROL), receive control register [RXCONTROL), and transmit control register [TXCONTROL) [not necessary immediately after reset).
Initialize all 16 header descriptor pointer registers [RXnHDP and TXnHDP) to 0.
Clear all 36 statistics registers by writing 0 [not necessary immediately after reset).
Setup the local Ethernet MAC address by programming the MAC index register [MACINDEX), MAC address high bytes register [MACADDRHI), and MAC address low bytes register [MACADDRLO). Be sure to program all eight MAC address registers - whether the receive channel is to be enabled or not. Duplicate the same MAC address across all unused channels. When using more than one receive channel, start with channel 0 and progress upwards.
If buffer flow control is to be enabled, initialize the receive channel n free buffer count registers [RXnFREEBUFFER), receive channel n flow control threshold register [RXnFLOWTHRESH), and receive filter low priority frame threshold register [RXFILTERLOWTHRESH).
Most device drivers open with no multicast addresses, so clear the MAC address hash registers [MACHASH1 and MACHASH2) to 0.
Write the receive buffer offset register [RXBUFFEROFFSET) value [typically zero).
Initially clear all unicast channels by writing FFh to the receive unicast clear register [RXUNICASTCLEAR). If unicast is desired, it can be enabled now by writing the receive unicast set register [RXUNICASTSET). Some drivers will default to unicast on device open while others will not.
Setup the receive multicast/broadcast/promiscuous channel enable register [RXMBPENABLE) with an initial configuration. The configuration is based on the current receive filter settings of the device driver. Some drivers may enable things like broadcast and multicast packets immediately, while others may not.
Set the appropriate configuration bits in MACCONTROL [do not set the GMIIEN bit yet).
Clear all unused channel interrupt bits by writing the receive interrupt mask clear register [RXINTMASKCLEAR) and the transmit interrupt mask clear register [TXINTMASKCLEAR).
Enable the receive and transmit channel interrupt bits in the receive interrupt mask set register [RXINTMASKSET) and the transmit interrupt mask set register [TXINTMASKSET) for the channels to be used, and enable the HOSTMASK and STATMASK bits using the MAC interrupt mask set register [MACINTMASKSET).
Initialize the receive and transmit descriptor list queues.
Prepare receive by writing a pointer to the head of the receive buffer descriptor list to RXnHDP.
Enable the receive and transmit DMA controllers by setting the RXEN bit in RXCONTROL and the TXEN bit in TXCONTROL. Then set the GMIIEN bit in MACCONTROL.
Enable the device interrupt in EMAC control module registers C0RXTHRESHEN, C0RXEN, C0TXEN, and C0MISCEN.
SafeTool Function MD5:
113D6BCD2FF84D63F62014097C77A17E
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.001
References EMAC_BASE, EMAC_CONTROL_RESET, EMAC_CTRL_BASE, EMAC_CTRL_SOFTRESET, EMAC_MACCONTROL, EMAC_MACHASH1, EMAC_MACHASH2, EMAC_MAX_HEADER_DESC, EMAC_RXBUFFEROFFSET, EMAC_RXCONTROL, EMAC_RXCP, EMAC_RXFREEBUFFER, EMAC_RXHDP, EMAC_RXINTMASKCLEAR, EMAC_TXCONTROL, EMAC_TXCP, EMAC_TXHDP, EMAC_TXINTMASKCLEAR, HWREG, and vRM4_EMAC_RESET__Soft_Reset().
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__RxHdrDescPtrWrite (Luint32 descHdr, Luint32 u32Channel)
Write the RX HDP register.
If receive is enabled, write to the RX HDP will enable data reception to point to the corresponding RX buffer descriptor's buffer pointer.
Parameters
[in] u32Channel ## Desc ##
[in] descHdr ## Desc ##
SafeTool Function MD5:
C0CA0A7FA19A93CA0EF9DC19D18F50A2
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.013
References EMAC_BASE, EMAC_RXHDP, and HWREG.
Referenced by vRM4_EMAC_LINK__Process(), and vRM4_EMAC_RX__RxIntHandler().
void vRM4_EMAC__Set_Duplex (Luint32 u32DuplexMode)
sets the duplex mode of operation(full/half) for MAC.
Parameters
[in] u32DuplexMode ## Desc ##
SafeTool Function MD5:
C7FF4BFEEEFD1D3383A7E8042C2F2DCA
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.009
References EMAC_BASE, EMAC_MACCONTROL, EMAC_MACCONTROL_FULLDUPLEX, and HWREG.
Referenced by s16RM4_EMAC_LINK__Link_Setup(), and s16RM4_EMAC_LINK__Link_Setup_AsyncCheck().
void vRM4_EMAC__Set_MACAddx (Luint32 u32Channel, Luint8 * pu8MACAddx, Luint32 pu32MatchFilter)
Sets the MAC Address in MACADDR registers.
28.2.11.3 Receive Address Matching All eight MAC addresses corresponding to the eight receive channels share the upper 40 bits. Only the lower byte is unique for each address. All eight receive addresses should be initialized, because pause frames are acted upon regardless of whether a channel is enabled or not. A MAC address is written by first writing the address number (channel) to be written into the MAC index register (MACINDEX). The upper 32 bits of address are then written to the MAC address high bytes register (MACADDRHI), which is followed by writing the lower 16 bits of address to the MAC address low bytes register (MACADDRLO). Since all eight MAC addresses share the upper 40 bits of address, MACADDRHI needs to be written only the first time (for the first channel configured).
Parameters
[in] pu32MatchFilter matchFilt can take the following values: EMAC_MACADDR_NO_MATCH_NO_FILTER - Address is not used to match or filter incoming packet. EMAC_MACADDR_FILTER - Address is used to filter incoming packets EMAC_MACADDR_MATCH - Address is used to match incoming packets
[in] pu8MACAddx The array[0] shall be the LSB of the MAC address
[in] u32Channel Channel Number
SafeTool Function MD5:
7E96C7EF4D0F30FFB82CF5587EF0780D
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.015
References EMAC_BASE, EMAC_MACADDRHI, EMAC_MACADDRLO, EMAC_MACINDEX, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__Set_MACSrcAddx (Luint8 * pu8MACAddx)
Sets the MAC Address in MACSRCADDR registers.
Parameters
[in] pu8MACAddx The array[0] shall be the LSB of the MAC address
SafeTool Function MD5:
483D5CDC8E79983E722EDD344D2C3047
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.014
References EMAC_BASE, EMAC_MACSRCADDRHI, EMAC_MACSRCADDRLO, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__Set_NumFreeRxBuffers (Luint32 u32Channel, Luint32 u32NumBuffers)
Set the free buffers for a specific channel.
Parameters
[in] u32NumBuffers Number of free buffers
[in] u32Channel Channel Number.
SafeTool Function MD5:
94F8AC14060596D118732AAF47839DA2
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.022
References EMAC_BASE, EMAC_RXFREEBUFFER, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__Set_RMII_Speed100Mb (void)
This API sets the RMII speed to 100Mb.
SafeTool Function MD5:
8541BC859FE9787FFA2106886ADD5903
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.007
References EMAC_BASE, EMAC_MACCONTROL, EMAC_MACCONTROL_RMIISPEED, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__Set_RMII_Speed10Mb (void)
This API sets the RMII speed to 10Mb.
SafeTool Function MD5:
98EFEB2EFFA9D958B80E1F8272135560
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.006
References EMAC_BASE, EMAC_MACCONTROL, EMAC_MACCONTROL_RMIISPEED, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__TxHdrDescPtrWrite (Luint32 descHdr, Luint32 u32Channel)
Write the TX HDP register.
If transmit is enabled, write to the TX HDP will immediately start transmission. The data will be taken from the buffer pointer of the TX buffer descriptor written to the TX HDP
Parameters
[in] u32Channel ## Desc ##
[in] descHdr ## Desc ##
SafeTool Function MD5:
CAE67B3330B496AF2288DA99715C6AD9
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.012
References EMAC_BASE, EMAC_TXHDP, HWREG, lastInputdescHdr, and valHDPbefWrite.
void vRM4_EMAC__Write_RxChannelCompletionPointer (Luint32 u32Channel, Luint32 u32CompletionPointer)
Writes the the RX Completion Pointer for a specific channel.
Upon interrupt reception, the CPU processes one or more packets from the buffer chain and then acknowledges one or more interrupt(s) by writing the address of the last buffer descriptor processed to the queue's associated receive completion pointer in the receive DMA state RAM.
Parameters
[in] u32CompletionPointer Completion Pointer Value to be written
[in] u32Channel Channel Number
SafeTool Function MD5:
A138FC52F827A9DC521050F205A7893B
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.018
References EMAC_BASE, EMAC_RXCP, and HWREG.
Referenced by vRM4_EMAC_RX__RxIntHandler().
void vRM4_EMAC__Write_TxChannelCompletionPointer (Luint32 u32Channel, Luint32 u32CompletionPointer)
Writes the the TX Completion Pointer for a specific channel.
Parameters
[in] u32CompletionPointer Completion Pointer Value to be written
[in] u32Channel Channel Number
SafeTool Function MD5:
C226994569AD17AF59D7C1C618065A0D
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.017
References EMAC_BASE, EMAC_TXCP, and HWREG.
Referenced by vRM4_EMAC_TX__Tx_IntHandler().
void vRM4_EMAC_BD__Init (void)
Initialize the Descriptor Memory For TX and RX Only Channel 0 is supported for both TX and RX.
SafeTool Function MD5:
25847BA436E9E2E442D5C55CFF3D1109
SafeTool Function ID:
LCCM254R0.FILE.012.FUNC.003
References EMAC_BUF_DESC_OWNER, EMAC_CTRL_RAM_0_BASE, m_pEMAC_IF, m_u8EMAC_RxBuffer, m_u8EMAC_TxBuffer, RM4_EMAC_IF::pEMAC_Rx_Channel, RM4_EMAC_IF::pEMAC_Tx_Channel, RM4_EMAC__RX_CHANNEL_T::pHeadDescriptor, RM4_EMAC__TX_CHANNEL_T::pHeadDescriptor, RM4_EMAC__TX_BD_T::pNextBlockDescriptor, RM4_EMAC__RX_BD_T::pNextBlockDescriptor, RM4_EMAC__TX_BD_T::pu32Buffer, RM4_EMAC__RX_BD_T::pu32Buffer, RM4_EMAC__TX_BD_T::u16BufferOffset__u16BufferLength, RM4_EMAC__RX_BD_T::u16BufferOffset__u16BufferLength, RM4_EMAC__TX_BD_T::u16Flags__u16PacketLength, and RM4_EMAC__RX_BD_T::u16Flags__u16PacketLength.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC_BD__Set_Length (Luint8 u8BufferIndex, Luint16 u16Length)
set the length of the buffer
Parameters
[in] u16Length The transmission length
[in] u8BufferIndex The buffer index for tx
SafeTool Function MD5:
94923FAC8135E37F914CD95AC29B86C0
SafeTool Function ID:
LCCM254R0.FILE.012.FUNC.002
References m_pEMAC_IF, RM4_EMAC_IF::pEMAC_Tx_Channel, RM4_EMAC__TX_CHANNEL_T::pHeadDescriptor, RM4_EMAC__TX_BD_T::pNextBlockDescriptor, and RM4_EMAC__TX_BD_T::u16Flags__u16PacketLength.
void vRM4_EMAC_INT__CoreIntAck (Luint32 u32EOIFlag)
Acknowledges an interrupt processed to the EMAC Control Core.
Acknowledges an interrupt processed to the EMAC Control Core. The application software must acknowledge the EMAC control module after processing packets by writing the appropriate C0TX key to the EMAC End-Of-Interrupt Vector register (MACEOIVECTOR). See Section 28.5.12 for the acknowledge key values.
Parameters
[in] u32EOIFlag u32EOIFlag can take the following values: EMAC_INT_CORE0_TX - Core 0 TX Interrupt EMAC_INT_CORE1_TX - Core 1 TX Interrupt EMAC_INT_CORE2_TX - Core 2 TX Interrupt EMAC_INT_CORE0_RX - Core 0 RX Interrupt EMAC_INT_CORE1_RX - Core 1 RX Interrupt EMAC_INT_CORE2_RX - Core 2 RX Interrupt
SafeTool Function MD5:
C301E3EF23044506E9CABD61E90263EE
SafeTool Function ID:
LCCM254R0.FILE.010.FUNC.007
References EMAC_BASE, EMAC_MACEOIVECTOR, and HWREG.
Referenced by vRM4_EMAC_LINK__Process(), vRM4_EMAC_RX__RxIntHandler(), and vRM4_EMAC_TX__Tx_IntHandler().
void vRM4_EMAC_INT__Disable_RxIntPulse (Luint32 u32ControlCore, Luint32 u32Channel)
Disables the RXPULSE Interrupt Generation.
Parameters
[in] u32Channel The EMAC channel
[in] u32ControlCore The value
SafeTool Function MD5:
02DF2FA663F1FD81E4DF7DCE7BD26D7A
SafeTool Function ID:
LCCM254R0.FILE.010.FUNC.006
References EMAC_BASE, EMAC_CTRL_BASE, EMAC_CTRL_CnRXEN, EMAC_RXINTMASKCLEAR, and HWREG.
void vRM4_EMAC_INT__Disable_TxIntPulse (Luint32 u32ControlCore, Luint32 u32Channel)
Disables the TXPULSE Interrupt Generation.
Parameters
[in] u32Channel The EMAC channel
[in] u32ControlCore The value
SafeTool Function MD5:
3EA539E78A6C44DDFEC660668D4A492C
SafeTool Function ID:
LCCM254R0.FILE.010.FUNC.004
References EMAC_BASE, EMAC_CTRL_BASE, EMAC_CTRL_CnTXEN, EMAC_TXINTMASKCLEAR, and HWREG.
void vRM4_EMAC_INT__Enable_RxIntPulse (Luint32 u32ControlCore, Luint32 u32Channel)
Enables the RXPULSE Interrupt Generation.
Parameters
[in] u32Channel The EMAC channel
[in] u32ControlCore The value
SafeTool Function MD5:
271748BC60ACACBF713F0266D9439CBD
SafeTool Function ID:
LCCM254R0.FILE.010.FUNC.005
References EMAC_BASE, EMAC_CTRL_BASE, EMAC_CTRL_CnRXEN, EMAC_RXINTMASKSET, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC_INT__Enable_TxIntPulse (Luint32 u32ControlCore, Luint32 u32Channel)
Enables the TXPULSE Interrupt Generation.
Parameters
[in] u32Channel The EMAC channel
[in] u32ControlCore The value
SafeTool Function MD5:
4EDEB7CF1982F93551CB5CB78467A101
SafeTool Function ID:
LCCM254R0.FILE.010.FUNC.003
References EMAC_BASE, EMAC_CTRL_BASE, EMAC_CTRL_CnTXEN, EMAC_TXINTMASKSET, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC_INT__RxISR (void)
Interrupt Handler for Core 0 Receive interrupt.
SafeTool Function MD5:
EE7B977116572E58740EDC8D5906FDEF
SafeTool Function ID:
LCCM254R0.FILE.010.FUNC.002
References countEMACCore0RxIsr, and vRM4_EMAC_RX__RxIntHandler().
void vRM4_EMAC_INT__TxISR (void)
Interrupt Handler for Core 0 Transmit interrupt.
SafeTool Function MD5:
BB61598D47AA68E2503813CB8819B0A0
SafeTool Function ID:
LCCM254R0.FILE.010.FUNC.001
References countEMACCore0TxIsr, and vRM4_EMAC_TX__Tx_IntHandler().
void vRM4_EMAC_LINK__Init (Luint8 * pu8MAC, Luint8 * pu8IP)
Init the link state machine Call this at power up to get the EMAC working.
Example:
u8MACAddx[0] = 0x00; u8MACAddx[1] = 0x26; u8MACAddx[2] = 0x80; u8MACAddx[3] = 0x00; u8MACAddx[4] = 0x00; u8MACAddx[5] = 0x01;
u8IPAddx[0] = 192; u8IPAddx[1] = 168; u8IPAddx[2] = 1; u8IPAddx[3] = 200;
SafeTool Function MD5:
58AF718D01B1040C1966D8735815BED3
Parameters
[in] pu8IP Pointer to IP Address
[in] pu8MAC Pointer to MAC Address
SafeTool Function MD5:
2ABEF0E5890FA02A89BBC11DFCBC37C4
SafeTool Function ID:
LCCM254R0.FILE.014.FUNC.001
References RM4_EMAC_IF::eLinkState, LINK_STATE__IDLE, m_pEMAC_IF, RM4_EMAC_IF::u8IPAddx, and RM4_EMAC_IF::u8MACAddx.
void vRM4_EMAC_LINK__Process (void)
process the state machine Called each program loop to progressively bring up the link.
SafeTool Function MD5:
A0CE617E45084BA14633D7602074CCEB
SafeTool Function ID:
LCCM254R0.FILE.014.FUNC.002
References C_DP83640__PHY_INDEX, RM4_EMAC_IF::eLinkState, EMAC_INT_CORE0_RX, EMAC_INT_CORE0_TX, EMAC_MACADDR_MATCH, EMAC_MACADDR_NO_MATCH_NO_FILTER, LINK_STATE__BLOCK_DESC_INIT, LINK_STATE__CABLE_CHECK, LINK_STATE__CHECK_PHY_ALIVE, LINK_STATE__CHECK_PHY_ALIVE_1, LINK_STATE__ENAB_RX_BROADCAST, LINK_STATE__GET_ALIVE_STATUS, LINK_STATE__GET_PHY_ID, LINK_STATE__GRAT_ARP, LINK_STATE__IDLE, LINK_STATE__INIT_EMAC, LINK_STATE__INIT_MDIO, LINK_STATE__INTERRUPTS_INIT, LINK_STATE__INTERRUPTS_INIT_2, LINK_STATE__LINK_PRE, LINK_STATE__LINK_SETUP_1, LINK_STATE__LINK_SETUP_2, LINK_STATE__LLDP, LINK_STATE__RUN, LINK_STATE__SET_MAC_ADDX, m_pEMAC_IF, RM4_EMAC_IF::pEMAC_Rx_Channel, RM4_EMAC__RX_CHANNEL_T::pHeadDescriptor, s16RM4_EMAC_LINK__Link_Setup_AsyncCheck(), s16RM4_EMAC_LINK__Link_Setup_AsyncStart(), s16RM4_EMAC_MDIO__Init(), RM4_EMAC_IF::sStats, SYS_IRQ, u32RM4_EMAC_MDIO__Get_AliveStatus(), RM4_EMAC_IF::u8CableLength, RM4_EMAC_IF::u8MACAddx, RM4_EMAC_IF::u8PairsSwapped, RM4_EMAC_IF::u8PolarityInvert, vRM4_DELAYS__Delay_mS(), vRM4_DELAYS__Delay_uS(), vRM4_EMAC__Enable_MII(), vRM4_EMAC__Enable_Rx(), vRM4_EMAC__Enable_RxBroadcast_OnChannel(), vRM4_EMAC__Enable_RxUnicast_OnChannel(), vRM4_EMAC__Enable_Tx(), vRM4_EMAC__Init(), vRM4_EMAC__RxHdrDescPtrWrite(), vRM4_EMAC__Set_MACAddx(), vRM4_EMAC__Set_MACSrcAddx(), vRM4_EMAC__Set_NumFreeRxBuffers(), vRM4_EMAC__Set_RMII_Speed100Mb(), vRM4_EMAC__Set_RMII_Speed10Mb(), vRM4_EMAC_BD__Init(), vRM4_EMAC_INT__CoreIntAck(), vRM4_EMAC_INT__Enable_RxIntPulse(), vRM4_EMAC_INT__Enable_TxIntPulse(), and vRM4_VIM__EnableInterrupt().
void vRM4_EMAC_LINK__Set_State (RM4_EMAC__LINK_STATE_T eState)
Set the Link state to a new value.
Parameters
[in] eState The new link state value
SafeTool Function MD5:
1CA806A289D95EFAB4E72C7A265CA301
SafeTool Function ID:
LCCM254R0.FILE.014.FUNC.005
References RM4_EMAC_IF::eLinkState, and m_pEMAC_IF.
void vRM4_EMAC_MDIO__Write_Register (Luint32 u32RegIndex, Luint16 u16Value)
Writes a PHY register using MDIO.
Writes a PHY register using MDIO. 28.2.8.2.2 Writing Data To a PHY Register The MDIO module includes a user access register [USERACCESSn) to directly access a specified PHY device. To write a PHY register, perform the following:
Check to ensure that the GO bit in the MDIO user access register [USERACCESSn) is cleared.
Write to the GO, WRITE, REGADR, PHYADR, and DATA bits in USERACCESSn corresponding to the PHY and PHY register you want to write.
The write operation to the PHY is scheduled and completed by the MDIO module. Completion of the write operation can be determined by polling the GO bit in USERACCESSn for a 0.
Completion of the operation sets the corresponding USERINTRAW bit [0 or 1) in the MDIO user command complete interrupt register [USERINTRAW) corresponding to USERACCESSn used. If interrupts have been enabled on this bit using the MDIO user command complete interrupt mask set register [USERINTMASKSET), then the bit is also set in the MDIO user command complete interrupt register [USERINTMASKED) and an interrupt is triggered on the CPU.
Parameters
[in] u16Value Value to be written.
[in] u32RegIndex Register Number to be read.
SafeTool Function MD5:
CF9A82F985E2A7CBE53A1C2F5C4DFCF0
SafeTool Function ID:
LCCM254R0.FILE.009.FUNC.004
References C_DP83640__PHY_INDEX, HWREG, MDIO__PHY_ADDR_MASK, MDIO__PHY_ADDR_SHIFT, MDIO__PHY_REG_MASK, MDIO__PHY_REG_SHIFT, MDIO_BASE, MDIO_USERACCESS0, MDIO_USERACCESS0_GO, and MDIO_USERACCESS0_WRITE.
void vRM4_EMAC_RESET__Soft_Reset (void)
Perform a soft reset.
SafeTool Function MD5:
620D7BB4A0D1C0517E074B2B28FC33D9
SafeTool Function ID:
LCCM254R0.FILE.020.FUNC.001
References EMAC_BASE, EMAC_SOFT_RESET, EMAC_SOFTRESET, and HWREG.
Referenced by vRM4_EMAC__Init().
void vRM4_EMAC_RX__RxIntHandler (void)
Rx Interrupt Handler.
28.2.17.1.2 Receive Packet Completion Interrupts The receive DMA engine has eight channels, which each channel having a corresponding interrupt [RXPENDn). The receive interrupts are level interrupts that remain asserted until cleared by the CPU. Each of the eight receive channel interrupts may be individually enabled by setting the appropriate bit in the receive interrupt mask set register [RXINTMASKSET) to 1. Each of the eight receive channel interrupts may be individually disabled by clearing the appropriate bit by writing a 1 in the receive interrupt mask clear register [RXINTMASKCLEAR). The raw and masked receive interrupt status may be read by reading the receive interrupt status [unmasked) register [RXINTSTATRAW) and the receive interrupt status [masked) register [RXINTSTATMASKED), respectively.
When the EMAC completes a packet reception, the EMAC issues an interrupt to the CPU by writing the packet's last buffer descriptor address to the appropriate channel queue's receive completion pointer located in the state RAM block. The interrupt is generated by the write when enabled by the interrupt mask, regardless of the value written. Upon interrupt reception, the CPU processes one or more packets from the buffer chain and then acknowledges one or more interrupt[s) by writing the address of the last buffer descriptor processed to the queue's associated receive completion pointer in the receive DMA state RAM. The data written by the host [buffer descriptor address of the last processed buffer) is compared to the data in the register written by the EMAC [address of last buffer descriptor used by the EMAC). If the two values are not equal [which means that the EMAC has received more packets than the CPU has processed interrupts for), the receive packet completion interrupt signal remains asserted. If the two values are equal [which means that the host has processed all packets that the EMAC has received), the pending interrupt is de-asserted. The value that the EMAC is expecting is found by reading the receive channel n completion pointer register [RXnCP). The EMAC write to the completion pointer actually stores the value in the state RAM. The CPU written value does not actually change the register value. The host written value is compared to the register content [which was written by the EMAC) and if the two values are equal then the interrupt is removed; otherwise, the interrupt remains asserted. The host may process multiple packets prior to acknowledging an interrupt, or the host may acknowledge interrupts for every packet. The application software must acknowledge the EMAC control module after processing packets by writing the appropriate C0TX key to the EMAC End-Of-Interrupt Vector register [MACEOIVECTOR). See Section 28.5.12 for the acknowledge key values.
SafeTool Function MD5:
4832A593C55223462546628F2E0510D1
SafeTool Function ID:
LCCM254R0.FILE.008.FUNC.001
References EMAC_DSC_FLAG_OWNER, EMAC_DSC_FLAG_SOP, EMAC_INT_CORE0_RX, EMAC_INT_CORE0_TX, m_pEMAC_IF, RM4_EMAC_IF::pEMAC_Rx_Channel, RM4_EMAC__RX_CHANNEL_T::pHeadDescriptor, RM4_EMAC__RX_BD_T::pu32Buffer, RM4_EMAC__RX_BD_T::u16BufferOffset__u16BufferLength, RM4_EMAC__RX_BD_T::u16Flags__u16PacketLength, vRM4_EMAC__RxHdrDescPtrWrite(), vRM4_EMAC__Write_RxChannelCompletionPointer(), and vRM4_EMAC_INT__CoreIntAck().
Referenced by vRM4_EMAC_INT__RxISR().
void vRM4_EMAC_TX__Tx_IntHandler (void)
Transmit interrupt handler.
SafeTool Function MD5:
CB980C816513107B0A31B342EA4C1726
SafeTool Function ID:
LCCM254R0.FILE.007.FUNC.001
References EMAC_DSC_FLAG_EOP, EMAC_DSC_FLAG_OWNER, EMAC_DSC_FLAG_SOP, EMAC_INT_CORE0_TX, m_pEMAC_IF, RM4_EMAC_IF::pEMAC_Tx_Channel, RM4_EMAC__TX_CHANNEL_T::pHeadDescriptor, RM4_EMAC__TX_BD_T::pNextBlockDescriptor, RM4_EMAC__TX_BD_T::u16Flags__u16PacketLength, vRM4_EMAC__Write_TxChannelCompletionPointer(), and vRM4_EMAC_INT__CoreIntAck().
Referenced by vRM4_EMAC_INT__TxISR().
Variable Documentation
RM4_EMAC__LINK_STATE_T RM4_EMAC_IF::eLinkState
Referenced by u8RM4_EMAC_LINK__Is_LinkUp(), vRM4_EMAC_LINK__Init(), vRM4_EMAC_LINK__Process(), and vRM4_EMAC_LINK__Set_State().
struct RM4_EMAC__RX_CHANNEL_T RM4_EMAC_IF::pEMAC_Rx_Channel
Referenced by vRM4_EMAC_BD__Init(), vRM4_EMAC_LINK__Process(), and vRM4_EMAC_RX__RxIntHandler().
struct RM4_EMAC__TX_CHANNEL_T RM4_EMAC_IF::pEMAC_Tx_Channel
Referenced by vRM4_EMAC_BD__Init(), vRM4_EMAC_BD__Set_Length(), and vRM4_EMAC_TX__Tx_IntHandler().
struct { ... } RM4_EMAC_IF::sStats
Stats about the link.
Referenced by vRM4_EMAC_LINK__Process().
struct { ... } RM4_EMAC_IF::sTxStack
Luint8 RM4_EMAC_IF::u8CableLength
Referenced by vRM4_EMAC_LINK__Process().
Luint8 { ... } ::u8CableLength
Luint8 RM4_EMAC_IF::u8IPAddx[4]
Referenced by vRM4_EMAC_LINK__Init().
Luint8 RM4_EMAC_IF::u8MACAddx[6]
Referenced by vRM4_EMAC_LINK__Init(), and vRM4_EMAC_LINK__Process().
Luint8 RM4_EMAC_IF::u8PairsSwapped
Referenced by vRM4_EMAC_LINK__Process().
Luint8 { ... } ::u8PairsSwapped
Luint8 RM4_EMAC_IF::u8PolarityInvert
Referenced by vRM4_EMAC_LINK__Process().
Luint8 { ... } ::u8PolarityInvert
Luint8 { ... } ::u8StackPos
Luint8 RM4_EMAC_IF::u8StackPos