LFW513 (RLOOP - POWER NODE): I2C__PINS
I2C__PINS
RM4 » I2C
Functions
void vRM4_I2C_PINS__Set_SDA_Tris (Luint8 u8Tris)
Set the SDA tristate.
void vRM4_I2C_PINS__Set_SCL_Tris (Luint8 u8Tris)
Set the SCL tristate register.
void vRM4_I2C_PINS__Set_SDA_Latch (Luint8 u8Latch)
Set the SDA latch pin.
void vRM4_I2C_PINS__Set_SCL_Latch (Luint8 u8Latch)
Set the SCL pin state.
Luint8 u8RM4_I2C_PINS__Get_SDA (void)
Gets the SDA line state.
Luint8 u8RM4_I2C_PINS__Get_SCL (void)
Gets the SCL line state.
void vRM4_I2C_PINS__Set_OutputLow (void)
set all outputs to low
void vRM4_I2C_PINS__Toggle_Clock (void)
Toggle the clock pin.
void vRM4_I2C_PINS__Set_Functional (void)
set pins to functional mode from output mode.
Detailed Description
Function Documentation
Luint8 u8RM4_I2C_PINS__Get_SCL (void)
Gets the SCL line state.
SafeTool Function MD5:
B6D4F979BD195A3A05301CC4F4309F3A
SafeTool Function ID:
LCCM215R0.FILE.007.FUNC.009
References C_LOCALDEF__LCCM215__I2CPFNC_PINFUNCT, C_LOCALDEF__LCCM215__I2CPFNC_PINFUNCT_IO, C_LOCALDEF__LCCM215__I2CPFNC_PINFUNCT_SHIFT, C_LOCALDEF__LCCM215__PDIR_SCLDIR_INPUT, C_LOCALDEF__LCCM215__PDIR_SCLDIR_SHIFT, and i2cREG1.
Referenced by u8RM4_I2C__Check_Pin_Condition().
Luint8 u8RM4_I2C_PINS__Get_SDA (void)
Gets the SDA line state.
SafeTool Function MD5:
0D28917AEF2C1D162A8CDEEA2B50A422
SafeTool Function ID:
LCCM215R0.FILE.007.FUNC.008
References C_LOCALDEF__LCCM215__I2CPFNC_PINFUNCT, C_LOCALDEF__LCCM215__I2CPFNC_PINFUNCT_IO, C_LOCALDEF__LCCM215__I2CPFNC_PINFUNCT_SHIFT, C_LOCALDEF__LCCM215__PDIR_SDADIR_INPUT, C_LOCALDEF__LCCM215__PDIR_SDADIR_SHIFT, and i2cREG1.
Referenced by u8RM4_I2C__Check_Pin_Condition(), and vRM4_I2C__Init().
void vRM4_I2C_PINS__Set_Functional (void)
set pins to functional mode from output mode.
SafeTool Function MD5:
E4A946DCC2414316A14676D696B91F23
SafeTool Function ID:
LCCM215R0.FILE.007.FUNC.002
References C_LOCALDEF__LCCM215__I2CDOUT_SCLOUT, C_LOCALDEF__LCCM215__I2CDOUT_SCLOUT_SHIFT, C_LOCALDEF__LCCM215__I2CDOUT_SDAOUT, C_LOCALDEF__LCCM215__I2CDOUT_SDAOUT_SHIFT, C_LOCALDEF__LCCM215__I2CPFNC_PINFUNCT, C_LOCALDEF__LCCM215__I2CPFNC_PINFUNCT_SHIFT, C_LOCALDEF__LCCM215__PDIR_SCLDIR, C_LOCALDEF__LCCM215__PDIR_SCLDIR_SHIFT, C_LOCALDEF__LCCM215__PDIR_SDADIR, C_LOCALDEF__LCCM215__PDIR_SDADIR_SHIFT, and i2cREG1.
Referenced by vRM4_I2C__Init().
void vRM4_I2C_PINS__Set_OutputLow (void)
set all outputs to low
SafeTool Function MD5:
ED823E209F211799185E607313A2B98D
SafeTool Function ID:
LCCM215R0.FILE.007.FUNC.001
References C_LOCALDEF__LCCM215__I2CDOUT_SCLOUT_LOW, C_LOCALDEF__LCCM215__I2CDOUT_SCLOUT_SHIFT, C_LOCALDEF__LCCM215__I2CDOUT_SDAOUT_LOW, C_LOCALDEF__LCCM215__I2CDOUT_SDAOUT_SHIFT, C_LOCALDEF__LCCM215__I2CPFNC_PINFUNCT_IO, C_LOCALDEF__LCCM215__I2CPFNC_PINFUNCT_SHIFT, C_LOCALDEF__LCCM215__PDIR_SCLDIR, C_LOCALDEF__LCCM215__PDIR_SCLDIR_SHIFT, C_LOCALDEF__LCCM215__PDIR_SDADIR, C_LOCALDEF__LCCM215__PDIR_SDADIR_SHIFT, and i2cREG1.
void vRM4_I2C_PINS__Set_SCL_Latch (Luint8 u8Latch)
Set the SCL pin state.
Parameters
[in] u8Latch 1 or 0
SafeTool Function MD5:
F5739D605051185C3D4ACD972C64666C
SafeTool Function ID:
LCCM215R0.FILE.007.FUNC.007
References C_LOCALDEF__LCCM215__I2CDOUT_SCLOUT_SHIFT, C_LOCALDEF__LCCM215__I2CPFNC_PINFUNCT_IO, C_LOCALDEF__LCCM215__I2CPFNC_PINFUNCT_SHIFT, and i2cREG1.
Referenced by vRM4_I2C__Init().
void vRM4_I2C_PINS__Set_SCL_Tris (Luint8 u8Tris)
Set the SCL tristate register.
Parameters
[in] u8Tris 1 = input, 0 = output
SafeTool Function MD5:
306C0AAEBE755B963474EA907E7BEF4A
SafeTool Function ID:
LCCM215R0.FILE.007.FUNC.005
References C_LOCALDEF__LCCM215__I2CPFNC_PINFUNCT_IO, C_LOCALDEF__LCCM215__I2CPFNC_PINFUNCT_SHIFT, C_LOCALDEF__LCCM215__PDIR_SCLDIR_INPUT, C_LOCALDEF__LCCM215__PDIR_SCLDIR_OUTPUT, C_LOCALDEF__LCCM215__PDIR_SCLDIR_SHIFT, and i2cREG1.
Referenced by vRM4_I2C__Init().
void vRM4_I2C_PINS__Set_SDA_Latch (Luint8 u8Latch)
Set the SDA latch pin.
Parameters
[in] u8Latch The pin value
SafeTool Function MD5:
8DBC5F056D8C010B655067F868D2DE92
SafeTool Function ID:
LCCM215R0.FILE.007.FUNC.006
References C_LOCALDEF__LCCM215__I2CDOUT_SDAOUT_SHIFT, C_LOCALDEF__LCCM215__I2CPFNC_PINFUNCT_IO, C_LOCALDEF__LCCM215__I2CPFNC_PINFUNCT_SHIFT, and i2cREG1.
Referenced by vRM4_I2C__Init().
void vRM4_I2C_PINS__Set_SDA_Tris (Luint8 u8Tris)
Set the SDA tristate.
Parameters
[in] u8Tris 0 = output, 1 = input
SafeTool Function MD5:
435697874ED6D25EAA87CC5BFF13BBD7
SafeTool Function ID:
LCCM215R0.FILE.007.FUNC.004
References C_LOCALDEF__LCCM215__I2CPFNC_PINFUNCT_IO, C_LOCALDEF__LCCM215__I2CPFNC_PINFUNCT_SHIFT, C_LOCALDEF__LCCM215__PDIR_SDADIR_INPUT, C_LOCALDEF__LCCM215__PDIR_SDADIR_OUTPUT, C_LOCALDEF__LCCM215__PDIR_SDADIR_SHIFT, and i2cREG1.
Referenced by vRM4_I2C__Init().
void vRM4_I2C_PINS__Toggle_Clock (void)
Toggle the clock pin.
SafeTool Function MD5:
3F6266E6D1622ABFC42CBC14A3A4DA39
SafeTool Function ID:
LCCM215R0.FILE.007.FUNC.003
References C_LOCALDEF__LCCM215__I2CDOUT_SCLOUT_HIGH, C_LOCALDEF__LCCM215__I2CDOUT_SCLOUT_SHIFT, i2cREG1, and vRM4_DELAYS__Delay_mS().