LFW513 (RLOOP - POWER NODE): SPI135__CORE
SPI135__CORE
RM4 » SPI135
Functions
void vRM4_MIBSPI135__Setup_Multibuffered (RM4_MIBSPI135__CHANNELS_T eChannel)
Setup and configure Multibuffering mode.
void vRM4_MIBSPI135__Init (RM4_MIBSPI135__CHANNELS_T eChannel)
Init the SPI module, Each channel must be initted separately.
Detailed Description
Function Documentation
void vRM4_MIBSPI135__Init (RM4_MIBSPI135__CHANNELS_T eChannel)
Init the SPI module, Each channel must be initted separately.
Parameters
[in] eChannel The channel index
SafeTool Function MD5:
E5E9AC0B8F563E66F6AFBE75E9AE27A2
SafeTool Function ID:
LCCM280R0.FILE.001.FUNC.001
References RM4_MIBSPI135__BASE_T::DEF, RM4_MIBSPI135__BASE_T::DELAY, RM4_MIBSPI135__BASE_T::FLG, RM4_MIBSPI135__BASE_T::GCR0, RM4_MIBSPI135__BASE_T::GCR1, RM4_MIBSPI135__BASE_T::INT0, MIBSPI135_CHANNEL__1, MIBSPI135_CHANNEL__3, MIBSPI135_CHANNEL__5, MIBSPI135_CS__NONE, MIBSPI135_DATA_FORMAT__0, MIBSPI135_DATA_FORMAT__1, MIBSPI135_DATA_FORMAT__2, MIBSPI135_DATA_FORMAT__3, RM4_MIBSPI135__BASE_T::MIBSPIE, mibspiREG1, mibspiREG3, mibspiREG5, RM4_MIBSPI135__BASE_T::UERRCTRL, vRM4_MIBSPI135__Set_Speed(), vRM4_MIBSPI135__Setup_Interrupts(), vRM4_MIBSPI135__Setup_Multibuffered(), and vRM4_MIBSPI135_PINS__Set_Defaults().
Referenced by vPWRNODE__Process().
void vRM4_MIBSPI135__Setup_Multibuffered (RM4_MIBSPI135__CHANNELS_T eChannel)
Setup and configure Multibuffering mode.
Parameters
[in] eChannel The SPI channel
SafeTool Function MD5:
8C3C34097D90DBA2BAA7C4F7EB1BDDB3
SafeTool Function ID:
LCCM280R0.FILE.001.FUNC.002
References RM4_MIBSPI135__BASE_T::LTGPEND, MIBSPI135_CHANNEL__1, MIBSPI135_CHANNEL__3, MIBSPI135_CHANNEL__5, mibspiRAM3, mibspiREG1, mibspiREG3, mibspiREG5, and RM4_MIBSPI135__BASE_T::TGCTRL.
Referenced by vRM4_MIBSPI135__Init().