LFW513 (RLOOP - POWER NODE): EMAC__TX
EMAC__TX
RM4 » EMAC
Functions
void vRM4_EMAC_TX__Tx_IntHandler (void)
Transmit interrupt handler.
Variables
struct RM4_EMAC_IF m_pEMAC_IF
Detailed Description
Function Documentation
void vRM4_EMAC_TX__Tx_IntHandler (void)
Transmit interrupt handler.
SafeTool Function MD5:
CB980C816513107B0A31B342EA4C1726
SafeTool Function ID:
LCCM254R0.FILE.007.FUNC.001
References EMAC_DSC_FLAG_EOP, EMAC_DSC_FLAG_OWNER, EMAC_DSC_FLAG_SOP, EMAC_INT_CORE0_TX, m_pEMAC_IF, RM4_EMAC_IF::pEMAC_Tx_Channel, RM4_EMAC__TX_CHANNEL_T::pHeadDescriptor, RM4_EMAC__TX_BD_T::pNextBlockDescriptor, RM4_EMAC__TX_BD_T::u16Flags__u16PacketLength, vRM4_EMAC__Write_TxChannelCompletionPointer(), and vRM4_EMAC_INT__CoreIntAck().
Referenced by vRM4_EMAC_INT__TxISR().
Variable Documentation
struct RM4_EMAC_IF m_pEMAC_IF
Referenced by vRM4_EMAC_TX__Tx_IntHandler().