LFW513 (RLOOP - POWER NODE): RTI__CORE
RTI__CORE
RM4 » RTI
Functions
void vRM4_RTI__Start_Interrupts (void)
Sart the RTI interrupts.
void vRM4_RTI__Struct_Init (void)
Init the main struct Input valeus must be specified in microseconds as an integer.
void vRM4_RTI__Init (void)
Initialises the RTI module with the values stored in the RTI struct.
void vRM4_RTI__Update_Period (Luint8 u8Counter, Luint32 u32Period_US)
Update the period of a counter.
void vRM4_RTI__Clear_Flags (Luint32 u32FlagsToClear)
Clears the flags indicated by u32FlagsToClear parameter.
void vRM4_RTI__Start_Counter (Luint32 u32Counter)
Starts the indicated counter.
Lint16 s16RM4_RTI__Stop_Counter (Luint32 u32Counter)
Stops the indicated counter.
Lint16 s16RM4_RTI__ResetCounter (Luint32 u32Counter)
Reset the counter.
Luint32 u32RM4_RTI__Get_FreeClock (Luint8 u8Index)
Get the free running clock value.
void vRM4_RTI__SystemReset (void)
Perform a system reset.
Variables
struct _strRTI sRTI
RM4_RTI__INTERNAL_CLOCK_T sRTI_CLK
Lfloat32 f32_FIT
Detailed Description
Function Documentation
Lint16 s16RM4_RTI__ResetCounter (Luint32 u32Counter)
Reset the counter.
Parameters
[in] u32Counter The counter index
SafeTool Function MD5:
D7530AF11C95DEC2CC38F671841E5055
SafeTool Function ID:
LCCM124R0.FILE.001.FUNC.012
References RM48L950_RTI_NUMBER_OF_COUNTERS, and rtiREG1.
Lint16 s16RM4_RTI__Stop_Counter (Luint32 u32Counter)
Stops the indicated counter.
Parameters
[in] u32Counter The counter index
SafeTool Function MD5:
20D91C3786BC7C371AD0AADC52DAE930
SafeTool Function ID:
LCCM124R0.FILE.001.FUNC.011
References _strRTI::Counter0_Running, _strRTI::Counter1_Running, RM48L950_RTI_COUNTER_0_STOPPED, RM48L950_RTI_COUNTER_1_STOPPED, RM48L950_RTI_COUNTER_DOES_NOT_EXIST, RM48L950_RTI_COUNTER_ONE, RM48L950_RTI_COUNTER_ZERO, RM48L950_RTI_NUMBER_OF_COUNTERS, rtiREG1, and sRTI.
Luint32 u32RM4_RTI__Get_FreeClock (Luint8 u8Index)
Get the free running clock value.
Parameters
[in] u8Index Clock Index
SafeTool Function MD5:
871198B180D89CA8954299E7E9704363
SafeTool Function ID:
LCCM124R0.FILE.001.FUNC.013
References rtiREG1.
Referenced by vRM4_CAN_RX__RxMessage().
void vRM4_RTI__Clear_Flags (Luint32 u32FlagsToClear)
Clears the flags indicated by u32FlagsToClear parameter.
Parameters
[in] u32FlagsToClear The flag mask
SafeTool Function MD5:
DD9D9B69886124C86D1E64A92F224A6F
SafeTool Function ID:
LCCM124R0.FILE.001.FUNC.004
References rtiREG1.
Referenced by vRM4_RTI__Init(), and vRM4_RTI_ISR__Enable_Interrupts().
void vRM4_RTI__Init (void)
Initialises the RTI module with the values stored in the RTI struct.
vRM4_RTI__Struct_Init must be called before calling this function.
SafeTool Function MD5:
3F4CBDA502A745C1A95F74CDA7D09820
SafeTool Function ID:
LCCM124R0.FILE.001.FUNC.003
References _strRTI::Counter0_Running, _strRTI::Counter1_Running, _strRTI::CountersRunInHaltDebug, _strCounter::CUCompareValuePrescale, _strCounter::CUValue, f32_FIT, _strRTI::FRC0_IncrementsOnFailingExternalClock, _strCounter::FRCValue, _strRTI::NTUsignalforTimeBase, rtiREG1, _strRTI::sCompare, _strRTI::sCounter, _strRTI::SourceCaptureEventCounter0, _strRTI::SourceCaptureEventCounter1, sRTI, _strRTI::TimebaseForFRC0, _strCompare::u32Compare, _strCompare::u32UpdateCompare, _strCompare::u8CounterToCompareWith, vRM4_RTI__Clear_Flags(), vRM4_RTI__Struct_Init(), and vRM4_RTI_ISR__Disable_Interrupts().
void vRM4_RTI__Start_Counter (Luint32 u32Counter)
Starts the indicated counter.
Parameters
[in] u32Counter The counter index.
SafeTool Function MD5:
763E0A9BD969CCB826E0F474AD6BC015
SafeTool Function ID:
LCCM124R0.FILE.001.FUNC.010
References _strRTI::Counter0_Running, _strRTI::Counter1_Running, RM48L950_RTI_NUMBER_OF_COUNTERS, rtiREG1, and sRTI.
void vRM4_RTI__Start_Interrupts (void)
Sart the RTI interrupts.
SafeTool Function MD5:
6BEBA2A4E9301F143EE1E5624BAD7935
SafeTool Function ID:
LCCM124R0.FILE.001.FUNC.001
void vRM4_RTI__Struct_Init (void)
Init the main struct Input valeus must be specified in microseconds as an integer.
SafeTool Function MD5:
6C288CBC49F0BFE3D732ECD33DC0B353
SafeTool Function ID:
LCCM124R0.FILE.001.FUNC.002
References _strRTI::Compare0_InterruptEnabled, _strRTI::Compare1_InterruptEnabled, _strRTI::Compare2_InterruptEnabled, _strRTI::Compare3_InterruptEnabled, _strRTI::Counter0_Running, _strRTI::Counter1_Running, _strRTI::CountersRunInHaltDebug, _strCounter::CUCompareValuePrescale, _strCounter::CUValue, _strRTI::DMA0_RequestEnabled, _strRTI::DMA1_RequestEnabled, _strRTI::DMA2_RequestEnabled, _strRTI::DMA3_RequestEnabled, RM4_RTI__COUNTER_CLOCK_T::f32OutFreq, RM4_RTI__COUNTER_CLOCK_T::f32SrcFrequency, _strRTI::FRC0_IncrementsOnFailingExternalClock, _strRTI::FRC0_OverflowInterruptEnabled, _strRTI::FRC1_OverflowInterruptEnabled, _strCounter::FRCValue, _strRTI::NTUsignalforTimeBase, RM48L950_RTI_CAPTURE0_TRIG, RM48L950_RTI_CAPTURE1_TRIG, RM48L950_RTI_COMPARE0, RM48L950_RTI_COMPARE1, RM48L950_RTI_COMPARE2, RM48L950_RTI_COMPARE3, RM48L950_RTI_COMPARE_WITH_COUNTER_0, RM48L950_RTI_COUNTER0_PRESC, RM48L950_RTI_COUNTER1_PRESC, RM48L950_RTI_COUNTER_0_STOPPED, RM48L950_RTI_COUNTER_1_STOPPED, RM48L950_RTI_COUNTERS_STOP_ON_DEBUG_HALT, RM48L950_RTI_CU0_PRESET, RM48L950_RTI_CU1_PRESET, RM48L950_RTI_FRC0_PRESET, RM48L950_RTI_FRC0_TIMEBASE, RM48L950_RTI_FRC1_PRESET, RM48L950_RTI_FREE_RUNNING_COUNTER_NOT_INC_ON_FAILING_EXT_CLK, RM48L950_RTI_NTU0, RM48L950_RTI_NUMBER_OF_COMPARE_MODULES, _strRTI::sCompare, _strRTI::sCounter, RM4_RTI__INTERNAL_CLOCK_T::sCounters, _strRTI::SourceCaptureEventCounter0, _strRTI::SourceCaptureEventCounter1, sRTI, _strRTI::TimebaseForFRC0, _strRTI::TimebaseInterruptEnabled, _strCompare::u32Compare, _strCompare::u32UpdateCompare, _strCompare::u8CounterToCompareWith, and RM4_RTI__COUNTER_CLOCK_T::u8Div.
Referenced by vRM4_RTI__Init().
void vRM4_RTI__SystemReset (void)
Perform a system reset.
SafeTool Function MD5:
D2137B39BB37095D91EE43500657C499
SafeTool Function ID:
LCCM124R0.FILE.001.FUNC.015
References rtiREG1.
void vRM4_RTI__Update_Period (Luint8 u8Counter, Luint32 u32Period_US)
Update the period of a counter.
Parameters
[in] u32Period_US New period in uS
[in] u8Counter The counter index
SafeTool Function MD5:
2A9B22CFAFE88F00CBB957AE37962E33
SafeTool Function ID:
LCCM124R0.FILE.001.FUNC.014
References RM4_RTI__COUNTER_CLOCK_T::f32OutFreq, RM48L950_RTI_COMPARE_WITH_COUNTER_0, RM48L950_RTI_NUMBER_OF_COUNTERS, rtiREG1, _strRTI::sCompare, RM4_RTI__INTERNAL_CLOCK_T::sCounters, sRTI, _strCompare::u32Compare, _strCompare::u32UpdateCompare, and _strCompare::u8CounterToCompareWith.
Variable Documentation
Lfloat32 f32_FIT
Referenced by vRM4_RTI__Init().
struct _strRTI sRTI
Referenced by s16RM4_RTI__Stop_Counter(), vRM4_RTI__Init(), vRM4_RTI__Start_Counter(), vRM4_RTI__Struct_Init(), vRM4_RTI__Update_Period(), vRM4_RTI_ISR__Disable_Interrupts(), vRM4_RTI_ISR__Enable_Interrupts(), vRTI_COMPARE__Disable_CompareInterrupt(), and vRTI_COMPARE__Enable_CompareInterrupt().
RM4_RTI__INTERNAL_CLOCK_T sRTI_CLK