LFW513 (RLOOP - POWER NODE): RM4__N2HET__EDGE
RM4__N2HET__EDGE
RM4 » RM4__N2HET
Functions
Luint16 u16N2HET_PROG_DYNAMIC__Add_Edge (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32PinIndex, RM4_N2HET__EDGE_EDGE_T eType, Luint8 u8EnableInterrupt)
Adds a dynamic edge detection program.
Luint16 u16N2HET_PROG_DYNAMIC__Add_Edge_Counter (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32PinIndex, RM4_N2HET__EDGE_EDGE_T eType, Luint8 u8EnableInterrupt, Luint32 u32MaxCount)
Adds an edge counter program After max count the interrupt will be fired.
Variables
struct _strRM4_N2HET sN2HET
Detailed Description
Function Documentation
Luint16 u16N2HET_PROG_DYNAMIC__Add_Edge (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32PinIndex, RM4_N2HET__EDGE_EDGE_T eType, Luint8 u8EnableInterrupt)
Adds a dynamic edge detection program.
Parameters
[in] u8EnableInterrupt Enable isr on edge
[in] eType The type of edge
[in] u32PinIndex The pin to use
[in] eChannel N2HET Channel
SafeTool Function MD5:
5C66CB10F7A0C37C8BBBC5911B9ECA6F
SafeTool Function ID:
LCCM240R0.FILE.024.FUNC.001
References DYN_TYPE__EDGE_DETECT, hetRAM1, hetRAM2, hetREG1, N2HET_CHANNEL__1, N2HET_PROG__REG_NONE, _strRM4_N2HET::sDynamicProgram, sN2HET, _strRM4_N2HET::sProgram, _strRM4_N2HET::u32InstructionCount, _strRM4_N2HET::u32ProgramCount, vN2HET_PROG__BR__Make(), and vN2HET_PROG__Update_RAM().
Referenced by u16N2HET_PROG_DYNAMIC__Add_QEP().
Luint16 u16N2HET_PROG_DYNAMIC__Add_Edge_Counter (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32PinIndex, RM4_N2HET__EDGE_EDGE_T eType, Luint8 u8EnableInterrupt, Luint32 u32MaxCount)
Adds an edge counter program After max count the interrupt will be fired.
Parameters
[in] u32MaxCount The maxiumum edge count before an ISR will be fired
[in] u8EnableInterrupt 1 = Enable Interrupt
[in] eType The edge type
[in] u32PinIndex The pin in the HET module
[in] eChannel The channel
SafeTool Function MD5:
82DE05D0EE7E85708BEFFF460CA5B2C0
SafeTool Function ID:
LCCM240R0.FILE.024.FUNC.003
References DYN_TYPE__EDGE_COUNTER, EDGE_TYPE__RISING, hetRAM1, hetRAM2, N2HET_CHANNEL__1, N2HET_PROG__REG_T, _strRM4_N2HET::sDynamicProgram, sN2HET, _strRM4_N2HET::sProgram, _strRM4_N2HET::u32InstructionCount, _strRM4_N2HET::u32ProgramCount, vN2HET_PROG__BR__Make(), and vN2HET_PROG__Update_RAM().
Variable Documentation
struct _strRM4_N2HET sN2HET
Referenced by u16N2HET_PROG_DYNAMIC__Add_Edge(), and u16N2HET_PROG_DYNAMIC__Add_Edge_Counter().