LFW513 (RLOOP - POWER NODE): DELAYS__CORE
DELAYS__CORE
RM4 » DELAYS
Functions
void vRM4_DELAYS__Delay_mS (Luint32 u32Value)
Millisecond delay.
void vRM4_DELAYS__Delay_uS (Luint32 u32Value)
Microseconds Delay.
Detailed Description
Function Documentation
void vRM4_DELAYS__Delay_mS (Luint32 u32Value)
Millisecond delay.
Parameters
[in] u32Value Delay in milliseconds
SafeTool Function MD5:
58460ADF66242FBA8E0A90BCC7BA5CA3
SafeTool Function ID:
LCCM228R0.FILE.001.FUNC.001
References vRM4_DELAYS__Delay_uS().
Referenced by vATA6870__Init(), vDS18B20_DELAYS__Delay_mS(), vRM4_EMAC_LINK__Process(), and vRM4_I2C_PINS__Toggle_Clock().
void vRM4_DELAYS__Delay_uS (Luint32 u32Value)
Microseconds Delay.
Note
The following function is instruction based. Therefore: GCLK = 200MHZ = 5ns/instr
Parameters
[in] u32Value The delay in microseconds.
SafeTool Function MD5:
5062CA156C32574789620515A33FC074
SafeTool Function ID:
LCCM228R0.FILE.001.FUNC.002
References _pmuEnableCountersGlobal_(), _pmuGetCycleCount_(), _pmuResetCounters_(), _pmuStartCounters_(), _pmuStopCounters_(), and pmuCYCLE_COUNTER.
Referenced by s16DS2482S_LOWLEVEL__ReadReg(), s16DS2482S_LOWLEVEL__RxReg(), s16DS2482S_LOWLEVEL__TxReg(), s16DS2482S_LOWLEVEL__WriteReg(), u8DS2482S_DEVICE__Wait_Busy(), vDS18B20_DELAYS__Delay_uS(), vDS2482S__Init(), vRM4_DELAYS__Delay_mS(), vRM4_EMAC_LINK__Process(), and vRM4_I2C__Init().