LFW513 (RLOOP - POWER NODE): SELFTEST__CORE
SELFTEST__CORE
RM4 » SELFTEST
Functions
void vRM4_SELFTEST__Init (void)
Init the self test module.
void vRM4_SELFTEST__STC_Check (void)
This function is called to perform STC module self check.
void vRM4_SELFTEST__CPU_Test (Luint32 u32NumIntervals, Luint32 u32MaxTimeout, Luint8 u8RestartTest)
This function is called to perform CPU self test using STC module.
Luint32 u32RM4_SELFTEST__Get_FaultFlags (void)
Return the self test fault flags.
void vRM4_SELFTEST__Set_FailNotification (Luint32 u32Flag)
This function is called if there is a self test fail with appropriate flag.
void vRM4_SELFTEST__EFuse_Check (void)
EFUSE module self check Driver.
Luint8 u8RM4_SELFTEST__EFuse_StuckZeroTest (void)
Checks to see if the EFUSE Stuck at zero test is completed successfully.
void vRM4_SELFTEST__EFuse_SelfTest (void)
EFUSE module self check Driver.
Luint8 u8RM4_SELFTEST__EFuse_CheckSelfTest (void)
EFUSE module self check Driver.
void vRM4_SELFTEST__CCM_Check (void)
This function self checks the CCM module.
void vRM4_SELFTEST__MemoryInit (Luint32 u32RAM)
This function is called to perform Memory initialization of selected RAM's.
void vRM4_SELFTEST__VIM_ParityCheck (void)
Routine to check VIM RAM parity error detection and signaling mechanism.
void vRM4_SELFTEST__DMA_ParityCheck (void)
Routine to check DMA control packet RAM parity error detection and signaling mechanism.
void vRM4_SELFTEST__MIBSPI1_ParityCheck (void)
Routine to check MIBSPI1 RAM parity error detection and signaling mechanism.
void vRM4_SELFTEST__MIBSPI3_ParityCheck (void)
Routine to check MIBSPI3 RAM parity error detection and signaling mechanism.
void vRM4_SELFTEST__MIBSPI5_ParityCheck (void)
Routine to check MIBSPI5 RAM parity error detection and signaling mechanism.
void vRM4_SELFTEST__N2HET1_ParityCheck (void)
Routine to check HET1 RAM parity error detection and signaling mechanism.
void vRM4_SELFTEST__Check_RAMECC (void)
Check TCRAM ECC error detection logic.
void vRM4_SELFTEST__CAN1_ParityCheck (void)
Routine to check CAN1 RAM parity error detection and signaling mechanism.
void vRM4_SELFTEST__CAN2_ParityCheck (void)
Routine to check CAN2 RAM parity error detection and signaling mechanism.
void vRM4_SELFTEST__CAN3_ParityCheck (void)
Routine to check CAN3 RAM parity error detection and signaling mechanism.
void vRM4_SELFTEST__ADC1_ParityCheck (void)
Routine to check ADC1 RAM parity error detection and signaling mechanism.
void vRM4_SELFTEST__EnableParity (void)
This function enables RAM parity for all peripherals for which RAM parity check is enabled.
void vRM4_SELFTEST__DisableParity (void)
This function disables RAM parity for all peripherals for which RAM parity check is enabled.
Variables
struct _strRM4ST sRM4ST
Detailed Description
Function Documentation
Luint32 u32RM4_SELFTEST__Get_FaultFlags (void)
Return the self test fault flags.
SafeTool Function MD5:
110A3B0D5F8FC6DF3283614AD0B41C6F
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.020
References _strRM4ST::sFaultFlags, sRM4ST, and FAULT_TREE__PUBLIC_T::u32Flags.
Luint8 u8RM4_SELFTEST__EFuse_CheckSelfTest (void)
EFUSE module self check Driver.
SafeTool Function MD5:
6480CFAA948CC1F16B7AC29C926F48E0
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.005
References EFC_SELF_TEST_DONE, EFC_SELF_TEST_ERROR, efcREG, esmREG, and SELF_TEST_ERROR.
Referenced by vRM4_SYSTEM__Init().
Luint8 u8RM4_SELFTEST__EFuse_StuckZeroTest (void)
Checks to see if the EFUSE Stuck at zero test is completed successfully.
Returns
1 if EFUSE Stuck at zero test completed, otherwise 0.
SafeTool Function MD5:
ED2A4EA502708C103A0E7465B67BC705
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.003
References EFC_AUTOLOAD_ERROR_EN, EFC_INSTRUCTION_ERROR_EN, EFC_INSTRUCTION_INFO_EN, EFC_SELF_TEST_ERROR_EN, efcREG, esmREG, and OUTPUT_ENABLE.
Referenced by vRM4_SELFTEST__EFuse_Check().
void vRM4_SELFTEST__ADC1_ParityCheck (void)
Routine to check ADC1 RAM parity error detection and signaling mechanism.
SafeTool Function MD5:
41B60591F32470FCD01FE8FD87492881
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.023
References adcPARRAM1, adcPARRAM2, adcRAM1, adcRAM2, adcREG1, adcREG2, esmREG, and vRM4_SELFTEST__ADC2_ParityCheck().
Referenced by vRM4_SYSTEM__After_STC().
void vRM4_SELFTEST__CAN1_ParityCheck (void)
Routine to check CAN1 RAM parity error detection and signaling mechanism.
SafeTool Function MD5:
1502882B340E658E22EC85F829BDEA29
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.014
References C_LCCM221__CORE__FAULT_INDEX__00, C_LCCM221__CORE__FAULT_INDEX__11, canPARRAM1, canRAM1, canREG1, esmREG, _strRM4ST::sFaultFlags, sRM4ST, and vFAULTTREE__Set_Flag().
Referenced by vRM4_SYSTEM__After_STC().
void vRM4_SELFTEST__CAN2_ParityCheck (void)
Routine to check CAN2 RAM parity error detection and signaling mechanism.
SafeTool Function MD5:
31D62549D11659875B3B8F110B89652C
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.015
References C_LCCM221__CORE__FAULT_INDEX__00, C_LCCM221__CORE__FAULT_INDEX__12, canPARRAM2, canRAM2, canREG2, esmREG, _strRM4ST::sFaultFlags, sRM4ST, and vFAULTTREE__Set_Flag().
Referenced by vRM4_SYSTEM__After_STC().
void vRM4_SELFTEST__CAN3_ParityCheck (void)
Routine to check CAN3 RAM parity error detection and signaling mechanism.
SafeTool Function MD5:
8C8112DA40F557896D93DB323AD44D92
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.016
References C_LCCM221__CORE__FAULT_INDEX__00, C_LCCM221__CORE__FAULT_INDEX__13, canPARRAM3, canRAM3, canREG3, esmREG, _strRM4ST::sFaultFlags, sRM4ST, and vFAULTTREE__Set_Flag().
Referenced by vRM4_SYSTEM__After_STC().
void vRM4_SELFTEST__CCM_Check (void)
This function self checks the CCM module.
SafeTool Function MD5:
C4AE540BF2EE062780670717F1985523
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.021
References C_LCCM221__CORE__FAULT_INDEX__00, C_LCCM221__CORE__FAULT_INDEX__15, C_LCCM221__CORE__FAULT_INDEX__16, C_LCCM221__CORE__FAULT_INDEX__17, C_LCCM221__CORE__FAULT_INDEX__18, CCMKEYR, CCMSR, esmREG, _strRM4ST::sFaultFlags, sRM4ST, vFAULTTREE__Set_Flag(), and vimREG.
Referenced by vRM4_SYSTEM__After_STC().
void vRM4_SELFTEST__Check_RAMECC (void)
Check TCRAM ECC error detection logic.
SafeTool Function MD5:
97D3EE4673B9BE265A9EB2A812A046BC
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.013
References C_LCCM221__CORE__FAULT_INDEX__00, C_LCCM221__CORE__FAULT_INDEX__09, C_LCCM221__CORE__FAULT_INDEX__10, esmREG, _strRM4ST::sFaultFlags, sRM4ST, tcram1REG, tcram2REG, tcramA1bit, tcramA1bitError, tcramA2bit, tcramA2bitError, tcramB1bit, tcramB1bitError, tcramB2bit, tcramB2bitError, and vFAULTTREE__Set_Flag().
Referenced by vRM4_SYSTEM__After_STC().
void vRM4_SELFTEST__CPU_Test (Luint32 u32NumIntervals, Luint32 u32MaxTimeout, Luint8 u8RestartTest)
This function is called to perform CPU self test using STC module.
Parameters
[in] u8RestartTest Restart the test from Interval 0 or Continue from where it stopped.
[in] u32MaxTimeout Maximum Timeout to complete selected test Intervals
[in] u32NumIntervals Number of Test Intervals to be
SafeTool Function MD5:
3B1262810FCC55A3E0FB48CC2C88F8B9
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.019
References _gotoCPUIdle_(), and stcREG.
Referenced by _c_int00().
void vRM4_SELFTEST__DisableParity (void)
This function disables RAM parity for all peripherals for which RAM parity check is enabled.
This function is called after memoryInit in the startup
SafeTool Function MD5:
73946FF7592FFAA6272074CAA0770CBA
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.026
References adcREG1, adcREG2, canREG1, canREG2, canREG3, DMA_PARCR, hetREG1, hetREG2, htuREG1, htuREG2, and VIM_PARCTL.
Referenced by vRM4_SYSTEM__After_STC().
void vRM4_SELFTEST__DMA_ParityCheck (void)
Routine to check DMA control packet RAM parity error detection and signaling mechanism.
SafeTool Function MD5:
4262F591839E7BAD39708DC2D5AA5EEE
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.008
References C_LCCM221__CORE__FAULT_INDEX__00, C_LCCM221__CORE__FAULT_INDEX__04, DMA_PARADDR, DMA_PARCR, DMAPARITYCHECK_FAIL1, DMARAMLOC, DMARAMPARLOC, esmREG, _strRM4ST::sFaultFlags, sRM4ST, vFAULTTREE__Set_Flag(), and vRM4_SELFTEST__Set_FailNotification().
Referenced by vRM4_SYSTEM__After_STC().
void vRM4_SELFTEST__EFuse_Check (void)
EFUSE module self check Driver.
SafeTool Function MD5:
080CD0B22D82434C53FD970968208A54
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.002
References C_LCCM221__CORE__FAULT_INDEX__00, C_LCCM221__CORE__FAULT_INDEX__01, C_LCCM221__CORE__FAULT_INDEX__02, EFCCHECK_FAIL1, efcREG, _strRM4ST::sFaultFlags, sRM4ST, u8RM4_SELFTEST__EFuse_StuckZeroTest(), vFAULTTREE__Set_Flag(), vRM4_SELFTEST__EFuse_SelfTest(), and vRM4_SELFTEST__Set_FailNotification().
Referenced by vRM4_SYSTEM__Init().
void vRM4_SELFTEST__EFuse_SelfTest (void)
EFUSE module self check Driver.
SafeTool Function MD5:
57F9B1664F6F97CF2AEAEAE9D62189CC
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.004
References efcREG.
Referenced by vRM4_SELFTEST__EFuse_Check().
void vRM4_SELFTEST__EnableParity (void)
This function enables RAM parity for all peripherals for which RAM parity check is enabled.
This function is called before memoryInit in the startup
SafeTool Function MD5:
EC2387BD975C45435A8D34B8DDB15E46
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.025
References adcREG1, adcREG2, canREG1, canREG2, canREG3, DMA_PARCR, hetREG1, hetREG2, htuREG1, htuREG2, and VIM_PARCTL.
Referenced by vRM4_SYSTEM__After_STC().
void vRM4_SELFTEST__Init (void)
Init the self test module.
SafeTool Function MD5:
D6565113C3D6E6DA522BE9D4D3AFCD45
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.017
References _strRM4ST::sFaultFlags, sRM4ST, and vFAULTTREE__Init().
Referenced by _c_int00().
void vRM4_SELFTEST__MemoryInit (Luint32 u32RAM)
This function is called to perform Memory initialization of selected RAM's.
Parameters
[in] ram ## Desc ##
SafeTool Function MD5:
EE486F5F833589A17D23D5771A5AA49E
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.006
References systemREG1.
Referenced by vRM4_SYSTEM__After_STC().
void vRM4_SELFTEST__MIBSPI1_ParityCheck (void)
Routine to check MIBSPI1 RAM parity error detection and signaling mechanism.
SafeTool Function MD5:
D1713E4253489BB809CB409FDFB5B462
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.009
References C_LCCM221__CORE__FAULT_INDEX__00, C_LCCM221__CORE__FAULT_INDEX__05, esmREG, MIBSPI1PARITYCHECK_FAIL1, mibspiPARRAM1, mibspiRAM1, mibspiREG1, _strRM4ST::sFaultFlags, sRM4ST, vFAULTTREE__Set_Flag(), and vRM4_SELFTEST__Set_FailNotification().
Referenced by vRM4_SYSTEM__After_STC().
void vRM4_SELFTEST__MIBSPI3_ParityCheck (void)
Routine to check MIBSPI3 RAM parity error detection and signaling mechanism.
SafeTool Function MD5:
9D8743B115AB6A7F340910A680DF4792
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.010
References C_LCCM221__CORE__FAULT_INDEX__00, C_LCCM221__CORE__FAULT_INDEX__06, esmREG, MIBSPI3PARITYCHECK_FAIL1, mibspiPARRAM3, mibspiRAM3, mibspiREG3, _strRM4ST::sFaultFlags, sRM4ST, vFAULTTREE__Set_Flag(), and vRM4_SELFTEST__Set_FailNotification().
Referenced by vRM4_SYSTEM__After_STC().
void vRM4_SELFTEST__MIBSPI5_ParityCheck (void)
Routine to check MIBSPI5 RAM parity error detection and signaling mechanism.
SafeTool Function MD5:
30F8F2A32D77B4696AEE9807F2CE19B8
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.011
References C_LCCM221__CORE__FAULT_INDEX__00, C_LCCM221__CORE__FAULT_INDEX__07, esmREG, MIBSPI5PARITYCHECK_FAIL1, mibspiPARRAM5, mibspiRAM5, mibspiREG5, _strRM4ST::sFaultFlags, sRM4ST, vFAULTTREE__Set_Flag(), and vRM4_SELFTEST__Set_FailNotification().
Referenced by vRM4_SYSTEM__After_STC().
void vRM4_SELFTEST__N2HET1_ParityCheck (void)
Routine to check HET1 RAM parity error detection and signaling mechanism.
SafeTool Function MD5:
220C251564B153415FDB448ABE983B82
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.012
References C_LCCM221__CORE__FAULT_INDEX__00, C_LCCM221__CORE__FAULT_INDEX__08, C_LCCM221__CORE__FAULT_INDEX__14, esmREG, HET1PARITYCHECK_FAIL1, hetREG1, hetREG2, NHET1RAMLOC, NHET1RAMPARLOC, NHET2RAMLOC, NHET2RAMPARLOC, _strRM4ST::sFaultFlags, sRM4ST, vFAULTTREE__Set_Flag(), vRM4_SELFTEST__N2HET2_ParityCheck(), and vRM4_SELFTEST__Set_FailNotification().
Referenced by vRM4_SYSTEM__After_STC().
void vRM4_SELFTEST__Set_FailNotification (Luint32 u32Flag)
This function is called if there is a self test fail with appropriate flag.
Parameters
[in] flag ## Desc ##
SafeTool Function MD5:
5E7C05385A3E4E519FC32110284B346E
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.001
Referenced by vRM4_BIST__SelfCheck(), vRM4_SELFTEST__DMA_ParityCheck(), vRM4_SELFTEST__EFuse_Check(), vRM4_SELFTEST__MIBSPI1_ParityCheck(), vRM4_SELFTEST__MIBSPI3_ParityCheck(), vRM4_SELFTEST__MIBSPI5_ParityCheck(), vRM4_SELFTEST__N2HET1_ParityCheck(), and vRM4_SELFTEST__VIM_ParityCheck().
void vRM4_SELFTEST__STC_Check (void)
This function is called to perform STC module self check.
SafeTool Function MD5:
16728FD025D9001659346BD594D919E8
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.018
References _gotoCPUIdle_(), stcREG, and systemREG2.
Referenced by _c_int00().
void vRM4_SELFTEST__VIM_ParityCheck (void)
Routine to check VIM RAM parity error detection and signaling mechanism.
SafeTool Function MD5:
80D8339258C37DBA25929310F1A62303
SafeTool Function ID:
LCCM221R0.FILE.001.FUNC.007
References C_LCCM221__CORE__FAULT_INDEX__00, C_LCCM221__CORE__FAULT_INDEX__03, esmREG, _strRM4ST::sFaultFlags, sRM4ST, vFAULTTREE__Set_Flag(), VIM_PARCTL, VIM_PARFLG, VIMPARITYCHECK_FAIL1, VIMRAMLOC, VIMRAMPARLOC, and vRM4_SELFTEST__Set_FailNotification().
Referenced by vRM4_SYSTEM__After_STC().
Variable Documentation
struct _strRM4ST sRM4ST
Referenced by u32RM4_SELFTEST__Get_FaultFlags(), vRM4_SELFTEST__CAN1_ParityCheck(), vRM4_SELFTEST__CAN2_ParityCheck(), vRM4_SELFTEST__CAN3_ParityCheck(), vRM4_SELFTEST__CCM_Check(), vRM4_SELFTEST__Check_RAMECC(), vRM4_SELFTEST__DMA_ParityCheck(), vRM4_SELFTEST__EFuse_Check(), vRM4_SELFTEST__Init(), vRM4_SELFTEST__MIBSPI1_ParityCheck(), vRM4_SELFTEST__MIBSPI3_ParityCheck(), vRM4_SELFTEST__MIBSPI5_ParityCheck(), vRM4_SELFTEST__N2HET1_ParityCheck(), and vRM4_SELFTEST__VIM_ParityCheck().