LFW513 (RLOOP - POWER NODE): DS18B20__CORE
DS18B20__CORE
MULTICORE » DS18B20
Functions
void vDS18B20__Init (void)
Init the DS18B20 device.
void vDS18B20__Process (void)
Process DS18B20 systems Call from main program loop as quick as possible.
Variables
struct _strDS18B20 sDS18B20
Detailed Description
Function Documentation
void vDS18B20__Init (void)
Init the DS18B20 device.
SafeTool Function MD5:
F9EE967EC67F9DAD0866F756CF98A726
SafeTool Function ID:
LCCM644R0.FILE.000.FUNC.001
References s16DS18B20_ADDX__Search(), s16DS18B20_SCRATCH__Read(), s16DS18B20_TEMP__Get_Resolution(), s16DS18B20_TEMP__Request(), s16DS2482S_SEARCH__SearchFirstDevice(), _strDS18B20::sDevice, sDS18B20, _strDS18B20::sEnum, _strDS18B20::u8ChannelIndex, _strDS18B20::u8NumDevices, _strDS18B20::u8Resolution, _strDS18B20::u8SerialNumber, and vDS18B20_ADDX__Init().
Referenced by vPWRNODE_BATTTEMP__Init().
void vDS18B20__Process (void)
Process DS18B20 systems Call from main program loop as quick as possible.
SafeTool Function MD5:
231B3835C46BE862352D9F1FB404D4C2
SafeTool Function ID:
LCCM644R0.FILE.000.FUNC.002
References vDS18B20_ADDX__SearchSM_Process().
Variable Documentation
struct _strDS18B20 sDS18B20
Referenced by s16DS18B20_ADDX__Search(), s16DS18B20_SCRATCH__Read(), s16DS18B20_SCRATCH__Write(), s16DS18B20_TEMP__All_Request(), s16DS18B20_TEMP__Request(), u8DS18B20_ADDX__SearchSM_IsBusy(), vDS18B20__Init(), vDS18B20_ADDX__Init(), vDS18B20_ADDX__SearchSM_Process(), vDS18B20_ADDX__SearchSM_Start(), and vDS18B20_TEMP__Scratch_To_Temp().