LFW513 (RLOOP - POWER NODE): NUMERICAL__POINTS
NUMERICAL__POINTS
MULTICORE » NUMERICAL
Functions
Lfloat32 f32NUMERICAL_POINTS__Length_BetweenPoints_2DPoints (const struct tsNUM_f32Point_2D *pt1, const struct tsNUM_f32Point_2D *pt2)
Calculates a distance between two 2D points.
void vNUMERICAL_POINTS__Bounds_U162D (struct tsNUM_u16Point_2D *ptArray, Luint16 u16NumPoints, Luint16 *pu16MinX, Luint16 *pu16MinY, Luint16 *pu16MaxX, Luint16 *pu16MaxY)
Get a bounding box for a set of points.
Luint16 u16NUMERICAL_POINTS__Min (Luint16 u16A, Luint16 u16B)
Gets the minimum of two values U16.
Lint16 s16NUMERICAL_POINTS__Min (Lint16 s16A, Lint16 s16B)
Gets the minimum of two values.
Luint16 u16NUMERICAL_POINTS__Max (Luint16 u16A, Luint16 u16B)
Return the max of two values.
Lint16 s16NUMERICAL_POINTS__Max (Lint16 s16A, Lint16 s16B)
Return the max of two values.
Lfloat32 f32NUMERICAL_POINTS__Length_BetweenPoints_S16 (Lint16 s16AX, Lint16 s16AY, Lint16 s16BX, Lint16 s16BY)
Calc the length between 2 points, int16.
Lfloat32 f32NUMERICAL_POINTS__Calculate_Mx_FromPoints_S16 (Lint16 s16AX, Lint16 s16AY, Lint16 s16BX, Lint16 s16BY)
Calculates the M in y = mx plus c, int16.
Luint8 u8NUMERICAL_POINTS__Point_BetweenTwoS16 (Lint16 s16A, Lint16 s16B, Lint16 s16TestPoint)
Checks if a point is between two others.
Detailed Description
Function Documentation
Lfloat32 f32NUMERICAL_POINTS__Calculate_Mx_FromPoints_S16 (Lint16 s16AX, Lint16 s16AY, Lint16 s16BX, Lint16 s16BY)
Calculates the M in y = mx plus c, int16.
Parameters
[in] s16BY Point By
[in] s16BX Point Bx
[in] s16AY Point Ay
[in] s16AX Point Ax
Returns
The slope of the line
SafeTool Function MD5:
F83622D35413E43AC259018C1217E492
SafeTool Function ID:
LCCM118R0.FILE.009.FUNC.003
Lfloat32 f32NUMERICAL_POINTS__Length_BetweenPoints_2DPoints (const struct tsNUM_f32Point_2D * pt1, const struct tsNUM_f32Point_2D * pt2)
Calculates a distance between two 2D points.
Parameters
[in] pt1 Point 1
[in] pt2 Point 2
Returns
Returns the distance between two 2D points
SafeTool Function MD5:
F39FF900C648C06E4DEE52A9D3165BE6
SafeTool Function ID:
LCCM118R0.FILE.009.FUNC.001
References tsNUM_f32Point_2D::f32X, and tsNUM_f32Point_2D::f32Y.
Lfloat32 f32NUMERICAL_POINTS__Length_BetweenPoints_S16 (Lint16 s16AX, Lint16 s16AY, Lint16 s16BX, Lint16 s16BY)
Calc the length between 2 points, int16.
Parameters
[in] s16BY Point By
[in] s16BX Point Bx
[in] s16AY Point Ay
[in] s16AX Point Ax
Returns
The length of the segment between the lines
SafeTool Function MD5:
3CD5FCD38A749B9A1EA571FF9BAB66BA
SafeTool Function ID:
LCCM118R0.FILE.009.FUNC.002
Lint16 s16NUMERICAL_POINTS__Max (Lint16 s16A, Lint16 s16B)
Return the max of two values.
Parameters
[in] s16B Value B
[in] s16A Value A
Returns
The maximum of A or B
SafeTool Function MD5:
2AA92FDB4B808FB9DD625AC967E02F2B
SafeTool Function ID:
LCCM118R0.FILE.009.FUNC.009
Referenced by u8NUMERICAL_POINTS__Point_BetweenTwoS16().
Lint16 s16NUMERICAL_POINTS__Min (Lint16 s16A, Lint16 s16B)
Gets the minimum of two values.
Parameters
[in] s16B Value B
[in] s16A Value A
Returns
The min of A or B
SafeTool Function MD5:
56AA85AD0E1301A6ACDC5965AAAE9EDB
SafeTool Function ID:
LCCM118R0.FILE.009.FUNC.008
Referenced by u8NUMERICAL_POINTS__Point_BetweenTwoS16().
Luint16 u16NUMERICAL_POINTS__Max (Luint16 u16A, Luint16 u16B)
Return the max of two values.
Parameters
[in] u16B Value B
[in] u16A Value A
Returns
The max of val A or B
SafeTool Function MD5:
6623BF690F67BFF8441F1C1587EFB9A8
SafeTool Function ID:
LCCM118R0.FILE.009.FUNC.006
Referenced by vNUMERICAL_POINTS__Bounds_U162D().
Luint16 u16NUMERICAL_POINTS__Min (Luint16 u16A, Luint16 u16B)
Gets the minimum of two values U16.
Parameters
[in] u16B Value B
[in] u16A Value A
Returns
The minimum of A or B
SafeTool Function MD5:
DDD79D9AF222EE4D8B07093BFC4C29B2
SafeTool Function ID:
LCCM118R0.FILE.009.FUNC.005
Referenced by vNUMERICAL_POINTS__Bounds_U162D().
Luint8 u8NUMERICAL_POINTS__Point_BetweenTwoS16 (Lint16 s16A, Lint16 s16B, Lint16 s16TestPoint)
Checks if a point is between two others.
Parameters
[in] s16TestPoint The test point
[in] s16B Point B
[in] s16A Point A
Returns
0 = not between
1 = between
SafeTool Function MD5:
B4CE93A8F5311A3FFE7700964CA0E513
SafeTool Function ID:
LCCM118R0.FILE.009.FUNC.007
References s16NUMERICAL_POINTS__Max(), and s16NUMERICAL_POINTS__Min().
void vNUMERICAL_POINTS__Bounds_U162D (struct tsNUM_u16Point_2D * ptArray, Luint16 u16NumPoints, Luint16 * pu16MinX, Luint16 * pu16MinY, Luint16 * pu16MaxX, Luint16 * pu16MaxY)
Get a bounding box for a set of points.
Parameters
[out] pu16MaxY Returned max Y
[out] pu16MaxX Returned max X
[out] pu16MinY Returned min Y
[out] pu16MinX Returned min X
[in] u16NumPoints Num points in array
[in] ptArray Array of points
SafeTool Function MD5:
FBA959392FD3AC7AC1D9BC1642134BC6
SafeTool Function ID:
LCCM118R0.FILE.009.FUNC.004
References u16NUMERICAL_POINTS__Max(), and u16NUMERICAL_POINTS__Min().