LFW513 (RLOOP - POWER NODE): I2C__WAIT
I2C__WAIT
RM4 » I2C
Functions
Luint8 u8RM4_I2C_WAIT__RxBufferFull (void)
Waits until some data is received into the Rx Buffer.
Luint8 u8RM4_I2C_WAIT__TxBufferEmpty (void)
Waits until the Tx buffer is empty.
Luint8 u8RM4_I2C_WAIT__TxBufferEmpty_Or_NACK (void)
Wait until the TX buffer is empty, or there is a NACK.
Luint8 u8RM4_I2C_WAIT__IsBusBusy (void)
Wait while the bus is busy, timeout if needed.
Variables
struct _strRM4I2C sRM4I2C
Detailed Description
Function Documentation
Luint8 u8RM4_I2C_WAIT__IsBusBusy (void)
Wait while the bus is busy, timeout if needed.
Returns
0 = Bus is NOT busy and a timeout did not occur
1 = A timeout occurred, bus busy unknown.
SafeTool Function MD5:
C1E46841342B0CB61F67781C9A2D224A
SafeTool Function ID:
LCCM215R0.FILE.050.FUNC.001
References I2C_NACK, i2cREG1, u8RM4_I2C__IsBusBusy(), u8RM4_I2C_TIMEOUT__Check(), vRM4_I2C__Set_Stop(), vRM4_I2C_TIMEOUT__Start(), and vRM4_I2C_TIMEOUT__Stop().
Referenced by s16RM4_I2C_USER__RxByte(), s16RM4_I2C_USER__RxReg(), s16RM4_I2C_USER__TxByte(), s16RM4_I2C_USER__TxByte16(), s16RM4_I2C_USER__TxByteArray(), and s16RM4_I2C_USER__TxReg().
Luint8 u8RM4_I2C_WAIT__RxBufferFull (void)
Waits until some data is received into the Rx Buffer.
Returns
0 = buffer is no longer full
-ve = error
SafeTool Function MD5:
2B675BF3F01BEA1B068DAADFBD6A368D
SafeTool Function ID:
LCCM215R0.FILE.050.FUNC.002
References u16RM4_I2C__IsRxBufferFull(), u8RM4_I2C_TIMEOUT__Check(), vRM4_I2C_TIMEOUT__Start(), and vRM4_I2C_TIMEOUT__Stop().
Referenced by s16RM4_I2C_USER__RxByte16(), s16RM4_I2C_USER__RxByteArray(), s16RM4_I2C_USER__RxByteArray16(), and s16RM4_I2C_USER__RxReg().
Luint8 u8RM4_I2C_WAIT__TxBufferEmpty (void)
Waits until the Tx buffer is empty.
Returns
0 = TX Buffer is empty and a timeout did not occur
1 = A timeout occurred
SafeTool Function MD5:
B335CFA59BB20335A5A96905CC5AEB20
SafeTool Function ID:
LCCM215R0.FILE.050.FUNC.003
References u16RM4_I2C__IsTxBufferEmpty(), u8RM4_I2C_TIMEOUT__Check(), vRM4_I2C_TIMEOUT__Start(), and vRM4_I2C_TIMEOUT__Stop().
Referenced by s16RM4_I2C_USER__RxByte(), s16RM4_I2C_USER__RxByte16(), s16RM4_I2C_USER__RxByteArray(), s16RM4_I2C_USER__RxByteArray16(), s16RM4_I2C_USER__TxByte(), s16RM4_I2C_USER__TxByte16(), s16RM4_I2C_USER__TxByteArray(), s16RM4_I2C_USER__TxByteArray_Constant(), and s16RM4_I2C_USER__TxReg().
Luint8 u8RM4_I2C_WAIT__TxBufferEmpty_Or_NACK (void)
Wait until the TX buffer is empty, or there is a NACK.
Returns
0 = Nuffer is Empty or NACK occurred
-ve = Error
SafeTool Function MD5:
319C76455DF322C4124B2DD8BA62DE11
SafeTool Function ID:
LCCM215R0.FILE.050.FUNC.004
References I2C_NACK, i2cREG1, u16RM4_I2C__IsTxBufferEmpty(), u8RM4_I2C_TIMEOUT__Check(), vRM4_I2C_TIMEOUT__Start(), and vRM4_I2C_TIMEOUT__Stop().
Referenced by s16RM4_I2C_USER__RxByte16().
Variable Documentation
struct _strRM4I2C sRM4I2C
Referenced by vRM4_I2C__Init(), vRM4_I2C__ReceiveArray(), vRM4_I2C__SendArray(), and vRM4_I2C__Set_TransactionLength().