LFW513 (RLOOP - POWER NODE): DS2482S__ONE_WIRE
DS2482S__ONE_WIRE
MULTICORE » DS2482S
Functions
static Lint16 s16DS2482S_1WIRE__Set_StrongPullup (Luint8 u8DeviceIndex)
Set the strong pullup to ON.
static Lint16 s16DS2482S_1WIRE__Clear_StrongPullup (Luint8 u8DeviceIndex)
Set the strong pullup to OFF.
Lint16 s16DS2482S_1WIRE__Generate_Reset (Luint8 u8DeviceIndex)
Generates a 1-Wire reset/presence-detect cycle (Figure 4) at the 1-Wire line.
Lint16 s16DS2482S_1WIRE__ReadByte (Luint8 u8DeviceIndex, Luint8 *pu8Byte, Luint8 u8PowerUp)
Read a byte on the 1-wire.
Lint16 s16DS2482S_1WIRE__WriteByte (Luint8 u8DeviceIndex, Luint8 u8Byte, Luint8 u8PowerUp)
Write a byte on the 1-wire device.
Lint16 s16DS2482S_1WIRE__WriteBit (Luint8 u8DeviceIndex, Luint8 u8Byte, Luint8 u8PowerUp)
Write a bit on the 1-wire device.
Lint16 s16DS2482S_1WIRE__ReadBit (Luint8 u8DeviceIndex, Luint8 *pu8Byte)
Read a bit from the bus.
Lint16 s16DS2482S_1WIRE__SelectDevice (Luint8 u8DeviceIndex, const Luint8 *pu8Addx)
Select a device on the 1-wire bus.
Lint16 s16DS2482S_1WIRE__Skip (Luint8 u8DeviceIndex)
Issue a skip command on the 1 wire.
Detailed Description
Function Documentation
Lint16 s16DS2482S_1WIRE__Clear_StrongPullup (Luint8 u8DeviceIndex) static
Set the strong pullup to OFF.
Parameters
[in] u8DeviceIndex Device index on the bus
Returns
0 = success
-ve = error
SafeTool Function MD5:
2C3B1BD13DB727B47151853D3B03D1A4
SafeTool Function ID:
LCCM641R0.FILE.004.FUNC.003
References s16DS2482S_DEVICE__Read_ConfigRegister(), and s16DS2482S_DEVICE__Set_ConfigRegister().
Referenced by s16DS2482S_1WIRE__Generate_Reset().
Lint16 s16DS2482S_1WIRE__Generate_Reset (Luint8 u8DeviceIndex)
Generates a 1-Wire reset/presence-detect cycle (Figure 4) at the 1-Wire line.
Note
1-Wire Reset Command Code B4h Command Parameter None Description Generates a 1-Wire reset/presence-detect cycle (Figure 4) at the 1-Wire line. The state of the 1-Wire line is sampled at tSI and tMSP and the result is reported to the host processor through the Status Register, bits PPD and SD. Typical Use To initiate or end any 1-Wire communication sequence. Restriction 1-Wire activity must have ended before the DS2482-100 can process this command. Strong pullup (see the SPU bit) should not be used in conjunction with the 1-Wire Reset command. If SPU is enabled, the PPD bit may not be valid and may cause a violation of the devices absolute maximum rating. Error Response Command code is not acknowledged if 1WB = 1 at the time the command code is received and the command is ignored. Command Duration tRSTL (600us) + tRSTH (580us) + maximum 262.5ns, counted from the falling SCL edge of the command code acknowledge bit. 1-Wire Activity Begins maximum 262.5ns after the falling SCL edge of the command code acknowledge bit. Read Pointer Position Status Register (for busy polling). Status Bits Affected 1WB (set to 1 for tRSTL + tRSTH), PPD is updated at tRSTL + tMSP, SD is updated at tRSTL + tSI. Config Bits Affected 1WS, APU, SPU apply. *
Parameters
[in] u8DeviceIndex The device index on the I2C
Returns
0 = Success
1 = pulse presense
-10 = Bus short
-ve = error
SafeTool Function MD5:
A91936A6D17B5C08BAE336623E8E8F94
SafeTool Function ID:
LCCM641R0.FILE.004.FUNC.001
Short Detected SD The SD bit is updated with every 1-Wire Reset command. If the DS2482-100 detects a logic 0 on the 1-Wire line at tSI during the presence-detect cycle, the SD bit is set to 1. This bit returns to its default 0 with a subsequent 1-Wire Reset command provided that the short has been removed. If SD is 1, PPD is 0. The DS2482-100 cannot distinguish between a short and a DS1994 or DS2404 signaling a 1-Wire interrupt. For this reason, if a DS2404 or DS1994 is used in the application, the interrupt function must be disabled. The interrupt signaling is explained in the respective 1-Wire device data sheets.
Presence-Pulse Detect PPD The PPD bit is updated with every 1-Wire Reset command. If the DS2482-100 detects a presence pulse from a 1-Wire device at tMSP during the presence-detect cycle, the PPD bit is set to 1. This bit returns to its default 0 if there is no presence pulse or if the 1-Wire line is shorted during a subsequent 1-Wire Reset command.
References DS2482_REGS__COMMAND_1_WIRE_RESET, s16DS2482S_1WIRE__Clear_StrongPullup(), s16DS2482S_DEVICE__Get_Status(), s16DS2482S_LOWLEVEL__TxReg(), and u8DS2482S_DEVICE__Wait_Busy().
Referenced by s16DS18B20_1WIRE__Generate_Reset(), and u8DS2482S_USER__1Wire_Reset().
Lint16 s16DS2482S_1WIRE__ReadBit (Luint8 u8DeviceIndex, Luint8 * pu8Byte)
Read a bit from the bus.
Parameters
[in] *pu8Byte Returned bit, 1 or 0
[in] u8DeviceIndex I2C Bus device index
Returns
0 = success
-ve = error
SafeTool Function MD5:
FD63571E1566B0028E8B2738B1CF44AC
SafeTool Function ID:
LCCM641R0.FILE.004.FUNC.006
References s16DS2482S_1WIRE__WriteBit(), and u8DS2482S_DEVICE__Wait_Busy().
Referenced by s16DS2482S_SEARCH__Search().
Lint16 s16DS2482S_1WIRE__ReadByte (Luint8 u8DeviceIndex, Luint8 * pu8Byte, Luint8 u8PowerUp)
Read a byte on the 1-wire.
Parameters
[in] u8PowerUp 1 = Enable high power
[in] *pu8Byte Pointer to the returned byte
[in] u8DeviceIndex I2C bus index
Returns
0 = success
-ve = error
SafeTool Function MD5:
E711932042EC46EE7C765C8CEAB06A7D
SafeTool Function ID:
LCCM641R0.FILE.004.FUNC.007
References DS2482_REGS__COMMAND_1_WIRE_READ_BYTE, s16DS2482S_1WIRE__Set_StrongPullup(), s16DS2482S_DEVICE__Read_Byte(), s16DS2482S_LOWLEVEL__TxReg(), and u8DS2482S_DEVICE__Wait_Busy().
Referenced by s16DS18B20_1WIRE__ReadByte().
Lint16 s16DS2482S_1WIRE__SelectDevice (Luint8 u8DeviceIndex, const Luint8 * pu8Addx)
Select a device on the 1-wire bus.
Uses the devices serial number to select it.
Parameters
[in] *pu8Addx Pointer to device serial number
[in] u8DeviceIndex Index on I2C
Returns
0 = success
-ve = error
SafeTool Function MD5:
74880CA462C65A17762CFBC9429F1E36
SafeTool Function ID:
LCCM641R0.FILE.004.FUNC.008
References s16DS2482S_1WIRE__WriteByte().
Referenced by s16DS18B20_1WIRE__SelectDevice().
Lint16 s16DS2482S_1WIRE__Set_StrongPullup (Luint8 u8DeviceIndex) static
Set the strong pullup to ON.
Parameters
[in] u8DeviceIndex Device index on the bus
Returns
0 = success
-ve = error
SafeTool Function MD5:
9FBF8AE61DB353678480886D681F9ADF
SafeTool Function ID:
LCCM641R0.FILE.004.FUNC.002
References s16DS2482S_DEVICE__Read_ConfigRegister(), and s16DS2482S_LOWLEVEL__TxReg().
Referenced by s16DS2482S_1WIRE__ReadByte(), s16DS2482S_1WIRE__WriteBit(), and s16DS2482S_1WIRE__WriteByte().
Lint16 s16DS2482S_1WIRE__Skip (Luint8 u8DeviceIndex)
Issue a skip command on the 1 wire.
Parameters
[in] u8DeviceIndex Index of device on I2C
Returns
0 = success
-ve = error
SafeTool Function MD5:
D998B0A5EA6FC05DFD3446449B800E90
SafeTool Function ID:
LCCM641R0.FILE.004.FUNC.009
References s16DS2482S_1WIRE__WriteByte().
Referenced by s16DS18B20_1WIRE__Skip().
Lint16 s16DS2482S_1WIRE__WriteBit (Luint8 u8DeviceIndex, Luint8 u8Byte, Luint8 u8PowerUp)
Write a bit on the 1-wire device.
Note
Generates a single 1-Wire time slot with a bit value as specified by the bit byte at the 1-Wire line A value of 0b generates a write-zero time slot; a value of 1b generates a write-one time slot, which also functions as a read-data time slot. In either case, the logic level at the 1-Wire line is tested at tMSR and SBR is updated.
Parameters
[in] u8PowerUp Put wire into max power mode
[in] u8Byte The bit 1 or 0 to write
[in] u8DeviceIndex I2C device index
Returns
0 = success
-ve = error
SafeTool Function MD5:
436E87F085FF0CE58C1AFFF5782F6D11
SafeTool Function ID:
LCCM641R0.FILE.004.FUNC.005
References DS2482_REGS__COMMAND_1_WIRE_SINGLE_BIT, s16DS2482S_1WIRE__Set_StrongPullup(), s16DS2482S_LOWLEVEL__WriteReg(), and u8DS2482S_DEVICE__Wait_Busy().
Referenced by s16DS2482S_1WIRE__ReadBit(), and s16DS2482S_SEARCH__Search().
Lint16 s16DS2482S_1WIRE__WriteByte (Luint8 u8DeviceIndex, Luint8 u8Byte, Luint8 u8PowerUp)
Write a byte on the 1-wire device.
Parameters
[in] u8PowerUp Put the wire into high power mode?
[in] u8Byte The byte of data to write
[in] u8DeviceIndex I2C device index
Returns
0 = success
-ve = error
SafeTool Function MD5:
F587F6697D8F6FA3C44646DF3D56ACBA
SafeTool Function ID:
LCCM641R0.FILE.004.FUNC.004
References DS2482_REGS__COMMAND_1_WIRE_WRITE_BYTE, s16DS2482S_1WIRE__Set_StrongPullup(), s16DS2482S_LOWLEVEL__WriteReg(), and u8DS2482S_DEVICE__Wait_Busy().
Referenced by s16DS18B20_1WIRE__WriteByte(), s16DS2482S_1WIRE__SelectDevice(), s16DS2482S_1WIRE__Skip(), and s16DS2482S_SEARCH__Search().