LFW513 (RLOOP - POWER NODE): N2HET__PROGRAM
N2HET__PROGRAM
RM4 » N2HET
Functions
void vN2HET_PROG_DYNAMIC__Clear (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32Key)
clear the program memory This should be called up at power up with the supplied unlock key to clear the ram and setup the basic program to keep the n2het happy.
void vN2HET_PROG__Update_RAM (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32Program, Luint32 u32Control, Luint32 u32Data)
Update the RAM with the current instruction This will write the current instruction to RAM The user is responsible for making sure the branch instruction is added after they have updated the RAM so at the N2HET will loop back.
void vN2HET_PROG__BR__Make (RM4_HET__INSTRUCTION_T *pReturn, Luint8 u8Request, Luint8 u8Break, Luint16 u16NextProgAddx, Luint16 u16ConditionalAddx)
Make a branch instruction The branch instruction is required at the end of each program so as the N2HET will branch back to instruction 0.
Variables
struct _strRM4_N2HET sN2HET
Detailed Description
Function Documentation
void vN2HET_PROG__BR__Make (RM4_HET__INSTRUCTION_T * pReturn, Luint8 u8Request, Luint8 u8Break, Luint16 u16NextProgAddx, Luint16 u16ConditionalAddx)
Make a branch instruction The branch instruction is required at the end of each program so as the N2HET will branch back to instruction 0.
Parameters
[in] u16ConditionalAddx Conditional Jump Address
[in] u16NextProgAddx Next program address
[in] u8Break Break Type
[in] u8Request Request type
[in] pReturn Pointer to the instruction to modify
SafeTool Function MD5:
4906D3E9CABFB84D0678C7BD525A9CA2
SafeTool Function ID:
LCCM240R0.FILE.022.FUNC.004
Referenced by u16N2HET_PROG_DYNAMIC__Add_Capture(), u16N2HET_PROG_DYNAMIC__Add_Edge(), u16N2HET_PROG_DYNAMIC__Add_Edge_Counter(), u16N2HET_PROG_DYNAMIC__Add_PWM(), u16N2HET_PROG_DYNAMIC__Add_PWM_Counter(), and vN2HET_PROG_DYNAMIC__Clear().
void vN2HET_PROG__Update_RAM (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32Program, Luint32 u32Control, Luint32 u32Data)
Update the RAM with the current instruction This will write the current instruction to RAM The user is responsible for making sure the branch instruction is added after they have updated the RAM so at the N2HET will loop back.
Parameters
[in] u32Data Instruction data value
[in] u32Control Instruction control value
[in] u32Program Instruction program value
[in] eChannel The current channel
SafeTool Function MD5:
10E23B594F1F1BDD88319B70026222C8
SafeTool Function ID:
LCCM240R0.FILE.022.FUNC.005
References hetRAM1, hetRAM2, N2HET_CHANNEL__1, _strRM4_N2HET::sDynamicProgram, sN2HET, and _strRM4_N2HET::u32InstructionCount.
Referenced by u16N2HET_PROG_DYNAMIC__Add_Edge(), u16N2HET_PROG_DYNAMIC__Add_Edge_Counter(), u16N2HET_PROG_DYNAMIC__Add_PWM(), and u16N2HET_PROG_DYNAMIC__Add_PWM_Counter().
void vN2HET_PROG_DYNAMIC__Clear (RM4_N2HET__CHANNEL_T eChannel, Luint32 u32Key)
clear the program memory This should be called up at power up with the supplied unlock key to clear the ram and setup the basic program to keep the n2het happy.
Parameters
[in] u32Key The unlock key
[in] eChannel The N2HET Channel to use
SafeTool Function MD5:
7212C2378AE248604103839611B1D046
SafeTool Function ID:
LCCM240R0.FILE.022.FUNC.003
References DYN_TYPE__TIMEBASE, hetRAM1, hetRAM2, N2HET_CHANNEL__1, _strRM4_N2HET::sDynamicProgram, sN2HET, _strRM4_N2HET::sProgram, _strRM4_N2HET::u32InstructionCount, _strRM4_N2HET::u32ProgramCount, and vN2HET_PROG__BR__Make().
Referenced by vRM4_N2HET__Init().
Variable Documentation
struct _strRM4_N2HET sN2HET
Referenced by vN2HET_PROG__Update_RAM(), and vN2HET_PROG_DYNAMIC__Clear().