LFW513 (RLOOP - POWER NODE): I2C__CORE
I2C__CORE
RM4 » I2C
Functions
Luint8 u8RM4_I2C__Check_Pin_Condition (void)
Check the condition of the pins, and if any pins are low, we need to clock out the problem.
void vRM4_I2C__Init (void)
init the module with pre values
Luint8 u8RM4_I2C__Get_NACK (void)
return the NACK status from the last transmission
void vRM4_I2C__Clear_NACK (void)
clear the NACK status bit
void vRM4_I2C__SetUpTransaction (Luint16 u16Length, Luint8 u8GenerateStopCondition, Luint8 u8IsTransmission, Luint8 u8SlaveAddress)
Setup to start a transaction.
void vRM4_I2C__Master_Ignore_NACK (void)
setup to ignore the NACK for slaves (like displays) that can't NACK
void vRM4_I2C__Set_Start (void)
Start condition Setting this bit will: 1 Generate the start condition 2 Transmit the slave address with the direction of the transaction.
Luint16 u16RM4_I2C__IsTxBufferEmpty (void)
Is Tx Ready.
Luint16 u16RM4_I2C__IsRxBufferFull (void)
Is the data ready (read in)
void vRM4_I2C__SendByte (Luint8 u8Byte)
sends one byte in polling mode User must make sure that DXR register is empty before calling this function Data written to this register will be transmitted on the I2C bus.
Luint8 u8RM4_I2C__ReceiveByte (void)
receives one byte in polling mode User must make sure that data is available before calling this function
void vRM4_I2C__SendArray (Luint32 u32Length, Luint8 *pu8Data)
sends an array of data either with interrupts or polling this is defined at compile time
void vRM4_I2C__ReceiveArray (Luint32 u32Length, Luint8 *pu8Data)
receives an array of data either with interrupts or polling this is defined at compile time
Luint8 u8RM4_I2C__IsBusBusy (void)
Checks to see if the bus is busy.
void vRM4_I2C__TransmiterEnable (void)
Enable transmitter bit.
void vRM4_I2C__ReceiverEnable (void)
Enable Receiver mode.
void vRM4_I2C__Set_OwnAdd (Luint16 u16OwnAdd)
Sets the device own address.
void vRM4_I2C__Set_SlaveAdd (Luint16 u16SlaveAdd)
Sets the address of the slave device to communicate to on the I2C bus The I2C slave address register is a 16-bit memory-mapped register used to specify the address of the slave device to communicate to on the I2C bus.
void vRM4_I2C__Set_Stop (void)
Stop condition Setting this bit will generate a stop condition when the transaction is finished(data counter equals zero)
void vRM4_I2C__Clear_Stop (void)
clearing this bit will prevent the generation of a stop condition when the transaction ends (data counter equals zero)
void vRM4_I2C__Set_MasterMode (Luint8 u8MasterEnable)
Sets the device as master or slave.
void vRM4_I2C__Set_TransactionLength (Luint16 u16Size)
Set the length in bytes to transmit.
Variables
struct _strRM4I2C sRM4I2C
Detailed Description
Function Documentation
Luint16 u16RM4_I2C__IsRxBufferFull (void)
Is the data ready (read in)
C_RM4I2C__IMR_REG__BIT__RXRDYRN = This bit is set to 1 to indicate when the data in the receive shift register has been copied into the data receive register [I2CDRR] 0 The I2CDRR has been read. 1 The received data has been written into the I2CDRR.
Returns
1 = Rx Buffer is full
0 = Rx Buffer Not Full
SafeTool Function MD5:
DF33732B7DDF5BCBBEFBD83A7484E73C
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.010
References C_RM4I2C__STR_REG__BIT__RXRDY, and i2cREG1.
Referenced by u8RM4_I2C_WAIT__RxBufferFull().
Luint16 u16RM4_I2C__IsTxBufferEmpty (void)
Is Tx Ready.
C_RM4I2C__IMR_REG__BIT__TXRDYEN : This bit is set to 1 to indicate when data in the transmit data register, I2CDXR, has been copied into the transmit shift register. This bit can also be polled by the device to indicate when to write the next transmitted data into the I2CDXR. Writing a 1 to this bit will set it.
#return 0 = I2CDXR contains data to transmit
1 = I2CDXR is empty.
SafeTool Function MD5:
7A2DF3BDC6EF21843D58E76228C16FFA
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.008
References C_RM4I2C__STR_REG__BIT__TXRDY, and i2cREG1.
Referenced by u8RM4_I2C_WAIT__TxBufferEmpty(), and u8RM4_I2C_WAIT__TxBufferEmpty_Or_NACK().
Luint8 u8RM4_I2C__Check_Pin_Condition (void)
Check the condition of the pins, and if any pins are low, we need to clock out the problem.
Returns
0 = one or more pins stuck low 1 = all good, both high
SafeTool Function MD5:
121F88B14B33B248A43B16386E575B47
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.032
References u8RM4_I2C_PINS__Get_SCL(), and u8RM4_I2C_PINS__Get_SDA().
Referenced by vRM4_I2C__Init().
Luint8 u8RM4_I2C__Get_NACK (void)
return the NACK status from the last transmission
Returns
1 = NACK occurred
0 = NACK did not occur
SafeTool Function MD5:
33E77AD7F1ECE943E3D29029B37B18A9
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.029
References C_RM4I2C__STR_REG__BIT__NACK, and i2cREG1.
Referenced by s16RM4_I2C_USER__TxByte(), and s16RM4_I2C_USER__TxByte16().
Luint8 u8RM4_I2C__IsBusBusy (void)
Checks to see if the bus is busy.
SafeTool Function MD5:
FF818117A2447BA8B621BE53FD74E23B
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.002
References C_RM4I2C__STR_REG__BIT__BB, and i2cREG1.
Referenced by s16RM4_I2C_USER__RxByte16(), s16RM4_I2C_USER__RxByteArray(), s16RM4_I2C_USER__RxByteArray16(), s16RM4_I2C_USER__TxByteArray_Constant(), and u8RM4_I2C_WAIT__IsBusBusy().
Luint8 u8RM4_I2C__ReceiveByte (void)
receives one byte in polling mode User must make sure that data is available before calling this function
Returns
The read data
SafeTool Function MD5:
ED696908845459BC7E30406F810FFB00
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.012
References i2cREG1.
Referenced by s16RM4_I2C_USER__RxByte(), s16RM4_I2C_USER__RxByte16(), s16RM4_I2C_USER__RxByteArray(), s16RM4_I2C_USER__RxByteArray16(), and s16RM4_I2C_USER__RxReg().
void vRM4_I2C__Clear_NACK (void)
clear the NACK status bit
SafeTool Function MD5:
60B19BFB19A1220AADE0427E8C61483B
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.030
References C_RM4I2C__STR_REG__BIT__NACK, and i2cREG1.
void vRM4_I2C__Clear_Stop (void)
clearing this bit will prevent the generation of a stop condition when the transaction ends (data counter equals zero)
SafeTool Function MD5:
FB98D636466D8AAE1749B23A4E491372
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.026
References C_LOCALDEF__LCCM215__I2CMDR_STP_SHIFT, and i2cREG1.
Referenced by vRM4_I2C__SetUpTransaction().
void vRM4_I2C__Init (void)
init the module with pre values
SafeTool Function MD5:
2DE10DB96643E204BD9699DBEA7FD0C4
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.001
References C_LOCALDEF__LCCM215__I2CDOUT_SCLOUT, C_LOCALDEF__LCCM215__I2CDOUT_SCLOUT_SHIFT, C_LOCALDEF__LCCM215__I2CDOUT_SDAOUT, C_LOCALDEF__LCCM215__I2CDOUT_SDAOUT_SHIFT, C_LOCALDEF__LCCM215__I2CMDR_BC_IN_FDF_8_WITH_ACK_9, C_LOCALDEF__LCCM215__I2CMDR_BC_SHIFT, C_LOCALDEF__LCCM215__I2CMDR_DLB, C_LOCALDEF__LCCM215__I2CMDR_DLB_SHIFT, C_LOCALDEF__LCCM215__I2CMDR_FDF_NOT_FREE, C_LOCALDEF__LCCM215__I2CMDR_FDF_SHIFT, C_LOCALDEF__LCCM215__I2CMDR_FREE_SHIFT, C_LOCALDEF__LCCM215__I2CMDR_MST_SHIFT, C_LOCALDEF__LCCM215__I2CMDR_nIRS_OUT_OF_RESET, C_LOCALDEF__LCCM215__I2CMDR_nIRS_RESET, C_LOCALDEF__LCCM215__I2CMDR_nIRS_SHIFT, C_LOCALDEF__LCCM215__I2CMDR_RM, C_LOCALDEF__LCCM215__I2CMDR_RM_SHIFT, C_LOCALDEF__LCCM215__I2CMDR_STB, C_LOCALDEF__LCCM215__I2CMDR_STB_SHIFT, C_LOCALDEF__LCCM215__I2CMDR_STP, C_LOCALDEF__LCCM215__I2CMDR_STP_SHIFT, C_LOCALDEF__LCCM215__I2CMDR_STT, C_LOCALDEF__LCCM215__I2CMDR_TRX, C_LOCALDEF__LCCM215__I2CMDR_TRX_SHIFT, C_LOCALDEF__LCCM215__I2CMDR_XA, C_LOCALDEF__LCCM215__I2CMDR_XA_SHIFT, C_LOCALDEF__LCCM215__I2CPFNC_PINFUNCT, C_LOCALDEF__LCCM215__I2CPFNC_PINFUNCT_SHIFT, C_LOCALDEF__LCCM215__PDIR_SCLDIR, C_LOCALDEF__LCCM215__PDIR_SCLDIR_SHIFT, C_LOCALDEF__LCCM215__PDIR_SDADIR, C_LOCALDEF__LCCM215__PDIR_SDADIR_SHIFT, C_LOCALDEF__LCCM215__PDIS_SCLPDIS_PULL_DISABLE, C_LOCALDEF__LCCM215__PDIS_SCLPDIS_SHIFT, C_LOCALDEF__LCCM215__PDIS_SDAPDIS_PULL_DISABLE, C_LOCALDEF__LCCM215__PDIS_SDAPDIS_SHIFT, C_LOCALDEF__LCCM215__PDR_SCLPDR, C_LOCALDEF__LCCM215__PDR_SCLPDR_SHIFT, C_LOCALDEF__LCCM215__PDR_SDAPDR, C_LOCALDEF__LCCM215__PDR_SDAPDR_SHIFT, C_LOCALDEF__LCCM215__PSEL_SCLPSEL, C_LOCALDEF__LCCM215__PSEL_SCLPSEL_SHIFT, C_LOCALDEF__LCCM215__PSEL_SDAPSEL, C_LOCALDEF__LCCM215__PSEL_SDAPSEL_SHIFT, C_RM4I2C__IMR_REG__BIT__AASEN, C_RM4I2C__IMR_REG__BIT__ALEN, C_RM4I2C__IMR_REG__BIT__ARDYEN, C_RM4I2C__IMR_REG__BIT__NACKEN, C_RM4I2C__IMR_REG__BIT__RXRDYRN, C_RM4I2C__IMR_REG__BIT__SCDEN, C_RM4I2C__IMR_REG__BIT__TXRDYEN, C_RM4I2C__MDR_REG__BIT__FREE_STOP, C_RM4I2C__MDR_REG__NACKMOD_BIT__ACK, C_RM4I2C__MDR_REG__NACKMOD_BIT__SHIFT, C_RM4I2C__MDR_REG__STT_BIT_SHIFT, i2cREG1, sRM4I2C, _strRM4I2C::sStats, _strRM4I2C::u32General_Timeout, _strRM4I2C::u32Length, u8RM4_I2C__Check_Pin_Condition(), u8RM4_I2C_PINS__Get_SDA(), vRM4_DELAYS__Delay_uS(), vRM4_I2C__Set_OwnAdd(), vRM4_I2C__Set_Stop(), vRM4_I2C_PINS__Set_Functional(), vRM4_I2C_PINS__Set_SCL_Latch(), vRM4_I2C_PINS__Set_SCL_Tris(), vRM4_I2C_PINS__Set_SDA_Latch(), and vRM4_I2C_PINS__Set_SDA_Tris().
Referenced by vRM4_I2C_USER__Init().
void vRM4_I2C__Master_Ignore_NACK (void)
setup to ignore the NACK for slaves (like displays) that can't NACK
SafeTool Function MD5:
2DF22501143A89799FF1F3BF6A218F89
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.031
References i2cREG1.
void vRM4_I2C__ReceiveArray (Luint32 u32Length, Luint8 * pu8Data)
receives an array of data either with interrupts or polling this is defined at compile time
Parameters
[out] pu8Data Pointer to the returned data
[in] u32Length Total receive length
SafeTool Function MD5:
EFEB718ED040E4A8F441954C98E93134
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.014
References C_RM4I2C__IMR_REG__BIT__ALEN, C_RM4I2C__IMR_REG__BIT__NACKEN, C_RM4I2C__STR_REG__BIT__RXRDY, i2cREG1, _strRM4I2C::pu8Data, sRM4I2C, and _strRM4I2C::u32Length.
void vRM4_I2C__ReceiverEnable (void)
Enable Receiver mode.
SafeTool Function MD5:
EA18FB0BCE38E178C5BC8EACF012BC53
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.028
References i2cREG1.
Referenced by vRM4_I2C__SetUpTransaction().
void vRM4_I2C__SendArray (Luint32 u32Length, Luint8 * pu8Data)
sends an array of data either with interrupts or polling this is defined at compile time
Parameters
[in] pu8Data Pointer to data for transmit
[in] u32Length Length of transmitted data
SafeTool Function MD5:
3931C9C974E920B1A0794C8497ECCFFA
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.013
References C_RM4I2C__IMR_REG__BIT__TXRDYEN, C_RM4I2C__STR_REG__BIT__TXRDY, i2cREG1, _strRM4I2C::pu8Data, sRM4I2C, and _strRM4I2C::u32Length.
void vRM4_I2C__SendByte (Luint8 u8Byte)
sends one byte in polling mode User must make sure that DXR register is empty before calling this function Data written to this register will be transmitted on the I2C bus.
A write to this register clears the TXRDY bit and clears code 0x05 from the I2CIVR register.
Parameters
[in] u8Byte The byte value to send.
SafeTool Function MD5:
1D32CF8B7E063704C8B3FCEB637C2C0C
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.011
References i2cREG1.
Referenced by s16RM4_I2C_USER__RxByte(), s16RM4_I2C_USER__RxByte16(), s16RM4_I2C_USER__RxByteArray(), s16RM4_I2C_USER__RxByteArray16(), s16RM4_I2C_USER__TxByte(), s16RM4_I2C_USER__TxByte16(), s16RM4_I2C_USER__TxByteArray(), s16RM4_I2C_USER__TxByteArray_Constant(), and s16RM4_I2C_USER__TxReg().
void vRM4_I2C__Set_MasterMode (Luint8 u8MasterEnable)
Sets the device as master or slave.
Parameters
[in] u8MasterEnable Enable Master Mode
1 = Enable Master Mode
0 = Enable Slave mode
SafeTool Function MD5:
5C5664D74E3281026DFE167ACBD08548
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.015
References C_LOCALDEF__LCCM215__I2CMDR_MST_SHIFT, and i2cREG1.
Referenced by vRM4_I2C__SetUpTransaction().
void vRM4_I2C__Set_OwnAdd (Luint16 u16OwnAdd)
Sets the device own address.
Parameters
[in] u16OwnAdd Our own address
SafeTool Function MD5:
F7DE973FFF358229719C379B47C630E5
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.003
References i2cREG1.
Referenced by vRM4_I2C__Init().
void vRM4_I2C__Set_SlaveAdd (Luint16 u16SlaveAdd)
Sets the address of the slave device to communicate to on the I2C bus The I2C slave address register is a 16-bit memory-mapped register used to specify the address of the slave device to communicate to on the I2C bus.
Figure 27-20 and Table 27-12 describe this register.
Parameters
[in] u16SlaveAdd The target slave address
SafeTool Function MD5:
E9D4D4EC6D00F33B4852A6F726C13F66
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.004
References i2cREG1.
Referenced by vRM4_I2C__SetUpTransaction().
void vRM4_I2C__Set_Start (void)
Start condition Setting this bit will: 1 Generate the start condition 2 Transmit the slave address with the direction of the transaction.
SafeTool Function MD5:
1B489DF954337EEC0C91B7F997EF7E39
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.006
References C_RM4I2C__MDR_REG__STT_BIT_SHIFT, and i2cREG1.
Referenced by s16RM4_I2C_USER__RxByte(), s16RM4_I2C_USER__RxByte16(), s16RM4_I2C_USER__RxByteArray(), s16RM4_I2C_USER__RxByteArray16(), s16RM4_I2C_USER__RxReg(), s16RM4_I2C_USER__TxByte(), s16RM4_I2C_USER__TxByte16(), s16RM4_I2C_USER__TxByteArray(), s16RM4_I2C_USER__TxByteArray_Constant(), and s16RM4_I2C_USER__TxReg().
void vRM4_I2C__Set_Stop (void)
Stop condition Setting this bit will generate a stop condition when the transaction is finished(data counter equals zero)
SafeTool Function MD5:
92F0EC9CEB4FDE957F46D107995D91ED
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.007
References C_LOCALDEF__LCCM215__I2CMDR_STP_SHIFT, and i2cREG1.
Referenced by s16RM4_I2C_USER__RxByte16(), u8RM4_I2C_WAIT__IsBusBusy(), vRM4_I2C__Init(), and vRM4_I2C__SetUpTransaction().
void vRM4_I2C__Set_TransactionLength (Luint16 u16Size)
Set the length in bytes to transmit.
Note
The I2C data count register is a 16-bit memory mapped register used to count received or transmitted data bytes. This register is also used to generate the STOP condition which terminates the transfer after the counter reaches zero. Figure 27-18 and Table 27-10 describe this register.
Parameters
[in] u16Size The size in byte to transmit
SafeTool Function MD5:
7CCE88629C91B6AA73DE5FCA5DB001CC
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.027
References i2cREG1, _strRM4I2C::pu8Data, sRM4I2C, and _strRM4I2C::u32Length.
Referenced by vRM4_I2C__SetUpTransaction().
void vRM4_I2C__SetUpTransaction (Luint16 u16Length, Luint8 u8GenerateStopCondition, Luint8 u8IsTransmission, Luint8 u8SlaveAddress)
Setup to start a transaction.
Parameters
[in] u8SlaveAddress The slave address to send data to
[in] u8IsTransmission Transmit = 1, or Receive = 0
[in] u8GenerateStopCondition Generate a stop condition, or not
[in] u16Length The total length of the transmision in bytes
SafeTool Function MD5:
87E8E9F84013CDFFEFA0FACDD7D8E360
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.024
References vRM4_I2C__Clear_Stop(), vRM4_I2C__ReceiverEnable(), vRM4_I2C__Set_MasterMode(), vRM4_I2C__Set_SlaveAdd(), vRM4_I2C__Set_Stop(), vRM4_I2C__Set_TransactionLength(), and vRM4_I2C__TransmiterEnable().
Referenced by s16RM4_I2C_USER__RxByte(), s16RM4_I2C_USER__RxByte16(), s16RM4_I2C_USER__RxByteArray(), s16RM4_I2C_USER__RxByteArray16(), s16RM4_I2C_USER__RxReg(), s16RM4_I2C_USER__TxByte(), s16RM4_I2C_USER__TxByte16(), s16RM4_I2C_USER__TxByteArray(), s16RM4_I2C_USER__TxByteArray_Constant(), and s16RM4_I2C_USER__TxReg().
void vRM4_I2C__TransmiterEnable (void)
Enable transmitter bit.
SafeTool Function MD5:
18FBC7E3348B93AC2D4E5545F848DA6B
SafeTool Function ID:
LCCM215R0.FILE.001.FUNC.025
References i2cREG1.
Referenced by vRM4_I2C__SetUpTransaction().
Variable Documentation
struct _strRM4I2C sRM4I2C
Referenced by s16RM4_I2C_USER__RxByte(), s16RM4_I2C_USER__RxByte16(), s16RM4_I2C_USER__RxByteArray(), s16RM4_I2C_USER__RxByteArray16(), s16RM4_I2C_USER__RxReg(), s16RM4_I2C_USER__TxByte(), s16RM4_I2C_USER__TxByte16(), s16RM4_I2C_USER__TxByteArray(), s16RM4_I2C_USER__TxByteArray_Constant(), s16RM4_I2C_USER__TxReg(), u32RM4_I2C_USER__Get_FaultFlags(), u8RM4_I2C_TIMEOUT__Check(), vRM4_I2C__Init(), vRM4_I2C__ReceiveArray(), vRM4_I2C__SendArray(), vRM4_I2C__Set_TransactionLength(), vRM4_I2C_TIMEOUT__Start(), and vRM4_I2C_USER__Init().