LFW513 (RLOOP - POWER NODE): SCI__CORE
SCI__CORE
RM4 » SCI
Functions
void vRM4_SCI_HELPERS__DisplayText (RM4_SCI__CHANNEL_T eChannel, const Luint8 *pcu8Text, Luint32 u32Length)
Display a string.
void vRM4_SCI_LOOPBACK__Enable (RM4_SCI__CHANNEL_T eChannel, RM4_SCI__LOOPBACK_T eLoopback)
Enable the loopback mode.
void vRM4_SCI_LOOPBACK__Disable (RM4_SCI__CHANNEL_T eChannel)
Disable Loopbacking.
void vRM4_SCI__Init (RM4_SCI__CHANNEL_T eChannel)
Init the SCI channel.
void vRM4_SCI__Set_PortFunctional (RM4_SCI__CHANNEL_T eChannel, Luint32 u32Port)
Change functional behavoiur of pins at runtime.
void vRM4_SCI__Set_Baudrate (RM4_SCI__CHANNEL_T eChannel, Luint32 u32Baud)
Change baudrate at runtime.
Luint32 u32RM4_SCI__Is_TxReady (RM4_SCI__CHANNEL_T eChannel)
Check if Tx buffer empty Checks to see if the Tx buffer ready flag is set, returns 0 is flags not set otherwise will return the Tx flag itself.
void vRM4_SCI__TxByteArrayByte (RM4_SCI__CHANNEL_T eChannel, Luint8 u8Byte)
Send Byte Sends a single byte in polling u32Mode, will wait in the routine until the transmit buffer is empty before sending the byte.
void vRM4_SCI__TxByteArray (RM4_SCI__CHANNEL_T eChannel, Luint32 u32Length, Luint8 *pu8Data)
Send Array Send a block of data pointed to by 'data' and 'length' bytes long.
Luint32 u32RM4_SCI__Is__RxReady (RM4_SCI__CHANNEL_T eChannel)
Check if Rx buffer full Checks to see if the Rx buffer full flag is set, returns 0 is flags not set otherwise will return the Rx flag itself.
Luint32 u32RM4_SCI__Get__RxErrorFlags (RM4_SCI__CHANNEL_T eChannel)
Return Rx Error flags Returns the Rx framing, overun and parity errors flags, also clears the error flags before returning.
Luint8 u8RM4_SCI__Get_Rx_Value (RM4_SCI__CHANNEL_T eChannel)
ToDo.
Luint8 u8RM4_SCI__RxByte (RM4_SCI__CHANNEL_T eChannel)
Receive Byte Recieves a single byte in polling u32Mode.
void u8RM4_SCI__RxByteArray (RM4_SCI__CHANNEL_T eChannel, Luint32 u32Length, Luint8 *pu8Data)
Rx a byte array Receive a block of 'length' bytes long and place it into the data buffer pointed to by 'data'.
Variables
RM4_SCI__TX_T g_sciTransfer_t [2]
Detailed Description
Function Documentation
Luint32 u32RM4_SCI__Get__RxErrorFlags (RM4_SCI__CHANNEL_T eChannel)
Return Rx Error flags Returns the Rx framing, overun and parity errors flags, also clears the error flags before returning.
Parameters
[in] eChannel The SCI Channel
Returns
The Rx error flags
SafeTool Function MD5:
16B87E63A0EF6D18A52FAD00CE3A0782
SafeTool Function ID:
LCCM282R0.FILE.001.FUNC.008
References SCI_FE_INT, SCI_OE_INT, SCI_PE_INT, scilinREG, and sciREG.
Luint32 u32RM4_SCI__Is__RxReady (RM4_SCI__CHANNEL_T eChannel)
Check if Rx buffer full Checks to see if the Rx buffer full flag is set, returns 0 is flags not set otherwise will return the Rx flag itself.
Parameters
[in] eChannel The SCI Channel
Returns
The Rx ready flag
SafeTool Function MD5:
CFE9E2883BE46B14A4102F0EDD25ECFA
SafeTool Function ID:
LCCM282R0.FILE.001.FUNC.007
References SCI_RX_INT, scilinREG, and sciREG.
Luint32 u32RM4_SCI__Is_TxReady (RM4_SCI__CHANNEL_T eChannel)
Check if Tx buffer empty Checks to see if the Tx buffer ready flag is set, returns 0 is flags not set otherwise will return the Tx flag itself.
Parameters
[in] eChannel The SCI Channel
Returns
The TX ready flag
SafeTool Function MD5:
D99C25F100761A8A57F92932A0D9201D
SafeTool Function ID:
LCCM282R0.FILE.001.FUNC.004
References SCI_TX_INT, scilinREG, and sciREG.
Luint8 u8RM4_SCI__Get_Rx_Value (RM4_SCI__CHANNEL_T eChannel)
ToDo.
Parameters
[in] eChannel ## Desc ##
SafeTool Function MD5:
D65EB4EABADFEEFDF4DB0D4500869D3D
SafeTool Function ID:
LCCM282R0.FILE.001.FUNC.011
References scilinREG, and sciREG.
Luint8 u8RM4_SCI__RxByte (RM4_SCI__CHANNEL_T eChannel)
Receive Byte Recieves a single byte in polling u32Mode.
If there is not a byte in the receive buffer the routine will wait until one is received. Use u32RM4_SCI__Is__RxReady to check to see if the buffer is full to avoid waiting.
Parameters
[in] eChannel The SCI Channel
Returns
Received byte
SafeTool Function MD5:
79B17F36B45BDF265C01EFDE0B484B5C
SafeTool Function ID:
LCCM282R0.FILE.001.FUNC.009
References SCI_RX_INT, scilinREG, and sciREG.
void u8RM4_SCI__RxByteArray (RM4_SCI__CHANNEL_T eChannel, Luint32 u32Length, Luint8 * pu8Data)
Rx a byte array Receive a block of 'length' bytes long and place it into the data buffer pointed to by 'data'.
If interrupts have been enabled the data is received using interrupt u32Mode, otherwise polling u32Mode is used. In interrupt u32Mode receive is setup and the routine returns imediatly, u8RM4_SCI__RxByteArray must not be called again until the transfer is complete, when the vRM4_SCI_INT__Notification callback will be called. In polling u32Mode, u8RM4_SCI__RxByteArray will not return until the transfer is complete.
Parameters
[out] pu8Data Pointer to rx buffer
[in] u32Length Length required
[in] eChannel The SCI Channel
SafeTool Function MD5:
EC03E5BDB3874B64B074064FDD547701
SafeTool Function ID:
LCCM282R0.FILE.001.FUNC.010
References RM4_SCI__TX_T::pu8RxData, SCI_FE_INT, SCI_OE_INT, SCI_PE_INT, SCI_RX_INT, scilinREG, sciREG, and RM4_SCI__TX_T::u32RxLength.
void vRM4_SCI__Init (RM4_SCI__CHANNEL_T eChannel)
Init the SCI channel.
Parameters
[in] eChannel The SCI Channel
SafeTool Function MD5:
8F9212E8BB8EED5A5092546BB025C112
SafeTool Function ID:
LCCM282R0.FILE.001.FUNC.001
References scilinREG, and sciREG.
Referenced by vPWRNODE__Process().
void vRM4_SCI__Set_Baudrate (RM4_SCI__CHANNEL_T eChannel, Luint32 u32Baud)
Change baudrate at runtime.
Parameters
[in] u32Baud Baudrate in HZ
[in] eChannel The SCI Channel
SafeTool Function MD5:
8921070CE9EA4AC171E9436BBE6B1EB0
SafeTool Function ID:
LCCM282R0.FILE.001.FUNC.003
References scilinREG, and sciREG.
Referenced by vPWRNODE__Process().
void vRM4_SCI__Set_PortFunctional (RM4_SCI__CHANNEL_T eChannel, Luint32 u32Port)
Change functional behavoiur of pins at runtime.
Change the value of the PCFUN register at runtime, this allows to dynaimcaly change the functionality of the SCI pins between functional and GIO mode.
Parameters
[in] u32Port The port bit
[in] eChannel The SCI Channel
SafeTool Function MD5:
4090BC68B133F00896875E46A2966279
SafeTool Function ID:
LCCM282R0.FILE.001.FUNC.002
References scilinREG, and sciREG.
void vRM4_SCI__TxByteArray (RM4_SCI__CHANNEL_T eChannel, Luint32 u32Length, Luint8 * pu8Data)
Send Array Send a block of data pointed to by 'data' and 'length' bytes long.
If interrupts have been enabled the data is sent using interrupt mode, otherwise polling mode is used. In interrupt mode transmition of the first byte is started and the routine returns imediatly, vRM4_SCI__TxByteArray must not be called again until the transfer is complete, when the vRM4_SCI_INT__Notification callback will be called. In polling mode, vRM4_SCI__TxByteArray will not return until the transfer is complete.
Note
if data word is less than 8 bits, then the data must be left aligned in the data byte.
Parameters
[in] pu8Data Pointer to byte array
[in] u32Length Length of data to send
[in] eChannel The SCI Channel
SafeTool Function MD5:
615C2CF84E829132C3B712FC8B7369E9
SafeTool Function ID:
LCCM282R0.FILE.001.FUNC.006
References RM4_SCI__TX_T::pu8TxData, SCI_TX_INT, scilinREG, sciREG, and RM4_SCI__TX_T::u32TxLength.
void vRM4_SCI__TxByteArrayByte (RM4_SCI__CHANNEL_T eChannel, Luint8 u8Byte)
Send Byte Sends a single byte in polling u32Mode, will wait in the routine until the transmit buffer is empty before sending the byte.
Use u32RM4_SCI__Is_TxReady to check for Tx buffer empty before calling vRM4_SCI__TxByteArrayByte to avoid waiting.
Parameters
[in] u8Byte The byte of data to send
[in] eChannel The SCI Channel
SafeTool Function MD5:
8729549E82D8573D1469542A0A7CDD78
SafeTool Function ID:
LCCM282R0.FILE.001.FUNC.005
References SCI_TX_INT, scilinREG, and sciREG.
Referenced by vRM4_SCI_HELPERS__DisplayText().
void vRM4_SCI_HELPERS__DisplayText (RM4_SCI__CHANNEL_T eChannel, const Luint8 * pcu8Text, Luint32 u32Length)
Display a string.
Parameters
[in] u32Length The max length of the string
[in] pcu8Text Pointer to the string to display
[in] eChannel The SCI Channel
SafeTool Function MD5:
60B30E624D116D21CABB8DC1154FCC8D
SafeTool Function ID:
LCCM282R0.FILE.007.FUNC.001
References vRM4_SCI__TxByteArrayByte().
void vRM4_SCI_LOOPBACK__Disable (RM4_SCI__CHANNEL_T eChannel)
Disable Loopbacking.
Parameters
[in] eChannel The SCI Channel
SafeTool Function MD5:
F327C73067126F8EECAA762F90C1B15A
SafeTool Function ID:
LCCM282R0.FILE.005.FUNC.002
References scilinREG, and sciREG.
void vRM4_SCI_LOOPBACK__Enable (RM4_SCI__CHANNEL_T eChannel, RM4_SCI__LOOPBACK_T eLoopback)
Enable the loopback mode.
Parameters
[in] eLoopback Digital or analog loopback
[in] eChannel The SCI Channel
SafeTool Function MD5:
45679CC2028AD138291F19A49364FD24
SafeTool Function ID:
LCCM282R0.FILE.005.FUNC.001
References scilinREG, and sciREG.
Variable Documentation
RM4_SCI__TX_T g_sciTransfer_t[2]