LFW513 (RLOOP - POWER NODE): EMAC__LINK
EMAC__LINK
RM4 » EMAC
Functions
void vRM4_EMAC_LINK__Init (Luint8 *pu8MAC, Luint8 *pu8IP)
Init the link state machine Call this at power up to get the EMAC working.
void vRM4_EMAC_LINK__Set_State (RM4_EMAC__LINK_STATE_T eState)
Set the Link state to a new value.
void vRM4_EMAC_LINK__Process (void)
process the state machine Called each program loop to progressively bring up the link.
Luint8 u8RM4_EMAC_LINK__Is_LinkUp (void)
Is the link up Returns true if the EMAC link is established.
Lint16 s16RM4_EMAC_LINK__Link_Setup (void)
Setup the link Attempts to set up the link via auto-negotiation.
Lint16 s16RM4_EMAC_LINK__Link_Setup_AsyncStart (void)
ToDo.
Lint16 s16RM4_EMAC_LINK__Link_Setup_AsyncCheck (void)
ToDo.
Variables
struct RM4_EMAC_IF m_pEMAC_IF
Detailed Description
Function Documentation
Lint16 s16RM4_EMAC_LINK__Link_Setup (void)
Setup the link Attempts to set up the link via auto-negotiation.
Returns
0 = success
-ve = error
SafeTool Function MD5:
F7E0204FCDFA817F9162A12FAA7A613E
SafeTool Function ID:
LCCM254R0.FILE.014.FUNC.004
References C_DP83640__PHY_INDEX, EMAC_DUPLEX_FULL, EMAC_DUPLEX_HALF, and vRM4_EMAC__Set_Duplex().
Lint16 s16RM4_EMAC_LINK__Link_Setup_AsyncCheck (void)
ToDo.
SafeTool Function MD5:
158221585BF60E05760521AE0804B013
SafeTool Function ID:
LCCM254R0.FILE.014.FUNC.007
References C_DP83640__PHY_INDEX, EMAC_DUPLEX_FULL, EMAC_DUPLEX_HALF, and vRM4_EMAC__Set_Duplex().
Referenced by vRM4_EMAC_LINK__Process().
Lint16 s16RM4_EMAC_LINK__Link_Setup_AsyncStart (void)
ToDo.
SafeTool Function MD5:
8C509E5A2CFE1B95E3A9A93980FFEC24
SafeTool Function ID:
LCCM254R0.FILE.014.FUNC.006
References C_DP83640__PHY_INDEX.
Referenced by vRM4_EMAC_LINK__Process().
Luint8 u8RM4_EMAC_LINK__Is_LinkUp (void)
Is the link up Returns true if the EMAC link is established.
Returns
0 = link down
1 = link up
SafeTool Function MD5:
A5EF9C0FC3175F17D6016D1B08F7D92D
SafeTool Function ID:
LCCM254R0.FILE.014.FUNC.003
References RM4_EMAC_IF::eLinkState, LINK_STATE__RUN, and m_pEMAC_IF.
void vRM4_EMAC_LINK__Init (Luint8 * pu8MAC, Luint8 * pu8IP)
Init the link state machine Call this at power up to get the EMAC working.
The EMAC controls the flow of packet data from the system to the PHY.
Example:
u8MACAddx[0] = 0x00; u8MACAddx[1] = 0x26; u8MACAddx[2] = 0x80; u8MACAddx[3] = 0x00; u8MACAddx[4] = 0x00; u8MACAddx[5] = 0x01;
u8IPAddx[0] = 192; u8IPAddx[1] = 168; u8IPAddx[2] = 1; u8IPAddx[3] = 200;
SafeTool Function MD5:
58AF718D01B1040C1966D8735815BED3
Parameters
[in] pu8IP Pointer to IP Address
[in] pu8MAC Pointer to MAC Address
SafeTool Function MD5:
2ABEF0E5890FA02A89BBC11DFCBC37C4
SafeTool Function ID:
LCCM254R0.FILE.014.FUNC.001
References RM4_EMAC_IF::eLinkState, LINK_STATE__IDLE, m_pEMAC_IF, RM4_EMAC_IF::u8IPAddx, and RM4_EMAC_IF::u8MACAddx.
void vRM4_EMAC_LINK__Process (void)
process the state machine Called each program loop to progressively bring up the link.
SafeTool Function MD5:
A0CE617E45084BA14633D7602074CCEB
SafeTool Function ID:
LCCM254R0.FILE.014.FUNC.002
References C_DP83640__PHY_INDEX, RM4_EMAC_IF::eLinkState, EMAC_INT_CORE0_RX, EMAC_INT_CORE0_TX, EMAC_MACADDR_MATCH, EMAC_MACADDR_NO_MATCH_NO_FILTER, LINK_STATE__BLOCK_DESC_INIT, LINK_STATE__CABLE_CHECK, LINK_STATE__CHECK_PHY_ALIVE, LINK_STATE__CHECK_PHY_ALIVE_1, LINK_STATE__ENAB_RX_BROADCAST, LINK_STATE__GET_ALIVE_STATUS, LINK_STATE__GET_PHY_ID, LINK_STATE__GRAT_ARP, LINK_STATE__IDLE, LINK_STATE__INIT_EMAC, LINK_STATE__INIT_MDIO, LINK_STATE__INTERRUPTS_INIT, LINK_STATE__INTERRUPTS_INIT_2, LINK_STATE__LINK_PRE, LINK_STATE__LINK_SETUP_1, LINK_STATE__LINK_SETUP_2, LINK_STATE__LLDP, LINK_STATE__RUN, LINK_STATE__SET_MAC_ADDX, m_pEMAC_IF, RM4_EMAC_IF::pEMAC_Rx_Channel, RM4_EMAC__RX_CHANNEL_T::pHeadDescriptor, s16RM4_EMAC_LINK__Link_Setup_AsyncCheck(), s16RM4_EMAC_LINK__Link_Setup_AsyncStart(), s16RM4_EMAC_MDIO__Init(), RM4_EMAC_IF::sStats, SYS_IRQ, u32RM4_EMAC_MDIO__Get_AliveStatus(), RM4_EMAC_IF::u8CableLength, RM4_EMAC_IF::u8MACAddx, RM4_EMAC_IF::u8PairsSwapped, RM4_EMAC_IF::u8PolarityInvert, vRM4_DELAYS__Delay_mS(), vRM4_DELAYS__Delay_uS(), vRM4_EMAC__Enable_MII(), vRM4_EMAC__Enable_Rx(), vRM4_EMAC__Enable_RxBroadcast_OnChannel(), vRM4_EMAC__Enable_RxUnicast_OnChannel(), vRM4_EMAC__Enable_Tx(), vRM4_EMAC__Init(), vRM4_EMAC__RxHdrDescPtrWrite(), vRM4_EMAC__Set_MACAddx(), vRM4_EMAC__Set_MACSrcAddx(), vRM4_EMAC__Set_NumFreeRxBuffers(), vRM4_EMAC__Set_RMII_Speed100Mb(), vRM4_EMAC__Set_RMII_Speed10Mb(), vRM4_EMAC_BD__Init(), vRM4_EMAC_INT__CoreIntAck(), vRM4_EMAC_INT__Enable_RxIntPulse(), vRM4_EMAC_INT__Enable_TxIntPulse(), and vRM4_VIM__EnableInterrupt().
void vRM4_EMAC_LINK__Set_State (RM4_EMAC__LINK_STATE_T eState)
Set the Link state to a new value.
Parameters
[in] eState The new link state value
SafeTool Function MD5:
1CA806A289D95EFAB4E72C7A265CA301
SafeTool Function ID:
LCCM254R0.FILE.014.FUNC.005
References RM4_EMAC_IF::eLinkState, and m_pEMAC_IF.
Variable Documentation
struct RM4_EMAC_IF m_pEMAC_IF
Referenced by u8RM4_EMAC_LINK__Is_LinkUp(), vRM4_EMAC_LINK__Init(), vRM4_EMAC_LINK__Process(), and vRM4_EMAC_LINK__Set_State().