LFW513 (RLOOP - POWER NODE): EMAC__CORE
EMAC__CORE
RM4 » EMAC
Macros
#define EMAC_CONTROL_RESET (0x01U)
#define EMAC_MAX_HEADER_DESC (8U)
#define EMAC_UNICAST_DISABLE (0xFFU)
Functions
void vRM4_EMAC__Init (void)
This API Initializes the EMAC and EMAC Control modules.
void vRM4_EMAC__Set_RMII_Speed10Mb (void)
This API sets the RMII speed to 10Mb.
void vRM4_EMAC__Set_RMII_Speed100Mb (void)
This API sets the RMII speed to 100Mb.
void vRM4_EMAC__Enable_MII (void)
enables the MII control block
void vRM4_EMAC__Set_Duplex (Luint32 u32DuplexMode)
sets the duplex mode of operation(full/half) for MAC.
void vRM4_EMAC__Enable_Tx (void)
API to enable the transmit in the TX Control Register.
void vRM4_EMAC__Enable_Rx (void)
Enable the receive in the RX Control Register.
void vRM4_EMAC__TxHdrDescPtrWrite (Luint32 descHdr, Luint32 u32Channel)
Write the TX HDP register.
void vRM4_EMAC__RxHdrDescPtrWrite (Luint32 descHdr, Luint32 u32Channel)
Write the RX HDP register.
void vRM4_EMAC__Set_MACSrcAddx (Luint8 *pu8MACAddx)
Sets the MAC Address in MACSRCADDR registers.
void vRM4_EMAC__Set_MACAddx (Luint32 u32Channel, Luint8 *pu8MACAddx, Luint32 pu32MatchFilter)
Sets the MAC Address in MACADDR registers.
void vRM4_EMAC__Write_TxChannelCompletionPointer (Luint32 u32Channel, Luint32 u32CompletionPointer)
Writes the the TX Completion Pointer for a specific channel.
void vRM4_EMAC__Write_RxChannelCompletionPointer (Luint32 u32Channel, Luint32 u32CompletionPointer)
Writes the the RX Completion Pointer for a specific channel.
void vRM4_EMAC__RxIntAckToClear (Luint32 u32Channel, Luint32 u32CompletionPointer, Luint32 u32EOIFlag)
Acknowledges an interrupt processed to the EMAC module.
void vRM4_EMAC__Enable_RxBroadcast_OnChannel (Luint32 u32Channel)
Enables a specific channel to receive broadcast frames.
void vRM4_EMAC__Enable_RxPromiscous_OnChannel (Luint32 u32Channel)
ToDo.
void vRM4_EMAC__Enable_RxUnicast_OnChannel (Luint32 u32Channel)
Enables unicast for a specific channel.
void vRM4_EMAC__Set_NumFreeRxBuffers (Luint32 u32Channel, Luint32 u32NumBuffers)
Set the free buffers for a specific channel.
Luint32 u32RM4_EMAC__Get_IntVector (void)
Gets the interrupt vectors of EMAC, which are pending.
Variables
volatile Luint32 lastInputdescHdr = 0U
volatile Luint32 valHDPbefWrite = 0U
struct RM4_EMAC_IF m_pEMAC_IF
Detailed Description
Macro Definition Documentation
#define EMAC_CONTROL_RESET (0x01U)
Referenced by vRM4_EMAC__Init().
#define EMAC_MAX_HEADER_DESC (8U)
Referenced by vRM4_EMAC__Init().
#define EMAC_UNICAST_DISABLE (0xFFU)
Function Documentation
Luint32 u32RM4_EMAC__Get_IntVector (void)
Gets the interrupt vectors of EMAC, which are pending.
SafeTool Function MD5:
57F6B8FA945D8C7D6450DDDB014BF128
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.023
References EMAC_BASE, EMAC_MACINVECTOR, and HWREG.
void vRM4_EMAC__Enable_MII (void)
enables the MII control block
SafeTool Function MD5:
7EA6C1991F4D7CB31D3FE008A5E93F78
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.008
References EMAC_BASE, EMAC_MACCONTROL, EMAC_MACCONTROL_GMIIEN, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__Enable_Rx (void)
Enable the receive in the RX Control Register.
After the transmit is enabled, and write to RXHDP of a channel, the data can be received in the destination specified by the corresponding RX buffer descriptor.
SafeTool Function MD5:
BF28161241FC629DD8468A4AC60D3525
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.011
References EMAC_BASE, EMAC_RXCONTROL, EMAC_RXCONTROL_RXEN, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__Enable_RxBroadcast_OnChannel (Luint32 u32Channel)
Enables a specific channel to receive broadcast frames.
To receive frames with a matching unicast or multicast destination address. The RXBROADEN bit in the receive multicast/broadcast/promiscuous channel enable register (RXMBPENABLE) determines if broadcast frames are enabled or filtered. If broadcast frames are enabled (when set to 1), then they are copied to only a single channel selected by the RXBROADCH bit in RXMBPENABLE.
Parameters
[in] u32Channel Channel Number.
SafeTool Function MD5:
EEFCD96DBDB1BFA07B495721D5A108BA
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.020
References EMAC_BASE, EMAC_RXMBPENABLE, EMAC_RXMBPENABLE_RXBROADCH, EMAC_RXMBPENABLE_RXBROADCH_SHIFT, EMAC_RXMBPENABLE_RXBROADEN, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__Enable_RxPromiscous_OnChannel (Luint32 u32Channel)
ToDo.
Parameters
References EMAC_BASE, EMAC_RXMBPENABLE, EMAC_RXMBPENABLE_RXPROMCH_SHIFT, and HWREG.
void vRM4_EMAC__Enable_RxUnicast_OnChannel (Luint32 u32Channel)
Enables unicast for a specific channel.
28.2.11.2 Receive Channel Enabling Each of the eight receive channels has an enable bit (RXCHnEN) in the receive unicast set register (RXUNICASTSET) that is controlled using RXUNICASTSET and the receive unicast clear register (RXUNICASTCLEAR). The RXCHnEN bits determine whether the given channel is enabled (when set to 1) to receive frames with a matching unicast or multicast destination address. The RXBROADEN bit in the receive multicast/broadcast/promiscuous channel enable register (RXMBPENABLE) determines if broadcast frames are enabled or filtered. If broadcast frames are enabled (when set to 1), then they are copied to only a single channel selected by the RXBROADCH bit in RXMBPENABLE. The RXMULTEN bit in RXMBPENABLE determines if hash matching multicast frames are enabled or filtered. Incoming multicast addresses (group addresses) are hashed into an index in the hash table. If the indexed bit is set then the frame hash matches and will be transferred to the channel selected by the RXMULTCH bit in RXMBPENABLE when multicast frames are enabled. The multicast hash bits are set in the MAC address hash n registers (MACHASH1 and MACHASH2). The RXPROMCH bit in RXMBPENABLE selects the promiscuous channel to receive frames selected by the RXCMFEN, RXCSFEN, RXCEFEN, and RXCAFEN bits. These four bits allow reception of MAC control frames, short frames, error frames, and all frames (promiscuous), respectively.
Parameters
[in] u32Channel Channel Number
SafeTool Function MD5:
E0D46C26158CAEFA74D71EC17C36630E
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.021
References EMAC_BASE, EMAC_RXUNICASTSET, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__Enable_Tx (void)
API to enable the transmit in the TX Control Register.
After the transmit is enabled, any write to TXHDP of a channel will start transmission
SafeTool Function MD5:
338CA8AE75A77B93F328FEC83F35E482
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.010
References EMAC_BASE, EMAC_TXCONTROL, EMAC_TXCONTROL_TXEN, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__Init (void)
This API Initializes the EMAC and EMAC Control modules.
The EMAC Control module is reset, the CPPI RAM is cleared. also, all the interrupts are disabled. This API does not enable any interrupt or operation of the EMAC.
28.2.16.4 EMAC Module Initialization The EMAC module is used to send and receive data packets over the network. This is done by maintaining up to eight transmit and receive descriptor queues. The EMAC module configuration must also be kept up-to-date based on PHY negotiation results returned from the MDIO module. Most of the work in developing an application or device driver for Ethernet is programming this module. The following is the initialization procedure a device driver would follow to get the EMAC to the state where it is ready to receive and send Ethernet packets. Some of these steps are not necessary when performed immediately after device reset.
If enabled, clear the device interrupt enable bits in the EMAC control module interrupt control registers C0RXTHRESHEN, C0RXEN, C0TXEN, and C0MISCEN.
Clear the MAC control register [MACCONTROL), receive control register [RXCONTROL), and transmit control register [TXCONTROL) [not necessary immediately after reset).
Initialize all 16 header descriptor pointer registers [RXnHDP and TXnHDP) to 0.
Clear all 36 statistics registers by writing 0 [not necessary immediately after reset).
Setup the local Ethernet MAC address by programming the MAC index register [MACINDEX), MAC address high bytes register [MACADDRHI), and MAC address low bytes register [MACADDRLO). Be sure to program all eight MAC address registers - whether the receive channel is to be enabled or not. Duplicate the same MAC address across all unused channels. When using more than one receive channel, start with channel 0 and progress upwards.
If buffer flow control is to be enabled, initialize the receive channel n free buffer count registers [RXnFREEBUFFER), receive channel n flow control threshold register [RXnFLOWTHRESH), and receive filter low priority frame threshold register [RXFILTERLOWTHRESH).
Most device drivers open with no multicast addresses, so clear the MAC address hash registers [MACHASH1 and MACHASH2) to 0.
Write the receive buffer offset register [RXBUFFEROFFSET) value [typically zero).
Initially clear all unicast channels by writing FFh to the receive unicast clear register [RXUNICASTCLEAR). If unicast is desired, it can be enabled now by writing the receive unicast set register [RXUNICASTSET). Some drivers will default to unicast on device open while others will not.
Setup the receive multicast/broadcast/promiscuous channel enable register [RXMBPENABLE) with an initial configuration. The configuration is based on the current receive filter settings of the device driver. Some drivers may enable things like broadcast and multicast packets immediately, while others may not.
Set the appropriate configuration bits in MACCONTROL [do not set the GMIIEN bit yet).
Clear all unused channel interrupt bits by writing the receive interrupt mask clear register [RXINTMASKCLEAR) and the transmit interrupt mask clear register [TXINTMASKCLEAR).
Enable the receive and transmit channel interrupt bits in the receive interrupt mask set register [RXINTMASKSET) and the transmit interrupt mask set register [TXINTMASKSET) for the channels to be used, and enable the HOSTMASK and STATMASK bits using the MAC interrupt mask set register [MACINTMASKSET).
Initialize the receive and transmit descriptor list queues.
Prepare receive by writing a pointer to the head of the receive buffer descriptor list to RXnHDP.
Enable the receive and transmit DMA controllers by setting the RXEN bit in RXCONTROL and the TXEN bit in TXCONTROL. Then set the GMIIEN bit in MACCONTROL.
Enable the device interrupt in EMAC control module registers C0RXTHRESHEN, C0RXEN, C0TXEN, and C0MISCEN.
SafeTool Function MD5:
113D6BCD2FF84D63F62014097C77A17E
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.001
References EMAC_BASE, EMAC_CONTROL_RESET, EMAC_CTRL_BASE, EMAC_CTRL_SOFTRESET, EMAC_MACCONTROL, EMAC_MACHASH1, EMAC_MACHASH2, EMAC_MAX_HEADER_DESC, EMAC_RXBUFFEROFFSET, EMAC_RXCONTROL, EMAC_RXCP, EMAC_RXFREEBUFFER, EMAC_RXHDP, EMAC_RXINTMASKCLEAR, EMAC_TXCONTROL, EMAC_TXCP, EMAC_TXHDP, EMAC_TXINTMASKCLEAR, HWREG, and vRM4_EMAC_RESET__Soft_Reset().
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__RxHdrDescPtrWrite (Luint32 descHdr, Luint32 u32Channel)
Write the RX HDP register.
If receive is enabled, write to the RX HDP will enable data reception to point to the corresponding RX buffer descriptor's buffer pointer.
Parameters
[in] u32Channel ## Desc ##
[in] descHdr ## Desc ##
SafeTool Function MD5:
C0CA0A7FA19A93CA0EF9DC19D18F50A2
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.013
References EMAC_BASE, EMAC_RXHDP, and HWREG.
Referenced by vRM4_EMAC_LINK__Process(), and vRM4_EMAC_RX__RxIntHandler().
void vRM4_EMAC__RxIntAckToClear (Luint32 u32Channel, Luint32 u32CompletionPointer, Luint32 u32EOIFlag)
Acknowledges an interrupt processed to the EMAC module.
After processing an interrupt, the last processed buffer descriptor is written to the completion pointer. Also this API acknowledges the EMAC Control Module that the RX interrupt is processed for a specified core
Parameters
[in] u32EOIFlag Type of interrupt to acknowledge to the EMAC Control module u32EOIFlag can take the following values EMAC_INT_CORE0_RX - Core 0 RX Interrupt EMAC_INT_CORE1_RX - Core 1 RX Interrupt EMAC_INT_CORE2_RX - Core 2 RX Interrupt
[in] u32CompletionPointer Completion Pointer value. This shall be the buffer descriptor address last processed.
[in] u32Channel Channel Number
SafeTool Function MD5:
1949E0B51215843252741E199C9C9733
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.019
References EMAC_BASE, EMAC_MACEOIVECTOR, EMAC_RXCP, and HWREG.
void vRM4_EMAC__Set_Duplex (Luint32 u32DuplexMode)
sets the duplex mode of operation(full/half) for MAC.
Parameters
[in] u32DuplexMode ## Desc ##
SafeTool Function MD5:
C7FF4BFEEEFD1D3383A7E8042C2F2DCA
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.009
References EMAC_BASE, EMAC_MACCONTROL, EMAC_MACCONTROL_FULLDUPLEX, and HWREG.
Referenced by s16RM4_EMAC_LINK__Link_Setup(), and s16RM4_EMAC_LINK__Link_Setup_AsyncCheck().
void vRM4_EMAC__Set_MACAddx (Luint32 u32Channel, Luint8 * pu8MACAddx, Luint32 pu32MatchFilter)
Sets the MAC Address in MACADDR registers.
28.2.11.3 Receive Address Matching All eight MAC addresses corresponding to the eight receive channels share the upper 40 bits. Only the lower byte is unique for each address. All eight receive addresses should be initialized, because pause frames are acted upon regardless of whether a channel is enabled or not. A MAC address is written by first writing the address number (channel) to be written into the MAC index register (MACINDEX). The upper 32 bits of address are then written to the MAC address high bytes register (MACADDRHI), which is followed by writing the lower 16 bits of address to the MAC address low bytes register (MACADDRLO). Since all eight MAC addresses share the upper 40 bits of address, MACADDRHI needs to be written only the first time (for the first channel configured).
Parameters
[in] pu32MatchFilter matchFilt can take the following values: EMAC_MACADDR_NO_MATCH_NO_FILTER - Address is not used to match or filter incoming packet. EMAC_MACADDR_FILTER - Address is used to filter incoming packets EMAC_MACADDR_MATCH - Address is used to match incoming packets
[in] pu8MACAddx The array[0] shall be the LSB of the MAC address
[in] u32Channel Channel Number
SafeTool Function MD5:
7E96C7EF4D0F30FFB82CF5587EF0780D
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.015
References EMAC_BASE, EMAC_MACADDRHI, EMAC_MACADDRLO, EMAC_MACINDEX, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__Set_MACSrcAddx (Luint8 * pu8MACAddx)
Sets the MAC Address in MACSRCADDR registers.
Parameters
[in] pu8MACAddx The array[0] shall be the LSB of the MAC address
SafeTool Function MD5:
483D5CDC8E79983E722EDD344D2C3047
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.014
References EMAC_BASE, EMAC_MACSRCADDRHI, EMAC_MACSRCADDRLO, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__Set_NumFreeRxBuffers (Luint32 u32Channel, Luint32 u32NumBuffers)
Set the free buffers for a specific channel.
Parameters
[in] u32NumBuffers Number of free buffers
[in] u32Channel Channel Number.
SafeTool Function MD5:
94F8AC14060596D118732AAF47839DA2
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.022
References EMAC_BASE, EMAC_RXFREEBUFFER, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__Set_RMII_Speed100Mb (void)
This API sets the RMII speed to 100Mb.
SafeTool Function MD5:
8541BC859FE9787FFA2106886ADD5903
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.007
References EMAC_BASE, EMAC_MACCONTROL, EMAC_MACCONTROL_RMIISPEED, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__Set_RMII_Speed10Mb (void)
This API sets the RMII speed to 10Mb.
SafeTool Function MD5:
98EFEB2EFFA9D958B80E1F8272135560
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.006
References EMAC_BASE, EMAC_MACCONTROL, EMAC_MACCONTROL_RMIISPEED, and HWREG.
Referenced by vRM4_EMAC_LINK__Process().
void vRM4_EMAC__TxHdrDescPtrWrite (Luint32 descHdr, Luint32 u32Channel)
Write the TX HDP register.
If transmit is enabled, write to the TX HDP will immediately start transmission. The data will be taken from the buffer pointer of the TX buffer descriptor written to the TX HDP
Parameters
[in] u32Channel ## Desc ##
[in] descHdr ## Desc ##
SafeTool Function MD5:
CAE67B3330B496AF2288DA99715C6AD9
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.012
References EMAC_BASE, EMAC_TXHDP, HWREG, lastInputdescHdr, and valHDPbefWrite.
void vRM4_EMAC__Write_RxChannelCompletionPointer (Luint32 u32Channel, Luint32 u32CompletionPointer)
Writes the the RX Completion Pointer for a specific channel.
Upon interrupt reception, the CPU processes one or more packets from the buffer chain and then acknowledges one or more interrupt(s) by writing the address of the last buffer descriptor processed to the queue's associated receive completion pointer in the receive DMA state RAM.
Parameters
[in] u32CompletionPointer Completion Pointer Value to be written
[in] u32Channel Channel Number
SafeTool Function MD5:
A138FC52F827A9DC521050F205A7893B
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.018
References EMAC_BASE, EMAC_RXCP, and HWREG.
Referenced by vRM4_EMAC_RX__RxIntHandler().
void vRM4_EMAC__Write_TxChannelCompletionPointer (Luint32 u32Channel, Luint32 u32CompletionPointer)
Writes the the TX Completion Pointer for a specific channel.
Parameters
[in] u32CompletionPointer Completion Pointer Value to be written
[in] u32Channel Channel Number
SafeTool Function MD5:
C226994569AD17AF59D7C1C618065A0D
SafeTool Function ID:
LCCM254R0.FILE.001.FUNC.017
References EMAC_BASE, EMAC_TXCP, and HWREG.
Referenced by vRM4_EMAC_TX__Tx_IntHandler().
Variable Documentation
volatile Luint32 lastInputdescHdr = 0U
Referenced by vRM4_EMAC__TxHdrDescPtrWrite().
struct RM4_EMAC_IF m_pEMAC_IF
Referenced by u8RM4_EMAC_LINK__Is_LinkUp(), vRM4_EMAC_BD__Init(), vRM4_EMAC_BD__Set_Length(), vRM4_EMAC_LINK__Init(), vRM4_EMAC_LINK__Process(), vRM4_EMAC_LINK__Set_State(), vRM4_EMAC_RX__RxIntHandler(), and vRM4_EMAC_TX__Tx_IntHandler().
volatile Luint32 valHDPbefWrite = 0U
Referenced by vRM4_EMAC__TxHdrDescPtrWrite().