LFW513 (RLOOP - POWER NODE): DS18B20__WIRE_IF
DS18B20__WIRE_IF
MULTICORE » DS18B20
Functions
Lint16 s16DS18B20_1WIRE__Generate_Reset (Luint8 u8DeviceIndex)
Generate a reset.
Lint16 s16DS18B20_1WIRE__SelectDevice (Luint8 u8DeviceIndex, Luint8 *pu8Addx)
Select a device.
Lint16 s16DS18B20_1WIRE__WriteByte (Luint8 u8DeviceIndex, Luint8 u8Byte)
Write a byte to the wire.
Lint16 s16DS18B20_1WIRE__ReadByte (Luint8 u8DeviceIndex, Luint8 *pu8Byte)
Read a byte from the 1-wire.
Lint16 s16DS18B20_SEARCH__SearchFirstDevice (Luint8 u8DeviceIndex, Luint8 *pu8Addx)
Search for the first device on the bus.
Lint16 s16DS18B20_SEARCH__SearchNextDevice (Luint8 u8DeviceIndex, Luint8 *pu8Addx)
Search for the next device on the bus.
Lint16 s16DS18B20_1WIRE__Skip (Luint8 u8DeviceIndex)
Implement a 1-Wire skip function.
Detailed Description
Function Documentation
Lint16 s16DS18B20_1WIRE__Generate_Reset (Luint8 u8DeviceIndex)
Generate a reset.
Parameters
[in] u8DeviceIndex Index of 1-wire interface
SafeTool Function MD5:
CDB3958614F79B28CB59ED3A211CC8AC
SafeTool Function ID:
LCCM644R0.FILE.007.FUNC.001
References s16DS2482S_1WIRE__Generate_Reset().
Referenced by s16DS18B20_SCRATCH__Read(), s16DS18B20_SCRATCH__Write(), s16DS18B20_TEMP__All_Request(), and s16DS18B20_TEMP__Request().
Lint16 s16DS18B20_1WIRE__ReadByte (Luint8 u8DeviceIndex, Luint8 * pu8Byte)
Read a byte from the 1-wire.
Parameters
[out] *pu8Byte Returned byte if found
[in] u8DeviceIndex Index of 1-wire interface
SafeTool Function MD5:
AFA59D986F8FC766E12551D1B6F84FA2
SafeTool Function ID:
LCCM644R0.FILE.007.FUNC.004
References s16DS2482S_1WIRE__ReadByte().
Referenced by s16DS18B20_SCRATCH__Read().
Lint16 s16DS18B20_1WIRE__SelectDevice (Luint8 u8DeviceIndex, Luint8 * pu8Addx)
Select a device.
Parameters
[in] *pu8Addx Device addx
[in] u8DeviceIndex Index of 1-wire interface
SafeTool Function MD5:
00E8C63D899BECC89CE14F45B9FF31BF
SafeTool Function ID:
LCCM644R0.FILE.007.FUNC.002
References s16DS2482S_1WIRE__SelectDevice().
Referenced by s16DS18B20_SCRATCH__Read(), s16DS18B20_SCRATCH__Write(), and s16DS18B20_TEMP__Request().
Lint16 s16DS18B20_1WIRE__Skip (Luint8 u8DeviceIndex)
Implement a 1-Wire skip function.
Parameters
[in] u8DeviceIndex Index of 1-wire interface
SafeTool Function MD5:
183883F869CD1E4C8B559B980F523637
SafeTool Function ID:
LCCM644R0.FILE.007.FUNC.007
References s16DS2482S_1WIRE__Skip().
Referenced by s16DS18B20_TEMP__All_Request().
Lint16 s16DS18B20_1WIRE__WriteByte (Luint8 u8DeviceIndex, Luint8 u8Byte)
Write a byte to the wire.
Parameters
[in] u8Byte The byte value to write
[in] u8DeviceIndex Index of 1-wire interface
SafeTool Function MD5:
488FA3234797EB76B772F4E003958BA9
SafeTool Function ID:
LCCM644R0.FILE.007.FUNC.003
References s16DS2482S_1WIRE__WriteByte().
Referenced by s16DS18B20_SCRATCH__Read(), s16DS18B20_SCRATCH__Write(), and s16DS18B20_TEMP__Request().
Lint16 s16DS18B20_SEARCH__SearchFirstDevice (Luint8 u8DeviceIndex, Luint8 * pu8Addx)
Search for the first device on the bus.
Parameters
[out] *pu8Addx Returned address if found
[in] u8DeviceIndex Index of 1-wire interface
SafeTool Function MD5:
43176838A53AF5897D5E3470907352DD
SafeTool Function ID:
LCCM644R0.FILE.007.FUNC.005
References s16DS2482S_SEARCH__SearchFirstDevice().
Referenced by s16DS18B20_ADDX__Search(), and vDS18B20_ADDX__SearchSM_Process().
Lint16 s16DS18B20_SEARCH__SearchNextDevice (Luint8 u8DeviceIndex, Luint8 * pu8Addx)
Search for the next device on the bus.
Parameters
[out] *pu8Addx Returned address if found
[in] u8DeviceIndex Index of 1-wire interface
SafeTool Function MD5:
B1D30D87E8A6ED5A273936EF78C52E1B
SafeTool Function ID:
LCCM644R0.FILE.007.FUNC.006
References s16DS2482S_SEARCH__SearchNextDevice().
Referenced by s16DS18B20_ADDX__Search(), and vDS18B20_ADDX__SearchSM_Process().