LFW513 (RLOOP - POWER NODE): DS2482S__DEVICE
DS2482S__DEVICE
MULTICORE » DS2482S
Functions
static Lint16 s16DS2482S_DEVICE__Set_ReadPointer (Luint8 u8DeviceIndex, E_DS2482_POINTER_T ePointer)
Sets the devices read pointer to one of a few predetermined values.
Lint16 s16DS2482S_DEVICE__Reset (Luint8 u8DeviceIndex)
Generate a device reset by activating the reset command in software.
Lint16 s16DS2482S_DEVICE__Get_Status (Luint8 u8DeviceIndex, Luint8 *pu8Status)
Gets the status register.
Lint16 s16DS2482S_DEVICE__Read_ConfigRegister (Luint8 u8DeviceIndex, Luint8 *pu8Value)
Read from the configuration register.
Lint16 s16DS2482S_DEVICE__Set_ConfigRegister (Luint8 u8DeviceIndex, Luint8 u8Value)
Sets the config register.
Luint8 u8DS2482S_DEVICE__Wait_Busy (Luint8 u8DeviceIndex, Luint8 *pu8Status)
Waits for the Busy bit to be clear before continuing.
Lint16 s16DS2482S_DEVICE__Read_Byte (Luint8 u8DeviceIndex, Luint8 *pu8Value)
Read a byte from the device's data register.
Detailed Description
Function Documentation
Lint16 s16DS2482S_DEVICE__Get_Status (Luint8 u8DeviceIndex, Luint8 * pu8Status)
Gets the status register.
SafeTool Images:
The image below shows a get status transaction.
Parameters
[in] *pu8Status Returned status register data
[in] u8DeviceIndex The I2C bus device index
Returns
0 = success
-ve = error
SafeTool Function MD5:
277602DD6823722E0663391C3ED64F36
SafeTool Function ID:
LCCM641R0.FILE.006.FUNC.003
References DS2482_POINTER__STATUS, s16DS2482S_DEVICE__Set_ReadPointer(), and s16DS2482S_LOWLEVEL__RxReg().
Referenced by s16DS2482S_1WIRE__Generate_Reset(), u8DS2482S_DEVICE__Wait_Busy(), and vDS2482S__Init().
Lint16 s16DS2482S_DEVICE__Read_Byte (Luint8 u8DeviceIndex, Luint8 * pu8Value)
Read a byte from the device's data register.
Parameters
[out] *pu8Value Pointer to the returned value
[in] u8DeviceIndex The I2C device index
SafeTool Function MD5:
87B1F205394A2E2D098CDB8F82DDF31C
SafeTool Function ID:
LCCM641R0.FILE.006.FUNC.007
References DS2482_POINTER__DATA, s16DS2482S_DEVICE__Set_ReadPointer(), and s16DS2482S_LOWLEVEL__RxReg().
Referenced by s16DS2482S_1WIRE__ReadByte().
Lint16 s16DS2482S_DEVICE__Read_ConfigRegister (Luint8 u8DeviceIndex, Luint8 * pu8Value)
Read from the configuration register.
Note
Example Bus transaction: 0x30 [Wr Addx], 0xE1 [Pointer Addx], 0xC3[Config Pointer] 0x31 [Rd Addx], 0x00 [Config Value]
Parameters
[in] *pu8Value The config reg value if read was successful
[in] u8DeviceIndex The I2C device index
Returns
0 = success
-ve = error -10, -11
SafeTool Function MD5:
8A8D230646F047DF454D3CD270B5F6A8
SafeTool Function ID:
LCCM641R0.FILE.006.FUNC.004
Remember here that the config register contains not bits: Configuration Register Bit Assignment: BIT 7 BIT 6 BIT 5 BIT 4 BIT 3 BIT 2 BIT 1 BIT 0 n1WS nSPU 1 nAPU 1WS SPU 0 APU
References DS2482_POINTER__CONFIG, s16DS2482S_DEVICE__Set_ReadPointer(), and s16DS2482S_LOWLEVEL__RxReg().
Referenced by s16DS2482S_1WIRE__Clear_StrongPullup(), and s16DS2482S_1WIRE__Set_StrongPullup().
Lint16 s16DS2482S_DEVICE__Reset (Luint8 u8DeviceIndex)
Generate a device reset by activating the reset command in software.
Note
This must be completed before any other transactions occur on the device
Example Bus Transaction: 0x30 [Wr Addx], 0xF0 [Command Reset Register] 0x31 [Rd Addx], 0x18 [Default Status Register]
Parameters
[in] u8DeviceIndex The I2C bus device index
Returns
0 = success
-ve = error
SafeTool Function MD5:
01824614781D8CCD0D8A061064FBBAD2
SafeTool Function ID:
LCCM641R0.FILE.006.FUNC.001
If the RST bit is 1, the DS2482-100 has performed an internal reset cycle, either caused by a power-on reset or from executing the Device Reset command. The RST bit is cleared automatically when the DS2482-100 executes a Write Configuration command to restore the selection of the desired 1-Wire features
References DS2482_REGS__COMMAND_RESET, s16DS2482S_DEVICE__Set_ConfigRegister(), s16DS2482S_LOWLEVEL__RxReg(), and s16DS2482S_LOWLEVEL__TxReg().
Referenced by vDS2482S__Init().
Lint16 s16DS2482S_DEVICE__Set_ConfigRegister (Luint8 u8DeviceIndex, Luint8 u8Value)
Sets the config register.
Parameters
[in] u8Value New register value
[in] u8DeviceIndex Device index on the bus
Returns
0 = success
-ve = error
SafeTool Function MD5:
14FDE7539F053AFD61DD8AC597D59C37
SafeTool Function ID:
LCCM641R0.FILE.006.FUNC.005
Write Configuration Description Writes a new configuration byte. The new settings take effect immediately. Note: When writing to the Configuration Register, the new data is accepted only if the upper nibble (bits 7 to 4) is the one's complement of the lower nibble (bits 3 to 0). When read, the upper nibble is always 0h. Typical Use Defining the features for subsequent 1-Wire communication. Restriction 1-Wire activity must have ended before the DS2482-100 can process this command. Error Response Command code and parameter are not acknowledged if 1WB = 1 at the time the command code is received and the command is ignored. Command Duration None. The Configuration Register is updated on the rising SCL edge of the configuration-byte acknowledge bit. 1-Wire Activity None Read Pointer Position Configuration Register (to verify write). Status Bits Affected RST set to 0. Config Bits Affected 1WS, SPU, APU updated.
References DS2482_REGS__COMMAND_WRITE_CONFIG, s16DS2482S_LOWLEVEL__RxReg(), s16DS2482S_LOWLEVEL__WriteReg(), and u8DS2482S_DEVICE__Wait_Busy().
Referenced by s16DS2482S_1WIRE__Clear_StrongPullup(), and s16DS2482S_DEVICE__Reset().
Lint16 s16DS2482S_DEVICE__Set_ReadPointer (Luint8 u8DeviceIndex, E_DS2482_POINTER_T ePointer) static
Sets the devices read pointer to one of a few predetermined values.
Parameters
[in] ePointer The register pointer enum.
[in] u8DeviceIndex The I2C bus device index
Returns
0 = success
-ve = error
SafeTool Function MD5:
542AC92DAF70666F055287D2AE3A388A
SafeTool Function ID:
LCCM641R0.FILE.006.FUNC.002
References DS2482_REGS__COMMAND_SET_READ_POINTER, and s16DS2482S_LOWLEVEL__WriteReg().
Referenced by s16DS2482S_DEVICE__Get_Status(), s16DS2482S_DEVICE__Read_Byte(), and s16DS2482S_DEVICE__Read_ConfigRegister().
Luint8 u8DS2482S_DEVICE__Wait_Busy (Luint8 u8DeviceIndex, Luint8 * pu8Status)
Waits for the Busy bit to be clear before continuing.
Parameters
[in] u8DeviceIndex Device index on the bus
Returns
0 = not busy or not time out
1 = Timeout (busy status unknown)
SafeTool Function MD5:
0F8EE83B4B12802BCBC13DF1612ED35C
SafeTool Function ID:
LCCM641R0.FILE.006.FUNC.006
References s16DS2482S_DEVICE__Get_Status(), and vRM4_DELAYS__Delay_uS().
Referenced by s16DS2482S_1WIRE__Generate_Reset(), s16DS2482S_1WIRE__ReadBit(), s16DS2482S_1WIRE__ReadByte(), s16DS2482S_1WIRE__WriteBit(), s16DS2482S_1WIRE__WriteByte(), s16DS2482S_DEVICE__Set_ConfigRegister(), and s16DS2482S_SEARCH__Search().