LFW513 (RLOOP - POWER NODE): RM4__RTI__INTERRUPTS
RM4__RTI__INTERRUPTS
RM4 » RM4__RTI
Functions
void vRTI_COMPARE__Disable_CompareInterrupt (Luint8 u8Index)
Disables one of the 4 timers indicated by u8Index.
void vRTI_COMPARE__Enable_CompareInterrupt (Luint8 u8Index)
Enables one of the 4 timers indicated by u8Index.
void vRM4_RTI_ISR__Enable_Interrupts (void)
Enables the interrupts marked in the RTI struct.
void vRM4_RTI_ISR__Disable_Interrupts (void)
Disables the interrupts marked in the RTI struct.
void vRM4_RTI_ISR__Compare0 (void)
RTI Counter 0 ISR.
void vRM4_RTI_ISR__Compare1 (void)
RTI Counter 1 ISR.
void vRM4_RTI_ISR__Compare2 (void)
RTI Counter 2 ISR.
void vRM4_RTI_ISR__Compare3 (void)
RTI Counter 3 ISR.
void vRM4_RTI_ISR__Overflow0 (void)
RTI1 counter 0 overflow interrupt handler.
void vRM4_RTI_ISR__Overflow1 (void)
RTI1 counter 1 overflow interrupt handler.
void vRM4_RTI_ISR__Timebase (void)
RTI1 timebase interrupt handler.
void vRM4_RTI_INTERRUPTS__DefaultCallbackHandler (void)
Default handler for unassigned interrupts.
Variables
struct _strRTI sRTI
Detailed Description
Function Documentation
void vRM4_RTI_INTERRUPTS__DefaultCallbackHandler (void)
Default handler for unassigned interrupts.
SafeTool Function MD5:
67D1566B01B9B24F87B148A0B85AE8B1
SafeTool Function ID:
LCCM124R0.FILE.008.FUNC.012
void vRM4_RTI_ISR__Compare0 (void)
RTI Counter 0 ISR.
SafeTool Function MD5:
CBB5904A691F39F5A76D687F7D1D46D6
SafeTool Function ID:
LCCM124R0.FILE.008.FUNC.005
References rtiREG1.
void vRM4_RTI_ISR__Compare1 (void)
RTI Counter 1 ISR.
SafeTool Function MD5:
3C00E0E1E69023978A67EDCA39709927
SafeTool Function ID:
LCCM124R0.FILE.008.FUNC.006
References rtiREG1.
void vRM4_RTI_ISR__Compare2 (void)
RTI Counter 2 ISR.
SafeTool Function MD5:
AB317D917083D4242FE00C4110B29996
SafeTool Function ID:
LCCM124R0.FILE.008.FUNC.007
References rtiREG1.
void vRM4_RTI_ISR__Compare3 (void)
RTI Counter 3 ISR.
SafeTool Function MD5:
4983186A1D1CCD5B07EB67E955284D58
SafeTool Function ID:
LCCM124R0.FILE.008.FUNC.008
References rtiREG1.
void vRM4_RTI_ISR__Disable_Interrupts (void)
Disables the interrupts marked in the RTI struct.
SafeTool Function MD5:
22A27711D35EB3D53362BB9D88117269
SafeTool Function ID:
LCCM124R0.FILE.008.FUNC.004
References _strRTI::Compare0_InterruptEnabled, _strRTI::Compare1_InterruptEnabled, _strRTI::Compare2_InterruptEnabled, _strRTI::Compare3_InterruptEnabled, _strRTI::DMA0_RequestEnabled, _strRTI::DMA1_RequestEnabled, _strRTI::DMA2_RequestEnabled, _strRTI::DMA3_RequestEnabled, _strRTI::FRC0_OverflowInterruptEnabled, _strRTI::FRC1_OverflowInterruptEnabled, rtiREG1, sRTI, and _strRTI::TimebaseInterruptEnabled.
Referenced by vRM4_RTI__Init(), and vRTI_COMPARE__Disable_CompareInterrupt().
void vRM4_RTI_ISR__Enable_Interrupts (void)
Enables the interrupts marked in the RTI struct.
SafeTool Function MD5:
D6427F926C3F4517EC12696A57E4BB03
SafeTool Function ID:
LCCM124R0.FILE.008.FUNC.003
References _strRTI::Compare0_InterruptEnabled, _strRTI::Compare1_InterruptEnabled, _strRTI::Compare2_InterruptEnabled, _strRTI::Compare3_InterruptEnabled, _strRTI::DMA0_RequestEnabled, _strRTI::DMA1_RequestEnabled, _strRTI::DMA2_RequestEnabled, _strRTI::DMA3_RequestEnabled, _strRTI::FRC0_OverflowInterruptEnabled, _strRTI::FRC1_OverflowInterruptEnabled, rtiREG1, sRTI, _strRTI::TimebaseInterruptEnabled, and vRM4_RTI__Clear_Flags().
Referenced by vRTI_COMPARE__Enable_CompareInterrupt().
void vRM4_RTI_ISR__Overflow0 (void)
RTI1 counter 0 overflow interrupt handler.
SafeTool Function MD5:
19A25F37D3BBD86DF82C02316136D8DF
SafeTool Function ID:
LCCM124R0.FILE.008.FUNC.009
References rtiREG1.
void vRM4_RTI_ISR__Overflow1 (void)
RTI1 counter 1 overflow interrupt handler.
SafeTool Function MD5:
77BDA2D4D996BC42DBCD47C8E6D8D3DF
SafeTool Function ID:
LCCM124R0.FILE.008.FUNC.010
References rtiREG1.
void vRM4_RTI_ISR__Timebase (void)
RTI1 timebase interrupt handler.
SafeTool Function MD5:
9B95C20A97EA51C8A8B99305A9EC23B1
SafeTool Function ID:
LCCM124R0.FILE.008.FUNC.011
References rtiREG1.
void vRTI_COMPARE__Disable_CompareInterrupt (Luint8 u8Index)
Disables one of the 4 timers indicated by u8Index.
Parameters
[in] u8Index The counter channel
SafeTool Function MD5:
B3B4662DEE8F179B9091A4BBDC756A73
SafeTool Function ID:
LCCM124R0.FILE.008.FUNC.001
References _strRTI::Compare0_InterruptEnabled, _strRTI::Compare1_InterruptEnabled, _strRTI::Compare2_InterruptEnabled, _strRTI::Compare3_InterruptEnabled, sRTI, and vRM4_RTI_ISR__Disable_Interrupts().
void vRTI_COMPARE__Enable_CompareInterrupt (Luint8 u8Index)
Enables one of the 4 timers indicated by u8Index.
Parameters
[in] u8Index The counter channel
SafeTool Function MD5:
08A783423A315B6201BB65ED5BD795F6
SafeTool Function ID:
LCCM124R0.FILE.008.FUNC.002
References _strRTI::Compare0_InterruptEnabled, _strRTI::Compare1_InterruptEnabled, _strRTI::Compare2_InterruptEnabled, _strRTI::Compare3_InterruptEnabled, sRTI, and vRM4_RTI_ISR__Enable_Interrupts().
Variable Documentation
struct _strRTI sRTI
Referenced by s16RM4_RTI__Stop_Counter(), vRM4_RTI__Init(), vRM4_RTI__Start_Counter(), vRM4_RTI__Struct_Init(), vRM4_RTI__Update_Period(), vRM4_RTI_ISR__Disable_Interrupts(), vRM4_RTI_ISR__Enable_Interrupts(), vRTI_COMPARE__Disable_CompareInterrupt(), and vRTI_COMPARE__Enable_CompareInterrupt().