LFW513 (RLOOP - POWER NODE): SPI135__TX
SPI135__TX
RM4 » SPI135
Functions
Luint16 u16RM4_MIBSPI135__Tx_U16_2 (RM4_MIBSPI135__CHANNELS_T eChannel, RM4_MIBSPI135__DATA_FORMAT_T eDataFormat, RM4_MIBSPI135__CHIP_SELECT_T eChipSelectNum, Luint8 u8DataL, Luint8 u8DataH)
Transmit a U16 as two separate U8's.
Luint8 u8RM4_MIBSPI135__Tx_U16_2_LSB (RM4_MIBSPI135__CHANNELS_T eChannel, RM4_MIBSPI135__DATA_FORMAT_T eDataFormat, RM4_MIBSPI135__CHIP_SELECT_T eChipSelectNum, Luint8 u8DataL, Luint8 u8DataH)
Send a 2 byte U16, and return the LSB (second return)
Luint16 u16RM4_MIBSPI135__Tx_U16 (RM4_MIBSPI135__CHANNELS_T eChannel, RM4_MIBSPI135__DATA_FORMAT_T eDataFormat, RM4_MIBSPI135__CHIP_SELECT_T eChipSelectNum, Luint16 u16Data)
Transmit a 16bit value.
Luint8 u8RM4_MIBSPI135__Tx_U8 (RM4_MIBSPI135__CHANNELS_T eChannel, RM4_MIBSPI135__DATA_FORMAT_T eDataFormat, RM4_MIBSPI135__CHIP_SELECT_T eChipSelectNum, Luint8 u8Data)
Transmit a byte.
Detailed Description
Function Documentation
Luint16 u16RM4_MIBSPI135__Tx_U16 (RM4_MIBSPI135__CHANNELS_T eChannel, RM4_MIBSPI135__DATA_FORMAT_T eDataFormat, RM4_MIBSPI135__CHIP_SELECT_T eChipSelectNum, Luint16 u16Data)
Transmit a 16bit value.
Parameters
[in] u16Data Value to transmit
[in] eChipSelectNum Chip select to use
[in] eDataFormat Data format to use
[in] eChannel Channel to use
Returns
The read 16bit value.
SafeTool Function MD5:
47E6FB44CF2ABFEB6B284448EEC8B91D
SafeTool Function ID:
LCCM280R0.FILE.005.FUNC.003
References RM4_MIBSPI135__BASE_T::BUF, RM4_MIBSPI135__BASE_T::DAT1, RM4_MIBSPI135__BASE_T::FLG, MIBSPI135_CHANNEL__1, MIBSPI135_CHANNEL__3, MIBSPI135_CHANNEL__5, mibspiREG1, mibspiREG3, and mibspiREG5.
Referenced by u16RM4_MIBSPI135__Tx_U16_2(), and u8RM4_MIBSPI135__Tx_U16_2_LSB().
Luint16 u16RM4_MIBSPI135__Tx_U16_2 (RM4_MIBSPI135__CHANNELS_T eChannel, RM4_MIBSPI135__DATA_FORMAT_T eDataFormat, RM4_MIBSPI135__CHIP_SELECT_T eChipSelectNum, Luint8 u8DataL, Luint8 u8DataH)
Transmit a U16 as two separate U8's.
Note
This function is useful for system that need to have 16bit register read/writes
Parameters
[in] u8DataH High nibble
[in] u8DataL Low Nibble
[in] eChipSelectNum Chip select if used
[in] eDataFormat Data formatting type
[in] eChannel SPI Channel
SafeTool Function MD5:
9DF839D7CDC02C1A25A2259A96EFCD36
SafeTool Function ID:
LCCM280R0.FILE.005.FUNC.001
References u16RM4_MIBSPI135__Tx_U16().
Luint8 u8RM4_MIBSPI135__Tx_U16_2_LSB (RM4_MIBSPI135__CHANNELS_T eChannel, RM4_MIBSPI135__DATA_FORMAT_T eDataFormat, RM4_MIBSPI135__CHIP_SELECT_T eChipSelectNum, Luint8 u8DataL, Luint8 u8DataH)
Send a 2 byte U16, and return the LSB (second return)
Parameters
[in] u8DataH High part of byte
[in] u8DataL Low part of byte
[in] eChipSelectNum Chipselect to use
[in] eDataFormat Dataformat to use
[in] eChannel SPI Channel
SafeTool Function MD5:
AEA42D1443FE04C147FBBB35CBBA8B78
SafeTool Function ID:
LCCM280R0.FILE.005.FUNC.002
References u16RM4_MIBSPI135__Tx_U16().
Luint8 u8RM4_MIBSPI135__Tx_U8 (RM4_MIBSPI135__CHANNELS_T eChannel, RM4_MIBSPI135__DATA_FORMAT_T eDataFormat, RM4_MIBSPI135__CHIP_SELECT_T eChipSelectNum, Luint8 u8Data)
Transmit a byte.
Parameters
[in] u8Data The data byte to use
[in] eChipSelectNum The chip select type to use (else none)
[in] eDataFormat Data format type to use
[in] eChannel SPI Channel
Returns
The read data byte
SafeTool Function MD5:
0F51126483B1B9418162CF4BBFEDAC68
SafeTool Function ID:
LCCM280R0.FILE.005.FUNC.004
References RM4_MIBSPI135__BASE_T::BUF, RM4_MIBSPI135__BASE_T::DAT1, RM4_MIBSPI135__BASE_T::FLG, MIBSPI135_CHANNEL__1, MIBSPI135_CHANNEL__3, MIBSPI135_CHANNEL__5, mibspiREG1, mibspiREG3, and mibspiREG5.