LFW513 (RLOOP - POWER NODE): DS2482S__CORE
DS2482S__CORE
MULTICORE » DS2482S
Functions
void vDS2482S__Init (void)
Init the DS2482 device User should call this first up after the I2C driver is operational.
void vDS2482S__Process (void)
Process any DS2482 tasks.
Luint8 u8DS2482S_USER__1Wire_Reset (Luint8 u8DeviceIndex)
User level function to generate a reset on the one wire bus.
Variables
struct _strDS2482S sDS2482S
Detailed Description
Function Documentation
Luint8 u8DS2482S_USER__1Wire_Reset (Luint8 u8DeviceIndex)
User level function to generate a reset on the one wire bus.
Parameters
[in] u8DeviceIndex I2C bus device index
Returns
0 = fault or no devices found
1 = at least one device found
SafeTool Function MD5:
7D4FF1951AA3DF6D9E6DF62D02B7C002
SafeTool Function ID:
LCCM641R0.FILE.000.FUNC.003
References s16DS2482S_1WIRE__Generate_Reset().
Referenced by s16DS2482S_SEARCH__Search().
void vDS2482S__Init (void)
Init the DS2482 device User should call this first up after the I2C driver is operational.
SafeTool Function MD5:
F66DF3BBFFE38B31DE9077D79A2E4B82
SafeTool Function ID:
LCCM641R0.FILE.000.FUNC.001
References C_LOCALDEF__LCCM641__NUM_DEVICS, s16DS2482S_DEVICE__Get_Status(), s16DS2482S_DEVICE__Reset(), _strDS2482S::sDevice, sDS2482S, _strDS2482S::sFaultFlags, _strDS2482S::sSearch, _strDS2482S::u8CRC8, vDS2482S_LOWLEVEL__Init(), vFAULTTREE__Init(), and vRM4_DELAYS__Delay_uS().
Referenced by vPWRNODE_BATTTEMP__Init().
void vDS2482S__Process (void)
Process any DS2482 tasks.
The user should call this in their main program loop as fast as possible.
SafeTool Function MD5:
9AFB9D855908D63AE113FC13B71D863D
SafeTool Function ID:
LCCM641R0.FILE.000.FUNC.002
Variable Documentation
struct _strDS2482S sDS2482S
Referenced by s16DS2482S_SEARCH__Search(), s16DS2482S_SEARCH__SearchFirstDevice(), s16DS2482S_SEARCH__SearchNextDevice(), and vDS2482S__Init().