LFW513 (RLOOP - POWER NODE): DS18B20__DELAYS
DS18B20__DELAYS
MULTICORE » DS18B20
Functions
void vDS18B20_DELAYS__Delay_uS (Luint32 u32Value)
microsecond delay.
void vDS18B20_DELAYS__Delay_mS (Luint32 u32Value)
millisecond delay
Detailed Description
Function Documentation
void vDS18B20_DELAYS__Delay_mS (Luint32 u32Value)
millisecond delay
Parameters
[in] u32Value Delay value
SafeTool Function MD5:
7C43316DD186DFA88546E51F8F144552
SafeTool Function ID:
LCCM644R0.FILE.008.FUNC.002
References vRM4_DELAYS__Delay_mS().
Referenced by s16DS18B20_SCRATCH__Write(), s16DS18B20_TEMP__All_Request(), and s16DS18B20_TEMP__Request().
void vDS18B20_DELAYS__Delay_uS (Luint32 u32Value)
microsecond delay.
Parameters
[in] u32Value Delay Value
SafeTool Function MD5:
49782D0D32EAE7FA4DE6100C744D6566
SafeTool Function ID:
LCCM644R0.FILE.008.FUNC.001
References vRM4_DELAYS__Delay_uS().