LFW513 (RLOOP - POWER NODE): COMMON_CODE/RM4/LCCM126__RM4__CAN/TX/rm4_can__tx.c File Reference
rm4_can__tx.c File Reference
#include "../rm4_can.h"
Functions
Lint16 s16RM4_CAN_TX__TxMessage (RM4_CAN__CHANNEL_E eChannel, const Luint8 *cpu8Data, Luint8 u8NodeID, Luint16 u16MessageID)
Transmit a message out the can port Attempts to transmit a message using the transmit worker
Luint32 u32RM4_CAN_TX__IsTxMessagePending (RM4_CAN__CHANNEL_E eChannel)
Checks to see if there is a transmission pending.
Lint16 s16RM4_CAN_TX__TxMessage_Worker (RM4_CAN__CHANNEL_E eChannel, const Luint8 *cpu8Data, Luint32 u32MessageID)
Performs the actual transmission of the message.
Luint32 u32RM4_CAN_TX__IsTxMessagePending_Worker (RM4_CAN__CHANNEL_E eChannel)
Checks if a message is pending for transmission in the Message Object.
Function Documentation
Lint16 s16RM4_CAN_TX__TxMessage (RM4_CAN__CHANNEL_E eChannel, const Luint8 * cpu8Data, Luint8 u8NodeID, Luint16 u16MessageID)
Transmit a message out the can port Attempts to transmit a message using the transmit worker
Parameters
[in] u16MessageID Message ID
[in] u8NodeID Node ID
[in] cpu8Data Pointer to tx data buffer
[in] eChannel The CAN channel
Returns
0 = success
-1 = message could not be sent, due to FIFO full or other network error
SafeTool Function MD5:
06137E9A0027A44AD6FB4FCB3A059DF4
SafeTool Function ID:
LCCM126R0.FILE.012.FUNC.001
References s16RM4_CAN_TX__TxMessage_Worker().
Lint16 s16RM4_CAN_TX__TxMessage_Worker (RM4_CAN__CHANNEL_E eChannel, const Luint8 * cpu8Data, Luint32 u32MessageID)
Performs the actual transmission of the message.
Parameters
[in] u32MessageID The ID of the message
[in] cpu8Data Payload Data
[in] eChannel Channel to transmit on
Returns
0 = success
-1 = message pending
-2 = some other error
SafeTool Function MD5:
B31DEA38D4E316EC45E5DEAAF7CA025B
SafeTool Function ID:
LCCM126R0.FILE.012.FUNC.006
References canREG1, canREG2, canREG3, RM48_DCANIFCMD_CHANGE_ARB, RM48_DCANIFCMD_CHANGE_DATA_A, RM48_DCANIFCMD_CHANGE_DATA_B, RM48_DCANIFCMD_CHANGE_MASK, RM48_DCANIFCMD_CHANGE_TX_RQST_RD, RM48_DCANIFCMD_KEEP_CTRL, RM48_DCANIFCMD_KEEP_INT_PEN, RM48_DCANIFCMD_WRITE, and tsRM4_CAN_FUNCTIONS__Get_AvailableWriteInterface().
Referenced by s16RM4_CAN_TX__TxMessage().
Luint32 u32RM4_CAN_TX__IsTxMessagePending (RM4_CAN__CHANNEL_E eChannel)
Checks to see if there is a transmission pending.
Parameters
[in] eChannel The CAN Channel
SafeTool Function MD5:
A6CBCAD2C18DCC4380077D18968C8AA9
SafeTool Function ID:
LCCM126R0.FILE.012.FUNC.002
References u32RM4_CAN_TX__IsTxMessagePending_Worker().
Luint32 u32RM4_CAN_TX__IsTxMessagePending_Worker (RM4_CAN__CHANNEL_E eChannel)
Checks if a message is pending for transmission in the Message Object.
Parameters
[in] u32MessageBox Message Box Index
[in] eChannel CAN Channel
SafeTool Function MD5:
552D88B085CBA7334820244432A22873
SafeTool Function ID:
LCCM126R0.FILE.012.FUNC.007
References canREG1, canREG2, and canREG3.
Referenced by u32RM4_CAN_TX__IsTxMessagePending().