LFW513 (RLOOP - POWER NODE): COMMON_CODE/RM4/LCCM219__RM4__SYSTEM/rm4_system.h File Reference
rm4_system.h File Reference
System header file.
#include <localdef.h>
#include <RM4/LCCM219__RM4__SYSTEM/rm4_system__private.h>
#include <RM4/LCCM223__RM4__periph_central_resource/rm4_pcr.h>
#include <RM4/LCCM222__RM4__pin_mux/rm4_pinmux.h>
#include <RM4/LCCM221__RM4__selftest/rm4_selftest.h>
#include <RM4/LCCM224__RM4__efuse/rm4_efuse.h>
#include <RM4/LCCM225__RM4__vectored_isr_mgr/rm4_vim.h>
#include <RM4/LCCM219__RM4__system/rm4_system__mpu.h>
#include <RM4/LCCM227__RM4__bist/rm4_bist.h>
#include <RM4/LCCM219__RM4__system/rm4_system__pmu.h>
Data Structures
union t_uDfsr
union t_uADfsr
Macros
#define C_LOCALDEF__SYSTEM__VCLK_FREQ_MHZ (C_LOCALDEF__SYSTEM__HCLK_FREQ_MHZ / 2U)
#define C_LOCALDEF__SYSTEM__VCLK2_FREQ_MHZ (C_LOCALDEF__SYSTEM__VCLK_FREQ_MHZ)
#define SYS_PRE1 (SYS_PLL1)
Alias name for RTI1CLK PRE clock source.
#define SYS_PRE2 (SYS_PLL1)
Alias name for RTI2CLK pre clock source.
#define C_RM4SYSTEM__SYS_DOZE_MODE 0x000F3F02U
#define C_RM4SYSTEM__SYS_SNOOZE_MODE 0x000F3F03U
#define C_RM4SYSTEM__SYS_SLEEP_MODE 0x000FFFFFU
#define C_RM4SYSTEM__LPO_TRIM_VALUE (((*(volatile Luint32 *)0xF00801B4U) & 0xFFFF0000U)>>16U)
#define C_RM4SYSTEM__SYS_EXCEPTION (*(volatile Luint32 *)0xFFFFFFE4U)
#define C_RM4SYSTEM__POWERON_RESET 0x8000U
#define C_RM4SYSTEM__OSC_FAILURE_RESET 0x4000U
#define C_RM4SYSTEM__WATCHDOG_RESET 0x2000U
#define C_RM4SYSTEM__ICEPICK_RESET 0x2000U
#define C_RM4SYSTEM__CPU_RESET 0x0020U
#define C_RM4SYSTEM__SW_RESET 0x0010U
#define C_RM4SYSTEM__WATCHDOG_STATUS (*(volatile Luint32 *)0xFFFFFC98U)
#define C_RM4SYSTEM__DEVICE_ID_REV (*(volatile Luint32 *)0xFFFFFFF0U)
Typedefs
typedef enum config_value_type config_value_type_t
config type Type Definition
typedef t_uADfsr t_uAIfsr
Enumerations
enum config_value_type {
InitialValue,
CurrentValue
}
config type definition
enum t_eDfsrFs {
AlignmentFault = 0x0001U,
BackgroundFault = 0x0000U,
PermissionFault = 0x000DU,
DebugEvent = 0x0002U,
SynchronousExternalAbort = 0x0008U,
MemoryAccessSynchronousParityError = 0x0409U,
AsynchronousExternalAbort = 0x0406U,
MemoryAccessAsynchronousParityError = 0x0408U
}
enum t_eADfsrSide {
AXIMaster = 0x00U,
Cache = 0x00U,
ATCM = 0x01U,
BTCM = 0x02U,
Reserved = 0x03U
}
enum systemClockSource {
SYS_OSC = 0U,
SYS_PLL1 = 1U,
SYS_EXTERNAL1 = 3U,
SYS_LPO_LOW = 4U,
SYS_LPO_HIGH = 5U,
SYS_PLL2 = 6U,
SYS_EXTERNAL2 = 7U,
SYS_VCLK = 9U
}
Alias names for clock sources.
Functions
void vRM4_SYSTEM__Init (void)
Init the system.
Luint8 u8RM4_SYSTEM_OSC__Is_OscFail (void)
checks to see if the oscillator has failed.
Luint8 u8RM4_SYSTEM_OSC__Is_PLLFail (void)
Check if the PLL has slipped could be caused by a noisy power supply or loss of filter into the PLL's power supply.
void vRM4_SYSTEM__SetupPLL (void)
Configure PLL control registers and enable PLLs.
void vRM4_SYSTEM__InitPerip (void)
Init the peripherals.
void vRM4_SYSTEM__MapClocks (void)
Map the clock domains.
void vRM4_SYSTEM__SetupFlash (void)
Setup the FLASH memories.
void vRM2_SYSTEM__PowerDown (Luint32 mode)
Power down the system.
void vRM4_SYSTEM__TrimLPO (void)
Set the low power oscillator trim.
void _rm4_system_core__InitRegisters_ (void)
void _rm4_system_core__InitStackPointer_ (void)
Initialize Core stack pointer.
Luint32 _getCPSRValue_ (void)
Get CPSR Value.
void _gotoCPUIdle_ (void)
Take CPU to Idle state.
void _coreEnableIrqVicOffset_ (void)
Enable Irq offset propagation via Vic controller.
void _coreEnableVfp_ (void)
Enable vector floating point unit.
void _coreEnableEventBusExport_ (void)
Enable event bus export for external monitoring modules.
void _coreDisableEventBusExport_ (void)
Disable event bus export for external monitoring modules.
void _coreEnableRamEcc_ (void)
Enable external ecc error for RAM odd and even bank.
void _coreDisableRamEcc_ (void)
Disable external ecc error for RAM odd and even bank.
void _coreEnableFlashEcc_ (void)
Enable external ecc error for the Flash.
void _coreDisableFlashEcc_ (void)
Disable external ecc error for the Flash.
Luint32 _coreGetDataFault_ (void)
Get core data fault status register.
void _coreClearDataFault_ (void)
Clear core data fault status register.
Luint32 _coreGetInstructionFault_ (void)
Get core instruction fault status register.
void _coreClearInstructionFault_ (void)
Clear core instruction fault status register.
Luint32 _coreGetDataFaultAddress_ (void)
Get core data fault address register.
void _coreClearDataFaultAddress_ (void)
Clear core data fault address register.
Luint32 _coreGetInstructionFaultAddress_ (void)
Get core instruction fault address register.
void _coreClearInstructionFaultAddress_ (void)
Clear core instruction fault address register.
Luint32 _coreGetAuxiliaryDataFault_ (void)
Get core auxiliary data fault status register.
void _coreClearAuxiliaryDataFault_ (void)
Clear core auxiliary data fault status register.
Luint32 _coreGetAuxiliaryInstructionFault_ (void)
Get core auxiliary instruction fault status register.
void _coreClearAuxiliaryInstructionFault_ (void)
Clear core auxiliary instruction fault status register.
void _disable_interrupt_ (void)
Disable IRQ and FIQ Interrupt u32Mode in CPSR register.
void _disable_IRQ_interrupt_ (void)
Disable IRQ Interrupt u32Mode in CPSR register.
void _disable_FIQ_interrupt_ (void)
Disable FIQ Interrupt u32Mode in CPSR register.
void _enable_interrupt_ (void)
Enable IRQ and FIQ Interrupt u32Mode in CPSR register.
void _rm4_system_core__esmCcmErrorsClear_ (void)
void _errata_CORTEXR4_66_ (void)
Work Around for Errata CORTEX-R4#66.
void _errata_CORTEXR4_57_ (void)
Work Around for Errata CORTEX-R4#57.
void custom_dabort (void)
Custom Data abort routine for the application.
void vRM4_SYSTEM__After_STC (void)
Detailed Description
System header file.
Author
Lachlan Grogan
Copyright
This file contains proprietary and confidential information of the Lockie Group of companies, including Lockie Innovation Pty. Ltd (ACN 123 529 064) and Lockie Safety Systems Pty. Ltd (ACN 132 340 571). This code may be distributed under a license from the Lockie Group of companies, and may be used, copied and/or disclosed only pursuant to the terms of that license agreement. This copyright notice must be retained as part of this file at all times.
This file is copyright Lockie Innovation Pty Ltd 2003-2012, All Rights Reserved.
This file is copyright Lockie Safety Systems Pty Ltd 2008-2012, All Rights Reserved.
SafeTool FileID:
LCCM219R0.FILE.002
Macro Definition Documentation
#define C_LOCALDEF__SYSTEM__VCLK2_FREQ_MHZ (C_LOCALDEF__SYSTEM__VCLK_FREQ_MHZ)
#define C_LOCALDEF__SYSTEM__VCLK_FREQ_MHZ (C_LOCALDEF__SYSTEM__HCLK_FREQ_MHZ / 2U)
#define C_RM4SYSTEM__CPU_RESET 0x0020U
Referenced by _c_int00().
#define C_RM4SYSTEM__DEVICE_ID_REV (*(volatile Luint32 *)0xFFFFFFF0U)
Referenced by _c_int00().
#define C_RM4SYSTEM__ICEPICK_RESET 0x2000U
Referenced by _c_int00().
#define C_RM4SYSTEM__LPO_TRIM_VALUE (((*(volatile Luint32 *)0xF00801B4U) & 0xFFFF0000U)>>16U)
Referenced by vRM4_SYSTEM__TrimLPO().
#define C_RM4SYSTEM__OSC_FAILURE_RESET 0x4000U
Referenced by _c_int00().
#define C_RM4SYSTEM__POWERON_RESET 0x8000U
Referenced by _c_int00().
#define C_RM4SYSTEM__SW_RESET 0x0010U
Referenced by _c_int00().
#define C_RM4SYSTEM__SYS_DOZE_MODE 0x000F3F02U
#define C_RM4SYSTEM__SYS_EXCEPTION (*(volatile Luint32 *)0xFFFFFFE4U)
Referenced by _c_int00().
#define C_RM4SYSTEM__SYS_SLEEP_MODE 0x000FFFFFU
#define C_RM4SYSTEM__SYS_SNOOZE_MODE 0x000F3F03U
#define C_RM4SYSTEM__WATCHDOG_RESET 0x2000U
Referenced by _c_int00().
#define C_RM4SYSTEM__WATCHDOG_STATUS (*(volatile Luint32 *)0xFFFFFC98U)
Referenced by _c_int00().
#define SYS_PRE1 (SYS_PLL1)
Alias name for RTI1CLK PRE clock source.
This is an alias name for the RTI1CLK pre clock source. This can be either:
Oscillator
Pll
32 kHz Oscillator
External
Low Power Oscillator Low
Low Power Oscillator High
Flexray Pll
Referenced by vRM4_SYSTEM__MapClocks().
#define SYS_PRE2 (SYS_PLL1)
Alias name for RTI2CLK pre clock source.
This is an alias name for the RTI2CLK pre clock source. This can be either:
Oscillator
Pll
32 kHz Oscillator
External
Low Power Oscillator Low
Low Power Oscillator High
Flexray Pll
Typedef Documentation
config_value_type_t
config type Type Definition
This type is used to specify the Initial and Current value.
typedef t_uADfsr t_uAIfsr
Enumeration Type Documentation
enum config_value_type
config type definition
Enumerator
InitialValue
CurrentValue
enum systemClockSource
Alias names for clock sources.
This enumeration is used to provide alias names for the clock sources:
Oscillator
Pll1
External1
Low Power Oscillator Low
Low Power Oscillator High
PLL2
External2
Synchronous VCLK1
Enumerator
SYS_OSC
Alias for oscillator clock Source.
SYS_PLL1
Alias for Pll1 clock Source.
SYS_EXTERNAL1
Alias for external clock Source.
SYS_LPO_LOW
Alias for low power oscillator low clock Source.
SYS_LPO_HIGH
Alias for low power oscillator high clock Source.
SYS_PLL2
Alias for Pll2 clock Source.
SYS_EXTERNAL2
Alias for external 2 clock Source.
SYS_VCLK
Alias for synchronous VCLK1 clock Source.
enum t_eADfsrSide
Enumerator
AXIMaster
Cache
ATCM
BTCM
Reserved
enum t_eDfsrFs
Enumerator
AlignmentFault
BackgroundFault
PermissionFault
DebugEvent
SynchronousExternalAbort
MemoryAccessSynchronousParityError
AsynchronousExternalAbort
MemoryAccessAsynchronousParityError
Function Documentation
void _coreClearAuxiliaryDataFault_ (void)
Clear core auxiliary data fault status register.
void _coreClearAuxiliaryInstructionFault_ (void)
Clear core auxiliary instruction fault status register.
void _coreClearDataFault_ (void)
Clear core data fault status register.
void _coreClearDataFaultAddress_ (void)
Clear core data fault address register.
void _coreClearInstructionFault_ (void)
Clear core instruction fault status register.
void _coreClearInstructionFaultAddress_ (void)
Clear core instruction fault address register.
void _coreDisableEventBusExport_ (void)
Disable event bus export for external monitoring modules.
This function disables event bus exports to external monitoring modules like tightly coupled RAM wrapper, Flash wrapper and error signaling module.
void _coreDisableFlashEcc_ (void)
Disable external ecc error for the Flash.
void _coreDisableRamEcc_ (void)
Disable external ecc error for RAM odd and even bank.
Referenced by vRM4_SYSTEM__After_STC().
void _coreEnableEventBusExport_ (void)
Enable event bus export for external monitoring modules.
Note
It is required to enable event bus export to process ecc issues.
This function enables event bus exports to external monitoring modules like tightly coupled RAM wrapper, Flash wrapper and error signaling module.
Referenced by _c_int00().
void _coreEnableFlashEcc_ (void)
Enable external ecc error for the Flash.
Note
It is required to enable event bus export to process ecc issues.
void _coreEnableIrqVicOffset_ (void)
Enable Irq offset propagation via Vic controller.
Referenced by vRM4_SYSTEM__After_STC().
void _coreEnableRamEcc_ (void)
Enable external ecc error for RAM odd and even bank.
Note
It is required to enable event bus export to process ecc issues.
Referenced by vRM4_SYSTEM__After_STC().
void _coreEnableVfp_ (void)
Enable vector floating point unit.
Luint32 _coreGetAuxiliaryDataFault_ (void)
Get core auxiliary data fault status register.
Returns
The function will return the auxiliary data fault status register value:
bit [13..5]:
Index value for access giving error
bit [21]:
0: Unrecoverable error
1: Recoverable error
bit [23..22]:
0: Side cache
1: Side ATCM (Flash)
2: Side BTCM (RAM)
3: Reserved
bit [27..24]:
Cache way or way in which error occurred
Luint32 _coreGetAuxiliaryInstructionFault_ (void)
Get core auxiliary instruction fault status register.
Returns
The function will return the auxiliary instruction fault status register value:
bit [13..5]:
Index value for access giving error
bit [21]:
0: Unrecoverable error
1: Recoverable error
bit [23..22]:
0: Side cache
1: Side ATCM (Flash)
2: Side BTCM (RAM)
3: Reserved
bit [27..24]:
Cache way or way in which error occurred
Luint32 _coreGetDataFault_ (void)
Get core data fault status register.
Returns
The function will return the data fault status register value:
bit [10,3..0]:
0b00001: Alignment -> address is valid
0b00000: Background -> address is valid
0b01101: Permission -> address is valid
0b01000: Precise External Abort -> address is valid
0b10110: Imprecise External Abort -> address is unpredictable
0b11001: Precise ECC Error -> address is valid
0b11000: Imprecise ECC Error -> address is unpredictable
0b00010: Debug -> address is unchanged
bit [11]:
0: Read
1: Write
bit [12]:
0: AXI Decode Error (DECERR)
1: AXI Slave Error (SLVERR)
Referenced by _data(), and custom_dabort().
Luint32 _coreGetDataFaultAddress_ (void)
Get core data fault address register.
Returns
The function will return the data fault address:
Referenced by _data().
Luint32 _coreGetInstructionFault_ (void)
Get core instruction fault status register.
Returns
The function will return the instruction fault status register value:
bit [10,3..0]:
0b00001: Alignment -> address is valid
0b00000: Background -> address is valid
0b01101: Permission -> address is valid
0b01000: Precise External Abort -> address is valid
0b10110: Imprecise External Abort -> address is unpredictable
0b11001: Precise ECC Error -> address is valid
0b11000: Imprecise ECC Error -> address is unpredictable
0b00010: Debug -> address is unchanged
bit [12]:
0: AXI Decode Error (DECERR)
1: AXI Slave Error (SLVERR)
Luint32 _coreGetInstructionFaultAddress_ (void)
Get core instruction fault address register.
Returns
The function will return the instruction fault address:
void _disable_FIQ_interrupt_ (void)
Disable FIQ Interrupt u32Mode in CPSR register.
This function disables IRQ Interrupt u32Mode in CPSR register.
void _disable_interrupt_ (void)
Disable IRQ and FIQ Interrupt u32Mode in CPSR register.
This function disables IRQ and FIQ Interrupt u32Mode in CPSR register.
void _disable_IRQ_interrupt_ (void)
Disable IRQ Interrupt u32Mode in CPSR register.
This function disables IRQ Interrupt u32Mode in CPSR register.
void _enable_interrupt_ (void)
Enable IRQ and FIQ Interrupt u32Mode in CPSR register.
This function Enables IRQ and FIQ Interrupt u32Mode in CPSR register. User must call this function to enable Interrupts in non-OS environments.
Referenced by vRM4_SYSTEM__Init().
void _errata_CORTEXR4_57_ (void)
Work Around for Errata CORTEX-R4#57.
Disable out-of-order single-precision floating point multiply-accumulate instruction completion.
Referenced by _c_int00().
void _errata_CORTEXR4_66_ (void)
Work Around for Errata CORTEX-R4#66.
This function Disable out-of-order completion for divide instructions in Auxiliary Control register.
Referenced by _c_int00().
void _getCPSRValue_ (void)
Get CPSR Value.
void _gotoCPUIdle_ (void)
Take CPU to Idle state.
Referenced by vRM4_SELFTEST__CPU_Test(), and vRM4_SELFTEST__STC_Check().
void _rm4_system_core__esmCcmErrorsClear_ (void)
Referenced by _c_int00().
void _rm4_system_core__InitRegisters_ (void)
Referenced by _c_int00().
void _rm4_system_core__InitStackPointer_ (void)
Initialize Core stack pointer.
Referenced by _c_int00().