LFW513 (RLOOP - POWER NODE): COMMON_CODE/RM4/LCCM126__RM4__CAN/rm4_can.h File Reference
rm4_can.h File Reference
RM4 CAN, main header file.
#include <localdef.h>
#include <rm4/lccm126__rm4__can/rm4_can__private.h>
#include <rm4/lccm126__rm4__can/rm4_can__fault_flags.h>
#include <rm4/lccm126__rm4__can/rm4_can__semistaticdef.h>
#include <rm4/lccm126__rm4__can/rm4_can__staticdef.h>
#include <multicore/lccm284__multicore__fault_tree/fault_tree__public.h>
Data Structures
struct _strRM4CAN
Enumerations
enum RM4_CAN__PORT_DIRECTION_T {
CAN_PORT__INPUT = 0U,
CAN_PORT__OUTPUT = 1U
}
For the can ports.
enum RM4_CAN__CHANNEL_E { CAN_CHANNEL_DUMMY = 3U }
enum RM4_CAN__MSGOBJ_DIRECTION_E {
MSGOBJ_DIR__TRANSMIT = 0x20000000U,
MSGOBJ_DIR__RECEIVE = 0x00000000U
}
Functions
void vRM4_CAN__Init (RM4_CAN__CHANNEL_E eChannel, Luint32 u32BitRate, Luint32 u32SJW, Luint32 u32PROP, Luint32 u32PhSeg1, Luint32 u32PhSeg2)
Init the CAN channel Call this to init the can channel with the correct timing information.
void vRM4_CAN__Process (RM4_CAN__CHANNEL_E eChannel)
Process a particular channel, Should be called from main program loop as fast as possible.
tsCANInterface * tsRM4_CAN_FUNCTIONS__Get_AvailableWriteInterface (RM4_CAN__CHANNEL_E eChannel)
Finds an available write interface for the.
void vRM4_CAN_FUNCTIONS__Configure_MessageObject (RM4_CAN__CHANNEL_E eChannel, Luint32 u32MessageObjectNumber, RM4_CAN__MSGOBJ_DIRECTION_E eDirection, Luint32 u32SingleFrame, Luint32 u32IDEMask, Luint32 u32IDE)
Function to configure the required message objects.
Lint16 s16RM4_CAN_FUNCTIONS__Configure_FIFO (RM4_CAN__CHANNEL_E eChannel, Luint8 u8FirstObject, Luint8 u8Size)
#brief Configures a CAN's FIFO for Rx
Luint32 u32RM4_CAN__Get_FaultFlags (void)
Return the module based fault flags.
Lint16 s16RM4_CAN_TX__TxMessage (RM4_CAN__CHANNEL_E eChannel, const Luint8 *cpu8Data, Luint8 u8NodeID, Luint16 u16MessageID)
Transmit a message out the can port Attempts to transmit a message using the transmit worker
Luint32 u32RM4_CAN_TX__IsTxMessagePending (RM4_CAN__CHANNEL_E eChannel)
Checks to see if there is a transmission pending.
Lint16 s16RM4_CAN_TX__TxMessage_Worker (RM4_CAN__CHANNEL_E eChannel, const Luint8 *cpu8Data, Luint32 u32MessageID)
Performs the actual transmission of the message.
Luint32 u32RM4_CAN_TX__IsTxMessagePending_Worker (RM4_CAN__CHANNEL_E eChannel)
Checks if a message is pending for transmission in the Message Object.
Luint8 u8RM4_CAN_RX__ProcessFIFOs (RM4_CAN__CHANNEL_E eChannel)
Process the hardware and software FIFO's Returns the number of messages extracted from hardware FIFO into the software FIFO.
Luint8 u8RM4_CAN_RX__Is_MessageAvailable (RM4_CAN__CHANNEL_E eChannel)
Is a Rx message avail? Returns true if a RX message is available for us to get.
void vRM4_CAN_RX__RxMessage (RM4_CAN__CHANNEL_E eChannel, Luint8 *pu8NodeID, Luint16 *pu16MessageID, Luint8 *pu8Buffer, Luint32 *pu32TimeStamp)
Rx a message from the CAN Software FIFO's If a new msg is avail, get the message from the FIFO's.
Luint32 u32RM4_CAN_RX__IsRxMessageArrived (RM4_CAN__CHANNEL_E eChannel, Luint32 u32MessageBox)
Checks if a Message has arrived to a specific Message Object The bit corresponding to the MessageBox NewDat.
Luint8 u8RM4_CAN_RX__Is_HardwareFIFOempty (RM4_CAN__CHANNEL_E eChannel)
Is the hardware FIFO empty? Checks if the hardware FIFO is empty.
Luint8 u8RM4_CAN_RX__ExtractAllMessagesFromHardwareFIFO (RM4_CAN__CHANNEL_E eChannel, RM4_CAN__SWFIFO_T *pFIFO)
Empties the FIFO to a message buffer Prerequisite the function should be called when there is something in the FIFO Must be called only if at least one message is waiting to be received.
Lint16 s16RM4_CAN_RX__RxMessage_Worker (RM4_CAN__CHANNEL_E eChannel, Luint32 u32MessageBox, Luint8 *pu8Data, Luint32 *pu32MessageID)
Reads a message from the Message Object.
Luint8 u8RM4_CAN_ERROR__Get_TxErrorCount (RM4_CAN__CHANNEL_E eChannel)
Return the tranmsit error count.
Luint8 u8RM4_CAN_ERROR__Get_RxErrorCount (RM4_CAN__CHANNEL_E eChannel)
Get the Rx error count.
Luint32 u32RM4_CAN_ERROR__Get_LastError (RM4_CAN__CHANNEL_E eChannel)
Gets last RX/TX-Error of CAN message traffic.
Luint32 u32RM4_CAN_ERROR__Get_ErrorLevel (RM4_CAN__CHANNEL_E eChannel)
Gets error level of a CAN node.
void vRM4_CAN_ERROR__Enable_ErrorNotification (RM4_CAN__CHANNEL_E eChannel)
Enable error notification This function will enable the notification for the reaching the error levels warning, passive and bus off.
void vRM4_CAN_ERROR__Disable_ErrorNotification (RM4_CAN__CHANNEL_E eChannel)
Disable error notifications This function will disable the notification for the reaching the error levels warning, passive and bus off.
Luint32 u32RM4_CAN_CONFIG__IsMessageBoxValid (RM4_CAN__CHANNEL_E eChannel, Luint32 u32MessageBox)
Checks if message box is valid Checks to see if the message box is valid for operation, returns 0 if flag not set otherwise will return the validation flag itself.
void vRM4_CAN_PORTS__Set_IODirection (RM4_CAN__CHANNEL_E eChannel, RM4_CAN__PORT_DIRECTION_T eTx, RM4_CAN__PORT_DIRECTION_T eRx)
Sets our IO Port direction.
void vRM4_CAN_PORTS__Set_IOPort (RM4_CAN__CHANNEL_E eChannel, Luint32 u32TxValue, Luint32 u32RxValue)
Write a port value.
Luint8 u8RM4_CAN_PORTS__Get_IOPort_Rx (RM4_CAN__CHANNEL_E eChannel)
ToDo.
Luint8 u8RM4_CAN_PORTS__Get_IOPort_Tx (RM4_CAN__CHANNEL_E eChannel)
ToDo.
void vRM4_CAN_SWFIFO__Init (RM4_CAN__SWFIFO_T *pFIFO)
Inits the FIFO.
Lint16 s16RM4_CAN_SWFIFO__Push (RM4_CAN__SWFIFO_T *pFIFO, CANRxMessageBuffer tuMessage)
Push data onto the FIFO Push new CAN data on to the software FIFO.
Lint16 s16RM4_CAN_SWFIFO__Pop (RM4_CAN__SWFIFO_T *pFIFO, CANRxMessageBuffer *pMsg)
POP a message from the fifo and return the message.
void vRM4_CAN_SWFIFO__Get (RM4_CAN__SWFIFO_T *pFIFO, CANRxMessageBuffer *pMsg)
Gets the current message from the FIFO, but does not pop the FIFO.
Luint8 u8RM4_CAN_SWFIFO__Is_Empty (RM4_CAN__SWFIFO_T *pFIFO)
Checks to see if the FIFO is empty.
Detailed Description
RM4 CAN, main header file.
Author
Lachlan Grogan
Copyright
This file contains proprietary and confidential information of the Lockie Group of companies, including Lockie Innovation Pty. Ltd (ACN 123 529 064) and Lockie Safety Systems Pty. Ltd (ACN 132 340 571). This code may be distributed under a license from the Lockie Group of companies, and may be used, copied and/or disclosed only pursuant to the terms of that license agreement. This copyright notice must be retained as part of this file at all times.
This file is copyright Lockie Innovation Pty Ltd 2003-2012, All Rights Reserved.
This file is copyright Lockie Safety Systems Pty Ltd 2008-2012, All Rights Reserved.
SafeTool FileID:
LCCM126R0.FILE.001
Enumeration Type Documentation
enum RM4_CAN__CHANNEL_E
Enumerator
CAN_CHANNEL_DUMMY
enum RM4_CAN__MSGOBJ_DIRECTION_E
Enumerator
MSGOBJ_DIR__TRANSMIT
MSGOBJ_DIR__RECEIVE
enum RM4_CAN__PORT_DIRECTION_T
For the can ports.
Enumerator
CAN_PORT__INPUT
CAN_PORT__OUTPUT
Function Documentation
Lint16 s16RM4_CAN_FUNCTIONS__Configure_FIFO (RM4_CAN__CHANNEL_E eChannel, Luint8 u8FirstObject, Luint8 u8Size)
#brief Configures a CAN's FIFO for Rx
Parameters
[in] u8Size FIFO Size
[in] u8FirstObject ## Desc ##
[in] eChannel The CAN device channel
Returns
0 = success, FIFO created successfull
-1 = FIFO Size too big to fit in hardware
-2 = First fifo obj out of range
-3 = FIFO out of range
SafeTool Function MD5:
80862E620E2644609686F5835E5F75C8
SafeTool Function ID:
LCCM126R0.FILE.004.FUNC.002
References MSGOBJ_DIR__RECEIVE, RM48_DCANIFMCTL_MULTI_FRAME, RM48_DCANIFMCTL_SINGLE_FRAME, RM48L950_CAN_NUMBER_OF_MSG_OBJ_IN_HARDWARE, and vRM4_CAN_FUNCTIONS__Configure_MessageObject().
Referenced by vRM4_CAN__Init().
Lint16 s16RM4_CAN_RX__RxMessage_Worker (RM4_CAN__CHANNEL_E eChannel, Luint32 u32MessageBox, Luint8 * pu8Data, Luint32 * pu32MessageID)
Reads a message from the Message Object.
Parameters
[out] pu32MessageID Pointer to hold the message ID
[out] pu8Data Pointer to a buffer to hold the data
[in] u32MessageBox The message box index
[in] eChannel The can Channel
Returns
0 = success, there is data to read
-1 = No data (message was written to the message object)
-2 = Lost message, msg was read, but got lost
-3 = Out of range DLC
SafeTool Function MD5:
8F2C0CD1ECC1671C96F0F1B6CA892CD1
SafeTool Function ID:
LCCM126R0.FILE.009.FUNC.006
References C_LCCM126__FAULT_INDEX__00, canREG1, canREG2, canREG3, RM48_DCANIFCMD_CHANGE_ARB, RM48_DCANIFCMD_CHANGE_CTRL, RM48_DCANIFCMD_CHANGE_DATA_A, RM48_DCANIFCMD_CHANGE_DATA_B, RM48_DCANIFCMD_CHANGE_TX_RQST_RD, RM48_DCANIFCMD_KEEP_INT_PEN, RM48_DCANIFCMD_KEEP_MASK, RM48_DCANIFCMD_READ, _strRM4CAN::sFaultFlags, sRM4CAN, tsRM4_CAN_FUNCTIONS__Get_AvailableWriteInterface(), and vFAULTTREE__Set_Flag().
Referenced by u8RM4_CAN_RX__ExtractAllMessagesFromHardwareFIFO().
Lint16 s16RM4_CAN_SWFIFO__Pop (RM4_CAN__SWFIFO_T * pCANFIFO, CANRxMessageBuffer * pMsg)
POP a message from the fifo and return the message.
Parameters
[in] * ## Desc ##
SafeTool Function MD5:
3B54C1A9247A218D4F16A8A4FCB86FC7
SafeTool Function ID:
LCCM126R0.FILE.007.FUNC.003
References RM4_CAN__SWFIFO_T::tuCANMessageBuffer, RM4_CAN__SWFIFO_T::u8FIFO_Empty, RM4_CAN__SWFIFO_T::u8FIFO_FillLevel, RM4_CAN__SWFIFO_T::u8FIFO_Full, RM4_CAN__SWFIFO_T::u8FIFO_ReadPosition, and RM4_CAN__SWFIFO_T::u8FIFO_WritePosition.
Referenced by vRM4_CAN_RX__RxMessage().
Lint16 s16RM4_CAN_SWFIFO__Push (RM4_CAN__SWFIFO_T * pCANFIFO, CANRxMessageBuffer tuMessage)
Push data onto the FIFO Push new CAN data on to the software FIFO.
Parameters
[in] tuMessage ## Desc ##
[in] pCANFIFO Pointer to FIFO
SafeTool Function MD5:
A8106A2ABADB553D4F704D9775A19CF6
SafeTool Function ID:
LCCM126R0.FILE.007.FUNC.002
References RM4_CAN__SWFIFO_T::tuCANMessageBuffer, RM4_CAN__SWFIFO_T::u8FIFO_Empty, RM4_CAN__SWFIFO_T::u8FIFO_FillLevel, RM4_CAN__SWFIFO_T::u8FIFO_Full, and RM4_CAN__SWFIFO_T::u8FIFO_WritePosition.
Referenced by u8RM4_CAN_RX__ExtractAllMessagesFromHardwareFIFO().
Lint16 s16RM4_CAN_TX__TxMessage (RM4_CAN__CHANNEL_E eChannel, const Luint8 * cpu8Data, Luint8 u8NodeID, Luint16 u16MessageID)
Transmit a message out the can port Attempts to transmit a message using the transmit worker
Parameters
[in] u16MessageID Message ID
[in] u8NodeID Node ID
[in] cpu8Data Pointer to tx data buffer
[in] eChannel The CAN channel
Returns
0 = success
-1 = message could not be sent, due to FIFO full or other network error
SafeTool Function MD5:
06137E9A0027A44AD6FB4FCB3A059DF4
SafeTool Function ID:
LCCM126R0.FILE.012.FUNC.001
References s16RM4_CAN_TX__TxMessage_Worker().
Lint16 s16RM4_CAN_TX__TxMessage_Worker (RM4_CAN__CHANNEL_E eChannel, const Luint8 * cpu8Data, Luint32 u32MessageID)
Performs the actual transmission of the message.
Parameters
[in] u32MessageID The ID of the message
[in] cpu8Data Payload Data
[in] eChannel Channel to transmit on
Returns
0 = success
-1 = message pending
-2 = some other error
SafeTool Function MD5:
B31DEA38D4E316EC45E5DEAAF7CA025B
SafeTool Function ID:
LCCM126R0.FILE.012.FUNC.006
References canREG1, canREG2, canREG3, RM48_DCANIFCMD_CHANGE_ARB, RM48_DCANIFCMD_CHANGE_DATA_A, RM48_DCANIFCMD_CHANGE_DATA_B, RM48_DCANIFCMD_CHANGE_MASK, RM48_DCANIFCMD_CHANGE_TX_RQST_RD, RM48_DCANIFCMD_KEEP_CTRL, RM48_DCANIFCMD_KEEP_INT_PEN, RM48_DCANIFCMD_WRITE, and tsRM4_CAN_FUNCTIONS__Get_AvailableWriteInterface().
Referenced by s16RM4_CAN_TX__TxMessage().
tsCANInterface* tsRM4_CAN_FUNCTIONS__Get_AvailableWriteInterface (RM4_CAN__CHANNEL_E eChannel)
Finds an available write interface for the.
Parameters
[in] eChannel The CAN channel to use
SafeTool Function MD5:
24605716C83612BDBF28C5C60455B016
SafeTool Function ID:
LCCM126R0.FILE.004.FUNC.001
References C_LCCM126__FAULT_INDEX__00, C_RM4_CAN__IF1_OFFSET, C_RM4_CAN__IF2_OFFSET, canREG1, canREG2, canREG3, _strRM4CAN::sFaultFlags, sRM4CAN, and vFAULTTREE__Set_Flag().
Referenced by s16RM4_CAN_RX__RxMessage_Worker(), s16RM4_CAN_TX__TxMessage_Worker(), and vRM4_CAN_FUNCTIONS__Configure_MessageObject().
Luint32 u32RM4_CAN__Get_FaultFlags (void)
Return the module based fault flags.
Returns
The fault flags.
SafeTool Function MD5:
7FC5E9C6528FF6C36C22C63F5B745EB5
SafeTool Function ID:
LCCM126R0.FILE.015.FUNC.003
References _strRM4CAN::sFaultFlags, sRM4CAN, and FAULT_TREE__PUBLIC_T::u32Flags.
Luint32 u32RM4_CAN_CONFIG__IsMessageBoxValid (RM4_CAN__CHANNEL_E eChannel, Luint32 u32MessageBox)
Checks if message box is valid Checks to see if the message box is valid for operation, returns 0 if flag not set otherwise will return the validation flag itself.
Parameters
[in] eChannel The CAN device channel
[in] u32MessageBox The message box index
Returns
Flags
SafeTool Function MD5:
F76720D6395BC55160B02BE827D4B349
SafeTool Function ID:
LCCM126R0.FILE.002.FUNC.001
References canREG1, canREG2, and canREG3.
Luint32 u32RM4_CAN_ERROR__Get_ErrorLevel (RM4_CAN__CHANNEL_E eChannel)
Gets error level of a CAN node.
This function returns the current error level of a CAN node. : : canLEVEL_ACTIVE [0x00U): When RX- and TX error counters are below 96 : canLEVEL_WARNING [0x40): When RX- or TX error counter are between 96 and 127 : canLEVEL_PASSIVE [0x20): When RX- or TX error counter are between 128 and 255 : canLEVEL_BUS_OFF [0x80): When RX- or TX error counter are above 255
Parameters
[in] eChannel The CAN controller channel
SafeTool Function MD5:
48965993FFC0E5153AEBC5733B884E74
SafeTool Function ID:
LCCM126R0.FILE.003.FUNC.002
References C_LCCM126__FAULT_INDEX__00, canREG1, canREG2, canREG3, _strRM4CAN::sFaultFlags, sRM4CAN, and vFAULTTREE__Set_Flag().
Luint32 u32RM4_CAN_ERROR__Get_LastError (RM4_CAN__CHANNEL_E eChannel)
Gets last RX/TX-Error of CAN message traffic.
The function will return: : 0 is flag not set otherwise will return the validation flag itself. : canERROR_OK [0): When no CAN error occured : canERROR_STUFF [1): When a stuff error occured on RX message : canERROR_FORMAT [2): When a form/format error occured on RX message : canERROR_ACKNOWLEDGE [3): When a TX message wasn't acknowledged : canERROR_BIT1 [4): When a TX message monitored dominant level where recessive is expected : canERROR_BIT0 [5): When a TX message monitored recessive level where dominant is expected : canERROR_CRC [6): When a RX message has wrong CRC value : canERROR_NO [7): When no error occured since last call of this function : The function canInit has to be called before this function can be used
Parameters
[in] eChannel The CAN controller channel
SafeTool Function MD5:
A50E989372E0C4BF67FE0B01BE78FE00
SafeTool Function ID:
LCCM126R0.FILE.003.FUNC.001
References C_LCCM126__FAULT_INDEX__00, canREG1, canREG2, canREG3, _strRM4CAN::sFaultFlags, sRM4CAN, and vFAULTTREE__Set_Flag().
Luint32 u32RM4_CAN_RX__IsRxMessageArrived (RM4_CAN__CHANNEL_E eChannel, Luint32 u32MessageBox)
Checks if a Message has arrived to a specific Message Object The bit corresponding to the MessageBox NewDat.
Datasheet: 23.17.11 New Data X Register (DCAN NWDAT X) With the New Data X Register, the CPU can detect if one or more bits in the different New Data Registers are set. Each register bit represents a group of eight message objects. If at least on of the NewDat bits of these message objects are set, the corresponding bit in the New Data X Register will be set.
Parameters
[in] eChannel The CAN channel
Returns
1 = Yes
0 = No
SafeTool Function MD5:
DF686749182C1B2C35F3EBBC1C9EC81E
SafeTool Function ID:
LCCM126R0.FILE.009.FUNC.007
References C_LCCM126__FAULT_INDEX__00, canREG1, canREG2, canREG3, _strRM4CAN::sFaultFlags, sRM4CAN, and vFAULTTREE__Set_Flag().
Referenced by u8RM4_CAN_RX__ExtractAllMessagesFromHardwareFIFO(), and u8RM4_CAN_RX__Is_HardwareFIFOempty().
Luint32 u32RM4_CAN_TX__IsTxMessagePending (RM4_CAN__CHANNEL_E eChannel)
Checks to see if there is a transmission pending.
Parameters
[in] eChannel The CAN Channel
SafeTool Function MD5:
A6CBCAD2C18DCC4380077D18968C8AA9
SafeTool Function ID:
LCCM126R0.FILE.012.FUNC.002
References u32RM4_CAN_TX__IsTxMessagePending_Worker().
Luint32 u32RM4_CAN_TX__IsTxMessagePending_Worker (RM4_CAN__CHANNEL_E eChannel)
Checks if a message is pending for transmission in the Message Object.
Parameters
[in] u32MessageBox Message Box Index
[in] eChannel CAN Channel
SafeTool Function MD5:
552D88B085CBA7334820244432A22873
SafeTool Function ID:
LCCM126R0.FILE.012.FUNC.007
References canREG1, canREG2, and canREG3.
Referenced by u32RM4_CAN_TX__IsTxMessagePending().
Luint8 u8RM4_CAN_ERROR__Get_RxErrorCount (RM4_CAN__CHANNEL_E eChannel)
Get the Rx error count.
Parameters
[in] eChannel The channel
Returns
The Rx Error Count
SafeTool Function MD5:
1C00F42F7938A13BB21B71651627A89A
SafeTool Function ID:
LCCM126R0.FILE.003.FUNC.006
References C_LCCM126__FAULT_INDEX__00, canREG1, canREG2, canREG3, _strRM4CAN::sFaultFlags, sRM4CAN, and vFAULTTREE__Set_Flag().
Referenced by vRM4_CAN__Process().
Luint8 u8RM4_CAN_ERROR__Get_TxErrorCount (RM4_CAN__CHANNEL_E eChannel)
Return the tranmsit error count.
Parameters
[in] eChannel The channel
Returns
The error count
SafeTool Function MD5:
504B1ED6F906E65A7F20732A93E12C65
SafeTool Function ID:
LCCM126R0.FILE.003.FUNC.005
References C_LCCM126__FAULT_INDEX__00, canREG1, canREG2, canREG3, _strRM4CAN::sFaultFlags, sRM4CAN, and vFAULTTREE__Set_Flag().
Referenced by vRM4_CAN__Process().
Luint8 u8RM4_CAN_PORTS__Get_IOPort_Rx (RM4_CAN__CHANNEL_E eChannel)
ToDo.
Parameters
[in] eChannel ## Desc ##
SafeTool Function MD5:
056448EE8BE46DFC7E58E158579D0225
SafeTool Function ID:
LCCM126R0.FILE.024.FUNC.025
References canREG1, canREG2, and canREG3.
Luint8 u8RM4_CAN_PORTS__Get_IOPort_Tx (RM4_CAN__CHANNEL_E eChannel)
ToDo.
Parameters
[in] eChannel ## Desc ##
SafeTool Function MD5:
E2DB8A808B21B16929DF93D24D7FDA5B
SafeTool Function ID:
LCCM126R0.FILE.024.FUNC.026
References canREG1, canREG2, and canREG3.
Luint8 u8RM4_CAN_RX__ExtractAllMessagesFromHardwareFIFO (RM4_CAN__CHANNEL_E eChannel, RM4_CAN__SWFIFO_T * pCANFIFO)
Empties the FIFO to a message buffer Prerequisite the function should be called when there is something in the FIFO Must be called only if at least one message is waiting to be received.
Parameters
[in] pCANFIFO Pointer to the FIFO
[in] eChannel The CAN Channel
Returns
The number of messages
SafeTool Function MD5:
27A84A6A7B21E12BF806B83E0F7680A4
SafeTool Function ID:
LCCM126R0.FILE.009.FUNC.005
References s16RM4_CAN_RX__RxMessage_Worker(), s16RM4_CAN_SWFIFO__Push(), CANRxMessageBuffer::sX, CANRxMessageBuffer::u32MsgID, u32RM4_CAN_RX__IsRxMessageArrived(), and CANRxMessageBuffer::u8Data.
Referenced by u8RM4_CAN_RX__ProcessFIFOs().
Luint8 u8RM4_CAN_RX__Is_HardwareFIFOempty (RM4_CAN__CHANNEL_E eChannel)
Is the hardware FIFO empty? Checks if the hardware FIFO is empty.
Parameters
[in] eChannel The CAN Channel
Returns
0 = not empty
1 = empty
SafeTool Function MD5:
8D4C1D4329476A7358B0F5DB5A01F0C0
SafeTool Function ID:
LCCM126R0.FILE.009.FUNC.004
References C_LCCM126__FAULT_INDEX__00, _strRM4CAN::sFaultFlags, sRM4CAN, u32RM4_CAN_RX__IsRxMessageArrived(), and vFAULTTREE__Set_Flag().
Referenced by u8RM4_CAN_RX__ProcessFIFOs().
Luint8 u8RM4_CAN_RX__Is_MessageAvailable (RM4_CAN__CHANNEL_E eChannel)
Is a Rx message avail? Returns true if a RX message is available for us to get.
Parameters
[in] eChannel The can channel
Returns
1 = message is available
0 = no new messages avail
SafeTool Function MD5:
0DC0FF20F9443394D47376F171D87A3F
SafeTool Function ID:
LCCM126R0.FILE.009.FUNC.002
References C_LCCM126__FAULT_INDEX__00, _strRM4CAN::sFaultFlags, sRM4CAN, u8RM4_CAN_SWFIFO__Is_Empty(), and vFAULTTREE__Set_Flag().
Luint8 u8RM4_CAN_RX__ProcessFIFOs (RM4_CAN__CHANNEL_E eChannel)
Process the hardware and software FIFO's Returns the number of messages extracted from hardware FIFO into the software FIFO.
Parameters
[in] eChannel The CAN Channel
Returns
0 = the FIFO is empty
n = some messages were extracted
SafeTool Function MD5:
5169E81DF6C05ABF2F3C1AE84C8C871A
SafeTool Function ID:
LCCM126R0.FILE.009.FUNC.001
References C_LCCM126__FAULT_INDEX__00, _strRM4CAN::sFaultFlags, sRM4CAN, u8RM4_CAN_RX__ExtractAllMessagesFromHardwareFIFO(), u8RM4_CAN_RX__Is_HardwareFIFOempty(), and vFAULTTREE__Set_Flag().
Referenced by vRM4_CAN__Process().
Luint8 u8RM4_CAN_SWFIFO__Is_Empty (RM4_CAN__SWFIFO_T * pCANFIFO)
Checks to see if the FIFO is empty.
Parameters
[in] pCANFIFO Pointer to the can fifo structure
Returns
1 = Empty
0 = Not Empty
SafeTool Function MD5:
B2EBACF9FE6B46DD463434A8146CDA5E
SafeTool Function ID:
LCCM126R0.FILE.007.FUNC.005
References RM4_CAN__SWFIFO_T::u8FIFO_Empty.
Referenced by u8RM4_CAN_RX__Is_MessageAvailable().
void vRM4_CAN__Init (RM4_CAN__CHANNEL_E eChannel, Luint32 u32BitRate, Luint32 u32SJW, Luint32 u32PROP, Luint32 u32PhSeg1, Luint32 u32PhSeg2)
Init the CAN channel Call this to init the can channel with the correct timing information.
Parameters
[in] u32PhSeg2 Phase 2 segment
[in] u32PhSeg1 Phase 1 segment
[in] u32PROP Prop segment
[in] u32SJW Sync Jump Width
[in] u32BitRate Bit rate
[in] eChannel Desired can controller
SafeTool Function MD5:
0A049EEEFB9DF4666A2E7CE67EDA1C2F
SafeTool Function ID:
LCCM126R0.FILE.015.FUNC.001
References C_LCCM126__FAULT_INDEX__00, canREG1, canREG2, MSGOBJ_DIR__TRANSMIT, RM48_DCANCTL_CCE_MASK, RM48_DCANCTL_INIT_MASK, RM48_DCANIFMCTL_SINGLE_FRAME, s16RM4_CAN_FUNCTIONS__Configure_FIFO(), _strRM4CAN::sFaultFlags, sRM4CAN, vFAULTTREE__Set_Flag(), vRM4_CAN_FUNCTIONS__Configure_MessageObject(), and vRM4_CAN_SWFIFO__Init().
void vRM4_CAN__Process (RM4_CAN__CHANNEL_E eChannel)
Process a particular channel, Should be called from main program loop as fast as possible.
Parameters
[in] eChannel The CAN channel
SafeTool Function MD5:
2104F66792B37089AB3C2C78C5DCEC9D
SafeTool Function ID:
LCCM126R0.FILE.015.FUNC.002
References _strRM4CAN::sErrors, sRM4CAN, u8RM4_CAN_ERROR__Get_RxErrorCount(), u8RM4_CAN_ERROR__Get_TxErrorCount(), u8RM4_CAN_RX__ProcessFIFOs(), _strRM4CAN::u8RxErrorCount, and _strRM4CAN::u8TxErrorCount.
void vRM4_CAN_ERROR__Disable_ErrorNotification (RM4_CAN__CHANNEL_E eChannel)
Disable error notifications This function will disable the notification for the reaching the error levels warning, passive and bus off.
Parameters
[in] eChannel The CAN controller channel
SafeTool Function MD5:
C192271C45F04AA134764C4A862C9331
SafeTool Function ID:
LCCM126R0.FILE.003.FUNC.004
References C_LCCM126__FAULT_INDEX__00, canREG1, canREG2, canREG3, _strRM4CAN::sFaultFlags, sRM4CAN, and vFAULTTREE__Set_Flag().
void vRM4_CAN_ERROR__Enable_ErrorNotification (RM4_CAN__CHANNEL_E eChannel)
Enable error notification This function will enable the notification for the reaching the error levels warning, passive and bus off.
Parameters
[in] eChannel The CAN controller channel
SafeTool Function MD5:
97440BD231B80065807E2EF18E396A4C
SafeTool Function ID:
LCCM126R0.FILE.003.FUNC.003
References C_LCCM126__FAULT_INDEX__00, canREG1, canREG2, canREG3, _strRM4CAN::sFaultFlags, sRM4CAN, and vFAULTTREE__Set_Flag().
void vRM4_CAN_FUNCTIONS__Configure_MessageObject (RM4_CAN__CHANNEL_E eChannel, Luint32 u32MessageObjectNumber, RM4_CAN__MSGOBJ_DIRECTION_E eDirection, Luint32 u32SingleFrame, Luint32 u32IDEMask, Luint32 u32SID)
Function to configure the required message objects.
The DCAN Message RAM contains message objects and parity bits for the message objects.
Parameters
[in] u32SID The standard ID for this message object.
[in] u32IDEMask The identifier mask. Any bits which are cleared in this are not used for the id. Therefore a value of 0 indicates a don't care
[in] u32SingleFrame ## Desc ##
[in] eDirection ## Desc ##
[in] u32MessageObjectNumber ## Desc ##
[in] eChannel The CAN Channel
SafeTool Function MD5:
D347AA5E9E3A353C3B8A26B89E750A59
SafeTool Function ID:
LCCM126R0.FILE.004.FUNC.003
References RM48_DCANIFCMD_CHANGE_ARB, RM48_DCANIFCMD_CHANGE_CTRL, RM48_DCANIFCMD_CHANGE_INT_PEN, RM48_DCANIFCMD_CHANGE_MASK, RM48_DCANIFCMD_KEEP_DATA_A, RM48_DCANIFCMD_KEEP_DATA_B, RM48_DCANIFCMD_KEEP_TX_RQST_RD, RM48_DCANIFCMD_WRITE, and tsRM4_CAN_FUNCTIONS__Get_AvailableWriteInterface().
Referenced by s16RM4_CAN_FUNCTIONS__Configure_FIFO(), and vRM4_CAN__Init().
void vRM4_CAN_PORTS__Set_IODirection (RM4_CAN__CHANNEL_E eChannel, RM4_CAN__PORT_DIRECTION_T eTx, RM4_CAN__PORT_DIRECTION_T eRx)
Sets our IO Port direction.
Note
The values of the IO Control registers are only writable if Init bit of CAN Control Register is Cleared. The OD, Func, Dir and Out bits of the CAN TX IO Control register are forced to certain values when Init bit of CAN Control Register is reset (see bit descriptions).
Parameters
[in] u32RxDir RxPin Direction
0 = Input
1 = Output
[in] u32TxDir TxPin Direction
0 = Input
1 = Output
[in] eChannel The CAN Channel
SafeTool Function MD5:
347D6460CD4053D9C1B97DC9BAA8E599
SafeTool Function ID:
LCCM126R0.FILE.002.FUNC.002
References canREG1, canREG2, and canREG3.
void vRM4_CAN_PORTS__Set_IOPort (RM4_CAN__CHANNEL_E eChannel, Luint32 u32TxValue, Luint32 u32RxValue)
Write a port value.
Note
The values of the IO Control registers are only writable if Init bit of CAN Control Register is Cleared. The OD, Func, Dir and Out bits of the CAN TX IO Control register are forced to certain values when Init bit of CAN Control Register is reset (see bit descriptions).
Parameters
[in] u32RxValue The RX pin value
0 = low
1 = High
[in] u32TxValue The Tx pin value 0 = low
1 = High
[in] eChannel The CAN Channel
SafeTool Function MD5:
C4DA92A2B9E67DB48C480B6A3E4C4424
SafeTool Function ID:
LCCM126R0.FILE.002.FUNC.003
References canREG1, and canREG2.
void vRM4_CAN_RX__RxMessage (RM4_CAN__CHANNEL_E eChannel, Luint8 * pu8NodeID, Luint16 * pu16MessageID, Luint8 * pu8Buffer, Luint32 * pu32TimeStamp)
Rx a message from the CAN Software FIFO's If a new msg is avail, get the message from the FIFO's.
Parameters
[in] pu32TimeStamp Time stamp
[in] pu8Buffer Data Buffer
[in] pu16MessageID The message ID
[in] pu8NodeID The nodeID
[in] eChannel The channel
SafeTool Function MD5:
F6063526829ECB318AF70C626231A1E2
SafeTool Function ID:
LCCM126R0.FILE.009.FUNC.003
References C_LCCM126__FAULT_INDEX__00, s16RM4_CAN_SWFIFO__Pop(), _strRM4CAN::sFaultFlags, sRM4CAN, CANRxMessageBuffer::sX, CANRxMessageBuffer::u32MsgID, u32RM4_RTI__Get_FreeClock(), CANRxMessageBuffer::u8Data, and vFAULTTREE__Set_Flag().
void vRM4_CAN_SWFIFO__Get (RM4_CAN__SWFIFO_T * pCANFIFO, CANRxMessageBuffer * pMsg)
Gets the current message from the FIFO, but does not pop the FIFO.
Parameters
[in] * ## Desc ##
SafeTool Function MD5:
01BB1EE1F57B901C469F2E4973BA2BCB
SafeTool Function ID:
LCCM126R0.FILE.007.FUNC.004
References RM4_CAN__SWFIFO_T::tuCANMessageBuffer, and RM4_CAN__SWFIFO_T::u8FIFO_ReadPosition.
void vRM4_CAN_SWFIFO__Init (RM4_CAN__SWFIFO_T * pCANFIFO)
Inits the FIFO.
Parameters
[in] pCANFIFO pointer to the FIFO structure
SafeTool Function MD5:
259D26269665B9A95A3454986144976B
SafeTool Function ID:
LCCM126R0.FILE.007.FUNC.001
References RM4_CAN__SWFIFO_T::u8FIFO_Empty, RM4_CAN__SWFIFO_T::u8FIFO_FillLevel, RM4_CAN__SWFIFO_T::u8FIFO_Full, RM4_CAN__SWFIFO_T::u8FIFO_ReadPosition, and RM4_CAN__SWFIFO_T::u8FIFO_WritePosition.
Referenced by vRM4_CAN__Init().