LFW513 (RLOOP - POWER NODE): COMMON_CODE/RM4/LCCM126__RM4__CAN/RX/rm4_can__rx.c File Reference
rm4_can__rx.c File Reference
#include "../rm4_can.h"
Functions
Luint8 u8RM4_CAN_RX__ProcessFIFOs (RM4_CAN__CHANNEL_E eChannel)
Process the hardware and software FIFO's Returns the number of messages extracted from hardware FIFO into the software FIFO.
Luint8 u8RM4_CAN_RX__Is_MessageAvailable (RM4_CAN__CHANNEL_E eChannel)
Is a Rx message avail? Returns true if a RX message is available for us to get.
void vRM4_CAN_RX__RxMessage (RM4_CAN__CHANNEL_E eChannel, Luint8 *pu8NodeID, Luint16 *pu16MessageID, Luint8 *pu8Buffer, Luint32 *pu32TimeStamp)
Rx a message from the CAN Software FIFO's If a new msg is avail, get the message from the FIFO's.
Luint8 u8RM4_CAN_RX__Is_HardwareFIFOempty (RM4_CAN__CHANNEL_E eChannel)
Is the hardware FIFO empty? Checks if the hardware FIFO is empty.
Luint8 u8RM4_CAN_RX__ExtractAllMessagesFromHardwareFIFO (RM4_CAN__CHANNEL_E eChannel, RM4_CAN__SWFIFO_T *pCANFIFO)
Empties the FIFO to a message buffer Prerequisite the function should be called when there is something in the FIFO Must be called only if at least one message is waiting to be received.
Lint16 s16RM4_CAN_RX__RxMessage_Worker (RM4_CAN__CHANNEL_E eChannel, Luint32 u32MessageBox, Luint8 *pu8Data, Luint32 *pu32MessageID)
Reads a message from the Message Object.
Luint32 u32RM4_CAN_RX__IsRxMessageArrived (RM4_CAN__CHANNEL_E eChannel, Luint32 u32MessageBox)
Checks if a Message has arrived to a specific Message Object The bit corresponding to the MessageBox NewDat.
Variables
struct _strRM4CAN sRM4CAN
Function Documentation
Lint16 s16RM4_CAN_RX__RxMessage_Worker (RM4_CAN__CHANNEL_E eChannel, Luint32 u32MessageBox, Luint8 * pu8Data, Luint32 * pu32MessageID)
Reads a message from the Message Object.
Parameters
[out] pu32MessageID Pointer to hold the message ID
[out] pu8Data Pointer to a buffer to hold the data
[in] u32MessageBox The message box index
[in] eChannel The can Channel
Returns
0 = success, there is data to read
-1 = No data (message was written to the message object)
-2 = Lost message, msg was read, but got lost
-3 = Out of range DLC
SafeTool Function MD5:
8F2C0CD1ECC1671C96F0F1B6CA892CD1
SafeTool Function ID:
LCCM126R0.FILE.009.FUNC.006
References C_LCCM126__FAULT_INDEX__00, canREG1, canREG2, canREG3, RM48_DCANIFCMD_CHANGE_ARB, RM48_DCANIFCMD_CHANGE_CTRL, RM48_DCANIFCMD_CHANGE_DATA_A, RM48_DCANIFCMD_CHANGE_DATA_B, RM48_DCANIFCMD_CHANGE_TX_RQST_RD, RM48_DCANIFCMD_KEEP_INT_PEN, RM48_DCANIFCMD_KEEP_MASK, RM48_DCANIFCMD_READ, _strRM4CAN::sFaultFlags, sRM4CAN, tsRM4_CAN_FUNCTIONS__Get_AvailableWriteInterface(), and vFAULTTREE__Set_Flag().
Referenced by u8RM4_CAN_RX__ExtractAllMessagesFromHardwareFIFO().
Luint32 u32RM4_CAN_RX__IsRxMessageArrived (RM4_CAN__CHANNEL_E eChannel, Luint32 u32MessageBox)
Checks if a Message has arrived to a specific Message Object The bit corresponding to the MessageBox NewDat.
Datasheet: 23.17.11 New Data X Register (DCAN NWDAT X) With the New Data X Register, the CPU can detect if one or more bits in the different New Data Registers are set. Each register bit represents a group of eight message objects. If at least on of the NewDat bits of these message objects are set, the corresponding bit in the New Data X Register will be set.
Parameters
[in] eChannel The CAN channel
Returns
1 = Yes
0 = No
SafeTool Function MD5:
DF686749182C1B2C35F3EBBC1C9EC81E
SafeTool Function ID:
LCCM126R0.FILE.009.FUNC.007
References C_LCCM126__FAULT_INDEX__00, canREG1, canREG2, canREG3, _strRM4CAN::sFaultFlags, sRM4CAN, and vFAULTTREE__Set_Flag().
Referenced by u8RM4_CAN_RX__ExtractAllMessagesFromHardwareFIFO(), and u8RM4_CAN_RX__Is_HardwareFIFOempty().
Luint8 u8RM4_CAN_RX__ExtractAllMessagesFromHardwareFIFO (RM4_CAN__CHANNEL_E eChannel, RM4_CAN__SWFIFO_T * pCANFIFO)
Empties the FIFO to a message buffer Prerequisite the function should be called when there is something in the FIFO Must be called only if at least one message is waiting to be received.
Parameters
[in] pCANFIFO Pointer to the FIFO
[in] eChannel The CAN Channel
Returns
The number of messages
SafeTool Function MD5:
27A84A6A7B21E12BF806B83E0F7680A4
SafeTool Function ID:
LCCM126R0.FILE.009.FUNC.005
References s16RM4_CAN_RX__RxMessage_Worker(), s16RM4_CAN_SWFIFO__Push(), CANRxMessageBuffer::sX, CANRxMessageBuffer::u32MsgID, u32RM4_CAN_RX__IsRxMessageArrived(), and CANRxMessageBuffer::u8Data.
Referenced by u8RM4_CAN_RX__ProcessFIFOs().
Luint8 u8RM4_CAN_RX__Is_HardwareFIFOempty (RM4_CAN__CHANNEL_E eChannel)
Is the hardware FIFO empty? Checks if the hardware FIFO is empty.
Parameters
[in] eChannel The CAN Channel
Returns
0 = not empty
1 = empty
SafeTool Function MD5:
8D4C1D4329476A7358B0F5DB5A01F0C0
SafeTool Function ID:
LCCM126R0.FILE.009.FUNC.004
References C_LCCM126__FAULT_INDEX__00, _strRM4CAN::sFaultFlags, sRM4CAN, u32RM4_CAN_RX__IsRxMessageArrived(), and vFAULTTREE__Set_Flag().
Referenced by u8RM4_CAN_RX__ProcessFIFOs().
Luint8 u8RM4_CAN_RX__Is_MessageAvailable (RM4_CAN__CHANNEL_E eChannel)
Is a Rx message avail? Returns true if a RX message is available for us to get.
Parameters
[in] eChannel The can channel
Returns
1 = message is available
0 = no new messages avail
SafeTool Function MD5:
0DC0FF20F9443394D47376F171D87A3F
SafeTool Function ID:
LCCM126R0.FILE.009.FUNC.002
References C_LCCM126__FAULT_INDEX__00, _strRM4CAN::sFaultFlags, sRM4CAN, u8RM4_CAN_SWFIFO__Is_Empty(), and vFAULTTREE__Set_Flag().
Luint8 u8RM4_CAN_RX__ProcessFIFOs (RM4_CAN__CHANNEL_E eChannel)
Process the hardware and software FIFO's Returns the number of messages extracted from hardware FIFO into the software FIFO.
Parameters
[in] eChannel The CAN Channel
Returns
0 = the FIFO is empty
n = some messages were extracted
SafeTool Function MD5:
5169E81DF6C05ABF2F3C1AE84C8C871A
SafeTool Function ID:
LCCM126R0.FILE.009.FUNC.001
References C_LCCM126__FAULT_INDEX__00, _strRM4CAN::sFaultFlags, sRM4CAN, u8RM4_CAN_RX__ExtractAllMessagesFromHardwareFIFO(), u8RM4_CAN_RX__Is_HardwareFIFOempty(), and vFAULTTREE__Set_Flag().
Referenced by vRM4_CAN__Process().
void vRM4_CAN_RX__RxMessage (RM4_CAN__CHANNEL_E eChannel, Luint8 * pu8NodeID, Luint16 * pu16MessageID, Luint8 * pu8Buffer, Luint32 * pu32TimeStamp)
Rx a message from the CAN Software FIFO's If a new msg is avail, get the message from the FIFO's.
Parameters
[in] pu32TimeStamp Time stamp
[in] pu8Buffer Data Buffer
[in] pu16MessageID The message ID
[in] pu8NodeID The nodeID
[in] eChannel The channel
SafeTool Function MD5:
F6063526829ECB318AF70C626231A1E2
SafeTool Function ID:
LCCM126R0.FILE.009.FUNC.003
References C_LCCM126__FAULT_INDEX__00, s16RM4_CAN_SWFIFO__Pop(), _strRM4CAN::sFaultFlags, sRM4CAN, CANRxMessageBuffer::sX, CANRxMessageBuffer::u32MsgID, u32RM4_RTI__Get_FreeClock(), CANRxMessageBuffer::u8Data, and vFAULTTREE__Set_Flag().
Variable Documentation
struct _strRM4CAN sRM4CAN
Referenced by s16RM4_CAN_RX__RxMessage_Worker(), u32RM4_CAN__Get_FaultFlags(), u32RM4_CAN_RX__IsRxMessageArrived(), u8RM4_CAN_RX__Is_HardwareFIFOempty(), u8RM4_CAN_RX__Is_MessageAvailable(), u8RM4_CAN_RX__ProcessFIFOs(), vRM4_CAN__Init(), vRM4_CAN__Process(), and vRM4_CAN_RX__RxMessage().