(C Code, RLOOP, Power Node Core): POWER_NODE__STATE_MACHINE
POWER_NODE__STATE_MACHINE
RLOOP » POWER_NODE
Functions
void vPWRNODE_SM__Init (void)
Init any of the main application state machine items.
void vPWRNODE_SM__Process (void)
Process.
void vPWRNODE_SM__Enable_ChargingState (void)
call this to configure charging state.
void vPWRNODE_SM__Stop_ChargingState (void)
stop charging immediate
Variables
struct _strPWRNODE sPWRNODE
Detailed Description
Function Documentation
void vPWRNODE_SM__Enable_ChargingState (void)
call this to configure charging state.
SafeTool Function MD5:
A4102DAE2BA37B460B55A31632AE4AC5
SafeTool Function ID:
LCCM653R0.FILE.003.FUNC.003
References _strPWRNODE::eMainState, RUN_STATE__CHARGE_START, and sPWRNODE.
Referenced by vPWRNODE_NET_RX__RxSafeUDP().
void vPWRNODE_SM__Init (void)
Init any of the main application state machine items.
SafeTool Function MD5:
A40323662C84BEFCABD28662D11DA6D2
SafeTool Function ID:
LCCM653R0.FILE.003.FUNC.001
References _strPWRNODE::eMainState, RUN_STATE__RESET, and sPWRNODE.
void vPWRNODE_SM__Process (void)
Process.
SafeTool Function MD5:
2C216E76AC8D83A551120784C3CF399D
SafeTool Function ID:
LCCM653R0.FILE.003.FUNC.002
References _strPWRNODE::eMainState, RUN_STATE__CHARGE_PROCESS, RUN_STATE__CHARGE_START, RUN_STATE__CHARGE_STOP, RUN_STATE__IDLE, RUN_STATE__RESET, RUN_STATE__TEST, sPWRNODE, u8PWRNODE_CHG__Is_Busy(), vPWRNODE_CHG__Abort(), and vPWRNODE_CHG__Start().
Referenced by vPWRNODE__Process().
void vPWRNODE_SM__Stop_ChargingState (void)
stop charging immediate
SafeTool Function MD5:
CD45124CCD72755256E22880758DBE25
SafeTool Function ID:
LCCM653R0.FILE.003.FUNC.004
References _strPWRNODE::eMainState, RUN_STATE__CHARGE_STOP, and sPWRNODE.
Referenced by vPWRNODE_NET_RX__RxSafeUDP().
Variable Documentation
struct _strPWRNODE sPWRNODE
Referenced by vPWRNODE__Init(), vPWRNODE__Process(), vPWRNODE__RTI_100MS_ISR(), vPWRNODE_SM__Enable_ChargingState(), vPWRNODE_SM__Init(), vPWRNODE_SM__Process(), and vPWRNODE_SM__Stop_ChargingState().