(C Code, RLOOP, Power Node Core): POWER_NODE__IV_MEASURE
POWER_NODE__IV_MEASURE
RLOOP » POWER_NODE
Macros
#define ADCREFERENCEVOLTAGE (3.3F)
Functions
Lfloat32 f32PWRNODE_CHG_IV__Filter_ADC_Value (Lfloat32 ADC_Sample)
Average the current readings.
void vPWRNODE_CHG_IV__Init (void)
Init the charger voltage and current measurement.
void vPWRNODE_CHG_IV__Process (void)
Process the charger voltage and current measurement.
Variables
struct _strPWRNODE sPWRNODE
Detailed Description
Macro Definition Documentation
#define ADCREFERENCEVOLTAGE (3.3F)
Function Documentation
Lfloat32 f32PWRNODE_CHG_IV__Filter_ADC_Value (Lfloat32 ADC_Sample)
Average the current readings.
SafeTool Function MD5:
AF5EF4D90978E6F62271760FF836E754
SafeTool Function ID:
LCCM653R0.FILE.023.FUNC.002
References C_PWRCORE__CURRENT_AVG_SIZE, _strPWRNODE::f32HAAS_Current_Average_Array, _strPWRNODE::sHASS600, sPWRNODE, and _strPWRNODE::u16HAAS_Current_Average_Counter.
Referenced by vPWRNODE_CHG_IV__Process().
void vPWRNODE_CHG_IV__Init (void)
Init the charger voltage and current measurement.
SafeTool Function MD5:
60D7C48E9A55F549B328B969C6A38605
SafeTool Function ID:
LCCM653R0.FILE.023.FUNC.001
References _strPWRNODE::f32HASS_VoltageOffSet, _strPWRNODE::sFaultFlags, _strPWRNODE::sHASS600, and sPWRNODE.
Referenced by vPWRNODE_CHG__Init().
void vPWRNODE_CHG_IV__Process (void)
Process the charger voltage and current measurement.
SafeTool Function MD5:
AF5EF4D90978E6F62271760FF836E754
SafeTool Function ID:
LCCM653R0.FILE.023.FUNC.002
References C_LCCM653__IVMEASURE__FAULT_INDEX__00, C_LCCM653__IVMEASURE__FAULT_INDEX_MASK__00, _strPWRNODE::f32HASS_CurrentReading, _strPWRNODE::f32HASS_VoltageOffSet, f32PWRNODE_CHG_IV__Filter_ADC_Value(), _strPWRNODE::sFaultFlags, _strPWRNODE::sHASS600, and sPWRNODE.
Referenced by vPWRNODE_CHG__Process().
Variable Documentation
struct _strPWRNODE sPWRNODE
Referenced by f32PWRNODE_CHG_IV__Filter_ADC_Value(), vPWRNODE_CHG_IV__Init(), and vPWRNODE_CHG_IV__Process().