(C Code, RLOOP, Power Node Core): POWER_NODE__BATTERY_TEMP__ETHERNET
POWER_NODE__BATTERY_TEMP__ETHERNET
RLOOP » POWER_NODE
Functions
void vPWRNODE_BAATTEMP_ETH__Transmit (E_NET__PACKET_T ePacketType)
Transmit a general eth packet.
void vPWRNODE_BAATTEMP_ETH__Transmit_ROMID (Luint32 u32Index)
Transmit a ROMID packet.
Variables
struct _strPWRNODE sPWRNODE
Detailed Description
Function Documentation
void vPWRNODE_BAATTEMP_ETH__Transmit (E_NET__PACKET_T ePacketType)
Transmit a general eth packet.
Parameters
[in] ePacketType Eth Type
SafeTool Function MD5:
285D08C3FCC2B0B0F87EB0E5B7FAFB32
SafeTool Function ID:
LCCM653R0.FILE.028.FUNC.001
References sPWRNODE, _strPWRNODE::u16EthPort, and u16PWRNODE_BATTTEMP_MEM__Get_NumSensors().
Referenced by vPWRNODE_NET_TX__Process().
void vPWRNODE_BAATTEMP_ETH__Transmit_ROMID (Luint32 u32Index)
Transmit a ROMID packet.
Parameters
[in] u32Index Enumeration Index
SafeTool Function MD5:
ED610968B92B427A06555891B9679CDB
SafeTool Function ID:
LCCM653R0.FILE.028.FUNC.002
References sPWRNODE, and _strPWRNODE::u16EthPort.
Referenced by vPWRNODE_NET_TX__Process().
Variable Documentation
struct _strPWRNODE sPWRNODE
Referenced by vPWRNODE_BAATTEMP_ETH__Transmit(), and vPWRNODE_BAATTEMP_ETH__Transmit_ROMID().