(C Code, RLOOP, Power Node Core): POWER_NODE__BMS__ETHERNET
POWER_NODE__BMS__ETHERNET
RLOOP » POWER_NODE
Functions
void vPWR_BMS_ETH__Init (void)
Init the Eth Portion.
void vPWR_BMS_ETH__Transmit (E_NET__PACKET_T ePacketType)
Tx an eth packet.
Variables
struct _strPWRNODE sPWRNODE
struct _str6870 sATA6870
Detailed Description
Function Documentation
void vPWR_BMS_ETH__Init (void)
Init the Eth Portion.
SafeTool Function MD5:
3C23F10BFAD5C0FAB78B1C9FB1178A79
SafeTool Function ID:
LCCM653R0.FILE.032.FUNC.001
Referenced by vPWRNODE_BMS__Init().
void vPWR_BMS_ETH__Transmit (E_NET__PACKET_T ePacketType)
Tx an eth packet.
Parameters
[in] ePacketType The packet type.
SafeTool Function MD5:
8F66B9F76D2E197949E7C8F228310ABE
SafeTool Function ID:
LCCM653R0.FILE.032.FUNC.002
References _strPWRNODE::eState, _strPWRNODE::f32AverageTemp, _strPWRNODE::f32HASS_CurrentReading, _strPWRNODE::f32HighestTemp, f32PWRNODE_BMS__Cell_Get_HighestVoltage(), f32PWRNODE_BMS__Cell_Get_LowestVoltage(), f32PWRNODE_BMS__Get_PackVoltage(), f32PWRNODE_NODEPRESS__Get_Pressure_Bar(), f32PWRNODE_NODETEMP__Get_DegC(), _strPWRNODE::sAlgo, sATA6870, _strPWRNODE::sCharger, _strPWRNODE::sFaults, _strPWRNODE::sHASS600, sPWRNODE, _strPWRNODE::sTemp, _strPWRNODE::sTopLevel, _strPWRNODE::u16EthPort, _strPWRNODE::u16HighestSensorIndex, u32PWRNODE_BMS__Get_VoltsUpdateCount(), and _strPWRNODE::u32TempScanCount.
Referenced by vPWRNODE_NET_TX__Process().
Variable Documentation
struct _str6870 sATA6870
Referenced by vPWR_BMS_ETH__Transmit().
struct _strPWRNODE sPWRNODE
Referenced by vPWR_BMS_ETH__Transmit().