(C Code, RLOOP, Power Node Core): POWER_NODE__NODE_PRESSURE
POWER_NODE__NODE_PRESSURE
RLOOP » POWER_NODE
Functions
void vPWRNODE_NODEPRESS__Init (void)
Init the node pressure layer.
void vPWRNODE_NODEPRESS__Process (void)
Process the node pressure layer.
Lfloat32 f32PWRNODE_NODEPRESS__Get_Pressure_Bar (void)
Return the node pressure in Bar.
Variables
struct _strPWRNODE sPWRNODE
Detailed Description
Function Documentation
Lfloat32 f32PWRNODE_NODEPRESS__Get_Pressure_Bar (void)
Return the node pressure in Bar.
Returns
The most recent pressure sample.
SafeTool Function MD5:
0748B93E24608CC0971FB005AFCDF812
SafeTool Function ID:
LCCM653R0.FILE.006.FUNC.003
References sPWRNODE.
Referenced by vPWR_BMS_ETH__Transmit(), and vPWR_PVPRESS__Process().
void vPWRNODE_NODEPRESS__Init (void)
Init the node pressure layer.
SafeTool Function MD5:
431FFDCF30F00FA61A07843EAEF32994
SafeTool Function ID:
LCCM653R0.FILE.006.FUNC.001
Referenced by vPWRNODE__Process().
void vPWRNODE_NODEPRESS__Process (void)
Process the node pressure layer.
SafeTool Function MD5:
14FC06472F5A34E8DC409148E0A8E283
SafeTool Function ID:
LCCM653R0.FILE.006.FUNC.002
Referenced by vPWRNODE__Process().
Variable Documentation
struct _strPWRNODE sPWRNODE
Referenced by f32PWRNODE_NODEPRESS__Get_Pressure_Bar().