(C Code, RLOOP, Power Node Core): POWER_NODE__BATTERY_TEMP
POWER_NODE__BATTERY_TEMP
RLOOP » POWER_NODE
Functions
void vPWRNODE_BATTTEMP__Init (void)
Init the battery temperature measurement devices.
void vPWRNODE_BATTTEMP__Process (void)
Process any battery temp measurement tasks.
Luint8 u8PWR_BATTTEMP__Is_Avail (void)
Return 1 if we have the temp system avail?
Variables
struct _strPWRNODE sPWRNODE
Detailed Description
Function Documentation
Luint8 u8PWR_BATTTEMP__Is_Avail (void)
Return 1 if we have the temp system avail?
SafeTool Function MD5:
9225B00F2A81F2A0408B558E15D81756
SafeTool Function ID:
LCCM653R0.FILE.009.FUNC.005
References BATT_TEMP_STATE__RUN, _strPWRNODE::eState, sPWRNODE, and _strPWRNODE::sTemp.
Referenced by vPWRNODE_CHG__Start().
void vPWRNODE_BATTTEMP__Init (void)
Init the battery temperature measurement devices.
SafeTool Function MD5:
86C09833B06FA3BF0A2875528B492BEA
SafeTool Function ID:
LCCM653R0.FILE.009.FUNC.001
References BATT_TEMP_STATE__IDLE, _strPWRNODE::eState, _strPWRNODE::f32AverageTemp, _strPWRNODE::f32HighestTemp, sPWRNODE, _strPWRNODE::sTemp, _strPWRNODE::u16HighestSensorIndex, _strPWRNODE::u32TempScanCount, _strPWRNODE::u8NewTempAvail, and vPWRNODE_BATTTEMP_MEM__Init().
Referenced by vPWRNODE__Process().
void vPWRNODE_BATTTEMP__Process (void)
Process any battery temp measurement tasks.
SafeTool Function MD5:
521412365BC09A1D1CB3B029664377AB
SafeTool Function ID:
LCCM653R0.FILE.009.FUNC.002
References BATT_TEMP_STATE__CONFIGURE_RESOLUTION, BATT_TEMP_STATE__IDLE, BATT_TEMP_STATE__LOAD_DEFAULTS, BATT_TEMP_STATE__RUN, BATT_TEMP_STATE__START_SCAN, BATT_TEMP_STATE__WAIT_SCAN, C_PWRCORE__BMS_TEMP_MASK, _strPWRNODE::eState, _strPWRNODE::f32AverageTemp, _strPWRNODE::f32HighestTemp, s16PWRNODE_BATTEMP_MEM__Load(), sPWRNODE, _strPWRNODE::sTemp, _strPWRNODE::u16HighestSensorIndex, _strPWRNODE::u16NumSensors, _strPWRNODE::u32TempScanCount, _strPWRNODE::u8NewTempAvail, and vPWRNODE_BATTTEMP_MEM__Process().
Referenced by vPWRNODE__Process().
Variable Documentation
struct _strPWRNODE sPWRNODE
Referenced by u8PWR_BATTTEMP__Is_Avail(), vPWRNODE_BATTTEMP__Init(), and vPWRNODE_BATTTEMP__Process().