(C Code, RLOOP, Power Node Core): POWER_NODE__CHARGER
POWER_NODE__CHARGER
RLOOP » POWER_NODE
Functions
void vPWRNODE_CHG__Init (void)
Init the charger systems.
void vPWRNODE_CHG__Process (void)
Process the charger.
void vPWRNODE_GHG__Start_ManualBalance (void)
ToDo.
void vPWRNODE_GHG__Stop_ManualBalance (void)
ToDo.
void vPWRNODE_CHG__Start (void)
start charging
Luint8 u8PWRNODE_CHG__Is_Busy (void)
Return 1 if the charger system is busy.
void vPWRNODE_CHG__Abort (void)
Immediate charge abort.
Variables
struct _strPWRNODE sPWRNODE
Detailed Description
Function Documentation
Luint8 u8PWRNODE_CHG__Is_Busy (void)
Return 1 if the charger system is busy.
SafeTool Function MD5:
7357CD3525341E0653DA161837E24AE7
SafeTool Function ID:
LCCM653R0.FILE.030.FUNC.004
References CHG_STATE__IDLE, _strPWRNODE::sAlgo, _strPWRNODE::sCharger, and sPWRNODE.
Referenced by vPWRNODE_SM__Process().
void vPWRNODE_CHG__Abort (void)
Immediate charge abort.
SafeTool Function MD5:
E442AC159B78066F7C5A8EB1416847BE
SafeTool Function ID:
LCCM653R0.FILE.030.FUNC.005
References CHG_STATE__ABORT, _strPWRNODE::sAlgo, _strPWRNODE::sCharger, sPWRNODE, and vPWRNODE_CHG_RELAY__Off().
Referenced by vPWRNODE_SM__Process().
void vPWRNODE_CHG__Init (void)
Init the charger systems.
SafeTool Function MD5:
AC43B298818E1A69A7E37E92B6423BAA
SafeTool Function ID:
LCCM653R0.FILE.030.FUNC.001
References C_POWERCORE__EEPARAM_INDEX__CHARGER__CRC, C_POWERCORE__EEPARAM_INDEX__CHARGER__MAX_CELL_TEMP, C_POWERCORE__EEPARAM_INDEX__CHARGER__MAX_CELL_VOLT, C_POWERCORE__EEPARAM_INDEX__CHARGER__MAX_PACK_VOLT, C_POWERCORE__EEPARAM_INDEX__CHARGER__MIN_PACK_VOLT, CHG_STATE__IDLE, _strPWRNODE::f32MaxCellTemp, _strPWRNODE::f32MaxHighestCell, _strPWRNODE::f32MaxPackVoltage, _strPWRNODE::f32MinPackVoltage, _strPWRNODE::sAlgo, _strPWRNODE::sCharger, sPWRNODE, vPWRNODE_CHG_IV__Init(), and vPWRNODE_CHG_RELAY__Init().
Referenced by vPWRNODE__Process().
void vPWRNODE_CHG__Process (void)
Process the charger.
Note
http://confluence.rloop.org/display/SD/Charging
SafeTool Function MD5:
6C097DADD9FF1B6DA62B78D6AFBFC215
SafeTool Function ID:
LCCM653R0.FILE.030.FUNC.002
References CHG_STATE__ABORT, CHG_STATE__CHECK_CELL_V_DURING_CHG, CHG_STATE__CHECK_CHG_CURRENT, CHG_STATE__CHECK_PACK_TEMP, CHG_STATE__CLOSE_CONTACTOR_RELAY, CHG_STATE__IDLE, CHG_STATE__MANUAL_BALANCING, CHG_STATE__RUN_BALANCER, CHG_STATE__START, CHG_STATE__START_BALANCE, _strPWRNODE::f32HighestTemp, _strPWRNODE::f32MaxCellTemp, _strPWRNODE::f32MaxHighestCell, _strPWRNODE::f32MaxPackVoltage, _strPWRNODE::f32MinPackVoltage, f32PWRNODE_BMS__Cell_Get_HighestVoltage(), f32PWRNODE_BMS__Get_PackVoltage(), _strPWRNODE::sAlgo, _strPWRNODE::sCharger, sPWRNODE, _strPWRNODE::sTemp, _strPWRNODE::u8NewTempAvail, u8PWRNODE_BMS__Balance_IsBusy(), vPWRNODE_BMS__Balance_Start(), vPWRNODE_CHG_IV__Process(), vPWRNODE_CHG_RELAY__Off(), vPWRNODE_CHG_RELAY__On(), and vPWRNODE_CHG_RELAY__Process().
Referenced by vPWRNODE__Process().
void vPWRNODE_CHG__Start (void)
start charging
SafeTool Function MD5:
65E32C32337A7B32FD36F2E34741D976
SafeTool Function ID:
LCCM653R0.FILE.030.FUNC.003
References CHG_STATE__ABORT, CHG_STATE__START, _strPWRNODE::sAlgo, _strPWRNODE::sCharger, sPWRNODE, and u8PWR_BATTTEMP__Is_Avail().
Referenced by vPWRNODE_SM__Process().
void vPWRNODE_GHG__Start_ManualBalance (void)
ToDo.
SafeTool Function MD5:
2A73C0300D9DB117379DAF41BE6F7740
SafeTool Function ID:
LCCM653R0.FILE.030.FUNC.006
References CHG_STATE__IDLE, CHG_STATE__MANUAL_BALANCING, _strPWRNODE::sAlgo, _strPWRNODE::sCharger, and sPWRNODE.
Referenced by vPWRNODE_NET_RX__RxSafeUDP().
void vPWRNODE_GHG__Stop_ManualBalance (void)
ToDo.
SafeTool Function MD5:
AF2A6FD8F1D965F3F3F62EC9066C2F1C
SafeTool Function ID:
LCCM653R0.FILE.030.FUNC.007
References CHG_STATE__IDLE, _strPWRNODE::sAlgo, _strPWRNODE::sCharger, and sPWRNODE.
Referenced by vPWRNODE_NET_RX__RxSafeUDP().
Variable Documentation
struct _strPWRNODE sPWRNODE
Referenced by u8PWRNODE_CHG__Is_Busy(), vPWRNODE_CHG__Abort(), vPWRNODE_CHG__Init(), vPWRNODE_CHG__Process(), vPWRNODE_CHG__Start(), vPWRNODE_GHG__Start_ManualBalance(), and vPWRNODE_GHG__Stop_ManualBalance().