(C Code, RLOOP, Power Node Core): POWER_NODE__CORE
POWER_NODE__CORE
RLOOP » POWER_NODE
Functions
void vPWRNODE__Init (void)
Init the power node, this should be the first call.
void vPWRNODE__Process (void)
Process the power node states, this should be called as quick as possible from the main program loop.
void vPWRNODE__RTI_100MS_ISR (void)
100ms timer
void vPWRNODE__RTI_10MS_ISR (void)
10ms timer
Variables
struct _strPWRNODE sPWRNODE
http://confluence.rloop.org/display/SD/8.
Detailed Description
Function Documentation
void vPWRNODE__Init (void)
Init the power node, this should be the first call.
SafeTool Function MD5:
5E00CDBD0D5864C84CA2AD39AC3F3703
SafeTool Function ID:
LCCM653R0.FILE.000.FUNC.001
References _strPWRNODE::eState, INIT_STATE__START, _strPWRNODE::sInit, sPWRNODE, _strPWRNODE::u32Guard1, _strPWRNODE::u32Guard2, _strPWRNODE::u32NodePressCounter, _strPWRNODE::u32NodeTempCounter, and vPWRNODE_FAULTS__Init().
void vPWRNODE__Process (void)
Process the power node states, this should be called as quick as possible from the main program loop.
SafeTool Function MD5:
D87D0D684CF1560EB40560019D6342DE
SafeTool Function ID:
LCCM653R0.FILE.000.FUNC.002
References C_POWERCORE__EEPARAM_INDEX__NODE_TYPE__TYPE_A, C_POWERCORE__EEPARAM_INDEX__NODE_TYPE__TYPE_B, C_POWERCORE__EEPARAM_INDEX__NODE_TYPE__TYPE_CRC, _strPWRNODE::ePersonality, _strPWRNODE::eState, INIT_STATE__BMS, INIT_STATE__CELL_TEMP_START, INIT_STATE__COMMS, INIT_STATE__DC_CONVERTER, INIT_STATE__MS5607, INIT_STATE__RUN, INIT_STATE__START, INIT_STATE__START_LOW_SYSTEM, INIT_STATE__START_TIMERS, INIT_STATE__TSYS01, INIT_STATE__UNKNOWN, PWRNODE_TYPE__PACK_A, PWRNODE_TYPE__PACK_B, PWRNODE_TYPE__PACK_MAX, _strPWRNODE::sInit, sPWRNODE, _strPWRNODE::u16EthPort, _strPWRNODE::u32NodePressCounter, _strPWRNODE::u32NodeTempCounter, vPWR_COOLING__Init(), vPWR_COOLING__Process(), vPWR_PVPRESS__Init(), vPWR_PVPRESS__Process(), vPWRNODE_BATTTEMP__Init(), vPWRNODE_BATTTEMP__Process(), vPWRNODE_BMS__Init(), vPWRNODE_BMS__Process(), vPWRNODE_CHG__Init(), vPWRNODE_CHG__Process(), vPWRNODE_DC__Init(), vPWRNODE_DC__Process(), vPWRNODE_NET__Init(), vPWRNODE_NET__Process(), vPWRNODE_NODEPRESS__Init(), vPWRNODE_NODEPRESS__Process(), vPWRNODE_NODETEMP__Init(), vPWRNODE_NODETEMP__Process(), vPWRNODE_PICOMMS__Init(), vPWRNODE_PICOMMS__Process(), and vPWRNODE_SM__Process().
void vPWRNODE__RTI_100MS_ISR (void)
100ms timer
SafeTool Function MD5:
1C91DBE904A59002BE4066D0653B78F1
SafeTool Function ID:
LCCM653R0.FILE.000.FUNC.003
References sPWRNODE, _strPWRNODE::u32NodePressCounter, _strPWRNODE::u32NodeTempCounter, vPWR_COOLING__100MS_ISR(), vPWR_COOLING_EDDY__100MS_ISR(), vPWR_COOLING_HOVER__100MS_ISR(), vPWR_PVPRESS__100MS_ISR(), vPWRNODE_DC__100MS_ISR(), and vPWRNODE_PICOMMS__100MS_ISR().
void vPWRNODE__RTI_10MS_ISR (void)
10ms timer
SafeTool Function MD5:
6A863930CAD007EDEE0C5B0179EA027A
SafeTool Function ID:
LCCM653R0.FILE.000.FUNC.004
References vPWRNODE_NET__10MS_ISR().
Variable Documentation
struct _strPWRNODE sPWRNODE
http://confluence.rloop.org/display/SD/8.
+Control+Cooling+System http://confluence.rloop.org/display/SD/Thermal http://confluence.rloop.org/display/SD/7.+Control+Hover+Engines
Referenced by vPWRNODE__Init(), vPWRNODE__Process(), vPWRNODE__RTI_100MS_ISR(), vPWRNODE_FAULTS__Init(), vPWRNODE_FAULTS__Process(), vPWRNODE_SM__Enable_ChargingState(), vPWRNODE_SM__Init(), vPWRNODE_SM__Process(), and vPWRNODE_SM__Stop_ChargingState().