(C Code, RLOOP, Power Node Core): POWER_NODE__NETWORK__TX
POWER_NODE__NETWORK__TX
RLOOP » POWER_NODE
Functions
void vPWRNODE_NET_TX__Init (void)
Init any network transmission stuff.
void vPWRNODE_NET_TX__Process (void)
Process network transmission and do any transmission as required.
void vPWRNODE_NET_TX__10MS_ISR (void)
To be called from the 10ms timer routine Sets a flag to allow this module to determine that 10ms has elapsed.
Variables
struct _strPWRNODE sPWRNODE
Detailed Description
Function Documentation
void vPWRNODE_NET_TX__10MS_ISR (void)
To be called from the 10ms timer routine Sets a flag to allow this module to determine that 10ms has elapsed.
SafeTool Function MD5:
4F3E5F3BC3E1859166F0A689603284B8
SafeTool Function ID:
LCCM653R0.FILE.019.FUNC.003
References sPWRNODE, _strPWRNODE::sUDPDiag, and _strPWRNODE::u810MS_Flag.
Referenced by vPWRNODE_NET__10MS_ISR().
void vPWRNODE_NET_TX__Init (void)
Init any network transmission stuff.
SafeTool Function MD5:
3F2282AB7DAA3A767718151136E05BB2
SafeTool Function ID:
LCCM653R0.FILE.019.FUNC.001
References _strPWRNODE::eTxPacketType, _strPWRNODE::eTxStreamingType, sPWRNODE, _strPWRNODE::sUDPDiag, and _strPWRNODE::u810MS_Flag.
Referenced by vPWRNODE_NET__Init().
void vPWRNODE_NET_TX__Process (void)
Process network transmission and do any transmission as required.
SafeTool Function MD5:
35F64043C51C1661D37E387BBF650B0A
SafeTool Function ID:
LCCM653R0.FILE.019.FUNC.002
References C_ETH_PACKET_TX_COUNT, _strPWRNODE::eTxPacketType, _strPWRNODE::eTxStreamingType, sPWRNODE, _strPWRNODE::sUDPDiag, _strPWRNODE::u32Block0, _strPWRNODE::u810MS_Flag, vPWR_BMS_ETH__Transmit(), vPWRNODE_BAATTEMP_ETH__Transmit(), and vPWRNODE_BAATTEMP_ETH__Transmit_ROMID().
Referenced by vPWRNODE_NET__Process().
Variable Documentation
struct _strPWRNODE sPWRNODE
Referenced by vPWRNODE_NET_TX__10MS_ISR(), vPWRNODE_NET_TX__Init(), and vPWRNODE_NET_TX__Process().