(C Code, RLOOP, Power Node Core): POWER_NODE__BMS
POWER_NODE__BMS
RLOOP » POWER_NODE
Functions
void vPWRNODE_BMS__Init (void)
Init the battery management system.
void vPWRNODE_BMS__Process (void)
Process any battery management system items.
Lfloat32 f32PWRNODE_BMS__Cell_Get_HighestVoltage (void)
Get the highest cell voltage.
Lfloat32 f32PWRNODE_BMS__Cell_Get_LowestVoltage (void)
Returns the last computed lowest cell voltage.
Lfloat32 f32PWRNODE_BMS__Get_PackVoltage (void)
Returns the entire pack voltage.
void vPWRNODE_BMS__Balance_Start (void)
Start the balance process.
Luint8 u8PWRNODE_BMS__Balance_IsBusy (void)
Is the balancer busy?
void vPWRNODE_BMS__Balance_Stop (void)
Stop balance immediate.
void vPWRNODE_BMS__Balance_Manual (Luint8 u8CellIndex, Luint8 u8Enable)
ToDo.
Luint32 u32PWRNODE_BMS__Get_VoltsUpdateCount (void)
ToDo.
Variables
struct _strPWRNODE sPWRNODE
Detailed Description
Function Documentation
Lfloat32 f32PWRNODE_BMS__Cell_Get_HighestVoltage (void)
Get the highest cell voltage.
SafeTool Function MD5:
CCDA9D0AA2A185CC2B0AED32C6C65C05
SafeTool Function ID:
LCCM653R0.FILE.008.FUNC.003
Referenced by vPWR_BMS_ETH__Transmit(), and vPWRNODE_CHG__Process().
Lfloat32 f32PWRNODE_BMS__Cell_Get_LowestVoltage (void)
Returns the last computed lowest cell voltage.
SafeTool Function MD5:
71C954368FC27625363D95A446DA7B32
SafeTool Function ID:
LCCM653R0.FILE.008.FUNC.007
Referenced by vPWR_BMS_ETH__Transmit().
Lfloat32 f32PWRNODE_BMS__Get_PackVoltage (void)
Returns the entire pack voltage.
SafeTool Function MD5:
1FEB2A9DBECB7ED0651F480855A300D6
SafeTool Function ID:
LCCM653R0.FILE.008.FUNC.004
Referenced by vPWR_BMS_ETH__Transmit(), and vPWRNODE_CHG__Process().
Luint32 u32PWRNODE_BMS__Get_VoltsUpdateCount (void)
ToDo.
SafeTool Function MD5:
985C5FB642DFF8E96E0AB41B7CAAB50F
SafeTool Function ID:
LCCM653R0.FILE.008.FUNC.010
Referenced by vPWR_BMS_ETH__Transmit().
Luint8 u8PWRNODE_BMS__Balance_IsBusy (void)
Is the balancer busy?
SafeTool Function MD5:
4B308ED45EA0D643CDA7B851220C95A7
SafeTool Function ID:
LCCM653R0.FILE.008.FUNC.006
Referenced by vPWRNODE_CHG__Process().
void vPWRNODE_BMS__Balance_Manual (Luint8 u8CellIndex, Luint8 u8Enable)
ToDo.
Parameters
[in] u8Enable ## Desc ##
[in] u8CellIndex ## Desc ##
SafeTool Function MD5:
62BA84541AA2A37395BF6F24B081ED3D
SafeTool Function ID:
LCCM653R0.FILE.008.FUNC.009
Referenced by vPWRNODE_NET_RX__RxSafeUDP().
void vPWRNODE_BMS__Balance_Start (void)
Start the balance process.
SafeTool Function MD5:
A4A94DAE9A680CCCF72DBE546F52ED5F
SafeTool Function ID:
LCCM653R0.FILE.008.FUNC.005
Referenced by vPWRNODE_CHG__Process().
void vPWRNODE_BMS__Balance_Stop (void)
Stop balance immediate.
SafeTool Function MD5:
94B33EB600AA0ACD3DD21B166CE76587
SafeTool Function ID:
LCCM653R0.FILE.008.FUNC.008
Referenced by vPWRNODE_NET_RX__RxSafeUDP().
void vPWRNODE_BMS__Init (void)
Init the battery management system.
SafeTool Function MD5:
270D9FCF297F4E126AB47ABD1EAA4572
SafeTool Function ID:
LCCM653R0.FILE.008.FUNC.001
References vPWR_BMS_ETH__Init().
Referenced by vPWRNODE__Process().
void vPWRNODE_BMS__Process (void)
Process any battery management system items.
SafeTool Function MD5:
15B2FAA1BAD482B0EC323B1CBE361248
SafeTool Function ID:
LCCM653R0.FILE.008.FUNC.002
Referenced by vPWRNODE__Process().
Variable Documentation
struct _strPWRNODE sPWRNODE