(C Code, RLOOP, Power Node Core): POWER_NODE__CHARGE_RELAY
POWER_NODE__CHARGE_RELAY
RLOOP » POWER_NODE
Functions
void vPWRNODE_CHG_RELAY__Init (void)
Init the charge relay state.
void vPWRNODE_CHG_RELAY__Process (void)
Process the charge relay.
void vPWRNODE_CHG_RELAY__On (void)
switch on the charger relay
void vPWRNODE_CHG_RELAY__Off (void)
ToDo.
Variables
struct _strPWRNODE sPWRNODE
Detailed Description
Function Documentation
void vPWRNODE_CHG_RELAY__Init (void)
Init the charge relay state.
SafeTool Function MD5:
6F451776DBE4DCAE500A358AB04D18A7
SafeTool Function ID:
LCCM653R0.FILE.022.FUNC.001
References CHG_RLY_STATE__RESET, _strPWRNODE::eRelayState, _strPWRNODE::sCharger, and sPWRNODE.
Referenced by vPWRNODE_CHG__Init().
void vPWRNODE_CHG_RELAY__Off (void)
ToDo.
SafeTool Function MD5:
44A67B75C1052F8DCA9577FCCE0DE0E4
SafeTool Function ID:
LCCM653R0.FILE.022.FUNC.004
Referenced by vPWRNODE_CHG__Abort(), and vPWRNODE_CHG__Process().
void vPWRNODE_CHG_RELAY__On (void)
switch on the charger relay
SafeTool Function MD5:
A9BFD6505E8FC763D0B281BE62161696
SafeTool Function ID:
LCCM653R0.FILE.022.FUNC.003
Referenced by vPWRNODE_CHG__Process().
void vPWRNODE_CHG_RELAY__Process (void)
Process the charge relay.
SafeTool Function MD5:
1C9F48BE1837BEFD9325D836ACCB6CFC
SafeTool Function ID:
LCCM653R0.FILE.022.FUNC.002
References CHG_RLY_STATE__RESET, _strPWRNODE::eRelayState, _strPWRNODE::sCharger, and sPWRNODE.
Referenced by vPWRNODE_CHG__Process().
Variable Documentation
struct _strPWRNODE sPWRNODE
Referenced by vPWRNODE_CHG_RELAY__Init(), and vPWRNODE_CHG_RELAY__Process().