(C Code, RLOOP, Power Node Core): POWER_NODE__DC_CONVERTER
POWER_NODE__DC_CONVERTER
RLOOP » POWER_NODE
Functions
static void vPWRNODE_DC__Power_Off (void)
Switch the power off.
void vPWRNODE_DC__Init (void)
Init the DC/DC Converter system.
void vPWRNODE_DC__Process (void)
Process the DC/DC converter control.
void vPWRNODE_DC__Latch (Luint32 u32Key)
ToDo.
void vPWRNODE_DC__Pod_Safe_Unlock (Luint32 u32UnlockKey)
To implement pod safe, first we need to unlock the function with a separate command This will provent spurious safes.
void vPWRNODE_DC__Pet_GS_Message (Luint32 u32Key)
Pet the DC/DC conveters timeout watchdog based on GS messages.
Luint32 u32PWRNODE_DC__Get_TimerCount (void)
Get the DC/DC converter's timer count.
void vPWRNODE_DC__Pod_Safe_Go (void)
Execute pod safe.
void vPWRNODE_DC__100MS_ISR (void)
100ms timer tick
Variables
struct _strPWRNODE sPWRNODE
Detailed Description
Function Documentation
Luint32 u32PWRNODE_DC__Get_TimerCount (void)
Get the DC/DC converter's timer count.
SafeTool Function MD5:
04BE188F4A4B4B9C88B952F3C988059E
SafeTool Function ID:
LCCM653R0.FILE.021.FUNC.005
References _strPWRNODE::sDC, sPWRNODE, and _strPWRNODE::u32100MS_TimerCount.
void vPWRNODE_DC__100MS_ISR (void)
100ms timer tick
SafeTool Function MD5:
6B09D957DBEA0F8BE72657B22AE106B6
SafeTool Function ID:
LCCM653R0.FILE.021.FUNC.008
References _strPWRNODE::sDC, sPWRNODE, and _strPWRNODE::u8100MS_Tick.
Referenced by vPWRNODE__RTI_100MS_ISR().
void vPWRNODE_DC__Init (void)
Init the DC/DC Converter system.
SafeTool Function MD5:
03C5B47F8AC73AE6C19CF6ACC65B5FB2
SafeTool Function ID:
LCCM653R0.FILE.021.FUNC.001
References DC_STATE__RESET, _strPWRNODE::eState, _strPWRNODE::sDC, sPWRNODE, _strPWRNODE::u32100MS_TimerCount, _strPWRNODE::u8100MS_Tick, _strPWRNODE::u8PodSafeCommand, and _strPWRNODE::u8Unlock.
Referenced by vPWRNODE__Process().
void vPWRNODE_DC__Latch (Luint32 u32Key)
ToDo.
Parameters
[in] u32Key ## Desc ##
SafeTool Function MD5:
E2B6001DE811C97DECC3E37BB4314D81
SafeTool Function ID:
LCCM653R0.FILE.021.FUNC.009
References DC_STATE__LATCH_COMMAND, DC_STATE__RESET, _strPWRNODE::eState, _strPWRNODE::sDC, and sPWRNODE.
Referenced by vPWRNODE_NET_RX__RxSafeUDP().
void vPWRNODE_DC__Pet_GS_Message (Luint32 u32Key)
Pet the DC/DC conveters timeout watchdog based on GS messages.
Parameters
[in] u32Key 0x1234ABCD
SafeTool Function MD5:
57D147559750E935DEE4C30BC7AB0CB6
SafeTool Function ID:
LCCM653R0.FILE.021.FUNC.004
References _strPWRNODE::sDC, sPWRNODE, and _strPWRNODE::u32100MS_TimerCount.
void vPWRNODE_DC__Pod_Safe_Go (void)
Execute pod safe.
SafeTool Function MD5:
DABA4496931CC78AF6D1DAB36C684991
SafeTool Function ID:
LCCM653R0.FILE.021.FUNC.007
References _strPWRNODE::sDC, sPWRNODE, and _strPWRNODE::u8PodSafeCommand.
Referenced by vPWRNODE_NET_RX__RxSafeUDP().
void vPWRNODE_DC__Pod_Safe_Unlock (Luint32 u32UnlockKey)
To implement pod safe, first we need to unlock the function with a separate command This will provent spurious safes.
Parameters
[in] u32UnlockKey The key, should be ABCD1298
SafeTool Function MD5:
430ED2B41CF6301D6D45283A2F1EB803
SafeTool Function ID:
LCCM653R0.FILE.021.FUNC.003
References _strPWRNODE::sDC, sPWRNODE, and _strPWRNODE::u8Unlock.
Referenced by vPWRNODE_NET_RX__RxSafeUDP().
void vPWRNODE_DC__Power_Off (void) static
Switch the power off.
SafeTool Function MD5:
0B2C9EBE29F946E9B0F7A68EAEA09B99
SafeTool Function ID:
LCCM653R0.FILE.021.FUNC.006
Referenced by vPWRNODE_DC__Process().
void vPWRNODE_DC__Process (void)
Process the DC/DC converter control.
SafeTool Function MD5:
ED67B9BE6929E2BDFF7700E07B296503
SafeTool Function ID:
LCCM653R0.FILE.021.FUNC.002
References DC_STATE__CHECK_POD_SAFE, DC_STATE__CHECK_WDT_PET, DC_STATE__CHECK_WDT_TIMER, DC_STATE__LATCH_COMMAND, DC_STATE__RESET, _strPWRNODE::eState, _strPWRNODE::sDC, sPWRNODE, _strPWRNODE::u32100MS_TimerCount, _strPWRNODE::u8100MS_Tick, _strPWRNODE::u8PodSafeCommand, _strPWRNODE::u8Unlock, and vPWRNODE_DC__Power_Off().
Referenced by vPWRNODE__Process().
Variable Documentation
struct _strPWRNODE sPWRNODE
Referenced by u32PWRNODE_DC__Get_TimerCount(), vPWRNODE_DC__100MS_ISR(), vPWRNODE_DC__Init(), vPWRNODE_DC__Latch(), vPWRNODE_DC__Pet_GS_Message(), vPWRNODE_DC__Pod_Safe_Go(), vPWRNODE_DC__Pod_Safe_Unlock(), and vPWRNODE_DC__Process().