(C Code, RLOOP, Power Node Core): POWER_NODE__NETWORK__RX
POWER_NODE__NETWORK__RX
RLOOP » POWER_NODE
Functions
void vPWRNODE_NET_RX__RxUDP (Luint8 *pu8Buffer, Luint16 u16Length, Luint16 u16DestPort)
Rx a standard UDP packet.
void vPWRNODE_NET_RX__RxSafeUDP (Luint8 *pu8Payload, Luint16 u16PayloadLength, Luint16 ePacketType, Luint16 u16DestPort, Luint16 u16Fault)
Rx a SafetyUDP.
Variables
struct _strPWRNODE sPWRNODE
Detailed Description
Function Documentation
void vPWRNODE_NET_RX__RxSafeUDP (Luint8 * pu8Payload, Luint16 u16PayloadLength, Luint16 ePacketType, Luint16 u16DestPort, Luint16 u16Fault)
Rx a SafetyUDP.
Parameters
[in] u16Fault Fault details (if any)
[in] u16DestPort The destination port in the UDP packet
[in] ePacketType SafeUDP Packet Type
[in] u16PayloadLength SafeUDP Payload Length
[in] *pu8Payload Pointer to SafeUDP Payload
SafeTool Function MD5:
116A9079EF71D980FE146B60F169983E
SafeTool Function ID:
LCCM653R0.FILE.018.FUNC.002
References C_POWERCORE__EEPARAM_INDEX__CHARGER__MAX_CELL_TEMP, C_POWERCORE__EEPARAM_INDEX__CHARGER__MAX_CELL_VOLT, C_POWERCORE__EEPARAM_INDEX__CHARGER__MAX_PACK_VOLT, C_POWERCORE__EEPARAM_INDEX__CHARGER__MIN_PACK_VOLT, C_POWERCORE__EEPARAM_INDEX__NODE_TYPE__TYPE_A, C_POWERCORE__EEPARAM_INDEX__NODE_TYPE__TYPE_B, C_POWERCORE__EEPARAM_INDEX__NODE_TYPE__TYPE_CRC, COOLING_STATE__STARTTESTING_01, COOLING_STATE__STARTTESTING_02, COOLING_STATE__STARTTESTING_03, COOLING_STATE__STARTTESTING_04, COOLING_STATE__STARTTESTING_05, _strPWRNODE::eMainState, _strPWRNODE::ePersonality, _strPWRNODE::eTxPacketType, _strPWRNODE::eTxStreamingType, _strPWRNODE::f32MaxCellTemp, _strPWRNODE::f32MaxHighestCell, _strPWRNODE::f32MaxPackVoltage, _strPWRNODE::f32MinPackVoltage, PWRNODE_TYPE__PACK_A, PWRNODE_TYPE__PACK_B, _strPWRNODE::sCharger, sPWRNODE, _strPWRNODE::sUDPDiag, _strPWRNODE::u16EthPort, _strPWRNODE::u32Block0, vPWR_PVPRESS__Enable(), vPWRNODE_BATTEMP_MEM__Set_ROMID(), vPWRNODE_BATTEMP_MEM__Set_UserData(), vPWRNODE_BMS__Balance_Manual(), vPWRNODE_BMS__Balance_Stop(), vPWRNODE_DC__Latch(), vPWRNODE_DC__Pod_Safe_Go(), vPWRNODE_DC__Pod_Safe_Unlock(), vPWRNODE_GHG__Start_ManualBalance(), vPWRNODE_GHG__Stop_ManualBalance(), vPWRNODE_SM__Enable_ChargingState(), and vPWRNODE_SM__Stop_ChargingState().
void vPWRNODE_NET_RX__RxUDP (Luint8 * pu8Buffer, Luint16 u16Length, Luint16 u16DestPort)
Rx a standard UDP packet.
Parameters
[in] u16DestPort The desination UDP port
[in] u16Length The UDP Length
[in] *pu8Buffer Pointer to the UDP packet data
SafeTool Function MD5:
846C8A515C3244ECDD1DA5B609B8C1E7
SafeTool Function ID:
LCCM653R0.FILE.018.FUNC.001
Variable Documentation
struct _strPWRNODE sPWRNODE
Referenced by vPWRNODE_NET_RX__RxSafeUDP().