(C Code, RLOOP, Power Node Core): POWER_NODE__NODE_TEMPERATURE
POWER_NODE__NODE_TEMPERATURE
RLOOP » POWER_NODE
Functions
void vPWRNODE_NODETEMP__Init (void)
Init any node temperature based sub systems.
void vPWRNODE_NODETEMP__Process (void)
Process anything related to the node temperature.
Lfloat32 f32PWRNODE_NODETEMP__Get_DegC (void)
Return the most recent node temperature reading in degreesC.
Luint32 u32PWRNODE_NODETEMP__Get_FaultFlags (void)
Return any fault flags.
Variables
struct _strPWRNODE sPWRNODE
Detailed Description
Function Documentation
Lfloat32 f32PWRNODE_NODETEMP__Get_DegC (void)
Return the most recent node temperature reading in degreesC.
Returns
The node temperature in DegC
SafeTool Function MD5:
D6F0022A63A277FC6870789CAC50E861
SafeTool Function ID:
LCCM653R0.FILE.005.FUNC.003
References sPWRNODE.
Referenced by vPWR_BMS_ETH__Transmit().
Luint32 u32PWRNODE_NODETEMP__Get_FaultFlags (void)
Return any fault flags.
SafeTool Function MD5:
182BAF22E6D596A4EEB4A925EB2F4953
SafeTool Function ID:
LCCM653R0.FILE.005.FUNC.004
void vPWRNODE_NODETEMP__Init (void)
Init any node temperature based sub systems.
SafeTool Function MD5:
498EA8089ED7B6A33E5428EA2B8B0C14
SafeTool Function ID:
LCCM653R0.FILE.005.FUNC.001
Referenced by vPWRNODE__Process().
void vPWRNODE_NODETEMP__Process (void)
Process anything related to the node temperature.
SafeTool Function MD5:
72250C8B79693D5F000F4F14867A0915
SafeTool Function ID:
LCCM653R0.FILE.005.FUNC.002
Referenced by vPWRNODE__Process().
Variable Documentation
struct _strPWRNODE sPWRNODE
Referenced by f32PWRNODE_NODETEMP__Get_DegC().