(C Code, RLOOP, Power Node Core): POWER_NODE__BATTERY_TEMP__MEMORY
POWER_NODE__BATTERY_TEMP__MEMORY
RLOOP » POWER_NODE
Functions
void vPWRNODE_BATTTEMP_MEM__Init (void)
Init the memory system.
Luint16 u16PWRNODE_BATTTEMP_MEM__Get_NumSensors (void)
Return the number of sensors.
void vPWRNODE_BATTTEMP_MEM__Process (void)
Process any batt pack memory tasks.
void vPWRNODE_BATTEMP_MEM__Set_ROMID (Luint16 u16Index, Luint32 u32ROMID_Upper, Luint32 u32ROMID_Lower)
Set the ROMID in memory.
void vPWRNODE_BATTEMP_MEM__Set_UserData (Luint16 u16Index, Luint16 UserIndex, Luint8 u8BusID, Luint8 u8Resolution)
Set the misc user data.
Lint16 s16PWRNODE_BATTEMP_MEM__Save (void)
Save the current DS18B20 structure.
Lint16 s16PWRNODE_BATTEMP_MEM__Load (void)
Load the sensor array data from memory.
Variables
struct _strPWRNODE sPWRNODE
const Luint8 u8FwdPack__Default []
Format: u8SerialNumber[8U]; u8ChannelIndex; u8Resolution; u16UserIndex;.
Detailed Description
Function Documentation
Lint16 s16PWRNODE_BATTEMP_MEM__Load (void)
Load the sensor array data from memory.
SafeTool Function MD5:
57A569FE10BD47FD366E62DC6750E6C1
SafeTool Function ID:
LCCM653R0.FILE.029.FUNC.007
References sPWRNODE, _strPWRNODE::sTemp, _strPWRNODE::u16NumSensors, and _strPWRNODE::u16PackMemCRC.
Referenced by vPWRNODE_BATTTEMP__Process().
Lint16 s16PWRNODE_BATTEMP_MEM__Save (void)
Save the current DS18B20 structure.
SafeTool Function MD5:
EE6440D1A5AD7B2C555B3DE1D83E8197
SafeTool Function ID:
LCCM653R0.FILE.029.FUNC.006
Luint16 u16PWRNODE_BATTTEMP_MEM__Get_NumSensors (void)
Return the number of sensors.
SafeTool Function MD5:
61B6DDBC6B2331B8A91A22BAE7D575C4
SafeTool Function ID:
LCCM653R0.FILE.029.FUNC.002
References sPWRNODE, _strPWRNODE::sTemp, and _strPWRNODE::u16NumSensors.
Referenced by vPWRNODE_BAATTEMP_ETH__Transmit().
void vPWRNODE_BATTEMP_MEM__Set_ROMID (Luint16 u16Index, Luint32 u32ROMID_Upper, Luint32 u32ROMID_Lower)
Set the ROMID in memory.
Parameters
[in] u32ROMID_Lower ## Desc ##
[in] u32ROMID_Upper ## Desc ##
[in] u16Index ## Desc ##
SafeTool Function MD5:
D7F42D40DB34F09AEA3ACFED2EED390E
SafeTool Function ID:
LCCM653R0.FILE.029.FUNC.004
Referenced by vPWRNODE_NET_RX__RxSafeUDP().
void vPWRNODE_BATTEMP_MEM__Set_UserData (Luint16 u16Index, Luint16 UserIndex, Luint8 u8BusID, Luint8 u8Resolution)
Set the misc user data.
Parameters
[in] u8Resolution ## Desc ##
[in] u8BusID ## Desc ##
[in] UserIndex ## Desc ##
[in] u16Index ## Desc ##
SafeTool Function MD5:
A7987F0D7E4721A5389B8514028C9463
SafeTool Function ID:
LCCM653R0.FILE.029.FUNC.005
Referenced by vPWRNODE_NET_RX__RxSafeUDP().
void vPWRNODE_BATTTEMP_MEM__Init (void)
Init the memory system.
Check the CRC's and load the pack data if needed.
SafeTool Function MD5:
1EAD81C2BE5C0D89D90FEEA9ED938A1B
SafeTool Function ID:
LCCM653R0.FILE.029.FUNC.001
References C_POWERCORE__EEPARAM_INDEX__BATTTEMP__CRC, C_POWERCORE__EEPARAM_INDEX__BATTTEMP__NUM_SENSORS, C_POWERCORE__EEPARAM_INDEX__BATTTEMP__PACK_CRC, C_PWRCORE__NUM_6P_MODULES, C_PWRCORE__NUM_TEMP_SNSR_PER_6P, sPWRNODE, _strPWRNODE::sTemp, _strPWRNODE::u16NumSensors, and _strPWRNODE::u16PackMemCRC.
Referenced by vPWRNODE_BATTTEMP__Init().
void vPWRNODE_BATTTEMP_MEM__Process (void)
Process any batt pack memory tasks.
SafeTool Function MD5:
675C2F664A0027481072063B15FDCBE1
SafeTool Function ID:
LCCM653R0.FILE.029.FUNC.003
Referenced by vPWRNODE_BATTTEMP__Process().
Variable Documentation
struct _strPWRNODE sPWRNODE
Referenced by s16PWRNODE_BATTEMP_MEM__Load(), u16PWRNODE_BATTTEMP_MEM__Get_NumSensors(), and vPWRNODE_BATTTEMP_MEM__Init().
const Luint8 u8FwdPack__Default[]
Format: u8SerialNumber[8U]; u8ChannelIndex; u8Resolution; u16UserIndex;.