(C Code, RLOOP, Power Node Core): POWER_NODE__NETWORK
POWER_NODE__NETWORK
RLOOP » POWER_NODE
Functions
void vPWRNODE_NET__Init (void)
inits the ethernet networking
void vPWRNODE_NET__Process (void)
Process the EMAC link.
Luint8 u8PWRNODE_NET__Is_LinkUp (void)
Is the EMAC link up.
void vPWRNODE_NET__10MS_ISR (void)
10ms ISR from system timer.
Variables
struct _strPWRNODE sPWRNODE
Detailed Description
Function Documentation
Luint8 u8PWRNODE_NET__Is_LinkUp (void)
Is the EMAC link up.
Returns
0 = link down
1 = link up.
SafeTool Function MD5:
F9B6430A56764B8EFA4ADD7E7755D25E
SafeTool Function ID:
LCCM653R0.FILE.017.FUNC.003
Referenced by vPWRNODE_NET__Process().
void vPWRNODE_NET__10MS_ISR (void)
10ms ISR from system timer.
SafeTool Function MD5:
37B10B02423D305234C7C6886DC18950
SafeTool Function ID:
LCCM653R0.FILE.017.FUNC.004
References _strPWRNODE::sEthernet, sPWRNODE, _strPWRNODE::u810MS_Timer, and vPWRNODE_NET_TX__10MS_ISR().
Referenced by vPWRNODE__RTI_10MS_ISR().
void vPWRNODE_NET__Init (void)
inits the ethernet networking
SafeTool Function MD5:
6503B956583F682C19CEDEE0C48159A6
SafeTool Function ID:
LCCM653R0.FILE.017.FUNC.001
References _strPWRNODE::eMainState, _strPWRNODE::ePersonality, NET_STATE__IDLE, PWRNODE_TYPE__PACK_A, _strPWRNODE::sEthernet, sPWRNODE, _strPWRNODE::u810MS_Timer, _strPWRNODE::u8IPAddx, _strPWRNODE::u8MACAddx, _strPWRNODE::u8UnicastAddx, and vPWRNODE_NET_TX__Init().
Referenced by vPWRNODE__Process().
void vPWRNODE_NET__Process (void)
Process the EMAC link.
Note
This should be called from main program loop after power is stable This also calls the EMAC link state machine which processes the EMAC link and handles bringing the EMAC on line.
SafeTool Function MD5:
2AA3D2526979146A07CB5497CA59637B
SafeTool Function ID:
LCCM653R0.FILE.017.FUNC.002
References C_ETH_PACKET_TX_COUNT, _strPWRNODE::eMainState, NET_STATE__IDLE, NET_STATE__RUN, NET_STATE__WAIT_LINK, NET_STATE__WAIT_TIMER_TICK, _strPWRNODE::sEthernet, sPWRNODE, _strPWRNODE::u810MS_Timer, u8PWRNODE_NET__Is_LinkUp(), and vPWRNODE_NET_TX__Process().
Referenced by vPWRNODE__Process().
Variable Documentation
struct _strPWRNODE sPWRNODE
Referenced by vPWRNODE_NET__10MS_ISR(), vPWRNODE_NET__Init(), and vPWRNODE_NET__Process().