(C Code, RLOOP, Power Node Core): power_core.h File Reference
power_core.h File Reference
Main header file for the power node core functions.
#include <localdef.h>
#include <LCCM653__RLOOP__POWER_CORE/PI_COMMS/power_core__pi_comms__types.h>
#include <LCCM653__RLOOP__POWER_CORE/power_core__state_types.h>
#include <LCCM653__RLOOP__POWER_CORE/power_core__defines.h>
#include <LCCM653__RLOOP__POWER_CORE/power_core__eeprom_index.h>
#include <LCCM653__RLOOP__POWER_CORE/power_core__enums.h>
#include <LCCM653__RLOOP__POWER_CORE/power_core__fault_flags.h>
#include <LCCM653__RLOOP__POWER_CORE/CHARGER/IV_MEASURE/power__iv_measure__fault_flags.h>
#include <LCCM655__RLOOP__FCU_CORE/NETWORKING/fcu_core__net__packet_types.h>
#include <MULTICORE/LCCM284__MULTICORE__FAULT_TREE/fault_tree__public.h>
Data Structures
struct _strPWRNODE
Main Power Node Structure.
Functions
DLL_DECLARATION void vPWRNODE__Init (void)
Init the power node, this should be the first call.
DLL_DECLARATION void vPWRNODE__Process (void)
Process the power node states, this should be called as quick as possible from the main program loop.
void vPWRNODE__RTI_100MS_ISR (void)
100ms timer
void vPWRNODE__RTI_10MS_ISR (void)
10ms timer
void vPWRNODE_FAULTS__Init (void)
Init the faults.
void vPWRNODE_FAULTS__Process (void)
Process any faults.
void vPWRNODE_NET__Init (void)
void vPWRNODE_NET__Process (void)
void vPWRNODE_NET__10MS_ISR (void)
Luint8 u8PWRNODE_NET__Is_LinkUp (void)
void vPWRNODE_NET_RX__RxUDP (Luint8 *pu8Buffer, Luint16 u16Length, Luint16 u16DestPort)
void vPWRNODE_NET_RX__RxSafeUDP (Luint8 *pu8Payload, Luint16 u16PayloadLength, Luint16 ePacketType, Luint16 u16DestPort, Luint16 u16Fault)
void vPWRNODE_NET_TX__Init (void)
void vPWRNODE_NET_TX__Process (void)
void vPWRNODE_NET_TX__10MS_ISR (void)
void vPWRNODE_SM__Init (void)
Init any of the main application state machine items.
void vPWRNODE_SM__Process (void)
Process.
void vPWRNODE_SM__Enable_ChargingState (void)
ToDo.
void vPWRNODE_SM__Stop_ChargingState (void)
ToDo.
void vPWRNODE_DC__Init (void)
void vPWRNODE_DC__Process (void)
void vPWRNODE_DC__Pet_GS_Message (Luint32 u32Key)
Luint32 u32PWRNODE_DC__Get_TimerCount (void)
void vPWRNODE_DC__Pod_Safe_Unlock (Luint32 u32UnlockKey)
void vPWRNODE_DC__Pod_Safe_Go (void)
void vPWRNODE_DC__100MS_ISR (void)
void vPWRNODE_DC__Latch (Luint32 u32Key)
void vPWRNODE_CHG_RELAY__Init (void)
void vPWRNODE_CHG_RELAY__Process (void)
void vPWRNODE_CHG_RELAY__On (void)
void vPWRNODE_CHG_RELAY__Off (void)
void vPWRNODE_CHG__Init (void)
void vPWRNODE_CHG__Process (void)
void vPWRNODE_CHG__Start (void)
Luint8 u8PWRNODE_CHG__Is_Busy (void)
void vPWRNODE_CHG__Abort (void)
void vPWRNODE_GHG__Start_ManualBalance (void)
void vPWRNODE_GHG__Stop_ManualBalance (void)
void vPWRNODE_CHG_IV__Init (void)
void vPWRNODE_CHG_IV__Process (void)
void vPWR_CHARGER_ETH__Init (void)
void vPWR_CHARGER_ETH__Transmit (E_NET__PACKET_T ePacketType)
void vPWRNODE_BMS__Init (void)
void vPWRNODE_BMS__Process (void)
Lfloat32 f32PWRNODE_BMS__Cell_Get_HighestVoltage (void)
Lfloat32 f32PWRNODE_BMS__Cell_Get_LowestVoltage (void)
Lfloat32 f32PWRNODE_BMS__Get_PackVoltage (void)
Luint8 u8PWRNODE_BMS__Balance_IsBusy (void)
void vPWRNODE_BMS__Balance_Start (void)
void vPWRNODE_BMS__Balance_Stop (void)
void vPWRNODE_BMS__Balance_Manual (Luint8 u8CellIndex, Luint8 u8Enable)
Luint32 u32PWRNODE_BMS__Get_VoltsUpdateCount (void)
void vPWR_BMS_ETH__Init (void)
void vPWR_BMS_ETH__Transmit (E_NET__PACKET_T ePacketType)
void vPWRNODE_PICOMMS__Init (void)
void vPWRNODE_PICOMMS__Process (void)
void vPWRNODE_PICOMMS__100MS_ISR (void)
void vPWRNODE_PICOMMS_MSG__PodSafe__UnlockKey (Luint32 u32Key)
void vPWRNODE_PICOMMS_MSG__PodSafe__Execute (void)
Luint32 u32PWRNODE_PICOMMS_MSG__PodSafe__Get_Watchdog_Value (void)
Lfloat32 f32PWRNODE_PICOMMS_MSG__NodeTemp__Get_DegC (void)
Luint32 u32PWRNODE_PICOMMS_MSG__NodeTemp__Get_FaulFlags (void)
void vPWRNODE_CAN__Init (void)
Init any CAN specifics.
void vPWRNODE_CAN__Process (void)
Process any CAN tasks.
void vPWRNODE_BATTTEMP__Init (void)
void vPWRNODE_BATTTEMP__Process (void)
Luint8 u8PWR_BATTTEMP__Is_Avail (void)
void vPWRNODE_BATTTEMP_MEM__Init (void)
void vPWRNODE_BATTTEMP_MEM__Process (void)
Lint16 s16PWRNODE_BATTEMP_MEM__Load (void)
Luint16 u16PWRNODE_BATTTEMP_MEM__Get_NumSensors (void)
void vPWRNODE_BATTEMP_MEM__Set_ROMID (Luint16 u16Index, Luint32 u32ROMID_Upper, Luint32 u32ROMID_Lower)
void vPWRNODE_BATTEMP_MEM__Set_UserData (Luint16 u16Index, Luint16 UserIndex, Luint8 u8BusID, Luint8 u8Resolution)
void vPWRNODE_BAATTEMP_ETH__Transmit (E_NET__PACKET_T ePacketType)
void vPWRNODE_BAATTEMP_ETH__Transmit_ROMID (Luint32 u32Index)
void vPWRNODE_NODETEMP__Init (void)
void vPWRNODE_NODETEMP__Process (void)
Lfloat32 f32PWRNODE_NODETEMP__Get_DegC (void)
Luint32 u32PWRNODE_NODETEMP__Get_FaultFlags (void)
void vPWRNODE_NODEPRESS__Init (void)
void vPWRNODE_NODEPRESS__Process (void)
Lfloat32 f32PWRNODE_NODEPRESS__Get_Pressure_Bar (void)
void vPWR_PVPRESS__Init (void)
void vPWR_PVPRESS__Process (void)
void vPWR_PVPRESS__100MS_ISR (void)
void vPWR_PVPRESS__Enable (Luint32 u32Value)
void vPWR_COOLING__Init (void)
void vPWR_COOLING__Process (void)
void vPWR_COOLING_EDDY__100MS_ISR (void)
void vPWR_COOLING_HOVER__100MS_ISR (void)
void vPWR_COOLING__100MS_ISR (void)
void vPWR_COOLING__Enable (Luint32 u32Value)
void vPWR_COOLING__Solennoid_TurnAllOff (void)
void vPWR_COOLING__Solennoid_TurnOff (Luint32 u32PinNumber)
void vPWR_COOLING__Solennoid_TurnOn (Luint32 u32PinNumber)
void vPWR_COOLING_ETH__Transmit (E_NET__PACKET_T ePacketType)
void vPWR_COOLING_HOVER__Init (void)
void vPWR_COOLING_HOVER__Process (void)
void vPWR_COOLING_EDDY__Init (void)
void vPWR_COOLING_EDDY__Process (void)
Detailed Description
Main header file for the power node core functions.
Author
Lachlan Grogan
Copyright
rLoop Inc.
SafeTool FileID:
LCCM653R0.FILE.001
Function Documentation
Lfloat32 f32PWRNODE_BMS__Cell_Get_HighestVoltage (void)
Lfloat32 f32PWRNODE_BMS__Cell_Get_LowestVoltage (void)
Lfloat32 f32PWRNODE_BMS__Get_PackVoltage (void)
Lfloat32 f32PWRNODE_NODEPRESS__Get_Pressure_Bar (void)
Lfloat32 f32PWRNODE_NODETEMP__Get_DegC (void)
Lfloat32 f32PWRNODE_PICOMMS_MSG__NodeTemp__Get_DegC (void)
Lint16 s16PWRNODE_BATTEMP_MEM__Load (void)
Luint16 u16PWRNODE_BATTTEMP_MEM__Get_NumSensors (void)
Luint32 u32PWRNODE_BMS__Get_VoltsUpdateCount (void)
Luint32 u32PWRNODE_DC__Get_TimerCount (void)
Luint32 u32PWRNODE_NODETEMP__Get_FaultFlags (void)
Luint32 u32PWRNODE_PICOMMS_MSG__NodeTemp__Get_FaulFlags (void)
Luint32 u32PWRNODE_PICOMMS_MSG__PodSafe__Get_Watchdog_Value (void)
Luint8 u8PWR_BATTTEMP__Is_Avail (void)
Luint8 u8PWRNODE_BMS__Balance_IsBusy (void)
Luint8 u8PWRNODE_CHG__Is_Busy (void)
Referenced by vPWRNODE_SM__Process().
Luint8 u8PWRNODE_NET__Is_LinkUp (void)
void vPWR_BMS_ETH__Init (void)
void vPWR_BMS_ETH__Transmit (E_NET__PACKET_T ePacketType)
void vPWR_CHARGER_ETH__Init (void)
void vPWR_CHARGER_ETH__Transmit (E_NET__PACKET_T ePacketType)
void vPWR_COOLING__100MS_ISR (void)
Referenced by vPWRNODE__RTI_100MS_ISR().
void vPWR_COOLING__Enable (Luint32 u32Value)
void vPWR_COOLING__Init (void)
Referenced by vPWRNODE__Process().
void vPWR_COOLING__Process (void)
Referenced by vPWRNODE__Process().
void vPWR_COOLING__Solennoid_TurnAllOff (void)
void vPWR_COOLING__Solennoid_TurnOff (Luint32 u32PinNumber)
void vPWR_COOLING__Solennoid_TurnOn (Luint32 u32PinNumber)
void vPWR_COOLING_EDDY__100MS_ISR (void)
Referenced by vPWRNODE__RTI_100MS_ISR().
void vPWR_COOLING_EDDY__Init (void)
void vPWR_COOLING_EDDY__Process (void)
void vPWR_COOLING_ETH__Transmit (E_NET__PACKET_T ePacketType)
void vPWR_COOLING_HOVER__100MS_ISR (void)
Referenced by vPWRNODE__RTI_100MS_ISR().
void vPWR_COOLING_HOVER__Init (void)
void vPWR_COOLING_HOVER__Process (void)
void vPWR_PVPRESS__100MS_ISR (void)
Referenced by vPWRNODE__RTI_100MS_ISR().
void vPWR_PVPRESS__Enable (Luint32 u32Value)
void vPWR_PVPRESS__Init (void)
Referenced by vPWRNODE__Process().
void vPWR_PVPRESS__Process (void)
Referenced by vPWRNODE__Process().
void vPWRNODE_BAATTEMP_ETH__Transmit (E_NET__PACKET_T ePacketType)
void vPWRNODE_BAATTEMP_ETH__Transmit_ROMID (Luint32 u32Index)
void vPWRNODE_BATTEMP_MEM__Set_ROMID (Luint16 u16Index, Luint32 u32ROMID_Upper, Luint32 u32ROMID_Lower)
void vPWRNODE_BATTEMP_MEM__Set_UserData (Luint16 u16Index, Luint16 UserIndex, Luint8 u8BusID, Luint8 u8Resolution)
void vPWRNODE_BATTTEMP__Init (void)
Referenced by vPWRNODE__Process().
void vPWRNODE_BATTTEMP__Process (void)
Referenced by vPWRNODE__Process().
void vPWRNODE_BATTTEMP_MEM__Init (void)
void vPWRNODE_BATTTEMP_MEM__Process (void)
void vPWRNODE_BMS__Balance_Manual (Luint8 u8CellIndex, Luint8 u8Enable)
void vPWRNODE_BMS__Balance_Start (void)
void vPWRNODE_BMS__Balance_Stop (void)
void vPWRNODE_BMS__Init (void)
Referenced by vPWRNODE__Process().
void vPWRNODE_BMS__Process (void)
Referenced by vPWRNODE__Process().
void vPWRNODE_CHG__Abort (void)
Referenced by vPWRNODE_SM__Process().
void vPWRNODE_CHG__Init (void)
Referenced by vPWRNODE__Process().
void vPWRNODE_CHG__Process (void)
Referenced by vPWRNODE__Process().
void vPWRNODE_CHG__Start (void)
Referenced by vPWRNODE_SM__Process().
void vPWRNODE_CHG_IV__Init (void)
void vPWRNODE_CHG_IV__Process (void)
void vPWRNODE_CHG_RELAY__Init (void)
void vPWRNODE_CHG_RELAY__Off (void)
void vPWRNODE_CHG_RELAY__On (void)
void vPWRNODE_CHG_RELAY__Process (void)
void vPWRNODE_DC__100MS_ISR (void)
Referenced by vPWRNODE__RTI_100MS_ISR().
void vPWRNODE_DC__Init (void)
Referenced by vPWRNODE__Process().
void vPWRNODE_DC__Latch (Luint32 u32Key)
void vPWRNODE_DC__Pet_GS_Message (Luint32 u32Key)
void vPWRNODE_DC__Pod_Safe_Go (void)
void vPWRNODE_DC__Pod_Safe_Unlock (Luint32 u32UnlockKey)
void vPWRNODE_DC__Process (void)
Referenced by vPWRNODE__Process().
void vPWRNODE_GHG__Start_ManualBalance (void)
void vPWRNODE_GHG__Stop_ManualBalance (void)
void vPWRNODE_NET__10MS_ISR (void)
Referenced by vPWRNODE__RTI_10MS_ISR().
void vPWRNODE_NET__Init (void)
Referenced by vPWRNODE__Process().
void vPWRNODE_NET__Process (void)
Referenced by vPWRNODE__Process().
void vPWRNODE_NET_RX__RxSafeUDP (Luint8 * pu8Payload, Luint16 u16PayloadLength, Luint16 ePacketType, Luint16 u16DestPort, Luint16 u16Fault)
void vPWRNODE_NET_RX__RxUDP (Luint8 * pu8Buffer, Luint16 u16Length, Luint16 u16DestPort)
void vPWRNODE_NET_TX__10MS_ISR (void)
void vPWRNODE_NET_TX__Init (void)
void vPWRNODE_NET_TX__Process (void)
void vPWRNODE_NODEPRESS__Init (void)
Referenced by vPWRNODE__Process().
void vPWRNODE_NODEPRESS__Process (void)
Referenced by vPWRNODE__Process().
void vPWRNODE_NODETEMP__Init (void)
Referenced by vPWRNODE__Process().
void vPWRNODE_NODETEMP__Process (void)
Referenced by vPWRNODE__Process().
void vPWRNODE_PICOMMS__100MS_ISR (void)
Referenced by vPWRNODE__RTI_100MS_ISR().
void vPWRNODE_PICOMMS__Init (void)
Referenced by vPWRNODE__Process().
void vPWRNODE_PICOMMS__Process (void)
Referenced by vPWRNODE__Process().
void vPWRNODE_PICOMMS_MSG__PodSafe__Execute (void)
void vPWRNODE_PICOMMS_MSG__PodSafe__UnlockKey (Luint32 u32Key)