(C Code, RLOOP, Power Node Core): REPRESS/pwr__repress.c File Reference
pwr__repress.c File Reference
#include "../power_core.h"
Functions
void vPWR_PVPRESS__Init (void)
ToDo.
void vPWR_PVPRESS__Process (void)
ToDo.
void vPWR_PVPRESS__Enable (Luint32 u32Value)
ToDo.
void vPWR_PVPRESS__100MS_ISR (void)
ToDo.
Variables
struct _strPWRNODE sPWRNODE
Function Documentation
void vPWR_PVPRESS__100MS_ISR (void)
ToDo.
SafeTool Function MD5:
1D6024B6A44D7FB132FF6F6F7D4C319A
SafeTool Function ID:
LCCM653R0.FILE.035.FUNC.004
References sPWRNODE, _strPWRNODE::sRePress, and _strPWRNODE::u32100MS_Count.
Referenced by vPWRNODE__RTI_100MS_ISR().
void vPWR_PVPRESS__Enable (Luint32 u32Value)
ToDo.
Parameters
[in] u32Value ## Desc ##
SafeTool Function MD5:
F3BF77523E1E4FDE210AE4F5C4CAC9E9
SafeTool Function ID:
LCCM653R0.FILE.035.FUNC.003
References _strPWRNODE::eState, REPRESS_STATE__IDLE, REPRESS_STATE__RESET, sPWRNODE, and _strPWRNODE::sRePress.
Referenced by vPWRNODE_NET_RX__RxSafeUDP().
void vPWR_PVPRESS__Init (void)
ToDo.
SafeTool Function MD5:
DA61463302D1706E2EFE0AD5D80540B0
SafeTool Function ID:
LCCM653R0.FILE.035.FUNC.001
References _strPWRNODE::eSolState, _strPWRNODE::eState, _strPWRNODE::f32Press, REPRESS_SOL_STATE__OFF, REPRESS_STATE__RESET, sPWRNODE, _strPWRNODE::sRePress, and _strPWRNODE::u32100MS_Count.
Referenced by vPWRNODE__Process().
void vPWR_PVPRESS__Process (void)
ToDo.
SafeTool Function MD5:
4BDFBA2F957461A134F3C2F8E3B49BE2
SafeTool Function ID:
LCCM653R0.FILE.035.FUNC.002
References _strPWRNODE::eSolState, _strPWRNODE::eState, _strPWRNODE::f32Press, f32PWRNODE_NODEPRESS__Get_Pressure_Bar(), REPRESS_SOL_STATE__OFF, REPRESS_SOL_STATE__ON, REPRESS_STATE__CHECK_PRESS_SNSR, REPRESS_STATE__FAULT, REPRESS_STATE__IDLE, REPRESS_STATE__PROCESS_PRESS, REPRESS_STATE__RESET, sPWRNODE, and _strPWRNODE::sRePress.
Referenced by vPWRNODE__Process().