(C Code, MULTICORE, DS2482 1-Wire Driver): DS2482S__CRC
DS2482S__CRC
MULTICORE » DS2482S
Functions
static Luint8 u8DS2482S_CRC__CRC8_Calc (const Luint8 *pu8Data, Luint8 u8Length)
Calc the CRC using math methods.
Luint8 u8DS2482S_CRC__CRC8 (const Luint8 *pu8Data, Luint8 u8Length)
Calculate the CRC8 using avail methods.
Detailed Description
Function Documentation
Luint8 u8DS2482S_CRC__CRC8 (const Luint8 * pu8Data, Luint8 u8Length)
Calculate the CRC8 using avail methods.
Parameters
[in] u8Length Length of data to CRC
[in] *pu8Data Pointer to data array
Returns
The CRC8
SafeTool Function MD5:
E0B983F4A5D63637ED7D40E0B7804FF6
SafeTool Function ID:
LCCM641R0.FILE.007.FUNC.001
References u8DS2482S_CRC__CRC8_Calc().
Referenced by s16DS2482S_SEARCH__Search().
Luint8 u8DS2482S_CRC__CRC8_Calc (const Luint8 * pu8Data, Luint8 u8Length) static
Calc the CRC using math methods.
Parameters
[in] u8Length Length of data to CRC
[in] *pu8Data Pointer to data array
Returns
The CRC8
SafeTool Function MD5:
B9C82458D520779957DC9DD5FD23A236
SafeTool Function ID:
LCCM641R0.FILE.007.FUNC.003
Referenced by u8DS2482S_CRC__CRC8().